wesnoth/wesnoth

SConstruct, src/SConscript
This option cleans up some of the compatibility path code from the
1.12 release. After this commit:
- boost::filesystem becomes a hard dependency, for scons
- boost::locale is a soft dependency, a build flag "libintl" allows to swap boost::locale out for libintl.
- The libintl option cannot be used when building for windows
This decision is made based on gfgtdf's comments in this forum thread:
http://forums.wesnoth.org/viewtopic.php?f=10&t=41196
and the fact that the boost filesystem code currently assumes the presence of boost locale, for windows.
It also incorporates techtonik's patch:
#347
It is left to backport the same patch for cmake, but the libintl code there
seems messed up already...
=> scons: remove boostfilesystem build option, replace with "libintl"

src/game_events/manager.cpp, src/game_events/manager.hpp, src/game_events/menu_item.cpp, src/game_events/menu_item.hpp, src/game_events/wmi_container.cpp, src/game_events/wmi_container.hpp, src/scripting/game_lua_kernel.cpp
Don't merge yet, needs more testing...
this commit causes wml menu items to have their events registered
not during construction but only when "init_handler" is called.
it refactors the wmi_container object to do this when it
constructs new items via the [set_menu_item] path.
this is necessary because the items might be constructed before
the event queue even exists, and we want them to be able to
persist and be reactivated when a new campaign scenario starts.
more testing is necessary to determine if all code paths, including
carryover and reloading, are still working after this commit, and
the earlier commit 6fc1ac1bb224cddec5ccbb7f7865b69b1b093a01
See also discussion of bug #23115.
=> maybe fix 23115

src/gui/dialogs/title_screen.cpp
Removes the static const from wrapper methods.
Take binding function as copy in register_hotkey.
Fixes bug #18926
=> Changes registration of hotkeys for tips on titlescreen.

src/game_events/action_wml.cpp
This eliminates the need for image=misc/blank-hex.png
NOTE: Currently, you CAN just leave out the image= key when you use [message], and this
produces the same behavior, but wmllint complains about that, so there must have been some
reason to always use an image= key.
Shadowm suggested this method was a better solution than having it directly in gui2::twml_message.
=> Allow [message] image= to have 'none' as a value

data/tools/wmllint
Updates wmllint to cease adding usage= and border_size= keys to map files, as the editor no longer writes them as of 1.13.x.
PR-ing this since I don't know python and someone who does should probably look this over. I've tested it, and it appears to work, but it would be good to be sure to avoid yet another fixup commit.
=> Remove checks for usage= and border_size= in map files

data/lua/wml-tags.lua
used as 
```
[sync_variable]
name=my_variable
[/sync_variable]
```
it sets my_variable to the same value as on all clients, it uses the value from the currently active side.
The main intention is to replace needs_select=yes for wml menu items somewhen because needs_select is slightly bugged: needs_select=yes causes the event to be fired again when the wml menu item is triggered so the select event it fired 2 times in total on the currently active client.
The most common usecase of needs_select are wml menus like this:
```
[event]
name=start
[set_menu_item]
id=move_unit
description= _ "Move!"
image=buttons/WML-custom.png
needs_select=yes
[command]
{MOVE_UNIT x,y=$moving_unit_x,$moving_unit_y $x1 $y1}
{VARIABLE moving_unit_x $x1}
{VARIABLE moving_unit_y $y1}
[/command]
[/set_menu_item] …
```
=> add [sync_variable] tag

data/campaigns/Northern_Rebirth/scenarios/05a_The_Pursuit.cfg
This commit makes some minor (non-semantic) textual edits in the
mainline campaign "Northern Rebirth"’s scenario 5a, "The
Pursuit", mostly miscellaneous edits for correctness or clarity.
As far as edits that might need explanation:
- The change of “Lich Lord(s)” to “Lich-Lord(s)” matches
usage in the mainline campaign "The Rise of Wesnoth".
- The change of “the land of the dead” to “the Land of the
Dead” matches usage in the mainline campaign "Delfador’s
Memoirs".
- The “I am Lord Abhai” change is because “Lord Abhai” isn’t a
*name* exactly.
r? @Vultraz
=> NR S5a: Minor textual edits

src/display.cpp, src/display.hpp, src/widgets/slider.cpp, src/widgets/slider.hpp
This commit causes sliders to attract focus properly when their
grips are clicked on, and to respond to left and right arrow
presses again. It partly reverts two earlier commits that
affected this functionality.
cf84e1d8aae84b76e7e9adc15847089bdc940632
49614599fa5211e0bc3fdba43c6255509da66022
It causes the zoom slider to behave slightly badly, because it
does not lose focus when the user clicks elsewhere on the map.
But this bug should be fixed at the source and not by disabling
wanted functionality for all sliders.
=> fix bug #22984: sliders not adjustable with arrow keys

src/display.cpp, src/display.hpp, src/widgets/slider.cpp, src/widgets/slider.hpp
=> Fixup sliders 1.12

src/mp_game_settings.cpp
This appears to fix tutorial scenario two. Bug #23366.
I'm not sure if this should be related to loading the tutorial at
all though, so it might not be the real cause of the bug.
=> change mp_game_settings to default experience modifier to 100

src/image_modifications.cpp, src/image_modifications.hpp, src/sdl/utils.cpp, src/sdl/utils.hpp
This PR adds two new ImagePath functions.
The first one is called **~SEPIA**, and adds a sepia tone to the image. When applied to the portrait of an Elvish Captain, for example, this is the result:
The second one is called **~NEG** (short for *negative*), and makes an image negative. When applied to the same portrait, this is the result:
None of these two functions accepts additional arguments.
=> New ImagePathWML functions: ~SEPIA() and ~NEG()

src/game_initialization/configure_engine.cpp, src/game_initialization/configure_engine.hpp, src/game_initialization/connect_engine.cpp, src/game_initialization/connect_engine.hpp, src/game_initialization/flg_manager.cpp, src/game_initialization/flg_manager.hpp, src/game_initialization/multiplayer_configure.cpp, src/game_initialization/multiplayer_configure.hpp, src/game_preferences.cpp, src/game_preferences.hpp, src/mp_game_settings.cpp, src/mp_game_settings.hpp, src/tests/test_mp_connect.cpp
This PR makes "no mirror random" modifications as a core feature implemented in C++ and selected on the mp configure screen. It also adds "no ally mirror" mode, which is nice for team games.
It also switches us to use the Mersenne Twister rng instead of rand for all "resolve random" operations in the connect engine, e.g. random faction selection, and shuffling of sides.
=> Random faction mode

src/addon/manager_ui.cpp, src/addon/manager_ui.hpp, src/game_config_manager.cpp, src/game_initialization/lobby_reload_request_exception.hpp, src/game_initialization/multiplayer.cpp, src/game_initialization/multiplayer_lobby.cpp, src/game_initialization/multiplayer_lobby.hpp, src/mp_game_settings.cpp, src/mp_game_settings.hpp, src/saved_game.cpp, src/tests/gui/test_gui2.cpp
** Experimental **
A new feature: If one cannot join a game in the mp lobby because of missing addons, prompt the user to try to download those addons and whatever dependencies they have.
Four parts:
1.) Refactor some of the addon client code so that there is a simple "try to fetch and install this addon" function.
2.) In the game config manager, annotate certain top-level tags "era" and "modification" with "addon_id" attributes (generally, the addon folder name).
3.) In saved_game::expand_mp_events, when iterating over the mods and eras, also take note of their addon_id, and add these to a comma separated list in mp_game_settings, "addon_ids". Indirectly, this results that [multiplayer] tags now have an "addon_ids" attribute which becomes part of the server-side [game] children of …
=> automatically download needed addons in mp lobby

src/serialization/parser.cpp
previously they were serialized as "" which is the same as empty strings.
blank attributes are usually created when using operator[] on a a non-const config with an nonexsistent key. for example 
```
if(cfg["a"].to_bool()) {/*some code*/} 
```
might create a blank attribute value with key 'a' if cfg is non const.
=> don't write blank attribute values when serializing a config

src/actions/undo.cpp, src/ai/contexts.cpp, src/game_board.cpp, src/game_events/action_wml.cpp, src/menu_events.cpp, src/scripting/game_lua_kernel.cpp
persistent=no does not imply that the side does not have a recall list:
1) persisent=no did prevent units from this scenario to be carried over
to a next scenario but it did not prevent units from a previous scenario
to be carried over to this scenario.
2) [unit] in [side] and [unit] in action wml can give recall units to
nonpersistent sides.
3) The wiki does not mention that a side with persistent=no cannot have
recall units.
So i removed checks for [side]persistent= so that [unstore_unit] and
wesnoth.put_recall_unit can put units to the recall list and also tidied
up some other code that assumed sides with persistent=no to not have a
recall list.
=> allow putting units on recall list for nonpersistent sides

changelog, src/game_initialization/multiplayer_lobby.cpp
Only pop games off the list if the apply filter box is checked.
=> Bug Fix #23117: Invert breaks lobby filtering if Apply Filter is off.

data/lua/wml-tags.lua, src/scripting/game_lua_kernel.cpp
previously this was only possible by storing the unit and then unstoring
with advance=yes. Unstoring a unit can cause a lot of overhead if the
unit is complicated. so i added a way to do it without [unstore_unit]
=> add wesnoth.advane_unit lua function

src/gui/widgets/tree_view.hpp, src/gui/widgets/tree_view_node.cpp, src/gui/widgets/tree_view_node.hpp, src/scripting/lua_gui2.cpp, src/scripting/lua_gui2.hpp, src/scripting/lua_kernel_base.cpp
wesnoth.add_dialog_tree_value to add nodes to a tree_value
wesnoth.set_dialog_callback support for tree_views (triggers when the
selected node was changed)
wesnoth.get_dialog_value support for tree_views returns an array of
integers that describe the path to the currebntly selected node.
=> Enable tree_view gui2 widget for lua

src/game_initialization/create_engine.cpp
This reverts commit 61a8de3d946487abe3e1826a476666e23fd01053.
This fixes https://gna.org/bugs/?23399 but not in the way i'd like to have it fixed. still this should be merged before 1.13.0 release (onless teh bug is fixed otherwise)
=> Revert "don't reload config when selecing campaigns"

src/game_initialization/connect_engine.cpp, src/game_initialization/connect_engine.hpp, src/team.cpp
which causes them to be ignored by the "shuffle_sides" phase,
regardless of the heuristic used by the connect engine
=> add "disallow_shuffle" attribute to [side]

data/core/about.cfg
Hello, i'm Torsten Zühlsdorff. I'm taking care about the Wesnoth package at FreeBSD. Therefore i've added my contacts to the about.cfg file, so that FreeBSD user which wishes/problems/etc could contact me.
=> add FreeBSD packager to about.cfg

src/image_modifications.cpp, src/image_modifications.hpp, src/sdl/utils.cpp, src/sdl/utils.hpp
This PR adds a new ImagePath function, called **~SWAP()**.
This functions performs the channel swap operations that can be found in several image manipulation programs. It accepts three or four arguments (one for each RGBA channel of the image), and each of them can be one of _"red"_, _"green"_, _"blue"_ and _"alpha"_.
The attached image is an example of the effects that can be achieved by using this function.
* Top-left corner: original image `(portraits/elves/captain.png)`
* Top-middle: `~SWAP(red,blue,green)`
* Top-right: `~SWAP(blue,green,red)`
* Bottom-left: `~SWAP(blue,red,green)`
* Bottom-middle: `~SWAP(green,red,blue)`
* Bottom-right: `~SWAP(green,blue,red)`
=> ImagePathWML: added ~SWAP() function

src/game_initialization/configure_engine.cpp, src/game_initialization/configure_engine.hpp, src/game_initialization/connect_engine.cpp, src/game_initialization/mp_game_utils.cpp, src/game_initialization/multiplayer_configure.cpp, src/game_initialization/multiplayer_configure.hpp
When using force_lock_settings=yes that game now not only forces
use_map_settings to on, instead if doest show these options and doesn't
thouch those attributes in the scenario.
This implements http://gna.org/bugs/?23037
and might also fix some bugs related to spmp patch ( specially
https://gna.org/bugs/?23509) since force_lock_settings default to yes
for campaigns.
=> disable most mp_configure settings when force_lock_settings=yes

changelog, data/gui/default/window/campaign_difficulty.cfg, players_changelog, src/game_initialization/create_engine.cpp, src/game_launcher.cpp, src/game_preferences.cpp, src/game_preferences.hpp, src/gui/dialogs/campaign_difficulty.cpp, src/gui/dialogs/campaign_difficulty.hpp, src/savegame.cpp, src/tests/gui/test_gui2.cpp
Currently, users can see which campaigns they completed, but they don't see on which difficulty levels they were completed. This feature was [requested](http://forums.wesnoth.org/viewtopic.php?f=12&t=19757) [multiple](http://forums.wesnoth.org/viewtopic.php?f=12&t=29387) [times](http://forums.wesnoth.org/viewtopic.php?f=12&t=36061) on the forums.
=> Show on which difficulty levels a campaign was completed

src/game_events/menu_item.cpp, src/game_events/menu_item.hpp, src/game_events/wmi_container.hpp, src/game_state.cpp, src/game_state.hpp, src/hotkey_handler_sp.cpp
Unested.
Allows to add 'unsynced' wml menu hotkeys which are not sended to other
players and are also clickable off-turn.
This can for example used for help menus and similar.
=> Add synced=yes(default)/no to [set_menu_item]

changelog, data/campaigns/Delfadors_Memoirs/scenarios/19_Showdown_in_the_Northern_Swamp.cfg, data/core/about.cfg, players_changelog
This change to DM S19 adds a defeat condition for losing the last undead veteran before Iliah-Malal is destroyed.  This fixes bug #23668.
=> DM S19: Add defeat condition for losing last undead (bug #23668)

changelog, data/core/about.cfg, src/gui/dialogs/editor_generate_map.cpp
It just modifies `pre_show()` to call `do_generator_selected()` after selecting the last map generator used in the list. It would not be called even if the callback was set before selecting the row with `list.select_row()`.
=> Fix bug #23711 about selecting last map generator used in editor

data/tools/wesnoth/wmlgrammar.py, data/tools/wesnoth/wmliterator.py, data/tools/wesnoth/wmltools.py
Small things I noticed while trying to read and understand the code.
=> Various Python cleanup in wmltools-related code

changelog, data/campaigns/The_South_Guard/utils/sg_story.cfg
Changed Deoran to be the grandson of HttT Haldiel, instead of son,
because the 2 campaigns has 87 years between them.
=> Make Deoran the grandson of Haldiel

data/campaigns/The_South_Guard/scenarios/03_A_Desparate_Errand.cfg, data/campaigns/The_South_Guard/scenarios/06a_Tidings_Good_and_Ill.cfg, data/campaigns/The_South_Guard/scenarios/06b_The_Long_March.cfg, data/campaigns/The_South_Guard/scenarios/08a_Return_to_Kerlath.cfg
Increased the difficulties of scenario 3 and scenario 8a in the South
Guard;
Fixed the objective display after killing the naga queen in scenario 6a
=> Tweaked Elf Path of The South Guard

src/serialization/preprocessor.cpp
This is the first bullet item under [this wiki section](http://wiki.wesnoth.org/NotSoEasyCoding#Improve_WML_error_reporting). Planning on tackling the rest of them shortly.
=> adding location of macro definition to preprocessor argument error message

data/campaigns/The_South_Guard/scenarios/05_Choice_In_The_Fog.cfg, data/campaigns/The_South_Guard/scenarios/09a_Vengeance.cfg, data/campaigns/The_South_Guard/utils/sg_story.cfg
1. Swap option positions to make Elf Path the default choice;
2. Made it slightly less obvious that Epilogues are outdated reference
to Eastern Invasion
3. Added a delay at victory in 9a, to make it less abrupt
=> South Guard text change

data/tools/wmllint
I'm currently working through `wmllint` to see what simple improvements can be made before doing some more involved refactoring. I plan on adding a few more commits to this PR, but I figured submitting it early will make it easier to review in chunks (especially some of the more rote changes, such as changing `for i in xrange(len(foo))` to `for f in foo` or `for i, f in enumerate(foo)`).
=> Improve idiomaticity of wmllint

src/synced_context.hpp
The error was that `server_choice` is a class with virtual functions but no virtual destructor.
=> Fix a compilation error with XCode Version 6.2 on OSX 10.9

.travis.yml
`apt-get -qq` is completely quiet. If `apt-get` takes more than 10
minutes to execute, nothing will be outputted for 10 minutes, and travis
will kill the build. Using `travis_wait` ensures the commands will not be
killed for 20 minutes. See [the documentation] for details.
[the documentation]: http://docs.travis-ci.com/user/build-timeouts/#Build-times-out-because-no-output-was-received)
=> Prefix `apt-get -qq  with `travis_wait`

changelog, data/core/about.cfg, src/attack_prediction_display.cpp, src/build_info.cpp, src/desktop/clipboard.cpp, src/filesystem_common.cpp, src/floating_label.cpp, src/loadscreen.cpp, src/sdl/window.cpp, src/sdl/window.hpp, src/storyscreen/render.cpp, src/text.hpp
This does the bare minimum to get the game compiling and running again with SDL 2. It fixes all of the compile errors, adds a missing seek operation to the SDL_RWops. The missing seek operation caused a NULL pointer dereference during game start.
=> Make the game compile with SDL2.

src/desktop/open.cpp, src/global.hpp, src/sdl/utils.cpp, src/sdl/utils.hpp, src/tests/test_config.cpp, src/unit_drawer.cpp, src/video.cpp, src/widgets/menu.cpp
This fixes all compile warnings by performing the correct typecasts or by modifying types to be suitable. The code has been compiled with and without SDL2 enabled to make sure there are no regressions.
=> Fix all compile warnings when SDL2 is enabled

src/display.cpp
SDL2 has issues with overlapping surfaces when blitting, it seems to trigger an internal bug in SDL2. This causes the blitted surface to be incorrectly filled, causing a graphics corruption. This introduces a workaround that does a copy of the original surface before blitting, thus avoiding the bug. This behaviour seems to only occur while scrolling so it's a reasonably rare occurence.
=> Fix the graphics corruption when scrolling with SDL2 enabled

CMakeLists.txt, cmake/FindSDL2.cmake, cmake/FindSDL2_image.cmake, cmake/FindSDL2_mixer.cmake, cmake/FindSDL2_net.cmake, cmake/FindSDL2_ttf.cmake, src/CMakeLists.txt, src/desktop/clipboard.cpp, src/sdl/window.hpp
This adds support for doing SDL2 builds with CMake, as well as the required modules to find SDL2 and its dependencies.
To enable:
`-DENABLE_SDL2=TRUE`
SDL2 is disabled by default.
I have also made sure that clipboard is properly enabled for SDL2, and remove a piece of dead code for the defunct ttexture class.
=> Add SDL2 support to CMake, advertise clipboard availabilty and remove a small piece of dead code

src/hotkey/hotkey_item.cpp
Added special handling for j and m characters, where their respective key codes do not match the j and m buttons on the keyboard.
This most likely means that they have come from Ctrl+Return/Enter keys, which resolves to Ctrl+j and Ctrl+m characters.
As a bonus, also corrected unexpected behaviour when attempting combinations such as Ctrl+: or Ctrl+F1. Previously they would resolve to Ctrl+` or Ctrl+@, at least in Windows.
=> Correct handling of Ctrl+Return/Enter hot-key.

changelog, data/campaigns/Dead_Water/units/Brawler.cfg, src/game_events/action_wml.cpp, src/unit_display.cpp
Many other places make use of a female_XXX key to specify differing text for a female unit, and at least one place in mainline requires differing text for a female unit in this context. It's a convenience mainly, but it also feels more consistent.
I've also updated Dead Water to make use of this feature in the code for the stun weapon special. There may be other places in campaigns that could make use of it.
=> Add female_text key to [animate_unit] and [unstore_unit]

data/core/about.cfg, src/campaign_server/campaign_server.cpp
As suggested here:
http://wiki.wesnoth.org/NotSoEasyCoding#Passphrase_hashing
Currently the hashing function is 10-iteration MD5, but should really be something like scrypt (best) or bcrypt (acceptable), but it means pulling in a dependency and Wesnoth already includes an MD5 utility.
=> Added password hashing to campaignd

src/widgets/textbox.cpp
This is a quick fix to get input working, but it's sadly not foolproof. The correct way to deal with this would be to use SDL_TextInputEvent events under SDL2 instead.
=> Quck fix for textbox input under SDL2

.gitignore, src/SDL_gpu/SDL_gpu/GL_common/SDL_gpu_GL_common.inl, src/SDL_gpu/SDL_gpu/GL_common/SDL_gpu_GL_matrix.c, src/SDL_gpu/SDL_gpu/SDL_gpu.h, src/gui/dialogs/label_settings.cpp
Can use static inline in Visual C++ 2015
Also add WindowsTImeout to .gitignore.
=> Minor Windows Updates

changelog, src/actions/attack.cpp, src/ai/simulated_actions.cpp, src/scripting/game_lua_kernel.cpp, src/unit.cpp
The first change (using `[modifications][advancement]` instead of `[modifications][advance]`) makes it possible to use the same macro (eg `{AMLA_DEFAULT}`) both for adding an advancement possibility to a unit type and for adding that an advancement to a specific placed unit. The implementation is designed to be backwards compatible.
The second change allows making AMLA possibilities mutually exclusive. There is currently no way to indicate to the player that this is the case though; it would be nice to have some indication so that the player knows that certain choices will be eliminated by the choice they've made. However, I think that's a separate issue (in fact, it already affects 1.12 if you use strict_amla=no).
=> Two AMLA changes

projectfiles/Xcode/Wesnoth.xcodeproj/project.pbxproj
You still need to build them manually first by running 'scons translations' in the repo root dir.
=> XCode: Copy translations to target if they have been built

src/filesystem_boost.cpp
This allows ./wesnoth to work out of the box on OS X: it will use the git checkout as the data directory.
=> Fix get_exe_dir on OS X

src/CMakeLists.txt, src/SConscript, src/controller_base.hpp, src/display.cpp, src/events.cpp, src/quit_confirmation.cpp, src/quit_confirmation.hpp
when quitting (for example by clicking on the red cross in the corner) the
game now asks for a confirmation, if there is currently a (re-)play or
the editor running.
=> show confirmation dialog when quitting

changelog, src/unit_types.cpp
This introduces a way for custom terrains or damage types to be patched into pre-existing movetypes; previously the only way (as far as I know) to get this sort of effect would've been to use `[base_unit]` to make duplicates of all the unit types with the movetype you wanted to change. It uses the formula engine to allow you to set the new resistance/defence/cost base on the value of one or more resistances/defences/costs from the original movetype; for example, if you added a new "sonic" damage type, you could declare that the sonic resist level is equal to half the impact resist level for some movetypes.
Although the purpose is for adding custom damage type and terrain support to existing movetypes, this could in theory be used for any kind of tweaking of existing movetypes.
An example …
=> Movetype patching

src/terrain_builder.cpp
loc=x,y was previously undocumented so it's unlikeley that someone used it.
loc=4,2 had the same effect as x,y=4,2
=> remove support for [terrain_graphics][tile]loc=x,y

src/actions/attack.cpp, src/game_config.cpp, src/game_config.hpp, src/unit_animation.cpp, src/unit_display.cpp, src/unit_display.hpp
This adds a customizable list of status sounds (poison, slow, petrify) to game_config, which are then played automatically when the status is inflicted in combat (or by anything which goes through unit_attack()).
This fixes the long-standing problems with playing the status sounds from within attack animations not always working right (see bug #23024), and also makes the sounds customizable from game_config.cfg.
For now this only includes the engine-side changes. If this is deemed ok to merge, I'll add commits for changelog entries, the game_config.cfg additions (not needed to test; the same defaults are hard-coded) and removal of the sounds from mainline animations.
=> Fix problems with animation-based status sounds

src/editor/map/context_manager.cpp
When a map is generated, the labels for the player starting locations are correctly set. However, generating another map (or even loading a map and then generating a new one) results in the old labels remaining even after the new map has been generated and displayed.
Issue appears to be that the reset labels flag is not being set after a map generation. This change sets the reset labels flag and the subsequent perform_refresh() function then includes a reset of the map labels.
=> Resolve Bug #20036

CMakeLists.txt
This changes the ordering of the compile time options so the options
comes before any before any flags or checks that may depend on them.
=> Change the ordering of the CMakeLists so options comes first.

src/sdl/alpha.cpp
alpha.cpp was apparently written as a compatibility wrapper for SDL2, as SDL_SetAlpha() has been replaced with other functions in SDL2. As it currently stands, it neglects to set the alpha blend mode which is now required when in SDL2.
A quick check of the code indicates that in most places where SDL_SetAlpha() is called, the alpha parameter is only set as SDL_ALPHA_OPAQUE, or the flag input parameter does not include SDL_SRCALPHA. So in either case there is no alpha blending anyway and so this omission didn't make a difference.
However, alpha blending *is* used in fill_rect_alpha of rect.cpp. This is most noticeable in dialogues with sorted lists, such as the hot-key bindings in the preferences, where the background colour of the headings turns opaque white instead of the alpha-blended …
=> Correct Surface Alpha Blending in SDL2

changelog, data/lua/wml-tags.lua, data/lua/wml-utils.lua, data/test/macros/wml_unit_test_macros.cfg, data/test/scenarios/break_replay_with_lua_random.cfg, data/test/scenarios/characterize_pathfinding.cfg, data/test/scenarios/conditionals.cfg, data/test/scenarios/facing.cfg, data/test/scenarios/feeding.cfg, data/test/scenarios/filter_vision.cfg, data/test/scenarios/has_ally.cfg, data/test/scenarios/interrupts.cfg, data/test/scenarios/prestart_settings.cfg, data/test/scenarios/recruit_facing.cfg, data/test/scenarios/sighted_events.cfg, data/test/scenarios/test_check_victory.cfg, data/test/scenarios/test_dofile.cfg, data/test/scenarios/test_end_turn.cfg, data/test/scenarios/test_grunt_tod_damage.cfg, data/test/scenarios/test_lua_wml.cfg, data/test/scenarios/test_menu_items.cfg, data/test/scenarios/test_move.cfg, data/test/scenarios/test_move_unit.cfg, data/test/scenarios/test_role_types.cfg, data/test/scenarios/test_unit_map.cfg, data/test/scenarios/test_victory_attacks.cfg, wml_test_schedule
This commit adds three new control flow structure tags to WML: [for], [repeat], and [foreach].
The [for] tag is a general range-for loop, with special support for the common case of running over an array. It can be used as a drop-in substitute for the {FOREACH}/{NEXT} macros.
The [repeat] tag is a drop-in substitute for the {REPEAT} macro, with the added bonus that it doesn't break down if nested.
The [foreach] tag is an opaque foreach loop. It disallows adding or removing elements during iteration (though the contents of elements can be changed). If you need to add or remove elements, you can use [for] instead.
=> Enhanced looping tags

src/cursor.cpp, src/floating_label.cpp, src/halo.cpp, src/sdl/utils.cpp, src/sdl/utils.hpp
This commit introduces a new function, sdl_copy_portion that should be
used when copying portions of the screen area for later copying back
onto the screen area. The function does a copy without alpha blending,
thus emulating the functionality that SDL1.2 provides.
=> Bugfix #23820 - Fix alpha blending under SDL2

data/advanced_preferences.cfg, src/cursor.cpp, src/cursor.hpp, src/display.cpp, src/gui/auxiliary/event/handler.cpp
This fixes bug #18112 and re-enables colour cursors on OSX
=> Use native colour cursors

data/campaigns/An_Orcish_Incursion/_main.cfg, data/campaigns/Dead_Water/_main.cfg, data/campaigns/Delfadors_Memoirs/_main.cfg, data/campaigns/Descent_Into_Darkness/_main.cfg, data/campaigns/Eastern_Invasion/_main.cfg, data/campaigns/Heir_To_The_Throne/_main.cfg, data/campaigns/Legend_of_Wesmere/_main.cfg, data/campaigns/Liberty/_main.cfg, data/campaigns/Northern_Rebirth/_main.cfg, data/campaigns/Sceptre_of_Fire/_main.cfg, data/campaigns/Son_Of_The_Black_Eye/_main.cfg, data/campaigns/The_Hammer_of_Thursagan/_main.cfg, data/campaigns/The_Rise_Of_Wesnoth/_main.cfg, data/campaigns/The_South_Guard/_main.cfg, data/campaigns/Two_Brothers/_main.cfg, data/campaigns/Under_the_Burning_Suns/_main.cfg, data/core/macros/scenario-utils.cfg, data/gui/default/window/campaign_difficulty.cfg, src/game_initialization/create_engine.cpp, src/gui/dialogs/campaign_difficulty.cpp, src/gui/dialogs/campaign_difficulty.hpp, src/savegame.cpp, src/tests/gui/test_gui2.cpp
This replaces the current difficulties/difficulty_descriptions syntax with a new one using a [difficulty] tag with the following syntax
```
[difficulty]
define=
image=
label=
description=
default=
[/difficulty]
```
The old syntax is still completely supported and is translated to the new syntax at runtime.
Note that the old format doesn't have a deprecation warning right now, since I'm not sure where best to display it.
=> New syntax for campaign difficulty.

data/lua/helper.lua, src/scripting/lua_common.cpp
This patch adds metamethods for the vconfig userdata to allow you to iterate over them just as if they were a plain WML table. It also adds a couple of config utility functions to the helper module.
=> Lua vconfig iteration

data/lua/wml-tags.lua, src/scripting/game_lua_kernel.cpp, src/scripting/game_lua_kernel.hpp, src/scripting/lua_race.cpp, src/scripting/lua_unit_type.cpp
The commit messages are pretty self-explanatory. This allows you to call functions involving units using the syntax `u:function(args)` instead of `wesnoth.function(u, args)` (the function names are also different in most cases, omitting the word "unit").
=> Lua API changes (mainly relating to units)

src/dialogs.cpp, src/game_events/action_wml.cpp, src/game_initialization/multiplayer_lobby.cpp, src/saved_game.cpp
This has an advantage over the map key behavior, where the contents of the map
file were preprocessed and written to savefiles.
=> Add [replace_map] file= which will load the specified map at runtime

src/formula_string_utils.cpp
This breaks less existing strings and wasn't as complicated to implement as I had initially thought it would be.
=> Make closing | mandatory in $var?default| syntax

src/formula_string_utils.cpp
MSVC debug mode complains that var_end cannot be dereferenced if it hits the end of the string.
=> Ensure var_end is not beyond res.end()

src/carryover.cpp, src/carryover.hpp, src/scripting/game_lua_kernel.cpp, src/scripting/game_lua_kernel.hpp, src/team.cpp, src/team.hpp
http://gna.org/bugs/?23490
This makes it possible to store variables inside the side with the lua
functions get/set_side_variable. These variables are carried over along
other side specific data(units, gold)
It is currently not possible to write these variables without lua.
There are some advantages over storing these variables in the normal variables as found out in the bugerport:
1) It not trivial to store this data asociated with the sides save-id in wml variables, mainly because sides side id might be unsiuted to act as a variablename since it miight contain spaces or other unsuitable characters.
2) by storing these variables inside the side cvarryover data the variables are automatically removed along with the side if the side is removed (for exampple becase they have persistent=no …
=> side specific variables.

scons/sdl.py
This clears warnings on Windows
https://github.com/wesnoth/wesnoth/pull/481#issue-104760195
=> scons/sdl.py: Escape backslashes on path substitution

data/campaigns/Legend_of_Wesmere/scenarios/chapter4/14_Human_Alliance.cfg
Verified in debug mode that the death of Galtrid is the only death missing from the losing conditions.  Rebuilt and verified death of Galtrid is listed in the objectives as a losing condition.
=> Added Death of Galtrid to losing conditions for the Human Alliance.

changelog, data/core/about.cfg, players_changelog, src/display_chat_manager.cpp, src/display_chat_manager.hpp, src/play_controller.cpp
In the game lobby you can tab-complete ANY nick, both from the lobby or from a match running. While playing you can only tab-complete ingame players and observers.
This patch works in the match, it helps answering whispers from people in lobby or in other games.
The nick will be added to a string (in the same way as observers already work) and get recalled with TAB key.
=> Tab-completion added for in-game whispers

src/game_initialization/multiplayer_create.cpp
Resolving bug #22133, stating Cancel Orders does not work when loading a MP game.
Modelled from the Cancel Orders functionality in the single-player Load Game, game_launcher::load_game() of game_launcher.cpp.
=> Resolve Bug #22133

src/server/game.cpp
In 1.11.x cycle, we moved all "client-side controller tweaks" to
be effected by the server, so that clients won't on their own
change the data they find in a level config at game start. This
had some benefits:
- Only host and server are ever modifying the level data
- Easier to keep observers and clients synced correctly
- Easier to change client behavior with server side patches
The server-sided tweaks happened at the following point in time:
1. Host clicks start game button, a [start] signal is sent to
server.
2. Server now checks the level config and tries to make sense of
it, making sure every side has an owner and such. Then it issues
controller change commands to all clients, making sure they match
its picture of what is going on.
3. Server passes the [start] signal on to the other …
=> fixup server controller tweaks, dont tweak host

data/core/terrain.cfg
Correct Desert Sands / Oasis help entry.
From what I can tell of show_terrain_description(), the oasis terrain help entry is meant to be combined with the desert terrain help entry. But it incorrectly shows just 'Desert Sands /' in the title - explicitly adding the editor_name seems to resolve this.
In contrast, the nearby rubble and crater terrain types don't have a editor_name presumably because they will re-use the name string, and these seem to work because they are stand-alone help entries.
=> Resolve Bug #23023

src/hotkey/hotkey_preferences_display.cpp
Some hotkeys (like the loadgame hotkey) are present in some, but not all hotkey scopes and teh hotkey preferences dialog was unable to handle that. One of the results was that it was not possible to assign the same hotkey to the loadgame hotkey and the loadmap hotkey, this commit attempts to fix that.
=> fix preferences dialog for loadgame hotkey

changelog, data/core/terrain.cfg, players_changelog, src/editor/map/context_manager.cpp, src/game_config_manager.cpp, src/global.hpp
Add a couple of bug fixes from master. I thought I'd be able to get the MP Load Game Cancel Orders fix into this as well but it looks like there was some rewriting of the load game dialogues for 1.13.x.
Also a couple of updates to get compilation working in MSVC14/2015 (adapted from changes already in master).
=> Bug Fixes from Master (1.12)

changelog, src/editor/editor_main.cpp
Bug report refers to a more thorough patch #3972 which seems to have never been accepted. All I'm trying to do here is add the file_exists check which fixes the hanging while minimising the changes needed.
(MSVC debug mode still fails due to a vector assertion failure (teams vector reference), which makes testing/debugging the editor difficult.)
If anyone feels like adding all the error messages/handling included from the patch, go right ahead.
=> Resolve Bug #20900

changelog, src/whiteboard/manager.cpp
Check IDs match before re-using an existing fake_unit. IDs can be different in the situation described by bug #20299, where the user selects the next unit while planning a move.
=> Resolve bug #20299

data/core/terrain.cfg, src/terrain.cpp
Reverts the previous change to the terrain.cfg and allows the terrain code to fall back to name if editor name is unavailable.
This is a proper fix and supersedes PR #537.
=> Properly correct the broken Desert Sands / Oasis help entry (bug #23023)

data/core/terrain.cfg, src/terrain.cpp
Reverts the previous change to the terrain.cfg and allows the terrain code to fall back to name if editor name is unavailable.
Back-ports PR #545 to 1.12 branch.
=> Properly correct the broken Desert Sands / Oasis help entry (bug #23023) [1.12]

changelog, src/whiteboard/manager.cpp
Back-port of PR #523 for 1.12 branch. Tested and seems to be working as it already is for master.
=> Resolve incorrect fake unit types (bug #20299) [1.12]

changelog, src/whiteboard/move.cpp
Attempt to work-around bug #18637, where planning moves on planned recruits results in a crash (because get_unit() is null when move::init() is called).
This isn't a comprehensive fix because clicking on a planned recruit will still result in the usual display feedback for planning a move. The difference here is that attempting to place a planned move will result in nothing happening when the mouse button is clicked (as opposed to the assertion failure or crash which happens currently). It is better than nothing, I believe, unless there are negative side-effects of which I am unaware of.
=> Work-around for planning moves on planned recruits (bug #18637)

src/saved_game.cpp, src/saved_game.hpp
[scenario], [multiplayer], [era], [modification] and [campaign] can now
contain [load_resource] tags that will load [resource]s that are
toplevel tags similar to [modification] whose child tags will be copied
into the scenario.
These are mainly intended to load resrouces like new wml tags or similar. This adresses https://gna.org/bugs/?22974 . This is a rather basic implementation and im not sure whether it  would be better to make it part of mp depcheck or similar. Spcially becasue this for example has no features like "require_resource" (whether all clients need the resource) yet which i sthink it still important.
=> add [resource] tag simlar to mp modifications.

changelog, src/actions/attack.cpp
[ref](https://gna.org/bugs/index.php?reload=1&func=detailitem&item_id=23108)
This commit moves the expected damage calculation from before the attack loop to during the perform_hit phase, since it's possible to abort from the attack loop prematurely via WML actions like teleporting a unit or changing its side. Now each strike adds its expected damage to the total expected.
I also refactored the replay validation into its own function to cut down on the complexity of perform_hit (still almost 200 lines).
=> Bug 23108: expected damage for aborted attacks

changelog, projectfiles/Xcode/Mac Sources/SDLMain.m, src/mouse_handler_base.cpp
Two patches:
**First:**
For OS X, control is the default modifier key that is used for contextual menus throughout the system
KMOD_CTRL will check for a control-click instead of a command click. This fixes [#15259](https://gna.org/bugs/?15259).
I’ve built and verified with this patch, and it works correctly. Native secondary-clicking (like two-finger clicking on a trackpad) still works, and is unaffected.
**Second:**
Delete two lines in SDLMain.m to fix an SDL2 crash. Tested successfully.
=> Fix SDL2 crash; update mouse_handler_base.cpp for OS X to look for ctrl-click instead of cmd-click

src/tests/main.cpp, src/tests/test_map_location.cpp, src/tests/test_mp_connect.cpp, src/tests/utils/auto_parameterized.hpp
The unit test part in boost has changed a few header files and
function signatures between previous versions and 1.60.0. These
changes adds a version check and two different versions of the
affected code, as well as introducing semicolons after the global text
fixtures (which doesn't appear to do harm) but otherwise requires more
version checks.
=> Fix bug #24234: Add Boost 1.60.0 support to unit tests

src/events.cpp, src/events.hpp, src/video.cpp, src/video.hpp
This adds a global event scope that an sdl_handler can register to in
order to receive all current events, regardless of the current
scope. Care should be taken to not be registerd in a local event
context and the global context at the same time as it will lead to the
event handler potentially being invoked twice.
This also adds the workaround needed for #24209 in the new event
handler in the video class.
=> Fix bug #24209 and add a global event context

src/gui/widgets/container.cpp, src/gui/widgets/container.hpp, src/gui/widgets/control.cpp, src/gui/widgets/control.hpp, src/gui/widgets/generator.hpp, src/gui/widgets/generator_private.hpp, src/gui/widgets/grid.cpp, src/gui/widgets/grid.hpp, src/gui/widgets/minimap.cpp, src/gui/widgets/minimap.hpp, src/gui/widgets/multi_page.cpp, src/gui/widgets/multi_page.hpp, src/gui/widgets/panel.cpp, src/gui/widgets/panel.hpp, src/gui/widgets/scrollbar_container.cpp, src/gui/widgets/scrollbar_container.hpp, src/gui/widgets/spacer.cpp, src/gui/widgets/spacer.hpp, src/gui/widgets/toggle_panel.cpp, src/gui/widgets/toggle_panel.hpp, src/gui/widgets/tree_view_node.cpp, src/gui/widgets/tree_view_node.hpp, src/gui/widgets/widget.cpp, src/gui/widgets/widget.hpp, src/gui/widgets/window.cpp
According to a comment in the code, the functions with only a frame_buffer as a argument could be removed. Since they were never called before, this shouldn't break anything, but PR-ing it so travis can run through.
=> gui2: removed never accessed code path and related functions

src/storyscreen/controller.cpp, src/storyscreen/render.cpp, src/storyscreen/render.hpp
These changes make the storyscreen resize aware by adding an event
handler to the UI component and giving it its own event context. On an
window-event it'll restart relayout the entire scene and re-start the
drawing of the text.
Known issue: Gamescreen buttons appear when you move over them. This is beyond the scope of this commit and will be fixed in other changes.
=> Make the story screen resize aware

data/lua/wml-tags.lua, data/test/scenarios/for-loops.cfg
This fixes the `[for]` loop (and by extension, the `{FOREACH}` macro) not iterating the correct number of times if the array length changes during the loop. It does this by re-evaluating the endpoint and step size on each loop iteration, meaning that if someone uses variables in these fields, both the step size and endpoint could change during iteration.
=> Fix [for] loop not iterating the correct number of times

data/lua/wml/message.lua, src/scripting/game_lua_kernel.cpp, src/scripting/lua_common.hpp
This fixes some issues with the Lua implementation of `[message]`.
* The last unit who spoke ends up selected after the event ends.
* The speaking unit is not correctly highlighted on the map
* Units without portraits show non-team-coloured sprites.
My build doesn't have team colour at all for some reason, so I need someone else to test the TC part of this.
=> Fix [message] issues

changelog, src/actions/attack.cpp, src/actions/create.cpp, src/actions/unit_creator.cpp, src/game_events/action_wml.cpp, src/play_controller.cpp, src/scripting/game_lua_kernel.cpp, src/synced_commands.cpp
This is intended to allow event-driven abilities and other modifications to immediately take action when any unit appears on the map.
Still needs some more testing in context of replays and multiplayer.
=> Added event type "unit placed"

data/core/about.cfg, src/filesystem_boost.cpp, src/serialization/string_utils.hpp, src/wesnoth.cpp
I compiled Battle for Wesnoth from source code, and attempted to launch it with this batch file (placed into the folder which contains the "wesnoth" and "external" folders):
SET PATH=%PATH%;%~d0%~p0external\dll
START "" "%~d0%~p0wesnoth\wesnoth.exe"
It crashed on startup.
Debugging showed me that this code right in main() is the culprit:
```c++
#ifdef _OPENMP
// Wesnoth is a special case for OMP
// OMP wait strategy is to have threads busy-loop for 100ms
// if there is nothing to do, they then go to sleep.
// this avoids the scheduler putting the thread to sleep when work
// is about to be available
//
// However Wesnoth has a lot of very small jobs that need to be done
// at each redraw => 50fps every 2ms.
// All the threads are thus busy-waiting all the time, hogging the CPU
// To avoid …
```
=> Fix some startup crashes

src/config.cpp, src/config.hpp, src/filesystem.hpp, src/filesystem_boost.cpp, src/scripting/game_lua_kernel.cpp, src/scripting/lua_fileops.cpp, src/scripting/push_check.hpp, src/serialization/preprocessor.cpp, src/unit.cpp, src/unit.hpp, src/unit_abilities.cpp, src/unit_types.cpp, src/unit_types.hpp
this adds a new proprocessor macro called as {CURRENT_FILE}/{CURRENT_DIRECTORY} whcih expands to the current file/directory name. the intention is to use for example as
```
[lua]
code = "wesnoth.dofile({CURRENT_DIRECTORY}lua/myfile.lua)"
[/lua]
```
This also contains 2 other (unrelated) changes:
It cleans up the units cdfg_ field so that it only contains atributes, no child tags. This also Fixes a savefiles bloat becase the [variation]s, specially of walking corpses aren't stored in the [unit] wml anymore.
It adds "./dir/file.lua" support to lua dofile/require, this is also not optimial yet, becase lua chunknames shoudl only contains teh relative name (~add-ons/..  ../myfile.lua) while it currently contains the complate path (C:\users\..    ../add-ons/..   ../myfile.lua)
=> Add CURRENT_FILE proprocessor macro

data/core/encyclopedia/geography.cfg
Fixes a typo reported on https://wiki.wesnoth.org/SpellingMistakes
@Vultraz: Should I clear the entry in the wiki? Or do we wait until a release is made?
Also, this one can be backported to 1.12 if that's still being done.
=> Help: Fix typo in Help -> Encyclopedia -> Geography -> Great Ocean.

data/ai/dev/akihara_recruitment.cfg
A quick fix to get Default RCA to top of list in debug mode, so add-on development is easier.
It's a quick fix, as there's the possibility that the abandoned ai's might be removed.
=> Change id of broken ai to get it off the top of list in mp debug.

src/wesnoth.cpp
Loading of user preferences - or user hot-keys at the very least - were broken with the deletion at https://github.com/wesnoth/wesnoth/commit/28be388d6d59783e140aeaad1f3410766212d056#diff-fce7a1e6525522f3e4ab47349051a806L770
This restores loading of user preferences at start-up.
=> Restore loading of user hot-keys at start-up (bug #24427)

data/campaigns/An_Orcish_Incursion/scenarios/01_Defend_the_Forest.cfg, data/campaigns/An_Orcish_Incursion/scenarios/07_Showdown.cfg
Somebody went to the trouble of giving them specific names, Similar is done in spots in HttT, and it seems silly to allow Lomarfel to be renamed.
=> AOI: Make the named loyal units unnameable.

src/replay.hpp
#include <iterator> is needed for back_insert_iterator. This was included in config.hpp, but inclusion of that header here was removed in the previous commit. It might not be needed in Linux, but it looks like it's required for VC/Windows.
=> Fix broken build in VC

projectfiles/CodeBlocks/wesnoth.cbp, src/gui/dialogs/preferences_dialog.cpp, src/gui/dialogs/preferences_dialog.hpp, src/gui/widgets/group.hpp
A group is a window-unique named vector of widgets. Different widget classes can
use tgroup::execute_group_actions() to iterate over the group members, and pass
a setter function of their own to operate on each group member.
Currently, the code is specialized for the tselectable_ class, but could be
expanded later for other base types if necessary. Out of the tselectable_
inheritors, only ttoggle_button makes use of groups so far (for radio groups).
=> gui2: implement widget groups

changelog, src/hotkey/command_executor.cpp, src/hotkey/hotkey_item.cpp, src/hotkey/hotkey_item.hpp
Re-open PR #530 but now based on master.
Only save non-default hot-keys to the preferences file if the hot-key is active (ie command != 'null').
Clearing hot-keys in memory (via the hot-key functions in the game) only sets the command to 'null', which currently gets written to the preferences file if it is a custom, ie non-default, hot-key. Over time, creating and clearing hot-keys results in a lot of redundant hot-key entries. The nice thing about this update is that it will remove redundant command='null' entries for existing preferences files as well as prevent it from being included in future ones..
To do: while this change achieves the intended result there is extra work to be done to allow the clearing of default hot-keys (bugs #21983, #22218, #23981).
=> Resolve preferences file polluted with null-command hot-keys (Bug #21969)

src/storyscreen/render.cpp
I created a loop to redraw all markers because the background hid them.
=> Fixed bug #24496: story maps show all markers in journey trails again

src/display.cpp
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=462794 was reported and fixed in 2008. The issue was reported fro libsdl 1.2.13, the latest/last version was 1.2.15. Debian is still shipping 1.2.13, but have applied a patch to fix the issue. I would also expect that other platforms will also have resolved this issue since if they are still shipping that version of the library.
=> Fix TODO by removing workaround for a resolved SDL issue.

src/scripting/game_lua_kernel.cpp, src/scripting/game_lua_kernel.hpp, src/unit.cpp, src/unit.hpp, src/unit_attack_type.cpp, src/unit_attack_type.hpp
This allows them to be called by Lua code or even overridden.
In addition, the effect functions have changed a little:
- They now return a string value which can be used to describe the effect, for building descriptions of traits.
- They now receive a boolean value; if false, they should _only_ build the description without altering the unit (used when `times=per level` but the unit is level 0).
- The config passed to the function by Wesnoth will always have `times=1`, no matter what the original `[effect]` tag had. This is something of a safeguard against coders manually implementing this when Wesnoth already calls the function several times if needed.
Needs testing still.
=> Include built-in effects in wesnoth.effects

changelog, po/wesnoth-lib/af.po, po/wesnoth-lib/ang.po, po/wesnoth-lib/ar.po, po/wesnoth-lib/ast.po, po/wesnoth-lib/bg.po, po/wesnoth-lib/ca.po, po/wesnoth-lib/ca_ES@valencia.po, po/wesnoth-lib/da.po, po/wesnoth-lib/el.po, po/wesnoth-lib/eo.po, po/wesnoth-lib/et.po, po/wesnoth-lib/eu.po, po/wesnoth-lib/fur_IT.po, po/wesnoth-lib/ga.po, po/wesnoth-lib/hr.po, po/wesnoth-lib/id.po, po/wesnoth-lib/is.po, po/wesnoth-lib/ko.po, po/wesnoth-lib/lv.po, po/wesnoth-lib/mk.po, po/wesnoth-lib/mr.po, po/wesnoth-lib/nb_NO.po, po/wesnoth-lib/racv.po, po/wesnoth-lib/ro.po, po/wesnoth-lib/tl.po, po/wesnoth-lib/tr.po
I recognise that translations are normally supposed to go through Ivanovic. But since this pertains to the code's handling of translated images and not translated text, I think this should be an acceptable exception.
=> Resolve translated logo images not being used (bug #24357)

src/CMakeLists.txt
make_enum.cpp was moved to utils/make_enum.cpp, and src/CMakeLists.txt
wasn't updated.
=> Fix cmake reference to make_enum.cpp.

changelog, src/hotkey/hotkey_item.cpp
Unfortunately, the US/QWERTY-centric nature of SDL 1.2 keyboard handling means that the previous commit breaks character-based hot-keys for non-US/QWERTY keyboard layouts. (Bug #24186)
This reversion wipes out all improvements to hot-key handling introduced for US/QWERTY keyboards.
=> Revert all recent improvements to SDL1.2 hot-key handling (1.12)

changelog, data/core/about.cfg, data/core/macros/names.cfg, src/CMakeLists.txt, src/SConscript, src/race.cpp, src/race.hpp, src/utils/context_free_grammar_generator.cpp, src/utils/context_free_grammar_generator.hpp
Added a new way to generate unit names, using rules of a context-free grammar. It is much more configurable than the current system, so it's possible to prevent extremely long or otherwise funny and awkward names. If it can't find its entries in the race definition, it falls back to the old Markov chains.
=> Unit name generator using context-free grammar

changelog, src/playturn.cpp
This moves the options for giving control to an ally/observer to the top of the list, labels them more descriptively, and prevents the dialog from appearing during linger mode if there is no next scenario.
Old:
Replace with AI
Replace with local player
Set side to idle
Save and abort game
Replace with (observer1)
Replace with (observer2)
Replace with (ally1)
Replace with (ally2)
New:
Give control to their ally (ally1)
Give control to their ally (ally2)
Give control to observer (observer1)
Give control to observer (observer2)
Replace with AI
Replace with local player
Set side to idle
Save and abort game
=> Improve the control reassignment dialog when a player leaves

changelog, data/core/about.cfg, data/lua/wml/message.lua
Made [this](https://gna.org/bugs/?24576) request, then realized I could do it myself.
=> Add color=value to [message]

data/tools/wmllint
Thanks to Elvish_Hunter for telling me what it supposed to do.
=> wmllint: add missing instructions for "#wmllint: skip-side".

utils/pywmlx/__init__.py, utils/pywmlx/wmlerr.py, utils/wmlxgettext
Thanks to Elvish Hunter, wmlxgettext now have colored text not only on posix system, but also on windows (I'm speaking about the text that appears on terminal).
I did some little changes from that original code.
=> terminal colored text extended to windows

src/utils/context_free_grammar_generator.hpp
I got these compiler errors when trying to build Wesnoth:
> 4>i:\battle for wesnoth\wesnoth\src\utils\context_free_grammar_generator.hpp(37): error C2061: syntax error : identifier 'uint32_t'
> 4>..\..\src\utils\context_free_grammar_generator.cpp(131): error C2511: 'std::string context_free_grammar_generator::print_nonterminal(const std::string &,uint32_t *,short) const' : overloaded member function not found in 'context_free_grammar_generator'
> 4>          i:\battle for wesnoth\wesnoth\src\utils\context_free_grammar_generator.hpp(25) : see declaration of 'context_free_grammar_generator'
> 4>..\..\src\utils\context_free_grammar_generator.cpp(133): error C2228: left of '.find' must have class/struct/union
> 4>..\..\src\utils\context_free_grammar_generator.cpp(134): error C2228: left of …
=> Fix build with Visual Studio 2013

changelog, players_changelog, src/halo.cpp, src/units/drawer.cpp
The bug was caused by overly aggressive performance optimizations.
When a unit is moving, it's replaced with a temporary unit. If the moving unit is a Mage of Light, its halo is recreated. The recreated halo is originally placed in the top-left corner of the screen (exactly the position where it actually stayed in practice).
The game attempts to correct the position of the halo on the next frame by calling `halo::manager::set_location()`, that eventually calls `halo_impl::effect::set_location()`. Since the overlayed hexes (`overlayed_hexes_`) aren't known after moving the halo, `set_location()` clears the list of overlayed hexes. The idea is that the overlayed hexes will be determined when the halo is drawn next time, in `halo_impl::effect::render()`.
`Halo_impl::render()` only draws …
=> Fix bug #23712: Mage of Light halo not drawing correctly

src/hash.cpp, src/hash.hpp, src/md5.cpp, src/md5.hpp
I modernized the MD5 calculation API to use `std::array` and `std::vector` instead of raw C arrays. This way, in particular, the length of the MD5 hash is shown right in the function signatures, and it's no longer possible to accidentally pass an incorrect length to `MD5::update()`.
The internal API of the MD5 class I left intact to the extent I could. I needed to add the `const` qualifier to a couple of function parameters, though.
=> Modernize the MD5 hash calculation API

utils/pywmlx/autof.py
During a test I noticed that the pywmlx.autof.autoscan function could work (very) wrongly if the path contains a symlink somewhere.
The bug is now fixed, and autoscan work correctly also if the input path (with symlinks) and the real path (where symlinks are translated to actual path) differs.
This issue was strictly related to the '--recursive' option (wich makes the life easier for UMC authors :) )
=> bugfix: wmlxgettext '--recursive'  option and symlinks

src/display.cpp, src/events.cpp, src/video.cpp, src/video.hpp
The fix supresses the call to flip() while a full redrawn
is performed. The flip calls are instead deferred to
then next draw-cycle.
=> Hacky fix for the flickering when a screen is fully redrawn.

data/campaigns/An_Orcish_Incursion/scenarios/03_Wasteland.cfg, data/campaigns/An_Orcish_Incursion/scenarios/04_Valley_of_Trolls.cfg, data/campaigns/An_Orcish_Incursion/scenarios/06_A_Detour_through_the_Swamp.cfg, data/campaigns/An_Orcish_Incursion/scenarios/07_Showdown.cfg, data/campaigns/An_Orcish_Incursion/utils/macros.cfg
With Zookeeper's and CelticMinstrel's changes to remove the on-screen warning about no unit for role, and add functionality to the [role] tag, this is my cleaned-up changes to An Orcish Incursion. It replaces my previous PR for that campaign. This patch set includes the following changes:
S01     No changes
S02     No changes
S03  ** On victory, ensure a unit has the advisor role
** On time over, if needed, re-assign the advisor role to a unit on the board
S04  ** On enemies defeated, ensure a unit has the advisor role
** On die (Erlornas), if needed, re-assign the advisor role to a unit on the board
** On time over, ensure a unit has the advisor role
S05     No changes
S06  ** During prestart, ensure a unit has the mage role
** On enemies defeated, ensure a unit has the mage role
S07  ** …
=> An Orcish Incursion fixes

changelog, data/campaigns/An_Orcish_Incursion/scenarios/01_Defend_the_Forest.cfg, data/campaigns/An_Orcish_Incursion/scenarios/02_Assassins.cfg, data/campaigns/An_Orcish_Incursion/scenarios/03_Wasteland.cfg, data/campaigns/An_Orcish_Incursion/scenarios/04_Valley_of_Trolls.cfg, data/campaigns/An_Orcish_Incursion/scenarios/05_Linaera_the_Quick.cfg, data/campaigns/An_Orcish_Incursion/scenarios/06_A_Detour_through_the_Swamp.cfg, data/campaigns/An_Orcish_Incursion/scenarios/07_Showdown.cfg, data/campaigns/An_Orcish_Incursion/utils/characters.cfg
This seems more logical, plus it allows the player to recover from losing all their Mages in S06 and S07. Mages really help in S07.
Originally part of my fixes to AOI, separated since it's completely independent.
N.B. When testing you must start a fresh campaign for the changed recruitment lists to fully take effect. If you see Linaera recruiting Elves **AND** Mages, that's the reason.
=> AOI Linaera should recruit Mages, not Elves

projectfiles/VC12/wesnoth.vcxproj, projectfiles/VC12/wesnoth.vcxproj.filters
I added `name_generator_factory.hpp` and `name_generator_factory.cpp` to the Visual Studio project. While I was at it, I also removed the nonexistent file `boost_function_guarded.hpp` from the project.
=> Update Visual Studio project files

data/game_config.cfg, data/gui/window/title_screen.cfg, src/game_config.cpp, src/game_config.hpp, src/gui/dialogs/title_screen.cpp
remove hardcoded path for logo image
add 'game_logo' & 'game_logo_background' keys in [game_config]
this allows [core] authors to define their own game logo to appear on the title screen
this does not (yet) affect the loadscreen
=> [game_config]: new keys for logo

projectfiles/VC12/wesnoth.vcxproj, projectfiles/VC12/wesnothlib.vcxproj
Pretty self-explanatory. Visual Studio can use multiple processor cores to speed up compilation, but the feature is not enabled in our VS project files.
I also disabled "minimal rebuild" (attempting to avoid rebuilding .cpp files when a .h file is changed) because it can't be used together with multi-processor compilation. At least in my experience, building is faster with multi-processor compilation than with minimal rebuild. (My processor is Intel Core i5-4430 [four physical cores, hyperthreading not supported]).
My guess as for why multi-processor compilation wasn't enabled already is that it probably wasn't supported by older versions of Visual Studio that Wesnoth supported until spring 2016. As of today, the oldest supported version is VS2013 that does support the feature.
=> Visual Studio: enable multi-processor compilation

src/events.cpp
Quoting the corresponding messages in IRC:
> [19:49:36] \<JyrkiVesterinen\> FYI: the game crashed when I tried to open the Preferences dialog ingame. Looks related to the event context changes.
> [19:49:37] \<JyrkiVesterinen\> https://gist.github.com/jyrkive/3992782bfb0c7b6bea6f9dd2ac6b9dad
> [19:49:42] \<JyrkiVesterinen\> I'm investigating.
> [20:10:19] \<hk238\> :o
> [20:21:54] * stikonas (~gentoo@wesnoth/translator/stikonas) has quit IRC (Quit: Konversation terminated!)
> [20:30:50] \<JyrkiVesterinen\> All right, the problem is in the destructor of the context class.
> [20:30:51] \<JyrkiVesterinen\> https://github.com/wesnoth/wesnoth/blob/681322bf2935ce08e2526d92b842aad86302afe6/src/events.cpp#L133-L146
> [20:31:43] \<JyrkiVesterinen\> It performs "it = handlers.erase(it);" followed by …
=> Fix undefined behavior on destroying an event context

src/tod_manager.cpp
This gets rid of yet another use of Boost.Bind. After this, only server.cpp remains. :smiling_imp:
=> Implement tod_manager::resolve_random() without Boost.Range

changelog, data/campaigns/An_Orcish_Incursion/utils/macros.cfg, data/campaigns/Liberty/scenarios/04_Unlawful_Orders.cfg, data/lua/wml-tags.lua, src/game_events/action_wml.cpp
This builds upon [CelticMinstrel's changes](https://github.com/wesnoth/wesnoth/commit/d4b8fec953ca81531d323774a39da90445dfd3d6) from a few days ago.
On code-reading, I see he made allowances to bypass searching the map. Also, he asked about whether a [role] would re-assign the role if a better match was found. On testing, I found, it did. As a result, I added the following new attributes for the [role] tag.
search_map=yes|no (optional, default yes)
reassign=yes|no (optional, default yes)
The search_map attribute determines whether units presently on the map should be considered for the role. Note that if both search_map and search_recall_list are specified as 'no' the [else] sub-tag always executes; if there also is no [else] tag the [role] tag does nothing at all. (These might be cases …
=> New features for [role]

changelog, data/lua/wml-tags.lua, data/test/scenarios/event_handlers_in_events.cfg, src/actions/undo_action.cpp, src/game_events/handlers.hpp, src/game_events/manager.cpp, src/game_events/manager.hpp, src/game_events/manager_impl.cpp, src/game_events/manager_impl.hpp, src/game_events/pump.cpp, src/game_events/pump.hpp, src/menu_events.cpp, src/scripting/game_lua_kernel.cpp, src/scripting/game_lua_kernel.hpp
I implemented a feature request mentioned in [https://wiki.wesnoth.org/EasyCoding], which allows you to raise events by id instead of name.
This adds the lua functions ```wesnoth.fire_event_by_id``` and ```wesnoth.fire_event_by_name```. The old ```wesnoth.fire_event``` is now an alias of ```wesnoth.fire_event_by_name```.
The WML tag ```[fire_event]``` has now an extra key ```ìd=```, which fires an event by id. When ```id=``` is empty or missing, the event is fired by name. If neither ```ìd=``` nor ```name=``` are given, nothing happens (like the current behavior).
=> Allow firing an event by id instead of name.

data/gui/window/preferences/04_sound.cfg, src/game_launcher.cpp, src/game_launcher.hpp, src/gui/dialogs/preferences_dialog.cpp, src/preferences.cpp, src/preferences.hpp, src/sound.cpp, src/sound.hpp
When I play any game, I tend to take a break once in a while: Alt-Tab out of the game and listen to some music for a while.
For that reason, it annoys me when a game continues to play music in background. In such a situation I either have to quit the game or mute it using the Windows volume mixer.
Wesnoth plays music in background, too.
This commit implements automatic muting of music on focus loss, and restarting it when Wesnoth regains focus.
=> Mute the music when the game loses focus

src/units/unit.cpp
When advancing or an object (say, the Scepter of Fire) selects a unit variation, the ellipse is lost. This causes a unit with {ISHERO} to convert to {ISLOYAL}, changing the hero ellipse to the default.
I consider this a Work In Process because I view the issue as symptomatic of a general error and would prefer someone better invested in the engine, and unit.cpp specifically, to review the code for other instances.
This problem was first noticed in HttT S17 when Li'sar obtains the Scepter of Fire. The Scepter operates by selecting a unit variation.
The problem was then confirmed to also effect any {ISHERO} unit who was not canrecruit and not at AMLA such as Kalenz when first able to advance in HttT S07 and confirmed with additional checks in other campaigns.
The problem was also confirmed …
=> unit.cpp Fix bug: Ellipse is lost

changelog, data/advanced_preferences.cfg, players_changelog, src/attack_prediction.cpp, src/attack_prediction.hpp, src/preferences.cpp, src/preferences.hpp, src/random_new.cpp, src/random_new.hpp
In short: I implemented the Monte Carlo damage calculation mode requested in https://wiki.wesnoth.org/NotSoEasyCoding#Add_a_new_damage_stats_calculation_mode_to_support_scenarios_with_extremely_high_stats . :+1: 
As explained in the wiki, the advantage of this mode is that its time requirement is almost fixed: the only things which can make it slower are the number of strikes and the berserk ability. I benchmarked the code using the built-in benchmark functionality (which simulates thousands of battles with hard-to-calculate units): the simulation takes, on average, four milliseconds per battle.
Also, like the wiki page requested, the Monte Carlo simulation mode is disabled by default. The player can enable it with an advanced preference.
=> Monte Carlo damage calculation

src/build_info.cpp, src/commandline_options.cpp, src/desktop/version.cpp, src/formatter.hpp, src/savegame.cpp
`formatter` is one of these classes that Dave has put into every project that he worked on it seems.
In wesnoth, the `formatter` class still has a copyright to "The Silvertree Project" which has long been defunct.
It's commonly used as
```c++
string result = (formatter() << "blah " << n << x << " blah").str();
```
In [anura](https://github.com/anura-engine/anura/blob/trunk/src/formatter.hpp), Dave modified it to be more aggressive, by giving it an `operator std::string()` implicit conversion.
This allows a terser syntax:
```c++
string result = formatter() << "blah " << n << x << " blah";
```
but it creates some room for compiler shenanigans. Usually programmers agree that implicit conversions like this are evil. But it's also pretty convenient.
In another project, I modified it as shown …
=> give formatter an x-value conversion to std::string (C++11)

data/lua/wml/objectives.lua
This matches the style used for OBJECTIVE_FOOTNOTE and makes the turn count more apparent.
The turn count really is not part of the win/lose condition. The show_turn_counter option adds it as an informative footnote. Other such footnotes are created using OBJECTIVE_FOOTNOTE, which sets the color 'white'. This change makes the show_turn_counter footnote consistent with that macro.
=> objectives.lua show_turn_counter in white

src/events.cpp, src/storyscreen/render.cpp
This also adds a call to stop flips during a full redraw as a consequence of a window event.
=> Fix bug #24553: Prevent the display from drawing over the storyscreen.

data/campaigns/Heir_To_The_Throne/scenarios/19c_Cliffs_of_Thoria.cfg
When a Drake base is killed it needs to be removed from the list of active Drake bases.
=> Emergency fix for commit #25e46473d2bdb0a2bb7577373c216efa5b631847

changelog, data/core/macros/sound-utils.cfg, players_changelog, src/playsingle_controller.cpp, src/sound.cpp, src/storyscreen/render.cpp
@Vultraz requested something like this in IRC.
> 20160730 12:44:41\< vultraz\> JyrkiVesterinen: I have a small task for you, if you're up to it: make it so music fades out (such as when you toggle it off, or a scenario ends) instead of stopping abruptly.
I implemented fading out when the player disables music in preferences. I also edited the SCENARIO_MUSIC and INTRO_AND_SCENARIO_MUSIC macros by turning on fade-out of previous music (i.e. the storyscreen music) when the scenario starts.
I assume that the "scenario ends" condition @Vultraz mentioned means the victory or defeat situation, when the game plays the victory/defeat music. I didn't implement fade-out of previous music in that situation because I *oppose* it. (I prefer the "abrupt" switch to the victory/defeat music.)
=> Fade out music on scenario start and on disabling it

src/text.cpp
This restores some code that wasn't being used on Windows to strip pre-multiplied alpha
from the text render before passing it to SDL_CreateRGBSurfaceFrom. Despite the code comment
to the contrary, enabling this code doesn't seem to mutilate the text output unless
pango_cairo_show_layout is called *after* stripping.
Unless I'm misunderstanding, pango_cairo_show_layout would get called 4 times on Windows.
Removing 3 of those calls meant the use of CAIRO_ANTIALIAS_GRAY as a fix for bug #21648
now resulted in horrible-looking text. Changing the AA method to CAIRO_ANTIALIAS_GRAY now
seems to produce acceptable results.
The resulting text is only slightly different from that produced before this change, though
very slightly more anti-aliased and a little grayer.
=> ttext: tweaks to rendering, especially on Windows

src/gui/dialogs/preferences_dialog.cpp
Sorting by hot-key was something that we could do in 1.12, but this is lost with current implementation of the redesigned dialogue. This is my attempt to restore this function.
https://gna.org/bugs/?24933
=> Allow hotkeys dialogue to be sorted by Hotkey column again. (Bug #24933)

src/game_events/handlers.cpp
Commit 18d7736 caused an infinite loop.
In HttT S14 we have a sighted event which includes [teleport] tags. This commit causes the sighted event to run to completion, then re-fire, in an infinite loop. Removing the [teleport] tags stopped the loop. Reversing this commit does, as well.
=> Reverse commit 18d7736

src/generators/cave_map_generator.cpp
The cave map generator displays the seed on stderr. Move it to the logging system at 'info' level.
=> Use info level

data/lua/wml/object.lua
This causes, for example, units the player does not control to be selected at the start of HttT S08, S11 and S16.
=> Do not select unit in silent object

changelog, data/lua/wml/message.lua
If [message] includes one or more [option] choices, store the choice index in the result variable. If [option] has value=, use that instead of the index number.
Simple example of use:
[message]
variable=choice
speaker=narrator
message="Choose option 1 through 4"
[option]
label="Option 1"
value="One"
[/option]
[option]
label="Option 2"
[/option]
[option]
label="Option 3"
value="Tres"
[/option]
[option]
label="Option 4"
[/option]
[/message]
[message]
speaker=narrator
message="You chose option number $choice|"
[/message]
{CLEAR_VARIABLE choice}
In examining AToTB, there is a lot of work in [command] blocks which can be eliminated if we simply know which of 1..4 was chosen. I imagine this is not all that unusual a use case.
=> Add result variable to [message] tag

changelog, data/core/macros/objective-utils.cfg
A convenience macro to add a standardized note to the objectives pointing out there is no turn limit.
I considered going through all the mainline scenario with turns=-1 and adding this, but decided it would be best to wait and change each, after consideration for each case, when reviewing them.
=> HAS_NO_TURN_LIMIT objectives macro

data/lua/wml-tags.lua
Tested with just cfg.message and it comes out as info/wml which seems just fine.
=> Remove dead code

data/campaigns/Two_Brothers/scenarios/02_The_Chase.cfg
This tells the AI for side 3 to ignore villages as candidate actions. This finishes the changes making side 3 move toward the player (side 1) without distraction.
I just learned of this, and tested it. Works great.
=> AToTB S02 Improve AI

changelog, data/lua/wml/modify_unit.lua
When specified, replace rather than merge the [unit] sub-tags. Does not effect [object], [trait], [effect] or [advancement].
For example:
[modify_unit]
[filter]
id=Deoran
[/filter]
mode=replace
[filter_recall]
[not]
id="Sir Gerrick"
[/not]
[/filter_recall]
[/modify_unit]
will replace the current contents of [filter_recall] with the given contents. Without mode=replace, the contents would be appended to the previous contents.
=> Add mode=replace to [modify_unit]

data/lua/wml-tags.lua
Missing role for [role] caused runtime errors. Do NOT report an error on this; using an empty string is intentional. It allows type-prioritized recalls!
"I want to recall the two highest-level bowmen and, if needed, will recruit them. They don't have a role, and won't need one later."
[repeat]
times=2
[do]
[role]
search_recall_list=only
type=Master Bowman,Longbowman,Bowman
[auto_recall][/auto_recall]
[else]
[unit]
placement=leader
side=1
type=Bowman
[/unit]
[/else]
[/role]
[/do]
[/repeat]
=> Fix bug [role] missing role=

src/map/map.cpp
To start this off, this first patch stops duplicated messages about the error.
=> Errors during Load if the save file has non-standard terrain

data/lua/wml-tags.lua
I changed my Felony Abuse of a Feature to use role="" to suppress the wml_error message.
It's best to always issue the error, even if we're going to auto_recall
=> [role] always error on missing role=

src/team.cpp
grep'd and didn't find any other places this massively stupid mistake appeared.
rather than change behavior, after correcting the definition, changed the calls.
=> Fix bug: Error typically means error

src/game_initialization/connect_engine.cpp
When pressing End Scenario and proceeding to the next scenario, the user_team_name shown on Menu|Status Table is incorrect.
If you Load (from the title screen) the saved scenario-start, the correct user_team_name appears.
This is caused by the random-shuffle feature for multi-player scenario. This fixes it for Single-Player campaigns and tries not to break it too badly for randomized Multi-Player campaigns.
=> Fix bug: user_team_name is wrong

src/savegame.cpp
For reproduce: play a scene, when the next settles down use Menu|Load to load the replay just created for the previous scene.
gtgftd suggested this patch. Seems to work. PR to document change for review.
=> Fix bug: Crash loading replay

data/campaigns/Heir_To_The_Throne/scenarios/01_The_Elves_Besieged.cfg, data/campaigns/Heir_To_The_Throne/scenarios/02_Blackwater_Port.cfg, data/campaigns/Heir_To_The_Throne/scenarios/03_The_Isle_of_Alduin.cfg, data/campaigns/Heir_To_The_Throne/scenarios/04_The_Bay_of_Pearls.cfg, data/campaigns/Heir_To_The_Throne/scenarios/05a_Muff_Malal_Peninsula.cfg, data/campaigns/Heir_To_The_Throne/scenarios/05b_Isle_of_the_Damned.cfg, data/campaigns/Heir_To_The_Throne/scenarios/06_The_Siege_of_Elensefar.cfg, data/campaigns/Heir_To_The_Throne/scenarios/07_Crossroads.cfg, data/campaigns/Heir_To_The_Throne/scenarios/08_The_Princess_of_Wesnoth.cfg, data/campaigns/Heir_To_The_Throne/scenarios/09_The_Valley_of_Death.cfg, data/campaigns/Heir_To_The_Throne/scenarios/10_Gryphon_Mountain.cfg, data/campaigns/Heir_To_The_Throne/scenarios/11_The_Ford_of_Abez.cfg, data/campaigns/Heir_To_The_Throne/scenarios/12_Northern_Winter.cfg, data/campaigns/Heir_To_The_Throne/scenarios/13_The_Dwarven_Doors.cfg, data/campaigns/Heir_To_The_Throne/scenarios/14_Plunging_Into_the_Darkness.cfg, data/campaigns/Heir_To_The_Throne/scenarios/15_The_Lost_General.cfg, data/campaigns/Heir_To_The_Throne/scenarios/16_Hasty_Alliance.cfg, data/campaigns/Heir_To_The_Throne/scenarios/17_Scepter_of_Fire.cfg, data/campaigns/Heir_To_The_Throne/scenarios/18_A_Choice_Must_Be_Made.cfg, data/campaigns/Heir_To_The_Throne/scenarios/19a_Snow_Plains.cfg, data/campaigns/Heir_To_The_Throne/scenarios/19b_Swamp_Of_Dread.cfg, data/campaigns/Heir_To_The_Throne/scenarios/19c_Cliffs_of_Thoria.cfg, data/campaigns/Heir_To_The_Throne/scenarios/20a_North_Elves.cfg, data/campaigns/Heir_To_The_Throne/scenarios/20b_Underground_Channels.cfg, data/campaigns/Heir_To_The_Throne/scenarios/21_Elven_Council.cfg, data/campaigns/Heir_To_The_Throne/scenarios/22_Return_to_Wesnoth.cfg, data/campaigns/Heir_To_The_Throne/scenarios/23_Test_of_the_Clans.cfg, data/campaigns/Heir_To_The_Throne/scenarios/24_Battle_for_Wesnoth.cfg, data/campaigns/Heir_To_The_Throne/utils/bigmap.cfg, data/campaigns/Heir_To_The_Throne/utils/httt_utils.cfg
**Hierarchy**
master
|
|
|
|
|
+-- …
=> HttT General Improvements

data/campaigns/Heir_To_The_Throne/scenarios/05b_Isle_of_the_Damned.cfg
**Hierarchy**
master
|
|
|
|
|
+-- …
=> HttT S05b Randomize Temples

changelog, src/map/map.cpp
Added overlay_special_locations=yes|no, default no, to [terrain_mask]. When yes, side starting locations and special locations marked in the mask replace those in the effected area of the underlying map by removing any from the underlying map, and applying only those given in the mask.
=> Honor special locations in terrain mask

src/actions/vision.cpp, src/addon/manager_ui.cpp, src/ai/default/ca.cpp, src/game_initialization/multiplayer_lobby.hpp, src/gui/dialogs/addon/filter_options.cpp, src/gui/dialogs/addon/filter_options.hpp, src/gui/dialogs/addon/list.cpp, src/gui/dialogs/game_load.cpp, src/gui/dialogs/lobby/info.hpp, src/gui/dialogs/multiplayer/mp_create_game.cpp, src/gui/dialogs/preferences_dialog.cpp, src/gui/dialogs/unit_create.cpp, src/gui/dialogs/unit_recall.cpp, src/gui/widgets/list.cpp, src/gui/widgets/list.hpp, src/gui/widgets/listbox.cpp, src/gui/widgets/listbox.hpp, src/playsingle_controller.cpp, src/reports.cpp, src/team.cpp, src/team.hpp, src/units/abilities.cpp, src/units/attack_type.hpp, src/units/unit.cpp, src/units/unit.hpp, src/whiteboard/manager.hpp, src/widgets/scrollpane.cpp
A few cases were skipped, most of which involved 2D bitsets (eg shroud) or uses that could not be easily translated (eg GUI1 multimenu).
In a few cases, code needed to be updated for the different API that the dynamic_bitset provides, but in most cases, this change is entirely transparent.
There are probably a few unnecessary dynamic_bitset.hpp includes.
One use of vector<bool> was replaced instead with std::bitset, since the dynamic size was not required.
=> Change most vector<bool> to dynamic_bitset

src/actions/move.cpp, src/pathfind/teleport.cpp, src/pathfind/teleport.hpp
Previously, units on the tunnel exits blocked tunnels, but this was not checked until the move execution, resulting in inconsistencies between displayed and possible moves even without fog. It also caused such units effectively to act as ambushers. This PR removes these inconsistencies.
It also adds a new boolean parameter, pass_allied_units, to the [tunnel] tag, which lets the scenario designer choose whether units can move through allied units on the tunnel exit.
=> Fix issues with tunnels when exit hex is occupied by an allied unit

data/campaigns/Heir_To_The_Throne/scenarios/10_Gryphon_Mountain.cfg, data/campaigns/Heir_To_The_Throne/scenarios/22_Return_to_Wesnoth.cfg, data/campaigns/Heir_To_The_Throne/scenarios/24_Battle_for_Wesnoth.cfg, data/campaigns/Heir_To_The_Throne/scenarios/25_HttT_Epilogue.cfg
**Hierarchy**
master
|
|
|
|
|
+-- …
=> HttT S22 Gryphons Return

data/campaigns/Heir_To_The_Throne/scenarios/20b_Underground_Channels.cfg, data/campaigns/Heir_To_The_Throne/scenarios/25_HttT_Epilogue.cfg
**Hierarchy**
master
|
|
|
|
|
+-- …
=> HttT S20b Wose Assistance

data/campaigns/Heir_To_The_Throne/scenarios/12_Northern_Winter.cfg, data/campaigns/Heir_To_The_Throne/scenarios/13_The_Dwarven_Doors.cfg
**Hierarchy**
master
|
|
|
|
|
+-- …
=> HttT S13 Snow Detritus

data/campaigns/Heir_To_The_Throne/scenarios/05b_Isle_of_the_Damned.cfg
**Hierarchy**
master
|
|
|
|
|
+-- …
=> HttT S05b Use Advisor

data/campaigns/Heir_To_The_Throne/scenarios/23_Test_of_the_Clans.cfg
The bonus is (1) recruit Knights and (2) the defeated leaders join you for the Battle for Wesnoth. You do not need to defeat all four for this.
=> HttT S23 Fix bug: Unclear objective

data/campaigns/Heir_To_The_Throne/scenarios/01_The_Elves_Besieged.cfg, data/campaigns/Heir_To_The_Throne/scenarios/07_Crossroads.cfg, data/campaigns/Heir_To_The_Throne/scenarios/25_HttT_Epilogue.cfg
**Hierarchy**
master
|
|
|
|
|
+-- …
=> HttT S07 Ambushers Reduced

data/campaigns/Heir_To_The_Throne/scenarios/06_The_Siege_of_Elensefar.cfg
**Hierarchy**
master
|
|
|
|
|
+-- …
=> HttT S06 Logical Thieves

src/synced_commands.cpp
Set the killed units hit points to zero so [have_unit] does not find it.
This prevents adding [kill] to [event]name=die simply to support Debug|Kill.
=> Fix bug: Debug|Kill [have_unit] error

src/actions/move.cpp, src/pathfind/pathfind.cpp, src/pathfind/teleport.cpp, src/pathfind/teleport.hpp
I think this is ready for testing and merging now.
There are some remaining questions about what should happen when there is an invisible unit on the tunnel exit hex, either because it's an enemy ambusher or because vision is not shared with an allied side.  Should the unit be revealed through the tunnel?  Should a message be displayed on-screen?  Etc.  But those are general questions as to what the correct behavior should be and have nothing specific to do with this PR.
=> Tunnels: fix issues with vision

src/reports.cpp
Remove unused variable, probably a leftover from when the function was originally copied from another function.
Found with cppcheck.
=> reports: remove unused variable "str"

changelog, src/editor/map/context_manager.cpp, src/editor/map/context_manager.hpp
Regarding the method commentary in context_manager.hpp, these are the kind of comments which are (mostly) useless - well-written method names should obviate the need for an explanatory comment. However, I replaced the 'TODO' and followed existing convention in this case.
This resolves https://gna.org/bugs/?25093 by replicating missing behaviour from 1.12 branch, however @Vultraz mentioned that he has 'an idea' and 'will investigate later' (#wesnoth-dev - 2016-09-24 07:08 UTC), so this may not be the 'proper' way to go about resolving the bug.
=> Resolve sides in editor not having a proper side number (bug #25093)

changelog, src/whiteboard/highlighter.cpp
Attempt to resolve bug #20071 where a unit with planned actions is killed before those actions can be completed. This would otherwise result in an assertion failure or crash to desktop because sa.find_last_action_of() would be making a null pointer reference (get_unit() returns null when the unit is killed).
I have tested this with one unit killed before planned actions are completed, two units killed before planned actions are completed, and a mixture of live units with planned actions completed, live units with planned actions incomplete, and units killed before planned actions are completed. The catch is that planned actions painted on the screen get left behind after their respective units are killed off, until the mouse cursor hovers over the actions and triggers a redraw. But it is …
=> Resolve crash on unit killed before planned actions are completed (bug #20071)

src/addon/info.hpp
Missing #include causes compilation error with clang++.
=> include ctime header for time_t

data/gui/window/wml_message.cfg, data/lua/wml/message.lua
The implementation of [this] (https://gna.org/bugs/?12098) feature request resulted in the content of a message being [squished] (http://cubeupload.com/im/Pcxsvs.png).  The change to wml_message.cfg fixes that issue.
[With no text] (http://i.cubeupload.com/7GTS22.png)
[With text] (http://i.cubeupload.com/inCkod.png)
[With text and options] (http://i.cubeupload.com/ET1bjV.png)
[With text and text input] (http://i.cubeupload.com/C4q4po.png)
[With text, text input, and options] (http://i.cubeupload.com/7CkSRJ.png)
The change to message.lua then allows the [message] tag to display and mirror two portraits.
=> Pentarctagon two portraits fix

src/ai/default/ca_move_to_targets.cpp, src/ai/default/ca_move_to_targets.hpp
This PR contains two changes which significantly improve AI move times for AI sides with many guardian units.  The first commit improves evaluation times for the guardian units themselves.  The second improves times for the other AI units.
=> Improve move times for AI sides with many guardians

src/ai/lua/core.cpp, src/game_initialization/multiplayer_ui.cpp, src/gui/dialogs/lobby/lobby.cpp, src/gui/widgets/chatbox.cpp, src/playturn.cpp, src/replay.cpp, src/savegame.cpp, src/scripting/lua_gui2.cpp, src/server/game.cpp, src/server/server.cpp, src/theme.cpp
An extension of af73336, hopefully this will remove some more of the warnings which pop up in MSVC compilation. Also try to use more explanatory variable names as code should generally be self-documenting and easy to read.
(Not that I think the names I picked are necessarily easier to read, but some of the older code is hard for me to interpret. Especially those single-character variable names!)
=> Avoid hidden variable warnings produced in MSVC compilation

utils/pywmlx/nodemanip.py, utils/pywmlx/postring.py, utils/pywmlx/state/lua_states.py, utils/pywmlx/state/machine.py, utils/wmlxgettext
Changelog:
* Added **--version** option (wmlxgettext version number is written in 
*YYYY.MM.DD.py3* format, where "_py3_" underline the language used on 
wmlxgettext: python 3.x)
* Added **--DMode** option --> I introduced a "stable" debugging code that can
be executed only using this option. It will write an extra file (_debug.txt_)
wich will record all the state sequences. It is a really useful option that
helps me to debug wmlxgettext if something doesn't work as expected.
Obliouvsly this option is useless for an end-user.
* Added lua plural support
The first test I did was focused to find and fix possible bugs on basic usage.
I tested wmlxgettext using this [lua source file](https://github.com/AncientLich/wmlxgettext-unoff/blob/master/wmlxgettext/test/reports/2016.10.03/tlua1.lua) …
=> wmlxgettext: added support for plural forms (used on lua files)

data/campaigns/The_Hammer_of_Thursagan/lua/spawns.lua, data/campaigns/The_Hammer_of_Thursagan/scenarios/02_Reclaiming_the_Past.cfg, data/campaigns/The_Hammer_of_Thursagan/scenarios/03_Strange_Allies.cfg, data/campaigns/The_Hammer_of_Thursagan/scenarios/04_Troll_Bridge.cfg, data/campaigns/The_Hammer_of_Thursagan/scenarios/05_Invaders.cfg, data/campaigns/The_Hammer_of_Thursagan/scenarios/06_High_Pass.cfg, data/campaigns/The_Hammer_of_Thursagan/scenarios/07_Mages_and_Drakes.cfg, data/campaigns/The_Hammer_of_Thursagan/scenarios/08_Fear.cfg, data/campaigns/The_Hammer_of_Thursagan/scenarios/09_Forbidden_Forest.cfg, data/campaigns/The_Hammer_of_Thursagan/scenarios/10_The_Siege_of_Kal_Kartha.cfg, data/campaigns/The_Hammer_of_Thursagan/scenarios/11_The_Court_of_Karrag.cfg, data/campaigns/The_Hammer_of_Thursagan/scenarios/12_The_Underlevels.cfg, data/campaigns/The_Hammer_of_Thursagan/scenarios/13_Epilogue.cfg, data/campaigns/The_Hammer_of_Thursagan/units/Dwarvish_Rune_Lord.cfg, data/campaigns/The_Hammer_of_Thursagan/utils/macros.cfg
This completes my code-read and play-test of THoT.
Most changes were minor. The changes effecting game-play are:
The treatment of the Mages obtained from Master Perrin’s academy has been adjusted. The ability to recruit mages is now gained when they appear, and lost immediately upon the death of the last one rather than lingering until the start of the next scenario.
In S08 ('Fear') it was possible to meet the enemy without previously capturing a village and having Ollin appear. This rendered the closing scene difficult to understand. Now, meeting the enemy also triggers Ollin's appearance.
And the following other major changes were made:
The Lua function used to spawn indigenous units which appear when capturing villages during S05 ('Invaders') has been corrected, debugged and revised to …
=> The Hammer of Thursagan (THoT) Corrections

src/server/server.cpp, src/server/server.hpp
Clean up the #if guards to suppress the message and code which does not execute on Windows because it has no FIFO support.
=> Suppress NO_FIFO_DIR message on WIN32

src/font/text_surface.cpp
Replacing fribidi_log2vis looks like more work than it's worth.
Checking the fribidi mailing list, I see remarks that it's not likely to go away and recommending people who hit the warnings ignore them and continue using the function.
=> Supress warnings

data/lua/helper.lua
Defender1031 noticed that the helper metatables are not guarded against external access via `getmetatable()`, allowing other code to arbitrarily change them and potentially break things. This commit fixes that.
=> helper.lua: set __metatable field to guard against external access to metatables

src/storyscreen/part.cpp, src/storyscreen/part.hpp, src/storyscreen/render.cpp
Adds an optional attribute `text_alignment` to the [part] tag for story text alignment.
```
[story]
[part]
story= _"Blah"
text_alignment=center
[/part]
[/story
```
=> Add ability to horizontally align story text

data/test/macros/wml_unit_test_macros.cfg
First come, first served.
This was causing many failures on Travis/CI
Use &w=1 to ignore white space viewing the diff.
=> Ensure [endlevel] only happens once.

data/test/scenarios/interrupts.cfg
For some reason the macro RESULT causes the test to crash Lua.
Don't see why. Don't know why this fixes it. But this gets the tests working.
=> Fix a unit test

src/CMakeLists.txt
Fix how wesnoth_lua_config.h is specified to allow out-of-tree builds.
I don't do out-of-tree builds so all I can say is it didn't break my build.
=> Fix bug: CMake out of tree

data/campaigns/Eastern_Invasion/lua/bandits.lua, data/campaigns/Legend_of_Wesmere/lua/wml_tags.lua, data/lua/helper.lua, data/multiplayer/scenarios/2p_Dark_Forecast.lua, src/wesnoth_lua_config.h
@gfgtdf requested assistance with a crash in MP scenario 2p_Dark_Forecast
The cause turned out to be a change from Lua 5.2 to 5.3 which converts numbers to always have a fractional part. This means integer values will have ".0" at the end. The unexpected input caused the engine to crash.
1. Changed all mainline which builds similar indices to conform to Lua 5.3
2. The MP startup is not complete, worked around this with a temporary fix
3. There were two issues with the Wesnoth API in the scenario
4. Updated the Lua configuration to enable compatibility with 5.2 for this error
2p_Dark_Forecast can now be played to victory/defeat although there is an error which appears complaining about an audio track being duplicated. (This may be due to my rapid play-through and is not a real error.)
The …
=> Lua integer indices

data/lua/wml/message.lua, src/gui/dialogs/wml_message.cpp, src/gui/dialogs/wml_message.hpp, src/scripting/lua_gui2.cpp
Added an internal flag to indicate [text_input] appeared so we no longer require label= to be present.
=> [text_input] Fix bug 25173

data/lua/wml/message.lua
No need to deselect when it was already done.
While this is the fix for the specific complaint, it does not address the larger issue of [message] being generally slow.
=> Fix bug: Slow narrator (Partial 25186)

data/core/macros/animation-utils.cfg, data/core/terrain.cfg, data/core/units/goblins/Wolf_Rider.cfg, data/core/units/monsters/Wolf.cfg, data/core/units/saurians/Skirmisher.cfg
E.g. they weren't working on water with water lilies before.
The terrain codes are now more generic too, for the case somebody wants to make an UMC variation.
Also had a look on other places where terrain codes get used.
There is also the DRAKE_FLYING_ANIMATION macro. It's not getting used, seems to be an old Artifact. DRAKE_STANDING_ANIMATION does the same thing.
I guess I can't just remove it but have to move it to macros/deprecated-utils?
The onliest reference to that macro is in data/tools/emacs_mode/wesnoth-wml-data.el
=> Made Drake Flying Animations working on more terrains.

src/gui/dialogs/lua_interpreter.cpp
In practice, it probably doesn't matter since cmd_string is a char array and not a complex data type, but nevertheless it is wrong to mix new and free. Also, this seemed like a good sized change to figure out how to send PRs. Appologies if it is too minor to bother about.
=> Don't mix new and free in lua_interpreter.cpp

SConstruct
SCons failed to rebuild game_config when the Git hash changes. The newer version was not copied into the source tree.
=> SCons Fix bug: Git Hash

src/filesystem_common.cpp
While given by the toolset, the default is set in wesonfig.h and should be used.
=> Fix bug: use of undeclared identifier LOCALEDIR

data/core/macros/animation-utils.cfg, data/core/macros/deprecated-utils.cfg
This macro isn't used anywhere in 1.12, probably even since the drakes animations have been remade.
Not even Ageless Era uses it.
DRAKE_STANDING_ANIM is the macro which gets used instead.
=> removed DRAKE_FLYING_ANIM

src/CMakeLists.txt
CMake omitted a unit test. Adding it so it runs the same tests as SCons.
CMake now runs 158 tests, the same as SCons.
=> CMake unit tests

data/gui/macros/_initial.cfg, data/gui/schema.cfg, data/gui/widget/size_lock_default.cfg, data/gui/window/lobby_main.cfg, data/gui/window/mp_join_game.cfg, data/gui/window/mp_staging.cfg, projectfiles/VC12/wesnoth.vcxproj, projectfiles/VC12/wesnoth.vcxproj.filters, src/CMakeLists.txt, src/SConscript, src/gui/core/window_builder.cpp, src/gui/widgets/container.hpp, src/gui/widgets/size_lock.cpp, src/gui/widgets/size_lock.hpp
http://i.imgur.com/2b8urXq.png
The chat box in the MP lobby is in a grid.
```
|-----------|
|filter area|
|-----------|
| game list |
|-----------|
|  chatbox  |
|-----------|
```
On `invalidate_layout()`, a grid determines the size of all child widgets by querying their optimal sizes with `get_best_size()` and distributing any surplus space according to the grow factors.
For a chatbox, the optimal size is however much is enough to show all the existing messages at once, without a scrollbar.
As a result, the chatbox randomly grows way too large. It looks ugly, takes space away from the game list, and when it gets even larger, breaks the layout system itself.
This pull request introduces a new GUI2 widget called **size lock**. A size lock wraps an arbitrary widget. Its `get_best_size()` …
=> Size lock widget

.appveyor.vs2013.yml, .appveyor.vs2015.yml
0) Visit https://appveyor.com
1) Sign in using your GitHub account.
2) Under projects tab: New Project
3) Click Add for wesnoth
4) Click back to Projects
5) Hover to right of wesnoth, click gear icon (Edit Project Settings)
6) Set project name ie., "Battle for Wesnoth (Visual Studio 2013)"
7) Enter custom configuration .yml name: .appveyor.vs2013.yml
8) Check to skip branches without appveyor.yml
9) Click Save
A) If desired, repeat 2 through 9 for Visual Studio 2015
Total run time for both toolsets is about 3.75 hours.
Note that each configuration builds both Debug and Release. Edit the .yml to only choose one.
There is a one-hour quota per build. Each build takes approximately 50 minutes. Cloning the repository takes from 5 to 20 minutes. Using a shallow clone zip file, reverting …
=> Add support for AppVeyor Continuous Integration for Visual Studio

.appveyor.vs2013.yml, .appveyor.vs2015.yml
Do not build branches with an open PR.
Use ZIP and clone only the commit in question. This should significantly reduce the time needed to download the repository. Live testing was exceeding 40 minutes and forcing a quota-exceeded timeout.
=> Adjust AppVeyor configurations

src/gettext_boost.cpp, src/spirit_po/po_message.hpp
This fixes the 2 warnings during a Visual Studio Release build.
It does not fix the other 24 warnings from a Debug build.
=> Fix warnings in spirit_po

data/campaigns/Under_the_Burning_Suns/scenarios/01_The_Morning_After.cfg
If the necromancer appears before Garak or Zhul are found, the objectives are wrong.
=> UtbS S1: Fix objectives if Necro appears early

changelog, src/serialization/preprocessor.cpp, src/serialization/preprocessor.hpp
Some code review for this wouldn't hurt.
Example:
```
#define SET_LABEL X Y STRING
#arg TOOLTIP
"default "+{STRING}+" tooltip"
#endarg
#arg COLOR
255,255,255#endarg
[label]
x={X}
y={Y}
text={STRING}
tooltip={TOOLTIP}
color={COLOR}
[/label]
#enddef
{SET_LABEL 25 23 "test label 1"}
{SET_LABEL 26 23 "test label 2" COLOR=0,0,255}
{SET_LABEL 27 23 "test label 3" (TOOLTIP= _ "this is a
multiline tooltip") COLOR=255,0,0}
{SET_LABEL 28 23 "test label 4" TOOLTIP=_"a single-line tooltip"}
=> Implemented support for optional macro arguments

src/game_config.cpp, src/generators/default_map_generator_job.cpp, src/gettext_boost.cpp, src/gui/core/canvas.cpp, src/gui/widgets/window.cpp, src/serialization/parser.cpp, src/serialization/preprocessor.cpp, src/server/simple_wml.cpp, src/terrain/translation.hpp, src/units/unit.cpp, src/wesnoth.cpp
These commits should get us to 0 errors / 0 warnings for both Release and Debug builds for Visual Studio 2015.
In general there were three classes of error:
* A local name hiding another. Renamed the local name
* The poorly-written logging macro causing a duplicated name to hide an earlier name. Removed the duplicate macro. This eliminated some inner log scopes. A better fix would be to completely replace the lame macro with a better one; but that is too much work for today.
* Bugs in spirit_po and certain Boost libraries. These were names-hides-name errors. Some could have been fixed by renaming some Wesnoth global variables; some are true bugs in the libraries. Since these are libraries, they messages were suppressed rather than correcting the library.
=> VC14 Cleanup

src/gui/widgets/spacer.cpp, src/gui/widgets/spacer.hpp, src/gui/widgets/styled_widget.cpp, src/gui/widgets/styled_widget.hpp
For widgets which don't contain text (`label_` is empty),
`request_reduce_width()` and `request_reduce_height()` can be implemented in a
way that respects the minimum size set in widget definition. However,
neither of those functions do anything for non-text widgets.
This pull request simply implements the request_reduce_* functions for non-text
widgets, and overrides the implementation for spacers because ingame WML
messages break otherwise.
This is the only commit I intend to have in this PR.
=> styled_widget: respect minimum size even for non-text widgets

src/gui/widgets/container_base.cpp
Composite widgets, i.e. widgets which inherit container_base, such as the unit preview pane, can have an explicit minimum size set in their definition. The widget will request either that size or however much space the child widgets want, whichever is higher.
If an explicit minimum size is set, the composite widget can't shrink below that size even if there isn't enough space. That limitation has annoyed at least @Vultraz : he wants to specify a minimum size for the unit preview pane but still allow it to shrink below that size before scrollbars show up.
This commit implements ability for composite widgets to shrink below the explicit minimum size, if set. I tested it locally: I set the minimum width of unit preview pane to 1000 pixels by editing [this …
=> Ability to shrink composite widgets below the default size

src/SConscript
Fix CPPDEFINES orphaned during #882.
Also rename a few loop variables to not shadow the existing 'env' variable.
Issue reported [here](https://forums.wesnoth.org/viewtopic.php?f=4&p=607035#p607026).
=> Fix CPPDEFINES for scons build

src/gui/widgets/listbox.cpp
I don't see the point of such a change. More important, it breaks all dialogs which search a listbox with `find_widget<listbox>()` and don't have a separate code path for `--new-widgets`, such as the new add-on manager. In particular, testing the new add-on manager without code changes is impossible because it is disabled without `--new-widgets` and fails to find the add-on list with it.
Besides, list boxes have been improved over the years with useful features such as an easy way to register sortable columns (commit a30d816ac7995ca6a2382de2268e765b9292f7ee). Writing pane codepaths for all the places where those features are used would be significant effort for no benefit.
=> Stop replacing listboxes with panes with --new-widgets

utils/woptipng.py
An improved version of the wesnoth-optipng shell script.
Supports multiple jobs at a time. ( -j )
Accepts a threshold for discarding images which were only reduced by a few bytes. ( -t 15 will only save images that were reduced in size by at least 15 %)
Niceness can be set using the -n switch.
Usage:
cd directory
woptipng . ../some/dir  ../some/some_file.png
The script should achive better compression ratios than the previous script.
The previous script was running optimizations in an unconditional loop and, at the end, did not save the image if pixel colors changed.
This implies if _one_ of the crushers did a bad job and changed the images content in a bad way, _none_ of the possibly good optimizations by the other crushed would be saved.
Woptipng checks the image every time after a …
=> add woptipng png compression script

changelog, src/game_initialization/multiplayer.cpp, src/game_initialization/playcampaign.hpp, src/playmp_controller.cpp
Hey,
I noticed that replays were not skipped when joining a multiplayer game with "Quick Replay" being selected. This fixes the issue.
In addition, I changed the `skip_replay_until_turn` option to a boolean, since specific turn numbers are never specified and have no effect.
=> Fix an issue with "quick replay" when joining multiplayer games

data/lua/wml/message.lua
Currently, if only second_image is provided, the unit portrait gets displayed as well.
=> Fix the unit portrait being displayed with only second_image is provided

src/game_initialization/multiplayer.cpp, src/game_initialization/playcampaign.hpp, src/gui/dialogs/lobby/lobby.cpp, src/gui/dialogs/lobby/lobby.hpp, src/playmp_controller.cpp
After #916, quick replays worked again when joining MP games but the "quick replay" mode was not deactivated when the client caught up.
This takes note of the joined game's current turn at the time of joining, and disables quick replay mode once that turn is reached.
=> Stop "quick replay" mode in MP games once the client caught up

src/help/help_text_area.cpp
help_text_area::add_text_item() doesn't support scaled font, so help pages crash when font scale is changed from 100%.
This is fix of bug: https://gna.org/bugs/index.php?25292
=> fix bug 25292 to support scaled font in help pages

src/help/help_text_area.cpp
https://gna.org/bugs/index.php?25334
help_text_area::add_text_item() checks width of string before split it by split_in_width().
But, that check don't consider no_break_after() and no_break_before() used inside of split_in_width().
So, if there is no_break_after() or before() character in line breaking point, split_in_width()'s first return string is  empty and it cause infinity recursive call.
=> fix bug #25334, segmentation faults in CJK help page

src/utils/name_generator_factory.cpp, src/utils/name_generator_factory.hpp
name_generator_factory::add_name_generator_from_config now only falls
back to loading a Markov-chain generator if the loading of the context-
free grammar generator fails or there is none available.
Motivation for the change: Until now, the CFG generator would be ignored for the base names. The Markov generator can't be adapted to my locale. c.f. [Forum discussion](https://forums.wesnoth.org/viewtopic.php?f=12&p=607975#p607889).
=> Do not load Markov name generator if a CFG generator could be loaded

src/gui/dialogs/addon/install_dependencies.cpp
Soliton said in IRC that translation strings with plural forms should be fetched with `_n()`, `sngettext()` or `vngettext()`.
The reason why I made this a pull request instead of pushing directly to master is that I'm unsure on whether it's a good idea at all to convert a _translated string_ into a `t_string`, as the code is doing. Since `_n()`, `sngettext()` and `vngettext()` all return `std::string`, the conversion is inevitable if the code has to use those functions.
=> Install dependencies dialog: Use _n() to fetch a translation string

src/units/attack_type.cpp
- Replaced _ with vgettext
- Replaced _n with vngettext
- Set_damage now uses set_damage rather than increase_damage
- Add missing utils::print_modifier to increase_movement
Fixes https://gna.org/bugs/?25468
=> Fixed hard-coded word order in attack_type::describe_modification

src/units/unit.cpp
Replaced hard-coded word order and N_ for all strings in
unit::describe_builtin_effect() with vgettext/vngettext using
placeholders.
=> Fixed translation markup in unit::describe_builtin_effect()

changelog, data/lua/wml-tags.lua
Most were only possible to add since 1.13.5
Not sure if 'lost' should be here.
I still need to add a changelog entry
=> WML: Add additional members to [store_side] results

doc/manual/manual.txt
There is "Unpoison" in the manual, but I don't know the ability such name.
It has almost same description as "Cure".
I think it is an old ability, so it should be deleted.
=> Delete old ability's description:Unpoison

src/font/sdl_ttf.cpp
fix bug #25332  https://gna.org/bugs/index.php?25332
render_text() separates sentences which use plural fonts to plural surfaces, but render_text() makes the surfaces invisible when blit surfaces.
=> Fix bug #25332, some sentences are not shown in help pages

src/server/forum_user_handler.cpp, src/server/forum_user_handler.hpp, src/server/mysql_prepared_statement.ipp
This makes forum_user_handler use prepared statements mysql api. This has following advantages:
1. Better security. We don't concatenate values into sql queries directly. Instead  we designate placeholders   for values in the query and provide values separately so that they never will be parsed as sql.
2. Prepared statements api can extract data directly in native types instead of as strings only. Thus there's no need to call atoi/stoi on numeric values obtained from the database since we get them directly as ints.
=> Sql prepared statements

data/core/editor/help.cfg
There are duplication of text attribute, so some sentence is not displayed.
=> help(editor): fix duplication of text attribute

src/game_initialization/flg_manager.cpp, src/game_initialization/flg_manager.hpp
In file included from ../src/game_initialization/flg_manager.cpp:15:
../src/game_initialization/flg_manager.hpp:108:13: warning: private field 'use_map_settings_' is not used [-Wunused-private-field]
const bool use_map_settings_;
^
=> resolve compile warning (clang)

src/units/types.cpp
Fix bug #25360: https://gna.org/bugs/index.php?25360
=> Fix bug #25360: variants name in help is not displayed.

data/campaigns/Heir_To_The_Throne/scenarios/14_Plunging_Into_the_Darkness.cfg
The player can't have recruited Gryphons yet, but may have summoned them using `:create'.  Don't kill any such Gryphons, only the one added by the event.
I ran into this when I tried going through HttT with dwarves rather than elves.  I had edited the savefile by hand to permit Konrad to recruit Gryphon Riders, but my level 1 Gryphon Riders disappeared between The Dwarven Doors and The Lost General.
=> HttT: don't kill Gryphons in the recall list

src/actions/undo.cpp, src/actions/undo.hpp, src/actions/undo_action.cpp, src/actions/undo_action.hpp, src/actions/undo_dismiss_action.cpp, src/actions/undo_dismiss_action.hpp, src/actions/undo_move_action.cpp, src/actions/undo_move_action.hpp, src/actions/undo_recall_action.cpp, src/actions/undo_recall_action.hpp, src/actions/undo_recruit_action.cpp, src/actions/undo_recruit_action.hpp, src/game_events/action_wml.cpp, src/synced_context.cpp, src/synced_context.hpp
Previously when redoing an action each action had a seperate action::redo function that handled redioing that action. Now when redoing an action we just use the replaywml (that we cut form the replay when undoing that action) to redo the action, and call synced_context::run() just liek when we executed the action for the first time.
The main advantage is that [on_redo] is no longer nesasary since the
game will ow just fire the action related wml events again when redoing
the actions.
See also http://gna.org/bugs/?25472
=> use the original action codepath when redoding

src/scripting/game_lua_kernel.cpp
Since @vultraz recently decided to remove this feature from wesnoth.deselect_hex, there is now a need to support this behaviour in some other way,
Should probably also search all uses of deselect_hex in master to decide if they should also deselect the unit.
=> Allow wesnoth.select_unit() to deselect the unit

data/core/macros/abilities.cfg
This ability gives content creator complete freedom on what unit type to create. (It's also only used in UMC)  While it's probably mostly the lvl0 version of the unit who used the ability, the current description is not fitting.
Credits for spotting and changing this go to Ravana.
=> Changed description of the alternative plague ability.

changelog, src/gui/widgets/grid.cpp, src/gui/widgets/grid.hpp, src/gui/widgets/scrollbar_container.cpp, src/gui/widgets/widget.cpp, src/gui/widgets/widget.hpp
This pull request is a response to [bug #25523](https://gna.org/bugs/index.php?25523).
Debugging immediately showed me that changing the text of any label (e.g. add-on author name, or description) causes the whole window to be laid out, which is expensive. In addition, it's unnecessary in the add-on manager, as the containing grid has plenty of space available.
To improve performance, this branch implements **partial relayout**, where only the containing grid is laid out. If laying out the grid fails, then the function calls itself on the parent grid recursively. Finally, if even the root grid doesn't have enough space, then it falls back to laying out the window like before.
My testing shows that this branch is a **huge improvement** for add-on manager responsiveness. In theory, it can …
=> Partial relayout

data/campaigns/The_Hammer_of_Thursagan/units/Dwarvish_Annalist.cfg, data/campaigns/The_Hammer_of_Thursagan/units/Dwarvish_Loremaster.cfg, data/campaigns/The_Hammer_of_Thursagan/units/Dwarvish_Witness.cfg
With the intention to use the same spelling like in core.
Previously discussed on [GNA #25013](http://gna.org/bugs/index.php?25013) and PR #915.
This would be the last change of that kind.
=> changed morningstar to morning star

src/formula/variant.cpp
Was:
````
[ 45%/256/3/557,1168.424] Building CXX object src/CMakeFiles/wesnoth-game.dir/formula/variant.cpp.o
../src/formula/variant.cpp:647:68: warning: lambda capture 'this' is not used [-Wunused-lambda-capture]
return value_cast<game_logic::variant_list>()->list_op(v.value_, [this](variant& v1, variant& v2) { return v1 + v2; });
^
../src/formula/variant.cpp:653:68: warning: lambda capture 'this' is not used [-Wunused-lambda-capture]
return value_cast<game_logic::variant_list>()->list_op(v.value_, [this](variant& v1, variant& v2) { return v1 - v2; });
^
../src/formula/variant.cpp:659:68: warning: lambda capture 'this' is not used [-Wunused-lambda-capture]
return value_cast<game_logic::variant_list>()->list_op(v.value_, [this](variant& v1, variant& v2) { return v1 * v2; });
^ …
```
=> resolve -Wunused-lambda-capture warning (clang)

src/floating_label.cpp
````
[src/floating_label.cpp:261]: (style) Condition 'screen!=nullptr' is always false
[src/floating_label.cpp:281]: (style) Condition 'screen!=nullptr' is always false
````
=> floating label: remove dead code. Found by cppcheck.

src/ai/default/attack.cpp, src/ai/default/contexts.hpp, src/ai/formula/ai.cpp, src/ai/formula/ai.hpp, src/ai/formula/callable_objects.cpp, src/ai/formula/callable_objects.hpp, src/ai/formula/function_table.cpp, src/formula/callable.hpp, src/formula/callable_objects.cpp, src/formula/callable_objects.hpp, src/formula/debugger.cpp, src/formula/debugger.hpp, src/formula/formula.cpp, src/formula/function.cpp, src/formula/function.hpp, src/formula/variant.cpp, src/formula/variant.hpp
This is still not quite finished for a couple of reasons; in particular, the infinite loop protections around `set_var()`, `set_unit_var()`, and `'continue'` have been removed, which might be a problem. I don't understand how these could _cause_ infinite loops, but I assume the protection had been there for a reason.
The goal of this is to generalize the idea of a WFL object that the engine can execute to produce some effect. The concept already existed in the FormulaAI engine, but was not generally available to code using the WFL APIs. Vultraz wishes to use action objects in other contexts, such as GUI2 or perhaps even ActionWML, so I've attempted to disentangle it from the FormulaAI code. I'm not sure I've succeeded, and the API currently feels a little wonky as well (particularly the …
=> [don't merge yet] Generalizing the FAI concept of action objects

src/saved_game.cpp
options settigns attributes in a contianer like
```
[options]
[slider]
id="container.attribute"
....
[/slider]
[/options]
```
were broken in  a previous refactor in 1.13.0. This commit should restore them.
=> support container variables in [options]

src/units/frame.cpp
Attempt to compromise between day and night visibility for the Shadow sprite, due to the Nightstalker ability making it nearly invisible at night, otherwise.
Ghost -> Shadow (Nightstalker) -> Nightgaunt (Nightstalker)
Ghost -> Wraith -> Spectre
Ghost units have translucency animations to simulate their ethereal nature - currently all of the above units except for Nightgaunt because it only has one sprite frame.
Nightstalker units are invisible at night-time, invisibility producing a dimming of the sprite to 50% (https://github.com/wesnoth/wesnoth/blob/master/src/units/drawer.cpp#L108). This applies to any unit deemed 'invisible', not just Nightstalkers. Combining this with the alpha reduction for the ghost translucency animation produces long periods of non-visible sprites …
=> Prevent alpha underflow and reduce Shadow translucency (bug #14503)

src/ai/lua/core.cpp, src/menu_events.hpp, src/playsingle_controller.cpp, src/playsingle_controller.hpp
Just like the FormulaAI fallback() function, this temporarily transfers control of the side to a human player.
I simply used the same exception that the FormulaAI uses for this, making it inherit from `lua_jailbreak_exception`. I have not tested it, however, which is part of why this is a PR rather than being pushed straight to master.
=> Add fallback_human() action to the Lua AI

data/gui/schema.cfg, src/actions/move.cpp, src/gui/widgets/multi_page.cpp, src/gui/widgets/multi_page.hpp, src/scripting/lua_gui2.cpp
although stacked_widget supports similar functionality this is currently
not easily doable from the lua gui2 api. In particular
1) stacked_widget cannot add pages dynamically
2) multi_page can only contain one type of widget.
3) a stacked_widget inside a multi_page is ineffective since it
generates many unused widgets
4) a multi_page inside a stacked_widget is just unhandy to use
this also contains some unrelates commits in actions/move.cpp that just happend to be on that branch.
=> allow multi_page to contienr differnt type of pages

src/gui/widgets/generator_private.hpp, src/gui/widgets/listbox.cpp
previously listbox::clear() removed all elements one by one.
This was quite ineffective since due to the listbox always-one-element-selected behviour this required calculating which is the next element in this list in the current order. Which then again requires resorting of the whole list since due to the list content change (removal) the order cache is cleared.
this could also fix https://gna.org/bugs/?25504
=> improve listbox::clear() performance.

README.md
I just changed URLs to the wesnoth.org webpages to use https instead of http.
This will make users go directly to the webpages linked, instead of automatically being redirected to the https version by the website. 
Should be very slightly better for user experience! 😊
Please note: http://manual.wesnoth.org/ redirects to https://wiki.wesnoth.org/WesnothManual, but https://manual.wesnoth.org/ breaks, so I left it unchanged.
PS: Thank you for making an awesome game!
=> Updated links to wesnoth.org to use https

src/actions/advancement.cpp, src/actions/attack.cpp, src/actions/unit_creator.cpp, src/ai/simulated_actions.cpp, src/scripting/lua_unit.cpp, src/synced_commands.cpp
we use unit_map::insert instead of unit_map::add/unit_map::replace, to minimize copying of units.
=> less unit copying

src/config.cpp, src/config.hpp
this replaced the older heterogenous lookup optmisation in config.?pp,
the advantage  is that it no longer requires different overloads for c
strings and std::string so it can easily be aplied to all config memeber
functions witout code dublication.
=> use boost::string_view in config class 

.travis.yml
this was intially added brecause it didnt compile whne it was added.
=> remove 'allow_failures' from c++14 build

changelog, data/core/units/undead/Corpse_Soulless.cfg, data/core/units/undead/Corpse_Walking.cfg, players_changelog
Fixes https://gna.org/bugs/?25673
I figure it's either this fix, or I can split the bat's [attack_anim] into 3 tags instead of 2
=> Fix base animation showing in zombie bats

data/campaigns/tutorial/scenarios/01_Tutorial_part_1.cfg, data/campaigns/tutorial/utils/utils.cfg
There are a few situations where the player ends up being unable to do anything when he attacked with the leader. He should't do that, but he can, and it may sometimes even look tempting to do that. Two solutions come to mind, either a) allowing him to end the turn or b) _somehow_ aborting the attack.
The related bugreport is [bug #25111](https://gna.org/bugs/?25111), the cases where the player has to reload. In the other cases the player could undo the moves _if he would know about that possibility._
=> Tutorial - the player can't end turns after attacking

data/core/units/undead/Spirit_Shadow.cfg
Another adjustment as part of bug #14503. Idea is to make the Shadow alpha level spend more time between 0.6-0.8 instead of 0.4-0.6. So when the Shadow's Nightstalker ability becomes active at night time, the alpha level is mostly between 0.3-0.4 instead of 0.2-0.3, making it marginally more visible.
=> Invert alpha animation for Shadow (bug #14503)

src/units/drawer.cpp
Units are rendered at 0.5 alpha when they are invisible (for example, Elvish Avengers' Ambush ability). An issue arises with the Shadow (and Nightgaunt) ghost unit which has the Nightstalker ability allowing it to be invisible at night time - in combination with its fluctuating alpha animation, it can be quite hard for the player to see at night time (https://gna.org/bugs/?14503). @beetlenaut suggests that the global alpha level for invisible units be slightly increased from 0.5 to 0.6.
So this is related to PR #984, but we are keeping this separate as this change affects more than just Shadows and I don't know the full implications of changing this value.
=> Reduce invisible units' transparency

data/multiplayer/scenarios/3p_Island_of_the_Horatii.cfg, data/multiplayer/scenarios/4p_Isars_Cross.cfg, data/multiplayer/scenarios/4p_King_of_the_Hill.cfg, data/multiplayer/scenarios/4p_Loris_River.cfg, data/multiplayer/scenarios/4p_Paths_of_Daggers.cfg, data/multiplayer/scenarios/4p_Ruins_of_Terra-Dwelve.cfg, data/multiplayer/scenarios/4p_Siege_Castles.cfg, data/multiplayer/scenarios/4p_Xanthe_Chaos.cfg, data/multiplayer/scenarios/5p_Auction-X.cfg, data/multiplayer/scenarios/6p_The_Manzivan_Traps.cfg, data/multiplayer/scenarios/6p_Volcano.cfg, data/multiplayer/scenarios/6p_Waterloo_Sunset.cfg
don't include mape size in the description since map selection screen already displays map size by itself.
canonicalize "XvsY" and "X vs Y" to "X vs. Y".
work around pango_text::set_markup_helper warnings about unescaped ampersands.
=> multiplayer maps: descriptions: cleanup

src/campaign_server/campaign_server.cpp
The mandatory use of the GPL for all things Wesnoth has long been a sticky point for contributors, especially those not contributing to core (i.e. creating UMC add-ons).  [Here](https://forums.wesnoth.org/viewtopic.php?f=2&t=42966&p=588491#p588491) are a few [examples](https://forums.wesnoth.org/viewtopic.php?f=6&t=42975&p=588173#p588173) of forum [discussion](https://forums.wesnoth.org/viewtopic.php?f=14&t=41454&p=579487#p579340), and [an explanation](http://shadowm.ai0867.net/blog/archives/54-Original-music-in-Wesnoth-content.html) of why the current state of affairs is not ideal.
There's been much talk about addressing the issue, but no action, and the only actual planned solution is to allow use of Creative Commons licensing, which still forces content creators to give up some rights …
=> Allow explicit use of any CC license for UMC assets

data/lua/wml/objectives.lua, src/play_controller.cpp
Apparently they're supposed to be able to resubstitute variables each time they're shown; even if that wasn't the original intent, it would be quite useful.
The way to do this is not parse the `[objectives]` config instantly, and then substitute variables later. There are two possible implementations of this:
* The first implementation (e9895f8a102f) runs before any time the objectives show, whether explicitly requested by the user or by simply setting `team.objectives_changed = true`. However, this has the disadvantage that `[insert_tag]` will not be reparsed, as the objectives have already been reduced to a string by this point.
* The second implementation (699853dfc3a1) instead resubstitutes the variables as part of `[show_objectives]`, which means the entire `[objectives]` config is …
=> Fix objectives with variables

src/variable_info.cpp, src/variable_info.hpp, src/variable_info_detail.hpp, src/variable_info_private.hpp
Don't merge yet.
Copied from commit message:
First off, this doesn't touch the actual functionality of variable_info. Instead, it refactors how its all
put together:
* Comments have been cleaned up and improved.
* Formatting has been fixed.
* Class/type names have been improved.
* All info visitor and range helpers have been moved to a separate file.
* apply_visitor now takes a parameter pack and owns its own visitor object.
* as_range_visitor_base  now takes a parameter pack and owns its own visitor object (not fully working yet)
* The variable_info policy types have been split into their own helper classes and their respective functionality
implemented with static functions. This makes it clearer exactly how each policy works.
* Simplified the use of type traits. The weird …
=> Refactor variable_info impl

src/CMakeLists.txt
https://github.com/wesnoth/wesnoth/issues/1613
fix this error.
https://forums.wesnoth.org/viewtopic.php?f=5&t=44455
before this commit:
```
[  3%] Built target wesnoth-core
[  7%] Built target wesnothd
[ 13%] Built target wesnoth-lua
[ 24%] Built target wesnoth-game
[ 25%] Built target wesnoth-sdl
[ 25%] Linking CXX executable ../wesnoth
Undefined symbols for architecture x86_64:
"apple_notifications::send_notification(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, desktop::notifications::type)", referenced from:
desktop::notifications::send(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, …
```
=> fix cmake compile error on macOS

changelog, doc/man/wesnoth.6, src/build_info.cpp, src/build_info.hpp, src/commandline_options.cpp, src/commandline_options.hpp, src/gui/dialogs/game_version.cpp, src/wesnoth.cpp
This add a new `--report`/`-R` switch that generate an info dump for bug reports.
This is intended to be used instead of the Game Version dialog's clipboard text report in the event that Wesnoth cannot reach the titlescreen or the dialog for some reason.
Unlike the `--version` info dump, it performs various calls to the filesystem API which have potential side-effects on the environment (namely, creating a user data directory structure if none existed before running the command). It seems highly improper for a program's `--version` switch to perform any actions other than printing text to its parent terminal, hence I thought it would be better to add a new switch with a more active phrasing, also reflected in its accompanying documentation.
Ultimately, this and its UI counterpart should …
=> Add command line switch for printing info to be included in bug reports

data/campaigns/Secrets_of_the_Ancients/scenarios/21_Against_the_World.cfg
The speed improvement comes from not storing recall list units.
Use of [break] is for readability, it doesn't seem to have a significant effect on speed.
See also https://github.com/wesnoth/wesnoth/issues/1706
=> SotA S21: Improve speed & readability of code

src/scripting/game_lua_kernel.hpp
was:
````
[  0%/4/4/515,14.101] Building CXX object src/CMakeFiles/wesnoth-game.dir/ai/composite/aspect.cpp.o
In file included from ../src/ai/composite/aspect.cpp:19:
In file included from ../src/ai/composite/aspect.hpp:25:
../src/scripting/game_lua_kernel.hpp:196:22: warning: 'my_name' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
virtual std::string my_name() { return "Game Lua Kernel"; }
^
../src/scripting/lua_kernel_base.hpp:56:22: note: overridden virtual function is here
virtual std::string my_name() { return "Basic Lua Kernel"; }
^
In file included from ../src/ai/composite/aspect.cpp:19:
In file included from ../src/ai/composite/aspect.hpp:25:
../src/scripting/game_lua_kernel.hpp:213:15: warning: 'log_error' overrides a member function …
```
=> fix -Winconsistent-missing-override warnings by clang.

data/core/about.cfg, data/lua/wml-tags.lua
Fixes https://github.com/wesnoth/wesnoth/issues/1735
Implements https://forums.wesnoth.org/viewtopic.php?f=12&t=46029
[chat] has key observable=yes/no, default yes, which controls, if the message should be visible to observers.
=> Allow showing [chat] to observers, fixes #1735

src/game_events/manager.hpp, src/game_events/menu_item.cpp, src/game_events/pump.cpp
fixup be665e29f111ad6c8ef1e8410a08608a405554cc
This isn't the best fix, ideally the code wouldn't use weak_ptr::expired to check whether an event was already handled.
=> Atttempt to fix repeated fireing of first_time_only=yes events

data/core/about.cfg, data/scenario-test.cfg
Bug #1690. This is hopefully a better error message when the user clicks "Reload and execute Lua code", and lua/code.lua doesn't exist.
=> test: Use a better error message when code.lua doesn't exist

src/gui/dialogs/unit_recall.cpp, src/gui/dialogs/unit_recall.hpp
Changed unit_recall dialogue box to sort by
1. Level
2. Experience to advance
=> Issue #1738: Changed unit_recall dialogue box 

src/game_initialization/multiplayer.cpp, src/gui/dialogs/network_transmission.cpp, src/gui/dialogs/network_transmission.hpp, src/tests/gui/test_gui2.cpp, src/wesnothd_connection.cpp, src/wesnothd_connection.hpp
TODO: remove the first commit ( testing just get erros from travis faster) before merging.
fixes #1674
This fixed a problem where at game start the host sends first a [scenario_diff]
and then a [start_game] but then the host loads the scenario config (during loadingscreen before game) and
wesnothd_connection::poll isn't called while the loadingscreen is showing. so
the other players receive the [start_game] with a lot delay since
wesnothd_connection won't send it before the the loadingscreen has finished.
At least for me this solution is also easier to implement than the alternative which would be calling poll() regulary form inside the drawing (gui2 and gamemap) code.
=>  	use a worker thread to send packages in wesnothd_connection, fixes #1674

src/formula/function.cpp
This piece fixes an actual problem:
if(res.is_empty())  {
throw formula_error("min(list): list is empty", "", "", 0);
}
This one is a preventive care:
if(v.is_empty()) {
continue;
}
Reproduces in first mission of Legend of Wesmere. Just move some units in the attack range of bottom left orcs' assassins.
=> #1763: crash in "poisoning" Formula AI (affects mainline campaign)

src/scripting/lua_unit.cpp
Without this, values full, loyal, & free will cause "unknown upkeep value of unit: " error
This currently fails to build because 'free' handling is incorrect, but I tested that loyal & full work.
Any thoughts on how to handle free?
=> Fixup lua unit.upkeep getter

projectfiles/CodeBlocks/wesnoth.cbp
I recently tried to compile Wesnoth using Code::Blocks and i got stuck due to a couple fo issues. 
Anyway, i'm not completely sure that replacing "strnlen" in this way is the best chioce.
=> Fixes to Code::Blocks compilation

src/gui/widgets/text_box_base.cpp
First argument of std::string::insert() is byte index but ime_start_point_ is num of characters.
So, if multi-byte characters is included text_cached, the text edited by IME is inserted wrong position.
This fixes the problem above.
=> Fix insert index of the text edited by IME

src/gui/dialogs/addon/manager.cpp, src/gui/dialogs/addon/manager.hpp
Fixes #1829. Additionally fixes issue where changing the type or status filters would ignore name filters and vise versa. I don't think there is an existing issue for this. Creates a get_name_filter_visibility function which returns the set of addons with a matching name. The apply_filters function applies name filters in addition to type and status.
=> Fixed Bug#1829 Name filters are applied with type and status filters

data/campaigns/Delfadors_Memoirs/scenarios/12_Terror_at_the_Ford_of_Parthyn.cfg, data/campaigns/Legend_of_Wesmere/scenarios/chapter1/02_Hostile_Mountains.cfg, data/campaigns/The_Hammer_of_Thursagan/scenarios/06_High_Pass.cfg, data/core/macros/deprecated-utils.cfg, data/core/macros/event-utils.cfg, data/lua/wml-tags.lua, src/actions/create.cpp, src/actions/move.cpp, src/actions/move.hpp, src/actions/undo.cpp, src/actions/vision.cpp, src/actions/vision.hpp, src/game_events/fwd.hpp, src/game_events/pump.cpp, src/game_events/pump.hpp, src/scripting/game_lua_kernel.cpp, src/scripting/game_lua_kernel.hpp, src/synced_commands.cpp, src/team.cpp, src/team.hpp
this adds a new tag [cancel_action], it currently only has an effect in
move actions. It can be used in enter_hex/exit_hex events to abort the
current movement, It can also be used in moveto events there is just
cancels possible following attacks if the user issued a move+attack
action.
This also changes the behaviour of moveto and enter/exit_hex event so
that they now no longer cancel the movement automatically, also
[allow_undo] no longer has an effect on whether the move is cancelled,
it only allows undoing of the move.
=> add [cancel_action], implements #1427

projectfiles/Xcode/Wesnoth.xcodeproj/project.pbxproj
I added 'autorevision.sh' script inside Xcode project. Now all targets (Release and DEBUG) will contain revision number.
I can remove it for Release targets if you want.
This script is used in CMAKE 'project' and I just added it also to Xcode project.
=> Add revision info inside macOS releases.

src/game_initialization/configure_engine.cpp
This should fix issue [#1814](https://github.com/wesnoth/wesnoth/issues/1814). 
Village gold and village support are given their values here, so in case one has map settings enabled these two variables wouldn't be set. If this happens, they assume their default value (= 1) [when the teams are built](https://github.com/wesnoth/wesnoth/blob/master/src/team.cpp#L187). 
Anyway, "use_map_settings" is already checked by the [gui](https://github.com/wesnoth/wesnoth/blob/master/src/gui/dialogs/multiplayer/mp_create_game.cpp#L716) in the lobby, so removing this if-clause should still produce the expected behaviour.
=> Set village income and support to their expected default values in mp games

src/video.cpp
clang reports a warning. This appears to be a missing return. Originally fell through resulting in null pointer reference.
=> Unused expression result

data/lua/wml-tags.lua
Stores in variable the defense of a unit on a particular terrain. If terrain is not specified, the terrain on which the units currently stands is used. (Note: it is a WML defense, so the higher it is, the weaker unit's defense is.)
* StandardUnitFilter
* loc_x, loc_y: x and y of terrain location.
* terrain: alternatively, the character of terrain.
* variable: the name of the variable into which to store the defense. default: "terrain_defense"
=> [store_unit_defense] WML tag

utils/pywmlx/state/machine.py, utils/wmlxgettext
This code should fix the issue reported at
https://github.com/wesnoth/wesnoth/issues/1785
I tested my code with an older file of my own campaign wich contained an invalid UTF-8 byte 
https://github.com/AncientLich/wmlxgettext-unoff/blob/master/wmlxgettext/test/reports/2017.06.15/05_The_Underground_Path.cfg
The invalid byte is located on the comment at line 272
>  \# da modificare - devo aggiungerci la condizione "se il turno 23 non è stato raggiunto"
That is an italian comment (the meaning is not important). What it is import is that the 'è' character wasn't UTF-8 compatible, becouse I wrote that file with a wrong text encoding while I was a windows user (now I use Ubuntu).
Now the code manage the UTF-8 decode error, and will show a proper error message, wich is, in this case:
> error: …
=> wmlxgettext: fix UTF-8 issue: #1785

src/hotkey/command_executor.cpp
This is an attempt to fix #1855 which is caused by non-ASCII characters being produced by single keys. I'm not entirely sure this is the right approach, however.
=> Use UTF8 length to decide if a TEXTINPUT is a hotkey (should fix #1855)

src/attack_prediction.cpp, src/log_windows.cpp, src/reports.cpp, src/serialization/string_utils.cpp
Using "Microsoft All Rules" but not enabling lifetime evaluation results in just a few warnings which can be fixed.
The remaining messages are in the upstream Lua and Boost packages. A couple are related to Visual C/C++ static analysis bypassing checks on OpenMP-specific code.
=> Fix a few messages from VC static analysis

src/ai/lua/lua_object.cpp, src/scripting/lua_common.cpp, src/side_filter.cpp, src/terrain/filter.cpp, src/units/abilities.cpp, src/units/filter.cpp, src/units/filter.hpp, src/variable.cpp, src/variable.hpp
This refactors the unit filter so that it now parses as much as possible when the filter is created to speed up the filter::matches function. This also make the provious optimisation of havign a 'nil' filter unnecessary.
Also i did comepletey reworite these files so looking at the diff probably won't be handy.
=> Filter refactor

data/campaigns/Heir_To_The_Throne/scenarios/05b_Isle_of_the_Damned.cfg, data/campaigns/Heir_To_The_Throne/scenarios/15_The_Lost_General.cfg
This used to be needed here so trait order would be in harmony when other
undead units were made with LOYAL_UNDEAD_UNIT, but that macro has been
deprecated and replaced here with LOYAL_UNIT. Thus, the removal
restores the harmony.
Assigned to current maintainer.
=> HttT: Remove no longer needed trait_undead

data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg
There are two conflicting attack_end events in the 2nd part of the tutorial, one of them is first_time_only. 
The way it was first the dumbo event was triggered, and afterwards an _Ouch, I got retaliation damage_  event.
In the hope to keep the code more readable I moved some filters to the manually fired event.
=> Tutorial part 2: resolving conflicting attack_end events

src/game_config_manager.cpp
proposed fix for #1899 
Crashes don't happen again.
Still getting the wml error message thrice.
Aside from that, are there code formatting issues?
=> prevent crash in case of faulty WML in mainline content (#1899)

src/utils/irdya_datetime.cpp
Closes
CID 1380147
Message was date_result.month was not initialized. Added initialization.
=> Fix Coverity Warning - Uninitialized

src/display.cpp, src/display.hpp
That is, not calculated FPS, but the actual number of frames rendered during the previous second.
=> Display actual FPS

src/CMakeLists.txt, src/SConscript, src/campaign_server/campaign_server.cpp, src/campaign_server/fs_commit.cpp, src/campaign_server/fs_commit.hpp
=> Safer campaignd file commits

src/events.cpp, src/gui/core/event/distributor.cpp, src/gui/core/event/handler.cpp, src/gui/widgets/window.cpp, src/sdl/userevent.hpp, src/video.cpp
Coverity notes that SDL_UserEvent.windowID is never initialized. Initializing to 0 on the assumption that it means 'no window' (SDL comment says 'if any', which indicates there may be a 'none' value and zero is a good guess for that).
This closes
CID 1380246
CID 1380234
CID 1380159
CID 1380152
CID 1356356
Earlier commit for these warnings only fixed the timestamp. Checked there are no additional scalars for this commit and it should not expose additional warnings.
=> Fix Coverity Uninitialized Scalar Warnings

src/display.cpp
Closes CID 1380221
Instead of assert() simply skip the animation.
=> Fix Coverity divide-by-zero warning

src/gui/widgets/tree_view_node.cpp
It is probably not possible for cur to be nullptr, but best check anyway.
Closes CID 1380176
=> Fix Coverity null dereferenced warning

projectfiles/Xcode/Wesnoth.xcodeproj/project.pbxproj
This PR fixes this:
```
10:43:06 In file included from /Users/user/.jenkins/workspace/Wesnoth/src/color_range.cpp:24:
10:43:06 In file included from ../../src/map/map.hpp:22:
10:43:06 In file included from ../../src/terrain/translation.hpp:29:
10:43:06 In file included from Headers/boost/multi_array.hpp:21:
10:43:06 In file included from Headers/boost/multi_array/base.hpp:28:
10:43:06 Headers/boost/multi_array/concept_checks.hpp:42:43: error: unused typedef 'index_range' [-Werror,-Wunused-local-typedef]
10:43:06       typedef typename Array::index_range index_range;
10:43:06                                           ^
10:43:06 Headers/boost/multi_array/concept_checks.hpp:43:37: error: unused typedef 'index' [-Werror,-Wunused-local-typedef]
10:43:06       typedef typename Array::index …
```
=> Fix for error: unused typedef in Xcode builds

data/core/terrain-graphics.cfg
Fills in some gaps with Ke* terrains, so they are more like Ce*.  Basically replace C* filter with !,Ket,!,C*,Ke*
=> [terrain_graphics] fill in Ke* gaps

data/core/terrain-graphics.cfg, data/core/terrain-graphics/new-macros.cfg
This should fix some graphics glitches, where neighbor terrain transitions bleed through under the castle walls.  Example in the attached image.
And yeah, the commits should be squashed.
=> [terrain_graphics] Castle neighbor bleed-through (sand, snow) 

.gitignore
Shared Objects files should be ignored by git as well as DLL files.
=> Add *.so to .gitignore

data/ai/lua/move_to_any_target.lua
Sanity check - is it better to vet both levels? [if target && if target.x] ?
Or not necessary?
=> Fix crash when unable to find closest enemy.

src/addon/client.cpp, src/addon/client.hpp, src/addon/validation.cpp, src/addon/validation.hpp, src/campaign_server/campaign_server.cpp, src/campaign_server/campaign_server.hpp, src/gui/dialogs/addon/manager.cpp
(See issue #2043.)
It wouldn't be proper to stuff the full list into the conventional error response, so in order to provide clients with the means to report it in a better fashion in the future (a la WML load errors report dialog, with a fancy scrolling box and an option to copy the report to clipboard and stuff), we're attaching it as an `extra_data` attribute in the `[error]` response. Naturally, only clients that are aware of its existence can handle it, so this whole patch is completely unsuitable for 1.12.
Still, some level of backwards compatibility is retained -- the `[error]` continues to be perfectly functional for incompatible clients (e.g. 1.13.10), and the details are simply missing for them.
The list would currently look like this:
```
Test_Addon_420/~illegalname …
```
=> campaignd: Send uploading clients a list of illegal names when any are found

data/tools/wesnoth/wmltools3.py
Previously, this just printed the last file name again and again.
Now we are printing the file name we are currently looking at.
This can be observed e.g. by `wmlscope --progress`.
Potentially other WML tools are affected too.
=> wmlscope: Fix the output by --progress.

.gitignore, CMakeLists.txt, INSTALL.md, SConstruct, projectfiles/VC12/README.md
At branch 'doc-from-discord-boost-discussion-20170926'.
The build documentation and scripts were slightly out of date about
Boost. This commit makes an interim update to them.
(CMakeLists.txt|SConstruct): `wesnoth` won't build using Boost lesser
than '1.50.0'. Boost 1.50.0 changed the location of version 3 of Boost
filesystem, from 'boost/filesystem/v3/' (e.g. for
'using boost::filesystem::v3::path;') to 'boost/filesystem/' (e.g. for
'using boost::filesystem::path;', enforced since the very introduction
of 'src/filesystem_boost.cpp'), making it incompatible unless using
precompiler directives for supporting backwards versions of Boost
filesystem prior than '1.50.0'. Using Boost 1.50.0 builds, but
segfaults on start up (in my mileage) (Valgrind hints about …
=> On Boost: update build scripts and documentation.

CMakeLists.txt, SConstruct, src/SConscript
This PR removes the `Optimized` build, instead allowing adding the same flags to the `cmake` and `scons` Release build.  This PR also therefore supercedes #2042 .
The `-s -flto` flags can be added to the Release build with the existing `enable_lto` option.  There is also a new option, `arch`, which allows setting what value to use for the `-march` flag.  If `arch` is not set, and the build is on Windows, then it will continue to default to `pentiumpro`, due to a previously found issue when using `tdm-gcc` and the `-O3` flag.
Clang is now also supported for building with LTO, using the `lld` linker.  In my testing however, this requires at least clang and lld version 5.  The latest Ubuntu LTS does not support building Wesnoth with clang at all, due to an ABI incompatibility with the system …
=> Removed Optimized build, improved gcc LTO support, add clang LTO support.

src/units/unit.cpp
when an object expire in mid scenario, then hp=max_hp, it's not very logic and use of object duration turn  end turn is impossible.
=> fix hitpoints being restored by heal_full after modifications expire

CMakeLists.txt, SConstruct, src/SConscript
This PR:
- Removes support for building on Solaris from scons.  This support is currently non-functional.
- Replaces the `glibcxx_debug` separate build with a `glibcxx_debug=yes|no` option for the existing `debug` build.
- Adds building with the `glibcxx_debug` option to cmake.
- Adds a description of what the `profile` build is for to scons.
=> Remove Solaris support, improve glibcxx_debug support

data/campaigns/The_South_Guard/scenarios/03_A_Desparate_Errand.cfg
All other units, which you get without recruiting in The South Guard are loyal. I think Jarek should be loyal too for consistency and because he is recalled by default in almost every single scenario. It should not affect difficulty significally.
=> Make Jarek from TSG loyal for consistency.

src/menu_events.cpp, src/mouse_events.cpp, src/mouse_events.hpp
When selecting in UI, using mouse, `show [best] enemy moves`, on a cluttered battlefield, probably mouse will land on an unit.
That be the case, when the user moves the mouse, even just a single pixel; best enemy moves highlights vanish.
This is a first try to cope with the problem. When cursor is landing on an unit, unit normal highlight gets prevented until mouse reaches an hex where there is no unit. The user can now be sure best enemy moves will not accidentally vanish when dealing with cluttered battles, while s/he can still de-highlight them straightforwardly whenever wanted.
There are field visibility and protection decisions here, that I decided not to take but delegate on the PR reviewer, that in the end of the day is more used to cope with these classes and will know better if …
=> Fix enemy [best] moves vanish on mouse move when mouse landed on unit

src/game_initialization/lobby_info.cpp, src/gui/dialogs/game_stats.cpp
If by_name and by_relation are both omitted, behave as if both were given: sort first by relation then by name.
=> Fix error: control may reach end of non-void lambda

data/core/terrain.cfg
=> terrain.cfg: Fix grammar in Rockbound Cave

RELEASE_NOTES, changelog, src/filesystem_boost.cpp
The intent is to avoid UMC authors on Windows from accidentally using backslashes and making add-ons that won't work correctly on GNU/Linux and macOS.
IMO, this change is risky enough that we should merge it for 1.13.11, not 1.13.10.
=> Disallow backslashes in file paths

src/units/filter.cpp
args.loc is the location we use for 'filter as if the unit woudl be there', still the unit is curently at args.u.get_location() so to make scoped_xy_unit  find the unit we have to give args.u.get_location()
=> fix filters using this_unit in [hides]

src/addon/client.cpp, src/addon/validation.cpp
This PR (alternative to #2070) extends and expands the blacklist with the parts we could mostly agree on.
=> Blacklist filename chars

CMakeLists.txt, SConstruct
Adds the `profiler` option, which allows specifying:
- gprof (existing)
- gcov
- [gperftools](https://github.com/gperftools/gperftools)
gperftools also has a heap profiler/checker, but I wasn't sure if that was worth adding in as well.
=> Add additional profilers to scons and the Profile build to cmake

projectfiles/VC12/wesnoth.vcxproj, projectfiles/VC12/wesnoth.vcxproj.filters, projectfiles/VC12/wesnothlib.vcxproj, projectfiles/VC12/wesnothlib.vcxproj.filters, source_lists/libwesnoth_core, source_lists/wesnoth, src/actions/advancement.cpp, src/addon/client.cpp, src/ai/default/recruitment.cpp, src/ai/simulated_actions.cpp, src/display.cpp, src/formula/formula.cpp, src/play_controller.cpp, src/saved_game.cpp, src/server/user_handler.cpp, src/sound.cpp, src/soundsource.cpp, src/units/animation.cpp, src/units/animation_component.cpp, src/units/unit.cpp
Coverity has been complaining about using rand() as an insecure function. As we're using it, this function is not insecure; but is also not a very good RNG. We're using MT19937 in a system-independant manner. But some uses of rand() were never converted. This converts them.
This closes the following Coverity issues:
CID 1356297
CID 1356299
CID 1356303
CID 1356304
CID 1356306
CID 1356312
CID 1356314
CID 1380163
CID 1380173
CID 1380179
CID 1380191
CID 1380198
CID 1380201
CID 1380210
CID 1380214
CID 1380215
CID 1380219
CID 1380230
CID 1380241
=> Finish switch to MT19937 for randomness

.gitignore
New Xcode 9 creates Index storage inside project dir. This commit makes this index ignored by GIT
=> ignore Xcode 9 Index storage

src/editor/palette/unit_palette.cpp
Supress CID 1134314 about 'code' being constant. Remove 'const' if the TODO is ever done.
=> Suppress warning about const variable

src/gui/dialogs/message.cpp, src/gui/widgets/label.cpp, src/menu_events.cpp
Coverity has been complaining that a few uses of show_message do not have their return value checked.
Casting to void supresses these warning be documenting the value is intentionally not  checked.
This closes
CID 1380185
CID 1380186
CID 1380258
=> Suppress unchecked return warning

src/gui/widgets/text_box_base.cpp
Use the idiomatic combination.
=> Reconfigure 'select all' for texts in macOS.

changelog, src/actions/move.cpp, src/display.cpp, src/display.hpp, src/synced_commands.cpp
I suspect there might be a bug in `master` since rev ad809a87571f. About a label that I remember from when I was young, and I am missing now.
Compare `master` behavior at 'https://youtu.be/h_cA_UDTGKQ' with the intention of the feature branch at 'https://youtu.be/eVxK8uNWOsg'.
See also http://github.com/wesnoth/wesnoth/pull/999 to which this follows up.
Cheers and regards,
=> Fix candidate visual bug in the announces system.

.gitignore, CMakeLists.txt, SConstruct
Adds support for compiling with Profile Guide Optimization enabled to cmake and scons using GCC and Clang.  Before submitting I tested:
- the regular release build(-O3)
- LTO
- PGO
- LTO+PGO
On Mint 18.2:
- GCC 5.4: LTO+PGO failed with a compiler segfault.
On Ubuntu 17.10:
- GCC 7.2: All builds succeeded.
- Clang 5.0: LTO+PGO failed with a compiler error, `duplicate symbol: __llvm_profile_filename`
=> Add support for PGO builds.

data/campaigns/Dead_Water/scenarios/11_Getting_Help.cfg, data/campaigns/Dead_Water/scenarios/13_Epilogue.cfg, data/campaigns/Eastern_Invasion/scenarios/15_The_Council.cfg, data/campaigns/Eastern_Invasion/scenarios/18_Epilogue.cfg, data/campaigns/Heir_To_The_Throne/scenarios/21_Elven_Council.cfg, data/campaigns/Legend_of_Wesmere/scenarios/chapter4/13_News_from_the_Front.cfg, data/campaigns/Northern_Rebirth/scenarios/02_02_Meeting_With_Dwarves.cfg, data/campaigns/Northern_Rebirth/scenarios/05a_02_Dealings.cfg, data/campaigns/Northern_Rebirth/scenarios/09b_Judgment.cfg, data/campaigns/Northern_Rebirth/scenarios/14a_Epilogue.cfg, data/campaigns/Sceptre_of_Fire/scenarios/2t_In_the_Dwarven_City.cfg, data/campaigns/Sceptre_of_Fire/scenarios/3t_The_Council_Regathers.cfg, data/campaigns/Sceptre_of_Fire/scenarios/4t_The_Jeweler.cfg, data/campaigns/Sceptre_of_Fire/scenarios/Epilogue.cfg, data/campaigns/The_Hammer_of_Thursagan/scenarios/02_Reclaiming_the_Past.cfg, data/campaigns/The_Hammer_of_Thursagan/scenarios/13_Epilogue.cfg, data/campaigns/The_Rise_Of_Wesnoth/scenarios/07_Return_to_Oldwood.cfg, data/campaigns/The_Rise_Of_Wesnoth/scenarios/11_Southbay_in_Winter.cfg, data/campaigns/The_Rise_Of_Wesnoth/scenarios/16_The_Kalian.cfg, data/campaigns/The_Rise_Of_Wesnoth/scenarios/18_A_Spy_in_the_Woods.cfg, data/campaigns/The_Rise_Of_Wesnoth/scenarios/21_The_Plan.cfg, data/campaigns/The_Rise_Of_Wesnoth/scenarios/23_Epilogue.cfg, data/campaigns/Under_the_Burning_Suns/scenarios/10_Speaking_with_the_Fishes.cfg, data/campaigns/Under_the_Burning_Suns/scenarios/13_Epilogue.cfg
Makes use of Cutscene and Cutscene_Minimal themes for all scenarios in mainline that I am aware would benefit from it.
There seems to be a slight graphical hiccup when switching to Cutscene mid scenario in the third commit.
=> Deploy Cutscene Themes

data/campaigns/Heir_To_The_Throne/scenarios/05b_Isle_of_the_Damned.cfg
Add missing comma.  Also remove the word "here" because it felt redundant.
=> HttT: fix grammar in Moremirmu's farewell

SConstruct, src/SConscript
This PR replaces the `base` build with the `use_srcdir` option, which can then be applied to all of the remaining build types.  It also replaces the use of `env` for the compiler/linker flag variables to make it consistent with what was initially requested [here](https://github.com/wesnoth/wesnoth/pull/2081#discussion_r143444015).
=> Replace base build with use_srcdir option.

data/core/editor/help.cfg
Replace the sentence to make it clear the Starting Tool marks both the team leader, and named special, locations.
Closes #2085.
[ci skip]
=> Fix editor help incomplete sentence.

src/hotkey/hotkey_command.cpp, src/hotkey/hotkey_command.hpp
Adding this overload removes a silent type conversion from 'enum scope'
to 'hk_scopes' (std::bitset<3>) in the src/help/help_impl.cpp callsite.
Fixes #2135.
=> Fix #2135: Honour the show_all_units_in_help preference during scenarios

src/game_display.cpp
If reach_map_ had been empty to begin with, reach_map_changed_ would
have been reset to false before display::process_reachmap_changes()
acted on it.
Fixes #2132.
=> Fix highlighting reachable hexes when deselecting a moved unit.

src/minimap.cpp
Fixes #1645.
It would be nice to have some UI indication (in the main map + minimap) that the unit can move into the shrouded area.
=> When movement points > vision points, don't reveal in the minimap hexes that can be moved to but aren't yet visible.

data/campaigns/The_South_Guard/scenarios/07a_Into_the_Depths.cfg, data/core/macros/objective-utils.cfg
This adds one more caption macro for [objective]s
Currently there are:
- no caption, shows under "Victory"
- "alternative objective"
- "bonus objective"
Scenario 7a in TSG is an example where none of them fits:
_"Meet with and pay the troll leader 100 gold to receive their help"_
- it's not a win condition (it was set up like this previously)
- nor an alternative to the win condition 
- bonus sounds like you should do this, everybody wants a "bonus".
Optional would be the right word. Though I'm not sure about the wording, if "optional objective" or just "objective". Into German I would translate it as just "optional".
=> add an "optional objective" caption

scons/sdl.py
With the change from SDL_mixer 2.0.1 to 2.0.2, we cannot simply check if SDL_mixer can open an OGG/Vorbis file, we must first open an audio device. [This is probably a mistake, since the documentation implies simply initializing the codec should be enough.] To avoid future problems, upgrade the feature-test program to perform a full initialization and shut-down; everything except actually playing the sound.
Closes #2137
=> Fix Scons for SDL2_mixer 2.0.2

src/help/help_impl.cpp, src/help/help_topic_generators.cpp
Fixes #2108.
`print_trait_list` is used for "Traits (2): strong, quick, intelligent, resilient" listing in the unit help pages.
=> help: Handle traits with empty names or descriptions.

SConstruct
Scons will use the values saved in the .scons-option-cache to fill in values that I do not provide myself.  For example, if I execute:
`scons wesnoth build=release enable_lto=yes ctool=gcc cxxtool=g++ jobs=6`
then
`scons wesnoth build=release ctool=gcc cxxtool=g++ jobs=6`
the second run will still have LTO enabled.
This change will allow specifying `--option-cache=""`, so that the values provided for previous runs are not saved and reused.
=> Add ability to not create the .scons-option-cache file.

src/scripting/lua_common.cpp, src/scripting/lua_formula_bridge.cpp, src/scripting/lua_kernel_base.cpp
The key value returned by lua_next, on the Lua stack, cannot be modified.
Certain tests such as lua_isstring will convert the value.
The solution is, instead of testing if they key can be converted to a string, test if it actually is a string by using lua_type.
=> Respect lua_next constraints

src/SConscript
- Removes some unnecessary lists.
- Removes `env["wesnoth_res"]` and `env["wesnothd_res"]`, since neither of those are referenced anywhere else.
- Changes how `SDLMain.mm` is added so the `wesnoth_objects` variable can be reused between `wesnoth` and `boost_unit_tests`.
=> Minor code cleanup.

src/game_initialization/create_engine.cpp, src/game_initialization/create_engine.hpp, src/game_initialization/depcheck.cpp, src/gui/dialogs/campaign_selection.cpp, src/gui/dialogs/multiplayer/mp_create_game.cpp, src/gui/dialogs/multiplayer/mp_create_game.hpp, src/gui/widgets/menu_button.cpp, src/gui/widgets/menu_button.hpp, src/gui/widgets/selectable_item.hpp, src/gui/widgets/toggle_button.cpp, src/gui/widgets/toggle_button.hpp, src/gui/widgets/toggle_panel.cpp, src/gui/widgets/toggle_panel.hpp
just like in the gui1 version opf mp create we just call a 'sync'
function whenever the user changed the selected era/scenario/mod. This
commit currently only fixes the check for era/scenario compability not
for mods.
it might also create an ininite recursion sometimes, have to investigate that.
=> fix mp depckeck (#1887, #2092)

src/font/pango/hyperlink.hpp, src/font/text.cpp, src/font/text.hpp, src/serialization/string_view.hpp
As @Vultraz mentioned in Discord, the existing link detection code may sometimes detect Pango markup as parts of links and therefore produce invalid Pango markup. For example, if we have
\<span color='white'\>\<i\>Test **https://www.example.com/</i\>\</span\>**
automatic link detection will detect the part I bolded above as a link and add the following markup:
\<span color='white'\>\<i\>Test **\<span underline='single' color='#ffff00'\>** https://www.example.com/\</i\>\</span\>**\</span\>**
And that's invalid markup, because it attempts to open tags in the order `<span><i><span>` but close them in the order `</i></span></span>`.
To fix the problem, my code takes a completely different approach. Instead of scanning for links and replacing them in one go, the steps are performed …
=> Rewrite the link detection code

.travis.yml, CMakeLists.txt, SConstruct, src/CMakeLists.txt, src/SConscript
This PR:
- Fixes an issue @singalen found when the string passed to `RemoveFlag` is empty.
- Removes the `check_compiler_has_flag` macro from cmake.  I have no particular opinion on specific flags, but the flags used should at least be consistent.
- Sets the same flags to be used by scons and cmake for `strict` builds.
More specifically, for cmake's `strict`:
- Changes -W to -Wextra.  -Wextra is the new name for -W, and has been supported since at least GCC 4.3.
- Removes -Wnostrict-aliasing.  The -Wstrict-aliasing warning is only used when -fstrict-aliasing is also used, and -fstrict-aliasing is not used anywhere.
- Removes -Wno-overloaded-virtual.  As per the comment in cmake, it was used to silence a warning from clang 3.3 and earlier.
- Restricts -Wmismatched-tags to clang, since GCC …
=> Make strict builds consistent between scons and cmake

CMakeLists.txt, src/CMakeLists.txt
This PR:
- Removes MSVC support from cmake.
- Removes the two unused options `ENABLE_TOOLS` and `ENABLE_SDL2_TOOLS`.
=> Remove MSVC support from cmake.

data/core/macros/items.cfg
Sceptre (15x4) is now stronger than the uncut ruby of fire (14x4) for
regular mainline users Thursagan and Konard II. Level 3 Konrad & Li'sar
in HttT are still exceptional users of the sceptre (18x4 & 16x4).
From discussions with zookeeper in irc.
=> Macros: Tweak sceptre damage for story reasons

src/font/text.cpp, src/serialization/string_view.hpp
We only use it in once place. At that point we can guarantee we stay in-bounds. So there is no need to use at() to check we remain in-bounds.
This eliminates a warning when building Debug for Windows (quieting Appveyor).
AI0886 had a similar issue building using GCC 6.3 on Boost 1.62
Reverting ca03818fa897a558d9ad5d9c3729404f5959029f and 0cbab6eeedff676a57191440c0b2b89b923bfaad since this changeset should correct both issues.
=> Eliminate use of string_view::at

data/campaigns/Heir_To_The_Throne/scenarios/17_Scepter_of_Fire.cfg
1. Undo now works again in the scenario.
2. Lava now works again.
3. Triggering on a moveto event was not good, as several shorter moves
would make rate of lava grow much faster than fewer longer moves.
=> HttT S17: Fix lava issues

README.md
This PR updates README.md to:
- Point to the [updated wiki page](https://wiki.wesnoth.org/Wesnoth:Copyrights) for licensing/copyright related information.  The various forum threads have also been updated to point to the wiki page, rather than having information scattered across multiple different places.
- Updated "Free" to "Open Source".  This is how it has been updated to be stated on Wesnoth's website, and it should be consistent here as well.
- Change the Manual link to be able to use HTTPS like the other links.
=> Updates to licensing info and makes a link https.

CMakeLists.txt, SConstruct, src/CMakeLists.txt, src/SConscript
This PR:
- Moves all the flags from the scons/cmake `strict` build into the regular build flags, except for `-Werror`.  This means that the only difference between `strict` builds and non-strict builds will be if warnings are turned into errors.
- Removes `-std=c99` from scons' `CFLAGS`, since cmake does not set that flag.  This affects `src/SDL_SavePNG/savepng.c`, since it's the only C source file Wesnoth has.
- Removes the `-Wno-pointer-bool-conversion` flag from scons' lua build, since cmake does not use that flag.
Additionally, cmake has another option used to add additional warning flags, `ENABLE_PEDANTIC_COMPILATION`:
- `-Wlogical-op` - Warn about suspicious uses of logical operators in expressions. This includes using logical operators in contexts where a bit-wise operator is …
=> Add strict warning options to the default build options.

SConstruct
This is no longer needed, as Travis now has SDL 2.0.4 available via the docker image.
=> Remove the scons workaround for Travis only having SDL 2.0.2

src/CMakeLists.txt
Wesnoth's lua files are all already `*.cpp`, so this forcing is redundant.  It also for some reason is only being done for the cmake+clang combination.
=> Remove logic from cmake forcing lua to be compiled as c++ for clang.

CMakeLists.txt, SConstruct
This PR:
- Adds the `pedantic` option to scons, which matches cmake's `ENABLE_PEDANTIC_COMPILATION` functionality.
- Removes the `-Wnon-virtual-dtor` and `-Wmismatched-tags` flags from cmake's `ENABLE_PEDANTIC_COMPILATION` option, since they are already included in the default build flags.
Alternatively, these flags could be added to scons' and cmake's default build flags, and cmake's separate `ENABLE_PEDANTIC_COMPILATION` option removed.
=> Adds cmake's pedantic option to scons.

data/campaigns/Under_the_Burning_Suns/_main.cfg, data/campaigns/Under_the_Burning_Suns/units/elves/Kaleh.cfg, data/campaigns/Under_the_Burning_Suns/units/quenoth/Youth.cfg, src/units/unit.cpp
With the apply_to=type in effect the amla allow an unit to upgrade without specifing in advances_to. Different amlas can be associate with upgrade but color xp bar remain purple.
In utbs the wml is use for hide this but is no perfect when the youth upgrade( purple is briefly seeing). I propose an change in source for simplify the work of addons developer who want create an unit line similar.
=> add hidden_amla option in amlas

src/gui/widgets/unit_preview_pane.cpp
To reproduce:
1. Run `wesnoth -t`
2. Open the 'recruit' dialog
3. Mouseover the green "HP:" value
4. Observe that the attack types ("arcane", "blade", etc.) appear in English.
With this patch, the attack types are translated.
=> Translate damage types in the unit_preview_pane tooltip.

data/lua/wml/harm_unit.lua, data/lua/wml/kill.lua
The [kill] tag can run animations. But it can also fire the `last breath` event, which can call [kill]. When we get back to the original [kill], the unit is gone, causing an error attempting to run the animations.
Added a check to ensure the unit is still on the map before we attempt to run the animations.
The Issue also requested that [harm_unit] pass the unit causing the harm into the [kill] tag so that `last breath` could use the secondary (killing) unit available like it does elsewhere.
Closes #2298
=> Do not access non-existent unit

data/tools/wesnoth/campaignserver_client.py
Note that this still doesn't allow the --upload
functionality to work. After this fix,
wesnoth still complaints about unordered WML.
It is believed that this is a separate issue though,
happened because of the latest simple_wml changes.
=> addon_manager: fix append_tag usage

changelog, players_changelog, src/whiteboard/manager.cpp, src/whiteboard/manager.hpp
Fixes #2303.
I left the preferences as a todo since this patch as it stands is already an improvement for SP.
=> whiteboard: Don't clear the undo stack in SP mode.

src/game_events/manager.cpp, src/game_events/manager.hpp
Instead of trying to iterate over two lists at once, just construct a new list of matching
handlers. This should fix #2310 too, since it ensures any additional events added after
iteration begins don't get executed.
=> Game Events/Manager: refactor event iteration interface

src/utils/math.hpp
'toward zero' is confusing since it can round up or down.
The correct comment is 'round half up, to the nearest integer'.
Closes #2330
=> Misleading comment

data/test/scenarios/test_event_names_and_order.cfg, src/game_events/handlers.cpp, src/game_events/handlers.hpp, src/game_events/manager.cpp, src/game_events/manager_impl.cpp, src/game_events/manager_impl.hpp, wml_test_schedule
Turns out constructing a list of matching handlers breaks some undocumented behavior, namely events being executed in the order they're added (usually the order in which they appear in the WML). It also broke certain variable substitution by moving variable interpolation wholly before any event execution, as opposed to between each event.
This commit is an experiment with an even simpler method: simply iterating through every registered handler in order, checking for a name match on each one, and if it passes, immediately executing the provided handler.
Not ready yet, still needs some polishing.
=> Further reworking of event iteration interface to try to fix #2312

src/game_initialization/multiplayer.cpp, src/game_launcher.cpp, src/gui/dialogs/multiplayer/player_info.cpp, src/server/ban.cpp, src/server/ban.hpp, src/server/server.cpp, src/server/server.hpp, src/server/server_base.cpp, src/server/server_base.hpp, src/wesnothd_connection_error.hpp
Issue #2327 raises the issue that MP moderation was never implemented. So far the following action-items have been identified:
Not all of the above were actual code issues. They are listed to note they've been checked and corrected, if needed.
Issues not addressed:
* Administrators can kick and ban themselves. This is fixable but more work than I'm willing to put in at this time. In the meantime, hey, don't shoot your foot off, OK?
* The per-IP connection limit is very weak and easily bypassed. This is fixable but more work than I'm willing to put in at this time. If someone is that determined to abuse the server, then let them or ban them.
* File handling when persisting bans is not crash-resistant in all cases. There is a short period where, should a crash occur, the file may become …
=> Implement MP Moderation

changelog, players_changelog, src/addon/client.cpp, src/addon/client.hpp, src/addon/manager_ui.cpp, src/gui/dialogs/addon/manager.cpp, src/gui/dialogs/network_transmission.cpp, src/gui/dialogs/network_transmission.hpp
This pull request is a fix for bug #2203.
The approach is to close the connection when the player cancels the download. This is the same thing that Wesnoth was doing before the GUI2 port of the addon manager, and it has zero overhead if the player *doesn't* cancel the download (unlike some other options which were suggested).
=> Addon client: close connection if the player cancels the download

src/game_events/manager_impl.hpp
Since events can be added and removed constantly, this should be more performance-friendly than
a vector since it avoids reallocations. Though, since this container only holds shared_ptrs instead
of the objects themselves, it probably doesn't make that much difference right now, but I might
switch to object-direct storage in the future. Not sure.
=> Used a deque instead of a vector for active event handlers

data/lua/core.lua
The implementation differs from already-existing
wml.variable.proxy in that it does not try to proxy table sub-fields,
and is fast & simple.
Example usage:
```lua
wesnoth.variables.test = 123
print(wesnoth.variables.test)
```
=> Lua: add variables metatable

src/reports.cpp
I have been using this locally but @Pentarctagon suggested to post it as a PR.  Here's the tooltip it changes, the image shows the listing both before and after the patch:
_edit_: The "by unit" code is commit 5af12fb6ca73bd75b598e019394cd3f592cbc6e.
=> UI: Sort the 'damage versus' tooltip by unit type.

src/gui/widgets/text_box_base.cpp
This reverts part of commit 468c6e0f494793d57b0b1264894cd7f0b0383fa2.
Ctrl+A was removed because its emacs meaning is surprising to some
people.  Ctrl+E was removed because it was the counterpart of Ctrl+A.
Ctrl+U however doesn't conflict with anything else, and it's useful
to some people (me), so reinstate it.
Discussed with @CelticMinstrel.
=> Revert part of "GUI2 Textbox: Remove the other two emacs keybindings"

data/core/terrain.cfg, src/help/help_topic_generators.cpp, src/terrain/terrain.cpp, src/terrain/terrain.hpp
=> Hide 'Rails' and 'Fake Shroud' terrains in the unit help pages when impassable

CMakeLists.txt
Fixes #2392.  This PR prevents cmake from copying over all data/sounds/images when doing a server-only installation.
=> Have cmake not copy over everything for server-only installs.

data/lua/wml/endlevel.lua, data/lua/wml/find_path.lua, data/lua/wml/harm_unit.lua, data/lua/wml/items.lua, data/lua/wml/kill.lua, data/lua/wml/message.lua, data/lua/wml/micro_ai.lua, data/lua/wml/objectives.lua, data/lua/wml/random_placement.lua, data/lua/wml/role.lua, data/lua/wml/set_variable.lua
Second iteration of the process, now handling data/lua/wml/*.lua
luacheck command used to find bugs:
`luacheck ./*.lua --globals wesnoth wml --codes --ignore 542 213`
Additionally, error code 211 (unused variables) could be ignored,
as using underscore convention `_` is controversial in
wesnoth ( see https://github.com/wesnoth/wesnoth/pull/2380#discussion_r162519341 )
Actual bugs found:
* items.lua, access of global `write_name` instead of local `cfg.write_name`
* kill.lua, typo `primary_unit` -> `primary`
* bad code style: global `i` instead of local `i`
(would conflict with 3-rd party code if it would use global `i`, too)
=> fix code problems found by luacheck

src/ai/actions.cpp, src/ai/composite/aspect.cpp, src/ai/contexts.cpp, src/ai/default/aspect_attacks.cpp, src/ai/default/attack.cpp, src/ai/default/ca.cpp, src/ai/default/recruitment.cpp, src/ai/default/stage_rca.cpp, src/ai/formula/ai.cpp, src/ai/gamestate_observer.cpp, src/ai/manager.cpp, src/ai/manager.hpp, src/ai/testing.cpp, src/game_events/action_wml.cpp, src/game_state.cpp, src/game_state.hpp, src/gui/dialogs/gamestate_inspector.cpp, src/menu_events.cpp, src/play_controller.cpp, src/playsingle_controller.cpp, src/scripting/game_lua_kernel.cpp, src/team.cpp, src/units/unit.cpp
The AI keeps references to the Lua state, and because it's global, it can outlive Lua. That can result in dangling references: such a reference is the cause of bug #2372.
The best way to avoid it is to ensure that game_state, which already owns the Lua state, also owns the AI. That way, the AI will be destroyed before the Lua state.
This is obviously a quite big change, and for that reason I'm submitting it as a pull request instead of pushing it directly to master.
=> Make AI manager a singleton

data/core/hotkeys.cfg
Switch quit to title-screen from Ctrl+Q to Ctrl+W (OSX already uses Cmd+W) and quit-to-desktop from Ctrl+Shift+Q to Ctrl+Q.
=> Align default quit hot-key with conventions (fixes #2397)

CMakeLists.txt
I removed this from scons a while ago, though it looks like I forgot or didn't notice that cmake does the same.
=> Remove checking for a different SDL2 minimum version.

src/gui/core/canvas.cpp
The previous cleanup didn't handle the case when w or h is zero,
but resize_mode is not stretch.
=> Fix bug introduced in code cleanup commit 5e0c3056d

CMakeLists.txt, SConstruct, packaging/wesnoth.appdata.xml
With the adition of this wesnoth will show more information in software centers on linux.
Here an example from gnome-software:
The text shown is from the wiki (and thus the file is under GFDL license)
We would still need an email for the `update_contact` field, it should be an valid email address.
The 'Localized in your Language' is not properly detected for languages other than English, I wonder if it is related to #2213 or some other black magic.
As for the id:
It should ideally be of the scheme tld.developer.product
It seems like the comments and the rating in the software centres are bound to the id, so, if the id would be org.wesnoth.wesnoth-1.xy then each new release will start from scratch again.
Linux packagers will need more than one, maybe this is an alternative: …
=> appdata file for appstream software centers

src/scripting/game_lua_kernel.cpp
It was calling the getter instead of the setter.
=> Make [cancel_action] set_action_canceled (fixes #2430)

data/multiplayer/scenarios/2p_Clearing_Gushes.cfg
On this map, side 1 starts at the bottom, while side 2 starts at the top. The naming of the teams assumed the opposite. Another check mark on issue #2453.
=> Fix 2p - Clearing Gushes team names

.travis.yml
Scons makes this simple - all the object files are placed in `build/release/`, and the `build/sconsign.dblite` file keeps track of the md5 sum of each file built. This then means all that's necessary to prevent scons from doing a full rebuild each time is to cache the `build/` directory.
Keep in mind however, that this does not make the actual compiling faster, it just means that most of the time fewer things will need to be compiled. Any change that would trigger a rebuild of most or all of the source files will still take just as long as before.
---
The (c)make builds do not benefit from this partially because they put their compiled object files into a different directory(so they aren't being picked up right now anyways), but also because to my understanding git does not preserve the …
=> Enables travis to cache scons' build/ directory.

SConstruct
When ccache is enabled, env["CC"] becomes - `'CC': '$CCACHE gcc'`
=> Fixes LTO/PGO options not being used when ccache is enabled.

src/controller_base.cpp
UNIXes (namely, Linux and other non-Windows, non-macOS) were scrolling horizontally the incorrect direction on the game map. This addresses a problem that was introduced in #1754. Windows and macOS keep the new behavior where other platforms keep the original behavior.
=> Fixes event scrolling per issue #2218

projectfiles/Xcode/Wesnoth.xcodeproj/project.pbxproj
`$(PROJECT_DIR)/Headers` is included in `System Header Search Path` so this is just redundant duplicate.
=> Remove duplicated headers search path

changelog, src/campaign_server/campaign_server.cpp
Fixes issue #2444.
Clients may send an empty passphrase, especially if they do not do as the mainline client and generate a random one to substitute in the .pbl. An empty string is still hashable, but the server is really not supposed
to allow an empty passphrase so we should just reject those. It's also a good warning sign against broken clients -- like wesnoth_addon_manager right now.
=> campaignd: Reject empty passphrases

data/core/macros/deprecated-utils.cfg, data/lua/core.lua, projectfiles/VC12/wesnoth.vcxproj, projectfiles/VC12/wesnoth.vcxproj.filters, projectfiles/VC12/wesnothlib.vcxproj, projectfiles/VC12/wesnothlib.vcxproj.filters, source_lists/libwesnoth, source_lists/wesnoth, src/deprecation.cpp, src/deprecation.hpp, src/formula/formula.cpp, src/formula/string_utils.cpp, src/formula/string_utils.hpp, src/scripting/lua_common.cpp, src/scripting/lua_common.hpp, src/serialization/preprocessor.cpp, src/serialization/preprocessor.hpp
This extends the deprecation functionality (formerly implemented only in Lua) to the C++ core and adds a `#deprecated` preprocessor directive which, when used in a macro definition, will mark it deprecated so that a warning is printed on each use. (I'm not sure the implementation is quite the best; in particular, it doesn't currently give you the file and line number where it's used.) If used outside of a macro definition, the directive instead prints a deprecation warning applying to the entire file.
This is not ready to merge for one other reason: the second commit breaks the `$(...)` formula substitution syntax. The reason is that I need to be able to use string substitution syntax from the wesnothlib target (because the preprocessor is part of that target, and it depends on …
=> Deprecation handling for the wesnoth preprocessor

data/tools/wesnoth_addon_manager
allow overriding keys in _server.pbl
Example usage:
```
wesnoth_addon_manager \
--port 1.13.x \
--upload ~/.local/share/wesnoth/1.13/data/add-ons/example \
--pbl-override version "$(git describe --tags)" \
--pbl-override description "$(cat avoid_copy_paste_with_WML)" \
--pbl-override passphrase "in contrary to server.pbl, this is secret"
```
Downsides: user has to be aware that specifying
passwords as CLI arguments is not safe in multi-user environment.
If we're really-really serious about it, we should parse
values from environment variables then..
I wouldn't bother though.
fixes GH-2485
EDIT: fixed typo.
=> addon_manager: allow overriding keys

.travis.yml
This fixes the xcodebuild version error, since `gcc` is actual compiler being used, and gets rid of the `BUILDER` env variable since it was redundent with `TOOL`.
It also puts the xcode build first, since it is uncached and will likely run the longest - having the longest running build start last doesn't make a whole lot of sense.  That said, a quick google seems to indicate that xcode and ccache should be able to work together, so I'll probably poke at that this weekend.
If there are no objections, I'll merge this.
=> Touch-up for xcode build.

.travis.yml, docker_run.sh, projectfiles/Xcode/ccache-clang, projectfiles/Xcode/ccache-clang++
Also sets it to use clang rather than gcc.
---
[Without cache](https://travis-ci.org/Pentarctagon/wesnoth/builds/345424715)
[With cache](https://travis-ci.org/Pentarctagon/wesnoth/builds/345439211)(best case scenario, no recompiling needed)
`CCACHE_MAXSIZE` is set to 2 GBs here, rather than the 200 MBs used for the cmake+ccache builds, because xcode's Release build contains the `-g` flag.  As a result, the size of ccache's cache (before travis compresses it) is [1.3 GBs](https://travis-ci.org/Pentarctagon/wesnoth/builds/345439211#L5902).
=> Enable use of ccache for xcode build.

src/playsingle_controller.hpp
pr to make sur ethis doesn't contain any syntax errors.
=> fix reset_gamestate_exception not inheriting from std::exception

src/game_state.cpp, src/game_state.hpp, src/play_controller.cpp, src/playsingle_controller.cpp, src/replay.cpp, src/replay.hpp, src/scripting/game_lua_kernel.cpp, src/server/game.cpp, src/server/game.hpp
as title says.
Old post:
> doesn't work yet since the wesnothd code still needs to be updated. also i'm still unsure about the best api, i coul eigher make it a parameter to wesnoth.end_turn or add  seperate function set_next_playerr_number
=> allow specifying the next player number in end_turn #1392

src/image.cpp, src/image.hpp
Add support for using a [Data URI](https://en.wikipedia.org/wiki/Data_URI_scheme) in place of a filename. Addresses #1098.
There are currently 2 test add-ons on the 1.13 server using this for their icons (1 along with an IPF).
=> Add support for data URIs as images

data/campaigns/Legend_of_Wesmere/utils/deaths.cfg
For example, when Kalenz died he'd say to himself "I grieve that
I have failed you, my lord Kalenz..." followed by "Farewell Kalenz".
I'm sure that I've already seen this bug reported somewhere, but
can't find it now.
Also use speaker= instead of id=.
=> LoW Prevent the 'generic loyal' last breath triggering for main chars

RELEASE_NOTES, changelog, src/controller_base.cpp, src/editor/controller/editor_controller.cpp, src/editor/controller/editor_controller.hpp, src/game_events/menu_item.hpp, src/game_events/wmi_manager.cpp, src/game_events/wmi_manager.hpp, src/hotkey/command_executor.cpp, src/hotkey/command_executor.hpp, src/hotkey/hotkey_handler.cpp, src/hotkey/hotkey_handler.hpp
When the player holds a key down, the OS generates multiple key press and text input events. We can't assume that every such event is a real key press; instead, we need to track whether there has been a key up event since we last sent a key press event.
This PR fixes bug #1711.
I also moved `hotkey::execute_command()` into the `hotkey::command_executor` class, and renamed the existing member function of same name to `do_execute_command()`. I did that because the `command_executor` class was the best place to store the "press event already sent" flag.
=> Don't consider input events as keypresses without release in between

changelog, src/gui/dialogs/lua_interpreter.cpp
Fixes #2434.
Not much to say here since the code is pretty self-explanatory. The regular log is still needed since the UI needs to display text with markup enabled.
=> gui2/lua_interpreter: Maintain a raw console log for copy-to-clipboard

utils/travis/docker_run.sh, utils/travis/steps/script.sh
Travis looks at the return code of the final command run, and since printing the ccache statistics never fails, building would never be considered as failing.
=> Fix for failed ccache builds being considered successful.

.travis.yml, utils/travis/docker_run.sh, utils/travis/steps/script.sh
Travis runs all commands in .travis.yml in its own wrapper script, so by sourcing steps/script.sh and then using exit explicitly, it resulted in the entire travis wrapper immediately terminating.  With steps/script.sh no longer sourced, using exit works as expected again, and only exits steps/script.sh rather than quitting everything.
With that addressed, it's also possible to re-add printing the ccache statistics after the build ends.
---
An example of when it quit immediately: https://travis-ci.org/wesnoth/wesnoth/jobs/348757536
A test with this fix where I hard-coded it to exit with 0: https://travis-ci.org/Pentarctagon/wesnoth/jobs/348801187
And another test hard-coded to exit with 65(xcodebuild's compile failure exit code): https://travis-ci.org/Pentarctagon/wesnoth/jobs/348805244
=> Don't source steps/script.sh.

utils/travis/mp_test_executor.sh, utils/travis/steps/script.sh
Currently the MP unit tests will randomly fail due to one of the two background wesnoth instances failing video initialization.  All unit tests require the display server to be initialized however, or they fail with the same error as the MP tests sometimes fail with.  However, the MP tests are the only tests to randomly fail due to video initialization, while for the same travis job the WML unit tests (which run before) and the boost unit tests (which run after) are still able to be successfully completed.
Therefore, the video initialization failures are not entirely random, and the MP tests are also the only tests that experience this failure while also being the only tests that have more than one instance of wesnoth running simultaneously.
tl;dr: the attempted solution here is to sleep …
=> Attempt to fix suspected race condition when running MP tests.

src/actions/attack.cpp, src/gui/dialogs/attack_predictions.cpp, src/reports.cpp, src/units/abilities.cpp, src/units/attack_type.hpp
This refactors ability tests to use a passed-in unit instead of
searching for the unit on the map based on its location.
While it does fix #2247, I am not confident that this won't also
have some undesirable side-effects.
=> Don't assume unit is on the map when testing ability active

changelog, src/addon/info.cpp, src/addon/info.hpp, src/campaign_server/campaign_server.cpp
This adds a `tags=` attribute to the pbl WML that can be used to specify comma-separated tags to let users filter on them on the Add-ons Manager.
We don't do anything fancy with the tags at the moment since they can be matched with the existing filter algorithm without any changes, with the caveat that the word separator the filter box uses is whitespace instead of commas -- meaning that to match multiple tags they must be specified with spaces between them, in any order, and that pasting the tags from the WML into the filter box will not yield a match as some people might expect.
There is also no UI for the tags right now other than the filter box, so they are little more than an implementation detail hidden from the user.
See also issue #2565.
=> campaignd: Add support for free-form tags on add-ons

src/game_initialization/flg_manager.cpp, src/game_initialization/flg_manager.hpp
it previously only worked if both leader_lock and no_leader were set to yes.
from looking at the code i wonder what currently is the point of no_leader at all. I think no type= attribute together with leader_lock=yes should have the same effect? 
#2604
=> fix no_leader having no effect

utils/wmlxgettext
This new "release" of wmlxgettext will only contain minor changes:
- fixed some help text messages (--help option).
- the help message will not show anymore the --DMode option, wich is now hidden. This option flag, infact, does nothing useful for an end-user, and listing it and explaing what it does could be only confusing for the end-user. A (very) brief explaination of what --DMode does is now moved from the help message to the source comment.
- wmlxgettext --version is changed (to 2008.03.09) even if the changes are very very minimal.
=> help messages fix

data/campaigns/Legend_of_Wesmere/scenarios/chapter2/07_Elves_Last_Stand.cfg, data/campaigns/Legend_of_Wesmere/scenarios/chapter2/08_Council_of_Hard_Choices.cfg
In multiplayer mode, the LoW campaign has multiple start points, and some
persistent storage that stores the characters at the end of a chapter, so that
a new game starting from the next chapter starts with those stats.
The data for chapter 2 wasn't saved, because the campaign tried to create it in
a cutscene scenario that doesn't have the expected sides.
=> LoW save the persistent multiplayer data for chapter 2 (fixes #2637)

packaging/wesnoth.desktop
similar to the extra options which Firefox has
with an right click one can launch the editor now
one could as well add an "cheating mode" option for -d
Maybe to some Developers an desktop action for the test scenario is useful too?
(just for inspiration, not to be added to the PR)
Many distributions use modified desktop files, and add a 2nd
to launch the map editor. I think that's a better idea, because
it's less hidden than this feature. However, I think one doesn't
out-rule the other.
The translations are taken from downstream's desktop files for
the map editor - unfortunately they aren't complete
Basically I think this can go in as is.
=> Add a way to launch the map editor with the same desktop file

src/gui/widgets/text_box_base.cpp, src/gui/widgets/text_box_base.hpp
In SDL_TextEditingEvent, size of editing_text is limited.
If length of composition text is more than the limit, it is separated to multiple SDL_TextEditingEvent.
Current code don't assume the multiple event so this requests fix it.
=> Fix #2619, text_box_base: adapt to separated SDL_TextEditingEvent

src/units/unit.cpp
this fixes 2 issues:
1) previously code like
```
[object]
x,y=5,5
id=a
[effect]
apply_to=loyal
[/effect]
[/object]
[remove_object]
x,y=5,5
object_id=a
[/remove_object]
```
would leave the unit at 5,5 with a loyal upkeep even though the object was removed
2) fixes #1779
=> reset units upkeep on type change

src/CMakeLists.txt
This works around some issue when statically linking against boost for builds for flatpak and the steam runtime.  Follows the logic added to scons in e637c55 - APPLE is excluded explicitly here since ICU isn't supported there.
=> Explicitly link to ICU libraries for Linux.

src/font/text.cpp, src/font/text.hpp, src/gui/widgets/text_box_base.cpp
This commit fixes segfault when type characters more than limit by Input Method Editor.
pango_text.set_text() is not check whether the text over the maximum length, so change it to insert_text()
=> text_box_base: Fix segfault when type characters more than limit by IME

src/units/drawer.cpp
this should probably be opimized later so that it does not need the config lookup on each redraw, but that can be done 1.13.12
=> add bar_offset_x/y to [unit_type]

data/campaigns/Legend_of_Wesmere/scenarios/chapter4/14_Human_Alliance.cfg
Objectives: note that the death of Galtrid is a losing condition
Dialog: the following conversation happened on both turn 1 and turn 9.
Having 6 repeated messages in a row gave a strong sense of deja vu,
and I thought that a bug had repeated an event. This commit cuts the
repetition.
* Elf: "Kalenz! We come to fight beside you!"
* Kalenz: "Where is the rest of the elvish army? ...
* Elf: "The Great Council has decided it was too risky ...
* Landar: "That is well! If the Ka’lian is too fearful or blind ...
* Cleodil: "It is not well that we have become so divided as this."
* Kalenz: "No, it is not. But ...
=> LoW S14 Objectives and edit repetitive dialog (ok for string freeze)

projectfiles/Xcode/Wesnoth.xcodeproj/project.pbxproj
Before it used UTF-16 and for some reason after compiling `InfoPlist.strings` was filled with subsequence of Chinese characters.
After switching to UTF-8 it started working.
@ancestral found this issue first and I have problems because of that in codesigning process @singalen .
After merging to master, I'll also PR it to wesnoth-1.14 branch
=> Fix InfoPlist.strings encoding

utils/travis/steps/script.sh
This removes the -g option from the xcode travis build, since debugging information isn't needed and the increased size was causing the cache to timeout when compressing and uploading it.  ccache max cache size is also decreased from 2 GBs to 200 MBs, which matches the linux+cmake builds.  Fixes #2670.
---
This also supersedes #2714, since I didn't know I could set this myself.
=> Remove debugging symbols from Travis xcode build.

projectfiles/Xcode/Fix_Xcode_Dependencies, projectfiles/Xcode/Wesnoth.xcodeproj/project.pbxproj
To be exact, `libboost_timer-mt.dylib` is new dependence of `libboost_unit_test_framework-mt.dylib` and `libboost_chrono-mt.dylib` is dependence of `libboost_timer-mt.dylib`
=> Add new unit_tests dependencies

.travis.yml
This is the current default, and even though the job uses scons this also sets the osx version to use.  Therefore it's better to set it explicitly in case the default changes at some point.
---
https://docs.travis-ci.com/user/reference/osx/#OS-X-Version
=> Explicitly set osx_image for osx+scons job.

src/controller_base.hpp, src/playmp_controller.cpp, src/playmp_controller.hpp, src/playturn.cpp, src/playturn.hpp, src/playturn_network_adapter.cpp, src/playturn_network_adapter.hpp
this add a process_network_data in play_slice() whihc is called quite often, in particular during animations and [delay] so you can now see chat of other players. #1856
=> fix chat during chat & animations

src/gui/widgets/text_box_base.cpp, src/gui/widgets/text_box_base.hpp
The cause of #2694 is that ime_in_progress_ is not disable when text is deleted by Backspace or Delete key.
This PR fixes it and several code cleanup:
* Remove ime_length_
* Rename ime_in_progress_ to ime_composing_
* Use is_composing() instead of raw ime_in_progress_ 
The cleanup above shouldn't affect behavior of text_box.
=> Fix #2694, text_box: deleted text is restored during input method is activated

CMakeLists.txt, SConstruct, src/CMakeLists.txt
Commit dfc42e8a8dd550ca04ae16e2d2d7ebffbba0bc21 removed said code since Wesnoth can use `IMG_SavePNG()` from SDL_image 2.0 instead. However, the author left the build-time configuration options intact, and also part of the necessary code for CMake to link Wesnoth against libpng.
Note that this change also eliminates an unnecessary direct link-time dependency on libpng using both CMake and SCons.
=> cmake, scons: Drop option to enable or disable the removed SDL_SavePNG code

src/replay.cpp, src/synced_user_choice.cpp
this mainly effects wesnoth.synchronize_choices:
previously the client would not process incoming choices from other
players while it was exeucting its own local choice (usually a dialog).
The problem this commit fixes is that with the old behaviour any choice
from another player would block the incoming queue, in particular
chatmessages after that command would be delayed until the
wesnoth.synchronize_choices is finished.
=> pull remote user input even if we are doing a local choice.

projectfiles/Xcode/Fix_Xcode_Dependencies
This can be also merged to 1.14
=> Remove redundand cp from Fix_Xcode_Dependencies

data/campaigns/The_Hammer_of_Thursagan/scenarios/12_The_Underlevels.cfg
This matches with the "Another old caved-in passageway..." event
around line 835, the trigger is on 55,33 and the walls that open are
[terrain]
x=55,55
y=34,35
terrain=Uu
[/terrain]
Debian bug #483893, for which the original fix in
4c473187e658607b17c113d66b2bf549e48e41e5 changed the wrong digit.
=> THoT S12 Put the sneak-passageway's door on the right hex

docker/Dockerfile-travis-1604-master, utils/travis/steps/install.sh
This allows having multiple Dockerfile-base-* files without also needing to add a separate Dockerfile-travis-* file due to the FROM line changing.
=> Create travis dockerfile in the travis script step.

changelog.md, data/campaigns/The_Hammer_of_Thursagan/scenarios/12_The_Underlevels.cfg
Taking the chest south of the start hid the door and chest that are
north of the start.
The sneak-door opened much earlier in the level, allowing the undead
from the south-east lich to go north to the spider room.  The ghosts
and nightstalkers that are supposed to ambush the player's forces in
the south (after opening the 3-hex door) instead go north and end up
joining the spider fight.  The slower-moving undead also go north,
and are easily fought one-by-one in the sneak passage instead of the
south-east.
[ci skip]
=> THoT S12 Fix some "x=" tests that should be "x,y=" tests (for master branch)

src/actions/attack.cpp, src/gui/dialogs/unit_attack.cpp
this removes what seems to be a rather useless opinition in
battle_context::battle_context since choose_attacker_weapon woudl
basicially just return 0 in that case.
fixes #2801
=> fix filter not working in [disable]

src/addon/client.cpp, src/addon/validation.cpp, src/desktop/windows_tray_notification.cpp, src/font/marked-up_text.cpp, src/font/marked-up_text.hpp, src/font/text.cpp, src/font/text.hpp, src/gui/core/event/dispatcher.cpp, src/gui/core/event/dispatcher.hpp, src/gui/core/event/distributor.cpp, src/gui/core/event/distributor.hpp, src/gui/core/event/handler.cpp, src/gui/widgets/password_box.cpp, src/gui/widgets/password_box.hpp, src/gui/widgets/text_box.cpp, src/gui/widgets/text_box_base.cpp, src/gui/widgets/text_box_base.hpp, src/hotkey/hotkey_item.cpp, src/preferences/credentials.cpp, src/savegame.cpp, src/serialization/ucs4_convert_impl.hpp, src/serialization/ucs4_iterator_base.hpp, src/serialization/unicode.cpp, src/serialization/unicode.hpp, src/serialization/unicode_cast.hpp, src/serialization/utf8_exception.hpp, src/server/player_network.cpp, src/tests/test_serialization.cpp, src/utils/markov_generator.cpp, src/utils/markov_generator.hpp
This changes:
```
utf8::char_t   ->  char
utf8::string   ->  std::string
utf16::char_t  ->  char16_t
utf16::string  ->  std::u16string
ucs4::char_t   ->  char32_t
ucs4::string   ->  std::u32string
```
utf16::string and ucs4::string are now proper strings instead of vectors of characters too.
In order to get this change to compile at all, I needed to add a ucs4_convert_impl::convert_impl
specialization for wchar_t alongside the new char16_t specialization; both point to the same
conversion implementation type.
This commit doesn't do any additional cleanup. I'm sure if we looked, we could get rid of a
lot of the custom conversion code and probably a bunch of stuff that might have had to do with
supporting utf16::string and ucs4::string being vectors instead of basic_string specializations. …
=> Convert custom unicode type aliases to proper C++11 types

data/campaigns/Legend_of_Wesmere/lua/wml_tags.lua
3783693cbe95be6c51553dfa71bf0ecd5ed8116f was a general rename of
'V' to 'vars', and this line was missed. It caused an error at the
start of S09.
[ci skip]
=> LoW S09 Fix a bug introduced in Lua cleanup 3783693cb

data/campaigns/Legend_of_Wesmere/scenarios/chapter3/09_Bounty_Hunters.cfg
This uses the new `wesnoth.format_conjunct_list` function to implement the functionality. Needs to be tested, but there's no hurry since it's destined for 1.14.1.
=> LoW: Fix translation error in conjunct list (fixes #2833)

changelog.md, players_changelog.md, src/controller_base.cpp, src/controller_base.hpp, src/hotkey/command_executor.cpp, src/hotkey/command_executor.hpp
This is a fix for #1736. I have verified locally on GNU/Linux that the commit fixes it.
The underlying problem in #1736 is that two input events are generated for the same keypress, and this pull request drops the duplicates at the hotkey manager level.
Because the hotkey manager has traditionally received input events one-by-one, I needed to add a queue of input events. `controller_base` is now a pump monitor: when the event pump is done sending events, `controller_base` tells the hotkey manager to run queued commands. The hotkey manager drops duplicate commands at that point, before running the remaining commands.
=> Drop duplicate hotkey commands

data/campaigns/Dead_Water/units/Brawler.cfg
This looks trivial, and looking through the docs it should work this way.
But I see that 001fcdc changed only one event, which makes me wonder if the 2nd was missed or if there was a reason for it.
=> stun special edit

src/ai/default/recruitment.cpp, src/ai/default/recruitment.hpp
Units on the recall list are treated as recruits by the AI. The code
previously did not check whether a unit it worth being recalled until
after it makes the decision which unit type to recruit/recall. If it
then can only recall, but not recruit units of that type and all of
them are deemed not worth it, the entire recruitment CA is disabled
(via black listing), meaning recruiting is abandoned also.
This commit fixes this by checking the unit value vs. the recall cost
before putting recalls on the recruitment list.
=> AI recruitment: fix units on recall list interfering with recruiting

.travis.yml, docker/Dockerfile-base-1804-master, run_wml_tests, src/config.hpp, src/gettext.hpp, src/serialization/base64.cpp, src/serialization/string_view.hpp, utils/travis/docker_run.sh, utils/travis/play_test_executor.sh, utils/travis/test_executor.sh
Though given 00d87f8fe4078ffd84fcdc0d73fcc2104efef1e7 I would say this is better than nothing.
---
The checks for `Could not initialize SDL_video` were added since, for whatever reason, that error was [showing up at random](https://travis-ci.org/Pentarctagon/wesnoth/jobs/363709778#L2586) for everything *except* the mp tests.  The error never occurs twice in a row, [Xvfb](https://travis-ci.org/Pentarctagon/wesnoth/jobs/365380422#L2350) is running, and explicitly setting [SDL_VIDEODRIVER](https://wiki.libsdl.org/FAQUsingSDL#Linux) to x11 results in it instead saying that [x11 is not available](https://travis-ci.org/Pentarctagon/wesnoth/jobs/365380422#L3099).
Suffice it to say, I assume this is not a Wesnoth issue.
=> Adds a c++17 build using the pre-release Ubuntu 18.04.

data/campaigns/tutorial/scenarios/01_Tutorial_part_1.cfg
The comment at the start of 01_Tutorial_part_1.cfg wasn't immediately
before a string, so the hint for translators wasn't in the file that
goes to the translators. Fix it so that the tutorial shows working
usage of "# po:" style comments; this is probably more help to people
using the tutorial as a reference for WML, rather than the translators
themselves.
=> Tutorial: fix the overall translation hint comment

data/campaigns/Liberty/scenarios/01_The_Raid.cfg
... Quite some time ago I had a few PRs about weapon name changes for core units, mostly bandits.
This adjusts the weapon names of the campaign heroes to better match their portraits:
Harpers weapon is called club on the higher levels as well.
Baldras weapon is clearly a mace.
The female village leader .... ... well, what is it? I changed it for mace too, instead of a morning star.
=> Adjust the weapon names of the heroes to better fit their portraits

CMakeLists.txt, SConstruct
Otherwise, if we build with sanitizers and optimizations, the sanitizer stacktraces can become quite hard to read.
=> cmake: if sanitizers are enabled, also add -fno-omit-frame-pointer and -fno-optimize-sibling-calls.

changelog.md, data/gui/window/logging.cfg, src/gui/dialogs/log_settings.cpp
This adds a fifth radio button for disabling individual log domains in the Logging Options dialog from Advanced Preferences.
Once approved and merged I can backport it to 1.14 if this is something that would be deemed useful to have there.
=> Add support for disabling log domains in the Logging Options UI

.travis.yml, CMakeLists.txt, utils/travis/docker_run.sh, utils/travis/steps/install.sh, utils/travis/steps/script.sh
Not copying in the `po/` directory ends up saving ~30-40 seconds per non-NLS linux job.
=> Travis nls both

data/campaigns/Secrets_of_the_Ancients/scenarios/02_Dark_Business.cfg, data/campaigns/Secrets_of_the_Ancients/scenarios/08_Carcyn.cfg
**(NOTE: a changelog patch is not provided in order since it's going to become a merge conflicts minefield in a matter of days.)**
This restores the changes from the following commits:
* "SotA S2: fixed inconsistency between unit name and dialog (fixes #2844)" - commit ab9f29a7a44372a3e3703fd842740a9b425b6f5f
* "SotA S8: fixed inconsistent Ghost name (fixes #2846)" - commit fc6c3ac04b899b4c7f629a1cd8d80101c7cbb20c
=> SotA: Restore fixes for issues #2844 and #2846 on 1.14

data/gui/window/logging.cfg
Fixes #2837 on 1.14. This cannot be merged in 1.14 until after 1.14.0 is tagged and announced because of the active string freeze.
The master version is already merged (see commit 3967fd190e60b59cb9017bf4013a177dfcb44fdd).
=> gui2/log_settings: Make log options tooltips translatable

src/CMakeLists.txt
Fix for an issue reported [here](https://forums.wesnoth.org/viewtopic.php?f=5&t=48065#p627097).  I assume this should be cherry-picked over to 1.14 as well.
=> Fix cmake compiling with spaces in directory names.

CMakeLists.txt, SConstruct
Which results in the following:
```
hardening-check wesnoth
wesnoth:
Position Independent Executable: yes
Stack protected: yes
Fortify Source functions: yes (some protected functions found)
Read-only relocations: yes
Immediate binding: yes
```
=> Add option to build wesnoth with hardening options.

data/campaigns/Two_Brothers/lua/muff_toras_move.lua, data/campaigns/Two_Brothers/scenarios/02_The_Chase.cfg
I've disabled the elves and put a bunch of player's units close to the undead, so that one can test the new AI right from the beginning, without having to play through the first part of the scenario.  Those changes will be removed before merging, of course.
=> AToTB Chase: add custom AI controlling Muff Toras

CMakeLists.txt, SConstruct
Use of this feature with GCC in particular causes the stack to become marked as executable.
=> Warn about use of trampolines for nested functions.

data/campaigns/tutorial/scenarios/01_Tutorial_part_1.cfg
There have been reports of players who mistakenly went back to the keep when they were instructed to go to the village, and vice-versa (see #3039).
This confusion leads them to assume there's a bug in the game when they see they cannot end the turn, sometimes even retrying/undoing but consistently repeating the same thing without realizing they were going to the wrong tile. 
Examples:
- https://steamcommunity.com/app/599390/discussions/0/1696046342853921782/
- https://steamcommunity.com/app/599390/discussions/0/1696046342859863684/
This is just adding labels to make sure people don't confuse where to go.
Some new players might find confusing that what looks like a single house is considered a village.
=> Tutorial: add labels to villages and keep

data/campaigns/The_South_Guard/scenarios/07a_Into_the_Depths.cfg
Closes #3030. Since the trolls are on a different side, the event wouldn't trigger if they spotted Mal M'brin.
=> Fix dialogue not triggering in TSG 'Into the Depths'

data/campaigns/Son_Of_The_Black_Eye/scenarios/01_End_of_Peace.cfg, data/campaigns/Son_Of_The_Black_Eye/scenarios/17_The_Human_Attack.cfg
To fit the tweaks suggested in this thread: (https://forums.wesnoth.org/viewtopic.php?f=12&t=46460#p614551), there are three changed to make in the campaign Son of the Black Eye.
1. In the story of Scenario 1, it says "fourth year of his leadership" (from Rahul). It need to be changed to the fourteenth.
2. & 3. In Scenario 17, Kapou'e says, the killing of his father was twenty seven years ago. According to the tweaked timeline, it is just seventeen years ago.
I checked the surrounding campaigns, but didn't find anything else to be tweaked due to the timeline changes.
Why exactly I suggested the changes in the first place, can be read in the linked thread.
If these changes get accepted, then the timeline in the wiki has to be updated accordingly.
=> Change year numbers in SotBE according to timeline tweaks

data/campaigns/The_South_Guard/scenarios/02_Proven_by_the_Sword.cfg, data/campaigns/The_South_Guard/scenarios/07a_Into_the_Depths.cfg
Deoran is able to recruit peasants during the whole campaign, it was discussed to remove them from the recruit list after they leave Westin (Sc2).
=> fixes Issue #3051 (Recruitable Peasants in TSG)

data/campaigns/Northern_Rebirth/scenarios/05a_01_The_Pursuit.cfg
Fix for #3117: Malifor damage event now occurs on defence as well as attack
Fix for #3116: doors to the study can now be opened from inside
=> NR5_1: Fixes to Malifor attack and secret door events

data/campaigns/Under_the_Burning_Suns/scenarios/05_A_Subterranean_Struggle.cfg
From #3077:
* Moved AI leader spawns to keeps
* Changed spawn of trolls that were spawning in walls
* Sanity-checked village ownership in cavern
From #3078:
* Changed spawn of Eastern Troll Flamecaster
* Fixed entry routes of Troll Flamecasters
From author notes:
* Made 'Wounded Dwarf' a wounded unit
=> UtBS 5: changes to scenario locations

data/campaigns/Dead_Water/scenarios/05_Tirigaz.cfg
Fixes #3092 - Now updates objectives if orc leader is killed first, and gives additional dialogue
Fixes #3093 - Gold event now won't fire if ghosts kill the orc leader
=> DW 5 Tirigaz - Changes to orc leader death event

data/campaigns/Dead_Water/scenarios/05_Tirigaz.cfg
The orc calls them fish-men several times, so changing it to "merfolk"
wouldn't fit.
Also a whitespace fix from wmlindent.
=> DW S05: Add a po hint about the orc saying "mermen" (part of #2940)

data/campaigns/Dead_Water/scenarios/07_Bilheld.cfg, data/campaigns/Dead_Water/scenarios/10_The_Flaming_Sword.cfg, data/campaigns/Dead_Water/scenarios/12_Revenge.cfg, data/campaigns/Dead_Water/scenarios/13_Epilogue.cfg, data/campaigns/Dead_Water/units/Citizen.cfg, data/campaigns/Dead_Water/utils/dw-utils.cfg, data/campaigns/Dead_Water/utils/items.cfg, data/core/macros/items.cfg
* Dead Water: Change "mermen" to "merfolk" (part of #2940)
This commit excludes changes to S05 Tirigaz, I think changing the dialogue
there is going to be more complicated, and it's better for that to have a
separate PR.
* Prose: the Storm Trident's description uses "merfolk" (issue #2936)
Also update Dead Water's copy of it to use race= instead of a
list of unit types (as done for the core object in 613dd431).
=> Dead Water and core's Storm Trident: Change "mermen" to "merfolk"

data/gui/window/mp_faction_select.cfg, src/gui/dialogs/multiplayer/faction_select.cpp, src/gui/dialogs/multiplayer/faction_select.hpp
If the leader hasn't been discovered, the "Unknown Unit" topic will be shown.
Fixes #1491.
This is for 1.14. I tried to rebase it to master but the help system in master doesn't work for me at all right now even without the patch.
=> MP Faction Select dialog: Show leader unit details.

src/playsingle_controller.cpp
Fixes #3107 
The PR is for 1.14 because I couldn't test it with master. It compiled after changing the new constructor overload but I couldn't even load the replay UI in master.
=> Replay: Don't disable the "Point of view" button after reset

src/reports.cpp, src/units/attack_type.cpp, src/units/attack_type.hpp
Related to #3178 
This should fix weapon specials with "active_on" and "[filter_self] formula=" marked as inactive in the tooltips. 
I couldn't fix backstab because i didn't know what to do :p let me explain why in this example:
The Thief will have backstab enabled vs the Sergeant, but not vs the Troll Whelp. So what should the tooltip say in this case? That backstab is active because there is _at least_ one enemy who satisfies the skill's requirements? Or should it say something else?
Afaik such issue may occur with any weapon special having "[filter_opponent]" or "[filter_defender]" as filters.
=> Partial fix of weapon special marked as inactive

data/lua/wml/message.lua
Fixes: https://forums.wesnoth.org/viewtopic.php?f=21&t=48370
In the tutorial when we occupy the first village the message tells us the
village count got incremented, but in the old version it was incremented
only afterwards. Non-narrator messages were updated properly. By adding the
redraw, narrator messages triggered by capture event produce the same
result as other speakers.
=> Fix: add redraw to narrator's message so village count is refreshed

data/gui/window/mp_join_game.cfg, src/game_initialization/flg_manager.cpp, src/game_initialization/flg_manager.hpp, src/gui/core/timer.cpp, src/gui/dialogs/multiplayer/faction_select.cpp, src/gui/dialogs/multiplayer/faction_select.hpp, src/gui/dialogs/multiplayer/mp_join_game.cpp, src/gui/dialogs/multiplayer/mp_join_game.hpp, src/utils/scope_exit.hpp
previously players had to leave an rejoin the game to change their faction.
this was most annoying in coop games where you want might want to choose
your faction in consultation with the other players. Also you previously could
not even checkout the different available factions again after you joined
the game.
=> allow non hosts to change factions later.

data/campaigns/The_South_Guard/scenarios/05_Choice_In_The_Fog.cfg
Fixes #3031.
The objectives look funny in linger mode after killing both Urza Afalas and the lich, there's no condition=win objective shown at all, I'm not sure what to do about that.
=> TSG win conditions

data/themes/default.cfg
https://github.com/wesnoth/wesnoth/issues/3306
Fixes this rectangle box breaking the tooltips for the unit_side flag and the unit name.
=> Fix the unit name and unit side flag tooltips (Thanks, Landiss!)

src/replay.cpp
https://github.com/wesnoth/wesnoth/issues/3119
Fixing the lack of stars on the remote client when sending a team/observer message.
This commit didn't modify the necessary lines in replay.cpp:
6aa3b3b
(of which the chat_msg::chat_msg one has already been fixed)
=> Fix team chat not being marked as such on remote clients

data/lua/wml/objectives.lua
Remove the blank line that shows above the "Defeat:" header when there are `condition=lose` objectives but no `condition=win` objectives.
=> WML: Don't add a \n before condition=lose objectives if there are no objectives listed before them.

src/help/help_topic_generators.cpp
This algorithm was lifted from help::generate_trait_topics().
Fixes #3284
=> Help: Use `female_name` and `name` as fallback when `male_name` is empty and don't list hidden traits.

src/units/unit.cpp
From https://github.com/wesnoth/wesnoth/pull/3327#issuecomment-403287078
When this is merged https://wiki.wesnoth.org/SingleUnitWML will need to be updated to document the `jamming` key. That key is also missing from https://wiki.wesnoth.org/UnitTypeWML.
=> WML: Support the the 'jamming' key in [unit].

data/campaigns/tutorial/scenarios/01_Tutorial_part_1.cfg
Fixes #1584 1c - Delfador summons the puppet, you have 0 MP left but the
puppet is not adjacent to you, and can't attack or undo
Changed Delfador's initial position to match the quintain's, and made him
step away to summon in the original place next to us, so we don't need to
move again to attack after we reach him.
The movement points of the mage are now updated and he gained quick trait
to fit for the more movements he does.
Final movement also touched, so he does not seem to sidestep the new
enemies when leaving the map.
=> Tutorial S1: prevent getting stuck next to Delfador, unable to end turn

src/server/simple_wml.cpp, src/server/simple_wml.hpp
This still has problmes especially related to chaching of simple_wml. But it fixes the most commen cases of "translatability lost in networked mp"
=>  preserve traslatable strings in simple_wml.

src/help/help_impl.cpp
Fixes empty name abilities in help in Liberty S1.
I thought of adding support for `hide_help` for custom abilities but that might be overkill.
=> Help: Hide abilities with empty names.

data/advanced_preferences.cfg, src/gui/widgets/unit_preview_pane.cpp, src/help/help_topic_generators.cpp, src/reports.cpp
Sort the movement costs in the tooltip in ascending order costs. First bases on movement costs, then alphabetically. Addresses https://github.com/wesnoth/wesnoth/issues/2673.
=> Sort the movement costs in the tooltip in ascending order

data/test/scenarios/swarm_disables_upgrades.cfg, wml_test_schedule
Current implementation of unupgradable relies on [swarm] overwriting all strike modifications. That is not documented behavior, so it makes sense to add a test for it.
=> Add WML unit test for unupgradable

src/gui/widgets/generator.cpp
Before 20180724 17:21:37 error gui/layout: Failed to fit vertical list to requested rect; expected bottom edge was 27720180724 17:21:37 error gui/layout: , actual bottom edge was 19520180724 17:21:37 error gui/layout:  (top edge is 113)
After 20180724 17:34:30 error gui/layout: Failed to fit vertical list to requested rect; expected bottom edge was 277, actual bottom edge was 195 (top edge is 113)
=> Show "failed to fit" message with single timestamp

src/server/server.cpp
With case insensitive status if same case insensitive name is connected from multiple IP, it only outputs results for first IP. I believe that is acceptable. That problem does not affect sl.
=> Make /q sl and status case insensitive

data/campaigns/The_Hammer_of_Thursagan/scenarios/06_High_Pass.cfg
From https://github.com/wesnoth/wesnoth/pull/3395#issuecomment-408688252
The radius values may need balancing.
=> THoT S6: Now that the player is told which hut to look at, don't trigger Ratheln if the player ignores the hint.

data/campaigns/Sceptre_of_Fire/scenarios/9_Caverns_of_Flame.cfg
The original text that referred to Knalga was confusing if the
player thought of Knalga as "dwarvish territory", and most of
the campaign's scenarios have been somewhere in Knalga.
=> SoF S9: Rephrase the intro text (fixes #3405)

projectfiles/Xcode/Wesnoth.xcodeproj/project.pbxproj, src/CMakeLists.txt, src/SConscript, src/desktop/apple_version.hpp, src/desktop/apple_version.mm, src/desktop/version.cpp
Old os version detection was in case of macOS buggy so I reworked it. It is faster now and native.
I used `desktop::apple::os_version()` namespace. It may be nice to rework rest of platform specific code to use this namespace style (not only os_version, but also notifications, ...)
=> Better os version handling

src/scripting/lua_audio.cpp, src/sound_music_track.hpp
The current implementation of the [music] tag [sets the title](https://github.com/wesnoth/wesnoth/blob/master/data/lua/wml-tags.lua#L297) after adding the track, however the title field was read only.  This makes the field writeable.
---
Fixes #3461 
I can merge and cherry-pick this if there are no concerns.
=> Fixes track titles not being set from WML.

data/core/units.cfg
Fixes #3372  (fix for #3392 to be later for master only)
Gives the Saurians a race description (taken from the wiki, with the minor change of comparing height against humans instead of drakes) The wiki description has been around for several years.
Has the Saurian warrior line be female, in accordance with the new race description, some lore in SotA and some UMC campaigns, which have likely gotten this from the wiki.
=> Saurian Race Description

src/menu_events.cpp
=> Fix crash after hitting enter when no units match the recall list filter

src/gui/core/event/handler.cpp, src/wesnoth.cpp
Compatible with MacOS 10.14.
Rollback of previous one.
Subtask of #3455
=> A cleaner fix for "iOS interfering with Mac: Mac touchpad generates touch events"

utils/pywmlx/state/lua_states.py
wmlxgettext couldn't recognize lua plural strings in some context. More in details the underscore marker ( _ ) originally required to be located at the beginning of the line or preceded by a space.
Now string maker is recognized without the requirement of an extra space, so syntax like: 
`local var = wesnoth.format(_("one thing","$count things",count), {count = count})`
now can be recognized as plural string, even if the underscore marker is not preceded by a space, but is preceded, for example, by a parenthesis
=> wmlxgettext: fix #3469: lua plural strings not recognized in some context

data/campaigns/Northern_Rebirth/scenarios/14a_Epilogue.cfg
Some non-native English readers may find use of the word 'disposed' confusing.
(Using PR because I'm not sure of the process surrounding string freezes.)
=> Slightly rewrite dialogue (fixes #3386)

src/gui/dialogs/game_load.cpp
This PR changes "Difficulty: Medium" to "Difficulty: Hero (Normal)" in the game load screen.
=> Game Load: Show the user-name difficulty name instead of the internal name

src/game_display.cpp, src/menu_events.cpp, src/units/unit.hpp
Two cases are handled:
1. At start of side turn of the enemy
2. When the player presses 'l' during the enemy's turn
One case is not handled:
3. When loading a save that starts at a side turn of the enemy
=> Don't scroll to an enemy leader that has an effective [hides] ability.

data/gui/window/game_load.cfg, src/gui/dialogs/game_load.cpp, src/save_index.cpp
This PR adds the "Modifications:" header and bulleted list. It shows the mod name if the mod is installed, else mod id, as done for campaigns.
Similar to #3478.
=> Game Load: Show list of enabled modification.

src/color.hpp, src/map/location.hpp, src/server/server.cpp
I decided 1000 commits was enough lag and brought my repo up-to-date. CMake, using GCC 8.2.0, with strict and pedantic options, flagged a few warnings. I'm not looking at Master until someone claims it's working and playable. If these need to be there, too, someone else will have to do it.
=> Minor pedantic fixes for 1.14

data/multiplayer/eras.lua
Fixes #1341.
Worth noting is that this only affects the message displayed about which side held the advantage when the turn limit was hit; it doesn't address the related issue of showing the victory/defeat alert to the tied players when they then enter linger mode, since draws currently don't really exist in the game.
=> Allow ties when the turn limit is hit (fixes #1341)

data/lua/wml/heal_unit.lua
@jyrkive same problem og halo. This time if i modify an unit afyer heal_unit animated, the halo remain.
=> Clear animation in heal_unit for fix halo remain

data/campaigns/Heir_To_The_Throne/scenarios/06_The_Siege_of_Elensefar.cfg
If the player ordered a unit to move and attack, allow the attack to be canceled, as done in #3227 for DiD. And change the undead reinforcements triggering.
=> HttT S6: Cancel attacks, support alt cave entrance

data/campaigns/An_Orcish_Incursion/_main.cfg, data/campaigns/Dead_Water/_main.cfg, data/campaigns/Delfadors_Memoirs/_main.cfg, data/campaigns/Descent_Into_Darkness/_main.cfg, data/campaigns/Eastern_Invasion/_main.cfg, data/campaigns/Heir_To_The_Throne/_main.cfg, data/campaigns/Legend_of_Wesmere/_main.cfg, data/campaigns/Liberty/_main.cfg, data/campaigns/Northern_Rebirth/_main.cfg, data/campaigns/Sceptre_of_Fire/_main.cfg, data/campaigns/Secrets_of_the_Ancients/_main.cfg, data/campaigns/Son_Of_The_Black_Eye/_main.cfg, data/campaigns/The_Hammer_of_Thursagan/_main.cfg, data/campaigns/The_Rise_Of_Wesnoth/_main.cfg, data/campaigns/The_South_Guard/_main.cfg, data/campaigns/Two_Brothers/_main.cfg, data/campaigns/Under_the_Burning_Suns/_main.cfg
Fixes #1222.
Note that the wiki's description of "rank" on the CampaignWML page will need to be updated, though I don't have a wiki account or the knowledge of how that's supposed to go (I suppose it'd be the addition of one of those "if version XYZ or later:" blocks?).
For ease of comparison, here's a before and after summary of each campaign's rank and category, along with the wiki text:
BEFORE
```
Novice:
5 A Tale of Two Brothers
10 An Orcish Incursion
15 The South Guard
20 Heir to the Throne
Intermediate:
110 Liberty
125 Legend of Wesmere
130 Eastern Invasion
140 The Hammer of Thursagan
150 Descent into Darkness
160 Delfador's Memoirs
170 Dead Water
180 Secrets of the Ancients
Expert:
215 The Sceptre of Fire
220 Son of the Black-Eye
230 The Rise of Wesnoth
240 Northern Rebirth
250 …
```
=> Menu: re-order and re-rank campaigns (including new ranks) (fixes #1222)

data/gui/window/wml_message.cfg
Fixes #1938. Tested on 800x600 and 1920x1080. This brings the left edge of the message (title and text) away from the left edge of the map. When the screen is wide enough, the text is placed at the same position regardless of whether the portrait is on the left, on the right, or on both sides. To test this start AToTB and read the dialog.
=> Add left padding to messages with right portrait

data/campaigns/tutorial/scenarios/01_Tutorial_part_1.cfg
Fixes #3039
Until the elves attack the quintain it is not allowed to end turns before
completing the given tasks. Display a message how to undo if there is
not enough MP remaining to reach the current destination by either unit.
=> Tutorial S1: display an undo message if impossible to reach next target

doc/man/wesnoth.6, src/commandline_options.cpp, src/commandline_options.hpp, src/game_launcher.cpp, src/game_launcher.hpp, src/play_controller.cpp, src/play_controller.hpp, src/playsingle_controller.cpp, src/saved_game.cpp, src/saved_game.hpp, src/scripting/game_lua_kernel.cpp, src/tests/test_commandline_options.cpp
Fixes #3472. [story] and [message] through the end of the `start` event will be skipped.
Try it: `./wesnoth -cThe_South_Guard --campaign-difficulty=1 --campaign-scenario=01_Born_to_the_Banner --campaign-skip-story`
=> Add --skip-story option

changelog.md, data/lua/wml/items.lua, src/display.cpp, src/scripting/game_lua_kernel.cpp
If [filter_side] is present then "team_name" is ignored.
Fixes #1477.
Constructing a comma-separated set of team names is ugly but I didn't want to change `add_overlay` and the `overlay` struct. https://github.com/wesnoth/wesnoth/blob/cc98bcd9d015a852dbec2053f300ce4682c4765d/src/overlay.hpp#L23-L26
=> WML: Support [filter_side] in [item].

doc/man/wesnoth.6, src/commandline_options.cpp
`wesnoth --render-image $foo $bar` writes a png image to $bar, if $bar has a png extension, otherwise it dies with no error message.
=> Commandline: Fix documentation of --render-image

src/units/udisplay.cpp
Scrolling to them would leak their location to the player.
edit: To test this:
```
diff --git a/data/campaigns/Heir_To_The_Throne/scenarios/01_The_Elves_Besieged.cfg b/data/campaigns/Heir_To_The_Throne/scenarios/01_The_Elves_Besieged.cfg
index 805f25cc67..4c9fb338bc 100644
--- a/data/campaigns/Heir_To_The_Throne/scenarios/01_The_Elves_Besieged.cfg
+++ b/data/campaigns/Heir_To_The_Throne/scenarios/01_The_Elves_Besieged.cfg
@@ -6,7 +6,8 @@
victory_when_enemies_defeated=no
map_data="{campaigns/Heir_To_The_Throne/maps/01_The_Elves_Besieged.map}"
{TURNS 16 14 12}
-    {DEFAULT_SCHEDULE}
+    {SECOND_WATCH}
+    {DAWN}
{SCENARIO_MUSIC "battle.ogg"}
{EXTRA_SCENARIO_MUSIC "casualties_of_war.ogg"}
@@ -160,13 +161,14 @@
#enddef
[side]
-        type=Orcish Warlord
+        {QUANTITY type Nightgaunt …
```
=> Unit Display: When an invisible enemy unit recruits another invisible unit, don't scroll to their location

src/save_index.cpp
In 1.14 since 14abecb2df9f94b4a4438156f9808596d223864b (#3495), selecting a 1.12.6 savegame in Game Load results in
> The file you have tried to load is corrupt: 'Mandatory WML child missing yet untested for. Please report.'
This PR fixes that.
=> Game Load: Restore the ability to select 1.12.6 savegames in the list

src/image_modifications.cpp, src/tests/test_image_modifications.cpp
SDL_BlitSurface's documentation (https://wiki.libsdl.org/SDL_BlitSurface) notes that "Blits with negative dstrect coordinates will be clipped properly".
Looking at the source code for SDL_UpperBlit() made me think that dstrect coordinates that were too big would also be handled appropriately.
I also managed to build wesnoth and run it. 
```units/goblins/rouser-lead-2.png~TC(1,magenta)~BLIT(data/core/images/halo/misc/leadership-flare-5.png, 15, -20)```
worked, and had no errors. This path tests both the negative handling and the overflow handling, so I thought it was probably good enough.
My second attempt at fixing #2225. Hopefully this goes better than the first one.
=> Made Blitting more permissive

src/font/constants.cpp, src/font/constants.hpp, src/help/help_topic_generators.cpp
On 1.14, the help page for Shadow has a a line break between "Required XP" and the value:
This patch makes sure the "Required XP: 100" block is never split across a linebreak.
=> help: Prevent line breaks within the "Required XP: 80" block by using non-breaking spaces

src/units/udisplay.cpp, src/units/unit.cpp, src/units/unit.hpp
Like #3559, but for teleporting.
<details><summary>Diff for testing</summary>
```
diff --git a/data/campaigns/An_Orcish_Incursion/scenarios/01_Defend_the_Forest.cfg b/data/campaigns/An_Orcish_Incursion/scenarios/01_Defend_the_Forest.cfg
index f4d83db542..93a4dc3426 100644
--- a/data/campaigns/An_Orcish_Incursion/scenarios/01_Defend_the_Forest.cfg
+++ b/data/campaigns/An_Orcish_Incursion/scenarios/01_Defend_the_Forest.cfg
@@ -12,6 +12,7 @@
turns=24
next_scenario=02_Assassins
+    {SECOND_WATCH}
{DEFAULT_SCHEDULE}
{SCENARIO_MUSIC       knolls.ogg}
@@ -82,13 +83,13 @@
side=2
controller=ai
recruit="Orcish Archer,Orcish Grunt,Wolf Rider"
-        {GOLD 100 125 150}
+        {GOLD 0 0 0}
income=0
team_name=Orcs
user_team_name= _ "Orcs"
{FLAG_VARIANT6 ragged}
-        type=Orcish Warrior
+ …
```
=> Don't scroll to a teleporting unit that's invisible at the source or destination

changelog.md, src/reports.cpp
In the test scenario mouseover (4,19) to see the difference.
In master, the tod image and tod schedule indication in the sidebar show:
- "dusk 4/6" outside the cave
- "dusk 1/1" on (4,19) in master - leaking the fact that the tod schedule under the shroud consists of one timezone
- "dusk 4/6" on (4,19) with this patch - on a shrouded hex it shows what it shows on a non-shrouded hex, regardless of the time area of the shrouded hex. Is that good or would it be better to show, say, a black image and "?/?" instead, when mouseover'ing a shrouded hex?
(tagging "bug" because showing dusk and 1/1 is _definitely_ incorrect)
=> Don't show time of day under shroud

changelog.md, data/test/scenarios/heal.cfg, src/actions/heal.cpp, src/game_state.cpp, src/game_state.hpp, src/play_controller.cpp, src/play_controller.hpp, wml_test_schedule
Discussed on the forums: https://r.wesnoth.org/t48817
=> Healing: Do heal on turn 1.

src/actions/attack.cpp
If i use active_on=defense in poison ability, and i  attack with poisoned attack of an Assasin, the enemy was not poisoned.
=> Fix bug in bool implemened weapon when active_on used.

CMakeLists.txt, SConstruct, projectfiles/Xcode/Wesnoth.xcodeproj/project.pbxproj, src/build_info.cpp, src/hash.cpp, src/preferences/credentials.cpp, src/server/user_handler.cpp, utils/travis/install_deps.sh, utils/travis/steps/install.sh
Didn't test scons, so let's wait for Travis. The changes are pretty straightforward though.
I don't use MacCompileStuff project, but use MacPorts, so my environment is quite different.
Should fix both #3634 and #3557.
=> #3634, #3557: Port from iOS: Compile with Apple crypto framework instead of OpenSSL

SConstruct
Another libcrypto reference can be skipped on Mac.
=> After and #3634, #3557, this switch is excess.

src/actions/attack.cpp, src/actions/attack.hpp, src/game_display.hpp, src/gui/dialogs/attack_predictions.cpp, src/reports.cpp
This PR makes the alignment and weapon info in the sidebar show information for the mouseover hex, not for the unit's present position. For example, in the test scenario click the Footpad (14,6) and mouseover one of the empty hexes adjacent to the Dark Adept that has darkens; with the PR you'll see the sidebar show "chaotic (+25%)", compared to "chaotic (+0)%)" currently. Fog and shroud are honored.
=> Sidebar alignment follows mouseover

data/campaigns/Heir_To_The_Throne/scenarios/06_The_Siege_of_Elensefar.cfg
Also scroll to it, in case the viewport is elsewhere.
Suggested on the forums https://forums.wesnoth.org/viewtopic.php?p=634718#p634718
{REMOVE_LABEL} doesn't remove the label, from a brief look that seems to be a bug in that macro?
=> HttT S6: Point out exactly where the ford is.

data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg
If the wolves are recruited on the first turn then Galdrad's turn 3 hint about
getting to the island before them is too difficult for a tutorial, and his hint
about holding the village on turn 4 hint may be a turn too late.
Some have to be recruited on turn 2 to fit the turn 3 hint about them, so rig
the AI's recruitment to do that.
=> Tutorial S2: Don't allow the orc to recruit wolves on turn 1

data/lua/wml/modify_unit.lua, src/game_board.cpp, src/units/attack_type.cpp, src/units/attack_type.hpp, src/units/unit.cpp, src/units/unit.hpp
Unit attribues that unchanged
(except with object/advancement/trait) are no longer written
to savefiles, this not only greatly reduce savefile size on
some cases it also makes savefiles more comptible with newer
versions because it reduced the chance that old/incompatible
code is stored in savefiles.
Note that changes via [object] (`wesnoth.add_modification()`) also
count as changes but changes done via object in advance_to does not.
This is intentional as at add_modification an objects might have
an effect dependent on a filter that depends on directly changed
arrtibutes which would then be lost on rebuild if we wouldn't mark
them as 'changed'.
=> don't write unchanged unit attributes to savefiles

data/core/help.cfg, data/core/units/dunefolk/Apothecary.cfg, data/core/units/dunefolk/Explorer.cfg, data/core/units/dunefolk/Harrier.cfg, data/core/units/dunefolk/Herbalist.cfg, data/core/units/dunefolk/Ranger.cfg, data/core/units/dunefolk/Rider.cfg, data/core/units/dunefolk/Rover.cfg, data/core/units/dunefolk/Skirmisher.cfg, data/core/units/dunefolk/Swiftrider.cfg, data/core/units/dunefolk/Windrider.cfg, data/english.cfg, src/actions/attack.cpp, src/actions/attack.hpp, src/reports.cpp, src/tod_manager.cpp, src/tod_manager.hpp
The first introduction of liminal was a twilight bonus. It didn't work, and was reintroduced as a malus, which works but seems to be considered bad (see [Dunefolk balance discussions](https://forums.wesnoth.org/viewtopic.php?f=15&t=47831&start=15) on the forum). 
This change takes custom schedules into account, liminal bonus is computed as a bonus that is as close as possible to the best of fearless chaotic and fearless lawful averages.
=> Implement Liminal as a twilight bonus instead of night and day malus

.travis.yml, data/campaigns/Legend_of_Wesmere/lua/wml_tags.lua, data/campaigns/Legend_of_Wesmere/scenarios/chapter1/03_Kalian_under_Attack.cfg, data/campaigns/Legend_of_Wesmere/utils/map-utils.cfg, data/campaigns/Liberty/scenarios/01_The_Raid.cfg, data/campaigns/Northern_Rebirth/scenarios/02_01_Infested_Caves.cfg, data/campaigns/Northern_Rebirth/scenarios/05a_01_The_Pursuit.cfg, data/campaigns/Northern_Rebirth/scenarios/12a_Get_the_Gold.cfg, data/campaigns/Sceptre_of_Fire/scenarios/Epilogue.cfg, data/schema/core/actionwml.cfg, data/schema/core/addons.cfg, data/schema/filters/weapon.cfg, data/schema/units/abilities.cfg, data/schema/units/modifications.cfg, data/schema/units/specials.cfg, data/schema/units/types.cfg, data/test/scenarios/test_move.cfg, utils/travis/docker_run.sh, utils/travis/schema_validation.sh, utils/travis/steps/script.sh
This adds running the WML schema validation in travis.  It also updates the schema itself and fixes a few WML errors so that core and all campaigns under all difficulties pass the schema validation.
=> Run WML schema validation in travis. Fixes #3709

src/units/abilities.cpp
This PR removes the ellipsed word.
Is this right? It tested okay but I am not completely sure.
=> Attack Enemy: Don't show "poison" in the attacks list if the enemy is unpoisonable

src/actions/heal.cpp, src/units/udisplay.cpp
<details><summary>Diff for testing</summary>
```
diff --git a/data/campaigns/Heir_To_The_Throne/scenarios/01_The_Elves_Besieged.cfg b/data/campaigns/Heir_To_The_Throne/scenarios/01_The_Elves_Besieged.cfg
index a2b5cfc3093..1c4587f63fa 100644
--- a/data/campaigns/Heir_To_The_Throne/scenarios/01_The_Elves_Besieged.cfg
+++ b/data/campaigns/Heir_To_The_Throne/scenarios/01_The_Elves_Besieged.cfg
@@ -6,7 +6,7 @@
victory_when_enemies_defeated=no
map_data="{campaigns/Heir_To_The_Throne/maps/01_The_Elves_Besieged.map}"
{TURNS 16 14 12}
-    {DEFAULT_SCHEDULE}
+    {SECOND_WATCH_HOUR1}
{SCENARIO_MUSIC "battle.ogg"}
{EXTRA_SCENARIO_MUSIC "casualties_of_war.ogg"}
@@ -23,8 +23,14 @@
[/avoid]
#enddef
+    turn_at=2
[event]
name=prestart
+        {UNIT 2 (White Mage) 18 19 (max_moves=0)}
+        {UNIT …
```
=> Healing: Display healing animation if the healer is visible but the patient is not (due to fog, shroud, nightstalk...)

data/campaigns/Descent_Into_Darkness/scenarios/01_Saving_Parthyn.cfg
Fixup the dialog added in 39f26950c3a30f449e7c378dc94ebb26cc992cfb which is part of #3711. (#3711 has been merged to master but it's open because its target is 1.14.)
=> fixup! DiD S1: Add a dialog hint about the loyals staying behind.

src/reports.cpp
For example, for a Quenoth Youth, show this:
instead of "No advancement".
=> Sidebar: In the tooltip of 'lvl 1' show modifications advancements as well as type advancements

data/gui/window/unit_recruit.cfg, src/gui/dialogs/unit_recruit.cpp, src/gui/dialogs/unit_recruit.hpp
Will be useful, particularly for [certain](https://github.com/ProditorMagnus/Ageless-for-1-14/commit/a016fc9058afeeba05e148a7116a6c4116d4875b) large factions, but also for quickly searching the recruit list for a particular unit type.
In the test scenario (which allows you to recruit several dozen unit types) it looks like this:
The search uses the localized name.
=> Recruit Unit: Add search functionality

utils/pofix.py
Fixes some false positive warnings such as
```
pofix: po/wesnoth-aoi/en_GB.po already includes the new string
"the bodies of both sides. "
but also the old
"the bodies of both sides, "
this needs handfixing for now since it likely creates duplicate msgids.
pofix: po/wesnoth-aoi/en_GB.po already includes the new string
"There was no hale orc in sight,"
but also the old
"there was no hale orc in sight,"
this needs handfixing for now since it likely creates duplicate msgids.
```
in current master. This occurs when one of the duplicates is in the msgid and one in the msgstr. This example is en_GB but it also affects the drake race description in pl.po in 1.14, where some of the paragraphs in the msgstr are in English.
Okay to merge?
=> pofix: Strip msgstr's when checking for duplicate msgid's

INSTALL.md, data/core/about.cfg
They are required to build wesnoth client but not noted.
=> Note dependencies on OpenGL and GLEW in INSTALL.md

data/core/about.cfg, data/gui/widget/menu_button_default.cfg, data/gui/widget/multimenu_button_default.cfg
Icon `short_arrow_left_25-pressed.png` exists, but is not used anywhere.
Widgets in `menu_button_default.cfg` and `multimenu_button_default.cfg` were using active icon (`short_arrow_left_25-active.png`) for the "pressed" state.
=> Fix typo in menu_button: active icon was used instead of pressed icon

data/campaigns/Eastern_Invasion/scenarios/02_The_Escape_Tunnel.cfg
This PR addresses #3782; I've changed the player side to have fog at all times now. On the first turn, the player can see the path where the trolls are (parts of the path are unshrouded, but fogged). Upon seeing the dwarves (turn 2 or 3 ish, typically), the map becomes unshrouded including the amulet and treasure rooms. This should keep the player from going the wrong way due to lack of information.
=> [EI] Modified some player shroud and fog settings for #3782

data/campaigns/An_Orcish_Incursion/scenarios/01_Defend_the_Forest.cfg
This is just a hint on the general principle that it's good to have a healer,
based on the review comments of #3683.
When playing on easy, there's not much experience available in this first
scenario. Any hints about leveling units probably belong in S2 or later,
which also has the advantage of being able to talk about the enemies in S2.
=> AoI S1: Hint about recruiting a healer, if the player doesn't have any

data/campaigns/Liberty/scenarios/06_The_Grey_Woods.cfg
Added underground time_area because the terrain suggests it's a cave. Needs playtesting.
=> Liberty S6: Give the cave underground time of day.

data/themes/default.cfg, src/reports.cpp, src/units/unit.cpp
A bunch of small changes. The ones that affect the default theme are:
1. Don't truncate the abilities and traits lines before the "lvl" label
2. Make terrain defense follow mouseover, like the rest of the sidebar does.
3. Change the trait tooltip format
=> Several sidebar changes

data/tools/wmllint
In global_sanity_check(), variables "unit_id" and "base_unit" can be
used before assignment. This happens, for example, in this WML file:
https://github.com/Dugy/Legend_of_the_Invincibles/blob/master/utils/amla.cfg#L65
... where there is a [/unit_type] tag without the matching [unit_type].
(these variables are normally initialized when [unit_type] is found)
=> wmllint: fix "local variable 'unit_id' referenced before assignment"

projectfiles/CodeBlocks/wesnoth.cbp
Required for pull request #3851 that was recently merged.
=> codeblock: link to libogg, libvorbis and libvorbisfile for stable branch

data/campaigns/Descent_Into_Darkness/scenarios/02_Peaceful_Valley.cfg, data/campaigns/Northern_Rebirth/scenarios/01_Breaking_the_Chains.cfg, data/campaigns/Northern_Rebirth/scenarios/05a_01_The_Pursuit.cfg, data/campaigns/Northern_Rebirth/scenarios/09a_Introductions.cfg, data/campaigns/Sceptre_of_Fire/scenarios/3_Searching_for_the_Runecrafter.cfg, data/campaigns/Sceptre_of_Fire/scenarios/3t_The_Council_Regathers.cfg, data/campaigns/Sceptre_of_Fire/scenarios/7_Outriding_the_Outriders.cfg, data/campaigns/Sceptre_of_Fire/scenarios/Epilogue.cfg, data/campaigns/Secrets_of_the_Ancients/scenarios/02_Dark_Business.cfg, data/campaigns/Son_Of_The_Black_Eye/scenarios/16_The_Coward.cfg, data/campaigns/The_South_Guard/units/Junior_Commander.cfg, data/campaigns/The_South_Guard/utils/sg_help.cfg, data/core/units/elves/Archer.cfg
I realise we're in a string freeze for 1.14.6 at the moment - this can wait till it's released. In fact, I only found these _because_ I was reviewing the string changes for the 1.14.6 release.
Sending as a PR because I always seem to get things wrong with relation to string updates, especially if pofix is involved. Aside from maybe 'right click', I think these warrant an actual po update because translators may not necessarily know the intended word from the mis-spelled word.
=> Spelling corrections for 1.14.6

data/campaigns/The_Rise_Of_Wesnoth/scenarios/22_The_Rise_of_Wesnoth.cfg
=> [TRoW] S22: cuttlefish animations use different facing filters

src/units/abilities.cpp, src/units/attack_type.hpp
Here is a commit to address issue #3784 . This will make a defender's "first strike" inactive if the attacker also has "first strike".
=> Make defender's "first strike" inactive if the attacker also has "first strike", fixes #3784

src/units/unit.cpp
This fixes Issue #3831. The problem was that the appearance_changed attribute was set in set_facing() even if the direction the unit faces did not change.
The flag is passed to the unit_mover: https://github.com/wesnoth/wesnoth/blob/095edb36a1b4d06d8ab904e3d622e94ac9d65308/src/actions/move.cpp#L544-L545
Which causes the fake unit to be replaced: https://github.com/wesnoth/wesnoth/blob/095edb36a1b4d06d8ab904e3d622e94ac9d65308/src/units/udisplay.cpp#L328-L330
=> Fix issue #3831: Broken unit movement animations

data/tools/wesnoth/wmlparser3.py
The problem was that in the WML parser, when parsing the outside of a string that is translatable, the code only assumed “spaces” characters could precede it. If there are “tabs” characters the code parses the “_” character as an attribute value.
The solution is to add a stripping code for “tabs” characters.
=> Bug #3903 Fix.

data/tools/wesnoth/wmlparser3.py
The problem was that in the wml parser, when a node creation spans multiple lines, the code doesn’t take in account that one of those line can contain a #textdomain directive.
In the method “parse_outside_strings” (line 501), the code that processes the #textdomain directive is inside an if block that is true only if the node creation doesn’t span across multiple lines (self.temp_key_nodes is null).
The solution implemented is that in the method “parse_outside_strings” (line 501), the code that check if a line starts with #textdomain is moved from inside the block that is true only if the node creation doesn’t spans across multiple lines and put in the method scope after the first if block that checks if the line is empty.
=> Bug #3862 Fix.

data/campaigns/Two_Brothers/maps/03_Guarded_Castle.map, data/campaigns/Two_Brothers/scenarios/03_Guarded_Castle.cfg
Implemented @stevecotton's fix to #3389 with some slight modifications for gameplay rebalancing (I've playtested, don't know if anyone else wants to?). I didn't modify the lit stone walls to sconces, since scones don't seem to work right now. For 1.15/1.16, once those terrains work, we can fix them then. 
This has some string changes, so probably needs to go in 1.14.7.
=> [AToTB] Added castle ToD to S3

data/campaigns/Dead_Water/scenarios/03_Wolf_Coast.cfg
As the title says, implemented @CelticMinstrel's suggestion for #3400 (subtracted 30g from the enemy side to compensate for the extra wild wolf).
(Has string changes in it, don't merge for 1.14.6).
=> DW S3: added event for storm trident

data/tools/wesnoth/wmlparser3.py
The problem is that when parsing #textdomain directives, the parser
expects the directive to be at the start of the line. So if the directive
is preceded by spaces or tabs then it is treated as an attribute.
The solution is to strip all spaces and tabs on the left side of the
parsed line string when checking for #textdomain directive.
Closes #3951
=> Fix parser handles textdomain directives incorrectly

data/tools/wesnoth/wmlparser3.py
The problem is that if we have a "#define" directive followed with an
empty line ending with a newline character then the parser presumes the
value is the newline character instead of the actual value (which is
located on a subsequent line).
The solution is that when parsing an empty line, if "self.in_string" is
False and "self.temp_key_nodes" is not None then we ignore the line
instead of parsing it with the "parse_outside_strings" function.
Closes #3947
=> Fix parser crash in defined multi line str test

changelog.md, data/campaigns/tutorial/maps/02_Tutorial_part_2.map, data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg, data/campaigns/tutorial/units/Quintain.cfg, data/campaigns/tutorial/units/Warrior.cfg, data/campaigns/tutorial/units/Warrioress.cfg
For #3390, see my comment there (https://github.com/wesnoth/wesnoth/issues/3390#issuecomment-468960279).
=> [Tutorial] Small fixes

src/menu_events.cpp
This is essentially the same as https://github.com/wesnoth/wesnoth/pull/3476, except that it is applied to the recruit dialog rather than the recall dialog.
=> Fix crash after hitting enter when no units match the recruit list filter

src/display.hpp, src/game_display.cpp, src/game_display.hpp, src/menu_events.cpp, src/units/drawer.cpp, src/units/drawer.hpp
Fixes #1989 
Screenshot:
Does the implementation look right? I put the new member function in `game_display` next to the other reach functions, but then I had to use a `dynamic_cast` in unit_drawer because it can be constructed from a plain `display`: https://github.com/wesnoth/wesnoth/blob/53baf3514a8db2a96c6c5fae4d40af76b7e164f4/src/display.cpp#L2536
=> UI: Highlight enemy units in "Show Enemy Moves" mode

data/gui/widget/unit_preview_pane.cfg, src/gui/widgets/unit_preview_pane.cpp
This adds range and damage type icons to the unit preview pane, like #3732 did to the sidebar.
Depends on #3732 for finding the the `blade` icon (#3732 renamed blades.png to blade.png).
Currently this is a work in progress, not ready to be merged yet. This is how far I got, does anyone know how to stop that line from stretching to fill the width of the pane?
cc @CelticMinstrel
=> Add attack icons to unit_preview_pane

po/wesnoth-tutorial/de.po
Feel free to ask me about the changes I made.
Some other small issues (not fixed with this PR):
- Space before ’%’: https://de.wikipedia.org/wiki/Prozent#Schreibweise
- Spelling of numbers is inconsistent and doesn’t seem to follow any logic
=> Spelling fixes in German translation of the tutorial

src/help/help_impl.cpp, src/help/help_impl.hpp, src/help/help_topic_generators.cpp, src/help/help_topic_generators.hpp
Following up on #3732, also use the icons in the unit help pages:
=> Help: Show damage type and range icons in unit help pages

src/units/udisplay.cpp
The `return;` prevents the `set_hidden(false);` later in the function from being reached. This looks wrong, as though it would be a regression introduced by #3559, but I found no difference in my testing.
I found this while auditing code in search of a bug reported by @Konrad22 on discord. (In a nutshell, he played EI S17a and at the start of turn 6 an enemy Shadow was adjacent to Konrad's units but had `hidden=yes`.)
=> Unhide recruited unit when both the recruiter and recruitee are invisible to the viewing team

src/quit_confirmation.hpp, src/synced_commands.hpp
I'm not sure if this is the best way to resolve the compilation errors (how was std::string defined previously?) but maybe it's a case of MSVC compiler being more strict somewhere.
=> Visual Studio 2019 Compilation - master

src/quit_confirmation.hpp, src/synced_commands.hpp
I'm not sure if this is the best way to resolve the compilation errors (how was std::string defined previously?) but maybe it's a case of MSVC compiler being more strict somewhere.
=> Visual Studio 2019 Compilation - 1.14

src/addon/manager.hpp, src/game_config_manager.cpp
#3971 
Fail gracefully when an addon has an invalid pbl file, and make sure to push errors to the log and addon errors.
Should I include the pbl path somewhere in the logging?
=> Do a better job of catching pbl parse errors for addons

data/multiplayer/scenarios/2p_Dark_Forecast.cfg
1.14 OOS save backport of 05cd152
Don't merge yet, as it's not tested. Closes #3890.
@Vultraz might rename 1.14.8 milestone to 1.14.9
=> Dark forecast backport [WIP]

data/campaigns/Descent_Into_Darkness/maps/09_A_Small_Favor3.map, data/campaigns/Descent_Into_Darkness/scenarios/09_A_Small_Favor3.cfg
Refactor to using location_id for the location of the book, because it appears
multiple times in the .cfg file.
An edge case to this edge case: if DV's turn starts with DV next to the book
and one of DV's units on the book, DV doesn't move until the next turn.  This
was also true if the unit moved to attack something, and works in the player's
favor, as it gives Malin an extra turn to grab the book, so I'm treating it as
a feature.
If DV does grab the book, explicitly say in the objectives that it's now a race
to the escape tunnel. This means that the objectives dialog is shown twice:
* DV takes the book (no messages at all)
* start of player's turn: objectives shown (escape to win, deaths to lose)
* player ends turn
* DV moves, Malin asks if he's going to be left behind
* start of …
=> DiD S09: Unblock the book if one of DV's units is standing on it, clarify objectives

data/tools/unit_tree/helpers.py, data/tools/unit_tree/html_output.py
This should be a resolution  for #3949 
The unit database list should include range and type icons
and the details summary page should include the type and range icons inline in the attack line item
=> unit-database: issues/3949

data/campaigns/Heir_To_The_Throne/scenarios/11_The_Ford_of_Abez.cfg, data/campaigns/Heir_To_The_Throne/scenarios/16_Hasty_Alliance.cfg, data/campaigns/Heir_To_The_Throne/utils/httt_utils.cfg
In S11, if the player tries to attack Li'sar then there are supposed to be four
events adding extra guards. Two of them didn't trigger, because the [have_unit]
calls were trying to match her id with a typographic quotation mark.
One change in the opposite direction, where the displayed name could have a
non-typographic quotation mark; this might only happen when using choose_level
to reach a scenario with NEED_LISAR before her unit is on Konrad's recall list.
Remove a CLEAR_VARIABLE that was obsolete since 7778e6f4.
=> HttT S11: Correct two places where a typographic quote was used in Li'sar's id

data/campaigns/The_Hammer_of_Thursagan/scenarios/12_The_Underlevels.cfg
Otherwise the shroud doesn't update until the unit moves again.  When
teleporting that could lead to the unit being stuck in a shrouded location,
although that's unlike to happen except when running around the map using debug
commands.
The two teleports from the center to the north and south don't need this,
because they're only enabled after a unit has stood on the destination rune.
=> THoT S12: After breaking down a door or teleporting, clear the shroud

data/campaigns/Secrets_of_the_Ancients/scenarios/21_Against_the_World.cfg
Side 3 is the Saurians, the effect of this is just to have the very first
enemy that appears have blue reins instead of green reins during the
move_unit_fake. Only noticed it because I was adding wmllint:recognize
lines for each side's leader.
=> SotA S21: Fix the side= in the paladin's move_unit_fake

changelog.md, data/core/units/merfolk/Diviner.cfg, data/core/units/merfolk/Enchantress.cfg, data/core/units/merfolk/Priestess.cfg, data/core/units/merfolk/Siren.cfg
Like the title says, the HP of initiate advancements is extremely low compared to other mages (see elves and humans), so this aims to correct that. Since these units are very hard to get in MP, I don't think we need to worry about MP balance. For SP, this won't throw off campaign balance very much; if anything, it makes merfolk a bit more viable (since they are weak right now).
=> Merfolk: increase HP of initiate advancements

data/tools/wesnoth/wmliterator3.py, data/tools/wmllint
The main reason for moving this to a separate function was to make the
per-event variables local to that function.
=> wmllint: Handle nested events and other filters in the death check (closes #4085)

data/core/about.cfg, projectfiles/VC14/wesnoth.vcxproj
Fixed bug where Visual Studio would incorrectly interpret non-breaking
space characters, leading to being unable to open the unit help window.
Visual studio documentation here: https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=vs-2015
=> Added '/utf-8' character set option to Visual Studio project file

CMakeLists.txt, SConstruct, data/gui/window/statistics_dialog.cfg, src/actions/attack.cpp, src/actions/attack.hpp, src/gui/dialogs/statistics_dialog.cpp, src/gui/dialogs/statistics_dialog.hpp, src/statistics.cpp, src/statistics.hpp
Fixes #4066, see https://github.com/wesnoth/wesnoth/issues/4066#issuecomment-490973775 for an explanation.
Currently looks like this:
The screenshot shows the status after a single attack by a Silver Mage (9x4 magical) that hit 3/4.
=> Add actual/expected hit count stats to stats dialog

src/gui/dialogs/preferences_dialog.cpp
=> Fix crash when adding/removing hotkeys with no matches

src/serialization/string_utils.cpp
Behaviour for MSVC remains the same (fixed with 1 decimal).
Fix a corner-case where [999.5, 1000) would not trigger 4-digit precision,
but would be rounded to 1000 during printing, resulting in 1e+3.
=> Restore 3-significant-digit si_string (closes #3871)

changelog.md, src/gui/dialogs/multiplayer/lobby.cpp, src/server/server.cpp
Current situation:
* All observers allowed (Observers checked).
* No observers allowed (Observers unchecked).
New situation:
* All observers allowed (Observers checked, no password set).
* Some observers allowed (Observers checked, password set).
* No observers allowed (Observers unchecked).
=> Also require observers to enter a game's password.

src/server/game.cpp, src/server/game.hpp, src/server/server.cpp
This will have each game track a list of banned usernames in addition to currently tracking banned IPs.
=> Enforce game-level bans by username as well.

src/server/game.cpp, src/server/game.hpp
Currently, if someone observes with two accounts and then one account becomes a player, at no point is any message displayed about the two accounts having the same IP.
With this change a message will now also be displayed when two observers share an IP address.
=> Display when observers share IP addresses as well.

data/schema/core/addons.cfg
1. Allow carryover_percentage & carryover_add with
victory_when_enemies_defeated=no. Code from newfrenchy83 (taken from previous discussion)
2. Allow use of current_time in [time_area]. (wiki says it's valid & it works in-game)
The errors are in this report for Wings of Victory
https://travis-ci.org/wesnoth/wesnoth/jobs/552459607
=> Schema: Fix travis error by allowing additional keys in two situations

src/menu_events.cpp
:droid FULL will also set the side controller to AI, whereas ON only sets the proxy_controller.
This results in a situation where if an opponent leaves and is droided, the host will have vision to the side of the player who left.
This also results in the host *not* having vision to their original side again until it's their turn.
Fixes #3665
=> Add FULL action to :droid command.

data/core/terrain-graphics.cfg
The transitions from the Xue terrain to the Xoc / Xos / Xoi / Xom terrains were displayed incorrectly.
Fixes #4154.
=> Fixes incorrect handling of Xue transitions. 

data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg
Closes issue 2a of #1584
Previously the warning was always given on turn 7. It will still trigger even
if the player has units ready to defend that crossing, because I think it's
better to show the message and let the player think "I'm already ready" than to
have it pop up once some fighting has already happened; and it seems easier to
test this logic than to test logic for not showing the message if the crossing
is currently guarded.
Also add a first_time_only=no to the check_income event, so that it can trigger
on turn 7 if it doesn't trigger on turn 6.
=> Tutorial S2: Warn about orcs crossing the river when they cross

data/campaigns/Sceptre_of_Fire/scenarios/2_Closing_the_Gates.cfg
If all the dwarves are inside when the gate closes, don't say there were some lost outside.
Make the dialogue about the north and south side entrances only trigger once. This dialogue seems OK even if it's Baglur talking to himself.
=> SoF S2: Dialogue fixes (no dwarves outside, repeated comment about side entrances)

src/formula/variant.cpp, src/formula/variant.hpp
Fixes the majority of the warnings in issue #4166.
This class already shared copies of value_ between instances,
it seems to be the immutable design pattern so can share from
const to non-const instances safely.
Cherry-picking this to 1.14 needs a trivial conflict to be
resolved, the next line in the .cpp file has changed from
size_t in 1.14 to std::size_t in 1.15.
=> Fix Wdeprecated-copy in wfl::variant, and add move operations

src/formula/variant.cpp, src/formula/variant.hpp
Fixes the majority of the warnings in issue #4166.
This class already shared copies of value_ between instances,
it seems to be the immutable design pattern so can share from
const to non-const instances safely.
=> [1.14] Fix Wdeprecated-copy in wfl::variant, and add move operations

src/help/help_impl.cpp, src/help/help_impl.hpp
This is part of #4166, as topic_text wasn't consistent with
the Rule of Three.
Can be cleanly cherry-picked to 1.14, although there are other unrelated changes on the master branch.
=> Convert help_impl's ref-counting to std::shared_ptr

src/replay_controller.cpp, src/replay_controller.hpp
Remove code from replay_controller that's already handled by the hotkey system
Fixes a crash when playing a replay that includes a theme, when that theme doesn't
have all of the buttons that the removed code expected. For example, this replay
from SXRPG 5.2.3 has two replay themes, of which one lacks button-nextmove:
* https://replays.wesnoth.org/1.14/20190701/SXRPG_TempleOfBones_Turn_8_(53897).bz2
All of the button::enable() calls were unnecessary logic, because the hotkey
system will query replay_controller::can_execute_command() and enable or
disable the buttons to match. However, the enable() calls appear to have had
the side-effect of triggering the hotkey system to check the buttons' required
states and redraw.
Should be cherry-picked to master too.
=> Fix a crash playing a replay with an add-on theme that doesn't have button-nextmove

src/actions/vision.cpp, src/actions/vision.hpp, src/movetype.cpp, src/movetype.hpp, src/units/types.cpp, src/units/unit.cpp
Refactoring movetype and terrain_costs (#2486)
Simplify the public interface for movement, vision and jamming costs to only
the movetype class and a read-only interface called "terrain_costs".  Changes
to terrain_costs now need to be done through the movetype instance, so logic
about how movement, vision and jamming interact with each other can be handled
in movetype.  This fixes a possible dangling-pointer issue: the default
copy/move implementation in movetype::terrain_info would have copied raw
pointers, without ensuring that those pointers remained valid.
This feels too complex, but also feels like time to merge it and do any further
cleanup as a separate commit.  For example, there's only one place that calls
make_data_unique, and one place that calls make_data_shareable. Merging the …
=> Refactor movetype and terrain_costs for 1.15

changelog.md, data/campaigns/Under_the_Burning_Suns/units/units.cfg, data/core/units.cfg, data/schema/units/movetypes.cfg, src/movetype.cpp, src/movetype.hpp
This makes [movetype] consistent with [unit]. The code in movetype.cpp is used
for handling both of those tags and so already had support for "flying" in the
merge() and write() functions.
This shouldn't be backported to 1.14. For this reason, it also includes
handling the C++ todos to use C++14's std::make_unique.
=> Refactoring [movetype] to deprecate the "flies" key, use "flying" instead

src/play_controller.cpp, src/play_controller.hpp, src/playmp_controller.cpp, src/playsingle_controller.cpp, src/playsingle_controller.hpp
In hotseat games, the main map and minimap were updated and healing was animated
before blacking out the display for the turn dialog.
Fixes #4187.
=> Show the turn dialog before updating the GUI for the incoming player.

data/themes/_initial.cfg
No change for master, but this will allow me to package the asymmetric theme (#4184) as an addon.
<details>
<summary>
Screenshot with the argument at a **non-default** value:
</summary>
</details>
=> theme: Add optional argument to REPLAY_THEME for the benefit of user-defined themes

data/lua/wml-tags.lua, data/schema/units/modifications.cfg, src/units/unit.cpp
Possible fix for #4058, with the following logic (and no WML changes needed):
* If non-empty, [unit]overlay= is handled by adding modifications
* unit::write will always output an empty overlay=
* The Lua API's get_units() will still provide the list of overlays
* [effect]apply_to=overlay can now remove as well as add overlays
* [remove_unit_overlay] is implemented with [effect]apply_to=overlay
Using [object]s with durations hasn't been tested, but expected effects:
* An expired add= followed by a non-expired remove= will simply cause the remove=
to have no effect when std::remove(overlays_ ...) is called.
* A remove= followed by [remove_unit_overlay] cause the [remove_unit_overlay] to be a no-op,
and the overlay will reappear when the first remove= expires. This edge case is already …
=> Handle unit overlays as modifications, allow [effect] to remove them

doc/man/wesnothd.6, src/server/forum_user_handler.cpp, src/server/forum_user_handler.hpp, src/server/game.cpp, src/server/game.hpp, src/server/sample_user_handler.cpp, src/server/sample_user_handler.hpp, src/server/server.cpp, src/server/server.hpp, src/server/user_handler.hpp, utils/mp-server/table_definitions.sql
This requires three more tables to be added to any database with the forum user handler enabled, the structures of which are defined in the wesnothd man page:
* `db_game_info_table` - stores information about each game.
* `db_game_player_info_table` - stores information about each player in the game.
* `db_game_modification_info_table` - stores information about any modifications that are enabled for the game.
=> Add support for storing game information in wesnoth's mysql database.

src/events.cpp, src/events.hpp, src/widgets/widget.cpp, src/widgets/widget.hpp
This fixes the default implementations of widget's copy constructor and copy
assignment, which was root cause of the regression in 4139b43cc900 (#4215).
This reverts commit f46ed66f2c9a8acf8d88338d8433fc35689d4c39.
=> Rule of Five for event::sdl_handler

doc/man/wesnothd.6, src/server/forum_user_handler.cpp, src/server/forum_user_handler.hpp, utils/mp-server/table_definitions.sql
People who have MP mod authority for testing or other reasons can continue to use the existing user_is_moderator column check, but for people who are supposed to moderate the server, now the forum group will be used.
This will make it easier to add/remove people to/from the group, and also ensure that the list of actual moderators matches up with the list available to users.
New config attributes added for this are:
* db_group_table - should be, based on the phpbb documentation I found, phpbb_user_group
* mp_mod_group - should be set to Multiplayer Moderators group ID
---
Re-PR of #3964 so I can put this in a separate branch of my fork.
I am also waiting for this before continuing with some additional changes I would like to implement/enforce such as …
=> Use the MP Moderators forum group to check for mod authority.

src/play_controller.cpp
Fix a regression caused by #4188 (the fix to #4187): the turn dialog would show during replays as well.
I've tested this but it would be great if someone could review this and make sure that #4188 didn't introduce any _other_ regressions.
@linaio
=> fixup! Show the turn dialog before updating the GUI for the incoming player

data/gui/window/preferences/03_display.cfg
The tooltip now mentions that the game must be restarted for the setting to take effect. Restart is required because the setting is stored in a static variable:
https://github.com/wesnoth/wesnoth/blob/b9246dc6b4fee54751fcb37ad3ec97f751e7926a/src/display.cpp#L1662
I also removed "to 100%" and "at high resolutions". These bits provide little information and aren't always accurate.
=> Display settings: Adjust "Limit FPS" tooltip

changelog.md, src/font/text.cpp, src/font/text.hpp, src/serialization/string_utils.cpp, src/serialization/string_utils.hpp
This still requires a huge surface to render all of the text on to,
but is an easier fix for #3265 than redesigning the credits screen.
This removes the only caller of utils::vertical_split, which is why
that utility function is also removed.
=> If text is too long to render, fall back to line-by-line (fixes: #3265)

src/font/standard_colors.cpp
This is an resolve to https://github.com/wesnoth/wesnoth/issues/4094 issue.
and the result is here:
where backstab (coup  dans le dos)is inactive and poison(empoisonnement) is active.
=> resolve color active/inactive colors similars

src/gui/dialogs/network_transmission.cpp, src/gui/dialogs/network_transmission.hpp
I re-ran the timing test discussed in PR #4201 (comment linked to below), and
saw similar numbers.  The old, simpler code downloads an 86.1MB addon in 25
seconds, the code with the extra thread takes 29 seconds.
https://github.com/wesnoth/wesnoth/pull/4201#issuecomment-517856090
=> Revert network_transmission.cpp/hpp to its 1.14.7 version

data/lua/package.lua, src/scripting/lua_fileops.cpp, src/scripting/lua_fileops.hpp, src/scripting/lua_kernel_base.cpp
now wesnoth.require is able to detect when the same file is
required two times using different names (like a/../a/b.lua
a/b.lua) and will only execute it once.
for this a new function wesnoth.canonical_path was added
=> fix #4256 wesnoth.require with relative paths

src/server/player.hpp, src/server/player_connection.hpp
Attempting to call them results in an error during linking, for example:
undefined reference to `wesnothd::player::set_game(wesnothd::game*)'
=> Remove non-functional methods from player.hpp.

po/wesnoth-ai/sk.po, po/wesnoth-anl/bg.po, po/wesnoth-editor/af.po, po/wesnoth-editor/cs.po, po/wesnoth-editor/el.po, po/wesnoth-editor/lt.po, po/wesnoth-httt/af.po, po/wesnoth-httt/it.po, po/wesnoth-l/ru.po, po/wesnoth-lib/en_GB.po, po/wesnoth-lib/it.po, po/wesnoth-nr/ga.po, po/wesnoth-nr/lt.po, po/wesnoth-tutorial/hr.po, po/wesnoth-tutorial/sv.po, po/wesnoth-units/en_GB.po, po/wesnoth-utbs/en_GB.po, po/wesnoth/af.po, po/wesnoth/cs.po, po/wesnoth/et.po, po/wesnoth/lt.po, po/wesnoth/nl.po, po/wesnoth/pl.po, po/wesnoth/sv.po
Clean-up as described in #2965. See commit message for details.
=> Remove description prefixes from translated strings (1.14)

changelog.md, src/map_command_handler.hpp, src/menu_events.cpp
Backport of #4276
This removes all of the "do not translate part^string part" strings, replacing
them with more help in English and a place for translators to explain what the
untranslatable "all" means. For commands where the usage has notes about the
arguments, this embeds the \n in the strings passed to register_command; that
seems a reasonable balance between usability and effort to implement it.
Cherry-picking between 1.14 and 1.15: In 1.14.x, the "droid" command only has
options "on" and "off". The "full" option was only added in 1.15.
=> [1.14] Use multiple lines for help, and replace "do not translate part" with translation notes

changelog.md, src/map_command_handler.hpp, src/menu_events.cpp
This was inspired by @Wedge009 's #4271 , where these were one of the hotspots for problems.
However, I'm wondering if we should suggest that the translators add translations of what the non-translated English parts mean. For example:
> en: `[all|<command>]`
> de: `[all|<Befehl>]` <i>(»all« = Hilfe für jedem Befehl)</i>
For the `droid` command's `on` and `full`, that might be useful for English too.
=> [1.15] Use multiple lines for help, and replace "do not translate part" with translation notes

src/menu_events.cpp
Now, if no action is provided and the current side's controller or proxy controller is the AI, the side is changed to fully human control (same as `:droid <side> off`). If no action is provided and neither the controller or proxy controller of the current side are controlled by the AI, then the controller is set to human and the proxy controller set to AI(same as `:droid <side> on`).
Fixes #4308
=> Fixes the droid command's options not all being optional.

data/campaigns/Under_the_Burning_Suns/scenarios/09_Blood_is_Thicker_Than_Water.cfg
At the end of S09, the heroes have four ships. The narrative is that all the
elves are on the ships, but the in-game visuals were that the ships move while
all the player's units are standing on the shore.
The heal=yes isn't needed since 74c2398f6, but adding it here avoids
a possible bug if this commit is backported to 1.14.
=> UtBS S09: Non-merfolk get in the ships before they sail off

data/themes/default.cfg
Tested against master, already resolved for 1.14, resolves #3693.
May be good for @hrubymar10 to double-check this. Submitting as PR because I'm not sure what the figures mean for the theme configuration plus I don't know if the second of the three lines changed (which conflicts with later changes in master) needs further adjustments.
=> Restore defence modifier display in side-bar

changelog.md, data/schema/terrain/types.cfg, src/terrain/terrain.cpp
The feature was never added, a deprecation message saying that it's been
removed is the closest option to the situation. While terrain.cpp itself
supports vision_alias, it was never added to the calculations in movetype.cpp,
therefore it never affected units' vision. It's also not shown in the help
about the terrain.
This doesn't affect the features of units having vision costs different to
movement costs, or of units having a different number of vision points to
movement points, both of which are still supported.
While I'd encourage anyone who wants to implement vision_alias to do so, at the
moment I feel that the still-supported features in the same area haven't been
explored yet, and that vision_alias isn't going to developed before 1.16.0 is
released.
Issue #3148 would be closed by …
=> Trigger an L4 deprecation message for [terrain_type]vision_alias=

data/lua/wml/find_path.lua, data/schema/core/actionwml.cfg, data/schema/game_config.cfg, data/test/maps/simple_find_path.map, data/test/scenarios/simple_find_path.cfg, wml_test_schedule
Adding this is issue 2 of #4177, changing the behavior when [find_path]
is given a SLF which matches multiple hexes. Issue 1 of #4177 is to convert
the unit test and PR docs to wiki documentation about the current behavior.
The map and tests here should be easy enough for manually editing them. It
duplicates some of the functionality of the existing characterize_pathfinding
tests, however those tests need their expected values to be calculated and
can't be changed by hand.
'''nearest_by''': {DevFeature1.15|2} possible values "movement_cost"
(default), "steps", "hexes". If the [destination] SLF matches multiple hexes,
the one that would need the least movement points to reach may not be the one
that's closest as measured by '''hexes''', or closest as measured by steps,
from the starting …
=> Add [find_path] option "nearest_by", and simple_find_path test

data/tools/pywmlx/state/lua_states.py, data/tools/wmlxgettext
The original fix for #3469 introduced some bugs I did not notice as reported on issue #4275. So I reverted back the code to it's previous status and I re-fixed the bug #3469 with a regexp more similar to the original one and less simplified. This time it sees that wmlxgettext actually work as expected, and seems it is able to handle both mentioned corner cases. The new fix also allow again to recognize lua plural strings. I will attach a test.lua file I use to test the features and the resulting test.pot.     
>   ./wmlxgettext --domain="test" -o test.pot test.lua
[test.zip](https://github.com/wesnoth/wesnoth/files/3569691/test.zip)
=> wmlxgettext: fix #4275: not handle objectives.lua's turn counter

data/campaigns/Heir_To_The_Throne/scenarios/15_The_Lost_General.cfg, data/campaigns/Heir_To_The_Throne/scenarios/23_Test_of_the_Clans.cfg, data/campaigns/Heir_To_The_Throne/utils/httt_utils.cfg
There's a dialog hint just above the diff:
https://github.com/wesnoth/wesnoth/blob/57668733a26e04671025905935cea00555cd06a5/data/campaigns/Heir_To_The_Throne/scenarios/23_Test_of_the_Clans.cfg#L299-L302
But on EASY, make the hint explicit.
Come to think of it, the dialog hint is actually ambiguous: "defeat me personally" can be understood as though Konrad has to attack Lord Bayar, can't it? So how about removing the word "personally" from that line?
=> HttT S23: Give a more explicit hint on EASY

data/campaigns/Heir_To_The_Throne/scenarios/14_Plunging_Into_the_Darkness.cfg, data/campaigns/Heir_To_The_Throne/scenarios/15_The_Lost_General.cfg
=> HttT S15: Improve dialog flow when Geldar survives

data/core/units/saurians/Ambusher.cfg, data/core/units/saurians/Flanker.cfg, data/core/units/saurians/Skirmisher.cfg
This PR adds `female^` prefix to the female saurian unit types to help with proper translation. See also https://github.com/wesnoth/wesnoth/commit/7027930cf1766e4c3d0c9e0138dbbc55adc4bfbe
=> Added translation prefix to female saurian unit types.

src/game_initialization/playcampaign.cpp, src/playmp_controller.cpp, src/playturn.cpp, src/wesnothd_connection_error.hpp
This affects the stopgame command and :kick, for example.
Fixes #4370
=> Fix [leave_game] being ignored by clients during linger.

data/gui/window/unit_recall.cfg, src/font/text_formatting.cpp, src/font/text_formatting.hpp, src/gui/dialogs/unit_recall.cpp, src/gui/dialogs/unit_recruit.cpp, src/menu_events.cpp, src/units/unit.hpp
Part of issue #1282.
Looks like this:
<details>
<summary>
test case
</summary>
```
diff --git a/data/campaigns/An_Orcish_Incursion/scenarios/01_Defend_the_Forest.cfg b/data/campaigns/An_Orcish_Incursion/scenarios/01_Defend_the_Forest.cfg
index 53ea5f5be8e..596689ec975 100644
--- a/data/campaigns/An_Orcish_Incursion/scenarios/01_Defend_the_Forest.cfg
+++ b/data/campaigns/An_Orcish_Incursion/scenarios/01_Defend_the_Forest.cfg
@@ -50,7 +50,7 @@
[side]
side=1
controller=human
-        {GOLD 200 150 100}
+        gold=20
income=0
team_name=Elves
user_team_name= _ "Elves"
@@ -61,6 +61,10 @@
facing=nw
+        {UNIT 1 Mage recall recall ()}
+        {UNIT 1 Mage recall recall (recall_cost=25)}
+        {UNIT 1 Peasant recall recall ()}
+
[unit]
side=1
type=Elvish Rider
```
</details>
=> unit_recall: Show unrecallable units grayed out.

data/campaigns/Legend_of_Wesmere/_main.cfg, data/campaigns/Legend_of_Wesmere/scenarios/chapter2/08_Council_of_Hard_Choices.cfg, data/campaigns/Legend_of_Wesmere/scenarios/chapter4/15_The_Treaty.cfg, data/campaigns/Sceptre_of_Fire/scenarios/1_A_Bargain_is_Struck.cfg
This bug was a problem: https://github.com/wesnoth/wesnoth/issues/4314
The discussion regarding it can be found here: https://forums.wesnoth.org/viewtopic.php?f=8&t=50702
=> Resolving date inconsistency

data/gui/window/preferences/02_hotkeys.cfg, src/gui/dialogs/preferences_dialog.cpp
Suggested in https://github.com/wesnoth/wesnoth/issues/1152#issuecomment-535022785 and mitigates #1499.
=> Replace hot-key markers with initials

src/gui/widgets/unit_preview_pane.cpp, src/help/help_impl.cpp, src/help/help_topic_generators.cpp, src/map/map.cpp, src/movetype.cpp, src/terrain/terrain.cpp, src/terrain/terrain.hpp, src/terrain/translation.cpp, src/terrain/type_data.cpp, src/terrain/type_data.hpp
Change terrain_type_data's documentation and some methods to avoid exposing
implementation details, for example renaming try_merge_terrains to is_known.
Move the code to load all the [terrain_types] in to the terrain_type_data
class's own .cpp file, and out of terrain.cpp.
Add documentation about "underlying", and why worst(best(a,b),c,d) terrains don't work
The commented-out code for merging pluses and minuses in the middle of an alias
was commented out in 1.5's d2edbe118a5f49ca96268c6b5f6a4b2110df7cc2, but the
concept of pluses and minuses in the middle of an alias seems broken anyway
(see comments added to merge_alias_lists in this commit).
Descriptions are t_strings, avoid converting them to std::string and back.
=> Improve the terrain code's encapsulation

data/campaigns/Northern_Rebirth/scenarios/06a_Old_Friend.cfg
Now it only triggers if five or less units are outside. Every unit in the cave but illuminated by a MoL is counted as inside, not outside.
=> NR S06a: Fix the filter for Tallin complaining that they're sitting in the caves

data/ai/micro_ais/scenarios/simple_attack.cfg
@mattsc a suggestion for https://github.com/wesnoth/wesnoth/issues/3450#issuecomment-538598827
The default 1.14 already considers high-XP attacks.  Other than the dialogue,
the only change is to reduce the AI's default aggression, so there's more
contrast between what the Micro AI does compared to what the default AI does.
Switched to typographic quotation marks in the dialogue, and removed double
spaces between sentences.
=> Simple Attack Micro AI Demo: Update dialogue for 1.14's AI improvements

src/game_initialization/lobby_data.cpp
Currently, the value of `game["savegame"]` is one of `mp_game_settings::SAVED_GAME_MODE`.  However, the `to_bool()` function doesn't recognize any of those values as being true, so a game is always shown in the MP lobby as not being a reload, even if it actually is.
=> Fix the MP lobby reloaded indicator always saying the game isn't reloaded.

data/core/terrain.cfg, src/gettext.cpp
Two commits, which I've put in the same PR because the new mushroom text will be the first text displaying carets to the user. Will happily merge just the .cpp change if the prose needs more work.
Allow translatable strings to display carets to the user (#4359)
---
Treat `editor^The overlays '^Uf' and '^Ufi' are deprecated because ...` as a having translation hint `editor`, and show "The overlays ..." to the user. This disallows using carets inside the translation hint itself.
Code already reviewed in the discussion in #4359.
Help for the ^Uf mushrooms terrains, including an editor-only hint
---
As the terrain is hidden in help, these hints can only be seen by using the "Terrain Description" command on a ^Uf or ^Ufi mushroom hex, and then switching to the overlay's own page.
A hint for …
=> Help for the ^Uf mushrooms terrains + display carets to the user (#4359)

changelog.md, data/core/editor/help.cfg, data/core/help.cfg
... with the idea that these pages will either be improved or hidden again before 1.16.0. I think the terrain-editor part is good enough to stay in 1.16. The scenario editor part would have to be updated by someone familiar with that part.
This puts the two tips that are currently in https://wiki.wesnoth.org/MapEditor in to the in-game text.
=> Re-enable the editor help, and use it to document the keyboard modifiers

data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg
It's confusing when it pops up on turn 12, regardless of the game state. My
leader is normally on the other side of the river from my keep, and I always
wonder "what about my play triggered that?"
Move the message to be part of the "I now have enough gold to recruit more
units" hint.
=> Tutorial S02: Show "recruit the right units" when the player has gold

src/game_board.hpp, src/map_command_handler.hpp, src/menu_events.cpp, src/synced_commands.cpp
Usage: `:terrain <terrain type> [both|base|overlay]`
=> Add debug command :terrain.

data/campaigns/Heir_To_The_Throne/scenarios/15_The_Lost_General.cfg, data/campaigns/Heir_To_The_Throne/scenarios/19b_Swamp_Of_Dread.cfg, data/campaigns/Heir_To_The_Throne/scenarios/19c_Cliffs_of_Thoria.cfg, data/campaigns/Heir_To_The_Throne/scenarios/20a_North_Elves.cfg, data/campaigns/Heir_To_The_Throne/scenarios/21_Elven_Council.cfg
Originally from [this forum post](https://forums.wesnoth.org/viewtopic.php?f=38&t=43099&p=647379#p647362), although there's very little resemblance between the suggestions there and this PR.
Does the `Timber!` line work? I'm not sure. If it doesn't, I'll just delete that line so the flow is (thunderstick sound) (Konrad: What was that?) and then Delfador's line. Maybe have a dwarf say that it must be Lord Geldar's clan up ahead.
=> HttT: dialog tweaks and additions

src/gui/dialogs/game_stats.cpp
Note that all sides' gold status is already shown whenever debug mode is active.
Fixes part of #4134
=> Status table: In replays with "View: Full Map", show all sides' gold status

data/multiplayer/scenarios/2p_Aethermaw.cfg, src/gui/dialogs/multiplayer/mp_create_game.cpp
Fixes the second bullet of https://github.com/wesnoth/wesnoth/issues/4397#issuecomment-536357310.
Could someone double check the change to the generator_assigned condition? Is it about the case that a scenario file defines both map_file and a map generator? I would have expected that to be an error, actually.
=> mp_create_game: Show preview if map_file is set

src/serialization/preprocessor.cpp
=> Preprocessor: Add {LEFT_CURLY} and {RIGHT_CURLY} escape sequences

src/display.cpp, src/display.hpp, src/map/map.hpp
In the test scenario, toggling between 50%/100% zoom on 1920x1080 will now correctly switch between "Show the entire map" (50%) and "Show just the center of the map" (100%).
Fixes #1951
=> Display: Don't move the center of the viewport when zooming in when the map is narrower/shorter than the viewport

src/deprecation.cpp, src/filesystem.cpp, src/wesnoth.cpp
See individual commit messages for details.
I'd like to backport the wesnoth.cpp and deprecated.cpp parts. I'm not sure if I should backport the filesystem.cpp changes too.
The filesystem.cpp part is for issue #2000.
=> Changes to deprecation logging and deprecate --userdata-dir=relative-path

src/actions/create.cpp, src/gui/dialogs/unit_recruit.cpp, src/gui/dialogs/unit_recruit.hpp, src/menu_events.cpp, src/menu_events.hpp
Fixes #4443. This doesn't add or remove any units to the recruit dialog, it simply makes units that will fail to be recruited be listed in gray.
See the individual commits for details.
=> recruit dialog: Gray out units that will not be able to be recruited

changelog.md, data/game_config.cfg, data/themes/default.cfg, src/display.cpp, src/display.hpp, src/editor/controller/editor_controller.cpp, src/hotkey/command_executor.cpp, src/preferences/general.cpp, src/preferences/general.hpp
Resolves #1518
I don't know if this is the 'right' way to do things - there are a lot of places where preferences are set. There is a display preferences class and a display class, but also most things seem to be recorded in general preferences class. `tile_size` is referred to in `game_config.cpp` and the actual zooming is done inside the display class, using `game_config::tile_size` as the `DefaultZoom`. The default `tile_size` seems to be hard-coded to 72 in a few places.
Regardless, this seems to work for me.
=> Remember tile_size/zoom factor between play sessions

src/menu_events.cpp
This was an edge-case when the player had only one unit, logged as #4466.
This change looks fairly straightforward, will merge it tomorrow if it doesn't have any comments.
=> Make a unit respond to mouse-clicks after end_unit_turn (fixes #4466)

data/ai/lua/ca_recruit_rushers.lua, data/ai/lua/generic_recruit_engine.lua, data/ai/micro_ais/cas/ca_recruit_rushers.lua, data/ai/micro_ais/mai-defs/recruiting.lua, data/core/macros/ai.cfg
The ExpAI recruits almost no higher level units. In the scenarios I tested with default era units, there's maybe one L2 unit recruited every dozen or so recruits.  Yet, it's reasonable to assume that if scenario designers give the AI higher level units to recruit, they expect that to happen not just sporadically.
The reason why almost no L2s or higher are recruited might be partially because unit cost is not as well balanced for the higher level units.  But mostly it happens because cost is penalized by the ExpAI recruiting.  This is in order "to avoid recruiting many expensive units -- there is a requirement for bodies in order to block movement" as per a comment in the code. I don't want to change that, as it would mess up the recruiting ratios of L1 units of different cost, so instead …
=> Experimental AI: make AI recruit higher level units

data/core/units/drakes/Arbiter.cfg, data/core/units/drakes/Warden.cfg, data/core/units/elves/Avenger.cfg, data/core/units/elves/Ranger.cfg, data/core/units/humans/Loyalist_Halberdier.cfg, data/core/units/humans/Loyalist_Pikeman.cfg, data/core/units/humans/Loyalist_Royal_Guard.cfg, data/core/units/humans/Loyalist_Swordsman.cfg, data/core/units/humans/Mage_Arch.cfg, data/core/units/humans/Mage_Great.cfg, data/core/units/humans/Mage_Red.cfg, data/core/units/humans/Mage_White.cfg, data/core/units/humans/Mage_of_Light.cfg
Add special_notes that summarize the movetype differences between level 2 units and their respective level 1 forms, to make the differences easy to discover.
=> units: Add custom [special_note]s.

changelog.md, data/tools/pywmlx/state/machine.py, data/tools/pywmlx/state/wml_states.py
This adds support for _<<map="{maps/01_First_Map.map}">>.
@AncientLich , please would you review?
=> wmlxgettext: support double quotes in raw strings (fixes #4484)

src/help/help.cpp
Related to issue #4507, which is asking for better handling of the parse_error.
This commit doesn't improve the handling, but it will hopefully avoid anyone
spending time debugging to work out what text triggered #4507.
=> Log a console error message when a parse_error closes the help

data/core/units.cfg
PR for https://github.com/wesnoth/wesnoth/issues/4454
Adding mushroom defense cap to human mounted units, dunefolk mounted units and several flying units (Gryphon, Wyvern and Roc)
I noticed that dunefolk mounted units don't have forest defense cap. I will communicate to Hejnewar (who was working on the Dunefolk rebalancing) regarding that.
P.S. Hejnewar shared an idea of adding mushroom defense cap to orcs. However, that is debatable, so I am not adding it here.
=> Added mushroom defense cap to mounted and several flying units

data/campaigns/Son_Of_The_Black_Eye/scenarios/11_Clash_of_Armies.cfg
Per comment from @Konrad22 
> Hey, I've got a small issue with SotBE S11. Or rather with the scenario objectives. The defeat condition is 'Enemies control any villages on the north side of the river when turns run out' At least, that's what it says. The actual defeat condition is 'You don't control all villages on the north side of the river when turns run out' (There is one leaderless enemy side, so those two sentences don't mean the same thing.)
=> Corrected SotBE S11 objectives

src/game_launcher.cpp
When completing the tutorial, the preferences file's [completed_campaigns]
recorded that "" had been completed at difficulty NORMAL. This is an old
bug, unrelated to the other tutorial changes that I'm making, but would
cause problems if we want to change the UI based on whether the tutorial
has already been completed.
=> Fix the add_completed_campaign() call for the tutorial

data/tools/wmllint
This fixes situation when wmllint tried to add `description=_"fireball"`
to the following WML code:
```
[filter]
[filter_wml]
[not]
[attack]
name=fireball
[/attack]
[/not]
[/filter_wml]
[/filter]
```
Tags within `[filter_wml]` don't need to have all mandatory arguments
(like "description"), because:
1) they are temporary constructs and this description is never used,
2) such WML code expects that results will be filtered ONLY by name.
Adding description will remove results that have the same attack name
but different description.
=> wmllint: don't analyze WML within [filter_wml] blocks (most checks are not applicable to its contents)

data/campaigns/The_Rise_Of_Wesnoth/units/Noble_Commander.cfg, data/campaigns/The_Rise_Of_Wesnoth/units/Noble_Lord.cfg
Fixes https://github.com/wesnoth/wesnoth/issues/4541
When sword or ruby of fire is used, second animation will not pass filter and first one will be selected. When bow is used, second animation earns additional point for filter matching (see https://wiki.wesnoth.org/AnimationWML#Generic_animation_filters_available_for_all_animations) and will be selected.
=> TRoW: Fixed Haldric's defense animations

changelog.md, src/gui/dialogs/campaign_selection.cpp
This should extend the dialog's usefulness in a way that is more or less consistent with the Add-ons Manager's search function. Although one issue is that abbreviations are often found floating around in their English form ("HttT") instead of the various localized versions ("HaT").
=> Campaigns Menu: Make descriptions and abbreviations search terms

data/tips.cfg
"The Wesnoth Tactical Guide" is chosen because it is also used for these tips:
- Read the Hotkeys list in the Preferences menu ...
- You can see how far enemy units can move by moving the mouse cursor over them ...
- Nearly every button and icon in the Wesnoth game has a tooltip ...
- You cannot undo a move that uncovers hexes hidden by fog or shroud ...
=> Added tip of the day regarding changing difficulty level in a mid-campaign

changelog.md, data/gui/widget/text_box_default.cfg, data/schema/gui.cfg, src/gui/widgets/text_box.cpp, src/gui/widgets/text_box_base.cpp, src/gui/widgets/text_box_base.hpp
This gives GUI2 textboxes (and password boxes since they are a subclass) a simple hover effect by extending the canvas definitions for the widget accordingly.
=> gui2/text_box: Add hover effect

data/gui/window/mp_create_game.cfg, data/gui/window/mp_create_game/default_resolution.cfg, data/gui/window/mp_create_game/small_resolution.cfg, data/gui/window/mp_create_game/tiny_resolution.cfg, src/game_initialization/configure_engine.hpp, src/game_initialization/lobby_data.cpp, src/game_initialization/lobby_data.hpp, src/gui/dialogs/multiplayer/mp_create_game.cpp, src/gui/dialogs/multiplayer/mp_create_game.hpp, src/mp_game_settings.cpp, src/mp_game_settings.hpp, src/server/server.cpp
This makes it possible for a game to allow observers but have the replay not be public.
---
This resolves the second part of #3909
=> Add a separate toggle for if a replay should be public.

data/core/units/dwarves/Lord.cfg, data/core/units/dwarves/Pathfinder.cfg, data/core/units/dwarves/Sentinel.cfg, data/core/units/dwarves/Stalwart.cfg, data/core/units/dwarves/Steelclad.cfg, data/core/units/dwarves/Thunderguard.cfg
The counterpart to https://github.com/wesnoth/wesnoth/pull/4516, the steelclad/lord line was too strong, while other dwarvish level 2s are often too weak. Namely, Pathfinder and Thunderguard have too little HP (Pathfinder only has 42 and Thunderguard 44, compared to something like the Longbowman's 51, Pikeman/Swordsman 55). Additionally, the Stalwart and Sentinel do too little damage to justify their exp and costs (Stalwart has 7-3 melee pierce, the same as the level 1 Spearman,  but without even the firststrike special). Hopefully we can tweak their stats a bit to make them a bit better.
List of changes:
Pathfinder HP 42 -> 45
Thunderguard HP 44 -> 47
Stalwart Melee 7-3 -> 8-3
Sentinel Melee 9-3 -> 10-3
Tagging @soliton- and @Krogen2 for comments.
=> [Dwarves] Buff some level 2 units

changelog.md, data/tools/tmx_trackplacer, data/tools/wesnoth/trackplacer3/__init__.py, data/tools/wesnoth/trackplacer3/cfgfileformat.py, data/tools/wesnoth/trackplacer3/datatypes.py, data/tools/wesnoth/trackplacer3/tmxfileformat.py
The python2 trackplacer included both the handling of the file format, and the
GUI application. This trackplacer3 is a library for the file format, without
the GUI.
The tmx_trackplacer is a command-line tool for exporting the data to Tiled's
.tmx format, and re-importing it back to .cfg files, so that the GUI of Tiled
can be used to avoid reimplementing the GUI of Trackplacer in Python 3.
The implementation uses Tiled's Object Layers (not Tile Layers).  This allows
additional journey markers to be added with the "Insert Tile" tool, and
additional journeys to be added as new layers.
It can also read in a .cfg and then re-export it to a new .cfg file, to see if
the data is preserved. The format is chosen by the output filename.
----- Comments on the mainline campaigns: -----
AToTB, DM, LoW, …
=> trackplacer3 a utility to export and import tmx files (#4365)

.travis.yml, utils/dockerbuilds/mingw/Dockerfile, utils/dockerbuilds/travis/Dockerfile-base-mingw, utils/travis/docker_run.sh, utils/travis/steps/script.sh
Of note:
* The image now created by Dockerfile-base-mingw is available on wesnoth's Docker Hub.
* Strict building is disabled, as there are a couple warnings that show up when crosscompiling.
---
Said warnings:
https://travis-ci.org/Pentarctagon/wesnoth/jobs/612518109#L449-L467
https://travis-ci.org/Pentarctagon/wesnoth/jobs/612518109#L1135-L1136
https://travis-ci.org/Pentarctagon/wesnoth/jobs/612518109#L1170
=> Add mingw crosscompile job to travis.

data/ai/lua/ca_castle_switch.lua, data/ai/lua/ca_grab_villages.lua, data/ai/lua/ca_high_xp_attack.lua, data/ai/lua/ca_move_to_any_enemy.lua, data/ai/lua/ca_place_healers.lua, data/ai/lua/ca_recruit_rushers.lua, data/ai/lua/ca_retreat_injured.lua, data/ai/lua/ca_spread_poison.lua, data/ai/lua/ca_village_hunt.lua, data/ai/lua/generic_recruit_engine.lua, src/ai/composite/aspect.hpp, src/ai/composite/goal.cpp, src/ai/composite/rca.cpp, src/ai/composite/rca.hpp, src/ai/default/aspect_attacks.cpp, src/ai/default/ca.cpp, src/ai/default/ca_move_to_targets.cpp, src/ai/default/recruitment.cpp, src/ai/lua/core.cpp, src/ai/lua/core.hpp, src/ai/lua/engine_lua.cpp
This allows restricting the CA to only a subset of the units. It is a first step toward solving Issue #2349, which calls for adding `[filter_own]` tags to all candidate actions. In my experience, it is one of the most serious shortcomings of the default AI. See #2349 for more information and additional comments.
So far, this is only implemented for the move-to-targets CA, as I want to see if there are comments before I add it to the other CAs as well.
`[filter_own]` is chosen as the tag name, because that's what is used for the only CA (combat) for which this exists already.
=> AI: add [filter_own] to all candidate actions

src/commandline_options.cpp, src/commandline_options.hpp, src/game_launcher.cpp, src/game_launcher.hpp, src/wesnoth.cpp
The C++ part of issue #4535
This allows batching all of the tests that are expected to return status zero,
which is currently 161 tests, and running the batch with a single instance of
Wesnoth.  It doesn't include the changes to the run_wml_tests script to use
this new feature (and I'd welcome someone else refactoring that script).
Timing on my PC:
* 4 seconds to run a single test on a debug build
* 90 seconds to run the whole batch of 161 on a debug build
* 1.2 seconds to run a single test on a release build
* 31.2 seconds to run the whole batch of 161 on a release build
I feel it's hacking more complexity on top of the wesnoth.cpp / game_launcher.cpp / commandline_options.cpp / title_screen.cpp spaghetti, but faster testing means people are more likely to run the tests.
The main output …
=> Support running multiple expected-to-pass unit tests

src/gui/widgets/generator.cpp, src/gui/widgets/generator.hpp
In the load-game dialog, this makes deleting a file select the next
visible game save, thus it fixes #4125.
Credit and many thanks to @DisherProject for the inspiration and hard
work of debugging where to fix this.
=> Select the correct item in a filtered and sorted generator

run_wml_tests
The verbosity settings are a bit different, but other than that it
should be a drop-in replacement for the old shell script.
Wesnoth's --validcache option isn't used any more, which is part of
the cleanup for #4587 (it didn't speed anything up, because all of
the calculation for the checksum was still done).
@CelticMinstrel please would you test the xcode support? I think
I've implemented it correctly, but don't have a Mac to test on.
=> Port run_wml_tests to Python and add batch support (part of #4535)

src/actions/advancement.cpp, src/actions/advancement.hpp, src/actions/attack.cpp, src/actions/attack.hpp, src/ai/actions.cpp, src/ai/actions.hpp, src/ai/contexts.cpp, src/ai/lua/core.cpp, src/ai/manager.cpp, src/ai/manager.hpp
fixes #4605
previously advancements invoked by [event]s for example
by unstoring a unit with enough xp would alwas do a
purely random advancement even if they happend during
the ais own turn. Now the advancemt_aspect is considered
i don't really know how the code inside ai/ works so i
just took the easiert way to get a advancements_aspect
from the manager. In particular this leaves a TODO comment
about whether the advancemnts_aspect of advance_unit_at
(and thus of attack_and_advance) can not be removed or not
because i don't know whether the advancement aspect is
effectively a sinbgleton or not.
=> wip use ai advancement asepect also during [event]s

run_wml_tests
This commit:
* Adds the new `bt` (batch timeout) option, to limit the maximum time batched unit tests can take.  Otherwise, if for whatever reason they take longer than 10 minutes, travis will error the job due to not receiving any output for too long.
* Writes the test output to files rather than trying to get it from the stderr, and then output's the log from the failed test.  Currently if a test unexpectedly times out, there is nothing printed indicating the error or which test encountered the problem (in case of batched tests).
=> Improves the WML unit test script's error reporting.

data/core/units/dunefolk/Alchemist.cfg, data/core/units/dunefolk/Apothecary.cfg, data/core/units/dunefolk/Captain.cfg, data/core/units/dunefolk/Firetrooper.cfg, data/core/units/dunefolk/Luminary.cfg, data/core/units/dunefolk/Marauder.cfg, data/core/units/dunefolk/Raider.cfg, data/core/units/dunefolk/Rider.cfg, data/core/units/dunefolk/Scorcher.cfg, data/core/units/dunefolk/Skirmisher.cfg, data/core/units/dunefolk/Warmaster.cfg, data/core/units/nagas/Dirkfang.cfg, data/core/units/nagas/Ringcaster.cfg, data/core/units/nagas/Zephyr.cfg, data/multiplayer/factions/dunefolk-aoh.cfg, data/multiplayer/factions/dunefolk-default.cfg
Hello,
the usage attributes for AI recruitment of some dunefolk units are odd. Additionally, the current recruitment_pattern includes scout but does not include healer, while the Dune Herbalist has usage=healer and no dunefolk unit has usage=scout at the moment.
More details on the values that the proposed new usage attributes are based on can be found below.
I do not know if the suggested new recruitment_pattern is optimal, but it includes all occurring usage attributes, with weights according to the number of default era recruits of that type (2:2:1:1:1). In the few simple AI versus AI tests I did, the win ratio against other factions was quite okay.
Details:
each entry: level, id (ratio melee damage/ranged damage, some relevant abilities and weapon specials)
total: 33 (counting …
=> Dunefolk usage attributes and recruitment patterns

src/game_events/action_wml.cpp
Fixes 8080271231adddb3a3e88297d5fc52d37e3de7d7's Eternal Night. The northern
parts of both 10 and 10a are the same, but 10a is extended southwards; this
caused some confusion thinking that the map-load hadn't changed anything.
The regexp code is removed, as @gfgtdf comments in #4633: "I'm quite sure that I
wrote that code but I don't remember why, I was probably just extra cautious.
In particular with the existence of wesnoth.read_file nowdays there is little
point in these checks."
Removing the regexp code allowed merging with the codepath for handling
[scenario]map_file=, which will allow the main issue of #4633 (searching other
folders for maps) to automatically affect [replace_map] too.
=> Fix [replace_map]map_file= when called in a prestart event

data/tools/vim/wesml.vim
store_village and story had no space between them, so they didn't
highlight correctly.
Sorry if chose the wrong branch to merge to, I didn't see anything about that in the wiki.
=> Typo fix in wesml.vim.

src/actions/advancement.cpp
the list returned by `ai_advancement.get_advancements` is a priority list, so we use the first valid entry instead of a random one.
=> fix #4626 ai advacement aspects regression

src/filesystem_boost.cpp, src/tests/test_filesystem.cpp
The Boost-based C++ unit tests generate three messages about duplicates,
however as those tests don't run in strict mode this doesn't cause a
failure (and it's not the only warning-level message in those tests).
The 1.15 version of this will be in PR #4654 .
Example output:
```
20191221 17:18:31 warning filesystem: Conflicting files in binary_path: '/home/USER/.local/share/wesnoth/1.14/data/add-ons/Desert_Map-Pack/images/maps/background.jpg' and '/home/USER/development/other-source/wesnoth/branch_1_14/data/core/images/maps/background.jpg'
```
=> [1.14] Log a warning if a file is found in more than one [binary_path]

data/test/scenarios/filter_this_unit.cfg, run_wml_tests, src/commandline_options.cpp, src/game_launcher.cpp, src/game_launcher.hpp, wml_test_schedule
This is part of working out whether a subset of the "fail" tests could be run in one Wesnoth instance. To run a test that returns TEST_FAIL_BROKE_STRICT with any other test would require a mechanism to reset lg::broke_strict()'s flag.
All tests that fail with an {ASSERT} will also set the lg::broke_strict() flag, the tests with the new status are only those that would pass without the strict flag.
In the SUF tests, change a test from fail-on-success to breaks-strict, rename the formula tests and add some comments. The rename is because "fai" is "Formula AI", an obsolete name for WFL.
=> Separate unit test statuses for WML exceptions and strict warnings

packaging/flatpak/org.wesnoth.Wesnoth.json
Currently both on jenkins and locally building Wesnoth's flatpak gives the warning:
scons: warning: parallel builds are unsupported by this version of Python;
ignoring -j or num_jobs option.
This is apparently due to an issue between scons 3.0.1 and python 3.7+, which was reported at https://github.com/SCons/scons/issues/3145, fixed in https://github.com/SCons/scons/pull/3150, and is therefore first included in scons 3.0.2.
---
As far as running a flatpak job on travis, it is technically possible and I have a working docker image for it, however it takes longer than the 50 minute limit we have on travis to build the boost libraries, scons, and then Wesnoth.
=> Fixes a warning about scons builds with multiple threads.

data/test/scenarios/filter_this_unit.cfg, doc/man/wesnoth.6, run_wml_tests, src/commandline_options.cpp, src/commandline_options.hpp, src/game_launcher.cpp, src/game_launcher.hpp, src/wesnoth.cpp, wml_test_schedule
Note: needs to wait for the AppVeyor build to confirm that it fixes #4471.
The main reason for backporting all of this is to have separate unit test
statuses for WML exceptions and strict warnings, so that this mechanism can be
used instead of a793bce96's method of running the cve_2018_1999023 test in
non-strict mode, which means that the test now passes without making
equivalent-to-a793bce96 changes to projectfiles/VC12/WML_tests.cmd and
projectfiles/VC16/WML_tests.cmd.
The final commit, converting run_wml_scripts to Python, could be omitted. To
allow this, commit 7359fddecb8dafdb8bec33660259ec5e2fec4141 was reordered
slightly, with the changes to the script (adding the new statuses) in a
separate commit to the C++ changes.
Cherry-picked from the commits:
* …
=> Backport unit test framework changes (fixes #4471)

data/multiplayer/scenarios/2p_Aethermaw.cfg, src/gui/dialogs/multiplayer/mp_create_game.cpp
This branch combines fixes needed for using map_file.
See issues #4407, #4397, #4519, and #4652 for details.
=> Backport map_file feature fixes for 1.14

src/game_initialization/create_engine.cpp
Can be cleanly cherry-picked between 1.14 and master, and tested on both. Sample output:
```
20191229 18:22:08 error config: Found a [campaign] with neither a name nor an id attribute, ignoring it
20191229 18:25:18 error config: Ignoring a [campaign] with no id attribute, but name 'Tactics Puzzles'
```
=> Error handling for campaigns without id (fixes #4664)

data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg
Add more reminding PRINT messages, disallow_end_turn messages, and fix a bug where player can just capture village and end turn without recruiting/recalling units.
=> Tutorial S2 - Capturing village bug-fix, add more instructions about capturing and recruiting

src/gui/dialogs/multiplayer/mp_create_game.cpp
The multiplayer create game menu shows scenarios as having map size 0x0.
To reproduce this bug, select "Multiplayer" from main menu, then "Local Game".  After "OK" button pressed, select any scenario, and the map size is shown as "0x0".
This short fix loads the map data and collects metadata about it before displaying map size.
=> Fix Map size: 0x0 in multiplayer create game menu
