src/display.cpp

Attempts to fix openmp assertion failures reported in #23131

Fix openmp

---

src/multiplayer_connect_engine.cpp
src/multiplayer_wait.cpp

These commits  could fix https://gna.org/bugs/index.php?23036 and https://gna.org/bugs/?22968
all commits are untested and made with github web interface.
The failing build is a travis problem, and this very similar build here  https://travis-ci.org/gfgtdf/wesnoth-old/builds/45240117 compiled.

Mp 1.12 fixes

---

changelog
data/core/about.cfg
players_changelog

Also add Michael Strebel to misc. contributors.

Update changelog for bug #18926 in 1.12

---

src/savegame.cpp
src/savegame.hpp

Fixes a significant inefficiency introduced to master in earlier PR #344 .

Fixup time to load saves selected from in-game menu (bug #23359)

---

src/scripting/game_lua_kernel.cpp
src/scripting/lua_types.cpp
src/scripting/lua_types.hpp
src/unit_attack_type.hpp

add getter for unit attacks info in lua.

---

src/game_config_manager.cpp
src/game_initialization/multiplayer_lobby.cpp
src/saved_game.cpp

This is an extension of PR #284.
Need testing! But I really would like to merge.

add "require_scenario" for single scenarios. track addon metadata.

---

data/tools/wmllint

I can't contribute much to the Wesnoth's C++ codebase, but I'm looking to contribute to the Python toolchain. I'll be working my way through `wmllint` first to look for improvements, but here is a simple change I noticed right off the bat.

Improve colour search in pangoize()

---

data/tools/wmlindent
data/tools/wmllint
data/tools/wmlscope

with statement is the recommended way to open/close files on Python.
Some lines of code are saved, and readability is increased.

Use with statements to open/close files on wml{indent,lint,scope}.

---

src/game_config_manager.cpp
src/global.hpp

I managed to compile wesnoth using Visual Studio 2015 Community Edition.
Minor changes are necessary though.

Added VC14 support

---

data/lua/helper.lua
src/random_new.cpp
src/random_new.hpp
src/scripting/game_lua_kernel.cpp
src/scripting/game_lua_kernel.hpp
src/synced_context.cpp
src/synced_context.hpp

This might break compbility for people that relied on helper.shuffle beeing unsynced even in synced events but i think it makes muhc more sense this way.

Add wesnoth.random and sync helper.shuffle

---

projectfiles/Xcode/Wesnoth.xcodeproj/project.pbxproj

This basically makes it possible to find a file in the project window given its path, and removes some duplicate and defunct references. Note: Although it builds and runs without issue on my machine, I'd recommend verifying that it can produce a distributable build (that will run on any machine, including wesnothd) before merging it.

Reorganize XCode project

---

src/desktop/version.cpp

With this change, the version dialog shows the current Mac OSX version instead of the Darwin kernel version. It works on 10.7 and, based on what I hear from @mattsc, will also work on 10.10.

Fetch Mac OS X version instead of Darwin version

---

changelog
src/addon/manager_ui.cpp
src/addon/state.cpp
src/addon/state.hpp

This will inform an uploaded whether the version of an addon they are attempting to upload is equal or smaller than one already published.

Addon version validation

---

data/core/about.cfg
src/desktop/windows_tray_notification.cpp
src/video.cpp

The only update I needed to make to get SDL2 compiling with VC14/2015.

SDL2 Update for Windows Tray Notification

---

changelog
src/unit.cpp
src/unit_attack_type.cpp

The changelog commit summarize it fairly well, but I'll still list them here - this allows effects to modify alignment, vision, jamming, recall cost, attack movement, attacks per turn, and advancement choices.

New possibilities for [effect]

---

src/unit.cpp

This was originally in the previous pull request but somehow got lost when applying style fixes.

Let [effect]apply_to=new_advancement add multiple AMLAs

---

src/gui/dialogs/label_settings.cpp

No further description necessary.

Fix hidden/empty sides showing in Label Settings

---

SConstruct

This speeds up troubleshooting of OGG dependencies

SConstruct: Check all SDL libs together

---

src/replay_controller.cpp

https://github.com/wesnoth/wesnoth/commit/552a6ce6191272ee55f08dc5877aab43b448da9a

backport bug #23201

---

src/attack_prediction_display.cpp
src/display.cpp
src/display_chat_manager.cpp
src/game_initialization/multiplayer.cpp
src/game_initialization/multiplayer_create.cpp
src/gui/widgets/window.cpp
src/image_modifications.cpp
src/joystick.cpp
src/marked-up_text.cpp
src/minimap.cpp
src/playmp_controller.cpp
src/sdl/rect.hpp
src/sdl/utils.cpp
src/sdl/utils.hpp
src/storyscreen/render.cpp
src/tests/test_image_modifications.cpp

Some minor changes:
* Clarity on opaqueness definition vs hard-coded 255 value.
* Avoid potentially breaking SDL changes in implicit boolean conversion.

SDL2 Minor Changes

---

src/actions/undo.cpp

https://gna.org/bugs/?23600
https://github.com/wesnoth/wesnoth/commit/5ecc629c2c3e5cd15d68e70025edeffb95fe7210

backport sighted events fix

---

src/synced_commands.cpp

ignore [allow_undo] in wml menu handlers since it casues OOS

---

data/campaigns/Northern_Rebirth/scenarios/05a_01_The_Pursuit.cfg
data/campaigns/Sceptre_of_Fire/scenarios/6_Towards_the_Caves.cfg
data/campaigns/The_Hammer_of_Thursagan/scenarios/07_Mages_and_Drakes.cfg
data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg

Yes, more spelling corrections. These ones are from http://wiki.wesnoth.org/SpellingMistakes

Spelling corrections

---

data/lua/wml/message.lua
src/game_events/action_wml.cpp
src/gui/dialogs/wml_message.cpp
src/gui/dialogs/wml_message.hpp
src/menu_events.cpp
src/scripting/lua_gui2.cpp

This is a PR instead of being pushed directly to master mainly because I expect it to break unit tests.

New syntax for [message][option]message= similar to new [campaign][difficulty]

---

data/core/macros/utils.cfg
data/lua/wml-tags.lua
data/lua/wml/object.lua

I noticed a few errors in the implementation of [for], and also reimplemented {FOREACH} and {REPEAT} to use [for] and [repeat], respectively.

Some fixes to the looping tags

---

src/hotkey/hotkey_command.cpp

Enable Load Game hot-key in main menu.
Apparently a regression from 1.10.

Resolve Bug #23215

---

changelog
players_changelog

Adding log entries for changes already in master.

Change Logs (master)

---

projectfiles/VC9/liblua.vcproj
projectfiles/VC9/schema_generator.vcproj
projectfiles/VC9/wesnoth.vcproj
projectfiles/VC9/wesnoth.vcproj.user
projectfiles/VC9/wesnothd.vcproj
projectfiles/VC9/wesnothd.vcproj.user
projectfiles/VC9/wesnothlib.vcproj

I had some trouble with MSVC and 1.12 branch. Copying these settings from master seemed to help.

MSVC Settings (1.12)

---

data/campaigns/Descent_Into_Darkness/scenarios/02_Peaceful_Valley.cfg
data/campaigns/Eastern_Invasion/scenarios/13_The_Drowned_Plains.cfg
data/campaigns/Heir_To_The_Throne/scenarios/07_Crossroads.cfg
data/campaigns/The_Rise_Of_Wesnoth/scenarios/22_The_Rise_of_Wesnoth.cfg
data/campaigns/Under_the_Burning_Suns/scenarios/12_The_Final_Confrontation.cfg
data/core/macros/terrain-utils.cfg
data/core/macros/utils.cfg
data/lua/wml-tags.lua

and use it to implement SCATTER_IMAGE, SCATTER_EMBELLISHMENTS and
SCATTER_UNITS

add tag [random_placement]

---

src/replay_controller.cpp

attempt to fix saves from replay

---

src/construct_dialog.cpp
src/display.cpp
src/events.cpp
src/events.hpp
src/generators/default_map_generator.cpp
src/help/help.cpp
src/show_dialog.cpp
src/show_dialog.hpp
src/widgets/button.cpp
src/widgets/scrollarea.cpp
src/widgets/scrollbar.cpp
src/widgets/slider.cpp
src/widgets/textbox.cpp
src/widgets/widget.cpp
src/widgets/widget.hpp

This is my merge request for fixing a lot of the window handling (such as resize, hiding/unhiding) issues and rendering order problems under SDL2.
It fixes bugs:
#23934
#24211
#24214
#24213
#24209
#19666
#23534
And attempts to fix bug:
#24212

Fix window event handling

---

src/game_initialization/multiplayer.cpp
src/game_launcher.cpp
src/game_preferences_display.cpp
src/gui/dialogs/lobby_main.cpp
src/gui/dialogs/title_screen.cpp
src/gui/widgets/window.cpp
src/hotkey/command_executor.cpp
src/preferences_display.cpp
src/preferences_display.hpp
src/video.cpp
src/video.hpp

Simple PR split off from PR #566 for @aginor to use.

Moved video related functions from preferences to CVideo

---

src/events.cpp
src/game_launcher.cpp
src/game_preferences_display.cpp
src/gui/dialogs/lobby_main.cpp
src/gui/dialogs/title_screen.cpp
src/preferences.cpp
src/preferences.hpp
src/preferences_display.cpp
src/sdl/window.cpp
src/sdl/window.hpp
src/video.cpp
src/video.hpp

This PR refactors and simplifies the handling of window states in SDL2. It also improves behavior on changing states such as fullscreen/maximized/resolution and the saving of said states between sessions.

Refactor window state handling

---

data/gui/default/widget/combobox_default.cfg
data/gui/default/window/drop_down_list.cfg
data/gui/schema.cfg
src/CMakeLists.txt
src/SConscript
src/gui/auxiliary/event/distributor.cpp
src/gui/auxiliary/widget_definition/combobox.cpp
src/gui/auxiliary/widget_definition/combobox.hpp
src/gui/auxiliary/window_builder.cpp
src/gui/auxiliary/window_builder/combobox.cpp
src/gui/auxiliary/window_builder/combobox.hpp
src/gui/dialogs/drop_down_list.cpp
src/gui/dialogs/drop_down_list.hpp
src/gui/widgets/combobox.cpp
src/gui/widgets/combobox.hpp
src/gui/widgets/grid.hpp
src/gui/widgets/image.hpp
src/gui/widgets/label.hpp
src/gui/widgets/widget.hpp
src/make_enum.hpp
src/scripting/lua_gui2.cpp
src/tests/gui/test_gui2.cpp
src/unit_filter.cpp

This adds a combobox widget which is more or less a button that shows a popup list dialog next to the button when you click on it.
scons/cmake isnt updated yet, also it still used c++11 features so that it doesnt build on travis yet. Will fix that before i merge.

comboboxes for gui2

---

data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg

Some typo fixes & minor text cleanup in Tutorial Part 2. Let me know what's usable & I'll delete/squash commits as appropriate.

Tutorial part 2 typo fixes & text changes

---

projectfiles/VC9/wesnoth.vcproj

Had some trouble compiling in VC14 - added the missing files and did the same here for VC9.

vcproj: Add missing combobox and drop_down_list files.

---

data/campaigns/An_Orcish_Incursion/scenarios/04_Valley_of_Trolls.cfg
data/campaigns/An_Orcish_Incursion/scenarios/05_Linaera_the_Quick.cfg
data/campaigns/An_Orcish_Incursion/scenarios/07_Showdown.cfg

Changes a few more occurrences than needed for standardization.
Not sure if this warrants a changelog entry.

AOI: Fix unreported bug of advisor dialog not showing in S4 & S5.

---

data/campaigns/An_Orcish_Incursion/scenarios/01_Defend_the_Forest.cfg
data/campaigns/An_Orcish_Incursion/scenarios/02_Assassins.cfg
data/campaigns/An_Orcish_Incursion/scenarios/03_Wasteland.cfg
data/campaigns/An_Orcish_Incursion/scenarios/04_Valley_of_Trolls.cfg
data/campaigns/An_Orcish_Incursion/scenarios/05_Linaera_the_Quick.cfg
data/campaigns/An_Orcish_Incursion/scenarios/06_A_Detour_through_the_Swamp.cfg
data/campaigns/An_Orcish_Incursion/scenarios/07_Showdown.cfg

Some cleanup and making Lomarfel & the rangers have a listed loyal trait to follow convention in the other novice campaigns.
Not sure if any of this warrants a changelog entry

AOI cleanup & fixes

---

data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg

So he has identical stats to his appearance in HttT S1.
If it's though better to make him an Elvish Marshal, let me know and I'll redo this.

T S2: Make Galdrad an Elvish Champion without traits.

---

data/campaigns/An_Orcish_Incursion/scenarios/01_Defend_the_Forest.cfg
data/campaigns/An_Orcish_Incursion/scenarios/07_Showdown.cfg

Revert "AOI: Make the named loyal units unnameable."

---

data/gui/default/widget/unit_preview_pane.cfg
data/gui/default/window/unit_create.cfg
data/gui/default/window/unit_recruit.cfg
projectfiles/CodeBlocks/wesnoth.cbp
src/CMakeLists.txt
src/SConscript
src/gui/auxiliary/widget_definition/unit_preview_pane.cpp
src/gui/auxiliary/widget_definition/unit_preview_pane.hpp
src/gui/auxiliary/window_builder.cpp
src/gui/auxiliary/window_builder/unit_preview_pane.cpp
src/gui/auxiliary/window_builder/unit_preview_pane.hpp
src/gui/dialogs/unit_create.cpp
src/gui/dialogs/unit_create.hpp
src/gui/dialogs/unit_recruit.cpp
src/gui/dialogs/unit_recruit.hpp
src/gui/widgets/unit_preview_pane.cpp
src/gui/widgets/unit_preview_pane.hpp
src/menu_events.cpp

This adds a dedicated GUI2 unit preview pane widget, using the same design from the Unit Create dialog.

GUI2: Unit preview pane

---

projectfiles/VC9/liblua.vcproj

VC Project Update

---

data/campaigns/Heir_To_The_Throne/scenarios/10_Gryphon_Mountain.cfg

@ln-zookeeper
Let me know if these are ok, or if other changes should be added.
When it's good, I'll add changelog entries.
Also, should gryphon behavior be changed? Should 'defeat enemy leader' be 'defeat Ashivere's forces', or is the contrast between my proposed objective change sufficient?

HttT s10 fixes

---

data/multiplayer/scenarios/2p_Aethermaw.cfg

Due to Revenant & Skeleton Archer animations moved to subdirectories.

MP - Aethermaw: Fix image not found errors.

---

utils/pywmlx/state/wml_states.py
utils/wmlxgettext

This commit contains also some changes in comments made by aquileia.

wmlxgettext: added support for _ << translatable string >> on WML

---

data/advanced_preferences.cfg
data/core/about.cfg
data/gui/window/logging.cfg
players_changelog
src/CMakeLists.txt
src/SConscript
src/gui/dialogs/logging.cpp
src/gui/dialogs/logging.hpp
src/gui/dialogs/preferences_dialog.cpp
src/log.cpp
src/log.hpp
src/tests/gui/test_gui2.cpp

I kept getting weird errors when trying to rebase the old fork (probably related to me not using the git commandline from the start)
SO I tried doing things right this time around and there's now only one commit it seems...
sorry about any confusion ^^;;
On the bright side, I think I'll be able to use the terminal git from here on out :D
Also: everything is squashed into a single not-badly-named commit :D

gui2: new logging dialog

---

data/campaigns/Legend_of_Wesmere/scenarios/chapter4/14_Human_Alliance.cfg

Equivalent to pr #526 in the master branch.
Addresses https://gna.org/bugs/?23919.

Added death of Galtrid to defeat conditions for Human Alliance.

---

changelog
src/formula/function.cpp

This adds some new useful functions to the Wesnoth Formula Language.
Finally, I know how branches work ...

Added new functions sgn(), int() and frac()

---

changelog
data/campaigns/Heir_To_The_Throne/scenarios/20a_North_Elves.cfg
data/campaigns/Heir_To_The_Throne/scenarios/20b_Underground_Channels.cfg
data/campaigns/Heir_To_The_Throne/utils/bigmap.cfg

Adds journey tracks for the Cliffs of Thoria / Underground Channels path.

Htt t journey 19c 20b

---

data/multiplayer/scenarios/Random_Scenario_Desert.cfg

MP Random map (Desert): Use new desert mountains.

---

changelog
data/core/about.cfg
players_changelog
src/game_initialization/configure_engine.cpp
src/game_initialization/configure_engine.hpp
src/game_initialization/multiplayer_configure.cpp
src/game_initialization/multiplayer_configure.hpp
src/game_initialization/multiplayer_lobby.cpp
src/game_initialization/multiplayer_lobby.hpp
src/game_preferences.cpp
src/game_preferences.hpp
src/mp_game_settings.cpp
src/mp_game_settings.hpp
src/server/game.cpp
src/server/game.hpp
src/server/server.cpp

Implemented "Make it possible to host a game which only registered players are allowed to join" from https://wiki.wesnoth.org/Easycoding

Added new checkbox to multiplayer game configure dialog to allow only registered users to join the game

---

src/display.cpp
src/game_events/action_wml.cpp
src/generators/cave_map_generator.cpp
src/halo.cpp
src/help/help_topic_generators.cpp
src/map/location.cpp
src/preferences.cpp
src/serialization/string_utils.cpp
src/terrain/builder.cpp
src/units/frame.cpp

Adds try/catch statements to most cases of std::stoi, except ones which should be safe.

Appropriately handle std::stoi exceptions

---

data/gui/window/preferences/02_hotkeys.cfg
src/generators/default_map_generator_job.cpp
src/generators/default_map_generator_job.hpp

General code cleanups for the map generator. No deep refactoring included.

Map generator code cleanups

---

changelog
data/core/help.cfg
data/core/macros/traits.cfg
src/help/help_impl.cpp
src/help/help_impl.hpp

Introduces a new key "help_text=" in [trait]

Generate trait help instead of hardcoding

---

src/scripting/plugins/context.hpp
src/theme.hpp
src/units/animation.cpp
src/units/animation.hpp
src/units/animation_component.hpp
src/units/frame.hpp
src/units/udisplay.cpp

Incorporates (and thus supercedes) PR #705

Clean up the debug output for unit animations

---

data/campaigns/Heir_To_The_Throne/scenarios/19c_Cliffs_of_Thoria.cfg

I tested this and don't see why it missed being in the PR

Missed ending /foreach -> /for

---

changelog
data/english.cfg
src/generators/default_map_generator_job.cpp

This fixes the generation of the names in the map generator

Fixed name generation in map generator

---

data/english.cfg

This makes the name generator use the features of context free grammars and adds a few more diversity (e. g. Loch for lakes and Creek for rivers).

Beautified name generation

---

data/core/macros/items.cfg

And the Lord said, "Thou hast already consumed My Holy Water, thou needest another not."
And, hearing the Word of the Lord, Posieden said, "Yo! Storm Trident! Dude, look in your hand!"

Unique items: don't be a pig

---

data/lua/wml/object.lua

I have SO got to check I pressed Save before I press Commit! This time it bit me because it got merged so quickly.

Fix the fix

---

changelog
players_changelog
src/gui/dialogs/unit_attack.cpp

I'm not sure if this is the correct use of the various weapon objects, but this is the best I could work out from what I can see of the code. Please review and merge when satisfied or let me know what needs to be corrected.

Show correct number of attacks when using swarm weapon special (bug #24978)

---

projectfiles/VC12/wesnothd.vcxproj
projectfiles/VC12/wesnothd.vcxproj.filters
src/server/server.cpp
src/server/server.hpp

I'm trying to investigate the problem that causes our multiplayer tests to hang in Travis. It would be much easier if I was able to build wesnothd locally with MSVC. Thus, I made the necessary changes to make it build.
The `room` and `room_manager` classes can't be compiled (they use nonexistent functions) and already aren't compiled in Travis according to the logs, so I just removed them.

Make wesnothd build with Visual Studio

---

data/campaigns/The_South_Guard/scenarios/01_Born_to_the_Banner.cfg
data/campaigns/The_South_Guard/scenarios/02_Proven_by_the_Sword.cfg
data/campaigns/The_South_Guard/scenarios/03_A_Desparate_Errand.cfg
data/campaigns/The_South_Guard/scenarios/04_Vale_of_Tears.cfg
data/campaigns/The_South_Guard/scenarios/05_Choice_In_The_Fog.cfg
data/campaigns/The_South_Guard/scenarios/06a_Tidings_Good_and_Ill.cfg
data/campaigns/The_South_Guard/scenarios/06b_The_Long_March.cfg
data/campaigns/The_South_Guard/scenarios/07a_Into_the_Depths.cfg
data/campaigns/The_South_Guard/scenarios/07b_Pebbles_in_the_Flood.cfg
data/campaigns/The_South_Guard/scenarios/08a_Return_to_Kerlath.cfg
data/campaigns/The_South_Guard/scenarios/08b_The_Tides_of_War.cfg
data/campaigns/The_South_Guard/scenarios/09a_Vengeance.cfg

This PR was updated 30AUG2016 to include all my work EXCEPT changes to TSG S05 conversation, objectives and victory paths.
I believe it is ready for final review and merging.
I have made a personal Issue to remind myself I do want to take a hard look at TSG S05 but the changes there are looking to take longer than I want, so I've updated this PR will all the rest.

TSG Bug fixes

---

src/playsingle_controller.cpp

Fix bug: Map may not have starting positions

---

players_changelog

Hold for merge until all PRs merge.

HttT Player changelog

---

data/lua/wml/harm_unit.lua

Missing local T.
cf https://forums.wesnoth.org/viewtopic.php?f=21&t=44567

Fix bug: Lua harm_unit

---

changelog
data/campaigns/Eastern_Invasion/utils/schedule.cfg
data/core/macros/schedules.cfg
players_changelog

This mostly makes night darker and makes dusk more red.
It also makes the summer and winter schedule have more of a use, since they now have slightly different colors.

Change colors of ToDs

---

src/log.cpp
src/server/ban.cpp

Note: this hasn't actually been tested, so extra proofreading (or even testing, if someone feels up to it) would be good.

Clarify the display of the remaining ban duration to banned users

---

src/ai/lua/core.cpp
src/lua/lauxlib.cpp
src/lua/lauxlib.h
src/lua/lgc.cpp
src/lua/llex.cpp
src/lua/lmathlib.cpp
src/scripting/lua_common.cpp
src/scripting/lua_common.hpp
src/scripting/lua_formula_bridge.cpp
src/scripting/lua_gui2.cpp
src/scripting/lua_unit.cpp
src/scripting/lua_unit_attacks.cpp

This branch cleans up some of the current integration of Lua into Wesnoth.
This work is in preparation for upgrading the Lua engine. These changes reduce the future work needed for the upgrade. Additional changes will be forthcoming. This is being put forward as a PR for inclusion in 1.13.6.

Lua integration cleanup

---

CMakeLists.txt
SConstruct

Require SDL2 2.0.4 on all target platforms.

---

data/core/macros/ai_controller.cfg

[option]message= has been deprecated, use label=
This completes deprecation of [option]message= in mainline.

Completed deprecation of [option]message=

---

data/core/macros/ai_controller.cfg

Make a copy of just the header for use in sub-menus.

AI Controller Fix bug: infinite recusion

---

data/lua/wml/message.lua
src/scripting/lua_gui2.cpp

@CelticMinstrel requests the flag not be exposed to Lua.

Adjust PR 841

---

RELEASE_NOTES
data/campaigns/Heir_To_The_Throne/scenarios/17_Scepter_of_Fire.cfg
data/campaigns/Sceptre_of_Fire/scenarios/4_Gathering_Materials.cfg
data/lua/cave_map_generator.lua
data/lua/location_set.lua
data/lua/mapgen_helper.lua
src/game_launcher.cpp
src/gui/dialogs/loadscreen.cpp

This branch contains some improvements to the Lua cave generator. I still have several things I want to add, but I'd like to get at least the first two commits into 1.13.6, which is why I've opened this PR now.

Improvements to the Lua cave map generator

---

utils/umc_dev/Makefile

Seems xtext moved their javadoc

Fix xtext javadoc path

---

src/gui/dialogs/multiplayer/mp_join_game.cpp

@Vultraz commented he didn't want the throw

Fix VC14 Warnig for unreachable code

---

CMakeLists.txt
SConstruct
changelog
src/config_cache.cpp
src/game_initialization/flg_manager.cpp
src/game_initialization/multiplayer_wait.cpp
src/gui/core/window_builder.cpp
src/gui/core/window_builder.hpp
src/gui/widgets/control.cpp
src/gui/widgets/minimap.cpp
src/gui/widgets/widget.cpp
src/gui/widgets/widget.hpp
src/help/help_topic_generators.cpp
src/sound.cpp
src/statistics_dialog.cpp
src/storyscreen/controller.cpp
src/storyscreen/render.cpp
src/units/frame.cpp

Per @Vultraz 
----
Hold for @CelticMinstrel to finish rename PR

Remove LOW_MEM

---

src/wesmage/filter.cpp

Parameter name 'filter' masked struct name 'filter'

Fix error from b6c88df9e7da58921cd00813b7d99e41352bb03f

---

data/core/units/dwarves/Steelclad.cfg
data/core/units/humans/Loyalist_General.cfg
data/core/units/humans/Loyalist_Lieutenant.cfg
data/core/units/humans/Loyalist_Sergeant.cfg
data/core/units/humans/Peasant.cfg
data/core/units/humans/Royal_Warrior.cfg
data/core/units/merfolk/Fighter.cfg
data/core/units/merfolk/Triton.cfg
data/core/units/merfolk/Warrior.cfg
data/core/units/orcs/Grunt.cfg
data/core/units/orcs/Warlord.cfg
data/core/units/orcs/Warrior.cfg
data/core/units/undead/Necro_Ancient_Lich.cfg

I'm putting these in PR form to make it easier for more people to review them.
Note: don't merge. I can merge this myself after I've pushed all the ones I intend to and they've been reviewed.
Source: https://forums.wesnoth.org/viewtopic.php?f=32&t=43721

Gyra_Solune's unit description updates

---

src/sdl/color.cpp
src/sdl/color.hpp

const-correctness

---

.appveyor.vs2013.yml
.appveyor.vs2015.yml

Use proper escapes for command line
Add to VS2015

Fix YML for AppVeyor IRC

---

data/tools/campaign2wiki.py
data/tools/expand-terrain-macros.py
data/tools/journeylifter
data/tools/rmtrans/rmtrans.py
data/tools/scoutDefault.py
data/tools/terrain2wiki.py
data/tools/trackplacer
data/tools/unit_tree/overview.py
data/tools/wesnoth/wescamp.py
data/tools/wesnoth/wmldata.py
data/tools/wesnoth/wmlparser.py
data/tools/wesnoth/wmlparser2.py
data/tools/wmlflip
data/tools/wmlvalidator
utils/ai_test/ai_test.py
utils/codelist
utils/pofix.py
utils/umc_dev/build/update_version
utils/unused_functions.py
utils/wescamp_import
utils/wiki_grabber.py

It's mostly about making the scripts run if python defaults to python3.
Has been tested for each script.
I hope this doesn't lower the motivation to port things to python 3.

Changed Shebang line of python scripts and terrain2wiki

---

src/gui/core/register_widget.hpp
src/gui/widgets/listbox.cpp
src/gui/widgets/settings.cpp
src/gui/widgets/settings.hpp
src/scripting/lua_gui2.cpp
src/scripting/lua_gui2.hpp
src/scripting/lua_kernel_base.cpp
src/scripting/lua_kernel_base.hpp

known issues:
1) the lua kenel sould unregister the definition upon descruction
2) we migth want to add a mutex somehwere to amke sure this doesnt casue issues when those widgets are added in th worder thread of the loadingscreen.

add lua add_widget_definition function

---

data/gui/widget/unit_preview_pane.cfg
src/gui/widgets/unit_preview_pane.cpp

add unit preview pane hp xp mp tooltips

---

data/campaigns/Dead_Water/scenarios/01_Invasion.cfg
data/campaigns/Descent_Into_Darkness/scenarios/08_A_Small_Favor2.cfg
data/campaigns/Eastern_Invasion/scenarios/17a_The_Duel.cfg
data/campaigns/Heir_To_The_Throne/scenarios/12_Northern_Winter.cfg
data/campaigns/The_South_Guard/scenarios/06b_The_Long_March.cfg
data/campaigns/The_South_Guard/scenarios/09a_Vengeance.cfg
data/campaigns/Under_the_Burning_Suns/scenarios_old/12_The_Final_Confrontation.cfg
data/campaigns/Under_the_Burning_Suns/utils/macros.cfg
data/lua/wml/random_placement.lua

replacing some [while] with [repeat] or [random_placement]

wml cleanups, add terrain data in [random_placement]

---

data/campaigns/Heir_To_The_Throne/scenarios/19a_Snow_Plains.cfg
data/campaigns/Heir_To_The_Throne/scenarios/19b_Swamp_Of_Dread.cfg
data/campaigns/Heir_To_The_Throne/scenarios/20b_Underground_Channels.cfg

Slight variant of speech in 19 a & b.

HttT: Add Lisar's speech about power to CoT/UC branch

---

data/campaigns/tutorial/scenarios/01_Tutorial_part_1.cfg
data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg

S1 change is intended to simply for player by eliminating option to end early in order to make it more likely the player receives all the advice given in later turns. Also matches objectives better.
S2 change adds turn limit reminder.

Tutorial improvenments

---

src/game_events/action_wml.cpp

pull request for travis check before pushing this webpage commit.

fix OOS in case that [do_command] was used on the wrong client.

---

src/actions/undo_move_action.cpp
src/replay.cpp
src/replay.hpp

fix OOS when redoing certain action with choices

---

src/gui/widgets/text_box_base.cpp

related to bug #25543 : https://gna.org/bugs/index.php?25543

Change std::string::length() to utf8::size() for unicode characters

---

data/campaigns/Legend_of_Wesmere/units/ogres/Great_Ogre.cfg

already provided by the ogres in core

changed texdomain for cleaver in legend of wesmere

---

data/lua/wml-tags.lua

Restores check_passability default of yes.
Fixes 50a9a25ae7a84da43a0bcc80287a3a9c119adc22

Fixup [unstore_unit] Lua port

---

data/campaigns/Secrets_of_the_Ancients/scenarios/08_Carcyn.cfg

To match convention in mainline.

SotA: Reorder traits so loyal is first

---

changelog
data/lua/wml-tags.lua

The question I have with this is that it will add values not present in :inspect
Should we be doing that?
Also I may want to add a changelog entry

Add more keys to store_side

---

data/core/units/humans/Loyalist_Iron_Mauler.cfg

An perfect example of the confusion about these weapon names. He has all names for it.

changed weapon name= key to flail, like it is for the shock trooper

---

data/campaigns/An_Orcish_Incursion/utils/characters.cfg

AOI: Remove unnecessary trait

---

changelog
data/lua/wml-tags.lua

Discussed on IRC on 2017-04-08

WML: Add base_income key to [store_side]

---

src/game_initialization/multiplayer.cpp

at least this should save some ram.
pr for travis check before merging.

destro mp dialog objects before starting the game.

---

data/campaigns/An_Orcish_Incursion/scenarios/05_Linaera_the_Quick.cfg
data/campaigns/An_Orcish_Incursion/scenarios/06_A_Detour_through_the_Swamp.cfg

See last two comments in https://github.com/wesnoth/wesnoth/pull/969 conversation for the rational.

AOI: Inform the player that Linaera can recruit

---

data/tools/wesnoth/campaignserver_client.py
data/tools/wesnoth/libgithub.py
data/tools/wesnoth/wescamp.py

However, there's still a problem left which didn't occur with python2:
calling wescamp -l would crash at [line 49.][link]
I's just a debug message and could be left out, but does someone have an idea why?
[link]:https://github.com/sevu/wesnoth/blob/a92eb2465c402c1f00f8bcc8ddf34eea5c19481b/data/tools/wesnoth/wescamp.py#L49
> Exception ignored in: <bound method tempdir.__del__ of <__main__.tempdir object at 0x7f72de2fcac8>>
> Traceback (most recent call last):
>   File "data/tools/wesnoth/wescamp.py", line 49, in __del__
> AttributeError: 'NoneType' object has no attribute 'debug'
>

ported wescamp and libgithub to python3

---

doc/man/wesnoth.6

Clarify the man page for options that take optional arguments (bug 1670)

---

doc/man/wesnoth.6

... and to have the --campaign... options grouped together

move --core entry in the manpage down to have it in alphabetical order

---

src/scripting/lua_audio.cpp
src/sound.cpp
src/sound.hpp

Adds lua functions to get a config of the currently playing song and of the song that played before the current song.

Add lua functions music_list.get_current() and music_list.get_previous()

---

data/gui/widget/addon_list.cfg
data/gui/window/addon_manager.cfg
data/gui/window/mp_create_game/default_resolution.cfg
data/gui/window/mp_create_game/small_resolution.cfg
data/gui/window/mp_create_game/tiny_resolution.cfg
data/gui/window/mp_staging.cfg
src/gui/widgets/settings.cpp

…window size
previously the game would always choose resolutions that were too big for the screen, in particular in the mp_create window.

make [resolution] window_width/height=, the minimum required window size

---

src/units/types.cpp
src/units/types.hpp

I wanted to write a few doc comments so I could get used to looking at the code.

Add some doc comments to src/units/types.hpp

---

data/lua/wml-flow.lua
data/test/scenarios/test_for_tag.cfg
wml_test_schedule

https://forums.wesnoth.org/viewtopic.php?t=46450 reports a Lua crash if end is given but step is not. The wiki says the default step is 1. Note that if end is negative, the [for] does nothing (per sanity check).

Bug in [for] missing step

---

projectfiles/Xcode/Wesnoth.xcodeproj/project.pbxproj

I updated Xcode project for building accelerated_rendering branch on macOS.

Updated Xcode project for macOS targets

---

projectfiles/Xcode/Wesnoth.xcodeproj/project.pbxproj

Xcode gaves me long time ago hint that these duplicates exists in project. So I removed them.

Removed duplicates inside project file.

---

projectfiles/Xcode/Wesnoth.xcodeproj/project.pbxproj

I added missing function_gamestate.*pp files inside Xcode project.

Updated Xcode project.

---

data/campaigns/Delfadors_Memoirs/scenarios/02_This_Valley_Belongs_to_Me.cfg
data/campaigns/Delfadors_Memoirs/scenarios/07_Night_in_the_Swamp.cfg
data/campaigns/Delfadors_Memoirs/scenarios/12_Terror_at_the_Ford_of_Parthyn.cfg
data/campaigns/Delfadors_Memoirs/scenarios/13_The_Return_of_Trouble.cfg
data/campaigns/Delfadors_Memoirs/scenarios/14_Shadows.cfg
data/campaigns/Delfadors_Memoirs/scenarios/19_Showdown_in_the_Northern_Swamp.cfg
data/campaigns/Delfadors_Memoirs/scenarios/20_Prince_of_Wesnoth.cfg
data/campaigns/Delfadors_Memoirs/scenarios/21_Clash_at_the_Manor.cfg

DM Minor Fixes

---

src/display.cpp

This should fix issue [#1845](https://github.com/wesnoth/wesnoth/issues/1845).

Center viewport on zoom

---

data/campaigns/An_Orcish_Incursion/_main.cfg
data/campaigns/Heir_To_The_Throne/_main.cfg
data/campaigns/The_South_Guard/_main.cfg
data/campaigns/Two_Brothers/_main.cfg

Order of AToTB, AOI, TSG, HttT
Based on discussions from IRC & https://forums.wesnoth.org/viewtopic.php?f=12&t=46102
I'm planning to add dialog about use of impact weapons in AToTB S1, & make comments about beginner campaigns more generalized in tutorial S2

Reorder beginner campaigns to be more friendly to new players

---

projectfiles/Xcode/Wesnoth.xcodeproj/project.pbxproj

I added new source files and removed old ones.
Xcode project now works

Fixed Xcode project build

---

data/core/units/merfolk/Netcaster.cfg

Fix grammar in Merman Netcaster description

---

data/campaigns/Two_Brothers/scenarios/01_Rooting_Out_a_Mage.cfg
data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg

Posting for comments on suitability, especially for tutorial change.
This goes along with beginner campaign reordering in a273a8df25f1721b0029e83d9d2b17dfb3127f11
Will merge in about a week if no objections.

New player guidance

---

src/serialization/preprocessor.cpp
src/serialization/preprocessor.hpp

Ignore the first commit (and don't view the unified diff, you won't get anything out of it). Mostly some work to make the memory management of the preprocessor saner, as requested by @jyrkive. Currently crashes on startup :(

Preprocessor cleanup

---

data/campaigns/Two_Brothers/scenarios/01_Rooting_Out_a_Mage.cfg

Suggested here: https://forums.wesnoth.org/viewtopic.php?f=40&t=10334&start=45#p586212
I'm not sure if this is correct or not, can be merged if someone else agrees with it.

AToTB S01: Grammer Fix

---

src/events.cpp
src/gui/core/event/distributor.cpp
src/gui/core/event/handler.cpp
src/gui/widgets/window.cpp
src/video.cpp

Closes
CID 1380246
CID 1380234
CID 1380159
CID 1380152
CID 1356356

Coverity Fixes - Uninitalized SDL_UserEvent timestamp field

---

data/core/about.cfg

Quite simply I find I have done enough to warrant being there instead of the long list of "Miscellaneous Contributors".

Credits: move Jyrki to the list of primary developers

---

src/gui/dialogs/unit_list.cpp

Fix Coverity Warning: dead code

---

data/core/about_i18n.cfg

This PR adding 2 additional Czech Translators into credits section.

Add new Czech translators

---

changelog
data/campaigns/Delfadors_Memoirs/scenarios/21_Clash_at_the_Manor.cfg
data/campaigns/Delfadors_Memoirs/scenarios/22_Face_of_the_Enemy.cfg
players_changelog

This improves scenario difficulty on S21 & 22, though it is still quite beatable on hard with a reasonable recall.
The last breath added for S21 works but seems unlikely to get used in normal play.
I'd like thoughts on the missing book commit as far as story goes.
I may have more, though I could get these changes for S21 & 22 in for 1.13.9

DM fixes round 2

---

src/wesnothd_connection.cpp

previously if the the server closed the connection it could happen that wesnothd_connection::receive_data threw an exception before the last package was processed which would break wesnothd redirection.

don't throw network_error if we still have incoming data queued

---

data/core/terrain.cfg

this should fix issue #1990 
I'll merge it and close that issue, if no one objects soon.

adding hide_help key to gates terrains

---

data/campaigns/The_South_Guard/utils/sg_deaths.cfg

There is a scenario, where you have Gerrick as leader, while Deoran is left behind. Perhaps dialogue could be made better, so Jarek tells something to Gerrick instead.

Fix Jarek last breath message

---

changelog
src/lua/COPYRIGHT
src/lua/lauxlib.cpp
src/lua/lauxlib.h
src/lua/lbaselib.cpp
src/lua/lcode.cpp
src/lua/ldebug.cpp
src/lua/ldo.cpp
src/lua/lgc.cpp
src/lua/liolib.cpp
src/lua/lmathlib.cpp
src/lua/loadlib.cpp
src/lua/lobject.cpp
src/lua/lobject.h
src/lua/lopcodes.h
src/lua/loslib.cpp
src/lua/lparser.cpp
src/lua/lstate.h
src/lua/lstrlib.cpp
src/lua/ltable.cpp
src/lua/ltable.h
src/lua/ltm.cpp
src/lua/lua.h
src/lua/luaconf.h
src/lua/lualib.h
src/lua/lutf8lib.cpp
src/lua/lvm.h
src/wesnoth_lua_config.md

I followed the very helpful instructions provided by @GregoryLundberg to update to Lua 5.3.4. Also applied all currently available patches for [5.3.4 bugs](https://www.lua.org/bugs.html#5.3.4) on Lua.org (the second and third bugs listed had no patches).

Updated included Lua lib from 5.3.3 to 5.3.4

---

src/addon/validation.cpp

Windows XP and later* define DOS device names for several system devices that will be handled as if they had directory entries everywhere. Their names may not be used on the left side of a file name if a dot is present, otherwise the read or write operation in progress (if applicable) is redirected to the device in question, with unexpected results (e.g. writing to `CON` writes to a console that may or may not be
attached, writing to `COM1` will send data through the first enumerated serial port, and so on).
Thus, we really don't want add-on authors to either intentionally or accidentally use them on non-Windows platforms and cause Windows-based clients to do unexpected things.
Emitting special messages for the UI in this case seems unnecessary and it'll be a waste of space most of the …

campaignd: Blacklist standard reserved DOS Device Names

---

data/campaigns/Heir_To_The_Throne/scenarios/22_Return_to_Wesnoth.cfg

Li'sar would use the nominative pronoun here, right?
Also, would Li'sar use the royal we here?  She considers herself the rightful queen.

HttT S22: Grammar fix in Li'sar's dialog

---

projectfiles/VC12/wesnoth.vcxproj
source_lists/wesnoth
src/gui/dialogs/chat_log.cpp
src/gui/dialogs/editor/generator_settings.cpp
src/gui/dialogs/multiplayer/mp_options_helper.cpp
src/gui/dialogs/preferences_dialog.cpp
src/gui/widgets/integer_selector.hpp
src/gui/widgets/slider.cpp
src/gui/widgets/slider.hpp
src/gui/widgets/slider_base.cpp
src/gui/widgets/slider_base.hpp
src/utils/math.hpp

this fixes #1539, #1641, #1656 and #1767
It also decouples the sliders class from the scrollbar class, the main reason for that is actually that there are some things about the scrollbar class that i am unsure about and i don't want to risk breaking them.
hmm ok there seems to be a off-by-one error somewhere, so this is not yet ready to be merged.

[WIP]Slider refactor

---

data/campaigns/Two_Brothers/scenarios/01_Rooting_Out_a_Mage.cfg
data/campaigns/Two_Brothers/scenarios/02_The_Chase.cfg
data/campaigns/Two_Brothers/scenarios/03_Guarded_Castle.cfg
data/campaigns/Two_Brothers/scenarios/04_Return_to_the_Village.cfg
data/campaigns/Two_Brothers/utils/macros.cfg

Uses an expanded form of the hint macro from AOI and adds hints for each objective in the campaign.
S01-04 are separate commits in case changes are needed, I'll squash them later.
I'll leave this up at least a week for comments or suggestions on the hints.

AToTB: Full Set of Hints

---

src/gui/dialogs/multiplayer/lobby.hpp

Add missing autodoc comment

---

data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg

Something I've thought would be useful to include in the Tutorial. Leaving open for a while for comments.

T S02: Add a message about the status table

---

changelog
src/scripting/lua_unit_type.cpp

Lua API: Add advances_from and advances_to to unit type getter

---

data/scenario-test.cfg
src/sdl/utils.cpp
src/sdl/utils.hpp

Refactor the blurring code to use more modern C++. Fixes a bug for blur values larger than 127 and may quiet some coverity issues.

Blur refactor

---

src/display.cpp
src/play_controller.cpp
src/play_controller.hpp
src/widgets/button.hpp

Set skip animation checkbox

---

data/campaigns/Heir_To_The_Throne/scenarios/19c_Cliffs_of_Thoria.cfg
data/campaigns/Heir_To_The_Throne/scenarios/20b_Underground_Channels.cfg

The main thing here is the adding of underground time to cave areas, and a slight reduction in Saurian strength to somewhat compensate.
Tested with min gold (200) on hard with recruits only (& no gryphons) and heroes on max level. Appears to be beatable with completing the side quest, though the player needs to know what they are doing.

HttT S20b UC touchups

---

CMakeLists.txt

Add extra_flags to cmake.

---

data/campaigns/Two_Brothers/scenarios/03_Guarded_Castle.cfg

As discussed at https://github.com/wesnoth/wesnoth/pull/2105#pullrequestreview-72671256.

AToTB: Tweak hint to not assume the AI will make mistakes

---

data/campaigns/The_South_Guard/maps/07b_Pebbles_in_the_Flood.map
data/campaigns/The_South_Guard/scenarios/03_A_Desparate_Errand.cfg
data/campaigns/The_South_Guard/scenarios/07b_Pebbles_in_the_Flood.cfg
data/campaigns/The_South_Guard/scenarios/08b_The_Tides_of_War.cfg

@ln-zookeeper Let me know if you want any of these changed/removed.

Tsg touchup

---

src/SConscript

Fix the scons Wesnoth Windows executable icon.

---

src/game_initialization/playcampaign.cpp
src/gui/dialogs/lua_interpreter.cpp
src/play_controller.hpp
src/playmp_controller.cpp
src/playmp_controller.hpp
src/playsingle_controller.cpp
src/replay.cpp
src/server/game.cpp

I encountered a number of misspelled instances of the word "receive". fix it

Spelling fix: replaced recieve with receive

---

data/campaigns/Descent_Into_Darkness/scenarios/01_Saving_Parthyn.cfg
data/campaigns/Descent_Into_Darkness/scenarios/02_Peaceful_Valley.cfg
data/campaigns/Descent_Into_Darkness/scenarios/04_Beginning_of_the_Revenge.cfg

Long ago I started a code-read and walk-through of DiD, but had to drop it due to RL.
@sigurdfdragon has been working on DiD S12 in #2188, which reminded me of these changes. Turns out, even though it has been a year, there were no merge conflicts; so I rebased and pushed, and am putting up this PR to clear the completed work off my queue.

DiD S01-S04 fixes

---

.travis.yml

Also quote some variable expansions that weren't and fix some unnecessary bashism.

Fix shell injection

---

data/campaigns/Descent_Into_Darkness/maps/12_Endless_Night.map
data/campaigns/Descent_Into_Darkness/scenarios/11_Descent_into_Darkness.cfg
data/campaigns/Descent_Into_Darkness/scenarios/12_Endless_Night.cfg

Based on irc discussion https://www.wesnoth.org/irclogs/2017/10/%23wesnoth-dev.2017-10-05.log
The objective is to prevent players from playing forever or looking up in wiki/forums to complete the campaign. And also improve dialog & feel.
Comments especially wanted on the race-specific ending dialog & Change and improve objectives commit.

DiD S12 fixes

---

src/SConscript
src/macosx/SDLMain.h
src/macosx/SDLMain.mm
src/wesnoth.cpp

This reverts commit 489eed776091b65ab3ebe0ade2e1d0405658a375.

Revert "Fix travis osx build."

---

src/gettext_boost.cpp
src/scripting/lua_unit_attacks.cpp

#1759 and a completely original one, that happens only in some addons.

Two crashes on iOS

---

src/gui/dialogs/game_save.cpp
src/tstring.cpp

Just running this through CI to see if it builds, given that comment.

Removed some unnecessary boost includes

---

src/gui/dialogs/lua_interpreter.cpp

This should fix the possibility of broken markup in the Lua console.

Fix #2281 (lua console formatting can be broken)

---

data/campaigns/Liberty/scenarios/08_Glory.cfg

He's been a silver-crowned hero until this scenario, and in
the final scenario he's still loyal with dialogue if he dies,
so make him easily visible to the player.

L S8 Give Harper a loyal overlay in Liberty's final scenario

---

src/gui/widgets/styled_widget.cpp

follow-up to this issue: https://github.com/wesnoth/wesnoth/issues/2336

document use_markup widget property

---

data/campaigns/Descent_Into_Darkness/scenarios/01_Saving_Parthyn.cfg
data/campaigns/Descent_Into_Darkness/scenarios/03_A_Haunting_in_Winter.cfg
data/campaigns/Descent_Into_Darkness/scenarios/04_Beginning_of_the_Revenge.cfg
data/campaigns/Descent_Into_Darkness/scenarios/05_Orc_War.cfg
data/campaigns/Descent_Into_Darkness/scenarios/07_A_Small_Favor.cfg
data/campaigns/Descent_Into_Darkness/scenarios/08_A_Small_Favor2.cfg
data/campaigns/Descent_Into_Darkness/scenarios/11_Descent_into_Darkness.cfg
data/campaigns/Descent_Into_Darkness/scenarios/12_Endless_Night.cfg

@ln-zookeeper 
These are all straight bugfixes, but I was slightly unsure about:
DiD S03: Slightly change gameplay to better match objectives
DiD S04: Fix dialog so it better fits with if malin_used_necromancy or not
which is why I made a pr. I'll merge in 3 days if no issues.

DiD Touchups

---

src/game_display.cpp

Fixes #2353. I copied the idiom from the position report (REPORT_GENERATOR(position)), I'm not sure if that's the best fix.

Game Display: Show correct defense modifier for unreachable terrain.

---

src/addon/client.cpp

This places the invalid characters on their own line, as per @GregoryLundberg's suggestion.
Current: https://i.imgur.com/FkKTnHQ.png
With this PR: https://i.imgur.com/v2yapfi.png

Fix formatting of invalid characters for #2043.

---

projectfiles/CodeBlocks/README.md
projectfiles/CodeBlocks/wesnoth.cbp
projectfiles/CodeBlocks/wesnothd.cbp

[dll.zip](https://github.com/wesnoth/wesnoth/files/1648822/dll.zip)
[SDL2-devel-2.0.7-mingw32.zip](https://github.com/wesnoth/wesnoth/files/1648823/SDL2-devel-2.0.7-mingw32.zip)
i post also an the dll for sart .exe compiled with mingw64(32bits) and sdl 2.0.7 in hope what Cb files will be updated

update wesnoth codeblock projectfiles

---

data/lua/backwards-compatibility.lua
data/lua/cave_map_generator.lua
data/lua/core.lua
data/lua/helper.lua
data/lua/ilua.lua
data/lua/mapgen_helper.lua
data/lua/on_event.lua
data/lua/wml-flow.lua
data/lua/wml-tags.lua
data/lua/wml-utils.lua

actual bugs found:
* core.lua (undeclared global "helper")
* wml_tags.transform_unit had wrong code to deal with recall_cost
Also, there is cave_map_generator,
which seems to have a bug with `items` and `chamber_items` variables.
I want to confirm that with other developers before including in PR.

fix code problems found by luacheck

---

data/core/units/dunefolk/Khalid.cfg

The sprite has two swords, not a shield.

Rename the Khalid's shield bash to pommel strike.

---

projectfiles/CodeBlocks/liblua.cbp
projectfiles/CodeBlocks/wesnoth.cbp
projectfiles/CodeBlocks/wesnothd.cbp

Now what tdmgcc is replced by mingw64, the project can support compile in c++14

update codeblock projectfilrs to c++14

---

data/multiplayer/eras.cfg
data/multiplayer/factions/dunefolk-aoh.cfg
data/multiplayer/factions/dunefolk-default.cfg

Other factions lack magic users, so mentioning here it is superfluous
information. Also associated with the previous identity of the faction.
Posting here for comments.

MP: Simplify Dunefolk faction and era description

---

data/tips.cfg

From oaq's post https://forums.wesnoth.org/viewtopic.php?f=3&t=47702
Kai Laudiss is Kai Krellis' dad, and the quote would be 3 years
before Dead Water.

tips: add tips that villages can be lures, and losses are necessary

---

data/campaigns/Heir_To_The_Throne/scenarios/03_The_Isle_of_Alduin.cfg
data/campaigns/Heir_To_The_Throne/scenarios/04_The_Bay_of_Pearls.cfg
data/campaigns/Heir_To_The_Throne/scenarios/11_The_Ford_of_Abez.cfg
data/campaigns/Heir_To_The_Throne/scenarios/12_Northern_Winter.cfg
data/campaigns/Heir_To_The_Throne/scenarios/15_The_Lost_General.cfg
data/campaigns/Heir_To_The_Throne/scenarios/18_A_Choice_Must_Be_Made.cfg
data/campaigns/Heir_To_The_Throne/scenarios/19c_Cliffs_of_Thoria.cfg
data/campaigns/Heir_To_The_Throne/scenarios/20a_North_Elves.cfg
data/campaigns/Heir_To_The_Throne/scenarios/21_Elven_Council.cfg
data/campaigns/Heir_To_The_Throne/scenarios/23_Test_of_the_Clans.cfg
data/campaigns/Heir_To_The_Throne/scenarios/24_Battle_for_Wesnoth.cfg
data/campaigns/Heir_To_The_Throne/units/Battle_Princess.cfg
data/campaigns/Heir_To_The_Throne/units/Princess.cfg
utils/pofix.py

The new text in Bay of Pearls is copied from elsewhere in the same scenario. Added it there in order to make Konrad's next line ("I must do this?") flow better.

English fixes to HttT

---

data/core/about.cfg

Add real name to about.cfg

---

projectfiles/Xcode/Wesnoth.xcodeproj/project.pbxproj

Downgrading Xcode project to C++11 until 1.14 release

Downgrade Xcode project back to C++11

---

data/core/about.cfg

I forgot reorder names before so I did it now

Reorder names after last PR

---

projectfiles/Xcode/Fix_Xcode_Dependencies
projectfiles/Xcode/Wesnoth.xcodeproj/project.pbxproj

Full message:
Add missing files to Xcode project and include system libraries as absolute path. Don't include system libraries into .app bundle, it is bad idea.

Add missing files to Xcode project

---

data/tools/wesnoth_addon_manager

addon_manager: allow uploading . dir

---

src/actions/advancement.cpp

disable unit advancement dialog for droided side

---

projectfiles/Xcode/Wesnoth.xcodeproj/project.pbxproj

Please wait for travis build before merging

Fixed Xcode project

---

.travis.yml
utils/travis/docker_run.sh
utils/travis/steps/install.sh
utils/travis/steps/script.sh

A few minor travis cleanups/improvements.
As far as LTO goes, it couldn't actually be enabled yet due to causing build timeouts and also the boost unit tests fail with c++14, but now the switch is there at least.

Travis improvements

---

src/game_launcher.cpp
src/gui/widgets/debug.cpp

With big help from @jyrkive and @Vultraz

Fix for DEBUG_WINDOW_LAYOUT_GRAPHS macro

---

src/actions/attack.cpp

as title says, not sure if this is good for 1.14. But i think it's a rather small and harmless change, so i'm making a pr

make [cancel_action] work in attack related events

---

data/tips.cfg

... since I saw one language translating it literally.
Any remarks to the wording?

translation hint for planning mode

---

src/help/help_browser.cpp

Add support for mouse <kbd>forward</kbd> <kbd>back</kbd> buttons in Help

Add support for mouse forward/back button in Help

---

source_lists/libwesnoth_core
src/campaign_server/campaign_server.cpp
src/hash.cpp
src/image.cpp
src/serialization/base64.cpp
src/serialization/base64.hpp
src/serialization/string_view.hpp
src/server/user_handler.cpp
src/tests/test_serialization.cpp

Centralize base64 implementation.

Base64 refactor

---

data/core/units/dunefolk/Blademaster.cfg
data/core/units/dunefolk/Burner.cfg
data/core/units/dunefolk/Explorer.cfg
data/core/units/dunefolk/Firetrooper.cfg
data/core/units/dunefolk/Harrier.cfg
data/core/units/dunefolk/Marauder.cfg
data/core/units/dunefolk/Piercer.cfg
data/core/units/dunefolk/Raider.cfg
data/core/units/dunefolk/Ranger.cfg
data/core/units/dunefolk/Rider.cfg
data/core/units/dunefolk/Rover.cfg
data/core/units/dunefolk/Scorcher.cfg
data/core/units/dunefolk/Skirmisher.cfg
data/core/units/dunefolk/Soldier.cfg
data/core/units/dunefolk/Spearguard.cfg
data/core/units/dunefolk/Spearmaster.cfg
data/core/units/dunefolk/Swordsman.cfg
data/core/units/dunefolk/Warmaster.cfg

This implements most of the proposed tweaks in [this forum thread](https://forums.wesnoth.org/viewtopic.php?f=15&t=47831). Further discussion is probably required before merging.

Attempt at implementing proposed Dunefolk balance tweaks

---

projectfiles/Xcode/Info.plist

Merge this right before 1.13.12 tag

Pre-release Xcode version bump

---

data/tools/wesnoth/campaignserver_client.py
src/addon/validation.cpp

**Do NOT merge until right before tagging RC 1.**

campaignd: Set port allocation for version 1.14

---

projectfiles/Xcode/README.md
projectfiles/Xcode/Wesnoth.xcodeproj/project.pbxproj

Theoretically this can be also merged to 1.14 branch. I don't know if it will be useful there.

Fixed campaignd Xcode target

---

projectfiles/Xcode/Fix_Xcode_Dependencies
projectfiles/Xcode/Wesnoth.xcodeproj/project.pbxproj
src/build_info.cpp
src/desktop/apple_notification.mm

On more test running now and also wait for Travis

Drop OS X 10.7 and Growl support

---

data/campaigns/Under_the_Burning_Suns/units/quenoth/Youth.cfg

Nym's sound is male now, so this commit fix it.

 UtBS: Fix Nym's hit sound to be female

---

src/CMakeLists.txt

Also put Boost_RANDOM_LIBRARY, CRYPTO_LIBRARY, and MYSQL_LIBS into server-external-libs.

Remove tools-external-libs.

---

projectfiles/Xcode/README.md

This probably could be also merged to `master`

Updated Xcode's README.md

---

data/core/about_i18n.cfg

Credits for Chinese translation of iOS announcements

---

SConstruct
scons/gl.py

Taken mostly verbatim from 3e2eba22a96cb2c6c69ee5109059b806f22a372f

Adds OpenGL/GLEW checks to scons.

---

projectfiles/Xcode/Wesnoth.xcodeproj/project.pbxproj

Once more.
It is working now 😊

Fixed Xcode Project for OpenGL

---

src/playturn.cpp
src/synced_user_choice.cpp

1.14 only, no masterport, fixes #2794

 fix gui2 dialog disappearing after [change_controller]

---

changelog.md
data/lua/wml/move_unit.lua

This is a PR because it's untested and a little complex.

Relative movement with [move_unit]

---

SConstruct
utils/travis/docker_run.sh
utils/travis/steps/install.sh
utils/travis/steps/script.sh

Travis misc2

---

CMakeLists.txt
SConstruct
utils/travis/docker_run.sh
utils/travis/steps/install.sh
utils/travis/steps/script.sh

Give optimization level separate handling for scons/cmake

---

CMakeLists.txt
SConstruct
cmake/FindGLEW.make
cmake/FindOpenGL.cmake
cmake/FindPackageHandleStandardArgs.cmake
cmake/FindPackageMessage.cmake
scons/gl.py
src/CMakeLists.txt
utils/travis/steps/install.sh

Seeing as the dependencies have been added to master's docker images.  This would also be a couple fewer things to need to do when the opengl branch is periodically rebased against master.

Add OpenGL checks to master

---

src/hotkey/command_executor.cpp

#2971 Scrolling with arrow keys can get stuck

---

data/tools/GUI.pyw

I had to read this file and still found a 1.13 reference.
Is it relevant?

Bump program version.

---

data/campaigns/Secrets_of_the_Ancients/scenarios/09_Training_Session.cfg
data/campaigns/Secrets_of_the_Ancients/scenarios/10_Merfolk_Revenge.cfg
data/campaigns/Under_the_Burning_Suns/utils/abilities.cfg
data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg
data/core/editor/time-of-day.cfg
src/game_initialization/lobby_data.cpp
src/gui/dialogs/addon/manager.cpp
src/gui/dialogs/campaign_selection.cpp
src/gui/dialogs/multiplayer/lobby.cpp
src/reports.cpp

This fixes two open issues as well as one that was not reported.

Misc internationalization fixes

---

src/gui/dialogs/multiplayer/lobby.cpp
src/gui/dialogs/multiplayer/lobby.hpp

Fix excessive mp lobby refreshing.

---

data/campaigns/tutorial/scenarios/01_Tutorial_part_1.cfg
data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg
data/core/help.cfg
data/tools/addon_manager/html.py
doc/man/wesnoth.6
utils/umc_dev/manual/dev_manual.tex

Implementing text changes suggested in #2882 and #2950.

Text Updates (1.14)

---

data/campaigns/tutorial/scenarios/01_Tutorial_part_1.cfg
data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg
data/core/help.cfg
data/tools/addon_manager/html.py
doc/man/wesnoth.6
utils/umc_dev/manual/dev_manual.tex

Implementing text changes suggested in #2882 and #2950.

Text Updates (master)

---

data/core/units.cfg

Race descriptions for falcons & wolves from:
https://forums.wesnoth.org/viewtopic.php?f=32&t=43721&p=593757#p593757
&
https://forums.wesnoth.org/viewtopic.php?f=32&t=43721&start=75#p597028
Posting for review and will merge with 1.14 & master after 1.14.0 is out.

Falcons & Wolves Race Descriptions

---

src/gettext_boost.cpp

more debug information in icompare

---

data/ai/lua/generic_recruit_engine.lua

This started because of a report of the Experimental AI not working on Dark Forecast.  The reason was that recruiting crashed when there are no enemies on the map _and_ there is no enemy recruit list.  The first commit fixes that.
Btw, that commit looks like it's a lot of changes, but it's mostly just additional indenting.  If you add `?w=1` to the URL, it will just show you the non-whitespace changes.
In the process, I also found some other problems with the Experimental AI in scenarios where the situation changes (such as Dark Forecast).  I will work on those next and add them to this PR.

Experimental AI fixes

---

data/core/units/goblins/Spearman.cfg

See: https://forums.wesnoth.org/viewtopic.php?f=32&t=48137&start=60#p628424 and related posts.

Updated goblin spearman description.

---

src/server/player.cpp
src/server/player.hpp
src/server/server.cpp
src/server/server.hpp

to tell you what wesnoth version another player is using.

add player_version mp command

---

data/ai/lua/ai_helper.lua
data/ai/micro_ais/cas/ca_goto.lua

There is probably more that can be done along these lines and I am planning to do a general clean-up of the Micro AIs later.  In the meantime, this is specifically for the Goto Micro AI (although it affects some other Lua AIs as well) in response to [this forum thread](https://forums.wesnoth.org/viewtopic.php?f=21&t=48125).  For one of the test cases from that thread, it improves the evaluation time from close to a second (on my computer) to a milli second.
I don't have time for the more comprehensive clean-up right now, but it would be good to get this into 1.14.3.

Efficiency improvements to Lua AIs

---

data/core/about.cfg

Update core/about.cfg to use "merfolk" instead of "mermen" (part of #2940)

---

data/gui/window/preferences/01_general.cfg
src/gui/dialogs/preferences_dialog.cpp

Turbo slider

---

data/test/scenarios/feeding.cfg
src/actions/attack.cpp

this fixes some rare cheats in mp.

disallow attacking with disabled attacks via [do_command]

---

data/gui/widget/toggle_button_listbox_header.cfg

The arrow direction is now "up" for ascending order and "down" for descending order.

GUI: Fix the direction of the arrow on a listbox sort column header.

---

src/gui/dialogs/unit_list.cpp
src/gui/dialogs/unit_recall.cpp
src/gui/dialogs/unit_recall.hpp

Unit List: Sort by XP as second criterion when sorting by level.

---

data/campaigns/The_Hammer_of_Thursagan/scenarios/07_Mages_and_Drakes.cfg

The narrator says "the presence of Darchas" without explaining who or what Darchas is.

THoT S7: Select Darchas so the narrator's reference to him isn't dangling.

---

src/ai/default/ca.cpp
src/scripting/game_lua_kernel.cpp

Also fixes the leader goal candidate action ignoring teleport locations

Fix custom cost functions being unable to consider teleport locations

---

data/core/about.cfg
data/gui/window/unit_recall.cfg
src/gui/dialogs/unit_recall.cpp
src/gui/dialogs/unit_recall.hpp

Rename in recall window

---

changelog.md

Fix 3339dfbf4d687a389d7f056289ac82d6374f02b8 typos

---

src/gui/core/event/handler.cpp

Ignore them until Macs have a touchscreen: https://forums.libsdl.org/viewtopic.php?p=45758

iOS interfering with Mac: Mac touchpad generates touch events too.

---

data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg
data/core/about.cfg

Simple text change addressing issue #2883.

Tutorial: provide more detail about the Status Table

---

src/menu_events.cpp

Fix a condition that was always false and add feedback (#2819).

Droid toggle and feedback

---

data/campaigns/Northern_Rebirth/scenarios/07a_Settling_Disputes.cfg
data/campaigns/Northern_Rebirth/scenarios/08a_Elvish_Princess.cfg

Fixes issue #3140, and addresses something brought up by @sevu down below.

NR S7-8: make Stalrag "healthy" for consistency, and avoid re-creating him from scratch

---

src/mouse_events.cpp

GUI: Fix check for no usable weapons.

---

packaging/wesnoth.appdata.xml

following https://standards.freedesktop.org/menu-spec/latest/apas02.html
added to provide better filtering support in software utilizing the appstream.

Add categories to appdata

---

data/campaigns/Sceptre_of_Fire/scenarios/4_Gathering_Materials.cfg

Responding to @konrad22's #3394

SoF S4: Remind the player to recruit miners before their gold runs out

---

src/gui/dialogs/addon/manager.cpp

~Everyone is not a programmer.~

Addon Manager: Don't use "ascending" and "descending" to describe how dates are sorted.

---

data/core/about.cfg
data/core/about_i18n.cfg

Just added my name and my contribution for translating. (Yes, that's more commits than I should have needed. It's messy. ._.)

Updating (my) contributions

---

data/core/team-colors.cfg

Fix for issue #3444 
Please verify that it will work this way

Fix for issue #3444

---

projectfiles/CodeBlocks/wesnoth.cbp

Update wesnoth.cbp master branch only

---

data/campaigns/Northern_Rebirth/maps/14a_Epilogue.map

Fixes #3385.
S13: https://i.imgur.com/0g2RTAL.jpg
Old S14: https://i.imgur.com/87Byp0H.jpg
New S14: https://i.imgur.com/u7H1Lh6.jpg

NR S14: Update epilogue map to match previous scenario (fixes #3385)

---

data/campaigns/Sceptre_of_Fire/scenarios/8_The_Dragon.cfg

(It's about the time he needs to smith the Sceptre.)
I literally just changed 'a few days' to 'a day or two', because 'few' implies more than two (unlike the 1.6 days he needs).
#3404

SoF- Sc8, made Thursagens words fit the timeframe better (closes #3404)

---

data/core/units/dunefolk/Burner.cfg
data/core/units/dunefolk/Firetrooper.cfg
data/core/units/dunefolk/Scorcher.cfg

Fixes #2974 as well as a TODO that I noticed in the same file.

 Make Dune Burner line naphtha icons consistent and remove outdated comment

---

data/campaigns/An_Orcish_Incursion/scenarios/03_Wasteland.cfg
data/campaigns/Heir_To_The_Throne/scenarios/20b_Underground_Channels.cfg
data/campaigns/Heir_To_The_Throne/units/Battle_Princess.cfg
data/campaigns/Liberty/scenarios/02_Civil_Disobedience.cfg
data/campaigns/Liberty/scenarios/03_A_Strategy_Of_Hope.cfg
data/campaigns/Liberty/scenarios/06_The_Grey_Woods.cfg
data/campaigns/Liberty/scenarios/09_Epilogue.cfg
data/campaigns/Liberty/units/Rogue_Mage.cfg
data/campaigns/The_Hammer_of_Thursagan/units/Dwarvish_Masked_Lord.cfg
data/campaigns/The_South_Guard/scenarios/04_Vale_of_Tears.cfg
data/core/encyclopedia/geography.cfg
data/core/units/wose/Ancient.cfg

AOI S3: Address Erlornas as "lord" in lowercase as done elsewhere in the
scenario.

Fix various typos.

---

data/campaigns/Liberty/utils/bigmap.cfg
utils/pofix.py

Add pofix entries for the recent typo fixes (#3377).

---

data/campaigns/Liberty/scenarios/03_A_Strategy_Of_Hope.cfg

Previously discussed on #3377.

Liberty S3: Play orcish war drums

---

data/campaigns/Eastern_Invasion/scenarios/02_The_Escape_Tunnel.cfg
data/campaigns/Eastern_Invasion/scenarios/08_Training_the_Ogres.cfg
data/campaigns/Eastern_Invasion/scenarios/12_Evacuation.cfg
data/campaigns/Eastern_Invasion/scenarios/13_The_Drowned_Plains.cfg
data/campaigns/Eastern_Invasion/scenarios/16_Weldyn_under_Attack.cfg
data/campaigns/Eastern_Invasion/utils/animations.cfg

It's been a while since i last played this campaign, and i really enjoyed how some scenarios have been reworked (like "Captured"). There are just a couple of things that, imo, shoud be changed.

EI: Some minor changes

---

data/campaigns/An_Orcish_Incursion/scenarios/01_Defend_the_Forest.cfg
data/campaigns/An_Orcish_Incursion/scenarios/02_Assassins.cfg
data/campaigns/An_Orcish_Incursion/scenarios/03_Wasteland.cfg
data/campaigns/An_Orcish_Incursion/scenarios/04_Valley_of_Trolls.cfg
data/campaigns/An_Orcish_Incursion/scenarios/05_Linaera_the_Quick.cfg
data/campaigns/An_Orcish_Incursion/scenarios/06_A_Detour_through_the_Swamp.cfg
data/campaigns/An_Orcish_Incursion/scenarios/07_Showdown.cfg

These scenarios' structure is not that complex, and i've found it generally correct. For this reason, i'd like to propose some syntactic changes.

AOI: Some minor changes

---

data/lua/wml/animate_unit.lua
data/lua/wml/heal_unit.lua
data/lua/wml/kill.lua
src/scripting/game_lua_kernel.cpp

I propose a way to resolve https://github.com/wesnoth/wesnoth/issues/3534#issuecomment-419709950. I hope what is best

Find a way to negate need of anim:clear() in lua files

---

src/gui/dialogs/unit_list.cpp
src/gui/dialogs/unit_recall.cpp
src/gui/widgets/unit_preview_pane.cpp
src/reports.cpp

gui2: indicate that unit cannot advance

---

src/menu_events.cpp
src/play_controller.cpp
src/play_controller.hpp

Fixes #3544.
Is this a good approach?

Reevaluate [show_if] conditions and delayed variable expansions before displaying objectives at start.

---

data/gui/window/wml_message.cfg

for @GregoryLundberg https://github.com/wesnoth/wesnoth/pull/3529#issuecomment-421167263
edit: Please label Fwdport

Right portrait for master

---

data/campaigns/Sceptre_of_Fire/maps/2t_In_the_Dwarven_City.map
data/campaigns/Sceptre_of_Fire/maps/3t_The_Council_Regathers.map
data/campaigns/Sceptre_of_Fire/maps/4t_The_Jeweler.map
data/campaigns/Sceptre_of_Fire/maps/5_Hills_of_the_Shorbear_Clan.map
data/campaigns/Sceptre_of_Fire/scenarios/1_A_Bargain_is_Struck.cfg
data/campaigns/Sceptre_of_Fire/scenarios/2_Closing_the_Gates.cfg
data/campaigns/Sceptre_of_Fire/scenarios/2t_In_the_Dwarven_City.cfg
data/campaigns/Sceptre_of_Fire/scenarios/3_Searching_for_the_Runecrafter.cfg
data/campaigns/Sceptre_of_Fire/scenarios/3t_The_Council_Regathers.cfg
data/campaigns/Sceptre_of_Fire/scenarios/4_Gathering_Materials.cfg
data/campaigns/Sceptre_of_Fire/scenarios/4t_The_Jeweler.cfg
data/campaigns/Sceptre_of_Fire/scenarios/5_Hills_of_the_Shorbear_Clan.cfg
data/campaigns/Sceptre_of_Fire/scenarios/6_Towards_the_Caves.cfg
data/campaigns/Sceptre_of_Fire/scenarios/7_Outriding_the_Outriders.cfg
data/campaigns/Sceptre_of_Fire/scenarios/8_The_Dragon.cfg
data/campaigns/Sceptre_of_Fire/scenarios/9_Caverns_of_Flame.cfg
data/campaigns/Sceptre_of_Fire/scenarios/Epilogue.cfg

Here are some possible changes for the "Sceptre of Fire".
About the commits:
Commit 3) Would close #3373 .
Commit 5) Would close #3393 .
Commit 8) Would close #3403 following stevecotton's and Konrad22's suggestion.
Commit 9) I've wrapped some parts around `__UNUSED__` because it is stated [here](https://github.com/wesnoth/wesnoth/blob/a12feb93d3ab90063b7f1c24184b888cfec56115/data/campaigns/Sceptre_of_Fire/scenarios/9_Caverns_of_Flame.cfg#L640-L642) that the user doesn't have to kill the elves anymore, and i've added some more consistent objective (some help with prose would be great :) ).
I've also removed [this line](https://github.com/wesnoth/wesnoth/commit/a12feb93d3ab90063b7f1c24184b888cfec56115#diff-9ccb7ea3f778c87dfaecbbf5df90896fL667) because it could make the player lose by …

General maintainance for SoF

---

data/lua/on_event.lua

make it safe to dofile("on_event.lua")

make it safe to dofile("on_event.lua")

---

src/menu_events.cpp
src/play_controller.cpp
src/play_controller.hpp

Fwdport b7cb36a7116d687e4bbaeae32336c0d1dd7e2e0b (#3546)
Fixes #3544.

Fwdport b7cb36a7116d687e4bbaeae32336c0d1dd7e2e0b

---

data/gui/window/mp_create_game.cfg

Requested on the forums https://forums.wesnoth.org/viewtopic.php?t=48680

MP Create Game: Increase slider step size

---

data/campaigns/Descent_Into_Darkness/scenarios/10_Alone_at_Last.cfg

Added a defeat scene for DiD S10 where there was not previously one.

[DiD] S10 time over defeat scene

---

data/campaigns/Son_Of_The_Black_Eye/scenarios/02_The_Human_Army.cfg
data/campaigns/Son_Of_The_Black_Eye/scenarios/03_Toward_Mountains_of_Haag.cfg
data/campaigns/Son_Of_The_Black_Eye/scenarios/04_The_Siege_of_Barag_Gor.cfg
data/campaigns/Son_Of_The_Black_Eye/scenarios/07_The_Desert_of_Death.cfg
data/campaigns/Son_Of_The_Black_Eye/scenarios/11_Clash_of_Armies.cfg
data/campaigns/Son_Of_The_Black_Eye/scenarios/15_Civil_War.cfg
data/campaigns/Son_Of_The_Black_Eye/scenarios/16_The_Coward.cfg
data/campaigns/Son_Of_The_Black_Eye/scenarios/18_Northern_Alliance.cfg

I had a lot of fun in playing this campaign: i've found it well balanced and really challenging. Here are a few updates to the syntax.

Maintainance for SotBE

---

data/campaigns/Sceptre_of_Fire/scenarios/7_Outriding_the_Outriders.cfg
data/core/about.cfg
data/core/about_i18n.cfg

>I'm closing this, because for now, I'll try again once I've finally have a better idea.
maybe tomorrow.
This has happened, continuation of #3591.
Prose by Konrad, WML by me.

SoF 7: explain the reinforcements

---

CMakeLists.txt
SConstruct
projectfiles/Xcode/Wesnoth.xcodeproj/project.pbxproj
src/build_info.cpp
src/hash.cpp
src/preferences/credentials.cpp
src/server/user_handler.cpp
utils/travis/steps/install.sh

#3634, #3557: Port from iOS: Compile with Apple crypto framework instead of OpenSSL

---

src/gui/dialogs/game_load.cpp
src/gui/dialogs/game_load.hpp

Game Load: The dialog shall be usable even if the auto-selected savefile is invalid.

---

data/tools/scoutDefault.py
data/tools/unit_tree/animations.py
data/tools/wesnoth/campaignserver_client.py
data/tools/wesnoth/libgithub.py
data/tools/wesnoth/wescamp.py
data/tools/wesnoth/wmldata.py
data/tools/wesnoth/wmlparser.py
data/tools/wesnoth/wmlparser3.py
utils/gdb/register_wesnoth_pretty_printers.py
utils/simulate_lobby_traffic.py
utils/wiki_grabber.py

This is a trivial change that replaces `==` operator with `is` operator, following PEP 8 guideline:
> Comparisons to singletons like None should always be done with is or is not, never the equality operators.
https://legacy.python.org/dev/peps/pep-0008/#programming-recommendations

Compare to `None` using identity `is` operator

---

data/lua/wml/modify_unit.lua

Fixes some 3c63b1e6de8ae913f7aa2c6b3d06021f29382787 issues.

fix modify_unit split_to_array function

---

src/actions/attack.cpp

i changes that for apply_to identical to weapon specials

change "under" to "self" in weapon abilities

---

data/campaigns/Descent_Into_Darkness/scenarios/01_Saving_Parthyn.cfg
data/campaigns/Descent_Into_Darkness/scenarios/07_A_Small_Favor.cfg
data/campaigns/Descent_Into_Darkness/scenarios/08_A_Small_Favor2.cfg
data/campaigns/Descent_Into_Darkness/scenarios/09_A_Small_Favor3.cfg
data/campaigns/Descent_Into_Darkness/scenarios/12_Endless_Night.cfg
data/campaigns/Descent_Into_Darkness/utils/macros.cfg

Some dialog/objective clarifications. The only gameplay change is that if you create walking corpses in A Small Favor 2, you get to carry them over to the next scenarios. I'm not sure about the new dialog in S9 but I don't have anything better right now.

DiD tweaks

---

src/gui/dialogs/title_screen.cpp

Registers hotkey in titlescreen, adds code for taking screenshot with
choosing a filename.

Fix for wesnoth#3235: screenshots in titlescreen

---

src/actions/attack.cpp
src/actions/attack.hpp
src/ai/default/aspect_attacks.cpp

this is the fix what i propose for the https://github.com/wesnoth/wesnoth/issues/3770 issue.

resolve problem of negative value for leadership

---

changelog.md

As the title says, just wrote slightly more detailed notes for the changelog regarding the TSG update.

[TSG] Update changelog for TSG revisions

---

data/campaigns/Sceptre_of_Fire/maps/6_Towards_the_Caves.map
data/campaigns/Sceptre_of_Fire/maps/8_The_Dragon.map
data/campaigns/Sceptre_of_Fire/scenarios/1_A_Bargain_is_Struck.cfg
data/campaigns/Sceptre_of_Fire/scenarios/2_Closing_the_Gates.cfg
data/campaigns/Sceptre_of_Fire/scenarios/3_Searching_for_the_Runecrafter.cfg
data/campaigns/Sceptre_of_Fire/scenarios/6_Towards_the_Caves.cfg

Added some snow for #3416. Gameplay and other things should be exactly the same as before, I only swapped out some tiles that don't affect the player at all.

[SoF] Minor bugfixes

---

data/campaigns/Sceptre_of_Fire/scenarios/5_Hills_of_the_Shorbear_Clan.cfg

Implemented the fixes suggested in #2080 as is (added a label and put in zookeeper's suggested objective text).

[SoF] Clarified objective for S5 Hills of the Shorbear Clan

---

data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg

A couple more lines of dialogue after your tutor says "You are close to killing their leader! The unit who finishes him will gain 16 xp..."

Tutorial S2: Hint that it's better to keep units about-to-level

---

changelog.md
data/core/about.cfg
data/gui/window/preferences/02_hotkeys.cfg
src/gui/dialogs/preferences_dialog.cpp
src/gui/dialogs/preferences_dialog.hpp

Add the ability to filter hotkeys by description to make it easier to find specific hotkeys

Filter hotkeys

---

data/tools/wesnoth/wmlparser3.py

I reverted wml fragment formatting currently, not sure if those may be changed.

Add string representation to wmlparser3 nodes

---

projectfiles/CodeBlocks/wesnoth.cbp

Required for pull request #3851 that was recently merged.

codeblock: link to libogg, libvorbis and libvorbisfile

---

changelog.md
data/campaigns/The_Rise_Of_Wesnoth/scenarios/15_A_New_Land.cfg
data/campaigns/The_Rise_Of_Wesnoth/scenarios/17d_Cursed_Isle.cfg
data/campaigns/The_Rise_Of_Wesnoth/scenarios/22_The_Rise_of_Wesnoth.cfg

As the title states, to address #3819.

[TRoW] Small bugfixes

---

changelog.md
data/campaigns/Dead_Water/scenarios/12_Revenge.cfg

Addresses #3399, gives the enemy some more useful reinforcements, but reduces ai gold/income to compensate. @Konrad22, would you mind playtesting this to see if you think this is of reasonable difficulty?

[DW] S12 rebalance

---

src/units/unit.cpp

Fix issue #3831: Broken unit movement animations (1.14)

---

data/tools/wesnoth/wmlparser3.py

When parsing binary data in the wmlparser3 script, a temporary file is
created and opened. The problem is that the temporary file is never
closed and in subsequent functions it is reopened.
The solution is first, create a list of temporary file paths to delete at
program’s exit. In the atexit’s registered cleaning function, all the
files in this list are deleted.
Then in the function that creates the temporary file, we simply close
the file after the binary data has been written in it.
Closes #3927

Fix parser opens tmp file 2 times then crashes

---

src/gui/dialogs/multiplayer/lobby.cpp

This fixes issue described here: #3859
I would like if somebody more skilled in C++ could check, if is this correct.

Fix issue #3859

---

data/campaigns/Descent_Into_Darkness/maps/02_Peaceful_Valley.map
data/campaigns/Descent_Into_Darkness/scenarios/02_Peaceful_Valley.cfg

As the title says, this updates the dialogue for the second scenario of DiD. Not meant to be merged into 1.14.6.

[DiD] S2 revision

---

data/campaigns/Descent_Into_Darkness/maps/03_A_Haunting_in_Winter.map
data/campaigns/Descent_Into_Darkness/scenarios/03_A_Haunting_in_Winter.cfg

An update to the dialogue for DiD S3, again not meant for 1.14.6. There is a slight gameplay change, I've made it so that you can now recruit skeletons.

[DiD] S3 Dialogue and Gameplay rewrite

---

data/tools/wesnoth/wmlparser3.py

Revert "Fix parser crash in defined multi line str test"

---

data/campaigns/Descent_Into_Darkness/units/Apprentice_Mage.cfg
data/campaigns/Descent_Into_Darkness/units/Apprentice_Necromancer.cfg
data/campaigns/Descent_Into_Darkness/units/Dark_Mage.cfg
data/campaigns/Descent_Into_Darkness/units/Frontier_Baroness.cfg

[DiD] Update unit descriptions

---

src/filesystem.cpp
src/filesystem.hpp
src/game_config_manager.cpp
src/gui/dialogs/title_screen.cpp
src/menu_events.cpp
src/picture.cpp
src/sound.cpp
src/sound.hpp

This is a pretty simple change, and is necessary in order to create localized voice tracks. Including music probably isn't strictly necessary, but music _can_ have words in it, so I figured it wouldn't hurt.

Extend the image localization system to sounds and music

---

changelog.md
data/campaigns/Northern_Rebirth/scenarios/08a_Elvish_Princess.cfg
data/campaigns/Northern_Rebirth/scenarios/09a_Introductions.cfg
data/campaigns/Northern_Rebirth/scenarios/10a_Stolen_Gold.cfg
data/campaigns/Northern_Rebirth/scenarios/11a_The_Eastern_Flank.cfg
data/campaigns/Northern_Rebirth/scenarios/12a_Get_the_Gold.cfg
data/campaigns/Northern_Rebirth/scenarios/13a_Showdown.cfg
data/campaigns/Northern_Rebirth/utils/herodeaths.cfg

This fixes #3121 and #3122 (and also makes a reasonable amount of sense story-wise).

NR: require Eryssa to survive if she joins the player

---

changelog.md
data/campaigns/Two_Brothers/scenarios/04_Return_to_the_Village.cfg

[AToTB] S4: add dialogue between Baran and Tairach

---

.travis.yml
utils/travis/docker_run.sh
utils/travis/steps/script.sh

Also streamlined test execution and simplified execution timing.

print error messages in red

---

data/ai/micro_ais/scenarios/simple_attack.cfg
data/gui/window/depcheck_select_new.cfg
packaging/systemd/wesnothd.service.in

Fix a typo in micro_ai simple_attack demo: you -> your.

---

data/core/units/goblins/Knight.cfg
data/core/units/goblins/Wolf_Rider.cfg

From the "revisiting Wesnoth unit descriptions" forum thread,
https://r.wesnoth.org/t48137 .
The Wolf Rider's new text is the collated version in
https://r.wesnoth.org/p628443
The Goblin Knight text is a new revision of my own proposal.

New description for the Goblin Knight, minor change to the Wolf Rider

---

data/campaigns/Descent_Into_Darkness/scenarios/03_A_Haunting_in_Winter.cfg
data/campaigns/Descent_Into_Darkness/scenarios/06_Return_to_Parthyn.cfg
data/campaigns/Descent_Into_Darkness/scenarios/07_A_Small_Favor.cfg
data/campaigns/Descent_Into_Darkness/scenarios/11_Descent_into_Darkness.cfg
data/campaigns/Descent_Into_Darkness/scenarios/12_Endless_Night.cfg

I missed some small things with the other PRs, so this one will address those issues.

[DiD] Patch fixes

---

data/campaigns/Under_the_Burning_Suns/scenarios/02_Across_the_Harsh_Sands.cfg
data/campaigns/Under_the_Burning_Suns/scenarios/03_Stirring_in_the_Night.cfg
data/campaigns/Under_the_Burning_Suns/scenarios/04_Descending_into_Darkness.cfg
data/campaigns/Under_the_Burning_Suns/scenarios/05_A_Subterranean_Struggle.cfg
data/campaigns/Under_the_Burning_Suns/scenarios/06a_In_the_Tunnels_of_Trolls.cfg
data/campaigns/Under_the_Burning_Suns/scenarios/06b_In_the_Domain_of_Dwarves.cfg
data/campaigns/Under_the_Burning_Suns/scenarios/07b_Talking_with_Trolls.cfg
data/campaigns/Under_the_Burning_Suns/scenarios/08_Out_of_the_Frying_Pan.cfg
data/campaigns/Under_the_Burning_Suns/scenarios/09_Blood_is_Thicker_Than_Water.cfg
data/campaigns/Under_the_Burning_Suns/scenarios/12_The_Final_Confrontation.cfg

In general, i wouldn't find refactoring code very useful, but UtBS has very long files and sometimes reading them is not that easy. What i have tried to do is mainly:
- Renaming variables, so that their aim is clearer
- Moving code from macros to custom events, since macros must be defined before they are used. Custom events can be written in "chronological" order
- Updating code (`filter_condition` instead of if-then, `repeat` instead of `while` ...)
There aren't any variations in what the code does: this refactor doesn't affect the "result" of the code, but just how it is achieved.

UtBS: code refactor

---

changelog.md
data/campaigns/Dead_Water/scenarios/03_Wolf_Coast.cfg
data/campaigns/The_Rise_Of_Wesnoth/_main.cfg
data/campaigns/The_Rise_Of_Wesnoth/scenarios/02_The_Fall.cfg
data/campaigns/The_Rise_Of_Wesnoth/scenarios/03_A_Harrowing_Escape.cfg
data/campaigns/The_Rise_Of_Wesnoth/scenarios/04b_The_Midlands.cfg
data/campaigns/The_Rise_Of_Wesnoth/scenarios/07_Return_to_Oldwood.cfg
data/campaigns/The_Rise_Of_Wesnoth/scenarios/19_The_Vanguard.cfg
data/campaigns/The_Rise_Of_Wesnoth/scenarios/20_Return_of_the_Fleet.cfg

Prose updates for orcs eating other sapient races

---

data/tips.cfg

The "User Scenarios" label changed to "Custom Scenarios" in ae6ed8e71.

tips: Clarify that these are about the editor, fix quotes

---

data/tools/wesnoth/wmliterator3.py
data/tools/wmllint

Cherry-pick of 1.14's #4089 to 1.15, will close #4085 .

[1.15] wmllint: Handle nested events and other filters in the death check

---

src/menu_events.cpp
src/play_controller.hpp
src/playsingle_controller.hpp
src/replay_controller.cpp
src/replay_controller.hpp

Make it possible to use the "unit description" command in replay mode on fogged/shrouded units.

---

src/game_initialization/connect_engine.cpp
src/preferences/game.cpp
src/preferences/game.hpp
src/server/game.hpp
src/server/server.cpp

On game creation, use the name ban list to pre-ban usernames on the host's ignore list.

---

data/core/macros/movetypes.cfg
data/core/units.cfg

Command line --preprocess doesn't process macros in data/core/units.cfg.
Fixes #4152.

Command line --preprocess missing some macros. 

---

src/display.cpp

@Vultraz , please would you review this?

Fix units fading in or out affecting other units of the same type

---

data/campaigns/Delfadors_Memoirs/scenarios/21_Clash_at_the_Manor.cfg
data/campaigns/Delfadors_Memoirs/scenarios/22_Face_of_the_Enemy.cfg
data/campaigns/Delfadors_Memoirs/utils/misc.cfg

DM S22: Apply the weapon-change from S21 to S22 too

---

src/units/unit.cpp

this is another solution for resolve https://github.com/wesnoth/wesnoth/issues/4248 bug without regression of https://github.com/wesnoth/wesnoth/commit/66a282a96be288a284d12a71625868cee5b2dc6b#diff-8dd74f653e8c20d19565e37121f74e9fR1018

resolveHttT, Konrad's portrait is not used after he is lvl 2

---

src/server/forum_user_handler.cpp

Print an error message when the mp_mod_group is not a valid int.

---

po/wesnoth-ai/sk.po
po/wesnoth-anl/bg.po
po/wesnoth-editor/af.po
po/wesnoth-editor/cs.po
po/wesnoth-editor/el.po
po/wesnoth-editor/lt.po
po/wesnoth-httt/af.po
po/wesnoth-httt/it.po
po/wesnoth-l/ru.po
po/wesnoth-lib/en_GB.po
po/wesnoth-lib/it.po
po/wesnoth-nr/ga.po
po/wesnoth-nr/lt.po
po/wesnoth-tutorial/hr.po
po/wesnoth-tutorial/sv.po
po/wesnoth-units/en_GB.po
po/wesnoth-utbs/en_GB.po
po/wesnoth/af.po
po/wesnoth/cs.po
po/wesnoth/et.po
po/wesnoth/lt.po
po/wesnoth/nl.po
po/wesnoth/pl.po
po/wesnoth/sv.po

Remove description prefixes from translated strings (master)

---

data/campaigns/Heir_To_The_Throne/scenarios/19b_Swamp_Of_Dread.cfg

https://github.com/wesnoth/wesnoth/issues/4262

remove bonus objective once it's completed

---

data/campaigns/Heir_To_The_Throne/scenarios/19c_Cliffs_of_Thoria.cfg

objective update #4254

---

changelog.md
data/ai/micro_ais/scenarios/recruiting.cfg
data/ai/micro_ais/scenarios/wolves.cfg
data/campaigns/An_Orcish_Incursion/scenarios/01_Defend_the_Forest.cfg
data/campaigns/Descent_Into_Darkness/scenarios/02_Peaceful_Valley.cfg
data/campaigns/Eastern_Invasion/scenarios/11_Captured.cfg
data/campaigns/Legend_of_Wesmere/scenarios/chapter1/03_Kalian_under_Attack.cfg
data/campaigns/Legend_of_Wesmere/scenarios/chapter2/07_Elves_Last_Stand.cfg
data/campaigns/Legend_of_Wesmere/utils/map-utils.cfg
data/campaigns/Liberty/scenarios/08_Glory.cfg
data/campaigns/Secrets_of_the_Ancients/scenarios/04_Becalmed.cfg
data/campaigns/Secrets_of_the_Ancients/scenarios/06_Following_the_Shadow.cfg
data/campaigns/Secrets_of_the_Ancients/scenarios/08_Carcyn.cfg
data/campaigns/Secrets_of_the_Ancients/scenarios/10_Merfolk_Revenge.cfg
data/campaigns/Under_the_Burning_Suns/scenarios/06a_In_the_Tunnels_of_Trolls.cfg
data/core/macros/scenario-utils.cfg
data/core/macros/side-utils.cfg
data/schema/game_config.cfg
data/test/scenarios/store_locations.cfg
src/game_events/conditional_wml.cpp
src/map/location.cpp
src/serialization/string_utils.cpp
wml_test_schedule

Allow '1-infinity' in ranges

---

src/server/server.cpp
src/server/server.hpp

This command is of the form `/query stopgame <nick>`.  wesnothd then retrieves the id of the game that person is in and calls delete_game(<id>).

Add a MP mod command to stop a game.

---

SConstruct

See 7437b3992e3de4467bd76659b684285442d578d9

backport SConstruct have_fortify change

---

src/playsingle_controller.cpp
src/playturn.cpp
src/server/server.cpp
src/server/server.hpp

So now: `/query stopgame <nick> [<reason>]`. The reason is displayed to the players of the game on the savegame prompt dialog.

Add optional reason when using the stopgame command.

---

data/gui/window/lobby_player_info.cfg
src/gui/dialogs/multiplayer/player_info.cpp
src/gui/dialogs/multiplayer/player_info.hpp

This adds a button along side the kick/kickban/ban buttons to stop the game the selected user is in.
Fixes #3635

Add UI button to stop a game.

---

src/gettext_boost.cpp

Restore localised load dialogue (1.14)

---

src/gettext.cpp

Restore localised load dialogue (master)

---

src/addon/validation.cpp
src/attack_prediction.cpp
src/desktop/dbus_features.cpp
src/display.cpp
src/display.hpp
src/game_initialization/configure_engine.hpp
src/game_initialization/lobby_data.cpp
src/game_launcher.hpp
src/gui/dialogs/unit_list.cpp
src/hotkey/hotkey_item.hpp
src/map_command_handler.hpp
src/playturn_network_adapter.cpp
src/playturn_network_adapter.hpp
src/scripting/lua_fileops.cpp
src/tests/gui/test_gui2.cpp

Opening a PR to check the CI builds on all platforms, but not expecting any problems.

Clean up some Cppcheck warnings by passing args as const refs

---

data/lua/core.lua

See commit messages for details.
Fixes #4079 
Test case: start the test scenario, click on the petrified Elvish Avenger, and see whether the "petrified" icon appears in the sidebar.

Lua wesnoth.deprecate_api bug when deprecating tables with metatables

---

src/gui/dialogs/game_stats.cpp
src/reports.cpp
src/team.cpp
src/team.hpp

Add color names to the Status Table, sidebar and top bar

---

data/core/about.cfg

* add @Earth-Cake
* add my nickname (octalot)
* correct the number in @newfrenchy83's name
Earth-Cake and newfrenchy, are these both as you want them?

Update credits: add Earth-Cake, update octalot, newfrenchy83

---

src/scripting/lua_unit.cpp
src/scripting/lua_unit.hpp

Makes it easier to test SUFs with wesnoth.get_units{} in the lua console.

lua: Add __tostring to units

---

src/gui/dialogs/multiplayer/mp_staging.cpp

Resolves #2954
If acceptable, can go to 1.14 branch too.

Display translated string for "random" in MP staging

---

data/campaigns/Dead_Water/units/Brawler.cfg
data/campaigns/Under_the_Burning_Suns/utils/abilities.cfg

now what special is deprecated it must replace in master for resolve https://github.com/wesnoth/wesnoth/issues/3915

Upgrade special=* uses in master

---

data/schema/core/config.cfg
data/schema/units/modifications.cfg

Fix schema rejecting top-level color range/palette tags

---

src/gui/dialogs/multiplayer/mp_create_game.cpp

Also remove redundant disablement of registered_users_ option.
Resolves #1122

Disable game name for local MP

---

data/campaigns/The_Rise_Of_Wesnoth/scenarios/19_The_Vanguard.cfg
data/campaigns/The_Rise_Of_Wesnoth/scenarios/20_Return_of_the_Fleet.cfg

Fixes https://github.com/wesnoth/wesnoth/issues/4518

Changed Draug portrait in The Rise of Wesnoth

---

data/core/units/dwarves/Lord.cfg
data/core/units/dwarves/Sentinel.cfg
data/core/units/dwarves/Steelclad.cfg

Based on Krogen's argument here: http://forums.wesnoth.org/viewtopic.php?f=15&p=648448&sid=f2e07511b458d64bdb1b650c47a70651#p648335. I actually feel like there needs to be a slight HP nerf as well, but that might end up being overkill.

Nerf Dwarvish Steelclad and Lord

---

data/campaigns/Descent_Into_Darkness/_main.cfg
data/campaigns/Descent_Into_Darkness/scenarios/03_A_Haunting_in_Winter.cfg
data/campaigns/Descent_Into_Darkness/scenarios/06_Return_to_Parthyn.cfg
data/campaigns/Descent_Into_Darkness/scenarios/11_Descent_into_Darkness.cfg
data/campaigns/Descent_Into_Darkness/scenarios/12_Endless_Night.cfg
data/campaigns/Descent_Into_Darkness/units/Apprentice_Necromancer.cfg
data/campaigns/Descent_Into_Darkness/units/Dark_Mage.cfg
data/campaigns/Descent_Into_Darkness/units/Ghast.cfg
data/campaigns/Descent_Into_Darkness/units/Ghoul.cfg
data/campaigns/Descent_Into_Darkness/units/Mal_Keshar.cfg
data/campaigns/Descent_Into_Darkness/units/Malin_Keshar.cfg
data/campaigns/Descent_Into_Darkness/units/Necrophage.cfg
data/campaigns/Descent_Into_Darkness/units/Spectral_Servant.cfg
data/campaigns/Descent_Into_Darkness/utils/abilities.cfg
data/campaigns/Descent_Into_Darkness/utils/amlas.cfg
data/campaigns/Descent_Into_Darkness/utils/characters.cfg
data/campaigns/Descent_Into_Darkness/utils/macros.cfg

Like the title says. Not quite done yet, but planning to finish by 1.15.3.

[DiD]: add AMLAs to Mal Keshar and special units

---

data/campaigns/tutorial/scenarios/01_Tutorial_part_1.cfg
data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg
data/schema/core/addons.cfg
src/game_classification.cpp

The title screen's "tutorial" button will use the tag name from game_classification,
as would anything else that calls game_launcher::set_tutorial().

Replace the [tutorial] tag with [scenario]

---

data/gui/window/tooltip_floating.cfg

Committing on behalf of @Landiss
Resolves #3274

Move tool-tips to below-right

---

src/help/help_impl.cpp
src/reports.cpp

Also remove the string-freeze hacks.
Resolves #3064

Add Time of Day Bonuses to Help (1.14)

---

src/help/help_impl.cpp
src/reports.cpp

Also mark 'Time of Day Schedule' and bonus strings for translation, to synchronise with what 1.14 branch has.
Resolves #3064

Add Time of Day Bonuses to Help (master)

---

src/gui/dialogs/title_screen.cpp

Everything else is optional, so the UX can be changed simply by removing
buttons and the tips widget from the title_screen.cfg file.

Make "Quit" the only mandatory widget on the title screen

---

data/core/units.cfg
data/core/units/dunefolk/Alchemist.cfg
data/core/units/dunefolk/Apothecary.cfg
data/core/units/dunefolk/Burner.cfg
data/core/units/dunefolk/Captain.cfg
data/core/units/dunefolk/Explorer.cfg
data/core/units/dunefolk/Herbalist.cfg
data/core/units/dunefolk/Raider.cfg
data/core/units/dunefolk/Scorcher.cfg
data/core/units/dunefolk/Spearguard.cfg
data/core/units/dunefolk/Strider.cfg
data/core/units/dunefolk/Sunderer.cfg
data/core/units/dunefolk/Swiftrider.cfg
data/core/units/dunefolk/Swordsman.cfg
data/core/units/nagas/Bladewhirler.cfg
data/core/units/nagas/Ringcaster.cfg

List of changes:
Level 1
Burner - Ranged damage increased from 6 to 7, melee damage decreased from 7 to 6.
Soldier line cold resistance increades from -10 to 0.
Herbalist hp increased from 29 do 32.
Level 2
Cost of Dune Explorer changed from 35 to 29.
Cost of Dune Swordsman changed from 38 to 30.
Cost of Dune Captain changed from 38 to 30, hp changed form 45 to 48.
Cost of Dune Spearguard changed from 38 to 30.
Cost of Dune Scorcher changed from 35 to 21.
Cost of Dune Raider changed from 36 to 35, (very unusual unit)
Cost of Dune Swiftrider changed from 36 to 38.
Cost of Dune Sunderer changed from 36 to 38, hp changed form 58 to 55.
Cost of Dune Apothecary changed from 33 to 26, hp changed from 39 to 43.
Cost of Dune Alchemist changed from 33 to 26.
Cost of Dune Strider changed from 33 to …

Dunefolk balance update. 

---

changelog.md
data/gui/window/unit_recall.cfg
src/actions/create.cpp
src/gui/dialogs/unit_recall.cpp
src/gui/dialogs/unit_recruit.cpp
src/gui/dialogs/unit_recruit.hpp
src/menu_events.cpp
src/menu_events.hpp
src/units/unit.hpp

Attempts to resolve #4469 for @jostephd. Looking at the two original PRs, it makes sense to me to keep them together.

Backport #4362 and #4444

---

data/campaigns/tutorial/_main.cfg
data/gui/window/title_screen.cfg

As discussed in #4543. Tagging @stevecotton for comments.

Tutorial: move from title screen to campaign menu

---

data/tools/wmllint

Noticed from https://lgtm.com/projects/g/wesnoth/wesnoth/

Fix "wmllint: no translatables" magic comment

---

data/campaigns/Liberty/scenarios/02_Civil_Disobedience.cfg

Fix a bug regarding enemy leader leaving starting position and going with his soldiers.

Liberty S2 - bug fix

---

data/lua/core.lua

I posted this on https://github.com/wesnoth/wesnoth/issues/4584#issuecomment-560029352 but posting again as a PR for ease of tracking. Testing instructions are on that comment too, I haven't done any testing yet.

lua: Simplify the __index and __newindex wrappers in wesnoth.deprecate_api

---

data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg
data/campaigns/tutorial/utils/utils.cfg

Tutorial - remove repeating help messages

---

data/campaigns/tutorial/maps/02_Tutorial_part_2.map
data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg

Some players have commented on the tutorial S2 being too hard. This PR aims to make it easier by redoing the map.

Tutorial S2 map overhaul

---

data/campaigns/Heir_To_The_Throne/_main.cfg

Inspired by this: http://forums.wesnoth.org/viewtopic.php?f=32&t=49357

HttT - Change sprites in difficulty-choosing screen from Elves' to Konrad's sprites

---

data/tips.cfg

Miscellaneous fixes and additions to tips.cfg

---

data/campaigns/Heir_To_The_Throne/scenarios/16_Hasty_Alliance.cfg

Closes [#4498 ](url=https://github.com/wesnoth/wesnoth/issues/4498).

HttT - Fix Li'sar not being loyal in S17

---

data/campaigns/Under_the_Burning_Suns/utils/abilities.cfg

now what changes in abilities used like specials are merged, i can propose that for simpplify WEAPON_SPECIAL_DAZE_EVENTS code

weapon_special_daze_event with abilities

---

data/multiplayer/factions/khalifate-aoh.cfg
data/multiplayer/factions/khalifate-default.cfg
data/tips.cfg
data/tools/wmllint
utils/travis/schema_validation.sh

Remove references to WoV in tips and remove unnecessary Khalifate files

---

.travis.yml
packaging/windows/Wesnoth.nsi.in
packaging/windows/translations.nsh
utils/dockerbuilds/travis/Dockerfile-base-mingw
utils/travis/docker_run.sh
utils/travis/sftp
utils/travis/steps/install.sh
utils/travis/steps/script.sh

This PR will upload a windows installer to https://sourceforge.net/projects/bfw-travis-upload/files/ along with the wesnoth and wesnothd executables that get uploaded with each commit.

Create Windows installer on tag commits

---

data/campaigns/Liberty/scenarios/04_Unlawful_Orders.cfg
data/campaigns/Liberty/scenarios/06_The_Hunters.cfg

Scenario 4:
- prevented the enemy lieutenant from premature suiciding
Scenario 6:
- fixed a few typos; minor dialogue adjustments

Minor adjustments and typo fixes for Liberty scenarios 4 and 6

---

.travis.yml
utils/travis/docker_run.sh
utils/travis/steps/install.sh
utils/travis/steps/script.sh

Rename OPT -> CFG.
Rename LTS -> IMAGE.
Reorder travis jobs.

Make debug builds instead of -O0 builds.

---

.gitignore

I'm reluctant to touch a file like this one, but this would make life a little bit simpler.

gitignore data/**/layered_WIP_files

---

utils/travis/mp_test_executor.sh

Probably could be written more succinctly, but should work.

Fix the occasional mp unit tests travis failure.

---

data/campaigns/Son_Of_The_Black_Eye/maps/03_Toward_Mountains_of_Haag.map
data/campaigns/Son_Of_The_Black_Eye/maps/05_To_the_Harbor_of_Tirigaz.map
data/campaigns/Son_Of_The_Black_Eye/scenarios/14_Back_Home.cfg

Adding troll camps to S3 and S14, and undead camp to S5.
This is further progress on #4121 
Note: S14 was recently changed but my fork is not up to date. I think I've done this commit right but it's possible that I've goofed it.

SoTBE: New terrains

---

src/chat_command_handler.hpp

Add help text for the ping command

---

data/core/units/dunefolk/Wyvern_Rider.cfg
data/core/units/monsters/Elder_Falcon.cfg
data/core/units/monsters/Falcon.cfg
data/core/units/monsters/Roc.cfg
data/core/units/monsters/Wild_Wyvern.cfg

Changes:
Falcon, Elder falcon, Roc - changed charge attack into "blade - claws" and normal attack into "pierce - beak" 
Reason - birds do not attack while descending from skies with their beak. They use claws for that because if thier beak gets broken they can eat anymore.
Wild Wyvern and Wyvern Rider - overhaul of statistics. 
Roc - Decreased hp from 56 to 44, charge attack damage from 12 to 10 and cost from 45 to 36. This unit was just looking too strong for me on level 2. No as strong as Jinni looks but I decided to not touch him for now because I dont have clear vision for this unit. 
Next thing that I would like to talk about are descriptions that are missing for Wild Wyvern, Wyvern Rider and Roc. During times of dunefolk rework I created some lore for Wyverns and Rocs thus I want to …

Wyverns and other units

---

data/core/encyclopedia/_main.cfg
data/core/encyclopedia/calendar.cfg

For #4822, I may look at adding a small tidbit about each month later.

Add Calendar to Wesnoth encyclopedia

---

data/campaigns/Son_Of_The_Black_Eye/scenarios/15_Civil_War.cfg

SotBE S15: Check if Kapou'e is at 1,18 when killing last boss

---

src/units/abilities.cpp
src/units/attack_type.hpp

the use to special_active in attack_type::list_ability permit me to remove the static functions and to simplify the engine.

simplify code for ability used like weapon

---

src/build_info.cpp
src/video.cpp
src/video.hpp

As requested by Pentarctagon in #4911.

Add current video settings to the game_config::full_build_report.

---

src/scripting/game_lua_kernel.cpp
src/scripting/game_lua_kernel.hpp
src/side_filter.cpp

Im not 100% sure whether its better to pass a side object or the number...
anyways will merge myself, mostly created this pr for the travis check.

add lua_function in side filters

---

data/core/terrain-graphics.cfg

fixes #4923 
@Earth-Cake or anyone willing to test- if you don't want to bother with testing a PR, it's easy enough to modify the `core/terrain-graphics.cfg` file manually and test.

core - terrain - dwarf castle and tall encampment keep transition fixes

---

data/core/about.cfg

Noticed that I was added into the credits for some PRs from a few years back; just going and updating the entry with my name. 😄

Update @iKevinY's credits entry

---

src/build_info.cpp
src/sound.cpp
src/sound.hpp

Also refactored the display driver formatting code since SDL enumerates audio drivers in the exact same format.

bi: Add sound configuration to the clipboard report

---

src/game_initialization/mp_game_utils.cpp

This adds the additional attributes under the multiplayer information sent to wesnothd:
* mp_scenario_addon_id
* mp_scenario_addon_version (host's version)
* mp_era_addon_id
* mp_era_addon_version (host's version)
* active_mod_addon_ids
* active_mod_versions (host's versions)
---
This doesn't contain the part to actually insert the data, since I don't want to create a conflict with #4884.

Send scenario/era/modification source add-ons and addon versions to wesnothd.

---

src/server/forum_user_handler.cpp
src/server/forum_user_handler.hpp
src/server/sample_user_handler.cpp
src/server/sample_user_handler.hpp
src/server/server.cpp
src/server/user_handler.hpp
utils/mp-server/table_definitions.sql

* mp_scenario_addon_id
* mp_scenario_addon_version (host's version)
* mp_era_addon_id
* mp_era_addon_version (host's version)
* active_mod_addon_ids
* active_mod_versions (host's versions)

Store additional information in the database:

---

src/game_initialization/mp_game_utils.cpp
src/server/mysql_prepared_statement.ipp
src/server/server.cpp

Tested locally:
* Starting a game with and without mods using 1.14.13 (Steam release).
* Starting a game with and without mods using 1.14.13+dev.
* Loading a saved game in MP.

Various fixes

---

src/gui/core/canvas.cpp

I am openning this PR as I am not C++ expert.
I got SDL assertion failure with recent `master` branch and I found that this exactly same was discussed and solved there: http://forums.wesnoth.org/viewtopic.php?t=52296&start=15
My solution is based on this commit: https://github.com/wesnoth/wesnoth/commit/3545a3e48dec31abb651fd0b6ba4fb7052da5941
I want to ask someone to review my fix before accepting. Thank you

Fix SDL assertion failed

---

src/tests/gui/iterator.cpp
src/tests/test_formula_function.cpp
src/tests/test_unit_map.cpp

Make sure to reset the logging level to the default in tests that change the logging level.

---

changelog.md
data/core/units.cfg
data/core/units/drakes/Armageddon.cfg
data/core/units/drakes/Burner.cfg
data/core/units/drakes/Fire.cfg
data/core/units/drakes/Flameheart.cfg
data/core/units/drakes/Flare.cfg
data/core/units/drakes/Inferno.cfg
data/core/units/dwarves/Steelclad.cfg
data/core/units/elves/Shaman.cfg
data/core/units/humans/Woodsman_Poacher.cfg
data/core/units/merfolk/Hunter.cfg
data/core/units/trolls/Rocklobber.cfg
data/core/units/undead/Spirit_Ghost.cfg

Changes:
Burner line cold resistance changed from -50% to -40%.
Heavy Infantryman cold resistance changed from -10% to 0.
Dwarvish Steelclad hp changed from 55 to 57.
Poacher hp changed from 32 to 33. 
Troll Rocklobber hp changed from 49 to 51.
Merman Hunter hp changed from 30 to 33.
Wose cold resistance changed from 10% to 0.
Shaman ranged damage changed from 3 to 4.
Ghost cost changed from 20 to 19.

New balance update

---

SConstruct
projectfiles/Xcode/The Battle for Wesnoth.xcodeproj/project.pbxproj
src/desktop/apple_video.hpp
src/desktop/apple_video.mm
src/video.cpp

As always, I want to ask somebody for code review. I am not C++ master but I tried my best.
Also I have to note that this code is probably correct but I cannot tell it for 100%. As always, `it works for me`.
Also wait for travis CI builds before merging.
Fixes #5019

Fix SDL2 2.0.12 change in SDL_GetDisplayDPI

---

src/actions/advancement.cpp
src/actions/attack.cpp
src/actions/attack.hpp
src/ai/formula/callable_objects.cpp
src/ai/formula/function_table.cpp
src/display_context.cpp
src/display_context.hpp
src/gui/dialogs/attack_predictions.cpp
src/gui/dialogs/attack_predictions.hpp
src/gui/dialogs/unit_attack.cpp
src/reports.cpp
src/scripting/game_lua_kernel.cpp
src/units/abilities.cpp
src/units/animation.cpp
src/units/animation.hpp
src/units/animation_component.cpp
src/units/map.hpp
src/units/ptr.hpp
src/units/udisplay.cpp
src/units/udisplay.hpp
src/units/unit.cpp
src/units/unit.hpp
src/utils/shared_reference.hpp

This make the code a bit simpler, furthermore it
allows us to use weak_ptr to untsi shodul we ever
need that.

use shared_ptr for unit_ptr

---

projectfiles/VC16/campaignd.vcxproj
projectfiles/VC16/files_with_deactivated_warnings.txt
projectfiles/VC16/wesnothd.vcxproj
src/utils/shared_reference.hpp

I'm relying on Travis to check whether the VC16 fix is correct,
as I don't have a Windows install to test this locally. However,
I think having it building and running the unit tests would be
better than having the CI builds fail.

Fix the build, separate fixes for VC16 and GCC-10

---

data/core/help.cfg

This is part of resolving #4280.

Help dealing with losses: don't link to the forums

---

src/gui/dialogs/multiplayer/lobby.cpp
src/gui/dialogs/multiplayer/lobby.hpp

Resend the announcements and server info text when rejoining the lobby.

---

utils/travis/docker_run.sh
utils/travis/sftp
utils/travis/steps/script.sh

Also limit sftp to taking at most 5 minutes.

Compress linux and windows debug information before uploading.

---

projectfiles/VC16/wesnoth.vcxproj
source_lists/wesnoth

The VC project files are easy to hand-edit, just need Travis to check that this fixes the VC build. The Xcode build still needs to wait for @Hejnewar, it needs magic numbers for each file.
In source_lists/wesnoth, put the new files in alphabetical order.

Update the VC16 project files for Lua Widgets

---

data/campaigns/Descent_Into_Darkness/utils/abilities.cfg

simplify DID_SHADOW_VEIL_HANDLER  in DiD and implement an did_shadow_veil_helper active in radius 5 of shadow_veil ability

update DID_SHADOW_VEIL_HANDLER in DID campaign

---

src/menu_events.cpp

Fixes #5144 "one missing unit in recruit list makes entire recruit list
unavailable". The player will see an error dialog every time they try to
recruit, that seems good given that the limited recruitment options are likely
to severely affect game balance.
The `std::vector<t_string> unknown_units` uses t_string instead of std::string
because that's the class needed for format_conjunct_list. Those items aren't
translated - they're the values of [unit_type]id=, but the corresponding
[unit_type] is missing, so we can't get the translatable [unit_type]name=.

Allow the player to recruit, even when some recruitable units aren't known

---

changelog.md
data/core/units/dunefolk/Wyvern_Rider.cfg
data/core/units/gryphons/Gryphon.cfg
data/core/units/monsters/Cuttle_Fish.cfg
data/core/units/monsters/Fire_Guardian.cfg
data/core/units/monsters/Giant_Mudcrawler.cfg
data/core/units/monsters/Giant_Rat.cfg
data/core/units/monsters/Giant_Scorpion.cfg
data/core/units/monsters/Giant_Scorpling.cfg
data/core/units/monsters/Sea_Serpent.cfg
data/core/units/monsters/Water_Serpent.cfg
data/core/units/monsters/Wild_Wyvern.cfg
data/core/units/monsters/Wolf.cfg
data/core/units/monsters/Wolf_Dire.cfg
data/core/units/monsters/Wolf_Great.cfg
data/core/units/undead/Skele_Chocobone.cfg

Solving #5058.
Changelog:
Cost of Gigant Rat changed from 6 to 5.
Cost of Gigant Scorpling changed from 13 to 12.
Cost of Fire Guardian changed from 16 to 11.
Cost of Gigant Mudcrawler changed from 11.
Cost of Gigant Scorpion changed from 22 to 16.
Cost of Wolf changed from 17 to 15.
Cost of Chocobone changed from 38 to 28.
Cost of Cuttle Fish changed from 40 to 36.
Cost of Great Wolf changed from 30 to 21.
Cost of Gryphon changed from 40 to 29.
Cost of Water Serpent changed from 26 to 23.
Cost of Direwolf changed from 36 to 33.
Cost of Sea Serpent changed from 40 to 55.
Cost of Wyvern changed from 54 to 75.
Cost of Wyvern Rider changed from 80 to 102.

Changes in prices of monster units and Chocobone.

---

data/core/units/monsters/Ant.cfg
data/core/units/monsters/Bear.cfg
data/core/units/monsters/Crocodile.cfg
data/core/units/monsters/Fire-Ant.cfg
data/core/units/monsters/Giant_Stoat.cfg
data/core/units/monsters/Icemonax.cfg
data/core/units/monsters/Icemonax_Greater.cfg
data/core/units/monsters/Tusker_Gorer.cfg
data/core/units/monsters/Tusker_Tusklet.cfg

These changes are supposed to make new units look natural (and balanced). For example Icemonax should have cold resistance and Gorer (Level 1 unit) shouldn't deal 26-2 damage even if with charge.

Changes in new units.

---

data/gui/window/mp_create_game.cfg
data/gui/window/mp_create_game/default_resolution.cfg
data/gui/window/mp_create_game/small_resolution.cfg
data/gui/window/mp_create_game/tiny_resolution.cfg
src/addon/manager.cpp
src/game_initialization/configure_engine.cpp
src/game_initialization/configure_engine.hpp
src/game_initialization/lobby_data.cpp
src/game_initialization/lobby_data.hpp
src/game_initialization/multiplayer.cpp
src/gui/dialogs/multiplayer/mp_create_game.cpp
src/gui/dialogs/multiplayer/mp_create_game.hpp
src/mp_game_settings.cpp
src/mp_game_settings.hpp
src/preferences/game.cpp
src/preferences/game.hpp
src/server/wesnothd/game.cpp
src/server/wesnothd/game.hpp
src/server/wesnothd/server.cpp
src/tests/gui/test_gui2.cpp

Closes #4980. As @Pentarctagon suggested. Opening a PR to confirm removing that bit from wesnothd is ok.

Removed Registered Users Only game config option (resolves #4980)

---

.github/labeler.yml

Added support for the `Add-ons` tag to the pull-request labeler.
The file changes in the following directories will be marked as related to the addons system:
- src/server/campaignd/**
- src/addon/**
- src/gui/dialogs/addon/**

Add the 'Add-ons' tag to the pull-request labeler.

---

src/deprecation.cpp
src/font/pango/stream_ops.hpp
src/formatter.hpp
src/game_config_manager.cpp
src/game_events/pump.cpp
src/gui/core/event/distributor.cpp
src/gui/core/event/distributor.hpp
src/gui/core/log.hpp
src/log.cpp
src/log.hpp
src/server/campaignd/addon_utils.cpp

The draft #5176 included a wish for thread-safe logging, which I think would be a good idea in general, so I tried implementing the thing I was describing in that thread.
This works in the most basic sense, which is to say it compiles on my computer with no errors. I have not yet done any testing whatsoever, not even just running the game to see if logging even slightly works. Thus, the draft status of this PR.

Thread-safe logging

---

src/addon/client.cpp
src/addon/info.cpp

I have no idea what code style statement past me was trying to make
here anymore.

Clean up excessive use of this pointers in add-ons client

---

data/schema/core/actionwml.cfg
data/schema/core/addons.cfg
data/schema/schema.cfg
data/schema/units/specials.cfg
src/serialization/schema_validator.cpp
src/serialization/schema_validator.hpp
utils/travis/schema_validation.sh

The commit descriptions should mostly be self-explanatory; I'm only opening this as a pull request because it adds something to the Travis task. This can be merged as soon as Travis passes (assuming of course that it _does_ pass).

Some schema fixes

---

data/lua/wml-tags.lua
data/schema/core/actionwml.cfg
data/test/scenarios/store_unit_defense.cfg
wml_test_schedule

See https://r.wesnoth.org/t53448

Fix [store_unit_defense] and add a unit test for it

---

data/campaigns/Legend_of_Wesmere/scenarios/chapter2/07_Elves_Last_Stand.cfg

Change dialogue to address the bug reported in https://r.wesnoth.org/t53438
I'm expecting this to need some changes, but it seemed sense to start with a PR instead of an issue.

LoW S07: Revise the dialogue, as the dwarves don't turn up until the end

---

data/campaigns/Two_Brothers/_main.cfg

'Knight' to 'Grand Knight' so it matches the sprite used.

AToTB: Changing a difficulty name

---

src/gui/dialogs/multiplayer/lobby.cpp
src/gui/dialogs/multiplayer/lobby.hpp

https://github.com/wesnoth/wesnoth/issues/4685
Judging from the discussion in the issue, I guess we want this functionality? If we do, the fix seems pretty simple

Add help hotkey to mp lobby (fixes #4685)

---

data/core/units.cfg
data/core/units/dunefolk/Rider.cfg
data/core/units/dunefolk/Scorcher.cfg
data/core/units/elves/Rider.cfg
data/core/units/humans/Loyalist_Dragoon.cfg

Dune Rider xp changed from 42 to 47.
Sunderer line dodge on hills changed form 60% to 50%.
Scorcher gold cost changed from 23 to 25.
Dragoon gold cost changed from 27 to 28.
Elvish Rider gold cost changed form 32 to 28.
There is no changelog entry in this PR in order to avoid merge conflicts.

Balance update

---

data/campaigns/Secrets_of_the_Ancients/scenarios/10_Merfolk_Revenge.cfg

@sevu, I was wondering if the de version of the line should be "Wart ihr noch nie angeln?". It sounds okay to me with "du", but I'm not a native speaker.

SotA S10: Add some translation hints

---

data/campaigns/Secrets_of_the_Ancients/scenarios/04_Becalmed.cfg

These texts are only in the master branch, no need to backport to 1.14.

SotA S04: Run wmllint, which fixed some double-spaces in strings

---

src/chat_command_handler.hpp
src/chat_events.cpp
src/server/wesnothd/server.cpp
src/server/wesnothd/server.hpp

Adds '/roll N' command which gets a random number between 1 and N and prints it as "$username rolled a dice [1 - $N] and got a $value." to the game creation lobby chat or just to the sender otherwise (so not to flood the main server chat and ensure a sense of privacy).
Closes #5221 .

Add '/roll N' command to games and game lobbies.

---

data/core/macros/scenario-utils.cfg

this is a fix of https://github.com/wesnoth/wesnoth/issues/5346 issue

pass documentation outside some macro for fix bugs in loading scenarios

---

data/campaigns/Northern_Rebirth/scenarios/01_Breaking_the_Chains.cfg
data/campaigns/Northern_Rebirth/scenarios/02_01_Infested_Caves.cfg

dialogue when turns runs out NR S1 and S2

---

data/campaigns/Heir_To_The_Throne/scenarios/07_Crossroads.cfg
data/core/macros/items.cfg

fix https://github.com/wesnoth/wesnoth/issues/5383

ambusher don't workin httt 07_Crosroad.cfg

---

data/core/terrain-graphics.cfg
data/core/terrain-graphics/new-macros.cfg

A better fix than dd322ccbf4f31545b2ff567565a274d629b49a0e

terrain-graphics - iron fence fix

---

data/core/editor/help.cfg

Somehow I forgot to test that it worked on 1.14.

Correct the editor help about loading editor-generated .cfg files

---

src/units/abilities.cpp

fix attacker and defender formula pointed both' self'. Fix https://github.com/wesnoth/wesnoth/issues/5414 issue.

fix WFL variables aren't getting assigned correctly 

---

data/tools/README.md

Currently README does not document the purpose of wmllint-1.4

Add a note about wmllint-1.4

---

data/campaigns/Descent_Into_Darkness/utils/abilities.cfg

There is nothing that needs translating here

Silence warnings about a missing translation mark

---

changelog.md
src/lua/COPYRIGHT
src/lua/lapi.cpp
src/lua/lauxlib.cpp
src/lua/lcode.cpp
src/lua/ldebug.cpp
src/lua/liolib.cpp
src/lua/llex.cpp
src/lua/lobject.cpp
src/lua/lparser.cpp
src/lua/lua.h
src/lua/luaconf.h
src/lua/lundump.cpp
src/wesnoth_lua_config.md

Resolves #5452. There were no official patches to apply.

Upgrade to Lua 5.3.6

---

data/campaigns/The_South_Guard/units/Horseman_Commander.cfg
data/campaigns/The_South_Guard/units/Junior_Commander.cfg
data/campaigns/The_South_Guard/units/Mounted_General.cfg

Three units with movement_type=mounted were missing {NOTE_DEFENSE_CAP}

TSG: Add missing NOTE_DEFENSE_CAP

---

data/core/macros/abilities.cfg
data/core/units/dunefolk/Cataphract.cfg
data/lua/diversion.lua

fixes #5445 and #5454, partial fix for #5446

various small fixes

---

.github/workflows/ci-main.yml
.github/workflows/ci-scripts/docker.sh
utils/dockerbuilds/travis/Dockerfile-base-1604-1.14
utils/travis/check_utf8.sh

Cmake only since scons fails with an encoding error on Ubuntu 16.04.

Add NLS CI job.

---

data/campaigns/Descent_Into_Darkness/utils/team-colors.cfg
data/core/team-colors.cfg

Move [color_range] id=darkblue to core

---

data/core/editor/help.cfg

change User to Custom to unify the help with the game

---

data/campaigns/Legend_of_Wesmere/scenarios/chapter3/10_Cliffs_of_Thoria.cfg

So, to be honest, I wanted to edit a lot more scenarios in Legend of Wesmere when I played thru it, but the fact that it's also playable in multiplayer kind of scared me off. I did manage to edit one scenario in it, though: Cliffs of Thoria. It's a pretty simple edit, just tweaking some turns/gold/income/aggression values.

Legend of Wesmere: update Cliffs of Thoria difficulty

---

data/campaigns/Northern_Rebirth/scenarios/13a_Showdown.cfg

Fixes #5396
was: Player -> 5x AI -> Player -> AI -> Player
now: Player -> 6x AI -> 2x Player

NR S13: make all player sides have turns in sequence

---

data/core/macros/animation-utils.cfg
data/core/units/dunefolk/Cataphract.cfg
data/core/units/dunefolk/Horse_Archer.cfg
data/core/units/dunefolk/Marauder.cfg
data/core/units/dunefolk/Raider.cfg
data/core/units/dunefolk/Rider.cfg
data/core/units/dunefolk/Sunderer.cfg
data/core/units/dunefolk/Windbolt.cfg

fixes #5412
Also adds mounted undead variation to dunefolk

various small sprite-related fixes

---

data/core/_main.cfg
data/lua/as_text.lua
data/modifications.cfg
data/modifications/pick_advance/README.md
data/modifications/pick_advance/dialog.lua
data/modifications/pick_advance/main.lua
data/test/scenarios/as_text.cfg
src/actions/advancement.cpp
src/play_controller.cpp
src/units/helper.cpp
wml_test_schedule

The two commits explain their own reasoning.  Beyond that, the remaining question would be whether an advancement planning mod would:
* be a mainlining of the existing Plan Unit Advance modification; or
* be something brand new
The first option also of course depends on whether @vgaming is fine with their modification being mainlined or not.

Change mainline advancement modification

---

src/server/campaignd/server.cpp

This cleans up the awkwardness I introduced in 5de1f8d5ccda92e6e02df84146e85fd84d8fb241 and 78373d7c59e4876c27a6b14ae7ea2b308815eb24.

Campaignd: cleaned up error reporting slightly

---

projectfiles/CodeBlocks/campaignd.cbp
projectfiles/CodeBlocks/liblua.cbp
projectfiles/CodeBlocks/tests.cbp
projectfiles/CodeBlocks/wesnoth.cbp
projectfiles/CodeBlocks/wesnothd.cbp

c++20  is under construct, i willl revert to c++17 in wait

revert c++20 to c++17 in codeblock projectfiles

---

src/tstring.cpp
src/tstring.hpp
utils/msvc/wesnoth.natvis

This should greatly improve the experience of debugging Wesnoth code in MSVC. It also works in VSCode if you configure it to run MSBuild, as I have done.
The natvis file added in this commit needs to be added as a reference in the Visual Studio project file in order to work in Visual Studio (according to the documentation). Since I don't have Visual Studio and don't know what the MSBuild code would look like to add this, I've left it to someone else who does.

Add a Wesnoth MSVC visualization file for config and t_string

---

data/campaigns/Under_the_Burning_Suns/units/quenoth/Archer.cfg
data/campaigns/Under_the_Burning_Suns/units/quenoth/Marksman.cfg
data/campaigns/Under_the_Burning_Suns/units/quenoth/Outrider.cfg
data/campaigns/Under_the_Burning_Suns/units/quenoth/Pathfinder.cfg
data/campaigns/Under_the_Burning_Suns/units/quenoth/Scout.cfg
data/campaigns/Under_the_Burning_Suns/units/quenoth/Tauroch_Flagbearer.cfg
data/campaigns/Under_the_Burning_Suns/units/quenoth/Tauroch_Protector.cfg
data/campaigns/Under_the_Burning_Suns/units/quenoth/Tauroch_Rider.cfg
data/campaigns/Under_the_Burning_Suns/units/quenoth/Tauroch_Stalwart.cfg
data/campaigns/Under_the_Burning_Suns/units/quenoth/Tauroch_Vanguard.cfg

This is pretty simple, but I always figure out a way to fail the CI tests, so let's park it here first.
(Revisiting the Quenoth elves made me realize the archers could use a touch-up, so they look less like Kenny from South Park.)
Fixes #5529

UtBS - undead variations for the rider/mounted Quenoths

---

data/ai/lua/ai_helper.lua
data/ai/lua/extCAexample.lua
data/ai/lua/generic_recruit_engine.lua
data/ai/micro_ais/cas/ca_fast_combat_leader.lua
data/ai/micro_ais/cas/ca_hunter.lua
data/ai/micro_ais/cas/ca_recruit_random.lua
data/ai/micro_ais/cas/ca_wolves_move.lua
data/ai/micro_ais/cas/ca_wolves_multipacks_functions.lua
data/campaigns/Legend_of_Wesmere/lua/wml_tags.lua
data/campaigns/World_Conquest/lua/campaign/enemy.lua
data/campaigns/World_Conquest/lua/campaign/enemy_themed.lua
data/campaigns/World_Conquest/lua/era/era.lua
data/campaigns/World_Conquest/lua/game_mechanics/invest/invest_show_dialog.lua
data/campaigns/World_Conquest/lua/game_mechanics/training.lua
data/campaigns/World_Conquest/lua/game_mechanics/unittypedata.lua
data/campaigns/World_Conquest/lua/map/postgeneration/2C_Glaciers.lua
data/campaigns/World_Conquest/lua/map/postgeneration/2E_Paradise.lua
data/lua/core/gui.lua
data/lua/core/interface.lua
data/lua/core/map.lua
data/lua/core/persistent_tags.lua
data/lua/location_set.lua
data/lua/wml/move_unit.lua
host.lua

Submitting as a PR because this touches a lot of AI code and I'm not 100% confident all these globals were indeed unintentional.
There's some typos and stuff fixed in here too.

Fix several Lua issues, mostly unintentional globals

---

data/ai/lua/ai_helper.lua
data/ai/micro_ais/cas/ca_messenger_attack.lua
data/ai/micro_ais/cas/ca_messenger_escort_move.lua
data/ai/micro_ais/cas/ca_messenger_move.lua
data/ai/micro_ais/mai-defs/escort.lua

This is complete as far as I am concerned, I just want to give a couple days for people to comment and for @Hejnewar to test.  I see no reason why this should not go into 1.15.6.

Messenger Micro AI: add [avoid] tag functionality

---

src/server/wesnothd/server.cpp
src/server/wesnothd/server.hpp

The version when wesnothd is compiled may not match the client versions it serves when switching to a new stable branch, so that value must come from the server config. This also means that the value must be updated manually to match the intended version.

Add the server id to wesnothd as well.

---

SConstruct
cmake/SearchForStuff.cmake
config.h.cmake

---
Opening a PR to make sure the CI completes before merging.

Remove checks for stuff that aren't used anymore.

---

data/core/units/dunefolk/Alchemist.cfg

singular: brother; plural: brethren; plural possessive: brethren’s
granted: it is possible that this word is an exception. I'm not an expert

Fix a typo

---

data/multiplayer/scenarios/2p_Dark_Forecast.lua

"cauculate" does not seem to be any existing word and auto-corrects to "calculate" which seems more appropriate here.

Dark Forecast Lua file comment Typo fix

---

projectfiles/Xcode/The Battle for Wesnoth.xcodeproj/project.pbxproj
src/serialization/string_utils.hpp
src/tests/test_serialization.cpp

I want to modify these functions to take a string instead of a character as the separator, so these tests are intended to ensure they still work after the changes. This PR is just here for CI purposes; I'm not requesting a review on it. However, I'm still open to reviews if someone wants to take a look.

Unit tests for the various split functions

---

data/test/scenarios/event_handlers_in_events.cfg
data/test/scenarios/events-test_autovariables.cfg
data/test/scenarios/events-test_filters.cfg
wml_test_schedule

This just exists to ensure CI passes, but if anyone wants to comment on the new tests, feel free.

More unit tests for events

---

data/test/scenarios/event_handlers_in_events.cfg
data/test/scenarios/events-test_autovariables.cfg
data/test/scenarios/events-test_filters.cfg

Opening a PR just for the CI check, going to merge when it passes

Fixup 7cbc6c9d5d and 5bb0576e17

---

projectfiles/VC16/wesnoth.vcxproj
projectfiles/VC16/wesnoth.vcxproj.filters
projectfiles/Xcode/The Battle for Wesnoth.xcodeproj/project.pbxproj
src/gui/dialogs/multiplayer/mp_join_game.cpp
src/units/udisplay.cpp
src/utils/guard_value.hpp
src/utils/scope_exit.hpp

This is for future use, especially in #5663 - since it wasn't directly related to events, I extracted it to a separate PR.
I'll merge this in a day or two unless there are any comments (for example, maybe someone has a better name than `guard_value`?).

Scope exit utilities

---

data/campaigns/Under_the_Burning_Suns/utils/garak-abilities.cfg

UtBS: Use $amount instead of %d in the teaching ability

---

data/multiplayer/eras.lua

This should probably be changed into a table of GUI2 widgets, but this commit
is an improvement on what was here before. It removes the broken conjunct list
formatting for 3-way ties. However, it also means that there are 5 lines per
language to translate again.
Fixes #4274.

Multiplayer turns over dialog: stop using %d and %s in translatable strings

---

data/campaigns/World_Conquest/changelog.txt
data/campaigns/World_Conquest/lua/game_mechanics/effects.lua
data/campaigns/World_Conquest/lua/map/postgeneration/6D_Feudal.lua
data/campaigns/World_Conquest/lua/map/postgeneration_utils/engine.lua
data/campaigns/World_Conquest/lua/map/postgeneration_utils/events.lua
data/campaigns/World_Conquest/lua/map/postgeneration_utils/noise.lua

The Summary of this PR:
1. Fixed an un-added entry in the changelog
2. fixed the last 2 deprecation messages
3. removed instances of `wml.parsed` as it is no longer required.
Fixes #5650
Note: In regards to the last remaining error report, I want to open a fresh issue for it. So the existing one can be closed.
How do I request a review from CelticMinstrel and Soliton?

[World Conquest] Last 2 deprecation code usage fixes.

---

data/campaigns/Heir_To_The_Throne/units/Battle_Princess.cfg
data/campaigns/Heir_To_The_Throne/units/Princess.cfg
data/core/macros/deprecated-utils.cfg

I have forget to pull this in variation scpeter of unit_type

Fix teaching_anim not implmmented in variation_id=sceptre of Httt Princess and Battle Princess

---

changelog.md
data/schema/filters/unit.cfg
data/test/scenarios/ability_id_active_test.cfg
data/test/scenarios/swarm_disables_upgrades_with_abilities.cfg
data/test/scenarios/swarm_disables_upgrades_with_abilities_adjacent.cfg
data/test/scenarios/swarm_disables_upgrades_with_abilities_adjacent_fail.cfg
data/test/scenarios/swarm_disables_upgrades_with_abilities_adjacent_leadership.cfg
data/test/scenarios/swarm_disables_upgrades_with_abilities_adjacent_leadership_fail.cfg
data/test/scenarios/swarm_disables_upgrades_with_abilities_fail.cfg
src/units/filter.cpp
wml_test_schedule

until now, only the tpe of ability could be filtered with activity, and id only for unit who have ability, same if she's inactive.

add 'ability_id_active' attribute to filter

---

data/ai/lua/ai_helper.lua
data/ai/lua/generic_recruit_engine.lua
data/lua/core/map.lua
data/lua/wml/move_unit.lua

Remove remaining uses of wesnoth.special_locations and fix deprecation message.

Remove remaining uses of wesnoth.special_locations and fix deprecation message

---

data/core/about.cfg
data/core/about_i18n.cfg

* Move myself to the programming section
* Add Sean Yeh to the misc section
* Finish 287ec15c101b's update of Astrid's credits
[ci skip]
@Pentarctagon, I'm asking for a review because I'm moving myself upwards.

Credits: move myself to Programming, add Sean Yeh, update Astrid

---

projectfiles/CodeBlocks/campaignd.cbp
projectfiles/CodeBlocks/tests.cbp
projectfiles/CodeBlocks/wesnoth.cbp
projectfiles/CodeBlocks/wesnothd.cbp
src/scripting/lua_mathx.cpp

When i compile this file with gcc called with codeblock editor i have line 59: 'std::round is not a member of std'

update codeblock projectfiles andfix lua_mathx not compiled with gcc 8.0 on windows7(in codeblock project)

---

src/tls_root_store.cpp

---
Tested by @singalen and confirmed he could connect to the TLS-enabled 1.15 add-ons server now with this code.

See about adding macOS TLS system cert loading.

---

data/campaigns/Two_Brothers/scenarios/02_The_Chase.cfg

Also change a line from the elves, so that it changes from sympathy to defense
instead of a sudden swing from sympathy to aggression.
@Earth-Cake, @Konrad22, @Lordlewis6 and @nemaara: this is a follow-up to #5255. I'm assuming that AToTB won't be replaced with a rewritten version in time for 1.16, so want to improve up the existing dialogue.

AToTB S02: The necromancer is leaving, not waiting for reinforcements

---

data/schema/ai/goal.cfg

@doofus-01 Try pulling this and see if that fixes your validation issue. Pushing it to your PR would be fine if you're unable to validate locally.

Schema: Add lua_goal support

---

CMakeLists.txt
SConstruct

---
Just letting the CI complete to make sure none of the configuration options broke.

Combine profile build into release build.

---

src/ai/lua/core.cpp

It's kind of hard to explain but basically the code was doing something like this:
```lua
if ai then
return ai
else
return wesnoth.debug_ai(side)
end
```
And `wesnoth.debug_ai(side)` is definitely not the same thing as `ai`.

Fix bug in AI state loading that could cause an error when the AI is initialized from a saved game

---

data/core/units/monsters/Frost_Stoat.cfg
data/core/units/monsters/Horse.cfg
data/core/units/monsters/Horse_Great.cfg
data/core/units/monsters/Jinn.cfg

Last minute description fixes/additions.  I'm getting a bit out of my lane, but I was involved in some of this stuff, so this is an attempt to fix a few unit descriptions before the beta freeze.
- correction to Frost Stoat description (fixes #5853 )
- Jinn needs some minimal description
- Dustbok needs some minimal description
- Horses need some minimal description

1.16 Unit descriptions

---

data/campaigns/Under_the_Burning_Suns/units/quenoth/Dustbok.cfg

[UtBS] dustbok description for 1.16

---

data/multiplayer/scenarios/2p_Isle_of_Mists.cfg

Yeah, while reading the .pot file, I noticed these did not show up and saw this.

[IoM] [1.16 branch] fixed non-existent textdomain in scenario file

---

data/multiplayer/scenarios/2p_Isle_of_Mists.cfg

Same as #5887 but for master branch.

[IoM] [master] fixed non-existent textdomain in scenario file

---

data/lua/core/sides.lua

PR to run the CI before merging.

Fix whitespace from 16157e286bce
