wesnoth/wesnoth

- src/serialization/preprocessor.cpp
Several of the deprecated macros have two or three lines of explanation, but
only the last one was printed. This change fixes a cppcheck warning that the
value of deprecation_detail was overwritten without being used.
For example:
#define SOUND:POISON
#deprecated 3 1.15 This was used to play a sound when poisoning a unit, it had to
#deprecated 3 1.15 be placed inside an attack animation. Now this sound is played
#deprecated 3 1.15 automatically, there is no other use for this macro.
#enddef
Ended up printing:
20191229 21:39:36 error deprecation: SOUND:POISON has been deprecated and will be removed in version 1.15.0.
automatically, there is no other use for this macro.
> Fix multi-line deprecation messages

- data/campaigns/tutorial/scenarios/01_Tutorial_part_1.cfg
- data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg
- data/campaigns/tutorial/utils/utils.cfg
- Removal of unnecessary events, adding another PRINT messages event, changing coordinates in one message, if hero has attacked Dumbo provide another dialogue, and change highlighted village on turn 6 if player still hasn't captured it in S2
- Adding a macro and add [cancel_action] tag in utils.cfg
> Tutorial - minor improvements

- src/sdl/surface.hpp
(Found while investigating issue #4510.)
Unlike what the constructor's documentation says, passing a null `SDL_Rect*` does have unexpected consequences. First, one of the first two arguments to `SDL_IntersectRect` will be a null pointer, which results in `SDL_IntersectRect` returning SDL_FALSE without ever touching the output `SDL_Rect`:
```c
SDL_bool
SDL_IntersectRect(const SDL_Rect * A, const SDL_Rect * B, SDL_Rect * result)
{
int Amin, Amax, Bmin, Bmax;
if (!A) {
SDL_InvalidParamError("A");
return SDL_FALSE;
}
if (!B) {
SDL_InvalidParamError("B");
return SDL_FALSE;
}
```
In this context that means that next `SDL_SetClipRect` will receive a pointer to a fresh `SDL_Rect` full of uninitialized values and all kinds of weirdness could ensue next depending on the phase of the moon. …
> sdl: Prevent undefined behaviour in clip_rect_setter

- src/display.cpp
- src/help/help_text_area.cpp
With the introduction of batched rendering in SDL 2.0.10, the behaviour of the render API appears to have changed so that certain operations forcibly queue a renderer clip rectangle set operation, using a default rectangle if necessary. The command queue does not clean after itself since it appears that the operating assumption is that you either use the renderer API or you don't, and Wesnoth performs drawing operations both with and without it in a few places.
With commit 4cbd6529e3d5f378d4dd0080dda8a47025b0d50d, our drawing primitives were changed ("refactored") so that the render API is forcibly used by them. When combined with contexts that use the `clip_rect_setter` object, things get weird since the clipping rectangle is reset behind the code's back.
As I see it, there's two …
> Do not use SDL render API for certain drawing operations

- changelog.md
- src/filesystem_common.cpp
This replaces the previous behaviour of using `<pwd>/translations`, which could break on certain edge cases (e.g. if Wesnoth is launched from the command line from a different dir).
> i18n: Use <game dir>/translations on Windows

- data/campaigns/Eastern_Invasion/scenarios/11_Captured.cfg
Add an enter_hex event for moving into the throne room, and modify the "attack"
event so that the undisguised units can trigger it too. For reviewing, note that
the diff shows these as if the existing "attack" was changed to a "enter_hex",
but in fact it's the existing `[filter_wml]` moving from "attack" to "enter_hex".
Add L2 Trolls to various lists, as they're used on easy/normal difficulties.
The main bug fixed here is #4674 "When a guard sees one of the two units not
disguised as an orc, it chases after the unit, but no other enemies are
alerted. This allows a player to pick off each enemy unit individually, then
release the prisoners."
> EI S11: Trigger the guards if an undisguised unit moves into the throne room

- utils/gdb/register_wesnoth_pretty_printers.py
- utils/gdb/wesnoth_gdb.py
- utils/gdb/wesnoth_pretty_printers.py
Updates to the utility that adds support for showing Wesnoth's `config` class in the Gnu C++ debugger.
Two commits doing two separate tasks:
* Support GDB linked with Python3; has the side-effect of dropping support for GDB linked with Python2.
* Support `config.hpp` from b6e398fdb1a7fde15e6c6941c0d21a9eb5bd2ed9 (Wesnoth 1.13.9) or later; has the side-effect of no longer supporting earlier versions.
Given the time since b6e398fd, I assume that anyone using this is using a locally fixed version; therefore I'm not concerned about breaking support for GDB linked with Python2 pretty-printer support. Just going to leave the PR open for a couple of days, and merge unless someone objects.
> GDB (Gnu C++ debugger) pretty printers

- data/campaigns/Eastern_Invasion/scenarios/11_Captured.cfg
Remove redundant macro that adds a defeat event before triggering [endlevel]. The defeat event is already added at the end of the file.
> Remove redundant macro

- changelog.md
- data/core/about.cfg
- data/scenario-test.cfg
- src/gui/widgets/unit_preview_pane.cpp
- src/gui/widgets/unit_preview_pane.hpp
- src/reports.cpp
- src/units/helper.cpp
- src/units/helper.hpp
Moves creation of the advancement tooltip text when you mouseover the "Lvl [number]" in the sidebar to a helper function and convert's the recruit/recall dialog's `level_label_` to a `gui2::implementation::styled_widget` so we can add the tooltip.
I merged the two "User Interface" sections for master in the changelog.
There's a lot of duplication in `unit_preview_pane::set_displayed_type` (recruit list) and `unit_preview_pane::set_displayed_unit` (recall list); they've diverged a bit over time, but I haven't looked closely enough to see how much of that is intentional versus forgetting to update both.
> Fix #4135 - add the "Advances to" tooltip to the recruit and recall dialogs

- data/campaigns/Secrets_of_the_Ancients/units/Bone_Bird.cfg
- data/core/units/humans/Loyalist_Cavalier.cfg
- data/core/units/humans/Loyalist_Cavalryman.cfg
- data/core/units/humans/Loyalist_Dragoon.cfg
- data/core/units/undead/Skele_Chocobone.cfg
- data/tools/wmllint
As reported in issue #4379, wmllint has problems handling correctly defense caps in units. This PR fixes the issue in a few ways.
First of all, wmllint's magic comment `# wmllint: match ... with ...` was able to overwrite abilities-notes pairs in the dictionaries derived from the `notepairs` list, thus leading to false positives; this is handled by replacing the `notetrait` dictionary with a sort-of multimap (Python doesn't really have them, although they can be simulated by using `collections.defaultdict(list)`), so any such comment merely adds a new association to the same key, instead of destroying the existing one.
The second problem was that the `notepairs` list was actually designed to handle only pairs of macros; using that list to look for certain key=value lines has been a …
> Fix for bug #4379 (wmllint issues with defense cap)

- CMakeLists.txt
- cmake/FindSDL2.cmake
- src/CMakeLists.txt
Previously, only scons build in MSYS2 is possible. Now cmake also works with this fix.
`cmake .. -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release -DARCH=native`
> Fix MINGW (with MSYS2) build in Windows

- src/picture.cpp
I think the correct fix is to simply delete the localized_file_uptodate
function, however this commit is the minimal change to avoid #4716
for 1.14.11.
The functionality still works, which can be tested by:
1. set Wesnoth to French
2. note the logo on the title screen says "Bataille pour Wesnoth"
3. change l10n-track
-ok        ¦images/misc/l10n/fr/logo.png¦  f13ab03e31b1aaeec3036ebfe049e78f  6e0af4f77ed425d62ae06ce7157a5b37f67c8f7
+fuzzy        ¦images/misc/l10n/fr/logo.png¦  f13ab03e31b1aaeec3036ebfe049e78f  6e0af4f77ed425d62ae06ce7157a5b37f67c8f7
4. exit and re-launch Wesnoth (just pressing F5 does not work)
5. note the logo on the title screen is in English
> Workaround for the warning about conflicting files called "l10n-track"

- src/units/abilities.cpp
resolve https://github.com/wesnoth/wesnoth/issues/4718. if other_attack condition for adding of abilitie applied to opponent then abilitie function what for attack to same range what owned by owner of abilitie and weapon like abilities must be applied to all attack matched
> fix other_attack conditional generate bug in abilities used like specials

- .travis.yml
- utils/dockerbuilds/travis/Dockerfile-base-1604-master
- utils/dockerbuilds/travis/Dockerfile-base-1804-master
- utils/dockerbuilds/travis/Dockerfile-base-mingw
- utils/travis/docker_run.sh
- utils/travis/sftp
- utils/travis/steps/script.sh
This will SFTP the wesnoth and wesnothd executables from Travis (`UPLOAD_ID=<something>`) to SourceForge.
---
The files are SFTPed to the [bfw-travis-upload](https://sourceforge.net/projects/bfw-travis-upload/files/) project on SourceForge using the independent `bfw-uploader` ID, so it doesn't compromise the main Wesnoth project's files on SourceForge if the password used here were leaked.  The password is encrypted in the `travis.yml` via travis' support for [encrypted environment variables](https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml).  This means is should work for all branches, but not for PRs from forks.
> Upload executables from travis.

- src/units/attack_type.cpp
This will show a warning for bugs similar to the UtBS one that
was fixed in 74ad400900eb5264b0485e9f84b90c968c1aba77.
> Deprecate using [set_specials] without specifying mode=

- utils/dockerbuilds/travis/Dockerfile-base-mingw
- utils/travis/docker_run.sh
- utils/travis/steps/install.sh
While it can't be used currently, it's there and functioning in case that changes in the future.
> Upload .tar.bz2 from travis.

- data/campaigns/Liberty/scenarios/06_The_Hunters.cfg
- data/campaigns/Liberty/scenarios/07_Glory.cfg
- data/campaigns/Liberty/scenarios/08_Epilogue.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/09_Blood_is_Thicker_Than_Water.cfg
Liberty scenario 6:
- added victory event when the player defeated all patrols
- this is to prevent the player having to end turn (for two sides) for a couple turns to wait for victory on _time over_.
UtBS scenario 9:
- fix a dialogue attribution error (if alive, Esanoo speaks of his imprisonment despite never being captured)
- add further merfolk dialogue attribution as flavor
Edit:
- Liberty scenario 7: fixed a small number error, added flavor text to the army arrivals.
- Liberty scenario 8: added a victory event (display credits and add laurel in campaign menu), small text adjustments
> Changes UtBS 9 and Liberty 6,7,8

- src/gui/widgets/unit_preview_pane.cpp
- src/units/unit.cpp
- src/units/unit.hpp
Alternative to #4738, also resolves #4736 and also should be applicable to 1.14 branch. If one is accepted the other can be closed.
This one avoids the performance concerns of #4738 but retains the problem of hard-coded colour values.
> Resolve #4736 (XP always displayed in light blue)

- src/play_controller.cpp
- src/scripting/game_lua_kernel.cpp
- src/time_of_day.cpp
- src/tod_manager.cpp
- src/tod_manager.hpp
- src/utils/math.hpp
now the c++ code does no longer add a dummy time when
there are no times defines for an [time_area]. this is
in particular useful when one wants to define areas in
the map editor that is then used ingame for exampel in
filters.
We should consider renamaing [time_area] to just [area]
[time_area]s that dont define their own times are now
ignored during tod calculation.
> wip support [time_area] with no specific timezone

- data/campaigns/Son_Of_The_Black_Eye/scenarios/07_The_Desert_of_Death.cfg
- data/campaigns/Son_Of_The_Black_Eye/scenarios/09_Shan_Taum_the_Smug.cfg
- data/campaigns/The_Hammer_of_Thursagan/scenarios/04_High_Pass.cfg
- data/core/units/monsters/Giant_Scorpion.cfg
- data/core/units/monsters/Giant_Scorpling.cfg
The addition of a variation for the Giant Scorpion and respective resistance change in #4015 left the unit with the uninspired values of standard humans.
I propose to change the resistances back to something more interesting that builds on their carapace (hard to hurt with normal blades, but you can crush or cook them). Note, that especially the impact resistances go in the _opposite_ direction of the Scuttle variation. Didn't want to overdo it, but I'd also be open to add +10% pierce resistance.
Also added a fix to SotBE scenario 7 to use the variation because scenario dialogue clearly talks about the old resistance values.
Edit: updated the commit with resistances as discussed below and according modifications to the unit description.
I pulled the changes to the Scuttler, because simply …
> proposed new resistances for Giant Scorpion, fix to SotBE 7

- utils/dockerbuilds/travis/Dockerfile-base-1604-master
- utils/dockerbuilds/travis/Dockerfile-base-1804-master
- utils/travis/docker_run.sh
- utils/travis/steps/script.sh
This will then catch errors on the commit it happens instead of usually much later.
---
Also removes the `--tty` and `unbuffer` command usage, since for some reason their presence causes `po4a-translate` to hang ([example](https://travis-ci.org/Pentarctagon/wesnoth/jobs/653932887#L15095-L15098) - in this case cancelled by me early, but this job has the `--verbose --debug` options enabled for it).
If anyone knows of a solution then great, otherwise I'll fully remove the logic for coloring the output since I think running the additional translation targets is more important.
> [WIP] Run the pre-release translation targets on travis.

- src/server/game.cpp
- src/server/game.hpp
- src/server/server.cpp
Currently, wesnothd uses the game instance's `id_` value when inserting into the game_info, game_player_info, and game_modification_info tables.  However, this value is unique only per game instance, not per scenario.  This then results in problems when handling MP campaigns, which re-use the same game instance for multiple scenarios.  Incrementing the game instance's `id_` was determined to not be suitable since it's used in a boost multi-index, and instead creating a brand new game instance for each scenario in an MP campaign is complex without being especially useful beyond this case.
This commit instead adds a separate `db_id_` value to each game instance, which can be incremented without causing any issues since it's used nowhere else, and is what will be inserted into the database. …
> Use an independent ID for the database's GAME_ID column.

- data/campaigns/Under_the_Burning_Suns/utils/dehydration-utils.cfg
Fixes for issues raised in #4206 in two commits.
Part one, which I think is fine, prevents sun shyde from dehydrating herself by changing the dehydration macro.
Part two, which may change both the feel and the difficulty of the level but brings it into line with the current story text, makes dehydration only affect the player side.
> Changes to dehydration (UtBS 2)

- data/campaigns/Dead_Water/_main.cfg
- data/campaigns/Dead_Water/units/Kraken.cfg
- data/campaigns/Legend_of_Wesmere/_main.cfg
- data/campaigns/Sceptre_of_Fire/_main.cfg
- data/campaigns/Secrets_of_the_Ancients/_main.cfg
- data/campaigns/The_Rise_Of_Wesnoth/_main.cfg
- data/core/macros/optional_unit_advancements.cfg
- data/core/units/drakes/Armageddon.cfg
- data/core/units/dunefolk/Blademaster.cfg
- data/core/units/dwarves/Arcanister.cfg
- data/core/units/dwarves/Runesmith.cfg
- data/core/units/humans/Loyalist_General.cfg
- data/core/units/monsters/Wolf_Dire.cfg
- data/core/units/monsters/Wolf_Great.cfg
- data/core/units/orcs/Nightblade.cfg
- data/core/units/trolls/Troll_Shaman.cfg
- data/core/units/undead/Necro_Ancient_Lich.cfg
- data/core/units/undead/Skele_Death_Knight.cfg
- data/core/units/wose/Wose_Shaman.cfg
- data/schema/core/addons.cfg
- src/game_config_manager.cpp
- src/units/types.cpp
- src/units/types.hpp
See issue #3955
the intention is to deprecate [advancefrom] in
favour of [modify_unit_type], because it was a
common source of OOS errors, and it is less flexible.
As a secondary effect this also fixes issue #4402 :
"changing units via extra_defines sometimes not working
because extra_defines had bugs".
Now we no longer use extra_defines for that.
Addon authors should now no longer use these extra_defines,
instead put the new core marcos with the same name directly
into [campaign].
> remove [advancefrom] from mainline

- projectfiles/VC14/wesnoth.vcxproj
- projectfiles/VC16/wesnoth.vcxproj
- source_lists/wesnoth
- src/formula/formula.cpp
- src/scripting/lua_color.cpp
- src/scripting/lua_color.hpp
- src/scripting/lua_kernel_base.cpp
- src/scripting/push_check.hpp
- src/server/server.cpp
- src/sound.cpp
see https://github.com/wesnoth/wesnoth/issues/3706
the main usecase to be able to print messages and dialog labels in the color of a specific team.
Im still not 100% sure about the exact interface thougfh
> add wesnoth.colors

- src/gui/dialogs/multiplayer/mp_create_game.cpp
The UX seems to already be prepared for this - if the map doesn't load then
the create_engine class puts an error message in the map description, which
is shown on the top-left of the MP Create Dialog when the map is selected.
Fixes bugs #3149, #4395 and #4545.  The block deleted in this commit skipped
adding an entry to the games_list listbox, which broke assumptions elsewhere
that the indices returned by create_game_.get_filtered_level_indices()
correspond to the indices in the listbox.
> Fix the MP Create Dialog's handling of unplayable maps

- src/gui/dialogs/multiplayer/mp_create_game.cpp
The UX seems to already be prepared for this - if the map doesn't load then
the create_engine class puts an error message in the map description, which
is shown on the top-left of the MP Create Dialog when the map is selected.
Fixes bugs #3149, #4395 and #4545.  The block deleted in this commit skipped
adding an entry to the games_list listbox, which broke assumptions elsewhere
that the indices returned by create_game_.get_filtered_level_indices()
correspond to the indices in the listbox.
> Fix the MP Create Dialog's handling of unplayable maps (1.14 branch)

- src/display.hpp
- src/floating_label.cpp
- src/floating_label.hpp
- src/game_display.cpp
- src/play_controller.cpp
- src/play_controller.hpp
- src/playmp_controller.cpp
- src/scripting/game_lua_kernel.cpp
fixes https://github.com/wesnoth/wesnoth/issues/4347
the fix kinda works but for some reason it created errors, when undrawing out-of-map  parts. Also i feel dirty after touching the drawing  code.
> fix float_label too fast in some cases

- src/campaign_server/campaign_server.cpp
Commit 702a98d accidentally put the campaign size on its own line. This commit
prints the complete log message only if the campaign is actually sent out.
No changes in program logic. Just an early return added to reduce indentation.
> Improve log messages

- data/campaigns/Heir_To_The_Throne/scenarios/23_Test_of_the_Clans.cfg
Change a misleading word because of some confusion that came up on Discord.
(Someone actually tried to kill all horse lords with Konrad personally).
> HttT S23: change misleading dialogue

- src/actions/attack.cpp
- src/units/abilities.cpp
- src/units/udisplay.cpp
- src/units/unit.cpp
- src/units/unit.hpp
if a unit under leadership use a weapon don't matched with [leadership] [filter_(second_)weapon], then leader_anim of leader is played, or the attack not helped in that case, it musn't be like that.
> fix leadership animation played when weapon don't matche [filter_weapon]

- data/lua/wml/endlevel.lua
- data/schema/core/actionwml.cfg
- data/test/macros/wml_unit_test_macros.cfg
- data/test/scenarios/events-test_defeat.cfg
- data/test/scenarios/events-test_die.cfg
- data/test/scenarios/events-test_filterable1.cfg
- data/test/scenarios/events-test_filterable2.cfg
- data/test/scenarios/events-test_filterable3.cfg
- data/test/scenarios/events-test_nonfilterable.cfg
- data/test/scenarios/events-test_victory.cfg
- data/test/scenarios/interrupts.cfg
- data/test/scenarios/test_lua_wml_tagnames.cfg
- run_wml_tests
- src/game_end_exceptions.cpp
- src/game_end_exceptions.hpp
- src/game_launcher.cpp
- src/game_launcher.hpp
- src/playsingle_controller.cpp
- src/scripting/game_lua_kernel.cpp
- wml_test_schedule
This adds an additional `test_result` attribute to [endlevel], intended for use with the automated unit tests. This allows for the unit tests to differentiate a pass/fail result separately from scenario victory or defeat, which allows for more accurately determining the outcome of a test as well as addresses the potential, for example, for a scenario to be expect to pass because of the {SUCCEED} macro but instead passes because the scenario ended as a victory through some other method.
Additional unit tests which were the original motivation for this change are also added as part of this.  They test, as much as possible, that events are executed at all, and are then also executed in the expected order.
> Separate unit test results from scenario victory/defeat.

- src/wesnoth.cpp
Since it seems that the 64-bit enabled projectfiles for Visual Studio were added without also being tested that they generate a working executable.
---
Related: https://forums.wesnoth.org/viewtopic.php?p=653865#p653865
> Backport of cba53cd471e1b4bb44b2a57d477cf3401422219c

- data/campaigns/Northern_Rebirth/scenarios/05a_01_The_Pursuit.cfg
Small fix for issue #4853 .
Edit: Should probably be backported to 1.14 as well.
> NR S5a: fix issue #4853 naga triggers door

- data/schema/units/animations.cfg
- src/units/udisplay.cpp
If a day, a resistance abilities applied to adjacent unit is added in the core, with a proper animation, it can be validated.
> adding resistance_anim to shema validation

- data/core/about.cfg
- data/core/terrain-graphics.cfg
I mistakingly deleted my fork so I had to open this PR instead of https://github.com/wesnoth/wesnoth/pull/4838.
> Update base terrain for deprecated *^Uf*

- po/CMakeLists.txt
- po/SConscript
- src/CMakeLists.txt
- src/SConscript
- src/actions/create.cpp
- src/addon/info.hpp
- src/ai/contexts.cpp
- src/ai/default/recruitment.cpp
- src/carryover.cpp
- src/game_board.cpp
- src/game_initialization/connect_engine.cpp
- src/game_initialization/create_engine.cpp
- src/gui/dialogs/gamestate_inspector.cpp
- src/gui/dialogs/terrain_layers.cpp
- src/hotkey/hotkey_item.cpp
- src/preferences/game.cpp
- src/reports.cpp
- src/side_filter.cpp
- src/units/animation.cpp
- src/whiteboard/move.cpp
The first commit changes two uses of `python` -> `python3`, since 20.04 doesn't come with the `python` link by default.
Clang fix for `-Wdeprecated-copy` adds a copy constructor due to it warning about having an assignment operator defined but no copy constructor defined is deprecated.
Clang fix `-Wstring-plus-int` silences a warning from the lua source code stating that `<string> + <int>` does nothing.  This sounds... incorrect, but the lua code isn't ours and it doesn't seem to be breaking anything.
Everything else is for `-Wrange-loop-construct` warnings.
> Fixes for clang warnings for Ubuntu 20.04

- src/game_config.hpp
- src/minimap.cpp
A comment-only change, opening as a PR because I'm still wondering whether to
make it a code-change as well. Maybe the "team_rgb_range" should be renamed as "named_color_range", because
it's used for everything defined by the WML `[color_range]` tag. In addition to
the ones normally used for teams (`red`, `lightblue`, etc) it has the minimap
colors for `reef`, `cave`, etc.
Separating the team colors from the terrain colors probably shouldn't be done.
Looking from the opposite perspective, using the terrain colors as team colors
has been discussed on the forums and found to be a useful feature:
* https://r.wesnoth.org/p627592
* https://r.wesnoth.org/p627588
> Add comments about minimap.cpp's use of "team colors"

- src/theme.cpp
- src/theme.hpp
Prior to this change, the 1024x768 base resolution (found in the default theme)
was hard-coded into theme.cpp; resolutions beyond that were always scaled as if they
had been defined on a 1024x768 base resolution, even if the width and height specified
in the theme file were different. Combined with the scaling arithmetic in theme.cpp,
this assumption resulted in bugs such as panels disappearing whenever their width in the
base resolution specified in the theme exceeded 1024 pixels or their height exceeded 768
pixels. This change records the base resolution from the theme in the theme and all of
its objects, so the scaling computation can be done correctly.
This change would resolve issue #4850 -- see also the prototype high res theme posted at …
> Allow theme resolutions based on an arbitrary base resolution.

- data/campaigns/Sceptre_of_Fire/_main.cfg
- data/campaigns/Sceptre_of_Fire/maps/8_The_Dragon.map
- data/campaigns/Sceptre_of_Fire/scenarios/1_A_Bargain_is_Struck.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/2_Closing_the_Gates.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/2p5_Reaching_the_Runecrafter.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/2t_In_the_Dwarven_City.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/3_Searching_for_the_Runecrafter.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/4_Gathering_Materials.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/5_Hills_of_the_Shorbear_Clan.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/6_Towards_the_Caves.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/8_The_Dragon.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/Epilogue.cfg
- data/campaigns/Sceptre_of_Fire/utils/rune-equip.cfg
- data/schema/core/actionwml.cfg
I was previously asked to do one commit per file, they can be squashed for a merge.
I have added a macro to clear to rune variables added by @doofus-01 to `utils/rune-equip` and applied it to all scenarios where the player can buy runes.
Small dialogue tweaks were done for scenarios 1, 2t, 3, 5, and epilogue. This includes changing all mentions of "tribe" to "clan".
S8 map was slightly changed to keep the dragon from suiciding into the AI ulfserkers, which was actually not that improbable before and resulted in none of his dialogue lines triggering (and a scenario named "The Dragon" with no sign of a dragon whatsoever from the players perspective).
> Sceptre of Fire: bug fixes and small tweaks to dialogue

- data/gui/widget/label_default.cfg
PR #4860 scales fonts by the observed screen pitch in microns when the main window is 1200x900 or larger. However, it seems based on the issue report #4908 that in some cases, the reported pixel pitch is not correct, and the scaling was shrinking fonts intolerably. This PR ensures that the scaling will never decrease font sizes, although it does not address why or under what circumstances the screen_pitch_microns may be incorrect.
> Work around issue #4908.

- src/gui/widgets/settings.cpp
- src/video.cpp
SDL_GetDisplayDPI  returns zero if it can't determine the DPI scale factor.
This fix will fall back to a 1.0 scale factor instead of dividing by zero when this happens.
> Fix divide by zero when SDL can't get DPI for scale factor.

- data/themes/_initial.cfg
- data/themes/default.cfg
- src/theme.cpp
As Pentarctagon suggested, before PR #4851 the lower resolutions of the default theme were still calculating off of a base resolution of 1024x768. After PR #4851, they were calculating off of their specified resolutions. This is more sensible, but given the scaling code and the old theme specification, could cause the main map to disappear via a bug complementary to the one that PR #4851 fixed (that the main map was disappearing when the resolutions were *too high*). This PR tweaks the rescaling to handle these cases when the screen resolution is small, and tweaks the definition of the 800x600 resolution of the default theme to specify the main map at a reasonable size for that resolution (formerly it was specified as larger than the screen (!) which was only working due to the quirks of …
> Fix issue #4909.

- data/gui/macros/_initial.cfg
- data/gui/widget/button_default.cfg
- data/gui/widget/label_default.cfg
- data/gui/widget/toggle_button_default.cfg
This is a follow-on to PR #4860 -- it extends the scaling initiated in that PR to most of the buttons and toggle buttons in the game. Somewhat mysteriously, the "Menu," "Actions,", and "End Turn" buttons in the main gameplay window are still not scaling. Hopefully that can be tracked down in the future.
> Scale buttons and toggle buttons with screen pitch also.

- src/gui/dialogs/attack_predictions.cpp
In damage calculation window, the "damage" weapons specials were used in calculation but not the abilities equivalent.
> add "damage" ability in damage calculation window(UI)

- src/units/abilities.cpp
@gfgtdf without other_attack_ in special_active_impl, the opponent's attacks cannot be filtered and the use of filter_weapon filter_opponent always returns a null result.
> Fix [filter_weapon] that doesn't work in filter_opponent

- src/savegame.cpp
Fixes #4936 by only adding the timestamp to the replay's filename rather than *all* save filenames.
> Make the fix for #4730 more targetted.

- src/addon/manager.cpp
- src/addon/manager.hpp
- src/build_info.cpp
- src/game_config_manager.cpp
- src/game_config_manager.hpp
This would be useful since often one of the things asked when a user reports issues is if they have any addons installed.
---
Tested locally with two addons (first with an _info.cfg, second with a _server.pbl):
```
Installed Add-ons
=================
Ally_Village_Modification : 1.0.3
Ally_Village_Modification_pbl : 0.1.80
```
If there are no issues, I'd like to get this merged and backported prior to 1.14.13's release.
Edit-
Fixes #4873 as well.
> Add installed addons and addon versions to the build report.

- data/campaigns/Under_the_Burning_Suns/scenarios/03_Stirring_in_the_Night.cfg
In Under the Burning Sun scenario 3, Garak is given the ability "righteous rage" on both of his attacks. This effectively makes those attacks behave the same as berserk when Garak is fighting an enemy "champion", i.e. two undead units named Grak and Zur. I believe this was unclear and raised #4945 because I didn't understand that this ability only applies to fights against Grak and Zur, so I've made this PR to hopefully make the description a little clearer.
> Changes description of "righteous rage"

- src/build_info.cpp
- src/video.cpp
- src/video.hpp
This makes all sections use a formatter class to deal with the issue of keeping the first column's width consistent within each section (but not across all sections), so that we don't run into inconveniences later in the future if any section's entry labels change. It also allows us to change the list formatting entirely in a single place rather than multiple places if we ever decide to do so.
The video and add-ons report sections are also made to use the new formatter, making them look more consistent than before compared to the rest of the report:
```
Current video settings
======================
Current pixel resolution: 1920x1015
Refresh rate: 60
SDL reports: 92.5389x92.6757 dots per inch.
Installed add-ons
=================
After_the_Storm : 0.10.0-dev
AtS_Music : 0.3.1
IftU_Music : …
```
> bi: Refactor clipboard report formatting logic

- src/tests/test_recall_list.cpp
- src/tests/test_unit_map.cpp
Some indirect inclusion paths were removed in 194b903918db4405862028ed4ab2eb2ae6fc91c2.
Creating a PR to check that this builds everywhere.
> Add missing includes of units/types.hpp to the unit tests

- src/gettext_boost.cpp
you may _never_ use the std:: file io functions
in wesnoth since they only support acii characters.
wes have fixed this mayn times already but apparently
the preson that added -po file support didn't knew
that.
> WIP fix crash when reading chinese -po files

- data/campaigns/Heir_To_The_Throne/units/Battle_Princess.cfg
- data/campaigns/Heir_To_The_Throne/units/Princess.cfg
this macro must be present in scepter_variation of Princess and Battle_Princess unit_type for what initiative abilitie function in 1.14 when Li'sar have the Scepter of fire
> fix {WEAPON_SPECIAL_INITIATIVE_EVENTS} not in scepter_variation(1.14 version)

- data/gui/macros/_initial.cfg
Changes the GUI_WINDOW_PERC_FIXED_SIZED_CENTERED macro used by the load game dialogue to scale the nominal pixel size of the window by exactly the same scaling used for font sizes at large pixel dimensions, but (a) capped by a percentage of the screen size and (b) no smaller that it would have been under older code. Provision (b) is important to avoid the dialogue becoming any smaller on lower-pixel-dimension screen sizes where the label font scaling is not in effect.
Resolves #4969
> Scale fixed-size dialogue window capped by screen size percentage

- src/play_controller.cpp
- src/playsingle_controller.cpp
The former was added in commit 40a1e7d3fa74d59e7bba2d23fc535d9aa0a7f499. However, `ai/testing` predates it by several years (added in commit ab540dca1517e82d0f93153604cdb00f256becd6) and also follows the existing naming convention better.
I don't think this should break anything, but just in case I'm creating a PR for it to run unit tests, since apparently `aitesting` was at some point relevant for those.
> Replace aitesting log domain with ai/testing

- data/core/about.cfg
- src/addon/client.cpp
- src/addon/info.cpp
- src/addon/info.hpp
- src/campaign_server/addon_utils.cpp
- src/campaign_server/addon_utils.hpp
- src/campaign_server/campaign_server.cpp
- src/gui/dialogs/addon/manager.cpp
- src/gui/widgets/addon_list.cpp
- src/gui/widgets/addon_list.hpp
**Addon titles and descriptions made translatable**
Hello, wesnoth devs!
The international wesnoth players had long been troubled by not being able to see what the addon is about without installing it or using external tools. So I decided to make it possible to see addon titles and descriptions in the addon manager.
I've done through `[translation]` tag modification because sending .mo file for the entire campaign is unnecesearily, and .mo and .po workflow just for .pbl file is redundant.
The feature is done on the `master` branch, but I'd like backporting it to 1.14 in after it's tested.
The original tag contains only the `language` attribute, the new one has the following structure. (If the declaration is abscent, but the .mo file is present, it'll be added with `supported=yes` …
> Addon titles and descriptions made translatable

- data/gui/window/unit_create.cfg
- src/gui/dialogs/unit_create.cpp
- src/gui/dialogs/unit_create.hpp
- src/menu_events.cpp
- src/synced_commands.cpp
- src/units/types.hpp
- src/units/unit.cpp
- src/units/unit.hpp
This is a bit of a messy pull request that touches both backend code (the synced commands functionality) and UI code (context menu, Create Unit) bringing a few improvements to the Create Unit dialog.
Firstly, smaller aspects of Create Unit should be more streamlined by removing redundant labels and caption text.
Secondly, the dialog now supports selecting the unit type variation for the unit that will be created.
In order to implement this functionality I had to touch a surprising amount of code in `menu_events.cpp`, the synced commands functionality, as well as a couple key methods of the `unit` class. As far as I can tell there shouldn't be unexpected side-effects for these changes, but just in case I want @gfgtdf's review in addition to @Vultraz's anyway since it's not code I am well …
> Create Unit UI improvements & unit type variation selection

- data/core/about.cfg
- src/addon/client.cpp
- src/addon/info.cpp
- src/addon/info.hpp
- src/campaign_server/addon_utils.cpp
- src/campaign_server/addon_utils.hpp
- src/campaign_server/campaign_server.cpp
- src/gui/dialogs/addon/manager.cpp
- src/gui/widgets/addon_list.cpp
- src/gui/widgets/addon_list.hpp
Hello, wesnoth devs!
This is the backport of my previous pull-request (#4984) making addons titles and descriptions translatable to 1.14.
You can see the rationale and the discussion here: https://github.com/wesnoth/wesnoth/pull/4984 .
As for backwards-compatibility, I tested this build on my local server, and it works just as it had been before both when the new client connects to the old server or the old client connects to the new server. All the features worked fine when I tested them with an example addon.
> Backport addon titles and descriptions made translatable

- src/gui/widgets/window.cpp
Reverts the assertion concerning nonzero window dimensions in
gui/widgets/window.cpp; it turns out that some windows do request zero
dimension, and it doesn't hurt anything for them to.
Fixes #4960.
> Don't insist that windows request nonzero height or width

- src/editor/map/map_context.cpp
This comment will be added at the start of any .cfg file written by the
scenario editor. Given that the only target audience is authors using text
editors, it's not translatable and uses plain ascii characters.
This is the easy part of #1380.
> Warn about manually editing files created by the scenario editor

- src/game_config_view.cpp
before the 'ignore unused addons' commit the engine reordered [terrain_graphics] to make mainline [terrain_graphics] appear after umc [terrain_graphics] tags, this commit restores this behavior  (instead of using [terrain_graphics]precendence= in mainline which would be an alternative  fix). If we ever use game_config_view for anything else than the game_config we can also make this an optional "bool put_first_source_last" parameter.
> readd changing the order of [terrain_graphics]

- utils/dockerbuilds/mingw/get_dlls.py
- utils/update_appdata
I'm opening a PR to check that this builds on all of the platforms, but then plan
to merge without further review. @loonycyborg already uses these tools with
Python 3, and gave a green-light for this change in https://github.com/wesnoth/wesnoth/issues/1508#issuecomment-665119912 .
The python launcher tool for Windows has magic handling for some shebang lines,
however `#!/bin/env python` isn't recognised without the `/usr`. Had the `/usr`
been included with the old code then these scripts would likely have been run
with Python 2.
https://docs.python.org/dev/using/windows.html#shebang-lines
> Disambiguate some python shebang lines to be "python3"

- src/saved_game.cpp
- src/saved_game.hpp
- src/server/wesnothd/server.cpp
This commit:
* sends the era and scenario as part of a [multiplayer][addon] in order to make it consistent with how add-ons' information is sent to wesnothd. this means all of the game's content information is now available in the [multiplayer][addon] data.
* correctly covers the case of there potentially being modifications added to mainline at some point. the current code looks at the [multiplayer]mp_scenario= and [multiplayer]mp_era attributes to cover the case of a mainline era/scenario being used, but looks for modifications only in the [multiplayer][addon] data, which wouldn't have any entry for a mainline modification right now if one were added.
> Have mainline content send [multiplayer][addon] info as well.

- src/help/help_impl.cpp
- src/help/help_impl.hpp
- src/help/help_menu.cpp
- src/help/help_menu.hpp
This commit uses the UI's calculated indent for the UI's event handling, and
removes section::level. The code generating the help sections still has its own
"level", which is used to detect excessive recursion.
This fixes a UI quirk that I only noticed while working out what section::level
was for, while considering the subtopics needed for implementing a taxonomy
system. The help browser calculates indentation for its tree-view based on the
data tree given to it. However, the logic for deciding whether a mouse-click
was on the icon or the text used section::level, rather than any value
calculated in the UI classes. While section::level was often the correct
number, it was wrong for the terrain types' sections.
> Help browser: fix behavior of clicking on icons of terrain sections

- src/font/text.cpp
- src/font/text.hpp
The main change here is avoid a crash, but there's also a fix for a possible UI issue with text looking bad. I've made the two changes in a single commit, because if we backport either we might as well backport both (in my opinion).
The effect of text looking bad might only occur with certain combinations of OS, debug/release builds, and potentially graphics card and driver; I don't know whether it ever occurs. The effect is similar to  #1568, #1744 and #1925, to the extent that I'd expect any reports of it to be treated as duplicates of those bugs, however it doesn't quite match the screenshots in those bugs; when this bug is the root cause.
Simulated screenshot, showing what happens if Cairo pads the stride to twice the width - the first half of the text (vertically) looks OK. For this …
> text.cpp: throw if rendering needs more than 2GB, fix antialiasing with stride > width

- data/campaigns/World_Conquest/era/factions/strings.cfg
- data/campaigns/World_Conquest/lua/campaign/objectives.lua
- data/campaigns/World_Conquest/lua/game_mechanics/bonus_point_definitions.lua
- data/campaigns/World_Conquest/lua/game_mechanics/invest/invest_show_dialog.lua
- data/campaigns/World_Conquest/lua/game_mechanics/invest/invest_tellunit.lua
- data/campaigns/World_Conquest/lua/game_mechanics/promote_commander.lua
- data/campaigns/World_Conquest/lua/game_mechanics/unittypedata.lua
- data/campaigns/World_Conquest/lua/game_mechanics/wocopedia/help.lua
- data/campaigns/World_Conquest/lua/game_mechanics/wocopedia/help_dialog.lua
- data/campaigns/World_Conquest/lua/map/scenario_utils/plot.lua
- data/campaigns/World_Conquest/lua/map/settings/settings_dialog.lua
- data/campaigns/World_Conquest/lua/optional_mechanics/pick_advance.lua
- data/campaigns/World_Conquest/resources/strings/artifacts.cfg
- data/campaigns/World_Conquest/resources/strings/effects.cfg
- data/campaigns/World_Conquest/resources/strings/training.cfg
**Before** merging this I have some questions about some phrases in `data/campaigns/World_Conquest/lua/game_mechanics/wocopedia/help.lua` that I didn't know how to decipher (from a native English speaker's point of view):
Line 39:
> Carryover is 15%, comunitary and avoid negative amounts.
I don't know what 'comunitary' is supposed to mean. Communal? Also what does 'carry-over avoid negative amounts' supposed to mean? Gold will always be non-negative at the start of a scenario?
Line 45:
> Every chance will do different dice rolls
This is in the context of units' training. Every chance of what? Every time a new unit is recruited there will be a different chance of being trained?
Line 68 (partially edited):
> The World Conquest II era consists of factions that are build of pairs of mainline …
> Update World Conquest II Strings

- src/game_classification.cpp
This line is meant to skip the rest of the loop for things that have previously
been inserted in to loaded_resources; but instead it skipped the rest of the
loop unless the id was already in loaded_resources. Fixes #5126.
> Fix inverted logic in working out which resources are active

- src/addon/info.cpp
- src/gettext.hpp
- src/gettext_boost.cpp
Backport of pull-request #5109 from master to 1.14.
The nice new feature that allows translated add-on titles and descriptions in the add-ons manager works well when the language preference is explicitly set to some supported language, but not when "System default language" is selected, because this is represented by an empty string in language.hpp. This pull request fixes this by getting the effective locale (the actual translation target language) from gettext.
> 1.14 add-ons manager translated titles and description also for System default language

- src/addon/info.cpp
- src/gettext.cpp
- src/gettext.hpp
The nice new feature that allows translated add-on titles and descriptions in the add-ons manager works well when the language preference is explicitly set to some supported language, but not when "System default language" is selected, because this is represented by an empty string in language.hpp. This pull request fixes this by getting the effective locale (the actual translation target language) from gettext.
> add-ons manager translated titles and description also for System default language

- src/help/help_impl.cpp
- src/help/help_impl.hpp
Fixes #1935 for normal users, expanding on aac0941's fix which only showed
these abiities when Wesnoth was in debug mode.
The removed enum member "NON_REVEALING_DESCRIPTION" was unused, and all
existing callers effectively used description_type() as a boolean.
This does mean that the "aged" trait will be shown to all users, even if
they haven't played HttT, however that seems reasonable.
> Show the "loyal" trait in help

- data/core/units.cfg
- data/schema/units/races.cfg
- src/help/help_impl.cpp
- src/help/help_impl.hpp
- src/units/race.cpp
- src/units/race.hpp
This allows the help browser to add links between [race]s. I've used the word "group" rather
than "subrace",  it seems less likely to have political overtones.
The code comments talk about both Dunefolk and Quenoth Elves - of these two, only the
Dunefolk's data is changed in this commit, the Quenoth still have race=elf at the moment.
Draft documentation for the Wiki:
```
* '''help_taxonomy''': {{DevFeature1.15|?}} in the help browser, show this
race as a group of units from another race; the value of this attribute should
be the other race's '''id''' attribute. This only affects the help browser, for
all other purposes (such as WML filters) the two races are completely separate.
How this is visualised in the help browser is a GUI design decision, this attribute
merely tells the engine …
```
> Show [race]help_taxonomy= as "This is a group of units, all of whom are $help_taxonomy"

- data/campaigns/Under_the_Burning_Suns/_main.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/06b_In_the_Domain_of_Dwarves.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/08_Out_of_the_Frying_Pan.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/09_Blood_is_Thicker_Than_Water.cfg
- data/campaigns/Under_the_Burning_Suns/units/other/Dark_Assassin1.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Archer.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Champion.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Corrupted_Elf.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Divine_Avatar.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Druid.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Fighter.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Flanker.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Marksman.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Mystic.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Outrider.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Pathfinder.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Ranger.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Scout.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Shaman.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Shyde.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Sun_Singer.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Sun_Sylph.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Tauroch_Flagbearer.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Tauroch_Protector.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Tauroch_Rider.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Tauroch_Stalwart.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Tauroch_Vanguard.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Warrior.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Youth.cfg
- data/campaigns/Under_the_Burning_Suns/units/units.cfg
UtBS: Make "quenoth" a separate race to "elf" (fixes #4876)
This is motivated by reorganising the help pages to split the Quenoth from the
"pointy ears, pale skin" help text in data/core/units.cfg. It also means that
there's no reason to [hide_help] for the default era elvish units. The new help
text is just a short placeholder for now.
The new race has [race]help_taxonomy=elf.
If the player loads a mid-campaign save then their recalls and heroes will have
race=elf while new recruits have race=quenoth.  For that reason, I've changed
the scenarios' event triggers to recognise both races.
When levelling up, units with race=elf may change to race=quenoth.
Opening the help for a unit will show the help as if the unit has race=quenoth,
even when right-clicking on a race=elf unit. This is good. …
> UtBS: Make "quenoth" a separate race to "elf" (fixes #4876)

- data/campaigns/Under_the_Burning_Suns/scenarios/02_Across_the_Harsh_Sands.cfg
Fixes #5149.
@nemaara in terms of balance, without this fix I saw only 1 ghost during the first night; with this fix I had 3 ghosts spawn at end-of-turn-4, and another 2 at end-of-turn-5. They do attack the scorpions too, but it definitely needs a balance check.
> UtBS S02: Recognise Beach Sands and embellishments when spawning ghosts

- src/preferences/general.cpp
- src/preferences/general.hpp
Opening a PR just to run the CI tests, going to merge once the CI is done. That's a sanity-check in case some platform-specific code is depending on an indirect `#include "utils/make_enum.hpp"`.
The preference was removed in 15bf3bb25691c6ce71ac2a45bb4e5c06ea9239e6.
> Clean-up leftovers of the SCALING_ALGORITHM preference

- data/core/help.cfg
This command and the documentation provided by ":help droid" were updated
in efd808ea842ff88174cc2e953c8b871b8c41dae0, but we missed that this command
is also documented in the help browser's (Commands, General Commands) page.
The docs here are more verbose than in ":help", so the text is newly written
instead of being copied from the existing location.
> Update the docs for ":droid full" in the help browser

- src/commandline_options.cpp
- src/commandline_options.hpp
- src/game_config_manager.cpp
* Fixes #4223, by making the --validate and --validate-* options imply --nocache.
* Fixes #4224, showing an error if you misspell the id argument to
--validate-addon. The application doesn't (but should) quit automatically to
avoid the user spending time on a non-functional validation run, however it
does at least disable all add-ons, which should have the same end result.
* Shows a warning that --validate-addon needs the user to play the add-on, it
doesn't automatically check the add-on. This was my misunderstanding when
logging issue #4225, which has now been repurposed into a feature request for
a new tool that does what I thought --validate-addon did.
> Improve user-friendliness of the validation options

- data/ai/micro_ais/scenarios/animals.cfg
Several new animals were added in PR #5039's cbad6f42492be5fcbf8c29a3d10cbc43598ba32c.
The micro-ai demo can be accessed by starting Wesnoth with the command-line
arguments `--test animals`. The scenario uses some stand-ins for animals that
weren't in mainline; the new bears and tuskers fit straight in. For the sheep,
the icemonax's graphics are a bit more sheep-shaped than the troll whelp's.
This demo doesn't need to be balanced, the changed unit stats are no problem.
UtBS's dustboks aren't in core, otherwise I'd use them as the deer stand-in.
@doofus-01 thanks for these new resources. Are the unit ids final (as in, should
I postpone this change in case they get renamed)?
> Use the new animals in the "animals" micro-ai demo

- data/gui/window/outro.cfg
- src/about.cpp
- src/about.hpp
- src/game_launcher.cpp
- src/gui/dialogs/outro.cpp
- src/gui/dialogs/outro.hpp
An idea to improve the credits experience. This doesn't do anything to deal with the larger issue over the massive surface in the credits dialog, but I think it presents the campaign-specific credits better.
In short, it extends the Outro sequence past the "The End" text to include the campaign name followed by the campaign-specific credits with each section split into groups of no more than 5 names at a time. The long-form credits are **no longer shown** after.
For instance:
> [Proposal] Extended Outro dialog with campaign-specific credits

- data/_main.cfg
- data/modifications.cfg
- src/play_controller.cpp
- src/units/helper.cpp
Depsite being a [modification] this is actuall implemented
in the C++ code the [modification] just sets a flag.
With this modification active all advancements are delayed
until its the players (that controls the unit in question) turn
again.
This is meant as an alterntive to the preset advancement
type of mod.  want to play around with this alternative mod a a bit in 1.15
maybe we will remove it later if we find ot that it wasn't a good idea.
The problbme this is supposed to fix is that advancemnts
are done randomly during the enemeies turn. It has a few
advantages over the preset advancemnt approach:
1) It can easily handle Amlas and normal advancement
2) It doesn't need special code to handle the case that
A unit advances multiple times. During an enemies turn.
3) It doesn't break in …
> Add 'Delay Advancements [modification]

- src/editor/palette/terrain_palettes.cpp
This changes the legend at the bottom of the screen from
FG: Savannah/Forest (Forest,) | BG: Green Grass/Grassland (Flat)
to
Left-click: Savannah/Forest (Forest, ) | Right-click: Green Grass/Grassland (Flat)
Shift + left-click: paint overlay layer only | Ctrl + click: copy terrain
or (with a non-overlay selected)
Left-click: Desert Sands/Desert (Sand) | Right-click: Green Grass/Grassland (Flat)
Shift + left-click: paint base layer only | Ctrl + click: copy terrain
> Hint about the editor's shift+click and ctrl+click

- src/font/font_config.cpp
- src/gui/dialogs/title_screen.cpp
Fixes #5194. If starting the game in a given language works properly, then
this PR makes changing to that language without restarting also works properly.
This can work with or without #5200 - I hope to get both of them in as #5200
has a lot of code cleanup; but this one has a better ratio of
bugs fixed vs lines of code to review.
Getting fonts in the correct order is important for CJK (Chinese, Japanese,
Korean), as the same codepoint may have different images even between
DroidSansJapanese and DroidSansFallbackFull (see discussion in issue #5194).
This method of calling load_font_config() to reload the fonts is already used
during startup - see the two calls to it in src/wesnoth.cpp.
> Reload the fonts (both GUI1 and GUI2) when changing language

- src/game_initialization/lobby_info.hpp
- src/game_initialization/multiplayer.cpp
- src/game_initialization/multiplayer.hpp
- src/game_initialization/playcampaign.cpp
- src/game_launcher.cpp
This mainly consolidates the `enter_*_mode` functions under a single manager class with private members instead of relying on passing around a helper struct with data params.
One functional change is that lobby_info now also has the list of installed addons even in local mode, but I don't see any reason that shouldn't be the case. It keeps things consistent.
> MP: cleaned up mp workflow code

- data/themes/editor.cfg
Commit 43de778 made all themes scale from their base dimensions rather
than from an arbitrary hard-coded 1024x768 pixel size. As a result, the
800x600 layout for the editor needs its main map explicitly sized --
the 843-pixel width no longer fits in 800x600, and it isn't being scaled
down from 1024. (But once it is explicitly set for the 800x600 layout,
it will scale up for pixel widths between 800 and 1024). This commit
adds such an explicit sizing, analogous to the one found in default.cfg.
Resolves #5193.
> Update editor cfg file to reflect earlier changes in scaling

- data/campaigns/Secrets_of_the_Ancients/utils/zombie-utils.cfg
- data/lua/wml/set_variable.lua
I think it's easier for translators if each string is actually just one string. Using "split" on a translatable string just unnecessarily complicates things.
I also fixed a bug in `[set_variable]` which was referenced by a comment in the SotA zombie-utils file.
> Refactor translatable strings for the SotA zombie recruit dialog

- data/core/about.cfg
- data/core/units/monsters/Ant.cfg
- data/core/units/monsters/Bear.cfg
- data/core/units/monsters/Giant_Stoat.cfg
- data/core/units/monsters/Icemonax_Greater.cfg
- data/core/units/monsters/Tusker_Gorer.cfg
- data/core/units/monsters/Tusker_Tusklet.cfg
Giant Stoat (L0), Giant Ant (L0), Gorer (L1), Cave Bear (L2) and Great Icemonax (L2) have no advancements.
I changed their experience to 50 times level (25 for L0) to match with similar units in mainline.
Tusklet and Gorer are of the same unit line. So I gave Tusklet the advancement to Gorer.
There are some things I am not sure about:
Should Giant Ant (L0) advance to Fire Ant (L1)? I don't think so because they appear in different faunas corresponding to the [forum post](https://forums.wesnoth.org/viewtopic.php?f=9&t=52894) of doofus-01.
Icemonax (L0) and Great Icemonax (L2) are obviously of the same unit line. But their levels differ by two. Hence, an advancement of Icemonax to Great Icemonax would not make much sense at this time.
Will there be a L1 unit between those or will one of …
> Changes in new monster units regarding experience and advancements

- CMakeLists.txt
- SConstruct
- src/server/common/dbconn.cpp
- src/server/common/dbconn.hpp
- src/server/common/forum_user_handler.cpp
- src/server/common/forum_user_handler.hpp
- src/server/common/user_handler.hpp
- utils/travis/docker_run.sh
@soliton- @loonycyborg - while obviously this isn't remotely ready for review/merging yet, I would appreciate if you could take a quick look at what I have so far and make sure it makes sense.  Particular points of note:
* The `async_test_query()` is there as a query that will take a noticeable amount of time to complete, for testing purposes.
* In an actual async query implementation, the call to boost::asio::post that passes `io_service_` as the first argument would be where `async_send_doc_queued()` would be used (rather than just the cout that's there for the test query now).
* For the connection pool (`conn_pool_`), the idea is that [0] is what's used for all the existing, non-async queries.  [1] and above are used for async queries.
* `get_single_int()` was changed to …
> Add support for async queries.

- changelog.md
- data/core/help.cfg
- projectfiles/CodeBlocks/wesnoth.cbp
- projectfiles/VC16/wesnoth.vcxproj
- source_lists/wesnoth
- src/display.cpp
- src/display_context.cpp
- src/display_context.hpp
- src/units/drawer.cpp
- src/units/orb_status.cpp
- src/units/orb_status.hpp
Note: the build will fail on MacOS, as the new orb_status files still need
adding to the MacOS build.
Instead of using the allied orb during their turn, the unmoved, moved and
partial orbs are shown. The player's own units will be shown with the moved orb
during the ally's turn, which matches the previous behavior. This is intended for
co-operative MP campaigns, where it will make it easier for players to discuss
possible moves. The UX is also visible in SP scenarios with allied sides, HttT's
first scenario is an easy place to see what it does.
Updated the documentation about orb colors. In these docs I've moved all of
the images to a single line above the bullet-pointed list, as otherwise the
layout looked bad once a line wrapped - the first line appeared
horizontally-aligned with the …
> Orb refactor and ally orb colors during allies' turns (#1424)

- data/lua/wml-tags.lua
The remove attribute for [event] was never added to the validation schema,
and using [remove_event] seems easier to search WML for. Let's just recommend
the new key and deprecate the old one.
Tested with the current implementation of #5215
> Deprecate [event]remove=yes, recommend [remove_event]

- src/gui/dialogs/game_load.cpp
I recently came across https://github.com/wesnoth/wesnoth/issues/5156 and decided to look into it.
Instead of comparing to the filename from the label widget, I've changed it to compare to the `games_` save_info list, which seems to have the full filenames (the `delete_button_callback` method in this file already uses `games_` to get the exact filename to delete, so this seems like a similar use case). I've tested my changes locally and searching for words in long filenames work now.
Let me know if this is the right approach, thanks
> Fix load game search filter for long filenames (fixes #5156)

- src/server/common/dbconn.cpp
- src/server/common/dbconn.hpp
- src/server/common/forum_user_handler.cpp
- src/server/common/forum_user_handler.hpp
- src/server/common/user_handler.hpp
- src/server/wesnothd/server.cpp
- utils/mp-server/table_definitions.sql
Fixes #5066
---
As a reminder to myself as well, the existing MAP_NAME and ERA_NAME columns will need to be given defaults prior to the updated wesnothd being rebuilt.  Then once the existing data is migrated to the new table, I intend to drop the era/map columns on GAME_INFO as well as the modification-specific table.
> Move the game content info (scenario/era/modifications) into their own table.

- packaging/windows/translations.nsh
"Bitwy" means "Battles", in name there is clearly only single "Battle" thus it shouldn't be "Bitwy" but "Bitwa".
Copy of #5238 for 1.14.
> Typo fix in shortcut of polish version. for 1.14.

- packaging/windows/translations.nsh
"Bitwy" means "Battles", in name there is clearly only single "Battle" thus it shouldn't be "Bitwy" but "Bitwa".
> Typo fix in shortcut of polish version.

- data/campaigns/Delfadors_Memoirs/scenarios/14_Shadows.cfg
- data/campaigns/Delfadors_Memoirs/scenarios/15_Save_the_King.cfg
- data/campaigns/Delfadors_Memoirs/scenarios/16_Dark_Sky_Over_Weldyn.cfg
- data/campaigns/Delfadors_Memoirs/scenarios/18_The_Portal_of_Doom.cfg
- data/campaigns/Delfadors_Memoirs/scenarios/19_Showdown_in_the_Northern_Swamp.cfg
- data/campaigns/Delfadors_Memoirs/scenarios/20_Prince_of_Wesnoth.cfg
- data/campaigns/Delfadors_Memoirs/scenarios/21_Clash_at_the_Manor.cfg
- data/campaigns/Delfadors_Memoirs/scenarios/22_Face_of_the_Enemy.cfg
- data/campaigns/Legend_of_Wesmere/scenarios/chapter1/01_The_Uprooting.cfg
- data/campaigns/Legend_of_Wesmere/scenarios/chapter1/02_Hostile_Mountains.cfg
- data/campaigns/Legend_of_Wesmere/scenarios/chapter1/03_Kalian_under_Attack.cfg
- data/campaigns/Legend_of_Wesmere/scenarios/chapter2/04_The_Elvish_Treasury.cfg
- data/campaigns/Legend_of_Wesmere/scenarios/chapter2/05_The_Saurian_Treasury.cfg
- data/campaigns/Legend_of_Wesmere/scenarios/chapter2/06_Acquaintance_in_Need.cfg
- data/campaigns/Legend_of_Wesmere/scenarios/chapter2/07_Elves_Last_Stand.cfg
- data/campaigns/Legend_of_Wesmere/scenarios/chapter3/09_Bounty_Hunters.cfg
- data/campaigns/Legend_of_Wesmere/scenarios/chapter3/10_Cliffs_of_Thoria.cfg
- data/campaigns/Legend_of_Wesmere/scenarios/chapter3/11_Battle_of_the_Book.cfg
- data/campaigns/Legend_of_Wesmere/scenarios/chapter4/14_Human_Alliance.cfg
- data/campaigns/Legend_of_Wesmere/scenarios/chapter4/17_Breaking_the_Siege.cfg
- data/campaigns/Legend_of_Wesmere/scenarios/chapter5/19_Costly_Revenge.cfg
- data/campaigns/Legend_of_Wesmere/scenarios/chapter5/20_Council_Ruling.cfg
- data/campaigns/Legend_of_Wesmere/scenarios/chapter5/21_Elvish_Assassins.cfg
- data/campaigns/Legend_of_Wesmere/scenarios/chapter5/22_Northern_Battle.cfg
- data/campaigns/Legend_of_Wesmere/scenarios/chapter5/23_End_of_War.cfg
- data/campaigns/Legend_of_Wesmere/utils/bigmap.cfg
None of these had any effect, either on 1.15 or 1.14. I doubt that they ever
had an effect, because if these story screens had 4 second or even 8 second
delays then it would surely have been treated as a bug.
A schema update for this will follow in PR #5242.
> DM and LoW: Remove '[story][part]delay=' attributes

- src/gui/dialogs/unit_recall.cpp
Turns out that https://github.com/wesnoth/wesnoth/issues/5171 is caused when index is -1, when no unit is selected in the list. I don't know if we want some certain error message to show, but otherwise this fix will basically make the buttons do nothing if no unit is selected.
To reproduce error: open recall window in any game and type in search filter so no units match. Clicking "dismiss" or "rename" will segfault
> Add bounds checks for unit dismiss and recall (fixes #5171)

- data/campaigns/Secrets_of_the_Ancients/scenarios/04_Becalmed.cfg
While [background_layer] has a scale attribute, [story][part][image] doesn't. A schema update for that will follow in PR #5242.
> SotA S04: Remove some [image]scale=no attributes

- src/font/text.cpp
- src/font/text.hpp
https://github.com/wesnoth/wesnoth/issues/4387 and https://github.com/wesnoth/wesnoth/issues/2934 basically revolve around 2 problems:
**Problem 1: formatting links is done by a naive search and replace**
If there are duplicates of a url, only the first is highlighted, since we are using `replace_first`.
https://github.com/wesnoth/wesnoth/blob/b8f03c40e6f25ad0fd2ae3c6c1d7360c76270ef0/src/font/text.cpp#L812-L817
We can't just do a `replace_all` either, since this won't work correctly when one url is a substring of another url (`http://a.com` and `http://a.com/b`)
To reproduce:
1. Go to multiplayer chat and type `http://a.com` twice. Only the first is highlighted.
**Problem 2: escaping problems with &**
The problems occur when we send unescaped text to …
> Fix hyperlink formatting in texts (fixes #4387, #2934)

- src/editor/map/context_manager.cpp
I was investigating https://github.com/wesnoth/wesnoth/issues/4789 and I'm pretty sure that the crash has nothing to do with attempting to place a 2nd unit in the same spot as theorized, but rather that the team index (`currentTeam_`) is not reset when creating or switching to a different scenario. The crash occurs when the team index you're currently on doesn't exist in the scenario you're switching to.
There are 2 ways to reproduce:
**new scenario**
1. In the map editor, create a new scenario.
2. Add a 2nd side and switch to it
3. Create another new scenario
**switching scenarios**
1. In the map editor, create a new scenario
2. Create another new scenario
3. Add a 2nd side and switch to it
4. Switch to the first scenario
My current fix is in two places. The fix in …
> Fix crash from side not being reset in editor (fixes #4789)

- src/gui/dialogs/multiplayer/mp_join_game.cpp
https://github.com/wesnoth/wesnoth/issues/3715
To reproduce:
1. Player 1 hosts a multiplayer game
2. Player 2 joins the game. Player 2 focuses the chat input
3. Player 3 joins the game. Player 2 is no longer focused on the chat input
Does anyone know why we set keyboard focus here?
https://github.com/wesnoth/wesnoth/blob/6aa6c010e77eeded27dccbb200af06214363937f/src/gui/dialogs/multiplayer/mp_join_game.cpp#L348
I've looked through the commit history and it was there since the original version of the file. This takes away focus from the chat input when a player joins, and doesn't look like it does anything useful. But I could be wrong - I'm pretty new to the codebase.
> Don't lose text focus on mp player join (fixes #3715)

- data/campaigns/Under_the_Burning_Suns/utils/dehydration-utils.cfg
Added `"female^thirst"` and `"female^refreshed"` to the dehydration macro because otherwise it was creating translational problems in some languages. For example, we had to use `теперь легче` (`now it's easier`) phrase in Russian for the word `refreshed` whereas we could just have written `освежился` / `освежилась` if there were gender specific variants (as it is in the IftU translation).
> UtBS: add female variants to dehydration text

- changelog.md
- data/campaigns/Two_Brothers/scenarios/01_Rooting_Out_a_Mage.cfg
- data/campaigns/Two_Brothers/scenarios/02_The_Chase.cfg
@Earth-Cake and @Konrad22 
This is about 10 lines of translatable text, not sure if it's okay to backport to 1.14.
The storyline itself is going to have large changes by 1.18 (maybe 1.16), so I'm not sure if
this will ever be in a stable release. But having had the idea, I thought I'd make a PR for it.
If a player loads a start-of-S02 save without the `who_slew_mordak variable` then it will still
work, showing the "I saw the killing blow with my own eyes" version.
Explanation for what's going on (put in the commit message because this bit is non-canon):
There are some "grey mages" in the Grey Woods, who appear in the Liberty
campaign. Most of the details of these were removed from 1.15, but in 1.14's
Liberty S06 they don't tolerate necromancers. SotA mentions an ancient elvish
civil war …
> AToTB S02: Rewrite the script with the elves thinking the baddies are grey mages

- changelog.md
- data/schema/core/addons.cfg
- src/gui/dialogs/story_viewer.cpp
- src/storyscreen/part.cpp
- src/storyscreen/part.hpp
Prior to this commit, the scaled= attribute was undocumented and had what I assume was a bug - when enabled the image was scaled up to the width and height of the background - not to the same ratio as the background, but to the full size. So if you had a 1000 pixel wide background in an 800 pixel wide window, then scaled=yes meant each journey-marker was an 800 pixel-wide blob.
However, if anyone was using it with background-size images as overlays then this commit will break that usage - that use case is still supported by having multiple [background_layer]s.
Closes #5223, which was a question about whether to fix or simply remove the scaled attribute. Given that [background_layer]scale= and [image]scaled= have different meanings (the background_layer one should and does cause it to be …
> IntroWML code cleanup and fix for [image]scaled attribute

- src/editor/action/mouse/mouse_action_map_label.cpp
- src/editor/action/mouse/mouse_action_map_label.hpp
https://github.com/wesnoth/wesnoth/issues/3302
Currently in the scenario editor, dragging a label causes a crash. I rewrote the dragging functionality to be similar to how we do it with units, hope that's ok
> Fix dragging labels in editor (fixes #3302)

- src/theme.cpp
Detected by CppCheck, the cur_spec_width_ and cur_spec_height_ assignments
were missing from the move-assignment operator.
Trivial change, just wanting to check that the CI passes before merging.
> Fix theme::operator= not copying width or height

- .gitignore
- data/tools/emacs_mode/.gitignore
This is just the gitignore part of #5164; the ignored files are generated and/or binary files that don't belong in the repository.
> gitignore some additional patterns

- data/gui/window/addon_manager.cfg
- src/addon/client.cpp
- src/addon/client.hpp
- src/addon/info.cpp
- src/addon/info.hpp
- src/addon/state.cpp
- src/gui/dialogs/addon/manager.cpp
- src/gui/widgets/addon_list.cpp
Replaced the version display label in the addons manager with a dropdown list displaying all the downloadable versions in descending order with the latest version chosen by default. The selector is frozen for the pubishable addons on their .pbl set version.
The tooltips with useful data like the upload time and the pack size will be added later (not in this pr) as they require some work on the server side.
Tested on my Wesnoth instance.
> Add addon version selection dropdown list

- SConstruct
- source_lists/campaignd
- source_lists/libwesnoth_core
- src/commandline_argv.cpp
- src/commandline_argv.hpp
- src/commandline_options.hpp
- src/filesystem.cpp
- src/filesystem.hpp
- src/server/campaignd/options.cpp
- src/server/campaignd/options.hpp
- src/server/campaignd/server.cpp
- src/server/campaignd/server.hpp
- src/wesnoth.cpp
Adds a basic command line interface to campaignd implementing options to change logging configuration and set the server dir and config file path. This uses Boost.program_options, so some changes to the SCons build recipe were required (CMake links wesnothd and campaignd against Boost.program_options regardless already).
This changes campaignd's startup behaviour slightly so that campaignd ensures that the directory containing the config file exists before doing anything else. Normally this wouldn't be noticeable since the default behaviour continues to be to use `./server.cfg` (pwd should exist, right?), but it's important in the event that the user passes `-c` with a nonexistent path.
Additionally, it moves the argv repackaging logic out of wesnoth.cpp, in particular all the …
> campaignd: Implement basic command line interface

- data/campaigns/The_South_Guard/scenarios/08b_The_Tides_of_War.cfg
- data/campaigns/The_South_Guard/utils/sg_story.cfg
Fixes two minor inconsistencies reported by Konrad2 on discord.
TSG S8b: removed an impossible loss condition.
Epilogue: now correctly identifies Sir Gerricks weapon as a glaive.
> TSG S8b and epilogue: fix minor inconsistencies

- src/wesnoth.cpp
While making it work would be better, this is a minimial change to at least
get the developer back on track instead of wasting time trying to work out
why putting this in a campaign's _main.cfg file doesn't work:
#ifdef ENABLE_CAMPAIGN_TESTS
{./test/}
#endif
Context for this is in #5273. @Pentarctagon thanks for the suggestion, but don't worry I was already trying this and wasting the time before you posted it.
> Show an error message when --preprocess-defines is ignored

- data/gui/window/preferences/05_multiplayer.cfg
Allow users to set chat lines to 0. #1082 fix.
This is really simple fix making me wonder if its correct, I tested it and it seems to work as intended without any bugs. If this wasn't done because of some internal reason or good of players this can be closed.
> Allow users to set chat lines to 0.

- src/server/campaignd/options.cpp
- src/server/campaignd/options.hpp
- src/server/campaignd/server.cpp
- src/server/campaignd/server.hpp
- src/utils/optimer.hpp
Allows reporting the timing for individual requests serviced by campaignd.
> campaignd: Add --timings command line option

- src/saved_game.cpp
- src/saved_game.hpp
This doesn't change the behavior - the changed line is in a conditional block
which tells us exactly which of scenario_id()'s code paths will happen, and it
will still end up using carryover_["next_scenario"]. The change is just making
it consistent with the way that other lines in expand_scenario() find out which
scenario id to use; it's preparing to load the next scenario, so it should use
that scenario's id to load any metadata, not the current scenario's id.
Also, scenario_id() should be const. This helps with refactoring out the
existence of a de-facto singleton instance of saved_game.
> Make saved_game::expand_scenario() look correct, and add a const

- changelog.md
- data/campaigns/Secrets_of_the_Ancients/scenarios/13_Together_Again.cfg
- data/campaigns/Secrets_of_the_Ancients/utils/zombie-utils.cfg
Fixes #5256, which was that `{SAVE_ZOMBIE_LIST rastabahn_zombies}` overwrote
the ardonna_zombies variable.
Move the MERGE_ZOMBIE_LIST code to be next to the LOAD and SAVE code, as any
change to one of these functions should probably be done to all of them.
There's a unit test for this in a commit that's auto-attached itself to #5273, but there isn't the framework support to run it - instead it needs #define statements pushed into the toplevel data/_main.cfg file.
> SotA: Fix Ardonna's zombie list after Rastabahn's scenarios

- changelog.md
- data/campaigns/Sceptre_of_Fire/scenarios/2p5_Reaching_the_Runecrafter.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/4_Gathering_Materials.cfg
SoF S2p5:
-  increased the turn limit by 1 because the scenario felt _very_ tight on time even on easy difficulty (and my changes in 1.15.4 slightly increased minimum travel distance).
- the victory event filters were only triggered by Rugnur's moveto events; this is inconsistent with the scenario objectives and could also lead to costing the player a full turn if Rugnur wasn't the last hero moved to the tunnels end. I changed the event to trigger on any player movement while the heroes reached their destination. Tested to work for all three heroes.
SoF S4:
- reverted my commit from 1.15.4 to fix #5278 
- re-added the functionality of that commit and extended it to also encompass rails
- tested this extensively...
> SoF: fix #5278 in scenario 4 and a small fix for scenario 2p5

- data/campaigns/Secrets_of_the_Ancients/units/SotA_Corpses.cfg
- data/campaigns/Secrets_of_the_Ancients/utils/zombie-utils.cfg
- data/campaigns/Secrets_of_the_Ancients/utils/zombie_recruit_dialog.lua
Instead of trying to concatenate translatable strings, just make a single full
string to be shown in the recruitment dialog. This came from trying to update
the i18n hints, and realising my suggest of making the swimmers "Merfolk" in
f6dc83375 was causing problems when they could also be nagas.
These strings are stored in a variable at the start of the campaign (in
ZOMBIE_INIT), so won't appear when loading an existing save game. This is why
the Lua script keeps some support for the old names (although they're not going
to be translated in that case).
@ivanovic and @shikadiqueen I believe this is better for translators, but is it?
I'd also like to ask and apologise to our Polish translator, who has already translated
the 1.15.6 changes from f6dc83375.
> SotA: Don't concatenate strings in the recruit dialog

- data/test/scenarios/recall_by_unit_tag.cfg
- wml_test_schedule
Answers a question raised in PR #4999; the test also passes on 1.14.
> Add a unit test for the behavior of [unit]id= recalling units

- src/gui/dialogs/addon/manager.cpp
- src/gui/dialogs/addon/manager.hpp
- src/gui/dialogs/preferences_dialog.cpp
- src/gui/dialogs/unit_create.cpp
- src/gui/dialogs/unit_recall.cpp
- src/gui/widgets/addon_list.cpp
- src/gui/widgets/addon_list.hpp
- src/gui/widgets/listbox.cpp
- src/gui/widgets/listbox.hpp
- src/preferences/general.cpp
- src/preferences/general.hpp
This uses MAKE_ENUM for the listbox sort order, so that it can
be serialized to the preferences file.
This is @jostephd 's PR #4409, reopened as a new issue because it has a new author.
Fixes #1090 .
> Addon manager: Save the last sort order in a hidden preference

- src/editor/action/action.cpp
- src/editor/action/action.hpp
- src/editor/action/action_base.hpp
- src/editor/action/action_item.cpp
- src/editor/action/action_item.hpp
- src/editor/action/action_label.cpp
- src/editor/action/action_label.hpp
- src/editor/action/action_select.cpp
- src/editor/action/action_select.hpp
- src/editor/action/action_unit.cpp
- src/editor/action/action_unit.hpp
- src/editor/action/action_village.cpp
- src/editor/action/action_village.hpp
- src/editor/action/mouse/mouse_action.cpp
- src/editor/action/mouse/mouse_action.hpp
- src/editor/action/mouse/mouse_action_item.cpp
- src/editor/action/mouse/mouse_action_item.hpp
- src/editor/action/mouse/mouse_action_map_label.cpp
- src/editor/action/mouse/mouse_action_map_label.hpp
- src/editor/action/mouse/mouse_action_select.cpp
- src/editor/action/mouse/mouse_action_select.hpp
- src/editor/action/mouse/mouse_action_unit.cpp
- src/editor/action/mouse/mouse_action_unit.hpp
- src/editor/action/mouse/mouse_action_village.cpp
- src/editor/action/mouse/mouse_action_village.hpp
- src/editor/controller/editor_controller.cpp
- src/editor/controller/editor_controller.hpp
- src/editor/editor_common.hpp
- src/editor/map/map_context.cpp
When returning std::unique_ptr instead of raw pointers, the return type can't be a co-variant, which is why the clone() functions are all being changed to return the base class.   
Most of the dozen or so uses of editor_action_ptr where replaced with the `auto` keyword, but the reason that I didn't use in it the new code was that I find `std::unique_ptr<editor_action>` quicker to read than remembering if editor_action_ptr is a unique_ptr, a shared_ptr or a plain raw pointer.
> Convert the editor_action framework to use std::unique_ptr instead of raw pointers

- src/server/campaignd/fs_commit.cpp
- src/server/campaignd/fs_commit.hpp
This creates temporary files with the `FILE_SHARE_DELETE` sharing mode on Windows when using `filesystem::atomic_commit`,  thus allowing us to rename them to their final location without having to close them beforehand. Without these changes, campaignd gets really upset when trying to rename files created with `atomic_commit` since Windows by default will deny deletion/renaming of open files.
**UPDATE 2020-11-20:** Now it also makes it so the temporary files overwrite the destination in a POSIX-like fashion by using `SetFileInformationByHandle()`.
~~... Or at least so the theory goes.~~
~~`Wine (5.0) is being temperamental and campaignd doesn't work properly on it, with client requests not going completely through for some mysterious reason, and even occasionally crashing with a …
> campaignd: Fix broken Windows support

- src/tests/test_config.cpp
This commit tests the three config::add_child in src/config.cpp.
The config::add_child are among the most popular methods and
have at least 150 usages.
> Test config::add_child

- data/test/scenarios/test_resistances.cfg
- wml_test_schedule
Add a unit test for resistances (using the standard 6 damage types)
I'm working on a bugfix for [resistance_defaults] (bug #5308), for which the
unit test is going to be out-of-tree until we support some method of testing
it without affecting other tests. The version here is the part of that which
can be in-tree, because it doesn't change the core unit's stats.
This uses some Lua to check that the units have only the expected
resistance types, but I feel there should be a better way to write it.
> Unit test for resistances, could do with Lua advice

- src/lexical_cast.hpp
Essentially, strip the optional const and ptr types from `From` and check it against `char`.
> Refactored use of boost::mpl out of lexical_caster

- src/serialization/preprocessor.cpp
The code handling `#if(n)def` and `#if(n)have` is largely the same in both the normal and the negated paths, making two code paths redundant. This commit unifies each pair as it should have been done from the beginning.
This commit also alters the implementation of `#if(n)ver` very slightly so we do a single char check instead of comparing against a whole string a second time (we definitely don't need to compare the full thing).
> wml/preprocessor: Reduce code duplication in preprocessor conditionals

- src/addon/validation.cpp
- src/addon/validation.hpp
- src/server/campaignd/server.cpp
- src/server/campaignd/server.hpp
This makes it so by default campaignd will reject uploads of existing add-ons without a version bump. A server-side configuration flag (strict_versions) can be optionally enabled to lower the strictness and allow re-uploading the same version -- while still disallowing going backwards.
The reason for making it possible to lower the strictness is that very often while testing campaignd itself it becomes necessary to reupload the same add-on over and over. We don't want to get rid of *that* particular use case.
The server does not currently have a mechanism to advertise the different strictness levels, unfortunately, so clients may in fact need to send a 100 MB rock before finding out it's not good enough for upload. Such is life. This might be solved after #5338 is merged into mainline. …
> campaignd: Add strict version check on uploads

- src/game_initialization/multiplayer.cpp
- src/preferences/game.cpp
- src/preferences/game.hpp
- src/server/wesnothd/server.cpp
- src/server/wesnothd/server.hpp
This is instead of having the server send a message after the login is complete and before the initial gamelist.
Since we wait at the loading screen for the latter (e41534d114437b26c735915f530df2cbc28e6c15), this has needed
to be handled here (2b4ae206ab796934899a628be6d3808a4ccd6c60), but it doesn't make much sense to be handled this
way. Many years ago this message was meant to show up in chat, but after the former change that no longer happened,
(IIRC) and after the latter change it most certainly won't.
This adds a proper [login_response] response from the server on a successful login which includes an `is_admin`
key containing the user's admin status.
> Wesnothd: added a login response, including admin status

- data/gui/window/addon_license_prompt.cfg
- projectfiles/VC16/wesnoth.vcxproj
- projectfiles/VC16/wesnoth.vcxproj.filters
- source_lists/wesnoth
- src/addon/client.cpp
- src/addon/client.hpp
- src/gui/dialogs/addon/license_prompt.cpp
- src/gui/dialogs/addon/license_prompt.hpp
- src/gui/dialogs/addon/manager.cpp
- src/server/campaignd/server.cpp
- src/server/campaignd/server.hpp
- src/tests/gui/test_gui2.cpp
This new commands allows clients to request some identification and feature capability information from the server, intended to allow clients to find out what features the server supports and enable or disable UI elements accordingly while preserving compatibility where desired.
Currently this results in a response like this:
```
[server_id]
version="1.15.7+dev (c7643e0785b-Modified)"
cap="auth:legacy,delta"
[/server_id]
```
More information might be added later, such as a website URL and a link to a web listing for the particular server (e.g. <https://add-ons.wesnoth.org/1.16/>), more details on add-on licensing, or even doing away with the need to send `[request_terms]` before displaying the prompt on the client side.
Note: clients assume `cap=auth:legacy` for servers that can't respond …
> campaignd: [server_id] request

- data/campaigns/Dead_Water/scenarios/04_Slavers.cfg
- data/campaigns/Dead_Water/scenarios/06_Uncharted_Islands.cfg
- data/campaigns/Dead_Water/scenarios/10_The_Flaming_Sword.cfg
I found Dead Water to be too hard for me when I first played it on EASY, so I tweaked the difficulty a bit. I realize that Dead Water is supposed to be one of the harder campaigns, but since my changes are mostly confined to the EASY difficulty, they shouldn't affect the harder ones too much. I'm marking this as a draft since I messed up the pattern that held between certain values that varied by difficulty, so I might want to re-edit to make that consistent (or not, if people don't want that). I might also want to do an entire second playthru where I edit all the scenarios and not just the ones that gave me trouble, so that's another reason for marking this as a draft.
> Tweak Dead Water difficulty

- src/scripting/game_lua_kernel.cpp
- src/units/unit.cpp
- src/units/unit.hpp
There really seems no reason to use this. Also removes a stray use of `boost::copy` in `game_lua_kernel`.
> Unit: removed use of boost::ptr_vector

- data/gui/window/addon_manager.cfg
- src/gui/dialogs/addon/manager.cpp
- src/gui/dialogs/addon/manager.hpp
**N.B. This PR as it is exposes an unusual bug where the link's events (click, mouse motion) reflect the label's **previous** state whenever the selection changes. This results in situations where the label says "None" but it's actually still a clickable URL, or the URL displayed doesn't match the URL that will actually be opened when clicking on it. The PR post here is primarily intended as a test case for @Vultraz.**
The URL widgets (textbox + copy button + browse button) predate the implementation of link-awareness in labels and they sort of got carried over into the new design magically without there being a real need for that. Now that we have a visible cursor change when hovering links it's even less necessary to draw unnecessary attention to the link with a clunky and unintuitive …
> gui2/addon_manager: Replace URL widgets with a single link label

- data/advanced_preferences.cfg
- data/gui/widget/panel_campaign_menu.cfg
- data/gui/widget/panel_listbox_bg.cfg
- data/gui/widget/toggle_button_listbox_header.cfg
- data/gui/widget/toggle_button_listbox_header_bg.cfg
- data/gui/window/campaign_dialog.cfg
- src/actions/attack.cpp
- src/game_initialization/singleplayer.cpp
- src/gui/dialogs/campaign_selection.cpp
- src/gui/dialogs/campaign_selection.hpp
- src/synced_context.cpp
This overhauls the game's Campaigns menu following some of the directions previously suggested in issue #4543.
Requesting reviews from @Vultraz for the UI layout and code changes, @gfgtdf for the engine changes, and @Pentarctagon and @nemaara for the core changes to the single-player campaign UI flow.
* The main area of the dialog is rearranged into four distinct sections:
* The caption row, with the dialog caption and search box
* The main panel, with the list of campaigns on the left, the campaign description and image on the right, and an image background.
* The settings row, with the Modifications, Combat (RNG) and Difficulty menus arranged in that order.
* The control row, with the Play and Cancel buttons.
* The toggle buttons serving as the headers for the list of campaigns have …
> Campaigns menu overhaul

- data/campaigns/Secrets_of_the_Ancients/utils/sota-utils.cfg
The while loop no longer checks for location_found to stop.
location_found gets set inside the while loop and then gets cleared outside of it.
The variable itself can be safely removed, it serves no purpose.
> NEAREST_HEX: variable location_found is no longer used.

- src/filesystem.cpp
The OS-specific error code headers were deprecated in Boost 1.75 (see #5359). This code was first added back in 2013
(see 037e1c12997fe92a2aed36c8b2a05ff31696e8de) but testing now on Windows 10 using Boost 1.73 at least shows that
`no_such_file_or_directory` is returned for both missing files and paths. Seems unnecessary to keep this case around
especially as the header is deprecated going forward.
> FS: removed use of Windows-specific error code

- changelog.md
- data/core/editor/help.cfg
Add help topics for the Editor, as it stands in the 1.14 branch
This commit is on the master branch. There have been no changes at all to the editor documentation in the 1.14 branch, while there have been several updates to the master branch that would be good to backport if the help is displayed in the 1.14 branch - therefore my plan is to get this set of changes reviewed in the master branch, and then simply pull the entire file into the 1.14 branch along with enabling the editor documentation (a small change to data/core/help.cfg, as done in commit ed611f94385f608512da55d691d3c9753240d5d5).
A couple of warnings about the scenario mode being buggy are added to the user-visible text, find these by looking for <bold> tags within the text.
<strike>Original draft PR description follows:
I'm …
> Add help topics for the Editor (as it stands in the 1.14 branch)

- src/game_board.cpp
- src/game_board.hpp
- src/menu_events.cpp
- src/playturn.cpp
- src/server/wesnothd/game.cpp
- src/server/wesnothd/game.hpp
If one client changes the controller type of a side it controls from human -> AI or vice versa, the other clients need to know about it in case there's WML/lua that uses the controller type to determine what to do. This also means that droiding a side you own can now only be done when it's your turn.
Fixes #4996
> Tell other clients about controller type changes from :droid

- src/server/common/server_base.cpp
- src/server/common/server_base.hpp
- src/server/common/simple_wml.cpp
- src/server/common/simple_wml.hpp
- src/server/wesnothd/game.cpp
- src/server/wesnothd/game.hpp
- src/server/wesnothd/server.cpp
- src/server/wesnothd/server.hpp
This removes the use of boost::ptr_vector and replaces it with a vector of unique_ptr<document>. document::clone was also made to return a unique_ptr, which allows for the unification of doc pointer management. We don't have stray document pointers anymore, there's no manual deletion, and it's clear who owns what when (ptr_vector maintains ownership of the pointers it holds, but it's clearer to have everything using unique_ptr).
This also changes usecases of shared_ptr to unique_ptr and makes accommodations accordingly. `handle_player_in_game` and `handle_player_in_lobby` now take a document reference instead of shared_ptrs (they don't do anything with said pointers, and I don't think there are any async ops there that need them to extend the documents' lifetime). The doc send queue also …
> Wesnothd: cleaned up usage of document smart pointers

- changelog.md
- data/core/editor/help.cfg
- data/core/help.cfg
A couple of warnings about the scenario mode being buggy are added to the
user-visible text, find these by looking for <bold> tags within the text.
This takes all the changes to the editor documentation that were made to master
up to and including a4711ebad9. There have been no changes at all to the editor
documentation in the 1.14 branch, while there have been several updates to the
master branch that would be good to backport if the help is displayed in the
1.14 branch - this commit simply pulls the entire file into the 1.14 branch
along with enabling the editor documentation (a small change to
data/core/help.cfg, as done in commit ed611f9438).
The sound source tool isn't mentioned at all in this documentation. There is a
button for it in the 1.14 UI, but that button's only function is …
> [1.14] Re-enable the editor help, add docs about keyboard modifiers and the scenario editor

- changelog.md
- data/schema/units/movetypes.cfg
- src/movetype.cpp
- src/units/types.cpp
The draft version included the testing which I'm going to keep out-of-tree, that's now in my stevecotton:debugging/testing_i2486 branch.
These now work:
[resistance_defaults]
id="special_res_for_test"
default="30"
[/resistance_defaults]
[resistance_defaults]
id="copy_of_arcane"
default="(arcane)"
[/resistance_defaults]
and so do these:
[terrain_defaults]
id="special_terrain_for_test"
[movement_costs]
default="(swamp_water + 1)"
orcishfoot="(vision_costs.swamp_water * 2)"
[/movement_costs]
[/terrain_defaults]
[terrain_defaults]
id="special_terrain_for_test"
[defense]
default="(20 + 7 * movement_costs.special_terrain_for_test)"
[/defense]
[/terrain_defaults]
For [terrain_defaults], I've approached it as a new feature rather than a
simple fix. The subtags now use the same names as the …
> Fix [resistance_defaults] and [terrain_defaults] (fixes #5308)

- src/display.cpp
- src/display.hpp
The main reason for opening the PR is to trigger a CI build; I'm expecting to merge this
within 24 hours unless it gets a negative review comment.
No observers attached themselves to this event. Commit ea257355 removed some
code that should have been triggered by the event, but which now (since
ea257355) uses the "theme_reset" event or update_enabled_buttons() instead.
> Remove the unused completely_redrawn event

- data/core/about_i18n.cfg
wmllint complained:
"../../data/core/about_i18n.cfg", line 1: no textdomain string
Despite [data/core/about_i18n.cfg](https://github.com/wesnoth/wesnoth/blob/master/data/core/about_i18n.cfg) missing an explicit textdomain it appears to contain a number of strings marked for translation and I can see [translations](https://github.com/wesnoth/wesnoth/blob/master/po/wesnoth/af.po#L645) for those strings in the wesnoth textdomain folder.
> Add #textdomain wesnoth to data/core/about_i18n.cfg

- data/core/macros/movetypes.cfg
- data/core/macros/optional_unit_advancements.cfg
Fix wmllint errors:
```
"../../data/core/macros/movetypes.cfg", line 1: no textdomain string
"../../data/core/macros/optional_unit_advancements.cfg", line 1: no textdomain string
```
Add `#textdomain wesnoth` declaration to this two files. As far as I can tell this is just a formality: the files do not contain any strings that need a translation. I can see several other files in the same directory also defining `#textdomain wesnoth` as a formality. Example:
https://github.com/wesnoth/wesnoth/blob/d9ec9b9b55a5063a7709c52e6f28edaedad918a3/data/core/macros/event-utils.cfg#L1
> Add #textdomain wesnoth to two files w/o explicit textdomain

- data/core/units/monsters/Frost_Stoat.cfg
- data/core/units/monsters/Scarab.cfg
- data/core/units/monsters/Wild_Wyvern.cfg
- data/core/units/nagas/Dirkfang.cfg
- data/core/units/nagas/Ophidian.cfg
- data/core/units/nagas/Ringcaster.cfg
This PR fixes the following wmllint errors:
```
"../../data/core/units/monsters/Frost_Stoat.cfg", line 35: double space after sentence end
wmllint: converting ../../data/core/units/monsters/Frost_Stoat.cfg
"../../data/core/units/monsters/Scarab.cfg", line 25: double space after sentence end
wmllint: converting ../../data/core/units/monsters/Scarab.cfg
"../../data/core/units/monsters/Wild_Wyvern.cfg", line 44: description needs translation mark
"../../data/core/units/monsters/Wild_Wyvern.cfg", line 44: double space after sentence end
wmllint: converting ../../data/core/units/monsters/Wild_Wyvern.cfg
"../../data/core/units/nagas/Dirkfang.cfg", line 18: double space after sentence end
wmllint: converting ../../data/core/units/nagas/Dirkfang.cfg
"../../data/core/units/nagas/Ophidian.cfg", …
```
> Fix several wmllint errors in data/core/units

- data/core/units/dunefolk/Sky_Hunter.cfg
Dune Sky Hunter has a {WEAPON_SPECIAL_MARKSMAN} but is missing {NOTE_MARKSMAN}
https://github.com/wesnoth/wesnoth/blob/cd833206b19bc2982e0d914b42fa2e785c7f4608/data/core/units/dunefolk/Sky_Hunter.cfg#L150-L161
This PR adds the missing {NOTE_MARKSMAN}
> Add missing NOTE_MARKSMAN to Dune Sky Hunter

- data/tools/wmllint
This PR fixes a wmllint bug that causes it to complain about fog in maps that contain a fake map border terrain code.
To quote https://wiki.wesnoth.org/TerrainCodeTableWML :
name | string
-|-
Fake Map Border | ^_fme
Fog | _f
This bug causes the following wmllint error:
```
"data/multiplayer/maps/2p_Hornshark_Island.map", line 2: warning, fog or shroud in map file
```
> Fix wmllint confusing fake map border for fog

- data/tools/wmllint
This PR fixes the following wmllint error:
```
../../data/campaigns/Dead_Water/scenarios/06_Uncharted_Islands.cfg, line 22: [advancefrom] needs to be manually updated to [modify_unit_type] and moved into the _main.cfg file
```
A comment containing a string [advancefrom] was causing wmllint to get confused
https://github.com/wesnoth/wesnoth/blob/92fedf8f2aa7a4b83fe0e59e7e0e4f2c16e3c207/data/campaigns/Dead_Water/scenarios/06_Uncharted_Islands.cfg#L22
> Fix wrong comment handling in wmllint

- data/campaigns/Dead_Water/_main.cfg
This PR fixes the following wmllint error:
```
"../../data/campaigns/Dead_Water/_main.cfg", line 76: campaign requires an ID attribute but has none
```
This wmllint error was caused by the fact that the campaign definition is split into two and wmllint is not smart enough to understand that.
https://github.com/wesnoth/wesnoth/blob/92fedf8f2aa7a4b83fe0e59e7e0e4f2c16e3c207/data/campaigns/Dead_Water/_main.cfg#L7-L8
https://github.com/wesnoth/wesnoth/blob/92fedf8f2aa7a4b83fe0e59e7e0e4f2c16e3c207/data/campaigns/Dead_Water/_main.cfg#L74-L76
> Silence wmllint error about a missing campaign id

- data/tools/wmllint
wmllint saw [side] inside a comment and incorrectly assumed it is reading a side definition
This PR fixes the following wmllint errors:
```
"../../data/multiplayer/scenarios/4p_A_New_Land.cfg", line 484: side number 5 is out of sequence (11 expected)
"../../data/multiplayer/scenarios/4p_A_New_Land.cfg", line 488: side number 5 is out of sequence (11 expected)
"../../data/multiplayer/scenarios/4p_A_New_Land.cfg", line 512: side number 6 is out of sequence (11 expected)
"../../data/multiplayer/scenarios/4p_A_New_Land.cfg", line 516: side number 6 is out of sequence (11 expected)
"../../data/multiplayer/scenarios/4p_A_New_Land.cfg", line 540: side number 7 is out of sequence (11 expected)
"../../data/multiplayer/scenarios/4p_A_New_Land.cfg", line 544: side number 7 is out of sequence (11 …
```
> Fix comment parsing in wmllint

- data/campaigns/Descent_Into_Darkness/scenarios/02_Peaceful_Valley.cfg
~~1. According to this https://github.com/wesnoth/wesnoth/commit/6405507b2408fc79511c0210a7a39689d56a4b6f  `[message]` with `speaker=narrator` is supposed to have `image=wesnoth-icon.png`~~
2. https://github.com/wesnoth/wesnoth/blob/75271a824657b0be63369ed4fc55cf0cb3579429/data/tools/wmllint#L2583
> Quote an attribute value

- source_lists/wesnothd
- src/server/common/dbconn.cpp
- src/server/common/dbconn.hpp
- src/server/common/forum_user_handler.cpp
- src/server/common/forum_user_handler.hpp
- src/server/common/resultsets/game_history.cpp
- src/server/common/resultsets/game_history.hpp
- src/server/common/user_handler.hpp
- src/server/wesnothd/server.cpp
- utils/mp-server/table_definitions.sql
---
The server expects a request of (`search_for` optional):
```
[game_history_request]
offset=NN
search_for="a_username"
[/game_history_request]
```
and will send a response with a [game_history_result] per game in the form of:
```
[game_history_result]
game_name="game name"
reload=yes|no
game_start="some timestamp"
scenario_name="some scenario name"
scenario_id="some scenario id"
era_name="some era name"
era_id="some era id"
[player]
name="p1"
faction="drakes"
[/player]
[player]
name="p2"
faction="loyalists"
[/player]
[modification]
name="some mod name 1"
[/modification]
[modification]
name="some mod name 2"
[/modification]
[modification]
id="some_mod_id_1"
[/modification]
[modification]
id="some_mod_id_2"
[/modification]
[/game_history_result]
```
Also, I'm thinking it would make sense …
> Add support for asynchronously querying a player's game history for display on the client.

- .github/workflows/ci-main.yml
- utils/dockerbuilds/CI/Dockerfile-base-steamrt
- utils/dockerbuilds/make_steam_image
- utils/dockerbuilds/steamrt/Dockerfile
The gcc-9 shipped with the Scout runtime forces the use of -static-libstdc++ which is what allows this to work. However, LTO is not yet able to be enabled since as of right now it simply crashes immediately with `free(): invalid pointer`.
---
Note 1: Information about the Scout-provided `gcc-9` comes from https://github.com/ValveSoftware/steam-for-linux/issues/7430#issuecomment-761068435
Note 2: The updated docker image has not yet been uploaded for this PR.
> Use gcc-9 in the Scout runtime instead of gcc-5.

- .github/workflows/ci-main.yml
- CMakeLists.txt
- SConstruct
This then also bumps the minimum GCC version to 7.
> Update to require C++17.

- data/campaigns/Descent_Into_Darkness/scenarios/01_Saving_Parthyn.cfg
- data/campaigns/Descent_Into_Darkness/scenarios/03_A_Haunting_in_Winter.cfg
- data/campaigns/Descent_Into_Darkness/scenarios/04_Spring_of_Reprisal.cfg
- data/campaigns/Descent_Into_Darkness/scenarios/06_Return_to_Parthyn.cfg
- data/campaigns/Descent_Into_Darkness/scenarios/08_Alone_at_Last.cfg
- data/campaigns/Descent_Into_Darkness/utils/macros.cfg
My primary motivation was internationalization: with one added string we can translate all these messages.
```
_ "+$experience_gained| exp"
```
~This PR is currently in draft status pending testing.~ Testing was successful.
> DiD: refactor scripted experience gain

- src/config_attribute_value.cpp
- src/display.cpp
- src/gui/dialogs/lua_interpreter.cpp
- src/server/common/server_base.cpp
- src/server/wesnothd/player.cpp
- src/server/wesnothd/server.cpp
In general I think it's best to use std implementations unless there's a functional or performance reason not to, but also in a few cases this also allows removing the include of lexical_cast.hpp.
> Convert relevant cases of lexical_cast to std::to_string().

- data/campaigns/Descent_Into_Darkness/scenarios/03_A_Haunting_in_Winter.cfg
- data/campaigns/Descent_Into_Darkness/scenarios/07b_A_Small_Favor2.cfg
- data/campaigns/Descent_Into_Darkness/scenarios/07c_A_Small_Favor3.cfg
- data/campaigns/Descent_Into_Darkness/scenarios/09_Descent_into_Darkness.cfg
This PR:
1. adds `#wmllint: display on/off` in several places where line breaks inside messages are clearly intentional
2. Suppresses a wmllint false positive: `unknown 'YOgre2' referred to by id`
> DiD: fix some wmllint errors

- data/campaigns/Descent_Into_Darkness/scenarios/03_A_Haunting_in_Winter.cfg
This is a follow-up for #5442. I have found a better way to suppress the wmllint error.
> Use wmllint: recognize instead of blanket wmllint: ignore in DiD

- data/campaigns/Descent_Into_Darkness/scenarios/08_Alone_at_Last.cfg
This PR silences a wmllint error (unknown 'Jaime' referred to by id) in DiD caused by an intentional scenario design choice.
wmllint checks that every unit referred to in [event], [message] etc is first introduced by [unit], [recall] etc. It does this to catch errors where a scenario author forgets to recall a unit. Jaime is spawned by an easter egg in 07a_A_Small_Favor. Jaime may be on the recall list for this scenario if the egg was triggered and if Jaime survives 07a, 07b and 07c. I assume that in this case the scenario author intentionally counts on the player manually recalling Jaime instead of using [recall].
> DiD: add wmllint: recognize Jaime

- data/campaigns/Descent_Into_Darkness/scenarios/10_Endless_Night.cfg
It is a common mistake to have a unit speak in his/her "die" event (after the death animation is played). Wmllint tries to catch that. In this case, however, Inky does not actually die (as far as the plot is concerned) so it is a perfectly valid stylistic choice for her to make a "Bloub" sound as she dives into the water.
> DiD: suppress: Inky speaks in his/her "die" event rather than "last breath"

- data/campaigns/Eastern_Invasion/utils/animations.cfg
"data/campaigns/Eastern_Invasion/utils/animations.cfg", line 1: no textdomain string
> Fix wmllint error: no textdomain string

- data/campaigns/Heir_To_The_Throne/scenarios/05b_Isle_of_the_Damned.cfg
05b_Isle_of_the_Damned was using black magic: [store_unit] plus [set_variable] to change a unit's id. This confused wmllint. This is also just unnecessarily complicated since there are two more conventional ways to refer to the same unit: role=Advisor and id=$hidden_advisor.id. I chose the first option.
Before applying this PR:
1. Start HTTT
2. Create an easily identifiable unit that matches the role selector (eg Elvish Sylph)
3. Optional: rename the unit
2. :choose_level 05b_Isle_of_the_Damned
3. Save & quit to desktop
4. Apply the PR
5. Load
6. debug kill the liches
7. See that the message works correctly
After applying the PR
1. Start HTTT
2. Create an easily identifiable unit that matches the role selector (eg Elvish Sylph)
3. Optional: rename the unit
2. :choose_level …
> HTTT: don't change unit id

- src/actions/advancement.cpp
- src/actions/advancement.hpp
- src/scripting/lua_unit.cpp
- src/units/filter.cpp
- src/units/unit.cpp
- src/units/unit.hpp
- src/utils/variant.hpp
The upkeep_parser_visitor is still boost::variant-compatible since it's used by
const_attribute_value::apply_visitor, and configs still use boost::variant under the hood.
Additionally, these visitors are used in multiple places, so I can't convert them to lambas in-class.
Finally, I used brace-init for the upkeep types and visitors to make it clearer these are not functions.
> Unit: converted upkeep handling to std::variant

- data/campaigns/Heir_To_The_Throne/scenarios/13_The_Dwarven_Doors.cfg
wmllint tries to detect errors such as a scenario author forgetting to introduce a unit via [recall], [unit] etc and then referencing the unit by id.
Simyr is added to your recall list if you beat 02_Blackwater_Port on HARD by killing the orc leader.
In this instance the scenario author not automatically recalling Simyr is clearly intentional.
> HTTT: add wmllint: recognize Simyr

- data/campaigns/Heir_To_The_Throne/scenarios/22_Return_to_Wesnoth.cfg
wmllint tries to detect errors such as a scenario referencing the unit by id before it is introduced by via [recall], [unit] etc. The definition of "before" wmllint wants to check is chronological: "does an event that introduces a unit happen before an event that references it?", but the current implementation cheats by simply checking if the definition textually precedes the reference.
22_Return_to_Wesnoth contains two prestart events. The first prestart event defines an event that triggers on turn 4. The second prestart event introduces Kalenz, Delfador and Li'sar.
I could merge the prestart events and reorder the code to avoid the wmllint error, but since it does not actually make the code easier to read I chose a less disruptive option of simply adding "wmllint: recognize".
> HTTT: add wmllint: recognize Kalenz Delfador Konrad Li'sar

- data/campaigns/Sceptre_of_Fire/utils/bigmap.cfg
- data/campaigns/Secrets_of_the_Ancients/utils/terrain_graphics.cfg
- data/campaigns/The_Rise_Of_Wesnoth/units/Kalian.cfg
- data/campaigns/World_Conquest/_main.cfg
- data/campaigns/World_Conquest/config.cfg
- data/campaigns/World_Conquest/era/campaign/heroes.cfg
- data/campaigns/World_Conquest/era/era.cfg
- data/campaigns/World_Conquest/resources/data/artifacts.cfg
- data/campaigns/World_Conquest/resources/data/training.cfg
- data/campaigns/World_Conquest/resources/resources.cfg
- data/campaigns/World_Conquest/scenarios/WC_II_scenario.cfg
Ibanovic wants all #textdomain declrations in line 1: c10cf2b68b6
Several files were missing an explicit textdomain declaration.
Three of them actually have translated strings that defaulted to "wesnoth" textdomain:
- data/campaigns/World_Conquest/resources/data/training.cfg
- data/campaigns/World_Conquest/era/campaign/heroes.cfg
- data/campaigns/World_Conquest/scenarios/WC_II_scenario.cfg
> wmllint: fix textdomain errors

- data/campaigns/Legend_of_Wesmere/scenarios/chapter3/09_Bounty_Hunters.cfg
- data/campaigns/Legend_of_Wesmere/scenarios/chapter4/13_News_from_the_Front.cfg
Fix preprocessor warning:
warning preprocessor: Redefining macro LEAVE_BEHIND_L3 without explicit #undef at campaigns/Legend_of_Wesmere/scenarios/chapter4/13_News_from_the_Front.cfg:105
included from campaigns/Legend_of_Wesmere/_main.cfg:18
included from _main.cfg:38
previously defined at campaigns/Legend_of_Wesmere/scenarios/chapter3/09_Bounty_Hunters.cfg:240
included from campaigns/Legend_of_Wesmere/_main.cfg:17
included from _main.cfg:38
> LOW: Don't forget to undefine local macros

- data/campaigns/Heir_To_The_Throne/utils/httt_utils.cfg
This PR fixes the following wmllint errors:
"data/campaigns/Heir_To_The_Throne/utils/httt_utils.cfg", line 697: unit declaration without side attribute
"data/campaigns/Heir_To_The_Throne/utils/httt_utils.cfg", line 712: unit declaration without side attribute
"data/campaigns/Heir_To_The_Throne/utils/httt_utils.cfg", line 727: unit declaration without side attribute
As far as I understand this should be safe - side defaults to 1 anyway.
> Add side=1 in httt_utils.cfg to appease wmllint

- src/server/wesnothd/game.cpp
- src/server/wesnothd/game.hpp
- src/server/wesnothd/player_connection.hpp
- src/server/wesnothd/server.cpp
- src/server/wesnothd/server.hpp
Use `player_iterator` typedef instead of `socket_ptr` to refer to players once they're logged in. `player_iterator` points directly to player's record in `player_connections_` container allowing for access to any stats associated with player without searching by socket. Also this paves way to potentially remembering disconnected players for purpose of implementing player reconnect feature.
Interface conventions:
- `player_iterator` arguments should always refer to player existing in `player_connections_`. Potential past-the-end iterators should be checked for before passing the `player_iterator` to other functions.
- `utils::optional<player_iterator>` should be used in cases where actual player may not exist.
> Make wesnothd use iterators instead of socket_ptrs to keep track of players

- data/campaigns/Eastern_Invasion/scenarios/01_The_Outpost.cfg
- data/campaigns/Eastern_Invasion/scenarios/02_The_Escape_Tunnel.cfg
- data/campaigns/Eastern_Invasion/scenarios/12_Evacuation.cfg
- data/campaigns/Eastern_Invasion/scenarios/17b_Weldyn_Besieged.cfg
These are mostly just changes to gold/income/turns values, so they should be pretty safe to merge. Note that I originally developed these changes against 1.14, and @nemaara has already made some of her own changes to Eastern Invasion as part of 1.15, so I just dropped the parts that didn't apply anymore, or that didn't make sense anymore. This means I haven't actually tested these changes in this form, just in the form that appears in [https://github.com/cooljeanius/wesnoth_mods/tree/master/campaigns/Eastern_Invasion](https://github.com/cooljeanius/wesnoth_mods/tree/master/campaigns/Eastern_Invasion). They should be similar enough that that shouldn't make much of a difference, though.
> Tweak Eastern Invasion difficulty

- src/build_info.cpp
- src/build_info.hpp
- src/gui/dialogs/game_version_dialog.cpp
- src/wesnoth.cpp
This commit also adds this information to the startup banner on stderr, the output of --report, and the Game Version dialog's main UI and clipboard report.
(See also commits 9b1ea3078da2b2d874774bc631648d90a0f78433 and 15356f1db67b705686462bb077d0a39bc1f78791 previously merged.)
> bi: Use Boost.Predef to detect and expose the build arch

- data/tools/wmllint
> I'm not convinced this test is doing anything useful. I really doubt this ever caught an error. I'd rather remove it.
@soliton- in https://github.com/wesnoth/wesnoth/pull/5479#issuecomment-763696081
While I'm at it I also removed an orphaned comment.
> wmllint: remove check for nonstandard word-wrap style

- data/tools/wmllint
As far as I can tell this lines do nothing.
1. `file_handle = None` is NOT how to close a file in python
2. The file handle is already closed due to `with open() as file_handle:`
> wmllint: cleanup two useless lines

- data/tools/wmllint
The following line was causing a wmllint error because it contains _s:
```
Irs, book_start Icr^Ii, Irs
```
```
"../../data/campaigns/Descent_Into_Darkness/maps/07c_A_Small_Favor3.map", line 10: warning, fog or shroud in map file
```
> wmllint: Ignore location_id when checking for shroud and fog

- data/campaigns/Descent_Into_Darkness/scenarios/07b_A_Small_Favor2.cfg
- data/campaigns/Descent_Into_Darkness/scenarios/07c_A_Small_Favor3.cfg
- data/campaigns/Descent_Into_Darkness/scenarios/09_Descent_into_Darkness.cfg
- data/campaigns/Eastern_Invasion/scenarios/17a_The_Duel.cfg
- data/campaigns/Heir_To_The_Throne/scenarios/07_Crossroads.cfg
- data/campaigns/Heir_To_The_Throne/scenarios/19c_Cliffs_of_Thoria.cfg
- data/campaigns/The_Rise_Of_Wesnoth/scenarios/03_A_Harrowing_Escape.cfg
- data/campaigns/The_Rise_Of_Wesnoth/scenarios/04a_The_Swamp_of_Esten.cfg
- data/core/help.cfg
- data/core/macros/ai_controller.cfg
- data/multiplayer/scenarios/2p_Dark_Forecast.cfg
- data/multiplayer/scenarios/ANL_utils/ANL_leader_options.cfg
- data/multiplayer/scenarios/ANL_utils/ANL_research_options.cfg
https://github.com/wesnoth/wesnoth/pull/5481 removed the check that made wmllint: display on and wmllint: display off necessary. This PR removes now redundant wmllint comments.
```sh
find ./data/ -name '*.cfg' -exec sed -ri '/^ *# *wmllint *:? *display *(on|off) *$/d; s/ *# *wmllint *:? *display *(on|off) *$//' '{}' ';'
```
> Cleanup wmllint: display on/off

- data/campaigns/World_Conquest/resources/data/training.cfg
World_Conquest has a bunch of campaign-specific tags and attributes. This was causing wmllint to produce spurious errors (see below).
@soliton- suggested (https://github.com/wesnoth/wesnoth/pull/5484#issuecomment-763831678):
> support a wmllint directive to disable checks for a complete dir or so so we can exclude lua heavy stuff like WC
I think it would be easier to add `markcheck off`.
"data/campaigns/World_Conquest/resources/data/training.cfg", line 305: info should not have a translation mark
"data/campaigns/World_Conquest/resources/data/training.cfg", line 519: info should not have a translation mark
"data/campaigns/World_Conquest/resources/data/training.cfg", line 533: info should not have a translation mark
"data/campaigns/World_Conquest/resources/data/training.cfg", line 549: info …
> wc: markcheck off due to campaign-specific attrs

- data/core/editor/help.cfg
I see no "User Maps" under the list box when loading previously saved map, but the "Custom Maps" appears here.
> change User to Custom to unify the help with the game

- data/core/editor/help.cfg
This corrects a pair of editing errors, thanks to @celerini for reporting them.
This is targeting the 1.14 branch, I'll cherry-pick to master when it merges.
> Editor help: make the named areas topic visible, make "to load ..." translatable

- data/tools/wmllint
wmllint should not search for wml tags and keys inside [lua].
I caught it trying to add a translation mark in 23_Test_of_the_Clans inside a [lua] tag.
> wmllint: Stop looking for wml tags inside [lua]

- data/lua/wml-tags.lua
x,y were both binding to whole table instead of their expected values
#5519 should now be solved, although there still might be problem with location_id in teleport code
> Fixed unstore_unit lua code (issue #5519)

- data/campaigns/Under_the_Burning_Suns/scenarios/08_Out_of_the_Frying_Pan.cfg
- data/campaigns/Under_the_Burning_Suns/utils/terrain.cfg
- data/campaigns/Under_the_Burning_Suns/utils/terrain_graphics.cfg
- data/core/terrain-graphics.cfg
- data/core/terrain-graphics/new-macros.cfg
Fixes #5539
Makes the flood water in Sc8 have a fading overlap on floor terrains, instead of the usual banks and edges.
I think it works based on what I see in the editor, but still need to test in scenario.
I'm not sure if this should be back-ported to BfW 1.14, or maybe it's better to just remove the custom rules and live with the default transitions.
> UtBS - new terrain-graphics rules for flood water

- changelog.md
- src/units/frame.cpp
**Note:** I have tested the patch against the bug's test case, but I need to go over my own files to see if I can find a more elaborate test case involving progressive parameters.
It was already considered for registering halos, just not for rendering regular frames. This commit touches the halo code a little so we don't need to call get_zoom_factor() multiple times per frame.
Closes #5508.
> Take display zoom into account when rendering unit animation frames

- data/lua/wml-flow.lua
- data/lua/wml-utils.lua
- data/lua/wml/find_path.lua
- data/lua/wml/harm_unit.lua
- data/lua/wml/modify_unit.lua
- data/lua/wml/random_placement.lua
- data/test/scenarios/test_scoped_vars.cfg
- wml_test_schedule
With this you no longer have to worry about forgetting to end the variable scope - Lua will do it for you automatically. This is a PR because I've only done a basic smoke test (making sure there are no errors when starting a game; for this test I chose Aethermaw). I didn't confirm that the variable is correctly set and unset, though I have no reason to expect it wouldn't be; I did do some testing to verify how to-be-closed variables work.
> Use to-be-closed variables to scope WML variables in tag definitions

- src/floating_textbox.cpp
- src/floating_textbox.hpp
- src/play_controller.cpp
- src/play_controller.hpp
Now it's possible to browse the command history with up/down keys in in-game consoles such as used by debug mode, ai and search floating textboxes. It stores all the entered commands in chronological order, but already existing items will be moved to the end instead. If the player jumps to the previous command with some unenterred text in the textbox, it will also be stored. Chat messages are not stored like this to avoid spam.
I added a video with a little showcase below.
Closes #1542 .
https://user-images.githubusercontent.com/14872007/108371136-7e5c0300-720e-11eb-9039-bea0882c196d.mp4
(or this link if it doesn't show on github)
https://drive.google.com/file/d/18oYwpW3vEs2VP5OOh2iAXgyiS2Pjb-Er/view?usp=sharing
> Command history for in-game consoles

- src/ai/default/ca.cpp
Previously, trying to move the leader toward an occupied keep hex caused an E_NOT_REACHED_DESTINATION error.
Fixes #5345
> move_leader_to_keep CA: prevent error message

- data/ai/lua/ai_helper.lua
- data/ai/lua/ca_castle_switch.lua
- data/ai/lua/generic_recruit_engine.lua
- data/ai/micro_ais/cas/ca_fast_combat.lua
- data/ai/micro_ais/cas/ca_fast_combat_leader.lua
- data/campaigns/Heir_To_The_Throne/scenarios/17_Scepter_of_Fire.cfg
- data/lua/wml-tags.lua
- data/lua/wml/find_path.lua
- src/scripting/game_lua_kernel.cpp
This is what I have so far on the matter... I _think_ it addresses every possible case, but I'm quite not sure and I haven't yet tested it.
This includes an API change, deprecating the use of `viewing_side=0` to specify that fog, shroud, and hiding are ignored. Instead, you now use `see_all=true` for this purpose. The reason for this can be found in the issue discussion.
> Fix segfaults and a few other issues in wesnoth.find_path

- changelog.md
- data/gui/window/preferences.cfg
- data/gui/window/preferences/01_general.cfg
- data/gui/window/preferences/03_display.cfg
- data/gui/window/preferences/05_multiplayer.cfg
The hardcoded size of the window was too small for the large fonts on HDPI
displays, this changes to almost-automatic sizing. It leaves an upper limit for
the height of 80% of the main window size, so that there's a border at top and
bottom. Fixes #5185
Buttons that were placed at the bottom of pages move up so that they aren't
too far from the other controls. The sub-tab-selector buttons on the
multiplayer tab move above the sub-tabs themselves.
With HDPI text, the checkboxes are placed a little too high to align with
the font, but that's a cosmetic detail; this commit fixes the usability issue.
> Make the preferences window big enough for HDPI fonts

- data/campaigns/Sceptre_of_Fire/scenarios/4_Gathering_Materials.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/6_Towards_the_Caves.cfg
This is my attempt to apply patches from [my general mods collection](https://github.com/cooljeanius/wesnoth_mods/tree/master/campaigns/Sceptre_Of_Fire). Basically, I needed more turns in Gathering Materials, and I needed to make it easier for Alanin to escape in Towards the Caves. Tested on 1.14, not on 1.15 though.
> Edit Scepter of Fire difficulty

- src/game_config_manager.cpp
As of PR #4963, the engine ignores all global tags defined by add-ons that are not active, that is, that are not used in the current game.  Whether an add-on counts as active is determined based on a list of possible tags with add-on ids.  The [test] tag is not included in this list, resulting in test scenarios in add-ons not working any more.
> Add [test] to list of tags with add-on id

- changelog.md
- src/gui/dialogs/game_load.cpp
- src/gui/dialogs/game_load.hpp
Re-add the popup that appears when "Load" is pressed on the title screen if
there are no files, but now check for files from previous versions too.
Improve handling of switching from a version with files to a version without
files, disabling buttons on the load dialog when there are no files in the
current directory.
This adds a \todo about the error path at the start of evaluate_summary_string,
this path is reached by creating empty files in the save dir. The dialog's state
is reasonable, so it seemed a low priority and I don't want to introduce new
bugs by refactoring this path now.
Fixes #5517
> Improve the Load dialog's UX when there are no save files or corrupted files

- changelog.md
- src/units/types.cpp
This is preparation for backporting 0ba433203e, with the idea that both sets
of names will be supported in both branches as part of fixing #5308.
No deprecation messages are added. While config::get_attribute_value() has a
config::get_old_attribute_value(), there isn't currently a similar utility for
config::child(); maybe I should add one now, but it feels too large a change
for a backport.
> Support [terrain_defaults]'s original subtag names

- src/units/types.cpp
In movetype::write, the children might not be created if that child has an
empty config; there might be no child at all for movetypes such as "none". The
movetype "none" is a real movetype defined in units.cfg for units that
shouldn't be able to move.
The original_cfg local variable was only used once anyway, removing it and the
comment made the code clearer.
This wasn't caught in the 1.15 testing, but with 1.14 it resulted in a
"mandatory WML child missing" warning.
> Handle empty children in patch_movetype

- changelog.md
- data/test/scenarios/test_resistances.cfg
- src/movetype.cpp
- src/units/types.cpp
- wml_test_schedule
The bug introduced in fcd0ceda is fixed by ensuring that movetype::merge() is
called with the strings "movement_costs", "vision_costs" and "jamming_costs"
instead of "movement", "vision" and "jamming". Closes #5308.
Both [terrain_defaults][movement] and [terrain_defaults][movement_costs] are
supported and equivalent, as added to the master branch in 3522eb2c.
These now work again:
[resistance_defaults]
id="special_res_for_test"
default="30"
[/resistance_defaults]
[resistance_defaults]
id="copy_of_arcane"
default="(arcane)"
[/resistance_defaults]
[terrain_defaults]
id="special_terrain_for_test"
[movement]
default="(swamp_water + 1)"
orcishfoot="(swamp_water * 2)"
[/movement]
[/terrain_defaults]
Formulas can now access other parts of the movetype too, as this allowed the
code to be the same …
> [1.14] Fix [resistance_defaults] and [terrain_defaults] (issue #5308)

- SConstruct
- source_lists/campaignd
- src/SConscript
- src/addon/validation.cpp
- src/addon/validation.hpp
- src/server/campaignd/server.cpp
- src/server/campaignd/server.hpp
- src/server/common/dbconn.cpp
- src/server/common/dbconn.hpp
- src/server/common/forum_user_handler.cpp
- src/server/common/forum_user_handler.hpp
- src/server/common/user_handler.hpp
- utils/mp-server/table_definitions.sql
Also uses that support to insert data into the new "addon_info" table when an add-on is uploaded as well as adds validation of the topic_id to ensure it's a valid int before inserting.
One use case for this would be to be able to check how many people are using outdated add-ons when playing online multiplayer on the primary official server.  Others would be to let players know when they create/join a game with an outdated version of one or more add-ons that will be used as well as adding a way to open an add-on's feedback thread in their browser from the current game they are playing.
Addresses #5060
Addresses #5061
---
Implementing #5065 would be dependent on whenever #5567 is merged, since doesn't make sense to implement client-side hashing only to soon remove it when TLS support is …
> Adds optional database support to campaignd.

- changelog.md
- src/savegame.cpp
This connects to issue #2710, although the main reasoning about it is in #5517.
The difficulty balance isn't the only problem with loading old saved games, but
it's a simple example to explain.
This warning is intended for the change between 1.14 and 1.16, but will be shown
to anyone loading 1.15.x saves into 1.15.y - that's something that they should
expect in a dev branch.
> Unsubtly warn about subtle problems loading saved games from old versions

- src/attack_prediction.cpp
The corrections applied in calculate_probability_of_debuff() are already taken into account in the main attack outcome calculation for being slowed.  They do not need to be applied again, that only needs to be done for being poisoned.  Doing this for being slowed also can cause an assert, such as the one reported in issue #5533 (and probably also the one in issue #5002).
Fixes #5533
Note that this is a PR against Wesnoth 1.14, because that's where the issue was reported.  It should be ported to master also.
I would like to merge this tomorrow, so that it gets a week of testing before the 1.14 and 1.15 releases, just in case there are any adverse side effects.
> Fix attack prediction assert

- doc/man/wesnoth.6
- run_wml_tests
- src/commandline_options.cpp
- src/commandline_options.hpp
- src/game_launcher.cpp
- src/log_windows.cpp
- src/log_windows.hpp
- src/wesnoth.cpp
This is a bunch of updates to the WML test runner that I did while trying to figure out the test failures in #4580. The general motivation is that I was unable to get the output from the test that failed or even identify _which_ test that failed when running on Windows.
The main purpose of this PR is to verify that the runner still works on POSIX systems, but I'm also open to review comments.
* The first commit just fixes the new command-line argument I recently added on master - apparently I forgot to test it and it didn't work, just crashed the runner.
* In order to reduce clutter when displaying test output, I've added a `--nobanner` flag to Wesnoth. This could be probably achieved with `tail` or similar tools on POSIX systems, but that won't work on Wesnoth. The flag suppresses all or …
> Some enhancements to the WML test runner

- src/font/text.cpp
There's a long-standing issue with our usage of Cairo/ClearType on Windows that creates very noticeable chromatic aberration of rendered text (see the visual reference below) due to Wesnoth not respecting the industry recommendation of not using subpixel hinting when rendering text on transparent surfaces -- the latter being quite unfortunately something we always do because `pango_text` only generates transparent surfaces and most of the time has its output blitted onto more transparent surfaces.
This patch disables subpixel hinting, causing Cairo to render wispy text because of gamma issues when not rendering text directly onto an opaque surface. However, it also makes the implementation of pango_text overblend all transparent pixels to compensate like it was previously done before the …
> font: Work around chromatic aberration issue with Windows ClearType

- data/campaigns/Eastern_Invasion/scenarios/01_The_Outpost.cfg
- data/campaigns/Eastern_Invasion/scenarios/02_The_Escape_Tunnel.cfg
EI S1: Update objectives to reflect when an early finish bonus is given.
EI S1, S2: Fix typos
EI S2: Lift shroud (but not fog) around the amulet. Gives the player a hint to
explore around the amulet, despite the objectives saying "Get moving quickly",
which discourages that in the first playthrough. This might also prevent
players interpreting the revealed path directly through the trolls as the
suggested path through the level. By putting one of the dots in an obvious
dead-end, it's less of a surprise that the path shown by the other dots leads
to getting trapped between trolls and undead.
Part of #4145
> EI: minor fixes for S1 and S2

- data/campaigns/Eastern_Invasion/scenarios/07a_The_Crossing.cfg
- data/campaigns/Eastern_Invasion/scenarios/10_Lake_Vrug.cfg
- data/campaigns/Eastern_Invasion/scenarios/11_Captured.cfg
S7a: Improve how side 2 makes its entrance. Don't use [hide_unit], that's not what it's for.
EI S10: Make recall undoable: this event shows a warning about recalled units having low / no movement through mountainous terrain.
EI S10: Switch shroud to fog. The scenario was otherwise generally unwinnable on the first attempt. Although the extra turns in added in ab900b0093503809d91fc9c48ead19e388b63fe7 help with that, it's still worth changing to fog instead of shroud.
EI S11: Annotate bonus objectives as such.
Part of #4145.
> EI S7a S10 S11: Minor fixes

- utils/git_export_campaign
As with git-subtree, it creates reproducible SHA1 ids for the new branch, the
pre-removal history of An Orcish Incursion will appear as the branch with head
d45d9e7562e407d3b934c0eb88b40c891a963942.
Added to the utils directory rather than data/tools, as it makes no sense to have
without the full Git history.
> git-subtree like tool for exporting campaigns

- src/actions/attack.cpp
- src/ai/default/aspect_attacks.cpp
- src/gui/dialogs/attack_predictions.cpp
- src/units/abilities.cpp
- src/units/attack_type.cpp
- src/units/attack_type.hpp
- src/units/udisplay.cpp
When I was looking at the special weapons extension to [abilities] tags, I didn't understand the concept of lists at first, until someone added the .append function to add a list to a list. other, but I kept the names I used for the functions. Now that this work is completed, I would like the function calls to find their original names (get_specials and get_special_bool) among other things to clarify the reading for a developer.
> Rename functions managing special weapons to improve readability for engine devellopper

- data/campaigns/The_South_Guard/scenarios/05_Choice_In_The_Fog.cfg
TSG S05: Fix Urza's upkeep when taking the bandit branch. The `[trait]` shouldn't be inside a `[modifications]` block, as explained in #4137.
<strike>TSG S02: Simplify [store_unit]+[foreach] to [modify_unit]</strike>
> TSG S05: Fix use of [modify_unit]

- src/desktop/version.cpp
(tl:dr "run ci tests for me" pr)
This allows us to obtain the OS version without blocking for a long amount of time waiting for lsb_release (which is deprecated anyway).
The parsing is intentionally basic.
> desktop/version: Use systemd's os-release file if available

- data/campaigns/Under_the_Burning_Suns/scenarios/01_The_Morning_After.cfg
They were both placed on the same hex, which meant the engine moved one of
them a hex north-west, into the water.
Fixes #5632
> UtBS S01: Spawn the mystics on the island, not in the lake

- changelog.md
- data/test/scenarios/test_effect_on_vision.cfg
- src/units/unit.cpp
- wml_test_schedule
Fixes #5638 by correcting a cut & paste typo in 66a282a96be288a284d12a71625868cee5b2dc6b.
There's two commits here, the first of which is unit tests that are also in PR #5434. I'm not sure if it's too much testing for the amount of C++ changed in this PR, but it includes the framework I needed to test this code...
> Fix units that should have zero max mp being given one mp

- changelog.md
- src/formula/function.cpp
- src/formula/function.hpp
To report the WFL call stack in the event of errors, a static stack is used to
record that call-stack. This wasn't thread-safe, and it intermittently crashed
when the game config was movetype patching (the other WFL thread involved is
the GUI2 layout code).
Also a Rule of Three fix for the call_stack_manager class. While this wasn't
the cause of the crash, it could also have lead to a call_stack.pop_back() on
an empty stack.
Fixes #5629.
> [1.14] Make WFL's error-reporting machinery thread_local

- changelog.md
- src/formula/function.cpp
- src/formula/function.hpp
To report the WFL call stack in the event of errors, a static stack is used to
record that call-stack. This wasn't thread-safe, and it intermittently crashed
when the game config was movetype patching (the other WFL thread involved is
the GUI2 layout code).
Also a Rule of Three fix for the call_stack_manager class. While this wasn't
the cause of the crash, it could also have lead to a call_stack.pop_back() on
an empty stack.
Fixes #5629.
> [1.15] Make WFL's error-reporting machinery thread_local

- data/core/units/undead/Corpse_Necrophage.cfg
I can't find "fratures" in any dictionaries. I'm guessing the author intended to say "creatures"
> Fix a typo in data/core/units/undead/Corpse_Necrophage.cfg

- data/multiplayer/scenarios/2p_Dark_Forecast.lua
Adjusted the weather change effect from `side 3 turn` to `side 1 turn`. Side 1 is never empty so it would bypass the side 3 as empty cheat which impeded weather change.
Fixes #5653 
Also, I have playtested under the _cheat active_ conditions and found the weather change to working now.
> Fix for weather change cheat in dark forecast

- data/gui/window/addon_auth.cfg
- projectfiles/VC16/wesnoth.vcxproj
- projectfiles/VC16/wesnoth.vcxproj.filters
- source_lists/wesnoth
- src/addon/client.cpp
- src/gui/dialogs/addon/addon_auth.cpp
- src/gui/dialogs/addon/addon_auth.hpp
- src/gui/dialogs/addon/manager.cpp
- src/tests/gui/test_gui2.cpp
This is an alternative to needing to store the plaintext password in the _server.pbl.
> Add a prompt to allow entering an add-on's password at upload time.

- src/font/text.cpp
- src/font/text.hpp
The single-character insertion seems unlikely to be used in future. While
pango_text isn't a singleton, a few shared instances are created and then used
in a singleton-like way, with each caller assuming that it received it in an
unknown state and always calling set_text(), set_font_size(), set_font_style(),
etc.
This is a subset of the changes in #5617.
> pango_text: remove unused force options and single-character insertion

- data/ai/micro_ais/scenarios/animals.cfg
This adjusts to the change in e7b5996e988747c2b590852b4b461abe48857526.
The micro ai itself is unchanged, it's still controlled by `tusker_type` and
`tusklet_type`, it simply needed the new unit ids to be used in this scenario.
The demo can be run with `wesnoth -t animals`.
> Update the animals Micro-AI demo with boars and piglets

- data/multiplayer/scenarios/2p_Dark_Forecast.cfg
This PR makes Dark Forecast "passable" at default difficulty for 2 player mode. Initially, it was only passable if it was one-player-mode as one player could have 11 villages active and could get a good army built prior to the final wave.
2 player mode suffers from lack of resources to replace losses and would be unwinnable in some cases.
The change which has been made is that in 2-player-mode, the `village_support` has been set to 2.
The only 2 cases where it was won in 2 player mode was when the players were of _exceptionally high skill level_ but average skill-levelled players have yet to even win.
The enemy wave strength has been left untouched as the players can stand a chance now.
This PR fixes #5651 
Video Replays:
https://www.youtube.com/watch?v=w3VrWuS-IoU (Default Era) …
> [MP] 2p - Dark Forecast scenario is now winnable in 2-player mode.

- changelog.md
- data/gui/window/debug_clock.cfg
This is the only widget in mainline using GUI2's `[draw][circle]` tag. I'm
currently working on a change to the C++ `text_shape` class, and want to
be able to regression-test the placement of `[circle]`s after that change.
I'd be okay with deprecating both `[circle]` and `[round_rectangle]` as neither
seems to be used elsewhere, but this close to feature-freeze I'd prefer to keep
them in 1.16 rather than suggest removing them now.
To see the widget, start the game with `wesnoth --clock`, and then click the
button underneath "Quit" on the main menu.
Before and after:
> Make the debug clock look right

- data/core/units/monsters/Giant_Scorpion.cfg
This PR restores the broken Help entry links for the unit and its sand scuttler variation.
Fixes #5676
> Fix for Giant Scorpion having an empty variation name.

- src/actions/attack.cpp
Poison is added to the attack damage when comparing attacks by the same unit with different weapons, but it should only be counted as a bonus if the enemy survives, otherwise it serves no purpose.
> Fix better_attack evaluation for poison attacks

- src/game_events/conditional_wml.cpp
The current implementation technically allows for there to be multiple comparison attributes present and it will return false if any of them are false or return true if all of them are true. This changes the implementation to only check the first comparison attribute found and return true or false based on that check, which is how the [variable] tag is documented as working on the wiki.
> When checking [variable] comparison attributes, return after checking the first one.

- src/gui/core/canvas.cpp
- src/gui/core/canvas.hpp
The renderer only needs to exist during draw(). The old implementation kept the
old renderer until the next call to draw(), but would then usually destroy the
old one and create a new one.
Canvas kept separate lists of what had already been drawn and what needed to be
drawn, but whenever changes happened all of the drawn_shapes_ were put back
into shapes_. No point in having two separate lists.
The list of shape needs pointers to support polymorphism, but doesn't need
shared_ptrs.
This is some cleanup to make #5681 slightly smaller.
> Simplify canvas: renderer lifetime and only one list of shapes

- data/core/units/dunefolk/Blademaster.cfg
- data/core/units/dunefolk/Captain.cfg
- data/core/units/dunefolk/Cataphract.cfg
- data/core/units/dunefolk/Firetrooper.cfg
- data/core/units/dunefolk/Harrier.cfg
- data/core/units/dunefolk/Luminary.cfg
- data/core/units/dunefolk/Marauder.cfg
- data/core/units/dunefolk/Sky_Hunter.cfg
- data/core/units/dunefolk/Spearmaster.cfg
- data/core/units/dunefolk/Warmaster.cfg
- data/core/units/dunefolk/Wayfarer.cfg
- data/core/units/dunefolk/Windbolt.cfg
- data/core/units/monsters/Rock_Scorpion.cfg
- data/core/units/monsters/Scarab.cfg
- data/core/units/nagas/Ophidian.cfg
- data/core/units/nagas/Ringcaster.cfg
- data/core/units/nagas/Sicarius.cfg
- data/core/units/nagas/Zephyr.cfg
- data/core/units/undead/Corpse_Soulless.cfg
- data/core/units/undead/Corpse_Walking.cfg
- data/core/units/wose/Wose_Sapling.cfg
- data/core/units/wose/Wose_Shaman.cfg
Dunefolk:
Dune Blademaster gold cost changed from 52 to 57.
Dune Captain alignment changed from liminal to lawful.
Dune Cataphract gold cost changed from 61 to 62.
Dune Firetrooper gold cost changed from 50 to 41.
Dune Harrier gold cost changed from 46 to 47.
Dune Luminary gold cost changed from 53 to 38.
Dune Maruder gold cost changed from 52 to 60.
Dune Sky Hunter gold cost changed from 47 to 51.
Dune Spearmaster gold cost changed from 51 to 57.
Dune Wayfarer gold cost changed from 52 to 55.
Dune Windbolt gold cost changed from 50 to 49.
Dune Warmaster gold cost changed from 56 to 57, hp changed from 57 to 59, alignment changed from liminal to lawful.
Naga Ophidian gold cost changed from 24 to 22, melee damage changed from 7 to 6, ranged damage changed from 10 to 12.
Naga Ringcaster …
> Balance changes for version 1.15.12

- data/scenario-test.cfg
Make "show attack range" not overwrite the array for cleaning up
the "show movement range" command's display.
Add a label and tooltip about the enemy unit with jamming.
The new option shows the result of [store_reachable_locations]range=vision.
There are known issues (in #4179) with that for:
* units with vp different to mp
* units with vision costs different to movement costs
* jamming by enemy units
> scenario-test: Add a right-click "show vision range" option

- data/test/scenarios/test_lua_wml.cfg
This main change here is moving tags to their own line, to avoid wmlindent
bug #1397. The lua gets a manual tabs-to-spaces conversion.
> Fix the indentation in test_lua_wml

- data/lua/wml-tags.lua
- data/lua/wml/store_reachable_locations.lua
- data/test/scenarios/store_reachable_locations_vision.cfg
- src/actions/vision.cpp
- src/actions/vision.hpp
- src/scripting/game_lua_kernel.cpp
- src/scripting/game_lua_kernel.hpp
- wml_test_schedule
Previously it calculated max movement, and then added the adjacent hexes. This
version should correctly handle:
* units with vp different to max mp
* units with vision costs different to movement costs
* jamming by enemy units
An interactive test showing the before and after results is in #5704
Fixes #4179
> Make [store_reachable_locations]range=vision calculate vision

- src/serialization/string_utils.cpp
- src/serialization/string_utils.hpp
- src/server/common/dbconn.cpp
- src/server/common/dbconn.hpp
- src/server/common/forum_user_handler.cpp
- src/server/common/forum_user_handler.hpp
- src/server/common/user_handler.hpp
- src/server/wesnothd/player.cpp
- src/server/wesnothd/player.hpp
- src/server/wesnothd/server.cpp
- utils/mp-server/table_definitions.sql
This allows the history to be persisted across restarts, whereas right now it's lost.
> Use the database to store and retrieve login history for the searchlog command.

- run_wml_tests
The fix in 9535ed9 didn't work, the script still crashed on that line, the
logic for working out how many tests in the batch had passed wasn't correct.
This commit drops that logic, and drops the dependent feature of trying to
retry the next test in the batch, and simply says the entire batch failed.
The new logic for filtering the output of a failed batch is much simpler - the
script doesn't filter it and we assume the developer is just going to ignore
any line that starts "PASS TEST". Only tests that are expected to pass get
batched, so the output is going to look something like the following:
PASS TEST: test_return
PASS TEST: test_assert
PASS TEST: test_return_2
PASS TEST: test_assert_2
Assertion failed: assert false
FAIL TEST: test_assert_fail
Failure, Wesnoth returned 1 FAIL but we …
> run_wml_tests: Print the correct test name when a test fails

- changelog.md
- data/core/macros/utils.cfg
- data/schema/game_config.cfg
- data/schema/units/abilities.cfg
- src/actions/attack.cpp
- src/units/abilities.cpp
- src/units/attack_type.hpp
The overwrite_specials attribute is limites to abilities/specials owned by fighter or teacher, the specials/abilities who affect fighter but owned by opponent(apply_to=opponent/both) not affected.
the new attribute is created for fix that bugbut also select the specials afected, if is apply_to=self or opponent or both
> modify overwrite_specials attributefor select the specials and weapon abilities who must be overwrited

- data/campaigns/Heir_To_The_Throne/scenarios/23_Test_of_the_Clans.cfg
When a enemy is killed in 23_Test_of_the_Clans.cfg of Httt, the show of number to enmy to vanquish is too breve for be read.
> fix text don't readable because duration not specified

- src/save_index.cpp
- src/save_index.hpp
- src/savegame.cpp
This pull request fixes some issues related to save_index:
* fixes a bug in save_index_class::remove() method.
The method incorrectly tries to remove an attribute from root config instead of removing 'save' children.
In effect, save files were not being removed from the save_index file.
* removes call to save_index_manager_->remove() in savegame::finish_save_game
This call to remove() is incorrect and has no effect except causing unneeded call to write_save_index().
* introduces a new clean_up_index() method in save_index_class.
The method removes non-existing save files from the index. Clean up is triggered only during the first
synchronisation of the index to disc and only if the index has more save files than found on disk.
Fixes  #5702.
> Fix save_index issues

- .github/workflows/ci-main.yml
Quick workaround for #5741, the Windows builds weren't finding Pango's header
files when used with vcpkg version 546813ae7b9e2873dd3d38e78b27ac5582feae10
([glib up to gtk] update and make it work with meson).
Hopefully we can revert this workaround soon.
(Note: don't merge until the CI build has passed)
> Keep the Windows CIs on a version of vcpkg that builds Wesnoth

- changelog.md
- data/multiplayer/eras.lua
- data/test/scenarios/test_lua_color.cfg
- src/scripting/lua_color.cpp
- wml_test_schedule
The first of the two commits already has PR #5723, this PR will be for the second one once that merges. It's mainly about the unit test and whether `pango_color` is the right name.
Fixes #5722.
With Ravana's color changer mod:
> Add wesnoth.colors[name].pango_color and use it in the multiplayer turns-over dialog

- changelog.md
- src/gui/core/canvas.cpp
- src/gui/core/canvas.hpp
- src/gui/core/canvas_private.hpp
If a widget is partially hidden or off-screen, this commit makes canvas.cpp
optimise and only draw the visible part.
Many of the asserts in canvas.cpp are removed, as the surface is no longer the
full canvas. The SDL_Render* functions do support the out-of-bounds and
negative values for x and y that are now passed to them, these are tested by
SDL2's testviewport.c.
Scrolling by a single pixel will force canvas::draw to do the full work of
redrawing the canvas. I had considered rendering a few of the off-screen lines
too, however it seems this isn't optimisable because the dirty flag is already
set on each redraw - that can be traced to window.cpp's push_draw_event()
causing canvas::set_is_dirty(true) to be called.
Refactor handling of the x, y, w, h variables with a common …
> Only render the visible area in canvas.cpp

- src/game_launcher.cpp
- src/language.cpp
- src/language.hpp
When the user supplies an exact locale identifier on the command line,
it doesn't make sense to check whether it's an incomplete translation.
> Make command-line option --language never require --all-translations

- data/test/scenarios/sighted_events.cfg
- wml_test_schedule
The old version's [event]name=sighted had a {RETURN} statement in it,
which meant the test stopped on the first sighting. Most of the test
wasn't testing anything.
> Rewrite the WML unit test for sighted events

- changelog.md
- src/font/text.cpp
- src/font/text.hpp
- src/gui/core/canvas.cpp
This is meant to be an optimisation, which will reduce memory usage when
rendering text. It doesn't seem to reduce the amount of work done by Pango, but
the drawing will be clipped in the Cairo library.
The line-by-line workaround for rendering huge areas of text is dropped, as we
now only expect to be rendering screen-sized or smaller parts of the text.
Rendering huge texts (greater than 64kpixels high) requires the caller of
pango_text::render() to change to calling pango_text::render(SDL_Rect) instead,
which will be handled in a separate commit - fixing the known crash when
opening the credits screen will require that commit on top of this one.
> Rendering only a viewport area in pango_text

- utils/woptipng.py
If a tool made the image bigger, the debug message was the same as if the tool
had made the image's pixel change. Clarify that into two separate messages.
As each verify_images() call checks that the file became smaller, the removed
print statement would never be reached.
> Make woptipng's debug output about bigger images clearer

- data/core/about_i18n.cfg
When an [about] section has a title but no [entry] tags, it's automatically
hidden in the credits. The entry with name="" was causing the title to show
up with a blank section under it.
Asturian and Friulian were removed in ad7699bffc16f7c982c95f1989ad6f932a1580b4
because they'd been added to the translation framework but hadn't received any
translated strings.
The reason that I'm leaving these in rather than completely removing them is
that the string "Friulian Translation" has already been translated into almost
all of the languages that Wesnoth supports. "Asturian Translation" has been
translated into around half of them, although the fuzzy-string support has put
the translation of "Estonian Translation" into the other half.
> Credits: hide the blank section for Friulian

- src/config.hpp
This is prompted by 1f8101ef22bb23699421505235f4962802773c77. This
approach should still be correct while hopefully not bothering any
compilers *and* avoiding unnecessary copies or conversions until the
input actually needs to be converted to a different type (in this case
std::string_view, which is cheaper than std::string).
> config: Don't create differently-typed copies of input in loops

- src/game_initialization/lobby_info.cpp
- src/game_initialization/lobby_info.hpp
- src/gui/dialogs/multiplayer/lobby.cpp
https://github.com/wesnoth/wesnoth/issues/4723
Don't know if this approach is best, but I broke out a `is_game_visible` method from `apply_game_filter` to test if an individual game is visible.
I had originally considered adding some sort of check in
https://github.com/wesnoth/wesnoth/blob/1cdc4ef530835876621f74b681646271fc4646b0/src/gui/dialogs/multiplayer/lobby.cpp#L310-L313
but it proved tricky because the game filter isn't actually applied until https://github.com/wesnoth/wesnoth/blob/1cdc4ef530835876621f74b681646271fc4646b0/src/gui/dialogs/multiplayer/lobby.cpp#L397 Making an additional call to `apply_game_filter` beforehand worked but didn't seem like a good idea to call it so many times. (the logic in `lobby.cpp` is messy enough already)
> Only show notifications for visible mp games (fixes #4723)

- changelog.md
- data/schema/units/modifications.cfg
- data/test/scenarios/test_effect_on_vision.cfg
- src/units/unit.cpp
- wml_test_schedule
Add attribute also_apply_to_vision to [effect]apply_to=movement
When processing [effect]apply_to=movement, if also_apply_to_vision is 'yes'
(which is the default) then the vision points will change by the same amount.
Previously, it sometimes affected vision and sometimes didn't; for most cases
where it makes a difference, I expect it to be a change from unanticipated
behavior to expected behavior.
Please refer to the new unit test added in this commit for more detailed docs;
that test is also a rough draft for the Wiki update needed when this merges.
The reason it sometimes affected vision was that the special value of -1 vision
points was interpreted as "use the value of the max movement points instead".
The special value of -1 is still supported and frequently used, and refactor that …
> Add [effect]apply_to_vision= attribute to [effect]apply_to=movement

- src/gui/dialogs/multiplayer/faction_select.cpp
- src/gui/dialogs/multiplayer/lobby.cpp
- src/gui/dialogs/title_screen.cpp
- src/help/help.cpp
- src/help/help.hpp
- src/scripting/lua_gui2.cpp
Most of the places that created a help_manager did so just to call show_help on
the next line. Move knowledge of the internals out of those callers and into
help.cpp.
This leaves editor_controller and play_controller with knowledge of help_manager,
however both of those classes handle ownership of the game_config too.
@CelticMinstrel, I still have some `\todo` comments to check, but I think this is a better way to handle help_manager.
> Make callers of help::show_help not need a help_manager

- changelog.md
- src/scripting/lua_widget_attributes.cpp
Fixes #5755.
This is one of several layout invalidation hacks used in the old Lua
GUI2 API lost in the implementation of the new API (which the old API
now wraps).
It turns out that in the previous API (see 1.14 for reference if you
need easy access to the source) there were several calls to
invalidate_layout() that weren't there just to look pretty.
For wesnoth.set_dialog_value:
* One prior to setting the value of a text_box
* One prior to setting the value of a unit_preview_pane
* One prior to setting the value of a styled_widget
* One after changing a widget's visibility to hidden
All of these were removed by the new API implementation, with the last
one ending up commented out, restored now in commit
8989eb430311092e66177bc09e1b1c344000d5aa. All the other ones are
entirely gone, …
> lua/gui2: Restore layout invalidation hack when setting widget labels

- changelog.md
- data/gui/window/addon_manager.cfg
- src/gui/dialogs/addon/manager.cpp
- src/gui/dialogs/addon/manager.hpp
Show the contents of PblWML's "tags" attribute in the add-ons dialog. They're
shown at the bottom of the right-hand panel (only if the window size is large
enough to trigger that dialog's two-panel layout).
This started as part of #5765, I've split it because I think this part is ready to
merge, but the filtering-by-tags part needs an inspiration about the descriptive
strings.
> Add-ons manager: show tags in the details panel

- changelog.md
- data/gui/window/addon_manager.cfg
- src/gui/dialogs/addon/manager.cpp
- src/gui/dialogs/addon/manager.hpp
Add a new drop-down filter to the add-ons manager, based on PblWML's
`tags` attribute.
The existing PblWML specification includes a comma-separated list of tags.
Until now there are no official tag names, but some of the 1.14 add-ons already
have some unofficial ones. If this feature is included in 1.16 then I assume
many UMC authors will use the newly-official tags.
For a larger add-on list than the dev server has, use port 15014 which will
connect to the 1.14 server instead (in the connect dialog change the address to
addons.wesnoth.org:15014).
> Filtering by tags in the add-on manager

- data/core/editor/help.cfg
The editor/help.cfg file was kept in sync between 1.14 and 1.16, it's now time
for 1.16-specific changes, starting with dropping this warning.
> Scenario editor help: remove the warning about 1.14 bugs

- src/formula/callable_objects.cpp
- src/formula/function_gamestate.cpp
Opening a PR to ensure CI passes; assuming it does, I'll merge tomorrow.
I don't expect much controversy in this PR, but it:
* Deprecates "side" in WFL formulas in favour of "side_number", which is consistently 1-based
* Adds tod_bonus and base_tod_bonus gamestate functions
* Adds "terrain" to unit objects, which looks up the terrain info for the unit's current location
> A few WFL updates

- changelog.md
- src/reports.cpp
_@irydacea asked in https://github.com/wesnoth/wesnoth/pull/5798#discussion_r639428602_:
> Which function is used for the sidebar description tooltips? Considering that singular units having different attributes than their unit types is actually an extremely common thing.
There seems to be some bug about triggering this tooltip - for me hovering the mouse over the sidebar reliably shows other tooltips, but is very intermittent with this one. However, the subject of this PR is the content of the tooltip when it does show.
> Include the new-style special notes in the sidebar's unit description

- data/campaigns/Under_the_Burning_Suns/utils/abilities.cfg
- data/scenario-test.cfg
special attribute is deprecated and must be replaced by special_id or special_type before 1.17
> replace deprecated special= by special_id/type in Utbs and scenario-test

- data/core/macros/abilities.cfg
Fix https://github.com/wesnoth/wesnoth/issues/5816 issue . https://github.com/wesnoth/wesnoth/commit/04455c01b4649af8433924a1dca82ab4e2621653 commit forget second owner and unit.side in formula.
> fix teleport message.

- changelog.md
- src/gui/dialogs/addon/manager.cpp
This fixes two specific causes of #3059, where code assumes that all parts of
the add-ons manager's UI are accessible, an assumption that fails when the
dialog uses a stacked widget to handle small window sizes.
It would be better to redesign the C++ for this dialog, but a quick workaround
for the observed issues is much easier.
* Fixes #5810, triggered by using the version drop-down in small-screen mode.
* Adds a workaround for keyboard input changing the selected add-on on small screens.
> Add-ons manager: Fix bugs that return to the title screen with an "Invalid WML" message

- src/game_initialization/multiplayer.cpp
- src/multiplayer_error_codes.hpp
- src/server/common/forum_user_handler.cpp
- src/server/common/forum_user_handler.hpp
- src/server/common/server_base.cpp
- src/server/common/server_base.hpp
- src/server/common/user_handler.hpp
- src/server/wesnothd/server.cpp
---
Tested as working locally with the password `password` when hashed as md5 (`$H$9ZDzPE45CDau6Dx3EgubHP5V77/Q3P/`) and bcrypt (`$2y$10$0xhi24E6CXeoICokaHKsA.qWrUDtzzCJGQD9W4Bhxyxv9rOD7pLfG`).
> Remove nonce and double hashing as it's no longer needed.

- data/hardwired/fonts.cfg
- src/font/font_config.cpp
The [fonts] [font] WML was only used to set up SDL_ttf fonts. The engine
code to read it was left in after
2dfdc0061d400ffad39f974d7fe9348204af0d08 in a dead state (some
structures are filled with data that never gets used).
> font: Remove dead code and WML previously associated to SDL_ttf

- src/formula/callable.hpp
- src/gui/core/canvas.cpp
- src/gui/core/canvas.hpp
Doesn't make much difference for release builds built with GCC,
it takes between 1% and 7% off the cost of std::update_canvas().
Calculated using the time taken by gui2::widget::get_best_size()
as a reference.
It's a tiny improvement, but it's also a tiny change, and the
improvement is in the loop that's MP lobby's performance problem,
as described in issue #5578.
> Slight optimisation of canvas::set_variables using std::move

- data/ai/micro_ais/micro_ai_unit_variables.lua
Some Micro AIs save information in unit variables. Examples are the patrol and messenger AIs, which save the next waypoint for a unit. This needs to be done as a synced command, so that the information is not lost when continuing a game from a replay.
Making this a PR because, at the moment, this can cause Wesnoth to crash.  An explanation for that and proposed fix is in #5595, but as discussed in that PR, I don't know if that is the correct way of fixing the problem.  So this will have to sit here until #5595 is merged.
> Micro AIs: fix unit variables being lost in replays

- src/server/wesnothd/server.cpp
- src/server/wesnothd/server.hpp
None of the dummy players have an actual connection or client, so any attempt to interact with them will fail. The main usecase for this right now is testing the performance of the MP lobby UI updates when there are many players online.
> Add option to pre-populate wesnothd's user list with dummy users.

- data/tips.cfg
Tooltips are such a common GUI feature that having a tip of the day about them
seems unnecessary. I'd expect a player to find out that we have them the first
time that the player wonders "what does that button do?".
While having hints about specific hotkeys seems logical, a general hint to
read the list of keybinds doesn't seem helpful.
> Tips: remove hints about tooltips and the hotkey preferences

- data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg
- data/tips.cfg
One of these uses bold for the menu's name, the other uses italic, because that
seems more consistent with the other hints in the same context.
Re-attach the comment about upkeep to the correct [event], and move the comment
about the easter-egg event to the start of its [event].
> Tutorial S02 and tips: Mention holding shift for accelerated speed

- data/advanced_preferences.cfg
- src/game_initialization/lobby_data.cpp
- src/game_initialization/lobby_data.hpp
- src/game_initialization/lobby_info.cpp
- src/game_initialization/lobby_info.hpp
- src/gui/dialogs/multiplayer/lobby.cpp
- src/gui/dialogs/multiplayer/lobby.hpp
- src/gui/widgets/tree_view.cpp
- src/gui/widgets/tree_view.hpp
- src/gui/widgets/tree_view_node.cpp
- src/gui/widgets/tree_view_node.hpp
- src/preferences/lobby.cpp
- src/preferences/lobby.hpp
This addresses the lobby performance issue as far as the playerlist updating. Previously for every player an item was added and the size of the tree view recalculated, which led to an increasingly unresponsive UI when the number of players in the lobby got to around 150+. With this change, the replace_children() method adds all the players and then after that recalculates the tree view's size once.
---
With a -O0 build, it now takes a fraction of a second to update the playerlist, down from over 30 seconds previously, when adding/removing a player from a playerlist with 500 entries.
For reference with #5578, the profile with this change applied:
> Add a method to clear and then add multiple items to a tree view.

- data/campaigns/tutorial/utils/utils.cfg
- data/schema/core/actionwml.cfg
- src/scripting/game_lua_kernel.cpp
In 1.14, the default was 50 frames, or around 1.7 seconds. In 1.15.4, commit
a9d9e48c72e70fd41ae9759e3894752eb9708596 changed the interpretation of that
number to milliseconds, but missed that this affected the [print] tag; this
left the default time that the text is shown as an unreadable 50ms.
All places in mainline that use [print] specify a duration, so the default
isn't used. Here I've plucked the new value from UtBS S09, where it was chosen
in f405b916a1141c2a4bc3bda3f88bbe0a8b8fe91b.
The tutorial is a special case - it originally displayed the text until the
player did the requested move (or almost, it used a duration of 10000 frames,
or around 40 minutes). That makes more sense to me than displaying it for 10
seconds, and as documented in floating_label.hpp the value -1 is already …
> Default [print]duration= to 5 seconds, tutorial uses "unlimited"

- data/multiplayer/maps/2p_Isle_of_Mists_basic.map
- data/multiplayer/maps/2p_Isle_of_Mists_drought.map
- data/multiplayer/maps/2p_Isle_of_Mists_rain.map
- data/multiplayer/maps/2p_Isle_of_Mists_secondrain.map
- data/multiplayer/maps/2p_Isle_of_Mists_secondsnow.map
- data/multiplayer/maps/2p_Isle_of_Mists_snow.map
- data/multiplayer/scenarios/2p_Isle_of_Mists.cfg
- data/multiplayer/scenarios/2p_Isle_of_Mists.lua
Description:
_Isle of Mists is a survival scenario for solitaire or two-player team-based play against randomly-spawned AI units. Victory is achieved by surviving and defeating all enemy waves. During the course of play, the terrain will change based on random weather effects. You need to use the default map settings for the scenario to work right._
This PR contains:
1. Adds a new multiplayer survival scenario.
2. Lua (similar to Dark Forecast one) code file used for the enemy waves and weather change events
3. Comes with 6 weather conditions (6 maps)
Features:
1. Default difficulty is set at `0`.
2. Has 1p/2p modes
3. 5 final waves
4. 8 difficulty levels, ranging from `-30` to `+60`, with `+60` being catered especially for veteran/skilled players.
Replays: 
Default difficulty | 2player …
> [MP] Isle of Mists - a new 1p/2p Survival Scenario. 

- data/core/units/dunefolk/Apothecary.cfg
- data/core/units/dunefolk/Captain.cfg
- data/core/units/dunefolk/Herbalist.cfg
- data/core/units/dunefolk/Horse_Archer.cfg
- data/core/units/monsters/Fire_Guardian.cfg
- data/core/units/monsters/Fire_Wraith.cfg
- data/core/units/monsters/Horse.cfg
- data/core/units/monsters/Horse_Black.cfg
- data/core/units/monsters/Horse_Great.cfg
- data/core/units/monsters/Jinn.cfg
- data/core/units/nagas/Sicarius.cfg
For changelog:
Dune Apothecary experience changed from 100 to 65.
Dune Captain experience changed from 86 to 75.
Dune Herbalist cost changed form 15 to 14.
Dune Horse Archer experience cost changed form 70 to 65.
Naga Sicarius hp changed form 55 to 53 and melee damage changed form 9 to 6, new special "deflect" added to melee attack.
Fire Guardian can now level into Fire Wraith.
Revised statistics of all animal horses in order for them to fit better within lore and not violate PIPLB. Bay Horse can now level into Great Horse.
Jinn - a lot changed within JInn, but the most impactful one is resistance change, it should allow for more wide use of this unit.
Fire Wraith cost changed from 25 ot 22.
Horses were changed a lot here are the most important changes:
Bay Horse can now level into Great …
> Balance changes for 1.15.14

- data/test/scenarios/unknown_scenario_warning.cfg
- src/play_controller.cpp
- src/play_controller.hpp
- wml_test_schedule
Check that the scenario's next_scenario= exists, and display a warning
if it would lead to an "Unknown Scenario" error. This also checks any
[endlevel] tags in events.
The error message includes the id of the missing scenario. If there
are multiple branches and some should be okay then a slightly
different message is shown saying which ones should work, hopefully
the ids will be something that hints to the player how to reach the
working branches.
The warnings' translatable strings could have plural and singular
forms, but these errors should be rare enough that it seems excessive
to have those separate plural and singular forms.
Fixes #5530.
> When starting or loading a game, warn if the next scenario is unknown

- changelog.md
- src/game_config_manager.cpp
Fixes #4447, and will be cherry-picked to the 1.16 branch too.
> Fix an intermittent crash with keyboard input during the load screen

- data/tools/wmlunits
Make it clear that the `yaml` package is not part of Python's Standard Library and should be installed with a package manager as outlined in [this](https://pep8.org/#imports) section of PEP8.
> Separate `import yaml` from other import statements in wmlunits

- src/gettext.cpp
Bug #5923 is that a broken .po file can make Wesnoth fail to start, not
even reaching the title screen. Additionally, the error message printed
to the console just said "*timestamp* error general:", and then missed
the details of what had broken.
This commit fixes the error message to show which add-on and which line
are causing the problem.
> Say what the error is when a broken .po file stops Wesnoth starting

- src/gettext.cpp
Bug #5923 is that a broken .po file can make Wesnoth fail to start, not
even reaching the title screen. Additionally, the error message printed
to the console just said "*timestamp* error general:", and then missed
the details of what had broken.
This commit fixes the error message to show which add-on and which line
are causing the problem.
(cherry picked from commit eaa39d653bc067d48449852cb480dff1c69b22ac)
> [1.16] Say what the error is when a broken .po file stops Wesnoth starting

- data/test/scenarios/test_synced_state.cfg
- wml_test_schedule
Note that this file gets formattedly badly by wmlindent, however it seems that wmlindent already skips the `data/test/scenarios` directory, the same issue affects `data/test/scenarios/recruit_facing.cfg`. Still working out if that is #1397 or if it should be a separate bug; I think it's a bug that needs fixing in wmlindent for 1.16, as it seems to break on any use of wesnoth.sync.evaluate_single in a `.cfg` file.
> Add a unit test for wesnoth.current.synced_state

- src/gettext.cpp
Prior to this, if any .po file included a \v (vertical tab), then the game
exited before reaching the title screen. It didn't have to be in a mainline
translation - any add-on could break the game, and would do so before the title
screen appeared, thus preventing the user from using the add-on manager or
language selection to avoid the problem.
Instead, treat a parsing error similarly to the .po file simply not existing.
Fixes #5923.
> Make failure loading textdomains non-fatal

- data/test/scenarios/test_synced_state.cfg
- wml_test_schedule
The edge-case of calling evaluate_single within an unsynced event was
surprising, and I'm not sure it's correct. However, as we're about to
release the 1.16 branch I think it's better to include that as a test
that the API doesn't change during the stable branch.
(cherry picked from commit f9fc806fd2955a5f9ac31803d429192c5fcfd478)
> [1.16] Add a unit test for wesnoth.current.synced_state

- src/gettext.cpp
Prior to this, if any .po file included a \v (vertical tab), then the game
exited before reaching the title screen. It didn't have to be in a mainline
translation - any add-on could break the game, and would do so before the title
screen appeared, thus preventing the user from using the add-on manager or
language selection to avoid the problem.
Instead, treat a parsing error similarly to the .po file simply not existing.
Fixes #5923.
(cherry picked from commit 23a0377b56d5455c08a741d1457a5cb92fd39091)
> [1.16] Make failure loading textdomains non-fatal

- src/gui/widgets/window.cpp
This delay is to stop the loop running continously, it isn't necessary to do
that when we're about to exit the loop anyway. I'm unsure whether this makes
any noticeable difference, but it seems reasonable to remove delays when
possible.
I'm tempted to change the enclosing loop to a `do ... while` instead of a `for`
that has an empty clause.
> Remove the 10ms delay before closing a window

- src/game_events/action_wml.cpp
The old `ai.synced_command` function always set the AI-context game state to changed when executing such a command. This was inadvertently omitted when the implementation was changed to `invoke_synced_command` in fef953a4. While custom synced commands may or may not change the game state and the engine has no means of determining this correctly in all cases (meaning that neither behavior is technically wrong), the fact that the behavior was changed should be considered a bug. This commit changes it back to how it was before fef953a4.
There are a variety of places where setting the game state to changed could be added in the code. I chose this one, as it is analogous to what is done for the `replace_map` function [later in the same …
> Fix custom synced commands not changing the AI game state

- data/gui/window/migrate_version_selection.cfg
- projectfiles/Xcode/The Battle for Wesnoth.xcodeproj/project.pbxproj
- source_lists/wesnoth
- src/addon/client.cpp
- src/addon/manager_ui.cpp
- src/filesystem.cpp
- src/filesystem.hpp
- src/game_config.cpp
- src/game_config.hpp
- src/gui/dialogs/migrate_version_selection.cpp
- src/gui/dialogs/migrate_version_selection.hpp
- src/preferences/game.cpp
- src/preferences/game.hpp
- src/preferences/general.cpp
- src/preferences/general.hpp
- src/wesconfig.h
- src/wesnoth.cpp
Currently migrated, if existing:
* Add-ons (redownloaded if present on new add-ons server)
* Preferences file
* Credentials file
---
Re-PR of #5918 so it's on a mainline branch.
Note to self: make sure to review the comments there as well.
> Add a prompt to migrate data from previous versions of wesnoth.

- data/campaigns/tutorial/scenarios/01_Tutorial_part_1.cfg
A player can follow Dacyn's instructions to the letter, yet get
killed if they choose a village 2 hexes away from the Quintain on
turn 2.
There are better suggestions about handling this in
https://r.wesnoth.org/t54644 , however during the string-freeze
let's simply make the Quintain stay on its starting spot on turn 1.
Add a CLEAR_PRINT because the player has just completed the
"End your turn" instruction.
Given the release timing, I'm opening this as a 1.16 PR, intending
to cherry-pick to master afterwards.
> [1.16] Tutorial S01: Don't let the first Quintain attack on turn 2

- data/campaigns/tutorial/scenarios/01_Tutorial_part_1.cfg
(cherry picked from commit b02b1ad2ff31d2e56828729cc9d2a952453b8761, so I'm just going to do a CI run and merge)
A player can follow Dacyn's instructions to the letter, yet get
killed if they choose a village 2 hexes away from the Quintain on
turn 2.
There are better suggestions about handling this in
https://r.wesnoth.org/t54644 , however during the string-freeze
let's simply make the Quintain stay on its starting spot on turn 1.
Add a CLEAR_PRINT because the player has just completed the
"End your turn" instruction.
> Tutorial S01: Don't let the first Quintain attack on turn 2

- changelog.md
- src/units/abilities.cpp
Now, if a weapon is affected by an ability used as a weapon, the name will appear as if it was a classic special.
> add the names of the abilities used as weapons in the attack prediction window

- data/campaigns/The_Rise_Of_Wesnoth/scenarios/04a_The_Swamp_of_Esten.cfg
For consistency, there should also be no hyphen in "un-death".
The style was decided in PR #5525.
> TRoW S04a: Typographic style is not to have a hyphen in "un-life"

- data/campaigns/Secrets_of_the_Ancients/utils/zombie_recruit_dialog.lua
- data/campaigns/tutorial/lua/character_selection.lua
Two related bugfixes, put into one PR because, if we find things to change on one, there may be things to change on the other one too. Both will backport cleanly and are already tested on the 1.16 branch.
Tutorial S01: Synchronise the choice of character
---
This avoids showing the dialog during replays, and thus avoids an
OOS if the person watching the replay chooses the other character.
Fixes (on master) #5926.
SotA: Synchronise the zombie recruitment dialog
---
This dialog works by setting variables in the postshow function,
so the code had to be moved around to ensure that those variables
were synchronised, not just the return value of the dialog.
The message about not having enough gold isn't necessary for the
replay, so that gets moved into the synchronised code too.
Fixes (on …
> Tutorial S01 and SotA: Synchronise calls to gui.show_dialog

- data/campaigns/Secrets_of_the_Ancients/utils/zombie_recruit_dialog.lua
- data/campaigns/tutorial/lua/character_selection.lua
Backport of #5994. Fixes #5334, fixes #5926.
Cherry-picked cleanly, and (aside from whitespace differences) already tested on 1.16 before opening the PR for master.
> [1.16] Tutorial S01 and SotA: Synchronise calls to gui.show_dialog

- data/campaigns/World_Conquest/_main.cfg
- data/campaigns/World_Conquest/scenarios/WC_II_scenario.cfg
This PR addresses #5113 and #5112 for the 1.16 branch. I shall make a master branch PR of this later on. 
The credits can be left untranslated as of right now, since the priority is returning world conquest to be playable from start to finish.
> [world conquest] add campaign icons, campaign image and credits

- data/campaigns/tutorial/gui/character_selection.cfg
- data/campaigns/tutorial/maps/01_Tutorial_part_1.map
- data/campaigns/tutorial/scenarios/01_Tutorial_part_1.cfg
Remove the maximum size for the character-select dialog, the window will
automatically choose the minimum size that fits the text.
Extend the map 1 hex south. This means that, if the full map fits on screen,
the horizontal center of the map (where the print statements appear) is between
the keep and the south village, thus their labels don't overlap the print
statements.
This backports cleanly (and has been tested on 1.16), it fixes 2 of the points in #5544.
Placement of `[print]` on HDPI:
The character selection still looks good in a minimum-sized window:
> Tutorial S01: HDPI support

- data/campaigns/tutorial/gui/character_selection.cfg
- data/campaigns/tutorial/maps/01_Tutorial_part_1.map
- data/campaigns/tutorial/scenarios/01_Tutorial_part_1.cfg
Backport of #5996. All three files are identical to the master version, and I
tested on 1.16 prior to opening that PR, so intending to merge once the CI
check passes without further review.
Remove the maximum size for the character-select dialog, the window will
automatically choose the minimum size that fits the text.
Extend the map 1 hex south. This means that, if the full map fits on screen,
the horizontal center of the map (where the print statements appear) is between
the keep and the south village, thus their labels don't overlap the print
statements.
(cherry picked from commit 25052e967ea75471796aa3c00d92f86f809521b7)
> [1.16] Tutorial S01: HDPI support

- data/gui/window/campaign_dialog.cfg
This doesn't scale the campaign image (and the campaign images are generally
350x350 images anyway), so it looks a bit wrong, but it's a lot more useable
on HDPI than putting a 1050x750 limit on a treeview with a text panel.
Without this change:
With this change:
> Allow the campaign selection to be bigger on HDPI screens

- data/gui/window/campaign_dialog.cfg
This doesn't scale the campaign image (and the campaign images are generally
350x350 images anyway), so it looks a bit wrong, but it's a lot more useable
on HDPI than putting a 1050x750 limit on a treeview with a text panel.
(cherry picked from commit 62a8bad97c89c08f0b96d5f1728e60b3bee7ec34)
> [1.16] Allow the campaign selection to be bigger on HDPI screens

- data/core/units/humans/Mage_Silver.cfg
The strings in special-notes.cfg don't have a leading space,
and this one causes a warning in poedit.
> Remove a leading space from the Silver Mage's [special_note]

- data/campaigns/Under_the_Burning_Suns/scenarios/09_Blood_is_Thicker_Than_Water.cfg
Opening the PR on 1.16 as that's what I tested on, will cherry-pick to master afterwards.
This foreshadows that the player will need to attack the north-west after
defeating the north-east enemy, which is a bit fairer to anyone playing this
scenario for the first time.
Removes a now-unused string (Darius' pre-sacrifice speech). There are no new
strings here, the others are just being moved around.
For clearing shroud, change to using radius= because clearing a circle looks
better than clearing a square.
There's no significance to whether the new plan is "Plan B" or "Plan C" - back
in Wesnoth 1.10 it seems to have been dependent on whether all the merfolk had
been rescued.
Fixes issue #5540 about Hekuba spawning on a water hex.
> UtBS S09: Reveal the boss of the scenario at the end of part 1

- changelog.md
- data/campaigns/Liberty/scenarios/06_The_Hunters.cfg
Issue #6019
Can be back-ported to 1.16 assuming corrections are still allowed at this time.
> Resolve #6019 - allied side not triggering failure condition when sighted

- data/campaigns/World_Conquest/era/era.cfg
Until a proper solution is found for #5228 , this will have to do. It suppresses the appearance of the era in the era selection list for other scenarios, preventing the bug from happening.
Hmm, I guess the [campaign] tag should support the `allow_era=` key in future but for the moment, this will do.
Players can play WC with Default, Default+Dunefolk, Age of Heroes, AOH+Dunefolk and UMC eras for the time being.
> [world conquest] World Conquest Era is only available for the campaign

- data/campaigns/World_Conquest/era/factions/The_Gang.cfg
- data/campaigns/World_Conquest/era/factions/The_Guild.cfg
- data/campaigns/World_Conquest/era/factions/The_Hand.cfg
- data/campaigns/World_Conquest/era/factions/The_Horde.cfg
- data/campaigns/World_Conquest/era/factions/The_Militia.cfg
- data/campaigns/World_Conquest/era/factions/The_Trust.cfg
- data/campaigns/World_Conquest/era/factions/strings.cfg
```
Arif -> Dune Soldier
Hakim -> Dune Herbalist
Jundi -> Dune Rover
Khaiyal -> Dune Piercer
Naffat -> Dune Burner
Rami -> Dune Rider
```
I have also substituted the "Dune Piercer" with "Dune Rider", since it's a non-existent unit in 1.16 and master.
> [world conquest] [master/1.17] Replacement of khalifate unit types with dunefolk unit types

- data/campaigns/World_Conquest/lua/map/scenario_utils/plot.lua
Fixes the campaign part of #5891 (which is the main part of that bug).
> WC: End the campaign at the end of the final scenario

- data/campaigns/World_Conquest/lua/campaign/scenario.lua
What this does is just checks the value of wc2_scenario before executing the function, and executes it for the first scenario only as intended.
Fixes #5900
> [world conquest] [master] [lua] Check for wc2_scenario value before executing wc2_start_units function

- data/campaigns/World_Conquest/lua/campaign/scenario.lua
What this does is just checks the value of wc2_scenario before executing the function, and executes it for the first scenario only as intended.
Same as #6052, Fixes #5900 for 1.16
> [world conquest] [1.16] [lua] Check for wc2_scenario value before executing wc2_start_units function 

- data/test/scenarios/lua_map_find.cfg
- data/test/scenarios/mapgen_filter.cfg
- src/scripting/lua_terrainfilter.cpp
- wml_test_schedule
Fixes the currently suspected root cause of #5108, but requires further testing
to confirm that it fixes that issue.
Closes #6501 (the question of how to test the mapgen filter).
Opening the 1.16 PR first, will forward-port afterwards.
Ping @knyghtmare
> [1.16] Fix an off-by-one in mapgen's x and y filters, and add unit tests

- data/test/scenarios/lua_map_find.cfg
- data/test/scenarios/mapgen_filter.cfg
- src/scripting/lua_terrainfilter.cpp
- wml_test_schedule
Forward-port of 6055, fixes #5108 and closes #6501 (the question of how to test the mapgen filter).
(cherry picked from commit 30f50bac681fda1566f5cee5aad7be6b65cb0fdb)
> Fix an off-by-one in mapgen's x and y filters, and add unit tests

- data/campaigns/World_Conquest/era/campaign/heroes.cfg
- data/campaigns/World_Conquest/era/campaign/strings.cfg
- data/campaigns/World_Conquest/era/era.cfg
- data/campaigns/World_Conquest/era/factions/The_Alliance.cfg
- data/campaigns/World_Conquest/era/factions/The_Cult.cfg
- data/campaigns/World_Conquest/era/factions/The_Empire.cfg
- data/campaigns/World_Conquest/era/factions/The_Gang.cfg
- data/campaigns/World_Conquest/era/factions/The_Guild.cfg
- data/campaigns/World_Conquest/era/factions/The_Hand.cfg
- data/campaigns/World_Conquest/era/factions/The_Horde.cfg
- data/campaigns/World_Conquest/era/factions/The_Militia.cfg
- data/campaigns/World_Conquest/era/factions/The_Scourge.cfg
- data/campaigns/World_Conquest/era/factions/The_Trust.cfg
- data/campaigns/World_Conquest/era/factions/strings.cfg
- data/campaigns/World_Conquest/resources/data/artifacts.cfg
- data/campaigns/World_Conquest/resources/data/training.cfg
- data/campaigns/World_Conquest/resources/strings/artifacts.cfg
- data/campaigns/World_Conquest/resources/strings/effects.cfg
- data/campaigns/World_Conquest/resources/strings/mainline.cfg
- data/campaigns/World_Conquest/resources/strings/training.cfg
- data/campaigns/World_Conquest/scenarios/WC_II_scenario.cfg
Macros with very generic names such as "STR_CASTLE" were defined and not
undefined. This prefixes all of them to be WC_STR_CASTLE, etc.
Either fixes or reduces the severity of #6062, going to treat this as fixing it.
> [1.16] WC: Add a WC_ prefix to defines with generic names

- data/campaigns/World_Conquest/era/campaign/heroes.cfg
- data/campaigns/World_Conquest/era/campaign/strings.cfg
- data/campaigns/World_Conquest/era/era.cfg
- data/campaigns/World_Conquest/era/factions/The_Alliance.cfg
- data/campaigns/World_Conquest/era/factions/The_Cult.cfg
- data/campaigns/World_Conquest/era/factions/The_Empire.cfg
- data/campaigns/World_Conquest/era/factions/The_Gang.cfg
- data/campaigns/World_Conquest/era/factions/The_Guild.cfg
- data/campaigns/World_Conquest/era/factions/The_Hand.cfg
- data/campaigns/World_Conquest/era/factions/The_Horde.cfg
- data/campaigns/World_Conquest/era/factions/The_Militia.cfg
- data/campaigns/World_Conquest/era/factions/The_Scourge.cfg
- data/campaigns/World_Conquest/era/factions/The_Trust.cfg
- data/campaigns/World_Conquest/era/factions/strings.cfg
- data/campaigns/World_Conquest/resources/data/artifacts.cfg
- data/campaigns/World_Conquest/resources/data/training.cfg
- data/campaigns/World_Conquest/resources/strings/artifacts.cfg
- data/campaigns/World_Conquest/resources/strings/effects.cfg
- data/campaigns/World_Conquest/resources/strings/mainline.cfg
- data/campaigns/World_Conquest/resources/strings/training.cfg
- data/campaigns/World_Conquest/scenarios/WC_II_scenario.cfg
Forward-port of #6063, will merge after CI passes.
Macros with very generic names such as "STR_CASTLE" were defined and not
undefined. This prefixes all of them to be WC_STR_CASTLE, etc.
Either fixes or reduces the severity of #6062.
(cherry picked from commit d3d21e59ee797cfe9eecd50aabae10a353547328)
> WC: Add a WC_ prefix to defines with generic names

- src/save_index.cpp
I haven't seen anyone else remark about this, which surprises me. But the `steam_autocloud.vdf` file that constantly gets updated and shown in my game load dialogue bothers me enough to make this small change.
I don't know if it's worthwhile ignoring any file that doesn't follow `*.gz` or other expected file format, but that's beyond the scope of this PR. In such a case, we may as well follow what seems to be customary in regular application load dialogues and have a filter under or next to name field, with `*.gz` as the default filter.
I also don't know if this change is small enough to be allowed into 1.16 branch, hence the back-port reminder label.
PS Any attempt to load `steam_autocloud.vdf` results in an error message 'The file you have tried to load is corrupt', so I can't imagine a …
> Ignore auto-generated Steam file in save directory

- data/campaigns/Under_the_Burning_Suns/units/undead/Ethereal_Shadow.cfg
The Ethereal Nightgaunt's equivalent note was already fixed in f94d0bb80a425b02873f13e67ea856151a05ae6f.
Fixes #4480.
> UtBS: Remove leading whitespace from Ethereal Shadow's special note

- data/campaigns/Delfadors_Memoirs/scenarios/07_Night_in_the_Swamp.cfg
According to the bonus objective as it stands, it should be possible to end the scenario early by simply destroying the 'generator' stones even if leaving a few skeletons around. However, the way victory condition is established simply by counting the number of enemy units at the start of a turn - if there are no units left, then the stones are assumed to be destroyed. (No generator stones active -> no enemy units)
As a work-around, simply update the objectives to make it clear that all enemies need to be eliminated for early victory to be achieved.
> DM S7: Clarify objectives (resolves #5608)

- data/campaigns/Under_the_Burning_Suns/scenarios/06a_In_the_Tunnels_of_Trolls.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/06b_In_the_Domain_of_Dwarves.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/11_Battle_for_Zocthanol_Isle.cfg
Use existing macro to avoid situations where Nym's otherwise-mute Dust Devil pet might speak.
Resolves #4892.
Note: I'm not familiar with WML so I'm not sure if I've done this 'right'. But for a quick test, focusing on the Draug mentioned in the aforementioned issue, I did the following (GUI Debug Tools wasn't working for me - maybe not yet working for 1.17.0+dev):
* Start UtBS campaign and debug-skip to Battle for Zocthanol Isle.
* Debug-remove fog and shroud.
* Debug-create Mage of Light adjacent to Kelur and attack to bring its HP down (high probability of all three attacks hitting).
* Debug-create Dust Devil and use it to finish off Kelur.
Before: Dust Devil remarks about the key left behind.
After: Nym speaks on the Dust Devil's behalf.
> UtBS: Silence the Dust Devil

- data/campaigns/World_Conquest/scenarios/WC_II_scenario.cfg
Fixes #6077
---
While no errors/warnings are present anymore, changing the number of players does print to the terminal for some reason.  For example, changing from 1 player to 3 players printed:
```
1	1
2	1
3	1
```
> Specify a non-zero value for nplayers.

- data/campaigns/Under_the_Burning_Suns/scenarios/03_Stirring_in_the_Night.cfg
if Garak have 0% or -10% resistance only then steadfeast don't usable here. Fix https://github.com/wesnoth/wesnoth/issues/6046
> Replace steadfast with resistance abilities special for Garak

- data/campaigns/Northern_Rebirth/scenarios/12a_Get_the_Gold.cfg
- data/campaigns/Northern_Rebirth/scenarios/13a_Showdown.cfg
Resolves #5375.
I tested this as per the above request and it works as intended. I can't think of how it could cause any, but not sure if there could be any unintended side-effects
> Make the team Eryssa leads (if alive) have consistent colour

- cmake/FindTranslationTools.cmake
- po/SConscript
- src/formula/string_utils.cpp
- src/formula/string_utils.hpp
- src/gettext.hpp
- src/tests/test_formula_timespan.cpp
See #6036.
This also adds a new `N_n()` no-op marker to `gettext.hpp` that is to `_n()` as `N_()` is to `_()`.
**NOTE:**
This is **NOT** a string-freeze-compliant change. Changing the strings from being standalone to being part of a plural form set causes them to be automatically fuzzied by the pot-update target. Merging this in 1.16 will have to wait until after 1.16.0 is released.
> Make utils::format_timespan() use gettext plurals, simpler output by default

- data/campaigns/Under_the_Burning_Suns/utils/dehydration-utils.cfg
Even though units are not dehydrated in subsequent scenarios, the dehydration icon may otherwise still appear in the side-bar without this.
> Clear dehydration status on victory (resolves #5687)

- src/gui/dialogs/formula_debugger.cpp
- src/help/help_impl.cpp
- src/reports.cpp
- src/units/attack_type.cpp
- src/units/unit.cpp
Resolves #4348
Pango changed its definition of 'green' in version 1.32.2 to align with CSS specifications (see #4348 for details). This change focuses only on instances of `<span color="green">`, leaving instances of named colours that don't use 'green'. For example:
https://github.com/wesnoth/wesnoth/blob/f8a41624e3022947b6d7d9ac6b0311c4a7d1fee4/src/gui/dialogs/gamestate_inspector.cpp#L598
**Problem**: I cannot see how to use this approach with `<format>` so it breaks time-of-day bonus colour consistency. Then again, I'm not sure if the green used in `<format>` is the same as the green used in `<span>`...
https://github.com/wesnoth/wesnoth/blob/f8a41624e3022947b6d7d9ac6b0311c4a7d1fee4/src/help/help_impl.cpp#L398-L402
Also:
https://github.com/wesnoth/wesnoth/blob/f8a41624e3022947b6d7d9ac6b …
> Switch to hard-coded colours instead of relying on pango names

- src/reports.cpp
Partially resolves #1297 - I'm not sure if there's a way to auto-scroll to the Defence figures in the unit's Help page.
> Link side-bar unit defence rating to unit's Help page

- data/campaigns/Northern_Rebirth/scenarios/05a_01_The_Pursuit.cfg
- data/campaigns/Northern_Rebirth/scenarios/10a_Stolen_Gold.cfg
- data/campaigns/Son_Of_The_Black_Eye/scenarios/08_Silent_Forest.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/03_Stirring_in_the_Night.cfg
As discussed in #6107, have left 'guys' in Camerin's lines alone.
> Avoid use of 'cool' and 'guys' (closes #6107)

- src/units/abilities.cpp
if an weapon like abilitie with apply_to=opponent is used, then name appear in attack
> fix possible bug in attack prediction windows

- src/editor/controller/editor_controller.cpp
Work-around crash situation caused by using scenario-specific tools in map context (closes #5883)
> Editor: Work-around crash situation

- src/units/drawer.cpp
Resolves #5974... I think.
It appears double `zoom_factor` scaling results in units being drawn way off their actual hex at high zoom, for tiles with a large (~20 pixels) unit height offset parameter, for example on certain keeps and bridges.
I'm not super-confident this is the 'right' way to resolve the issue, but empirical testing does suggest removing at least one of the `zoom_factor` scalings produces the desired result.
> Remove scaling by zoom_factor in unit height adjustment calculation

- src/gui/dialogs/game_load.cpp
Second attempt at resolving #5321 after first (naïve) attempt in #6092.
Also shows campaign-specific difficulty for MP games.
* Test scenario: No difficulty -> —
* Pre-1.15 Tutorial: No difficulty -> —
* SP Campaigns: Custom difficulty -> no change
* MP Campaigns: Plain difficulty -> Custom difficulty
* MP Scenario: No difficulty -> —
```
Save Game                Before              After
---------                ------              -----
Test scenario            Medium              —
Tutorial (1.14 Tutorial) Medium              —
Tutorial (1.17 Campaign) Tutorial (Beginner) Tutorial (Beginner)
MP single scenario       Medium              —
SP campaign (HttT)       Commander (Normal)  Commander (Normal)
MP campaign (HttT)       Medium              Commander (Normal)
SP campaign (LoW) …
```
> Display Difficulty as em dash when it is not valid (resolves #5321)

- data/campaigns/Under_the_Burning_Suns/scenarios/02_Across_the_Harsh_Sands.cfg
Issue #6125 - UtBS S2 Across the Harsh Sands Pinnacle Rock is covered during dialog fix. Now the camera will scroll to the tile where the "Pinnacle Rock" map label is.
> Pinnacle rock map label covered during dialog fix

- data/campaigns/Sceptre_of_Fire/scenarios/1_A_Bargain_is_Struck.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/2_Closing_the_Gates.cfg
Resolves #6160 
Objective Notes are added to inform the player about the available rune chests that can be used to purchase rune upgrades.
> SoF Add Rune Chest Objective Notes

- data/campaigns/The_Rise_Of_Wesnoth/scenarios/19_The_Vanguard.cfg
The S19's gold chest close to the troll enemy leader will now be collected at the end of the scenario if the player misses it (which is unlikely but could happen). A new dialogue may be necessary in line 704.
The expected behaviour of the changes is:
- If the player moves a unit during the scenario to the chest, it opens and cannot be opened again and at the end of the scenario nothing will happen.
- If the player misses the chest, Haldric (Or the closest ally unit, if that is ever wanted to be implemented) moves to the chest and opens it, and the scenario ends.
(Closes #6141)
> TRoW S19 Chest is automatically collected at the end of the scenario

- data/campaigns/Sceptre_of_Fire/scenarios/4_Gathering_Materials.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/5_Hills_of_the_Shorbear_Clan.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/6_Towards_the_Caves.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/8_The_Dragon.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/9_Caverns_of_Flame.cfg
- data/campaigns/Sceptre_of_Fire/utils/utils.cfg
Resolves #6153 
Adds an objective note to scenarios where Thursagan can upgrade units. This implementation is consistent with the design style set forth by Son of the Black Eye for its "Great Horde" mechanic, which displays an objective note for half of the scenarios in that campaign.
SoF Thursagan's Rune Mastery:
SotBE Great Horde:
> Add Objective Note for Thursagan's Rune Mechanic

- data/campaigns/Under_the_Burning_Suns/scenarios/06b_In_the_Domain_of_Dwarves.cfg
- data/core/macros/abilities.cfg
Two fixes have been bundled in this PR:
1. Tentacle spawning rework.
Previously, the tentacle spawning event would search for a suitable location to spawn the tentacles (and it would search for just the one location) so if it failed to find a Ww* or Wo* (shallow or deep water) tile then the location array (locs) would be empty and lowering the random variable by one (which is defined between 1 and the length of locs) would cause it to be below zero (-1) as seen in my comment in #6196 (Erased Lines 1268-1276). TL;DR [store_locations] would not store all matching locations.
The expected behaviour now is:
At the start of the scenario, in the prestart event, all the intended possible locations for spawn are stored in locs (Lines 293-306).
When tentacles have to be spawned, a random number is …
> UtBS S06b hermit enhancement and tentacle fix.

- src/font/text.cpp
- src/tooltips.cpp
Fix iterator-use-after-invalidation in tooltips
---
It's undefined behavior to access an iterator after calling std::map::erase(),
the correct method is to use the new iterator that erase() returns instead.
Fix pango_text::set_maximum_height
---
Change back to handling the height in our code instead of expecting Pango to
handle it. Pango is still expected to handle the maximum width, as Pango needs
to handle the word-wrapping.
While writing f282eb7, I had noticed that set_maximum_height called
PangoLayout's pango_layout_set_height, and removed the apparently unnecessary
enforcement of the maximum height from our wrapper code. The documentation
added in this commit explains why that was incorrect.
Fixes #6007 and #6096, both issues that some tooltips on the sidebar stopped
working. The …
> [1.16] Fix tooltips on the sidebar

- src/font/text.cpp
- src/tooltips.cpp
Forward-port of #6256. Will merge once the CI passes.
There's still a known issue with 800x600 resolution. At that resolution, the
side-flag is ellipsed (even if the unit has a short name), and the tooltips for
both the name and the flag are missing. The movement and defense tooltips (both
are on the line above the name and flag) are sometimes also missing in 800x600.
Given that, I'm considering leaving #6007 open to track it. Issue #6096 can be closed,
as it has "fullscreen" in the title.
Fix iterator-use-after-invalidation in tooltips
---
It's undefined behavior to access an iterator after calling std::map::erase(),
the correct method is to use the new iterator that erase() returns instead.
Fix pango_text::set_maximum_height
---
Change back to handling the height in our code instead of …
> Fix tooltips on the sidebar

- data/tools/wesnoth/wmltools3.py
Resolves #5949.
Seems more like a bug fix than a feature enhancement. The original code had a for loop that tried to modify the contents of `Forest.forest` but never actually updated it.
Tested by using wmlscope on a check out of A New Order:
Here's the output of `wmlscope --collision` before the fix:
[beforefix.txt](https://github.com/wesnoth/wesnoth/files/7428240/beforefix.txt)
And here's the output after. No more looking inside of .git:
[afterfix.txt](https://github.com/wesnoth/wesnoth/files/7428244/afterfix.txt)
So far this only makes wmlscope and anything else that uses the Forest class object inside wmltools actually avoid version control subdirectories. In #5949 there is also mention of other "pesky" subdirectories such as 
`.DS_Store`
Do we want to specifically also include …
> Make wmltools Forest avoid version control subdirectories

- data/gui/window/preferences/02_hotkeys.cfg
- src/gui/dialogs/preferences_dialog.cpp
Discussed in #4390 and originally introduced in 7c8c3114.
I suppose can back-port to 1.16 when there's no string freeze.
> Resolve title-screen vs main menu inconsistency

- data/core/units/monsters/Horse.cfg
- data/core/units/monsters/Horse_Black.cfg
- data/core/units/monsters/Horse_Great.cfg
- data/core/units/monsters/Wild_Wyvern.cfg
Makes attack name consistent with other weapon attacks and also avoids translation issues (resolves #6071).
> Rename kick attack for horses and wyverns

- data/campaigns/Under_the_Burning_Suns/scenarios/06b_In_the_Domain_of_Dwarves.cfg
Fix for one of the tasks in Issue #6196. Used a [switch] instead of [if]-[elses] for clarity. **⚠New strings have been added ⚠** and have to be revisioned, make sure string freeze is lifted before merging/backporting.
Dust devil (monster) string: 
Elyssa (human) string:
In case other race is added to previous scenarios in the future:
Troll and Quenoth elf strings are unchanged.
> UtBS S06b Fix Dwarf Sergeant confusing a dust devil or human for a troll

- src/units/race.cpp
In 1.16 with Ageless Era 4.28.0, the message `[race] '' is missing a
plural_name` is printed to the chat area. The message is not useful even to
add-on developers, because it only identifies which race is affected by
`[race]name`, and in the affected races the `name` attribute is also missing.
An unfortunate side-effect of making the warnings more useful is that more of
them are shown in-game - these messages go through the logging mechanism that
discards duplicate messages. Making them useful also makes them unique,
they are no longer duplicates.
Also log if a race lacks either a male or female singular name. This warning
will not trigger if the race has a non-empty `name`, as both gender-specific
options are documented to fall back to `name`.
Remove the warning about races that have a …
> Show the id in the "[race] '' is missing a plural_name" warning

- src/preferences/credentials.cpp
Fixes GH-6288, and hopefully makes the code
more readable / easier to understand.
> Fix multi-account password saving

- data/campaigns/Under_the_Burning_Suns/scenarios/07a_Dealing_with_Dwarves.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/07b_Talking_with_Trolls.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/08_Out_of_the_Frying_Pan.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/09_Blood_is_Thicker_Than_Water.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/10_Speaking_with_the_Fishes.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/11_Battle_for_Zocthanol_Isle.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/12_The_Final_Confrontation.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/13_Epilogue.cfg
- data/campaigns/Under_the_Burning_Suns/utils/dialog-macros.cfg
With four potential allies in the campaign, there is a lot of dialogue duplication. This refactoring attempts to consolidate the text. Additionally, the ally ID was recorded in the variable `ally_name` which can be confusing (it was to me, at least), so I renamed it to `ally_id` instead.
Unless I made a mistake somewhere, the dialogue itself should not be changed, this is just to avoid redundant duplication. Please keep in mind I'm still very much a novice with WML so be gentle in pointing out any errors. Thanks.
PS I tested a little bit but haven't done a thorough checking of S7 (where `ally_id` is introduced) onwards, for all four allies.
> Refactor handling of allies in UtBS

- data/tools/wmlindent
- data/tools/wmllint
- data/tools/wmlscope
- data/tools/wmlxgettext
Closes https://github.com/wesnoth/wesnoth/issues/3352.
wmllint and wmlscope already had KeyboardInterrupt Handlers. I just edited their displayed messages for consistency. wmlindent and wmlxgettext did not have interrupt handlers and it had to be defined in their scripts.
wmllint and wmlscope use try-except clauses to define the interrupt routine.
I used a listener, `signal.signal`, to handle the interrupt routine so that I wouldn't have to wrap all the existing code in a try-except clause and change all the indentation.
Approver, please try running all four scripts and then pressing ctrl-c to abort so that you can verify the new behavior.
> KeyboardInterrupt Handlers for wmltools

- src/editor/palette/location_palette.cpp
- src/utils/parse_network_address.cpp
Temporary workaround for #6291.
It is an upstream bug but seems to take a long time to fundamental resolve, such as fix the bug at the upstream or move release toolchain to MSVC.
> Replace std::regex by boost to temporary workaround for Mingw-w64's bug

- data/themes/default.cfg
Two changes in the theme config for 1024x600, which is inherited by the config
for 800x600. Both are the same line but otherwise only loosely related to each
other; together these fix issue #6264, which was that trigger areas for some
tooltips overlapped.
Reduce the width for the unit's name, thus giving the side-flag and side-number
(which get the remaining horizontal space) enough space to display themselves.
128 pixels wide is the same as the name gets in larger themes, even though
those larger themes use larger font sizes. This means that the side number
doesn't get ellipsed, at least for games with up to 9 sides, with the
side-effect that the tooltip can be displayed when hovering over the flag.
Move the name, and thus the flag and side-number down by 1 pixel, so that they
don't …
> ui: Fix 800x600 theme's sidebar tooltips

- po/CMakeLists.txt
Fixes #6320.
About whether to backport it: it's not necessary for 1.16, but it's a bugfix that I'd test along with #6321, and it's a bug that caused unexpected differences between SCons and CMake when testing #6322, so I think it's worth backporting all three PRs together.
> CMake: update the .po files before generating stats about them

- cmake/update_pot_source_dependencies.cmake
Make the search for translatable strings include install_dependencies.cpp in the POTFILES.in file.
Exactly one (plural) string has been missing from .pot files build by CMake, presumably since 2017.
> CMake: run xgettext on the .cpp file with GETTEXT_DOMAIN "wesnoth"

- data/campaigns/Secrets_of_the_Ancients/utils/sota-utils.cfg
It's possible, however unlikely, for none of Ardonna's bats to have died before killing the hostile bats in 'Following the Shadow'. In such a case, when the 'You can now raise bat corpses!' event triggers, Ardonna will still refer to the enemy bat as her 'pet' so add this condition to avoid it.
> Ardonna should only call her own bats 'my pet'

- data/campaigns/Under_the_Burning_Suns/scenarios/02_Across_the_Harsh_Sands.cfg
As said in the comments, a die event makes the unit linger. Applied what is said in https://wiki.wesnoth.org/Eventwml#die
> Note: The primary unit is not removed from the game until the end of this event. The primary unit can still be manipulated, will block other units from taking its hex, and will still be found by standard unit filters (except [have_unit]). To prevent this behavior, you can use [kill] to remove the unit immediately.
(Closes #6341)
> UtBS S02 Ogre now dissappears before Nym starts moving or talking

- data/tools/wmlxgettext
Add a sort inside wmlxgettext so that the order of filenames on the command
line doesn't affect the output. The sort is run unconditionally, because I
don't see a usecase for not enabling it. For consistency with xgettext and
msgcat, if there was an option to enable it then it would be called
`--sort-by-file`.
The aim of this change is to reduce the number of changes in .po files caused
by a pot-update. When multiple comments refer to the same translatable string,
separate runs of pot-update could generate them in a random order. If I've
understood the root cause correctly, wmlxgettext itself was deterministic, but
the order of the files on wmlxgettext's command line was not deterministic.
For testing, I tried reversing the sort order; the resulting reordering hit
lines that commonly swap …
> wmlxgettext: sort-by-filename before processing files

- src/units/abilities.cpp
Showing the names of the abilities that apply to the opposing side with that opponent's attack is more confusing than anything else.
> Remove apply_to = opponent from the opponent's attack prediction window(master)

- data/campaigns/Under_the_Burning_Suns/scenarios/04_Descending_into_Darkness.cfg
By happenstance, Elyssa was my first unit to enter the caves. It sounded really weird for her to complain about the darkness and then say that she can use her fireballs to defeat the orcs.
As per the code commentary, it seemed the intention was to have this dialogue be for the elves:
https://github.com/wesnoth/wesnoth/blob/4248738a3894df4a551debd4ff6afff4e68ffe49/data/campaigns/Under_the_Burning_Suns/scenarios/04_Descending_into_Darkness.cfg#L746
So I added `race=quenoth` to exclude Elyssa and focus on the elves as per the original intention.
Unfortunately - or perhaps fortunately - Kaleh was my next unit in line to enter the caves, and it sounded really bad for him to complain about the darkness and then tell himself 'we have no choice'. So I added `[not]id=Kaleh[/not]` to cover that …
> UtBS S4: Restrict who remarks about the dark underground tunnels

- data/campaigns/Under_the_Burning_Suns/units/monsters/Dust_Devil.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Youth.cfg
Effect ingame:
If the Dust devil still has the "Taller" and "Stronger" AMLAs available, the XP is blue.
If it reaches all major AMLAs, it turns purple so the player does not waste XP on him.
Also documented the changes in the files, so it is easier to understand, for future reference, why the XP bar is blue.
(Closes #6212)
> UtBS Changed and documented the change of XP bar color to blue

- data/campaigns/Under_the_Burning_Suns/utils/abilities.cfg
Like description of Utbs formation abilities is opposite of what suggest name in attack prediction windows, it best to remove that.
> remove Utbs 'formation' name of attack prediction windows

- .luacheckrc
- data/lua/functional.lua
- data/test/scenarios/lua_functional.cfg
- wml_test_schedule
The file `data/lua/functional.lua` contains a `reduce` function which, when receiving a falsey `identity` argument, changes it to `0`. This makes it impossible to initialize the calculation with `nil` or `false`. `functional.reduce(t, 'or', false)` will always return `0`.
While changing the function to accept any 3rd argument, I decided to rewrite it to `fold`, which always includes the init value in the calculation, and `reduce`, which only looks at the identity value if the array is empty.
> Expand the reduce function to both fold and reduce

- data/campaigns/The_Rise_Of_Wesnoth/scenarios/19_The_Vanguard.cfg
Fixed a bug reported on discord by @Konrad22 which made the chocobones spawn over a chasm as can be seen:
Using passable=yes, and with the previous code implementation, no undead should spawn over a chasm.
> TRoW S19 Fix for the flying chocobones issue

- data/campaigns/Under_the_Burning_Suns/scenarios/08_Out_of_the_Frying_Pan.cfg
There appears to be another situation as with #6341, but for the human attackers:
I tested this change directly in my current save file and it seemed to resolve the issue.
I also remove redundant phrasing and correct a commentary typo. @nemaara Please advise if you object to the former - I just find the phrasing of 'Hurry up already!' to be too modern (and redundant) compared with just 'Hurry up!'
> UtBS S8: Ensure humans are removed from display during their 'die' event

- data/campaigns/Under_the_Burning_Suns/scenarios/08_Out_of_the_Frying_Pan.cfg
Resolves #6355.
The 'Cloaked Figure' that hounds Kaleh and friends can be encountered up to three times:
* S4 - guaranteed as his appearance is triggered by Kaleh entering the cave which is a scenario requirement.
* S5 - appearance is at a random turn during the battle between the dwarves and the trolls.
* S8 - final appearance is triggered when moving through the narrow passage.
It is possible to miss the encounter in S5 due to the randomised turn mechanic. Thus, it can be confusing when Kaleh says 'third time'. This is just a quick work-around - another option may be to make the appearance in S5 more deterministic.
> UtBS S8: Avoid counting encounters with the 'Cloaked Figure'

- src/game_config_manager.cpp
Whether or not it's the campaign being played, this warning
gets printed if any add-on has a [campaign]extra_defines=
attribute with one of the deprecated strings (a hardcoded
list about 20 lines above the line that's changed here).
> Print which campaign is causing the extra_defines warning

- CMakeLists.txt
- src/CMakeLists.txt
Fixes the MINGW build in the MSYS2 environment on Windows.
I've seen the previous PR #4728, but a more recent change to the CMakeLists-files introduced MSVC-specific compile and link flags for all WIN32 targets.
This PR splits `WIN32` and `MSVC` and keeps the `gcc`-flags if MSVC is not used.
With this I was able to build and run wesnoth in the UCRT64-environment of MSYS2 using CMake.
There is one more occurrence of `NOT WIN32` where I'm not sure if the section should apply for MSYS2.
~~I will try to add an inline comment for the relevant section.~~
Since there are no changes to this section a inline comment is not possible.
Here is a link to the section in question: [CMakeLists.txt line 81-95](https://github.com/wesnoth/wesnoth/blob/9d5271b98aebdb39631b98089f22f15d80c75a5a/CMakeLists.txt#L …
> Fix MINGW build on Windows by splitting MSVC and WIN32

- SConstruct
- src/CMakeLists.txt
- src/desktop/version.cpp
With these changes, Wesnoth builds and runs on SunOS 5.11, tested on OpenIndiana 2021.10.
> SunOS 5.11/OpenIndiana build fixes

- src/game_config_manager.cpp
- src/game_config_manager.hpp
- src/gui/dialogs/multiplayer/mp_join_game.cpp
- src/server/wesnothd/server.cpp
> Get the scenario_id from the addon content list sent by the server if it's not otherwise available.

- data/themes/editor.cfg
I think we should add the `Map Screenshot` item to the menu so it's easier to discover. (See #6386)
Not sure where it fits best. I've put it below "Save Map As". The map menu could be another option.
> editor: Add "Map Screenshot" item to menu

- src/actions/move.cpp
- src/gui/widgets/multimenu_button.cpp
I tried to use the Wiki docs, and found the Wiki docs were outdated compared to
our codebase, which prompted this code review.
No code or string changes, just an improvement to the comments.
> Improve comments for translators around VNGETTEXT

- src/macosx/SDLMain.mm
Map new constant names to their previous names after testing the SDK version. Tested against wesnoth 1.16.1.
Patch adapted from https://github.com/macports/macports-ports/pull/13437
> Support macOS 10.8-10.11 SDKs

- src/gui/dialogs/unit_attack.cpp
if by example, formation affect a dark Adept, and he is defender, then formation name appear in defender attack.(if name and description of formation in chance_to_hit abilities)
> fix weapon abilities showed in void attack in attack dialog window

- changelog.md
- data/core/units/orcs/Nightblade.cfg
Grabbed the image from #6339 solves #4145 partly.
> 1.16 - Added attack icon to the nightblade's kick

- src/game_classification.cpp
- src/game_config_manager.cpp
- src/game_config_manager.hpp
The current issue is that, when loading a replay that requires addons from the main menu, it's checking for which addons can be enabled with game_classification.active_addons(...) before it reloads the cache to contain addons (such as eras) that are behind the #ifdef MULTIPLAYER define. It is of course impossible to find addon content before it has been loaded, which results in things like OOS errors due to unknown unit types.
Fixes #6283
> Only try to activate required addons after loading all addons present.

- data/campaigns/World_Conquest/lua/game_mechanics/effects.lua
In the old WC here there was wesnoth.unit_defense function, so it should be wesnoth.units.chance_to_be_hit. In the current code it's wesnoth.units.defense_on which returns actual defense (50,60,40, etc), so the code checked if the defense of the unit is better than given by the artifact and worsened it.
> Fix Winged Sceptre bug in WC

- data/lua/wml-tags.lua
- data/test/scenarios/put_to_recall_and_modify.cfg
- wml_test_schedule
Units on the recall list might have x,y coordinates that are on the map, which
therefore need to be replaced with "recall,recall" within [store_unit]. The
existing code created a temporary variable, changed the coordinates, and then
returned the unchanged original instead of the temporary.
Add a new test that `[put_to_recall_list]` followed by `[modify_unit]`
doesn't move the unit back to the map.
Fixes #6295
Fixes #6315
> Fix [store_unit]'s stored coordinates for recalls

- src/menu_events.cpp
- src/mouse_events.cpp
- src/mouse_events.hpp
Two commits. The first one unifies some common code from mouse_handler::mouse_motion and mouse_handler::touch_motion.
For changelog.md
---
``` 
* Fixed the originally planned move becoming visible to enemies when an "enemy sighted" event interrupts a multi-turn move (issue #6292)
* Made planned multi-turn moves consistently visible to allies.
* Fixed "enemy sighted, press t to continue" also activating a feature that showed units' route to where the move started (issue #6292)
```
Only show planned moves to self and allies
---
Fixes #6292, that the planned final destination from multi-turn moves and
interrupted moves was visible to enemies. There are three side-numbers involved
in this logic, listed below; the GUI code was checking whether the move should
be visible to the player whose …
> [1.16] Only show planned moves to self and allies in multiplayer

- changelog.md
- data/campaigns/Under_the_Burning_Suns/scenarios/08_Out_of_the_Frying_Pan.cfg
The variable talking_unit is used instead of unit to set the speaker in many messages.
The talking unit that talks on behalf of the monsters can be, in this order: An elf in the map, a recalled elf, a forcedly spawned elf (Lines 3007-3067)
That unit will move to the dunes to fit the dialogue (Lines 3124-3137)
EDIT: fixed on 061a42b:
I found that code at line 3024 was not searching for units on the recall list
Also if a unit was on 19 20 previously, it would get the talker role, even if it was not intended.
Also the unit which gets created in case everything else fails could get stuck in a wall
Another thing I found testing is that skeletons in one of the events can get stuck on the wall if you walk to their spawning positions maybe fixable on another PR.
Closes #6211
> UtBS S08 Kromph and Dust Devil able to trigger Eloh's event

- changelog.md
- data/campaigns/Delfadors_Memoirs/scenarios/14_Shadows.cfg
Please add postponed label due to string freeze.
**Changes:**
Changed the event comment (as beating the enemy leader is allowed and accounted for on lines 349+) (Line 331).
Added a dialogue to explain a bit why they are being spawned (Lines 332-335) (string could be changed before merging)
And added `animate=yes` to enemy spawning (Lines 337-339, 341-343)
Closes #6176
> DM S14 Smooth undead appearance and add dialogue

- changelog.md
- data/campaigns/The_Rise_Of_Wesnoth/scenarios/22_The_Rise_of_Wesnoth.cfg
**New behaviour:**
When no units are in the "island" north of the bridge, "retreat" is said instead of "advance".
If there are units on both sides of the bridge, (even if it is only one, minor level 1 unit) the word advance takes priority over retreat. As stated on the issue, it is such a minor possibility that it does not matter if the condition is simple, as long as it does not feel weird when the dialogue is triggered (at least, that is my opinion).
Also remember string freeze if backported.
Closes #6376
> TRoW S22 Fixed the possibility of a missplaced dialogue when a bridge was broken

- data/campaigns/Liberty/scenarios/06_The_Hunters.cfg
This is a simple translation fix
> Fix typo: "with heavy loses" -> "with heavy losses"

- utils/po_stat.py
The failure mode caused it to overwrite the es_ES stats
with the es_419 ones. Skipping the CI step, as this script
is only run by the pot-update targets.
[ci_skip]
> Fix the po stats script to recognise "es_419"

- data/campaigns/Heir_To_The_Throne/scenarios/04_The_Bay_of_Pearls.cfg
- data/campaigns/Heir_To_The_Throne/scenarios/05b_Isle_of_the_Damned.cfg
- data/campaigns/Heir_To_The_Throne/scenarios/06_The_Siege_of_Elensefar.cfg
>S04 assigns a unit as role=Supporter, which is used exactly once, in a [message] immediately after the assignment. The list isn't quite the same as the later scenarios' role=Advisor, as it includes no merfolk (and in S04 it shouldn't), but it seems odd to only use it once.
Now `type` is used inside `[message]` to avoid assigning a role used only once.
> S05a seems okay. It assigns role=Advisor along with [auto_recall][/auto_recall] even though the role hasn't been assigned in a previous scenario; however in this case it's in a prestart event and the [role] tag will search the recall list, so auto_recall makes sense. The type= list includes merfolk, but that's okay as the starting encampment is on a beach.
Agreed, S05a uses it properly.
> S05b also assigns role=Advisor, and again includes …
> HttT S04, S05b & S06 Role code enhancement

- src/help/help_topic_generators.cpp
The notes are automatically added based on the terrain's properties, there isn't a way to add or remove them in WML.
As-is, this fixes #6394. Issue #4417 mentions some other possibilities too, but I want to postpone these:
* income is complex about upkeep, and the values can be specific to the map and the side
* illumination would need to handle min and max lighting caps too
* defense caps would entangle this with the units on the map, I don't intend to add that at all
Any questions about negative values for gives_healing() are issue #4232; this PR simply doesn't add a special note for that.
The next image is what's shown when choosing the terrain in the help browser's list. The main reasoning for this PR is that the "A welcome sight" line doesn't appear when right-clicking on an oasis on …
> Add a "special notes" section to terrain help pages

- data/core/editor/help.cfg
This adds help documentation for:
* The deprecated terrain marker
* XO and UO movement overlays
* Castle, keep and village overlays
* Fake Shroud
> Editor: document the magenta D and the special terrain overlays

- data/campaigns/Sceptre_of_Fire/scenarios/1_A_Bargain_is_Struck.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/2_Closing_the_Gates.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/2p5_Reaching_the_Runecrafter.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/2t_In_the_Dwarven_City.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/3_Searching_for_the_Runecrafter.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/3t_The_Council_Regathers.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/4_Gathering_Materials.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/4t_The_Jeweler.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/5_Hills_of_the_Shorbear_Clan.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/6_Towards_the_Caves.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/7_Outriding_the_Outriders.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/8_The_Dragon.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/9_Caverns_of_Flame.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/Epilogue.cfg
- data/campaigns/Sceptre_of_Fire/units/Cave_Wyrm.cfg
- data/campaigns/Sceptre_of_Fire/units/Cave_Wyrmlet.cfg
- data/campaigns/Sceptre_of_Fire/units/Red_Wyrm.cfg
- data/campaigns/Sceptre_of_Fire/units/Red_Wyrmlet.cfg
- data/campaigns/Sceptre_of_Fire/utils/rune-equip.cfg
This is a proofread pass. But this also has edits that are more than just minor edits which try to improve the campaign text. `wmlxgettext` was used to review all the text.
> SoF Proofread Pass and Campaign Prose edits

- data/core/macros/special-notes.cfg
While this will be deleted before 1.18, at the moment UMC authors
are still working on 1.16. While the 1.17 branch is being used for
new development in the engine, I think it's more useful to be able
to run 1.16 UMCs that test engine edge cases rather than force the
UMCs to be upgraded for 1.18's macros.
There's currently circa 1200 units using `{SPECIAL_NOTES}` in
Ageless Era, probably requiring manual checks to update them.
Another option would be to `#define SPECIAL_NOTES` in the UMC
itself, but that would likely also mean that the warning was
silenced when running on 1.16, and few of the 1200 units would
get fixed during the 1.16 cycle.
This reverts part of commit 61fa3627818c1a3fb5181a21fc651b67d17b133a.
> Temporarily re-introduce the SPECIAL_NOTES macro

- src/chat_command_handler.cpp
- src/chat_command_handler.hpp
- src/chat_events.cpp
- src/chat_events.hpp
- src/gui/widgets/chatbox.cpp
- src/gui/widgets/chatbox.hpp
- src/menu_events.hpp
- src/tests/gui/test_gui2.cpp
Solves https://github.com/wesnoth/wesnoth/issues/3202
Add `/clear` chat command
https://user-images.githubusercontent.com/9501115/150701852-c67dd99f-f77f-43a7-8cff-270976dc91ac.mp4
> Add /clear chat command

- data/campaigns/World_Conquest/resources/data/artifacts.cfg
fixes banner not stacking with leadership
Addresses point 8 of #6411
> [world conquest] [artifact/abilities] Make banner stack with leadership ability.

- src/game_config_manager.cpp
Forward-port of #6425, planning to just run the CI and then merge immediately.
Closes #6204.
The existing code searched for `[units][advancefrom]` instead of
`[unit_type][advancefrom]`, so wasn't triggering. It was planned
for removal in 1.17, so simply mark it as already-removed in 1.15.3.
The deprecation warning is shown on stdout/stderr, but not in the
in-game UI, so it's generally not visible to players. I think it
would be better if it was visible, but OTOH it's something that's
easy for someone to check all add-ons for with a simple grep.
(cherry picked from commit f2fa807e6107c63aa9b38f36e5ad8a8fcfacf9a9)
> Fix deprecation of [advancefrom], mark as already removed

- data/test/scenarios/backstab.cfg
- wml_test_schedule
Based on part of Pentarctagon's #6308, and also improving
the encapsulation of the test to take a boolean value for whether
the ability should be active instead of the expected damage total.
> Refactor the backstab unit test

- src/addon/manager_ui.cpp
Originally this simply checked for whether the add-on's directory existed to avoid downloading the same add-on multiple times when migrating from one major release to another. However this then causes add-ons to not get updated when joining a multiplayer game where to person joining has the add-on (so the directory exists) but needs an updated version of it.
Fixes #6383
> Make the adhoc add-on download check more detailed.

- changelog.md
- src/gui/dialogs/addon/manager.cpp
Fix another instance of issue #3059, where code assumes that all parts of the
add-ons manager's UI are accessible, an assumption that fails when the dialog
uses a stacked widget to handle small window sizes.
The up and down arrow keys select the previous or next add-on in the list,
even when the small-window layout is hiding the list. That feels like a feature
rather than a bug, as it's useful and an understandable UX; however it needs
the fix in this commit so that on_addon_select() doesn't throw an exception
and close the dialog. The new code is the same as the fix that 050feb623b
applied to on_selected_version_change, traversing the stacked widget to get the
info.
Fixes #6485.
> Add-ons manager: handle the selected add-on changing in small-screen mode

- src/formula/callable_objects.cpp
This changes it to use the function that attack_type::get_value already uses,
thus removing a call to attack_type::weapon_specials. The latter is being
refactored by @newfrenchy83, and questions about the effect of that refactor on
this code delayed the review on his PR.
This code is part of the object used for [filter_weapon]formula=, however the
implementation of that filter creates exactly one attack_type_callable, so
doesn't trigger this code. For testing I called it via a debugger.
> Change [filter_weapon] to not depend on attack_type::weapon_specials

- packaging/flatpak/org.wesnoth.Wesnoth.json
- utils/dockerbuilds/CI/Dockerfile-base-flatpak
Since the CI was updated to build 1.17 with Flatpak 21.08, the 1.16 builds have failed because they're lacking 20.08.
This cherry-picks c6f9a96a09e3eda6e1e43ccdaabe8a5442a40b2a and 35211181b4ba6e08ff67d9a1b9ee3cdd2e311990. I haven't done local testing, just want to run a build to check that the CI is currently fully set up if we upgrade 1.16 to 21.08.
> [1.16] Update to Flatpak 21.08

- src/formula/callable_objects.cpp
Backport of #6501.
This changes it to use the function that attack_type::get_value already uses,
thus removing a call to attack_type::weapon_specials. The latter is being
refactored by newfrenchy83 (and that refactor is expected to be backported as
it allows UI improvements).
This code is part of the object used for [filter_weapon]formula=, however the
implementation of that filter creates exactly one attack_type_callable, so
doesn't trigger this code. For testing I called it via a debugger.
(cherry picked from commit 6ccac5a5e8ff75303c9190c0da60580925cb32c0)
> [1.16] Change [filter_weapon] to not depend on attack_type::weapon_specials

- src/gui/dialogs/unit_attack.cpp
- src/units/abilities.cpp
- src/units/attack_type.hpp
weapon_specials only called in unit_attack.cpp, only_active argument don't usable
> remove only_active argument to weapon_specials()

- changelog.md
- data/campaigns/Sceptre_of_Fire/scenarios/3_Searching_for_the_Runecrafter.cfg
> SoF: fix thursagan's arcanister advancement breaking in some cases

- changelog.md
- data/campaigns/Sceptre_of_Fire/scenarios/3_Searching_for_the_Runecrafter.cfg
Same as #6484 but for the 1.16.x branch. A backport.
> SoF: Fix for Thursagan's Arcanister advancement breaking

- data/tools/wmlindent
- data/tools/wmlxgettext
For keyboard interrupt change exit code from 0 to 1.
> wmlxgettext and wmlindent change exit code

- data/campaigns/Heir_To_The_Throne/scenarios/17_Scepter_of_Fire.cfg
Resolves #6517
It might be obvious to experienced Lua API users but it's not a direct translation to `map.special_locations` as per https://wiki.wesnoth.org/LuaAPI/UpdatingFrom14, but rather `wesnoth.current.map.special_locations`.
I tested this in master and believe it can/should be back-ported to 1.16.
> HttT S17: Update to comply with current Wesnoth Lua API specifications

- data/campaigns/Heir_To_The_Throne/scenarios/08_The_Princess_of_Wesnoth.cfg
- data/campaigns/Secrets_of_the_Ancients/scenarios/17_Mortality.cfg
- data/campaigns/The_Rise_Of_Wesnoth/scenarios/07_Return_to_Oldwood.cfg
I think deprecation notifications are only being shown in 1.17 but not 1.16. I noticed the `map_overwrite` deprecation message when testing the former.
I checked the change in SotA S17, no apparent regressions. I don't see any other instances of `map_overwrite`.
Info: https://wiki.wesnoth.org/SingleUnitWML#placement
> Replace deprecated placement=map_overwrite

- src/game_version.cpp
This controls whether the "show deprecation warnings" preference defaults to
on or off. It seemed odd to have that default to on for the official 1.17.x
releases, yet default to off for local builds which developers are fixing.
> Treat all 1.17 builds as dev versions, including non-canonical ones

- src/CMakeLists.txt
- src/color_range.cpp
- src/display.cpp
- src/terrain/translation.hpp
- src/tests/test_commandline_options.cpp
- src/tests/test_mp_connect.cpp
- vcpkg.json
> Minor req cleanup

- data/campaigns/Sceptre_of_Fire/scenarios/4t_The_Jeweler.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/9_Caverns_of_Flame.cfg
I don't like the explanation of the tools being made of unobtainium, so changed
it to use a convenient plot device. I think this also solves a plot hole about
the forge; instead of it being near the Shorbear Caves by random chance, this
gives a reason for the Shorbear Clan to live there (even if they haven't been
in there in living memory).
@max-torch I'd appreciate a review please, but I can't add you in Github's UI.
> SoF: explain the Shorbear tools as products of the volcanic forge

- data/gui/window/addon_auth.cfg
- src/addon/client.cpp
- src/gui/dialogs/addon/addon_auth.cpp
- src/gui/dialogs/addon/manager.cpp
This allows storing add-on passwords for uploading in the same credentials file as is currently used by the client when connecting to a multiplayer server. For add-on authors that don't keep their passwords as plaintext in their _server.pbl, this removes the need for them to manually enter their password each time they upload an add-on.
> Store add-on passwords in the credentials file as well.

- CONTRIBUTING.md
---
This would be a replacement to https://wiki.wesnoth.org/WesnothTranslations, just in a place people are more likely to see that contributing to translations is a thing they can do.  After merging, that wiki page would be replaced with a redirect to this section of CONTRIBUTING.md.
Translations listed with a maintainer of None were determined by there being no updates to that language for over 5 years, or if a language was added more recently but has not received any meaningful updates since.
> Put translation contribution info into CONTRIBUTING.md.

- src/addon/state.cpp
Previously this code assumed that all add-ons would have a _server.pbl or an _info.cfg. When neither was the case, it tried to dereference the begin() of an empty set, causing the crash.
> Fix #6389.

- src/formula/variant.cpp
- src/formula/variant.hpp
- src/formula/variant_value.cpp
- src/formula/variant_value.hpp
- src/utils/any.hpp
For CI.
There's one remaining use of boost::any in commandline_options.cpp that cannot be converted since boost::program_options
excepted custom validator functions to take boost::any as their first argument.
> Used std::any, except on MacOS

- utils/dockerbuilds/CI/Dockerfile-base-mingw
- utils/dockerbuilds/mingw/Dockerfile
- utils/dockerbuilds/msys2/Dockerfile
- utils/dockerbuilds/msys2/bin/pacman-cross
- utils/dockerbuilds/msys2/ownstuff.conf
rwgrim/msys2-cross on dockerhub we're currently using is incapable of being updated anymore because of changes in msys2 keyring and rebuilding the image from scratch is hard because it requires manual setup and many things seems to have broken due to changes in pacman and the like. So I made my own variant of it that downloads msys2 as archive, and uses pacman from archlinux base image to download msys2 package updates. rwgrim/msys2-cross uses debian base with pacman-static but I couldn't make this way work since new version of pacman-static seems to depend on some extra config files not existing in debian.
> Reimplement mingw cross-compile docker image

- data/tools/wmlxgettext
Some users of wmlxgettext have scripts that already provide the file list in
a deterministic order, and the sorting added in 2adcb92fab was choosing a
different order to the one desired.
This doesn't affect mainline's .pot files - `scons pot-update` will have the same
output with or without this change.
@cooljeanius here you go.
> [1.16] wmlxgettext: add a --no-sort-by-file option

- data/test/scenarios/test_move_unit_to_occupied_hex.cfg
- wml_test_schedule
Just a CI check for the forward-port of #6571.
(cherry picked from commit ba1767f8b90a4ca34cf8ef2abbc03cf98fd488f8)
> Add a unit test for [move_unit]location_id with an occupied hex

- src/gui/core/event/dispatcher.hpp
Opening as a PR for comments on the design, as well as waiting until we get the MacOS requirements sorted. Not 100% this is the correct use of `std::is_convertible`, but it does seem to work.
> GUI2/Dispatcher: refactored [dis]connect_signal to use constexpr-if

- src/map/label.cpp
Simple UX improvement that occurred to me. Thoughts?
Before:
After:
> Scale map labels by zoom

- utils/optiwebp.py
---
This is a script that converts png to lossless webp and jpg to lossy webp (quality 90), as well as reconverts existing webp images using lossless conversion. This PR is not for actually converting any images.
Remaining work:
* Some TODO comments.
* See if there's some way to tell if a webp image was created with lossy vs lossless compression.
[conversion-good.csv](https://github.com/wesnoth/wesnoth/files/8359738/conversion-good.csv) has a list of the files that had their size reduced by more than 10%.
[conversion-bad.csv](https://github.com/wesnoth/wesnoth/files/8359737/conversion-bad.csv) has a list of files that did not have their size reduced by more than 10%.
A quick summary:
* Out of 13832 files, 13345 files had their size reduced by more than 10% while 487 did not.
* Of the …
> Add script to mass convert images to webp.

- changelog.md
- data/campaigns/Northern_Rebirth/scenarios/05a_01_The_Pursuit.cfg
Stuck units will now be brought back (or pushed forward if hex is occupied). Also fixed the trigger. Will open backport PR ~soon~ when approved.
Closes #6607
> NR S05a_01 The Pursuit - Fixed units getting stuck in the wall before the spider chamber.

- data/test/maps/4p_single_castle.map
- data/test/scenarios/firststrike_and_laststrike.cfg
- src/units/abilities.cpp
- wml_test_schedule
Closes https://github.com/wesnoth/wesnoth/issues/6575. like reported in forum in https://forums.wesnoth.org/viewtopic.php?p=672374#p672374
if unit with "last strike" ([firststrike] special with apply_to=opponent, on any of its attacks) is targeted by other unit for attack, wesnoth crashes,
and other problems exist also for other weapon specials like poisons, when apply_to=opponent used(id two user of this specials fight, one fighter only could be poisoned)
> fix [firststrike] special with apply_to=opponent crashes Wesnoth 1.16.x

- changelog.md
- data/campaigns/Northern_Rebirth/scenarios/05a_01_The_Pursuit.cfg
Squash before merging.
Closes #6608
> NR S05a_01 Enhance dialogue between Tallin and Abhai

- data/test/maps/4p_single_castle.map
- data/test/scenarios/firststrike_and_laststrike.cfg
- data/test/scenarios/poison_opponent.cfg
- data/test/scenarios/swarm_disables_upgrades.cfg
- src/units/abilities.cpp
- wml_test_schedule
like reported in forum in https://forums.wesnoth.org/viewtopic.php?p=672374#p672374
if unit with "last strike" ([firststrike] special with apply_to=opponent, on any of its attacks) is targeted by other unit for attack, wesnoth crashes,
and other problems exist also for other weapon specials like poisons, when apply_to=opponent used(id two user of this specials fight, one fighter only could be poisoned)
> fix [firststrike] special with apply_to=opponent crashes Wesnoth 1.17.x

- data/campaigns/Sceptre_of_Fire/scenarios/2_Closing_the_Gates.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/2p5_Reaching_the_Runecrafter.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/3_Searching_for_the_Runecrafter.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/4t_The_Jeweler.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/5_Hills_of_the_Shorbear_Clan.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/6_Towards_the_Caves.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/9_Caverns_of_Flame.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/Epilogue.cfg
Sadly, this takes the campaign up to 100 string changes between 1.16.2 and 1.16.3. The only one of these that was already going to change for 1.16.3 is S04t's volcanic forge one.
My intention (whether or not this merges) is to send out a mail to the i18n list when Saturday's pot-update is done, identifying the [4 strings that are actual changes](https://r.wesnoth.org/p672656), and saying that all the other fuzzies are just en_US grammar changes.
I think all of these make sense as mid-sentence pauses, but a few were arguably starting a new sentence so the ellipse was acting as both an ellipse and a full stop.
Pings: @max-torch. I'd ping demario if I knew his Github username.
> SoF: Consistently use lower-case after ellipses

- data/campaigns/Under_the_Burning_Suns/scenarios/09_Blood_is_Thicker_Than_Water.cfg
- data/campaigns/tutorial/utils/utils.cfg
- data/core/macros/ai_controller.cfg
- data/lua/core/interface.lua
- data/lua/wml-tags.lua
- data/schema/core/actionwml.cfg
- data/test/scenarios/overlay_text_demo.cfg
- src/floating_label.cpp
- src/floating_label.hpp
- src/scripting/game_lua_kernel.cpp
- src/scripting/game_lua_kernel.hpp
- utils/emmylua/wesnoth/interface.lua
This returns a label handle which allows you to remove, reposition, or replace the label later.
In addition to all the features of wesnoth.print, you can now specify where the label appears onscreen,
as well as a fadeout time separate from the duration.
> Add wesnoth.interface.add_floating_label as a replacement for wesnoth.print

- src/gui/core/event/dispatcher.cpp
- src/gui/core/event/dispatcher.hpp
- src/gui/core/event/dispatcher_private.hpp
- src/gui/core/event/handler.hpp
> GUI2/Dispatcher: encode event categories in their enum values

- src/gui/core/event/distributor.cpp
- src/gui/core/event/distributor.hpp
This restores the template to mouse_button, but it keeps the struct-based approach for specifying ui_events.
> GUI2/Distributor: further cleanup

- changelog.md
- src/recall_list_manager.cpp
Patch originally from @stevecotton. Aiming to merge before 1.16.3 is tagged (supposedly scheduled for 17th April 2022).
Resolves #6603 (crash with musl implementation of libc)
> Avoid using unit IDs that are no longer valid

- data/test/macros/start_position_common_keep_a_b_c_d.cfg
- data/test/macros/start_position_generic.cfg
- data/test/macros/wml_unit_test_macros.cfg
- data/test/scenarios/firststrike_and_laststrike.cfg
Turn the 4 side setup of the `firststrike_and_laststrike` test into a macro
called `COMMON_KEEP_A_B_C_D`for reuse in other tests.
The comment for `GENERIC_UNIT_TEST` gets a couple of extra paragraphs.
All the files get wmlindent run on them, which reindents `FAIL_IF_NOT`.
The main reason for having these is separate files is Git's fuzzy-patch
matching when merging and rebasing. Having large blocks of identical text
in `wml_unit_test_macros.cfg` can mean the wrong section gets patched.
> Unit tests: make separate files for each starting position

- data/test/macros/start_position_common_keep_a_b.cfg
- data/test/maps/2p_single_castle.map
- data/test/scenarios/reflexive_drains.cfg
- data/test/scenarios/reflexive_poison.cfg
- data/test/scenarios/reflexive_slow.cfg
- wml_test_schedule
Here `apply_to=opponent` means that the weapon special gives the opponent the
ability, the unit that should get poisoned or slowed is the unit that has the
weapon special.
There's a known bug in 1.16, that `apply_to=opponent` check the wrong unit to
see it it's `unpoisonable`, `undrainable` etc. It also checks the wrong unit to
see if it's already poisoned or slowed, so a battle between two units that both
have reverse-poison results in at most one being poisoned.
As 1.16 has already been released, to avoid OOS the test is checking that the
current behavior's known bug is preserved. For the 1.17 branch the four tests
labelled `preserving known bug` will be changed to test the reverse.
Most of the credit for this is Newfrenchy's, as he's already written a fix
and a WML based test. This …
> [1.16] Unit tests for [drains], [poison] and [slows], including apply_to=opponent

- src/game_events/manager_impl.cpp
The problem with this warning was that it didn't include any clue about what
had triggered it - just that there's a broken event somewhere, and it could be
in a scenario, macro, unit_type or even from another add-on if you're using a
non-default era.
When run with `--log-debug=wml`, this makes Wesnoth print out whatever the
contents of the affected [event] tag are.
See https://r.wesnoth.org/t55584 for more details.
> Add debug for "[event] is missing name or id"

- data/campaigns/Sceptre_of_Fire/scenarios/2_Closing_the_Gates.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/5_Hills_of_the_Shorbear_Clan.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/9_Caverns_of_Flame.cfg
Also an idea for the translators' changelog: put a paragraph starting with `po:` in the commit message, so that someone can generate the translators' changelog from the Git changelog.
Example covering this and 2581ab6c87f24abc92c1933d790324cc22cc20e3 / f82079bcc0eb2a24fa0e0ee6559fb390480a77d7 :
```
po: In SoF S09, many strings involving Krawg (a gryphon) assumed that Krawg was
the only flying unit. Similar texts have been added that are used when the player
has gryphon riders too; most of these will be marked as fuzzy versions of the
Krawg-only strings.
> [1.16] SoF S09: A few extra translation hints

- src/gui/core/event/dispatcher.hpp
- src/utils/general.hpp
Already ran it on my fork's CI, so merging immediately.
> Add decltype.

- src/gui/dialogs/title_screen.cpp
- src/gui/widgets/window.hpp
The title screen was being displayed for a single frame in between loading dialogs when either starting a new campaign or loading a game.
This was giving me an aneurysm.
I just turned off drawing of the title screen after these processes are confirmed. The next time the title screen needs to be drawn, it is recreated from scratch anyway, so the existing instance should never actually need to redraw.
> Fix single-frame title-screen flicker when loading a game or starting a campaign.

- src/controller_base.cpp
- src/controller_base.hpp
Fixes #3607
The `controller_base::handle_scroll` function is being called inside a loop that doesn't seem to be limited by anything. So if processing is fast, it loops and scrolls a lot, and if processing is slow, it doesn't.
I made it scroll by an amount proportional to the amount of time between calls to `handle_scroll`.
> Scroll at a consistent speed.

- cmake/FindHistory.cmake
- src/CMakeLists.txt
Hello!
I was super excited to look into `wesnoth`! Amazing work!
While I was getting to know the project I've read through some of the `cmake` finders and thought I may help with some modernization.
I've made `FindHistory.cmake` use lower caps keywords, added an `IMPORTED` target for it and some documentation that looks like the standard `cmake` docs.
Please let me know if this kind of stuff is interesting to you as I'll probably also look into the other `cmake` files during my journey.
Thanks and keep up the great work!
Andrei
EDIT: my editor was configured with `spaces`. I noticed all other cmake finders use tabs. I'll update accordingly
> Refactor FindHistory.cmake

- data/campaigns/Descent_Into_Darkness/_main.cfg
- data/campaigns/Liberty/_main.cfg
After conversion to webp, their images for backgrounds were not being shown.
> [Campaign] [DiD] [Liberty] Fix background image paths

- changelog.md
- data/core/terrain.cfg
Resolves #6643.
I'm not overly familiar with the myriad of terrains but this seems to make sense to me (I tested the changes too). I tried to review everything but it's possible there could be more groupings that could be added.
> Editor: Add some missing terrain groupings

- cmake/FindTranslationTools.cmake
Hello!
I've looked into the translation search file and it was finding a bunch of `gettext` tools in the same manner.
Used a macro to factor that code out a bit.
How I've tested: inside a docker container and I've activated the `ENABLE_POT_UPDATE_TARGET` and built like that.
During my testing I've had cmake in very verbose mode to check for the paths and how it set the variables. All LGTM.
All in all seems to work well and the code is shorter and easier to modify if needed.
The CI seems to also do what I've done so fingers crossed!
Please let me know if you'd like me to further test this change.
Thanks!
Andrei
> Refactor FindTranslationTools.cmake

- INSTALL.md
- cmake/FindVorbisFile.cmake
- src/CMakeLists.txt
A couple of changes for consistency with the other modules + a small commit to state the minimum requirements for Boost and CMake which were a bit behind.
As always, tested as much I could, the `link.txt` file is looking good, same as `compile_commands.json`.
I was thinking, would it be interesting to move the `FindXXX` files in a `cmake/modules` folder? That way they're separate from other cmake utilities.
Also, since I've embarked in this journey, and haven't yet seen the whole history of the project, have there been efforts to unite the SDL2 find? I'm thinking about unifying windows/*nix finders with a couple of tricks but I'd like to see if there have been other efforts. Of course, it's fine even if there weren't and it may actually be impossible, but I'd like to try.
Thanks!
> Refactor find vorbis file cmake

- .github/workflows/ci-scripts/docker.sh
- .gitignore
- CMakeLists.txt
- SConstruct
- scons/sdl.py
- src/CMakeLists.txt
- src/conftests/sdl2.cpp
- src/conftests/sdl2_audio.cpp
- src/conftests/sdl2_image.cpp
- src/conftests/sdl2_jpg.cpp
- src/conftests/sdl2_mixer.cpp
- src/conftests/sdl2_png.cpp
- src/conftests/sdl2_webp.cpp
---
This moves the scons conf tests into their own cpp files rather than being embedded in the scons python scripts, and also has them be executed by cmake before building.
> Have cmake also execute the conftests.

- data/core/editor/help.cfg
po: in wesnoth-help's `<header>text='The files: .map and .cfg' ...`,
the change is just a spelling correction of "scenaro" to "scenario".
Reported by Antro in https://forums.wesnoth.org/viewtopic.php?t=55696
I think string-freeze will be tonight, so planning to merge before that.
> [1.16] Fix a typo in the editor-help

- src/formula/string_utils.cpp
- src/formula/string_utils.hpp
- src/map_command_handler.hpp
Makes suggestions when a command is misspelled as seen below.
*works in mp chats too.
Explanation:
Other commands will be recommended when a third or less of the letters (of the shortest string, either player input or actual command) are wrong. Additions, deletions, swaps and changes all count as 1 error (1 wrong letter).
- Writing 'hlep' recommends 'help' because there is only one error and the word is four letters (1/4 <= 1/3, one swap, string_utils.cpp Line 375)
- Writing 'hel' recommends 'help' because there is only one error and the word is three letters (1/3 <= 1/3, one deletion)
- Writing 'hello' does not recommend 'help' because there are two errors and the word is four letters (2/3 > 1/3, an addition and a change)
- Writing 'aawhiteboard' does not recommend 'whiteboard', even if …
> Add command suggestions

- src/animated.hpp
- src/animated.tpp
* small formatting changes
* small rearrange
> Remove some dead code (maybe a merge defect?)

- data/tools/wmllint
Context:
1. Gorer and Tusklet were added as is, and clashed with UMC units, so ID was changed during 1.15 cycle. Wmllint was not notified of this. Some addons using Gorer/Tusklet that time were not updated so I got Lua unknown unit bug. Also, I think better to not have these 2 lines since UMC still use IDs for this. Any comments? (#5662)
2. Giant Stoat and Frost Stoat was quickly renamed but wmllint was never notified. This might be worth adding to wmllint. (#5344) Some UMC still use deprecated Giant Stoat and aren't aware unless they see deprecated message.
> wmllint: add missing monster ID changes

- .github/workflows/map-diff.yml
The `Map Diff` action failed on this PR: https://github.com/wesnoth/wesnoth/pull/6704
Following [the documentation](https://github.com/peter-evans/create-or-update-comment/tree/v1.4.5), we should replace `pull_request` with `pull_request_target` - and this PR does it
> map-diff: fix missing permission

- .github/workflows/map-diff.yml
On the previous PR (https://github.com/wesnoth/wesnoth/pull/6709), I forgot to change orders when fetching the map files.
Since now it's running using the base branch, it should now use `github.event.pull_request.head.sha`.
I tested it on my test repository and it worked: https://github.com/macabeus/wesnoth/pull/9
> map-diff: fix event name

- .github/workflows/map-diff.yml
Fix again the `map-diff` action, as reported [in this comment](https://github.com/wesnoth/wesnoth/pull/6711#issuecomment-1127240999).
This PR also adds a step to get the previous comment to update it to avoid flooding the PR.
I tested it on my test repository and it's working: https://github.com/macabeus/wesnoth/pull/9
We can see the difference on the fire position and on the farm.
And the comment was updated:
> map-diff: fix get new map

- data/gui/widget/window_tooltip_large.cfg
- data/gui/window/tooltip_floating.cfg
- data/gui/window/unit_attack.cfg
- src/gui/dialogs/unit_attack.cpp
- src/units/abilities.cpp
- src/units/attack_type.hpp
in tooltip, the special and weapon_abilities are listed by stats (damage, attacks and chance to hit) and owner of each is specified.
replace https://github.com/wesnoth/wesnoth/pull/6399 for readibility purpose.
> add tooltip to unit_attack dialogs

- data/campaigns/tutorial/_main.cfg
- data/campaigns/tutorial/lua/hint_message.lua
- data/campaigns/tutorial/scenarios/01_Tutorial_part_1.cfg
- data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg
Based on @stevecotton's #6615, this moves many of the tutorial hint messages into persistent overlay text. I played through the tutorial with these changes and I think it seems pretty good, but it probably needs a little refinement.
> Make tutorial hint messages persistent

- data/campaigns/Northern_Rebirth/scenarios/01_Breaking_the_Chains.cfg
[This](https://wiki.wesnoth.org/EventWML#Multiplayer_safety) says the victory event is unsynced so I just moved the code to the enemies defeated event. Tested that everything works the same and replay goes all the way without OOSs.
Closes #6268
> NR S01 Solve OOS by moving code to synced event

- src/deprecation.hpp
- src/serialization/base64.hpp
Fixes the following issue:
`base64.hpp:23:49: error: 'uint8_t' was not declared in this scope`
and:
`deprecation.hpp:20:22: error: found ':' in nested-name-specifier, expected '::'`
> Fix building with GCC 13.

- src/video.cpp
- src/video.hpp
Changed to render everything to an offscreen texture rather than allowing SDL to do whatever it wants.
This isn't all that undesirable anyway.
From my earlier research, the only thing that doesn't support rendering to texture is some very very old graphics hardware. So likely these days, nothing.
> Potential fix for flickering and corrupted graphics on master branch.

- src/game_events/menu_item.cpp
- src/game_events/menu_item.hpp
- src/gui/dialogs/preferences_dialog.cpp
- src/hotkey/hotkey_command.cpp
- src/hotkey/hotkey_command.hpp
- src/hotkey/hotkey_manager.cpp
- src/play_controller.cpp
This encompasses two closely related changes. First, we now store hotkey_commands in a map instead of
a vector with accompanying index map. Most code did not rely on the command container being contiguous,
and since the commonly used get_hotkey_command was already performing a lookup in the index map, there
wasn't much need to use a separate container. Associative storage makes the most sense here.
The one place that did rely on the command container being contiguous was remove_wml_hotkey. I realized,
however, that it would be much cleaner to eliminate the manual bookkeeping. To this end, I added a new
wml_hotkey_record RAII class. It registers a hotkey_command when created and removes it on destruction.
Using a map for the commands made this even easier, since it doesn't invalidate other …
> Hotkeys: refactored how hotkey_commands are stored and managed (WML hotkeys only)

- data/core/editor/items.cfg
Resolves #6719. I didn't review #5821, I used the files that are actually present in `items` and `scenery` directories.
I'm not sure if the spelling correction for the `holly-water` ID will break anything (I couldn't find any references to it in `cfg` files). Please advise if I got anything wrong for the Lit Brazier, I'm not familiar with the animation syntax.
Back-port will need to wait for 1.16.3 string freeze to end.
> Editor: Add missing items and scenery

- src/editor/palette/common_palette.hpp
- src/editor/palette/editor_palettes.cpp
- src/editor/palette/editor_palettes.hpp
- src/editor/palette/empty_palette.hpp
- src/editor/palette/item_palette.cpp
- src/editor/palette/location_palette.cpp
- src/editor/palette/location_palette.hpp
- src/editor/palette/terrain_palettes.cpp
- src/editor/palette/unit_palette.cpp
Fixes #6724, where scrolling with the mousewheel could reach the last row, but
scrolling with keys or buttons couldn't. Although can_scroll_up() and
can_scroll_down() already existed, can_scroll_down() didn't allow access to the
last line when that line had less than the full number of items. The mousewheel
still worked, because it ignored that logic.
Remove a feature that was seen when the last row is visible - things jumped
between columns to fill the spaces. If you have 10 items, with 4 columns and 2
visible rows then it will appear like this:
```
a b c d
e f g h
```
when scrolling down it used to move items sideways to fill the last line, which
seems bad UI because it made items harder to find:
```
c d e f
g h i j
```
the new code is simpler, and will instead show the following when …
> Editor palettes: allow keyboard scrolling to see the last row

- src/editor/palette/common_palette.hpp
- src/editor/palette/editor_palettes.cpp
- src/editor/palette/editor_palettes.hpp
- src/editor/palette/empty_palette.hpp
- src/editor/palette/item_palette.cpp
- src/editor/palette/location_palette.cpp
- src/editor/palette/location_palette.hpp
- src/editor/palette/terrain_palettes.cpp
- src/editor/palette/unit_palette.cpp
Backport of #6733, just running a CI check before merging.
Fixes #6724, where scrolling with the mousewheel could reach the last row, but
scrolling with keys or buttons couldn't. Although can_scroll_up() and
can_scroll_down() already existed, can_scroll_down() didn't allow access to the
last line when that line had less than the full number of items. The mousewheel
still worked, because it ignored that logic.
Remove a feature that was seen when the last row is visible - things jumped
between columns to fill the spaces. If you have 10 items, with 4 columns and 2
visible rows then it will appear like this:
a b c d
e f g h
when scrolling down it used to move items sideways to fill the last line, which
seems bad UI because it made items harder to find:
c d e f
g h i j
the new code is simpler, …
> [1.16] Editor palettes: allow keyboard scrolling to see the last row

- src/pathfind/pathfind.cpp
When finding the vision path for a unit, that unit's team's vision needs to be used.  This had the potential of causing OOS errors in rare cases on maps with tunnels and at least three sides that do not share vision.
> Fix potential for OOS errors due to wrong viewing side in vision_path

- CMakeLists.txt
- src/CMakeLists.txt
Building wesnoth 1.16.3 with the cmake build system fails for me on macOS 10.15:
```
Undefined symbols for architecture x86_64:
"_CFArrayGetCount", referenced from:
network_asio::load_tls_root_certs(boost::asio::ssl::context&) in libwesnoth-client.a(tls_root_store.cpp.o)
desktop::battery_info::apple::get_iops_battery_info() in libwesnoth-client.a(apple_battery_info.mm.o)
"_CFArrayGetValueAtIndex", referenced from:
network_asio::load_tls_root_certs(boost::asio::ssl::context&) in libwesnoth-client.a(tls_root_store.cpp.o)
desktop::battery_info::apple::get_iops_battery_info() in libwesnoth-client.a(apple_battery_info.mm.o)
"_CFDataGetBytePtr", referenced from:
network_asio::load_tls_root_certs(boost::asio::ssl::context&) in libwesnoth-client.a(tls_root_store.cpp.o)
"_CFDataGetLength", …
```
> macOS: Link with AppKit and Foundation frameworks

- .github/workflows/ci-main.yml
- .github/workflows/ci-scripts/docker.sh
- .github/workflows/ci-scripts/ubuntu.sh
- CMakeLists.txt
- SConstruct
- run_wml_tests
- src/wesnoth.cpp
- utils/CI/play_test_executor.sh
- utils/CI/schema_validation.sh
- utils/CI/test_executor.sh
- utils/dockerbuilds/mingw/Dockerfile
- utils/dockerbuilds/steamrt/Dockerfile
Adds colours to CI output in a variety of places. Most notably:
* compiler error messages (this was actually already working, but now it's explicit)
* cmake progress stages
* test section headers (these were also made more distinct with a border and spacing)
* test section failure messages
* WML validation failures
* gdb backtraces
* boost test suite stages are now displayed, in colour (they weren't previously displayed at all)
The coloured outputs only really work in the linux builds. I'm not sure what the equivalent commands are on mac and windows, if any.
I also ran into a couple other problems during this, so fixed them in some additional commits.
* game::error messages weren't always being displayed on exit
* the MP Test executor was not actually running MP Tests, but duplicating …
> Colourful CI output

- src/display.cpp
- src/display.hpp
- src/draw.cpp
- src/editor/editor_display.cpp
- src/editor/palette/editor_palettes.cpp
- src/editor/palette/tristate_button.cpp
- src/editor/palette/tristate_button.hpp
- src/font/sdl_ttf_compat.cpp
- src/font/sdl_ttf_compat.hpp
- src/game_display.cpp
- src/gui/widgets/minimap.cpp
- src/gui/widgets/minimap.hpp
- src/picture.cpp
- src/picture.hpp
- src/sdl/surface.cpp
- src/sdl/surface.hpp
- src/show_dialog.cpp
- src/tests/test_filesystem.cpp
- src/theme.cpp
- src/units/drawer.cpp
- src/video.cpp
- src/video.hpp
- src/whiteboard/attack.cpp
- src/whiteboard/suppose_dead.cpp
- src/widgets/menu.cpp
- src/widgets/menu.hpp
- src/widgets/menu_style.cpp
- src/widgets/textbox.cpp
- src/widgets/textbox.hpp
This is to address some bugs preventing the game from working on MacOS, raised on Discord.
It removes the fake compatibility framebuffer that was being used to maintain old code that expected to be able to draw directly to the screen. However it does so in a way that is likely to be very bad for performance. Or rather, the subsequent commits that bring performance back into line haven't been pulled in to this PR.
It needs some brief testing from someone with a less fast system than i have. Previously there were reports of slowness in the editor, but i don't experience it. Two things might cause slowness: scrolling around a large map in game, and scrolling the tool pallete in the map editor. If these are acceptable, then this should be merged.
Actually that editor issue might also be in …
> merge some commits from the base of new_rendering, should fix problems with rendering on MacOS in master

- src/gui/core/canvas.cpp
Should fix the lua console, and the credits screen.
> Fix text positioning when clipped to a viewport.

- data/gui/widget/panel_box_display.cfg
- data/gui/widget/window_borderless.cfg
- data/gui/widget/window_default.cfg
- data/schema/gui.cfg
- src/build_info.cpp
- src/controller_base.cpp
- src/draw.cpp
- src/draw.hpp
- src/gui/core/canvas.cpp
- src/gui/core/canvas_private.hpp
- src/gui/core/event/handler.cpp
- src/help/help_topic_generators.cpp
- src/video.cpp
- src/video.hpp
- src/widgets/menu.cpp
This adds back the smooth scaling image mode, and also adds a new tiling mode "tile_highres" which can be used to tile images in full high-dpi output resolution rather than game resolution.
This is useful for texturing effects, such as the image that is used to texture window backgrounds which has been updated to use this tiling mode.
I didn't make it the default, because it would break anything relying on the previous sizing. The other modes "tile" and "tile_center" both tile images in draw-space - so their drawn sizes will match with sprite scales and with other sizing in WML.
Mostly just putting this up for the CI check.
> High-res tiled textures

- data/campaigns/Secrets_of_the_Ancients/gui/zombie_recruit_dialog.cfg
There was an error `error gui/parse: horizontal_grow and horizontal_alignment can't be combined, alignment is ignored.` when opening the recruit dialog for corpses in SoTA.
I removed horizontal_grow in favour of horizontal_alignment here, as that matches what is used in other blocks. There seems to be no visible difference.
There were also some unnecessary `..` which seemed to be attempting to concatenate strings in WML. It looks like this is a lua thing? They were visible in-game like "..Traits.." and "..Attacks..". I removed them and it seems to work fine now?
> Fix some SoTA zombie recruit dialog errors

- src/events.cpp
- src/events.hpp
- src/game_config_manager.cpp
- src/game_initialization/multiplayer.cpp
- src/gui/dialogs/loading_screen.cpp
- src/gui/dialogs/loading_screen.hpp
- src/wesnothd_connection.cpp
The programming interface is still the same. Draw and input events are now processed when the worker function calls loading_screen::progress().
This has two main repercussions:
1. exceptions will no longer be silently eaten by the loading screen,
2. loading screen animations will not update unless progress() is called.
In order to update animations in a timely fashion... well, for me they already update so fast as to be nigh-instant. I'm not really sure what ever takes any significant time to load.
If there are actually sections of loading code that take significant time, some sort of `loading_screen::spin()` function shouild be added, that simply lets the loading screen update the spinner animation. Worker functions should call this periodically while performing long-duration tasks.
An …
> De-thread the loading screen. Load in the main thread.

- data/ai/micro_ais/scenarios/animals.cfg
- data/core/terrain-graphics.cfg
- data/core/units/orcs/Assassin.cfg
- data/scenario-test.cfg
- data/tools/wmlindent
There's been a persistent wmlindent warning in the CI logs for awhile now, so I thought I'd fix it. This prevents wmlindent from treating commented-out quotes as opening or closing a string.
I also removed several ignore directives that were clear workarounds for the bug, as well as a clearly-pointless pair in terrain-graphics.cfg. As you can see, there are no actual changes in the wmlindent run as a result, other than the removal of trailing whitespace.
> Fix wmlindent quote detection

- CMakeLists.txt
- INSTALL.md
- SConstruct
- changelog.md
@doofus-01 reported not being able to build master with SDL 2.0.8. [SDL_RenderCopyF](https://wiki.libsdl.org/SDL_RenderCopyF) and [SDL_RenderCopyExF](https://wiki.libsdl.org/SDL_RenderCopyExF) are only available from SDL 2.0.10 onwards.
These are the only instances of SDL 2.0.8 that I could find. I do not know if there are other places where references to SDL need to be updated.
> SDL: Increase requirement to 2.0.10

- data/test/scenarios/test_lua_name.cfg
- src/scripting/lua_kernel_base.cpp
- wml_test_schedule
Complete with a unit test!
The test results in PASS_BY_VICTORY if it fails, which is a bit weird, but it does work.
There was a comment on this commit noting that it won't work without the events PR (#5663), but I suspect that comment is outdated, so I'm opening this to test the CI.
> Fix load_string() ignoring the passed chunk name

- src/config.hpp
This PR is just to test that CI passes, in case this syntax breaks in MSVC or something.
> Make predicate optional in config::remove_children

- src/picture.cpp
- src/picture.hpp
I also added some diagnostics, and did some minor cleanup.
After checking the diagnostics, i set it to skip the surface cache automatically when loading textures from image files unmodified. These get cached as textures only. Sometimes this causes images to be loaded twice when the surface is needed later, but not very frequently.
I left it caching surfaces when loading IPF modified textures, as these turned out to be often reused for other image loading operations. It could be revisited after hardware-acceleration conversion is more complete.
I'm considering exposing the cache skip to WML for edge-case use of animations (see #2915 ), but it would be kind of ugly to do for halos, so i'm a bit reluctant.
Currently the point of this is mostly to avoid keeping copies of images both in …
> Add options to skip adding images to the surface and texture caches

- src/draw.cpp
- src/sdl/utils.cpp
- src/sdl/utils.hpp
- src/sdl/window.cpp
- src/video.cpp
Aimed at fixing #6799.
According to the SDL bug linked there this was reported in SDL 2.0.15 and should have been fixed in 2.0.18. So i've set it to draw rectangles as four individual lines when linked against the affected SDL versions.
If the problem crops up again for others, the version check could be extended.
I'm assuming the problem doesn't also occur for lines.
> Draw rectangles as lines for some SDL versions.

- src/display.cpp
- src/game_display.cpp
As [this](https://github.com/wesnoth/wesnoth/blob/master/src/display.cpp#L2521-L2524) comment says, we are only redrawing haloes if anything else in the map is invalidating at least one hex.
`halo_man_->unrender(invalidated_)` actually invalidates the hexes covered by haloes which need to be updated, so i'm just moving the call outside the if-clause.
> Fix #4961 (halo animations sometimes freeze)

- data/lua/wml/harm_unit.lua
Discussed on the forum.
https://forums.wesnoth.org/viewtopic.php?f=4&t=53620
> [harm_unit] fix secondary_attack animation

- data/core/units/humans/Loyalist_Javelineer.cfg
Pikeman and Swordsman have special notes denoting their resistance increases...but the Javelineer got ignored?
Javelineer has 40% pierce resistance (identical to the Pikeman)
> [Units] [Loyalists] Add missing resistance special notes to Javelineer

- data/ai/lua/ai_helper.lua
- data/ai/micro_ais/mai-defs/animals.lua
- data/ai/micro_ais/mai-defs/bottleneck.lua
- data/ai/micro_ais/mai-defs/escort.lua
- data/ai/micro_ais/mai-defs/fast.lua
- data/ai/micro_ais/mai-defs/guardian.lua
- data/ai/micro_ais/mai-defs/healers.lua
- data/ai/micro_ais/mai-defs/misc.lua
- data/ai/micro_ais/mai-defs/patrol.lua
- data/ai/micro_ais/mai-defs/protect.lua
- data/ai/micro_ais/mai-defs/recruiting.lua
- data/ai/micro_ais/micro_ai_helper.lua
- data/ai/micro_ais/scenarios/guardians.cfg
- data/ai/micro_ais/scenarios/lurkers.cfg
- data/ai/micro_ais/scenarios/swarm.cfg
- src/teambuilder.cpp
This adds checks for the types of [micro_ai] tag parameters, addressing #6408.  It also adds warning messages if a parameter specified in a [micro_ai] tag is not valid for that MAI.
And while I was at it, I also added a couple bug fixes that I came across while working on this.
I am not planning to backport this to 1.16, as the risk of screwing something up in the stable series is too high.
> Mai parms tests

- data/game_config.cfg
- data/schema/core/config.cfg
- src/display.cpp
- src/game_config.cpp
- src/game_config.hpp
- src/game_display.cpp
- src/gui/core/canvas.cpp
- src/help/help_text_area.cpp
- src/show_dialog.cpp
- src/video.cpp
- src/whiteboard/attack.cpp
- src/whiteboard/suppose_dead.cpp
- src/widgets/menu_style.cpp
- src/widgets/textbox.cpp
Mostly these just involved checking if something was okay.
A couple unused things were removed.
1. The `hex_brightening` config option. This was not used, and from the looks of it has not been for quite some time. It was added in 2010 for testing the mouseover effect. The current effect is hardcoded and ignores this value.
2. There was a function dealing with "report" images, which actively analyzed them for transparency and automatically clipped them. This is ridiculous and i removed it some time ago. No adverse effect has been reported.
I originally thought "reports" were maybe some automatically generated graphs or something. But no. It is just the name for the automatically updated UI sections of the game display, such as the amount of village gold etc.. The icon images do not need …
> Address various minor highdpi TODOs

- src/color.hpp
- src/sdl/point.cpp
- src/sdl/point.hpp
- src/sdl/utils.cpp
This changes `color_t` and `point` to be thin wrappers over `SDL_Color` and `SDL_Point`.
They already had the same members, so usage is completely unchanged.
Aside from being a bit tidier to define, the practical differences are:
1. converting to and from the SDL versions no longer requires copying the data in most cases
2. color_t and point references can be passed directly to SDL functions requiring SDL_Color and SDL_Point pointers.
That second one was mostly why i wanted this.
> Inherit from SDL types for point and color_t

- src/menu_events.cpp
This adds an error message when the `:unit` debug command fails because no unit is selected or hovered over, as suggested in #6116
> Add no-unit error message for unit debug command

- src/actions/attack.cpp
Events during attacks may modify either of the units involved. If, as a result, one of the units does not have a weapon of the type used any more, this previously caused a segmentation fault in unit_attack() in udisplay.cpp. The solution is to set the remaining number of strikes for the unit to zero. This prevents that unit from striking again, but lets the opponent continue its attack.
I have confirmed that this fixes both #4927 and #5914. That's also the reason why this is based on 1.16, because the save provided in one of the issues is for 1.16.  Obviously, if this is merged, it should be forward ported as well.
> Fix seg fault when weapon is removed during attack

- src/filesystem.cpp
- src/game_launcher.cpp
- src/log.cpp
- src/log.hpp
- src/wesnoth.cpp
Making this a PR only to make sure I am not missing something and CI passes.
> Sound path

- src/color.hpp
- src/display.cpp
- src/display.hpp
- src/floating_label.cpp
- src/game_display.cpp
- src/image_modifications.cpp
- src/sdl/utils.cpp
- src/sdl/utils.hpp
- src/units/drawer.cpp
- src/units/drawer.hpp
- src/units/frame.cpp
I managed to get an effect that reproduces previous behaviour.
Some improvements could be made for things like the unit poisoning tint effect, but it would probably be better to revisit this when using GPU shaders is a possibility.
For now this does some semi-nasty hacks involving blitting one to four copies of the image depending on the effects used. This is still very cheap to do in hardware, so is fine for now. This should greatly improve performance for effects that animate colour tint, such as the flashing effect when clicking on an owned unit and some missile effects.
The tint effect is 1:1 identical to that in 1.16 for fully opaque pixels. It may differ slightly for translucent pixels. There's not much that can be done about that without shaders.
> Perform unit highlight and frame tint effects in hardware

- src/filesystem.cpp
- src/game_launcher.cpp
- src/log.cpp
- src/log.hpp
- src/wesnoth.cpp
This logs the provided text always, and without adding the log domain or timestamp. This is meant to be a replacement for std::cerr/std::cout, but that also goes through the normal logging logic as well.
> Add PLAIN_LOG logging macro.

- changelog.md
- data/core/units/drakes/Arbiter.cfg
- data/core/units/drakes/Warden.cfg
Previously, part of these drakes were popping out of the water during attack and defense animations because their images were bigger than a hex. This adds hand-picked submerge values that makes the animation feel more connected on water.
Closes https://github.com/wesnoth/wesnoth/issues/6508
> Fixed Warden’s and Arbiter’s animations popping on water tiles.

- src/color.cpp
- src/color.hpp
- src/draw.cpp
- src/sdl/point.cpp
- src/sdl/rect.cpp
These were somewhat inconsistent, and could be difficult to read. This only affects how these are written to an ostream.
It's basically as discussed in https://github.com/wesnoth/wesnoth/pull/6814#issuecomment-1171870532
The previous representations were:
```
color_t(255, 60, 140, 255) --> "255 60 140 255"
point(10,25) --> "10,25"
SDL_Rect(3, 15, 22, 89) --> "x: 3, y: 15, w: 22, h: 89"
```
The new representtions are:
```
color_t(255, 60, 140, 255) --> "#ff3c8c"
color_t(255, 60, 140, 128) --> "#ff3c8c80"
point(10,25) --> "(10,25)"
SDL_Rect(3, 15, 22, 89) --> "[3,15|22,89]"
```
The vertical bar in the rect representation is to differentiate the second pair as a size, not a position, and also (along with the square brackets) to make it clear that it's a rect, not some other 4-integer-element …
> Tweak debug representations of color_t, point and SDL_Rect

- src/draw.cpp
- src/draw.hpp
- src/font/text.cpp
- src/minimap.cpp
- src/sdl/point.cpp
- src/sdl/point.hpp
- src/sdl/texture.cpp
- src/sdl/texture.hpp
- src/video.cpp
- src/video.hpp
Added some utility methods to `sdl::texture`, scalar multiplcation and division for `sdl::point`, and changed CVideo render target functions to use `sdl::texture` in stead of `SDL_Texture*`
> Some miscellaneous additions and minor refactoring

- projectfiles/CodeBlocks/campaignd.cbp
- projectfiles/CodeBlocks/tests.cbp
- projectfiles/CodeBlocks/wesnoth.cbp
- projectfiles/CodeBlocks/wesnothd.cbp
This is for stop using of deprecated variable in boost
> add GLIBCXX_USE_DEPRECATED=0 in codeblock projectfiles

- src/gui/widgets/debug.cpp
3874fe5f0 compiled okay on the CI, but it seems it was relying
on an implicit include somewhere. GCC 11.3.0 requires this.
> Re-add an <fstream> include for GCC 11

- .github/workflows/ci-main.yml
The only suggestion that came up was checking to see if something in this file changed between when the vcpkg cache is used vs isn't used, so... print out the contents of a random dependency and then check back later I guess.
> Print vcpkg_abi_info.txt contents.

- src/game_initialization/create_engine.cpp
- src/gui/dialogs/multiplayer/mp_create_game.cpp
- src/terrain/translation.cpp
This PR causes all map errors to be handled identically in the Create Game dialog.  The behavior is now the same for all errors, as well as for maps provided via both `map_file=` and `map_data=`; errors are always displayed in the description under the minimap; none of them causes the game to fall back to the main menu; and none of them allows advancing to the next dialog.
This addresses the additional issues discussed after #1346 was closed.
> MP Create Game dialog: improve error handling

- src/log.cpp
- src/log.hpp
- src/log_windows.cpp
- src/server/campaignd/server.cpp
- src/server/common/server_base.cpp
- src/server/common/simple_wml.cpp
- src/server/wesnothd/server.cpp
- src/wesnoth.cpp
- src/widgets/menu.cpp
- src/widgets/widget.cpp
We don't want std::cerr to be used at all, and std::cout is only for certain special
cases such as command-line responses.
Therefore, log.hpp should not include <iostream>.
This is open as a PR to make sure there are no CI failures.
> Don't include <iostream> in every single file

- src/config.hpp
- src/server/campaignd/server.cpp
This adds a `config::copy_or_remove_attributes()` method with the semantics needed to solve issue #6284 in campaignd, and uses it instead of `config::copy_attributes()` in campaignd. The latter is now unused in the overall codebase, but I'm leaving it intact with new documentation in case it's useful to someone else in the future.
> campaignd: Drop removed pbl attributes on upload if applicable

- src/game_events/manager.cpp
> Fix assertion when opening the gamestate inspector while disabled events haven't been cleaned up

- data/core/macros/abilities.cfg
It affects all villages, water villages included. I don't see it practical to try to recreate the described behaviour cause concealment's been working for all village types for 12 years already https://github.com/wesnoth/wesnoth/commit/630b08078c8c14a18a8e046166af6a8ebc0d5f5a the commit made Oct 2008. So let's just fix the description to reflect the reality
> Fix the description of concealment

- src/picture.cpp
- src/sdl/utils.cpp
Images that are not 72x72 are centered and cropped before masking.
This fixes the inconsistent masking in SoTA (#6118).
> Handle non-hex-sized images when cropping to hex

- doc/man/wesnoth.6
- src/commandline_options.cpp
- src/filesystem.cpp
- src/filesystem.hpp
- src/log.cpp
- src/log.hpp
- src/log_windows.cpp
- src/log_windows.hpp
- src/wesnoth.cpp
This option sets up writing both the cerr and cout streams to a log file, as well as pulls the log rotation logic out of log_windows.*pp into the general logger.
Note that this is meant for usage on macOS and Linux, not Windows. log_windows.*pp has additional functionality in it, as well as a fair bit related to the --wconsole option.
---
Testing locally this seems to work fine, though the fact that this wasn't done years ago makes me wonder if there's something obvious that I'm missing.
> Add --log-to-file command line option.

- data/scenario-test.cfg
This is for testing #6589, as well as looking at how ellipse and HP bar move with sprite in progressive y= key
> 1.17 (test scenario) out-of-hex unit animation tests

- data/campaigns/Under_the_Burning_Suns/scenarios/11_Battle_for_Zocthanol_Isle.cfg
Resolves #6503. I tested this both with and without music enabled to the same level as the sound effects.
At worst, the player might not notice if music is on and louder than sound effects, but because the bat sound repeats 7 times it is more likely the player will notice. It also represents the fact that there are multiple bats that await.
At best, if the player falls under the demographic of players that like to play with music off, they will definitely hear the sound.
Requesting permission to merge.
> [UtBS] Add series of bat screeches in the Zochtanol Isle scenario

- data/campaigns/Heir_To_The_Throne/scenarios/04_The_Bay_of_Pearls.cfg
- data/core/editor/items.cfg
- data/core/macros/image-utils.cfg
- data/core/macros/items.cfg
- data/lua/wml/items.lua
- data/scenario-test.cfg
- data/schema/core/actionwml.cfg
- data/schema/core/addons.cfg
- src/display.cpp
- src/display.hpp
- src/editor/action/mouse/mouse_action_item.cpp
- src/editor/map/map_context.cpp
- src/overlay.hpp
- src/scripting/game_lua_kernel.cpp
This is addressing #1146.
As per the comments in #1146 I made a change to simply use the same submerge code as units, for items. So when an item is placed on water it partially submerges. This fixes the visual appearance when a unit is swimming on top of the item, and also IMO makes items in water look a whole lot better.
There are one or two situations in which the item probably should not be submerged. It can be seen below, with the target circle. This could be fixed by using "halo" in stead of "image" in the item definition, so it draws over units in stead of under them.
It might make sense to have a separate "floating" item type, like say for debris that is actually floating on the water. There would need to be an implementation to split the item into two halves, one drawn in front of …
> Submerge items on water, just like units

- src/font/text.cpp
Resolves #6908.
The work-around is no longer required due to 06b02471 (#6685).
I checked both Windows and Linux/X11 builds and the text rendering looks good to me in both. I'll merge after CI checks, assuming no objections.
> Revert Windows ClearType CA work-around

- data/campaigns/Eastern_Invasion/lua/bandits.lua
- data/campaigns/World_Conquest/lua/campaign/enemy.lua
- data/campaigns/World_Conquest/lua/campaign/scenario.lua
- data/campaigns/World_Conquest/lua/game_mechanics/dropping.lua
- data/lua/wml/move_unit.lua
I tested and confirmed the deprecation warning and resolution for the bandits event in Eastern Invasion S5.
The only place I could find a `fire_event` within a `[move_unit]` block was the MP version of Legend of Wesmere S4 so I didn't test that one. I also didn't test World of Conquest.
> Replace deprecated wesnoth.fire_event with wesnoth.game_events.fire

- src/gui/core/window_builder.cpp
- src/gui/dialogs/debug_clock.cpp
- src/gui/dialogs/debug_clock.hpp
- src/gui/dialogs/modeless_dialog.cpp
- src/gui/dialogs/modeless_dialog.hpp
- src/gui/dialogs/tooltip.cpp
- src/gui/widgets/window.cpp
- src/gui/widgets/window.hpp
- src/tests/gui/test_gui2.cpp
Not only was it conceptually confusing that a modeless dialog was not a window, but it causes several inefficiencies and general incapabilities when converting to use the new draw system.
So here i made a modeless dialog a window. This was the easy one as there are basically no modeless dialogs right now. Basically just tooltips and the debug clock.
As a note this will slightly invalidate #5561 which also uses a modeless dialog. But any changes are minimal and can be tacked on to whichever gets merged second.
The window builder finalization stuff was moved to a method of `window` so it can be called in the modeless dialog constructor.
As far as practical usage changes go... most stuff that was previously in "post_build" and "pre_show" virtual callbacks can simply go into the subclass …
> Make modeless_dialog an actual window

- data/gui/window/file_progress.cfg
- projectfiles/Xcode/The Battle for Wesnoth.xcodeproj/project.pbxproj
- source_lists/wesnoth
- src/addon/client.cpp
- src/addon/manager.cpp
- src/addon/manager.hpp
- src/gui/dialogs/file_progress.cpp
- src/gui/dialogs/file_progress.hpp
- src/tests/gui/test_gui2.cpp
This implements an add-on extraction progress dialog that does not actually run its own event loop, allowing the caller to take ownership of it (`display()` static method) and update its state using a callback function object.
The dialog is roughly identical to the network progress dialog, except for the greyed out Cancel button. This is intentional so that the dialogs can be transitioned more or less seamlessly into each other by the add-ons client code.
In order to avoid stalling the extraction process in UI code, the callback is invoked for every single file, but the dialog's progress update method places a time restriction on GUI2 API calls of 120 milliseconds -- this is a good throttle interval that allows add-ons to be extracted in about the same amount of time as before while still …
> addon/client: Add file operation progress dialog for installing add-ons

- data/campaigns/Under_the_Burning_Suns/scenarios/06b_In_the_Domain_of_Dwarves.cfg
One of the subitems of #6197. When Jorgin dies, the map scrolls to the place where the detonation will occur. Some shroud is removed so that the player can see the event unfold.
> Utbs s6 add scroll to detonation event

- src/display.cpp
- src/display.hpp
update_fps_label() uses a static variable to track current frame sample.
This causes division by zero while loading a save file if the
variable was previously equal to 9.
The commit changes the variable to private member to match its lifetime
with a lifetime of frametimes_ circular buffer.
Fixes: #5670
> Fix crash in update_fps_label()

- .github/workflows/ci-main.yml
- CMakeLists.txt
- src/CMakeLists.txt
- vcpkg.json
Relevant vcpkg PR: https://github.com/microsoft/vcpkg/pull/25763
> Fixed vcpkg build issue for port update to 2.6.1

- data/campaigns/Winds_of_Fate/scenarios/04_Journey.cfg
The first of four sea serpent spawn messages was not firing, because it was set to fire before its speaker appeared. The bug was introduced last year in a balance update affecting the sea serpent spawn rate, and was minor enough that it was missed during several play tests.
This simple fix is fully tested.
> WoF S4: fix message not firing

- cmake/FindSDL2.cmake
@bencsikandrei please would you review this? I can only add project members as reviewers, but you're probably the best reviewer.
In SDL 2.24.0, the CONFIG method doesn't add a target for libSDL2main. Seen on Debian Unstable, and seems to be https://github.com/libsdl-org/SDL/issues/6119 which is reported upstream on macOS. For consistency's sake, let's add a phony library we can link with, which is also the workaround that upstream suggests in the bug report.
> CMake 2.24.0: Workaround for missing SDL2::SDL2main

- src/server/wesnothd/game.cpp
Implements #6641
Just add "time" in the "speak" command that the server sends, I guess it should be fine?
I push to master, but I wonder, can it be backported into 1.16? Would be nice if possible
> Timestamping server messages

- data/campaigns/Winds_of_Fate/units/Outrigger.cfg
- data/campaigns/Winds_of_Fate/units/Stymphalian.cfg
- data/campaigns/Winds_of_Fate/units/Wyrm.cfg
1. Outrigger max XP is now 100
2. Stymphalian XP set to 50
3. Wyrm XP set to 50
XP value conventions for units with no level ups
- Level 0: 25
- level 1: 50
- level 2: 100
- level 3: 150
- level 4: 200
- level 5: 250
- level 6: 300
> WoF/Units: Adjust XP value oversights in the campaign units.

- src/units/map.cpp
Resolves #6933 - it was suggested there to just remove the error message altogether.
> Remove obsolete reference to gna.org

- data/tools/wmllint
We're had at least two people look at the "good first issue" list, pick up
the wmllint warnings, open a PR, and then get a response that these .pngs
shouldn't be added by default. That's not a welcoming introduction.
IIRC we didn't get full consensus that these should never be added, but I
think it's time to open a "just drop that code, no options" PR. If someone
wants it back in a subset of circumstances, they can always create a PR to
readd it along with adding an option to enable it.
Inspired by #6990, previously discussed in #5164.
> wmllint: stop adding wesnoth-icon.png to messages

- data/ai/lua/battle_calcs.lua
The method used in the battle_outcome() function is somewhat simplified compared to the default engine calculation and faster in the vast majority of cases, but it can become extremely slow when the combined number of strikes of the attacker and defender is very large.
This was reported as a complete stalling of the game in HttT The Princess of Wesnoth (which uses the Assassin Squad Micro AI) in combination with the Less Random modification.  Details are given in [this forum thread](https://forums.wesnoth.org/viewtopic.php?t=56116).
> Lua AI: speed up battle_calcs.battle_outcome in extreme cases

- src/mouse_events.cpp
- src/mouse_events.hpp
If it's another player's turn, then movement points will be reset in a refresh
phase and it's not useful to show current movement.
Partially reverts 978229c247 (af0968d9c3 on 1.16), using the old logic for
the movement range but the allies-based logic for goto_x,goto_y information.
Fixes #6716.
Note: bug #6997 is reproducible in all three of these combinations, so I'm treating it as an orthogonal issue:
* without this PR
* with this PR
* with a full revert of 978229c247
> Show units' max move ranges, unless it's the owner's turn

- src/preferences/advanced.cpp
If unset it has different behaviour in dev branch when checked (defaulting to yes). However this was not reflected in the actual prefs dialog which clearly said that it was "no".
This is a bit ugly... but well the default is set statically in `data/advanced_preferences.cfg`, so...
Also usage of bool preferences and how the default values work is horribly wrong everywhere, as the default value must be given by the code that tries to access the value. But they don't know the default value. So they make something up. Which leads to situations such as this one where it does not match the actual default value and wrong shit happens.
> preferences: Adjust show_deprecation default to coincide with usage

- src/mouse_events.cpp
- src/mouse_events.hpp
Backport of #6998.
If it's another player's turn, then movement points will be reset in a refresh
phase and it's not useful to show current movement.
Partially reverts 978229c247 (af0968d9c3 on 1.16), using the old logic for
the movement range but the allies-based logic for goto_x,goto_y information.
Fixes #6716.
(cherry picked from commit ae4ecd17e4c617af72c8c2e00bca014dcfb1b993)
> [1.16] Show units' max move ranges, unless it's the owner's turn

- data/campaigns/Descent_Into_Darkness/scenarios/08_Alone_at_Last.cfg
Resolves #7005.
I think this is perhaps overkill, but clearly at least some people notice the discrepancy in the dialogue if the scenario is completed before certain factions have appeared.
I consider 'paladins' as a generalisation for Cadaeus' forces, so there doesn't need to be yet another piece of dialogue differentiating whether or not Cadaeus is alive. Similarly, I generalise Dela's forces as 'Dela's men' so it shouldn't matter if Dela is alive or not. Regardless, the underlying bug report requires that there be work for the translators.
I think this scenario file is the same in 1.16 branch, so could be back-ported. I have tested the three phases as stated in the commentary: before Cadaeus appears, after Cadaeus appears but before Dela appears, and after Dela appears. It makes sense …
> DiD S8: Handle situations where factions have not yet appeared

- src/preferences/credentials.cpp
The AES implementation wasn't working, so someone using macos will need to investigate that in the future probably. For now though RC4 isn't deprecated yet on macos.
> Change macos back to using RC4.

- data/core/units/monsters/Caribe_Hunter.cfg
- data/core/units/monsters/Fire_Wraith.cfg
- data/core/units/monsters/Horse.cfg
- data/core/units/monsters/Horse_Black.cfg
- data/core/units/monsters/Horse_Great.cfg
- data/core/units/monsters/Scarab.cfg
- data/core/units/monsters/Seahorse.cfg
Certain units with no level up/advancements were not adhering to the max XP conventions which had been set for core units. This rectifies such oversights.
| Level | Maximum XP |
| ----- |  -------------- |
| 0 | 25 |
| 1 | 50 |
| 2 | 100 |
| 3 | 150 |
| 4 | 200 |
| 5 | 250 |
| 6 | 300 |
Note: Only Applicable for Units with no further advancements being available apart from `{AMLA_DEFAULT}`
Note 2: Some commits here should/can be cherry-picked since these units exist in 1.16 as well (all except the Hunter Caribe)
> [Units] Fix XP conventions oversight in some monster/horse Units

- src/gui/widgets/unit_preview_pane.cpp
- src/reports.cpp
To allow potential line breaks between the hexagons in MP tooltips, this pull request inserts (invisible) Unicode zero width space characters between them.
Previously, I have already used this little trick for the hexagons in the help browser.
With this pull request, the same thing is done for the MP tooltips in the sidebar and the recruitment dialog, which covers all places where MP hexagons appear.
This only makes a visible difference if a unit's movepoints are extremely large, quite beyond any mainline unit, but I see no drawbacks.
> MP tooltips: allow line breaks between hexagons by using Unicode zero width space

- data/gui/window/lobby_main.cfg
- src/game_initialization/connect_engine.cpp
- src/game_initialization/lobby_data.cpp
- src/game_initialization/lobby_data.hpp
- src/gui/dialogs/multiplayer/lobby.cpp
- src/gui/dialogs/multiplayer/lobby.hpp
Bot-hosted games are now shown in a separate tab from player-hosted games, based on the new `auto_hosted` attribute on the game creation WML. This is not something that's available to be selected during game creation since it's assumed it will instead be set by the bot implementation.
Resolves #6939
> Separate player-hosted games and bot-hosted games into tabs

- data/core/units/dunefolk/Wyvern_Rider.cfg
This is a level 4 unit and so, by convention, `experience=` should be `200`.
> Units: Wyvern Rider XP set to 200

- run_wml_tests
For example, `run_wml_tests --filter backstab` runs only the tests listed in `wml_test_schedule` that have `backstab` somewhere in their name.
I haven't tried to match the Boost test framework's [syntax for filters](https://www.boost.org/doc/libs/1_80_0/libs/test/doc/html/boost_test/utf_reference/rt_param_reference/run_test.html), because they expect tests to be organised into suites.
GTest's `--gtest_filter` agrees on the name and using regexps. That framework also allows negative patterns and multiple regexps separated by colons, but I'm not spending time adding that, nor does it seem necessary for our purposes.
> run_wml_tests: add an option to filter tests by name

- data/core/units/monsters/Giant_Scorpion.cfg
- data/core/units/undead/Corpse_Soulless.cfg
- data/core/units/undead/Corpse_Walking.cfg
This accommodates the variation of the Giant Scorpion, the Sand Scuttler.
Well, compare the resistances of the Giant Scorpion base variation and the Walking Corpse scorpion variation...do they match? No, They don't.
The WC/SL variation of the scorpion coincidences perfectly with the sand scuttler variation of the Giant Scorpion, not the base.
Oversight developed from b9e67f459840a01a3d453570cd6ceec31ef10ac6
Closes #7015
> Units: add sand_scorpion variation to Walking Corpse and Soulless

- src/gui/widgets/unit_preview_pane.cpp
- src/help/help_topic_generators.cpp
- src/reports.cpp
Attempting to mitigate #7017.
It's a subtle difference, but I think it may help ease the complaints of 'garishness' regarding the recent addition to the help page. (Also applied to the side bar reports, etc.)
Before:
After:
> Reduce the saturation of hex colour for movement points

- data/tools/wmllint
Allows updating terrain codes for stone floors and wooden floors by Wmllint tool. Accommodates #7042
> Wmllint: add new terrain code updaters

- src/units/unit.hpp
the 'attacks' abilities don't be checked by special-id/type_active
> Fix 'attacks' abilities not checked(1.17).

- data/test/macros/generic_backstab_test.cfg
- data/test/scenarios/backstab.cfg
- data/test/scenarios/replace_special_with_filter_in_attack_event.cfg
- wml_test_schedule
I'm using the existing backstab test as a framework for the new tests, but this means they have to be in the same file as the backstab test.
@Pentarctagon, this is probably a good time to discuss your plans for reorganising the tests - where would the common code of the `TEST_BACKSTAB` macro go?
> Unit tests for changing filters in [event]name=attack

- data/campaigns/Heir_To_The_Throne/utils/httt_utils.cfg
- data/campaigns/The_South_Guard/maps/06a_Into_the_Depths.map
- data/core/units.cfg
With the same unwalkable terrain movement and defense as the Quenoth versions of these units. Makes them behave as true flying/floating units as their wings, movetype name and other statistics suggest, while opening up interesting game play possibilities.
> Give Shyde and Sylph unwalkable statistics

- src/build_info.cpp
- src/gui/dialogs/game_version_dialog.cpp
- src/gui/dialogs/game_version_dialog.hpp
- src/log.cpp
- src/log.hpp
- src/log_windows.cpp
- src/log_windows.hpp
Also moves the last bit of potentially common code from log_windows into the base logger.
---
To be honest I'm tempted to tinker with it more to see if any more of the windows-specific code needs to be windows-specific, but I also don't have a Windows machine to actually test it out. Also a lot of it is around that weird console behavior windows has.
@Vultraz Can you build this PR and just make sure that the Windows logging to file still works?
> Show the log directory in the build info on non-windows platforms.

- data/lua/diversion.lua
- data/lua/feeding.lua
- data/lua/wml-tags.lua
- data/lua/wml/harm_unit.lua
- data/lua/wml/move_unit.lua
Guess after all this years I touch the Lua stuff behind the API …
One commit for #5158, other I found while testing for e3e80b4.
This all comes down to this comment:
https://github.com/wesnoth/wesnoth/blob/de9311e2622a9603834113cfd7f3fa2edb4de344/src/scripting/game_lua_kernel.cpp#L2583-L2584
It's the same method `[unstore_unit]fire_events=…` uses internally, just undocumented.
@CelticMinstrel, @gfgtdf can this go in as is?
> avoiding unit placed events

- data/core/units/monsters/Horse.cfg
The male variation of the dark horse unit is using the female translatable string.
Fix by making a male specific string to allow accurate translation.
> Fix male Dark Horse unit name

- data/campaigns/Sceptre_of_Fire/scenarios/9_Caverns_of_Flame.cfg
Visually, this makes more sense: on the game board Toomak isn't killed until he's said his final piece. This also resolves the `wmllint` flag against a unit speaking in their `die` event, probably so-flagged precisely because of a unit speaking after they've already been removed from the board is a visual inconsistency.
> SoF S9: Separate Toomak's last breath message from the events following his death

- data/tools/wmllint
Resolves #6995.
I'd prefer to use `pathlib.PurePath.suffix` but `os.path` is already used extensively here. Also, `os.path.isfile()` doesn't work because that actually checks for the presence of the file, not just if the string is a valid file expression.
I don't really know all the details from the discussion in #6995, I just noted that this dropped remaining 'label needs translation mark' (for `[image]`s) in master and 1.16 for me (including `units/human-princess.png~TC(1,magenta)`). This may not necessarily be the 'right' solution.
> wmllint: Ignore labels for translation if a PNG extension is found

- data/test/scenarios/interrupts.cfg
- wml_test_schedule
I've backported this and confirmed that the behavior is the same on 1.16 (using a binary built around 2 weeks ago).
Fixes #7084.
> Add unit tests for [break] and [return] during [fire_event]

- src/serialization/string_utils.hpp
The affected function may return prematurely given a sufficiently large input because of a downcast to int of a size_t value, followed by a comparison.
(This was caught through a mishap with `-Wshorten-64-to-32` on Xcode.)
> Fix 64-to-32 bits integer downcast issue

- data/test/scenarios/interrupts.cfg
- wml_test_schedule
Backport of #7086, planning to merge once the CI finishes.
Cherry-picked from b18b0e0f55ce595fe0e6986f96b1e26d7c44823b, including the docs from 16b900c27340a06c3b26cb5cbc1845432d8a2a34.
> [1.16] Add unit tests for [break] and [return] during [fire_event]

- run_wml_tests
Backport of #7036. It might be a little excessive to run this one through the CI, but I like to have a check-everything workflow.
For example, `run_wml_tests --filter backstab` runs only the tests listed in `wml_test_schedule` that have `backstab` somewhere in their name.
(cherry picked from commit 34ae0490b1975b950e90a5c9505abb85cc07d049)
> [1.16] run_wml_tests: add an option to filter tests by name

- Makefile.am
- src/actions.hpp
- src/ai_dfool.hpp
- src/config_adapter.cpp
- src/game_events.hpp
- src/pathfind.cpp
- src/preferences.cpp
- src/unit.hpp
- src/unit_abilities.cpp
- src/unit_map.hpp
- src/upload_log.cpp
Fix unit/unit_map include circular dependency (thanks to moi1392 on LinuxFR.org) Support of modern compiler (thanks to remico on LinuxFR.org)
Thanks to gnombat and Pentarctagon.
> [1.2] Fix unit/unit_map include circular dependency and force use of std=c++03 for g++ compiler.

- data/gui/window/game_version.cfg
- src/gui/dialogs/game_version_dialog.cpp
Honestly, I'm not sure if this addition is a good idea - it is possible to have too much information displayed - but it was requested and it looked relatively straightforward to implement, so here it is. Of course, I could have missed something somewhere.
Resolves #7096.
> Add screenshots directory to game version dialogue

- data/campaigns/Legend_of_Wesmere/scenarios/chapter3/09_Bounty_Hunters.cfg
Resolves #7130.
Enforcing the river crossing seems to be the better option (as opposed to just adding defeat enemies as an alternative victory objective) since there are monsters to contend with when arriving at the river.
> LoW S9: Remove standard enemies-defeated as a victory condition

- data/campaigns/Dead_Water/scenarios/05_Tirigaz.cfg
- data/campaigns/Legend_of_Wesmere/scenarios/chapter2/07_Elves_Last_Stand.cfg
- data/campaigns/Son_Of_The_Black_Eye/scenarios/16_The_Coward.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/11_Battle_for_Zocthanol_Isle.cfg
- data/core/macros/deprecated-utils.cfg
- data/core/macros/optional_unit_advancements.cfg
- data/core/units/orcs/Slayer.cfg
- data/multiplayer/factions/northerners-aoh.cfg
Similarly to #6911 this gives a level 3 advancement to a default unit that is still missing one. Except in this case the advancement was already in core, just not fully utilized.
Also adds the Orcish Nightblade as a leader for Age of Heroes era and to campaign side recruit lists wherever the other level 3 orcish units are found.
> Make Nightblade the default advancement for Slayer

- data/core/units.cfg
From 5 to 4. Makes moving them from one water body to another somewhat less tedious. Likewise makes merfolk units a bit more viable on maps with separated waterways.
Just as it was before this change, the merfolk remain twice as slow as naga at moving through these two terrains.
> Slightly reduce merfolk forest and hill move cost

- src/commandline_argv.cpp
use return of `emplace_back` to swap buffers
use argc to reserve space in the args vector
remove explicit constructor used in `push_back` vs `emplace_back`
> Simple refactor in read_argv

- changelog_entries/fix_undo.md
- data/lua/diversion.lua
- data/lua/on_event.lua
- data/modifications/pick_advance/main.lua
- data/multiplayer/scenarios/2p_Dark_Forecast.lua
- data/multiplayer/scenarios/2p_Isle_of_Mists.lua
Fixes #6898. The issue is that non-WML events added through the new events API always disable undo with no equivalent of WML's `[allow_undo]`. The long-term fix is to add a way to do that; however until that's available then listeners for `moveto` need to use the old `on_event` API. The old `on_event` API can't be deprecated yet, and this is enforced by our unit tests (the build fails if there are unexpected deprecation warnings during the tests).
Reverts most of 7e234f8833282424b3535b9c334c751748f7222b. Does not revert files that only listen for non-undoable events such as `die` or `new turn`.
Reverts the deprecation part of #5663's 8cd133263058a5df85f64988e348d2cf54d13a48.
> Make undo work again, undeprecate on_event()

- src/units/abilities.cpp
- src/units/attack_type.hpp
I know that I have already proposed a simplification of the code of this attribute, but several things lead me to propose this second rewrite.
First, using the first loop to define three boolean variables is more complicated than simply eliminating from the 'overwrite_specials' list the abilities not carrying the attribute then; if an ability with the attribute is present define a double for loop inside each other, where for each ability with overwrite_specials the type of ability removal from the returned list is defined at that time (one_side or both_sides). The code is even more readable than with the previous work in my opinion.
The second reason is that I eventually want to be able to use the request code https://github.com/wesnoth/wesnoth/pull/7050 to be even more selective about …
> [1.17]further simplification of overwrite_specials attribute code

- src/actions/heal.cpp
- src/units/abilities.cpp
- src/units/unit.cpp
- src/units/unit.hpp
- src/utils/general.hpp
C++20 will add std::erase_if as a convenience wrapper around std::remove_if, handling the subsequent call to std::vector::erase. This simplifies readability, avoiding the need to either store the result of std::remove_if in a temporary or to put the second argument of vector::erase after the body of a lambda.
This adds utils::erase_if, which does the same thing. The C++20 function returns the number of elements removed, but as none of the callers need that I've not implemented it in utils::erase_if.
This commit omits the refactor of attack_type::overwrite_special_checking, because that function is being worked on in parallel by @newfrenchy83. It'll be simpler for either of us to update it later instead of creating merge conflicts.
@newfrenchy83, please would you review this?
> Refactor ability lists using utils::erase_if and std::remove_if

- data/campaigns/Heir_To_The_Throne/utils/httt_utils.cfg
Kalenz now has traits loyal, and resilient. The quick trait is part of his changed unit type after LoW's ending.
Closes #7141
> HttT: give Kalenz his missing 2nd trait

- src/commandline_options.cpp
when returning by value, the ideal way to store the returned value is another value - using a const& works only because of how c++ prolongs the lifetime of temporaries with const&'s
use move on strings that get destroyed at scope end
fix some formatting differences between a couple functions (parenthesis spaces)
> Remove some un-needed references and optimize some string operations

- src/gui/widgets/text_box_base.cpp
> Don't call back() if open_window_stack is empty since that's UB.

- data/test/scenarios/premature_end_turn.cfg
- data/test/scenarios/test_event_names_and_order.cfg
- wml_test_schedule
Move `event_name_variable_substitution` to the top of the file, as it's testing that the event triggers at all, before the tests that check which order the events are triggered in.
The old `order_of_variable_events1` seemed to be a combination of two tests that should exist, but the code didn't quite test either of them. This replaces it with a new `order_of_variable_events1` and `order_of_variable_events3`.
Docs partially written by Pentarctagon, this started as a review comment on the documentation PR.
> Add unit tests for interpolated event names and end_turn

- data/test/scenarios/test_preprocessor_ifdef_in_arg.cfg
- wml_test_schedule
This one's surprising, but it's the behavior of 1.16, so add a test for the current behavior even though I wonder if it should change in 1.17.
@CelticMinstrel @newfrenchy83 this explains my current confusion in #7157.
> Add a unit test for the preprocessor's #ifdef handling

- changelog_entries/special_note_duplication.md
- data/test/scenarios/special_note_from_movetype.cfg
- data/test/scenarios/special_note_individual_unit.cfg
- src/movetype.cpp
- src/movetype.hpp
- src/units/types.cpp
- src/units/unit.cpp
- wml_test_schedule
Fixes #7153
The movetype's special notes were becoming a new note for the individual unit.
Clean up the documentation on some of movetype's functions, as they had documentation in both the .hpp and the .cpp.
> Fix [special_note] duplication when unstoring units

- README.md
Pretty simple; since the project has announced a migration from Twitter to Mastodon, this updates the README to reflect it.
> Change Twitter link to Mastodon link in README.md

- changelog_entries/special_note_duplication.md
- data/test/scenarios/special_note_from_movetype.cfg
- data/test/scenarios/special_note_individual_unit.cfg
- src/movetype.cpp
- src/movetype.hpp
- src/units/types.cpp
- src/units/unit.cpp
- wml_test_schedule
Backport of #7157, fixes #7153. Will merge once the CI passes.
The movetype's special notes were becoming a new note for the individual unit.
Clean up the documentation on some of movetype's functions, as they had documentation in both the .hpp and the .cpp.
(cherry picked from commit 38fdf06fa9a17ff0995909d5f76309d65ac05a5c)
> [1.16] Fix [special_note] duplication when unstoring units

- src/gui/dialogs/addon/manager.cpp
Attempts to fix this issue here: https://github.com/wesnoth/wesnoth/issues/7169
I just push the output of `langcode_to_string()` through another set, which removes duplicates of the display string.
> Language string duplicate removal

- src/lexical_cast.hpp
The motivation for this is that `lexical_cast` is called very frequently, even to the point of being called repeatedly in the main loop. By relying on exceptions internally, it becomes a hindrance to debugging.
This PR is mainly opened solely for CI purposes. Unless there are objections before the CI successfully completes, I will merge it immediately.
> Avoid throwing exceptions internally to lexical_cast when parsing an empty string

- src/gui/dialogs/gamestate_inspector.cpp
When given a string that includes newlines but doesn't end with a newline, the old code would get stuck in an infinite loop.
Fixes #7194
> Inspect console: fix infinite loop in pagination

- src/gui/dialogs/gamestate_inspector.cpp
Backport of #1795, will merge when CI passes.
When given a string that includes newlines but doesn't end with a newline, the old code would get stuck in an infinite loop.
Fixes #7194.
(cherry picked from commit b5ff5c3ddc706f1281bbbe2f235b16c4b00f92db)
> [1.16] Inspect console: fix infinite loop in pagination

- src/server/campaignd/addon_utils.cpp
"campaign_name" is not an existing attribute in the given config anymore. An addon should only contain a single toplevel dir tag with the name of the addon anyway.
> Just look for the toplevel dir tag

- data/multiplayer/scenarios/Test_Elevation_Test.cfg
Currently, the name of this scenario is too long, and it causes unattractive-looking width expansion of the MP scenario lists. Thus, it should be enclosed in `DEBUG_MODE` like the other three test scenarios in the MP scenarios folder.
> [MP] Change Elevation Test Scenario Name and Desc

- data/campaigns/Sceptre_of_Fire/scenarios/9_Caverns_of_Flame.cfg
- data/campaigns/Sceptre_of_Fire/utils/terrain.cfg
Resolves #7210
I think this is all the remaining instances of `Ias*` codes, aside from code specifically to mark or handle deprecated terrains.
At least I can confirm SoF S9 loads properly with this change.
> SoF: Convert Ias terrain codes missed in #7042

- data/test/scenarios/test_synced_side_number.cfg
- src/synced_user_choice.cpp
- wml_test_schedule
Change the C++ to show a Lua error instead of crashing with an assert.
There's no issue logged for this, but this adds a unit-test for reproducing the crash.
The code formatting is consistent with the rest of the file; the entire file should be run through clang-format, but I don't want to do that on a change that should be backported.
I haven't included a changelog entry, I'm on the borderline of whether it should have one or not.
> Handle out-of-bounds side numbers in Lua's sync.evaluate_multiple

- data/tools/wmllint
In python negative index counts from the end, so without this change or another solution 
`example with only < one side` would be converted to  
`example with only < one sid&gt;example with only < one side`
> Escape < and > even if only one of them exists

- changelog_entries/bounds_synced_eval.md
- data/test/scenarios/test_synced_side_number.cfg
- src/synced_user_choice.cpp
- wml_test_schedule
Backport of #7197.
Change the C++ to show a Lua error instead of crashing with an assert.
Cherry picked from commit a9d5c6ac6d8364f2fb3a6cd24dc55593d5b6f924, with a changelog entry added.
> [1.16] Handle out-of-bounds side numbers in Lua's sync.evaluate_multiple

- data/lua/wml/kill.lua
The previous logic simply did not make sense, especially for the secondary weapon. For example, it would ignore the secondary weapon specification if the primary weapon was not found on the secondary unit, which does not make any sense.
The cases that this changes are:
- There is a secondary unit and a primary attack, but no matching attack was found. Previously it would use the default, now it pretends that attack exists.
- There is a secondary attack specified, but no primary attack, either because it was unspecified or because it didn't match any attack on the secondary unit
In both these cases, the animation runs as if a matching attack exists, rather than using no attack and choosing the default animation.
> WML: Adjust the weapon selection logic for [kill]

- data/core/macros/animation-utils.cfg
Drakes attacking to the north with their fire breath face south and bend over, is this some sort of long running joke?
Using the se frames instead still doesn't look great, but it's not quite as bad.
> 1.17 - make north-breathing drakes face se instead of s

- data/campaigns/Under_the_Burning_Suns/scenarios/01_The_Morning_After.cfg
Fixes #7202 
@nemaara could confirm that Gd^Vdt, Rd^Vdt, Re^Vda are intended to be included.
V terrains in that map:
Dd^Vda
Dd^Vdr
Dd^Vdt
Ds^Vda
Ds^Vdr
Ds^Vdt
Gd^Vdt
Rd^Vdt
Re^Vda
> Exclude nonvillages from outer_villages array

- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/special_calculations.cfg
- wml_test_schedule
Covers the math for [attack]add=, [attack]divide=, [attack]multiply= and [attack]sub=. The behavior is the same in 1.16.
* 5 + 2 = 7
* 5 - 3 = 2
* 5 + 2 - 3 = 2. Yes it does, that's half of why this unit test exists ...
* 5 + 2 + 3 = 8
* 5 + 3 + 2 = 8
* 5 + 2 - (-3) = 7
* 3 * 3.34 = 10
* 3 * 3.334 = 9. ... and that's the other half of why this unit test exists.
@newfrenchy83 sorry, reviewing your PRs got sidetracked into discovering what the math rules are. I'll ask in the IRC channel if we can add you to a group that lets you be added to the "reviewers" list.
> Add unit tests for weapon-special calculations

- data/core/macros/special-notes.cfg
Units still using this in their descriptions will have the player-visible header change from "Special Notes:" to "Special Notes (1.14-style, please update to the new list format)".
The SPECIAL_NOTES macro was originally removed early in the 1.17 dev cycle. That removal was reverted and postponed in the roadmap until Jan 2023, on the grounds that it's a lot easier to test 1.17 when the big add-ons from 1.16 can run on it.
In 1.16, UMC that hasn't upgraded yet already has a cosmetic bug - the help pages of units still using the {SPECIAL_NOTES} macro will include duplicate notes (assuming the expected usage of {SPECIAL_NOTES} as a heading in [unit_type]description=, which is followed by old-style notes). These are minor cosmetic bugs, which are expected to be removed as UMC gets updated. …
> Update deprecation but postpone removal of the SPECIAL_NOTES macro

- changelog_entries/abilities_without_display.md
- src/units/abilities.cpp
Partially reverts 6a21fdc6750a8342846ef18248517808316c4118
Fixes #5643
Fixes #7238
There's a bunch of global things that can be accessed either via global pointers in the `resource` namespace, or via `display::get_singleton()`. The singleton and these global pointers are set up in `play_controller::init`, however there's a section where things are available via the global pointers but the `display` singleton doesn't exist yet. During that time, checking whether an ability is active can crash the game.
Removing the global pointers is a good goal, but detouring through a GUI class to access the data causes its own problems.
The "has already been confirmed valid by both callers" comment is replaced with an assert, because there's currently at least three callers.
> Allow abilities.cpp to access units and teams earlier during play_controller::init

- data/campaigns/Secrets_of_the_Ancients/utils/zombie-utils.cfg
Weapon specials usually are on wesnoth-help texdomain, as this case.
Before, appears on english on all languages.
> SotA: change textdomain of zombie-utils.cfg

- changelog_entries/httt_s03_intro.md
- data/campaigns/Heir_To_The_Throne/scenarios/03_The_Isle_of_Alduin.cfg
The Isle of Alduin doesn't have much dialogue at the start, it's a map where the island gives the player two fronts to progress on, and it's early enough to give the player time to prepare for the SoE.
> HttT S03: Rewrite intro text, hint about training troops for S06

- src/actions/create.cpp
- src/units/unit.cpp
- src/units/unit.hpp
Looking at the discussion in #7188, I thought it wouldn't be hard to have a fallback which only triggers when the normal checksum fails, and sees if the unit passes a 1.16 style checksum instead. Took a bit longer than expected, but looks like a reasonable solution to that problem without adding a maintenance burden.
This will also accept them during multiplayer matches, but it will still warn if the unit's stats have changed. When using the new option, the checksum includes data that has been ignored since 93fe5607a658c74b987.
> Checksums: accept 1.16's checksums during replays

- src/server/wesnothd/server.cpp
- utils/mp-server/table_definitions.sql
The cause is that somehow, during regular play, MP campaigns can end up with duplicate values in the [content] data for each [addon]. A very similar issue was fixed in 6c980d12dcd56ccd16ff8b7150cd15ef19f0a821, but there's apparently some other way to trigger it that I haven't been able to reproduce. Since the error itself is harmless, it'll just be ignored server-side to avoid the spurious errors in the server log file.
> Ignore duplicate primary key errors for game_content_info table.

- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/special_calculations.cfg
Just a whitespace change, because it can't be used as a reference to cut & paste from when it's incorrectly indented.
> Fix the indentation in the "special_calculations" test

- data/core/units/monsters/Dragonfly_Grand.cfg
Grand Dragonfly has been the using the textdomain of the UMC "Coaltion of Swamp Creatures: big Battle 1"
> [Units] add correct textdomain to Grand Dragonfly

- changelog_entries/orb_prefs_layout.md
- data/gui/window/select_orb_colors.cfg
- src/gui/dialogs/select_orb_colors.cpp
- src/gui/dialogs/select_orb_colors.hpp
Add some spacing to make it clearer what is grouped with what, move the disengage orb's setting to be part of the partial orb's group, and add tooltip.
There's only one tooltip so far, does anyone feel the "Show ... orb" checkboxes should have them too?
This dialog uses checkbox labels as section headers to indicate what the rows of colors refer to. This commit doesn't change that, but it makes the grouping clearer. Actual section headers would take additional space and probably not look any better.
The intention would be to backport it, and then backport a rebased PR #7189 on top of it. The image below shows the intended final destination, the current PR doesn't include the "During ally's turn, use a two-colored orb with status" line.
> Orb color preferences dialog layout and tooltip

- data/test/scenarios/wml_tests/ScenarioWML/EventWML/ActionWML/DirectActionsWML/kill_fires_events.cfg
- wml_test_schedule
This test checks if the last_breath and die events are triggered when a unit on the recall list is killed.
As you can see, with **equals yes** on all variables Alice does not trigger the last_breath and die events when she is on the recall list. This is the default behavior on 1.16 and 1.17
I send a version of the test that is supposed to pass, with Alice not firing the event.
Note: Sorry for sending the pull request again, since in the previous one I used a fork, and it is better to use a branch, since I cannot create more than one fork.
https://github.com/wesnoth/wesnoth/pull/7272
> Test fire_event of kill unit on recall list

- .github/workflows/ci-main.yml
- src/gettext.cpp
- vcpkg.json
The vital commit is fd766eba2b4cf59c7123d46189be373e2cee959d, but I'm taking the most recent version of vcpkg as the new baseline because it might as well use the latest.
> Bump vcpkg baseline to use a non-obsolete version of libtool

- changelog_entries/logs_duplicate_variants.md
- src/units/types.cpp
The strings involved aren't translatable, so this is taking a message that's already only printed in English, and making it more helpful. (It probably should be translatable, but this isn't making anything worse).
Add a useful identifier to the message
error config: Skipping duplicate unit variation ID: ''
This warning is generally shown because the variation_id is completely missing, and so the message appeared as above, without any hint of which unit was causing the problem.
In contrast to 19a5ce83's warning, this one is printed multiple times to stdout even if the messages are identical; therefore backporting this to 1.16 seems reasonable.
(cherry picked from commit 323ce6ec260f29f81c4cb4a703cc2202610db982)
> [1.16] Show id in "skipping duplicate variation" warning

- src/help/help_impl.cpp
Edit: no longer just a prototype.
Prototype: This was the original idea for visualising [race]help_taxonomy=, it didn't feel right to me back in September 2020, but I can't remember why it didn't. That idea is now being discussed in https://r.wesnoth.org/t56522 , so I'm opening a PR to share the implementation.
> Show races as nestable subfolders in help

- data/test/macros/shroud.cfg
- data/test/macros/start_position_generic.cfg
- data/test/scenarios/behavioral_tests/recruit_facing.cfg
- data/test/scenarios/cve_tests/test_cve_2018_1999023.cfg
- data/test/scenarios/lua_tests/wesnoth/sides/test_modify_shroud.cfg
- data/test/scenarios/lua_tests/wesnoth/sync/break_replay_with_lua_random.cfg
- data/test/scenarios/lua_tests/wesnoth/sync/test_synced_side_number.cfg
- data/test/scenarios/lua_tests/wesnoth/test_synced_state.cfg
- data/test/scenarios/lua_tests/wml-utils/test_scoped_vars.cfg
- data/test/scenarios/macro_tests/test_force_chance_to_hit_macro.cfg
- data/test/scenarios/manual_tests/test_relative_dir.cfg
- data/test/scenarios/wml_tests/ScenarioWML/AiWML/_main.cfg
- data/test/scenarios/wml_tests/ScenarioWML/EventWML/ActionWML/DirectActionsWML/shroud.cfg
- data/test/scenarios/wml_tests/UnitsWML/traits_exclude_include.cfg
- data/test/units.cfg
- data/test/units/test_unit_exclude.cfg
- data/test/units/test_unit_require.cfg
- data/tools/Makefile
The whole data/test directory was excluded from the CI's indentation check.
Two of the commits in this PR fix the indentation in some of the tests, and
then the final commit reduces the exclusion list to only
* data/test/scenarios/cve_tests/
* data/test/scenarios/lua_tests/
* data/test/scenarios/wml_tests/TerrainWML/
Exclude cve_tests because of the binary file that's masquerading as a .cfg;
I think it's correct to exclude the whole directory because any new tests
added there might also use weird edge cases in the parsing.
Exclude lua_tests as a "keep this PR small" thing. We should fix the bugs in
wmlindent, but I don't want to take on that work.
The exclusion of TerrainWML is again because I don't want to take on the work
of working out whether it's problems with terrain masks or bugs …
> Fix indent on unit tests, and make the CI check it

- changelog_entries/httt_s03_intro.md
- data/campaigns/Heir_To_The_Throne/scenarios/03_The_Isle_of_Alduin.cfg
Backport of #7214, simple cherry-pick with nothing to fix up afterwards.
The island gives the player two fronts to progress on, and it's early enough to give the player time to prepare for the SoE. Hint to them about improving their recall list.
When trying to add that hint as a single-line change to the dialogue, I reviewed the existing text and felt it didn't flow well. Reading the feedback thread, Delfador should have more emotion about finding his childhood home overrun; however I've gone for practical thoughts first.
The hint isn't #ifdef to only appear on easy, because the text wouldn't flow without it - take that line out and it goes from "there are more orcs than I thought" to "we must fight these orcs, who aren't the ones at the SoE". Also, players who are already doing XP …
> [1.16] HttT S03: Rewrite intro, hint about training troops for S06

- data/campaigns/Legend_of_Wesmere/_main.cfg
> [LoW] fix scenario count inconsistency

- data/campaigns/Legend_of_Wesmere/scenarios/chapter1/03_Kalian_under_Attack.cfg
Urudin the Slayer is supposed to move to 12,4 (next to the castle of one of the warlords), instead he is set to move to 20,6 which makes little sense. The event of Urudin moving at 12,4 was supposedly never triggered.
Reported on Discord
> Hi
In the file 03_Kalian_under_Attack.cfg, the coordinates of line 200 and 454/455 are not the same. Is that just a typo or intentional?
Steam 1.16.6
> [LoW] S3: fix mismatched coords of Urudin retreat

- changelog_entries/overlarge_unit_bars.md
- src/units/drawer.cpp
Fixes #7171.
Because of the move to hardware rendering in commit afd6baa7cf1685610c72305f5c9f989078462dff, some relevant info was lost that was previously used to limit bar height in particular.
This patch re-adds a dimension check and additionally ensures that the bar width doesn't exceed the tile size either.
**Before**
**After**
**Note:**
This is probably not 1:1 equivalent to the check done in past stable series. However, it does ensure that the bars do not exceed the tile size at the current zoom level, so it works in practice and solves the issue at hand. Right now drawing bars that exceed the tile area is generally a bad idea anyway and leads to graphical glitches when mousing over adjacent tiles.
> units: Limit energy bar sizes to the game tile size

- changelog_entries/editor_ability_assert.md
- src/units/abilities.cpp
The previous bugfix fixed a crash when loading savegames with units whose abilities accessed the map while the display_context was still being constructed, however it reintroduced a bug in the scenario editor. Using the unit tool always crashed when adding any unit.
This commit uses 4d1fc268b1's code path whenever possible, however it falls back to 6a21fdc675's code path when 4d1fc268b1 would assert. In practise one path is used in game and the other is used in the scenario editor, but doing the logic in this way ensures that any edge cases are going to affect the scenario editor rather than the game itself.
> [1.16] Fix crash in scenario editor when placing units

- changelog_entries/editor_ability_assert.md
- src/units/abilities.cpp
Forwardport of #7297. @newfrenchy83 this doesn't seem to have conflicts with your PRs.
The previous bugfix fixed a crash when loading savegames with units whose abilities accessed the map while the display_context was still being constructed, however it reintroduced a bug in the scenario editor. Using the unit tool always crashed when adding any unit.
This commit uses 4d1fc268b1's code path whenever possible, however it falls back to 6a21fdc675's code path when 4d1fc268b1 would assert. In practise one path is used in game and the other is used in the scenario editor, but doing the logic in this way ensures that any edge cases are going to affect the scenario editor rather than the game itself.
Cherry picked from commit 1485cfd6256b73bb06aa34c512c2890749b45487, with conflicts because code …
> Fix crash in scenario editor when placing units

- src/wesnoth.cpp
The logic we used here hasn't had the desired results since the move from using custom Visual Studio project files to using the CMake integration system, so this patch updates it to match the layout we get with the CMake integration on Visual Studio 2019 and 2022.
Note that without this patch, the game is unable to detect a valid game directory by default when launched by MSVC++ without an explicit path, which results in an assertion failure somewhere in the filesystem API.
> Fix game data dir search for Visual Studio builds on Windows

- src/build_info.cpp
- src/video.cpp
- src/video.hpp
There is currently a bug in master causing `--report` to raise a segmentation fault because of an attempt to dereference a null pointer to the game window to check the game's display configuration.
At some point in 1.17.x, the check for whether the game window was null disappeared. This brings it back by exposing a check through the `video` namespace so as to avoid piggybacking further on the `video::get_window()` function, which we are meant to avoid using.
> bi: Fix --report SIGSEGV caused by uninitialised video

- src/build_info.cpp
- src/video.cpp
- src/video.hpp
This patchset re-adds a clipboard report line for the Game Version dialog showing the game screen's DPI like in 1.16. This particular bit was dropped by mesilliac in the middle of an architectural change to how DPI is handled in the game, however it really shouldn't have been part of the removal given that it's meant to be diagnostic information for developer use when processing bug reports from players.
Additionally, it adds new information on the renderer in use including its name (e.g. "metal" on macOS, "direct3d" on Windows), whether it's a software rasteriser (indicated by "sw"), whether it's hardware accelerated (indicated by "hw"), whether VSync is enabled, and the maximum renderer texture size.
> bi: Re-add screen dpi report line, add information on the renderer setup

- changelog_entries/special_note_macro_postponed_removal.md
- data/core/macros/special-notes.cfg
This is a partial cherry-pick of b9e4fdffb46b9933a602ed2601b051c642e7ba07, merely reflecting that the removal has been postponed from 1.17 to 1.19 along with updating some outdated comments.
The motivation for backporting this is to make other warnings that are printed to stdout/stderr more visible, instead of being scrolled offscreen by the SPECIAL_NOTES messages.
> [1.16] Reduce log spam about the postponed removal of the SPECIAL_NOTES macro

- data/test/scenarios/lua_tests/wml-utils/test_scoped_array.cfg
- data/test/scenarios/lua_tests/wml-utils/test_scoped_scalar.cfg
- wml_test_schedule
The existing test for scoped vars is both copied and renamed.
This passes on 1.16 too (after moving the files to the old directory).
> Add a unit test for scoped arrays

- data/campaigns/Under_the_Burning_Suns/lua/theme.lua
It's simple, only a variable substitution, and I just tested it. The only problem is that the string will have to be translated again in all languages.
To be more sure, I've tried the spanish translation, and it works.
This should resolve #7295
> Fix HP lost with dehydrated on tooltip

- data/campaigns/Son_Of_The_Black_Eye/scenarios/14_Back_Home.cfg
This, instead of killing Grüü, moves him along with the others to participate in the conversation, and also switches him to side 1 (this side is temporary and only for narrative purposes, later on turn 7 he switches to side 4 again).
Grüü is correctly stored on the variable when the conversation ends, and restored later on turn 7.
> SotBE S14 Grüü apparition fixed

- .github/workflows/ci-main.yml
Looking at recent build failures, one of Debug or Release is using the prebuilt vcpkg from the cache, and the other one is detecting it but then deciding to rebuild many of the packages.
The build logs circa 8bd8c53f9887ae2440b9a4d29ec55655de08b519 are no longer accessible, only the success/failure and time taken are still accessible. Looking at build timings around those changes is inconclusive, however my guess is that the CI is noticing that CFG is different between the two builds, and that's forcing a rebuild for one of them.
> CI: Make the Windows CI builds use separate caches

- data/core/units/monsters/Sand_Scamperer.cfg
The Sand Scuttler has been separated from the Giant Scorpion. This commit adds a Level 0 counterpart of the Giant Scorpling which advances into the Sand Scuttler.
See also: #7244
> Add Sand Scamperer

- data/tools/emacs_mode/wesnoth-mode.el
Switch from obsolete Emacs Lisp functions to modern functions in order to remove two compiler warnings.
Properly quote lambdas with #' to remove two more compiler warnings.
> Fix Issue 7337: Byte Compiler Warnings for wesnoth-mode

- data/game_config.cfg
- data/schema/core/config.cfg
- src/game_config.cpp
- src/game_config.hpp
- src/gui/dialogs/select_orb_colors.cpp
- src/preferences/general.cpp
- src/preferences/general.hpp
- src/units/orb_status.cpp
Assorted cleanup, fixes #7261.
* Add `game_config.cfg`'s `show_*_orb` to the schema
* Rename `show_partly_orb`
* Remove the unused `disengaged_orb_color` preference
The `show_*_orb` keys are supported in game_config.cfg, but currently they're not used in that file, instead falling back to the defaults in the C++. Add them to the schema, but not to `game_config.cfg` itself.
The name `show_partly_orb` was inconsistent - in other places, including the WML that's stored in the user's preferences file, it's called `show_partial_orb`.
Remove leftovers from the original implementation of the disengage orb, when it was a new color for the single-color orb. During the review process it became the two-color design, but these parts were left in.
The value of …
> Orb related cleanup for preferences and game_config

- changelog_entries/ally_orbs.md
- changelog_entries/orb_prefs_layout.md
- data/gui/window/select_orb_colors.cfg
- src/game_config.cpp
- src/game_config.hpp
- src/gui/dialogs/select_orb_colors.cpp
- src/gui/dialogs/select_orb_colors.hpp
- src/preferences/general.cpp
- src/preferences/general.hpp
- src/units/drawer.cpp
- src/units/orb_status.cpp
Backports of #7266 and #7189.
Use spacing to improve the orb color preferences dialog (backport of #7266)
Use two-color orbs for allies' units, configurable by preferences (backport of #7189)
These orbs no longer look the same as the player's own orbs, so they won't cause confusion in multiplayer.
The relevant part of the advanced preference now shows:
```
[ ] - Show ally orb
[ ] - During ally’s turn, use a two-color orb to show movement
Radio buttons for colors: ( )  ( )  ( )  ( )  ( )  ( )  ( )
```
That offers these choices:
* Don't show ally orbs at all
* Always use the one-color (with ally color, not status)
* Use the two-color when that ally is playing, single color at other times
* Use the two-color when that ally is playing, no orb at other times
This probably doesn't need a change …
> [1.16] Ally orb color preferences

- src/actions/attack.cpp
- src/units/abilities.cpp
- src/units/attack_type.hpp
in addition to simplify the calling of calculation function for int weapon specials, it also because an commit what i want push in https://github.com/wesnoth/wesnoth/pull/6968 a attribute  require this function.
> modify calling of unit_abilities::effect and get_composite_value()

- .github/workflows/ci-main.yml
If the Windows CI rebuilds (or has an empty cache and just builds) vcpkg, and that build fails, then this will try to upload the logs from the glib build. It doesn't trigger if the vcpkg rebuild succeeds.
Although I was originally planning to close this without merging, as the builds have been awkwardly successful recently, I'd like to merge this and catch the logs when it does fail. It doesn't need the cache to be cleared - if vcpkg decides not to rebuild then everything is good for that build.
> Store glib build log on build failure

- data/test/scenarios/wml_tests/UnitsWML/unit_no_advancements.cfg
- data/test/scenarios/wml_tests/UnitsWML/zero_experience.cfg
- wml_test_schedule
Check the behavior of units when their maximum experience is 0, with or without advancement available. The default engine behavior is that if a unit has any advancement, it can't have `max_experience=0`, so it always changes to `0/1`. If the unit have no advancements, then the experience bar will disappear and show `-` instead of `0/1`
This test is equivalent to `experience=0` on `[unit_type]` too. `[unit] max_experience=` takes by default the value of `[unit_type] experience=`
* API(s) being tested: `[unit] max_experience=0`
* Actions:
Change Alice's and Bob's max_experience to 0. Delete Bob's 'Orcish Warrior' advancement but not Alice's. Harm bob with 1 hitpoint to be sure that he have some damage. They then fight each other.
* Expected end state:
Alice levels up and changes her …
> Unit tests to evaluate behavior with max_experience=0 and with no advancements

- changelog_entries/attacks_used.md
- data/schema/filters/weapon.cfg
- data/schema/units/modifications.cfg
- data/schema/units/types.cfg
- data/test/_main.cfg
- data/test/scenarios/wml_tests/UnitsWML/Attacks/test_attacks_used.cfg
- data/test/scenarios/wml_tests/UnitsWML/Attacks/test_movement_used.cfg
- src/actions/attack.cpp
- src/formula/callable_objects.cpp
- src/scripting/lua_unit_attacks.cpp
- src/units/attack_type.cpp
- src/units/attack_type.hpp
- src/whiteboard/attack.cpp
- src/whiteboard/attack.hpp
- utils/emmylua/wesnoth/units.lua
- wml_test_schedule
This implements the "uses N attacks" feature used by @Hejnewar in #7349. Since it parallels the existing `movement_used` key it seemed reasonable to handle it at the engine level.
Wiki documentation to be updated if this is merged:
> Add new attacks_used key to [attack]

- data/campaigns/tutorial/achievements.cfg
- data/campaigns/tutorial/scenarios/01_Tutorial_part_1.cfg
- data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg
- data/gui/widget/progress_bar_thin.cfg
- data/gui/window/achievements_dialog.cfg
- data/lua/wml-tags.lua
- data/schema/achievements.cfg
- src/achievements.cpp
- src/achievements.hpp
- src/gui/dialogs/achievements_dialog.cpp
- src/gui/dialogs/achievements_dialog.hpp
- src/preferences/general.cpp
- src/preferences/general.hpp
- src/scripting/game_lua_kernel.cpp
- src/scripting/game_lua_kernel.hpp
Instead of being either complete or incomplete, achievements can now specify a value at which they will be considered complete. For such achievements that are not yet complete, a progress bar is added to the achievements dialog showing how close to completion the achievement is.
> Add functionality for achievements to be partially complete.

- data/ai/micro_ais/mai-defs/animals.lua
- data/ai/micro_ais/mai-defs/bottleneck.lua
- data/ai/micro_ais/mai-defs/escort.lua
- data/ai/micro_ais/mai-defs/fast.lua
- data/ai/micro_ais/mai-defs/guardian.lua
- data/ai/micro_ais/mai-defs/healers.lua
- data/ai/micro_ais/mai-defs/misc.lua
- data/ai/micro_ais/mai-defs/patrol.lua
- data/ai/micro_ais/mai-defs/protect.lua
- data/ai/micro_ais/mai-defs/recruiting.lua
- data/ai/micro_ais/micro_ai_helper.lua
- data/ai/micro_ais/micro_ai_unit_variables.lua
- data/campaigns/World_Conquest/lua/game_mechanics/bonus.lua
- data/campaigns/World_Conquest/lua/map/scenario_utils/bonus_points.lua
- data/campaigns/World_Conquest/lua/map/scenario_utils/side_definitions.lua
- data/lua/diversion.lua
- data/lua/functional.lua
- data/lua/ilua.lua
- data/lua/location_set.lua
- data/tools/check_mixed_indent
- utils/CI/fix_whitespace.sh
Ensures that files either use tabs for indentation or spaces for indentation, but don't switch between the two within the same file.
This doesn't fix the whitespace, it's a simple check to flag it up on the assumption that it's better to use an editor or code formatter to clean up the file.
Elsewhere in the CI we use the luacheck tool - while that can detect mixing tabs and spaces in a single line's indent, it doesn't check for inconsistent indentation within a file.
> Make fix_whitespace complain about mixing tabs and spaces

- data/lua/wml-flow.lua
- data/test/scenarios/wml_tests/ScenarioWML/EventWML/ActionWML/ConditionalActionsWML/nested_foreach.cfg
- wml_test_schedule
Since a0ee38a49, the inner this_item was still in scope when the inner loop
writes changed data back to the outer loop's variable, which meant that
changes were silently ignored.
A lot of the changes in wml-flow.lua are just indentation because of the
extra block.
Extend the unit test for scoped variables, which includes fixing the mixed
tab-and-space indentation in that file.
Fixes #6305. I'm dithering about whether to say it's a bugfix and should go
in 1.16, or say that it's unimportant enough to only go in 1.17.
> Support [foreach]array=this_item, nested loops using the default name

- src/events.cpp
- src/events.hpp
- src/widgets/menu.cpp
- src/widgets/menu.hpp
- src/widgets/widget.cpp
- src/widgets/widget.hpp
Remove some dead GUI1 code, leaving the editor's palettes as the only code that calls font::set_help_string. This function shows a tooltip-like text at the bottom of the editor's screen, for example when the paint tool is active it shows which terrains are assigned to the left and right mouse buttons.
There is similar functionality in GUI2, for example when hovering over the title screen's buttons, which is handled via event::MESSAGE_SHOW_TOOLTIP.
This cleanup is the groundwork for moving the label in the map editor so that it doesn't always obscure the southmost hexes of the map. The implementation of font::set_help_string() has moved during 1.17's refactoring (from CVideo in 1.16 to floating_label in 1.17.12); the intention is to replace it with editor-specific code in a later PR for …
> Only call font::set_help_string() from the editor

- data/campaigns/Northern_Rebirth/utils/utils.cfg
In only one place Ro'Arthian has an error in his name:
#. [part]
#: data/campaigns/Northern_Rebirth/utils/utils.cfg:160
msgid "Arthian"
msgstr "Arthian"
I realized it by checking the translations.
> NR S07 - Arthian > Ro'Arthian typo

- data/themes/default.cfg
The level isn't to the right of the alignment any more, the workaround that the comment refers was removed in ca2eec45b9.
> Delete an out-of-date comment in data/themes/default.cfg

- changelog_entries/editor_help_string.md
- src/editor/controller/editor_controller.cpp
- src/editor/editor_display.cpp
- src/editor/editor_display.hpp
- src/editor/palette/editor_palettes.cpp
- src/editor/palette/editor_palettes.hpp
- src/editor/palette/location_palette.cpp
- src/editor/palette/location_palette.hpp
Having it at the very bottom means that it will always obscure the southmost hexes
of the map, and the only way to avoid that is to scroll east/west, or to add an extra
row on the south. Moving it upwards makes it more annoying when working elsewhere on
the map, but it's a trade-off for being able to edit those southmost hexes.
Also, make the text smaller if it's very wide.
This is the 1.16 fix for #6422, with the idea that the second commit will be cherry-picked to 1.17 and then possibly expanded upon. I've also looked at moving the label between the top and bottom of the screen, but that would feature-creep into adding additional functionality to the floating_label support.
The first commit of the two in this PR
--
Use an editor-only copy of font::set_help_string
This function shows a …
> [1.16] Editor: Move the text at the bottom of the screen

- data/gui/window/achievements_dialog.cfg
- src/gui/dialogs/achievements_dialog.cpp
changes from gold to khaki
The current gold looks more yellow and doesn't synergize well with the green description text.
> Engine: make achievement title less bright gold

- changelog_entries/ant_advancement.md
- data/core/units/monsters/Ant.cfg
- data/core/units/monsters/Ant_Soldier.cfg
Adds the missing advancement, unless there is argument that soldier ants and worker (Giant) ants should be different unit-lines as Darwinism goes.
> Units: Giant Ant advances to Soldier Ant

- data/campaigns/Legend_of_Wesmere/scenarios/chapter4/16_The_Chief_Must_Die.cfg
- data/campaigns/Liberty/scenarios/04_Unlawful_Orders.cfg
- data/campaigns/Secrets_of_the_Ancients/scenarios/17_Mortality.cfg
- data/campaigns/Secrets_of_the_Ancients/units/Skele_Sacrifice.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/05_A_Subterranean_Struggle.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/06a_In_the_Tunnels_of_Trolls.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/06b_In_the_Domain_of_Dwarves.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/08_Out_of_the_Frying_Pan.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/09_Blood_is_Thicker_Than_Water.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/12_The_Final_Confrontation.cfg
According to usage, i ended up adding the macros:
* `SCREEN_FADE_OUT` - replaces `FADE_TO_BLACK` in most cases
* `SCREEN_FADE_IN` - replaces `FADE_IN` in most cases
* `SCREEN_FADE r g b duration` - convenience wrapper for `[screen_fade]` with 255 alpha. Mostly used internally.
* `SCREEN_UNFADE duration` - convenience wrapper for `[screen_fade]` with 0 alpha. Mostly used internally.
* `FLASH r g b actionWML` - like `FLASH_WHITE` etc but takes a colour
* `FLASH_LIGHTNING actionWML` - flashes an appropriate colour and plays `lightning.ogg`
The `FLASH_WHITE`/`RED`/`GREEN`/`BLUE` macros were updated to use `screen_fade`.
All mainline campaigns were updated to use these or `[screen_fade]` over `[color_adjust]`, as appropriate. There are only a couple remaining uses of `color_adjust` that …
> Update mainline campaigns to use screen_fade

- data/campaigns/Under_the_Burning_Suns/units/monsters/Alien_Minion.cfg
- data/campaigns/Under_the_Burning_Suns/units/monsters/Alien_Spire.cfg
All the alien units have the same experience, resulting in this disproportion, and it looks pretty ugly.
I can change the ratio of the experience bar with xp_bar_scaling, but reducing the experience is the best option, it does not affect the balance since they are low health units, it is very almost impossible for them to level up.
> UTBS Minion and Spire XP reduced

- changelog_entries/editor_help_string.md
- src/editor/controller/editor_controller.cpp
- src/editor/editor_display.cpp
- src/editor/editor_display.hpp
- src/editor/palette/editor_palettes.cpp
- src/editor/palette/location_palette.cpp
- src/floating_label.cpp
- src/floating_label.hpp
- src/gui/widgets/window.cpp
- src/replay.cpp
- src/video.cpp
- src/widgets/menu.cpp
- src/widgets/widget.cpp
This is the forwardport of #7362. I'm now seeing that more cleanup is possible, but I'd prefer to merge this close to as-is, so that any cleanup that happens in later commits is separate and easily reviewable for (if necessary) backporting to 1.16 too.
Fixes: #6422
Second commit (cherry-pick of 1.16's 29d86d2c369483c45aa599076eb076c5792b7ef3)
---
Editor: let the help text switch between the top and bottom of the screen
If the northmost hexes of the map are visible, put the text on the bottom; if
the southmost are visible, put it on the top. Also, make the text smaller if
it's very wide.
It used to be fixed to the bottom of the screen, but this meant that it always
obscured the southmost hexes of the map, and the only way to avoid that is to
scroll east/west, or to add an extra row on the …
> Editor: move the text at the bottom of the screen

- data/campaigns/Son_Of_The_Black_Eye/scenarios/14_Back_Home.cfg
Backport of #7282, this time squashing the commits instead of rebase-merging them.
This, instead of killing Grüü, moves him along with the others to participate in the conversation, and also switches him to side 1 (this side is temporary and only for narrative purposes, later on turn 7 he switches to side 4 again).
Grüü is correctly stored on the variable when the conversation ends, and restored later on turn 7.
(cherry picked from commit cccd562cc5726348530f077dd9663239ef9cddda)
(cherry picked from commit 34a5cce2b072209cbf4de128b123a3dde7e65ee5)
(cherry picked from commit f23134890009896088b8e9fe549042ee4d0553a1)
(cherry picked from commit 89dbd2d37336785c416b9e76a3a0dcf27500b0b0)
> Grüü apparition fixed (and commits squashed)

- src/whiteboard/attack.cpp
The game crashes when the player clicks the Attack button with planning mode with a console error about a failed assert on line 164 of src/whiteboard/attack.cpp.  The assert uses > but it looks like it should be >=.
This commit switches from > to >= and appears to resolve the issue.
> Resolve Issue 7398: Crash on Attack with Planning Mode

- data/campaigns/Winds_of_Fate/utils/macros.cfg
The way it's written prevents undoing the recall action of the filtered unit trees (Drake Arbiter, Drake Thrasher and Drake Warrior). It is better to activate the event only if the other conditional is also fulfilled, it is unnecessary in the rest of the cases.
What I have done is simply moved the conditional from [if] to the [filter_condition] of the event itself
Just to clarify for those who don't know, the code makes the unit loyal if the original loyal of the same type tree died or was removed from the recall list. I've tested all cases with the new filters and works fine.
> WoF make recall of some unit type trees undoable

- src/units/unit.hpp
#7363 added a new invulnerable state but neglected to increment the number of states.
I'm not sure if there's a better way of doing this.
> Units: Try to avoid hard-coding of size of known boolean states

- src/synced_commands.cpp
Resolves #7402.
Took me a while to find the relevant `stoi` call - not sure if 'replay' is the right log domain but I'm just following the convention used elsewhere in this file.
When I checked, normal (debug) unit advancement still works and attempting to use a string argument does nothing (but logs the warning) instead of completely crashing.
Could be back-ported as the bug is present for 1.16 as well.
> Catch invalid argument exception for stoi in unit advancement

- data/campaigns/Winds_of_Fate/scenarios/03_The_Contention.cfg
- data/campaigns/Winds_of_Fate/scenarios/08_Overlook.cfg
This resolves #7410  and the same situation on S08 Overlook, when the units escapes from the cave on 31,1
Uses the pre_teleport animation (in the absence of another specific animation for drakes), which does a smooth fade effect and is automatically generated on any unit.
> WoF S03,S08 - Added animation when units go to recall list

- changelog.md
- data/campaigns/Under_the_Burning_Suns/scenarios/05_A_Subterranean_Struggle.cfg
Closes #7394 
Line 846 (changing the position of the troll) is meant as a fix to a borderline issue, where Kaleh is in a position where he can't reach the keep if the player allies the dwarves, but can if he allies the trolls (because Zone of Control) - a different approach could be setting the troll in 30, 28. Not a major change anyways.
As seen in the picture, Kaleh can't get to the keep via the 6-moves that is represented with the blue line, as it crosses two tiles with ZoC and he can't reach either via the 7-moves represented with the green line, as it is too far away.
Kaleh would be able to reach the keep with the new position of the troll.
Line 933 is a debug message, useful for debugging or playtesting later.
Lines 934 - 973 
- If kaleh is the explorer, he just says "Whoa." and …
> UtBS S05 add logic to the main cavern event so scouting is taken into account

- src/help/help_impl.cpp
The `[trait]availability=` attribute acts as a part of the parent tag, not as a part of the trait itself. For example, `[trait]id=fearless` occurs in both the `TRAIT_FEARLESS` and `TRAIT_FEARLESS_MUSTHAVE` macros, and the trait is:
* Must-have for units: Ghast, Ghoul, ...
* Available for non-leaders of race: Troll
* Available for non-leaders of types: Dune Paragon, HI, ...
Showing a single "Availability:" in the help is therefor misleading. Adding a detailed list of where it's available adds a lot of code complexity for little gain; this commit takes the code cleanup and comments from prototyping that, but just removes the "Availability:" text from the help.
> Help: don't display trait availability, and refactor code

- data/schema/core/actionwml.cfg
- data/schema/core/addons.cfg
- data/schema/units/types.cfg
- data/tools/Makefile
This uses tabs instead of spaces, because although that's not our coding standard, it is only a few lines of changes.
The alternative of running wmlindent on these files changes 4700 lines; while I'm in favor of doing it, it's discussed in #5709.
> Fix mixed indents in the schema, and verify new additions

- CMakeLists.txt
- SConstruct
- changelog_entries/glibcxx_assertions.md
Turning GLIBCXX_ASSERTIONS adds some bounds checks, such as checking in std::string::operator[]. It's a subset of the checks that GLIBCXX_DEBUG adds, but has the advantage that it doesn't require a rebuild of the Boost libraries.
None of the CI builds enable these assertions, as they slow down the code which makes the unit tests time out.
This makes it easy to replicate #7412.
> Add a CMake and SCons flag for GLIBCXX_ASSERTIONS without GLIBCXX_DEBUG

- data/gui/window/core_dialog.cfg
- data/gui/window/debug_clock.cfg
- data/gui/window/drop_down_list.cfg
- data/gui/window/editor_edit_scenario.cfg
- data/gui/window/editor_edit_side.cfg
- data/gui/window/editor_resize_map.cfg
- data/gui/window/language_selection.cfg
- data/gui/window/mp_create_game.cfg
- data/gui/window/unit_recall.cfg
- data/gui/window/wml_message.cfg
This isn't the complete set needed to allow `check_mixed_indent` to run over the data/gui directory, it's just these small changes:
* Remove the single space from lines indented "tab ... tab space".
* Convert lines indented with "tab ... tab four_spaces".
Although these are WML files, the coding standard for the data/gui directory is to indent with tabs instead of spaces.
These are whitespace-only changes, so I'm planning to merge after 24 hours unless someone comments on it.
> GUI: fix indentation that uses both tabs and spaces on the same line

- src/font/text.cpp
- src/font/text.hpp
A couple of functions become private. Although render_texture(viewport) is dead code I think it's useful enough as documentation to leave it in, at least until we work out how to fix #6952, the crash when trying to show the long text in the end_credits screen.
The removed render_surface() would be private because it returns a surface with render-space width and height, however it was also never called and wouldn't be useful as documentation.
While I understand the implementation of this class, I've not spent time to understand the overview of the design for the high-dpi support; please review assuming that I'm not going to be looking further at this area of the GUI code in the near future, so if you want more explanation about the implementation or if I've used the wrong terminology …
> Improve docs about pango_text's high-dpi encapsulation

- src/server/campaignd/server.cpp
- src/server/campaignd/server.hpp
If interacting with a campaignd instance that has a fresh configuration or is otherwise missing the `[server_info]` tag, the client will present the player with completely blank licensing terms. This was caused by a logic issue with the processing of `[server_info]` wherein no default attribute values would ever be loaded if the tag was missing.
(This has never been relevant or found on the production campaignd instances because all of them have `[server_info]` tags explicitly provided for the purpose of formatting add-on forum thread URLs.)
> campaignd: Fix blank license terms if [server_info] is missing

- data/campaigns/Son_Of_The_Black_Eye/scenarios/03_Toward_Mountains_of_Haag.cfg
- data/campaigns/Son_Of_The_Black_Eye/scenarios/05_To_the_Harbor_of_Tirigaz.cfg
Kapou'e does not appear to be making a comical statement, 'our rear' could be interpreted (admittedly, in a juvenile fashion) as 'rear end', or posterior.
Since #7454 was accepted I think this is a good time to make this change as well (noted this a long time ago but refrained from changing due to the complaints about re-translation overhead).
> SotBE: Replace unfortunate wording

- data/campaigns/Northern_Rebirth/scenarios/01_Breaking_the_Chains.cfg
- data/campaigns/The_South_Guard/scenarios/04_Vale_of_Tears.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/08_Out_of_the_Frying_Pan.cfg
Retested all scenarios in #6832 all are working fine, including the scenarios having the fixes reverted.
c1b6bfba34d777c6d854eb49af37db645c256c0b and cd9e92c3c3323ccc6ce41243cac01720d29d849b don't include changes to the changelog file, that's why the commits are different from bb2de96d71b88ee5561ab6b67c4a29c422244f23.
Closes #6832
> Revert WML workarounds on mainline replay OOS issues

- INSTALL.md
Add libboost coroutine and libssl to needed build libraries in INSTALL.md. Resolve #7475
> Add libboost coroutine and libssl to needed build libraries in INSTALL.md. Resolve #7475

- src/filesystem.hpp
- src/filesystem_sdl.cpp
- src/picture.cpp
unique_ptr is designed to allow EBO (empty base class optimization)
for the use case of SDL_RWops this fits well and allows the UP to be half the size it is now (8 bytes vs 16 bytes on x86-64)
see this compiler explorer link:
https://godbolt.org/z/KjnTeqhbv
it also allows easier construction of the unique_ptrs as the ctor no longer requires passing the address of the function to call
since runtime setting of the deleter is not required, that's an added bonus
> EBO for unique_ptr with SDL_RWops

- data/campaigns/Descent_Into_Darkness/scenarios/08_Alone_at_Last.cfg
Resolves #7485.
I tested with 'Walking' Corpse Bat, Soulless Bat, and regular (humanoid) Walking Corpse and regular Soulless. First two behave the same as live bats (aside from not squeaking) while the latter two behave as a regular unit picking up the book normally. Re-using Malin's line about the bat avoids translation overhead.
I think this should be back-ported too.
> DiD S8: Disallow undead bat from retrieving the Book

- src/display.cpp
- src/filesystem.cpp
- src/filesystem.hpp
- src/serialization/preprocessor.cpp
- src/serialization/preprocessor.hpp
Remove a couple cases where the same header was included in both .cpp and .hpp of some modules. No harm really, but it looks like it was either the result of a merge conflict resolution or simply an omission.
Since I was there, remove copying of `default_blacklist` in multiple TUs, which include `filesystem.hpp`, by using extern (instead of a static const) inside the header. TBH `inline` would have worked just the same, but since the filesystem module already has a .cpp might as well just put it to use.
> Minor fixes filesystem

- src/picture.cpp
- src/picture.hpp
Gets rid of that dreadful last_index stuff. It basically meant a slot was reserved for every image locator in every cache (even if never populated) rather than only the needed cache. The index was also never reset for the lifetime of the program. This new design uses a hashmap based on the locators themselves.
> Overhaul image cache to be hash-based rather than index-based

- src/attack_prediction.cpp
- src/random.hpp
This makes it match the documentation, although it makes no practical difference, other than solving one of the -Wshorten-64-to-32 warnings.
> Make rng::get_random_element return an index, not an int

- src/config.cpp
- src/config.hpp
Use std::size_t instead of unsigned int for container sizes.
There's one place where it still uses signed int, for using a negative index to access children from the end of the array. Overflow shouldn't be a worry here, as it would require 2**31 objects to be in the container, implying the container and children would use at least 32GB even if every child object was empty.
This expanded from review comments on Pentarctagon's #7451, seemed sensible to just make a PR. It goes in a different direction from that PR, trying to clean up the code's behavior instead of documenting what the compiler was already doing to the old code.
> Fix -Wshorten-64-to-32: config.hpp and config.cpp

- data/core/units/undead/Skele_Bone_Knight.cfg
Skeleton Rider: _has_ submerge
Bone Knight: does not...
This PR fixes this.
> Units: Add `submerge` ability to Bone Knight and solve RIPLIB

- src/editor/palette/editor_palettes.cpp
- src/editor/palette/editor_palettes.hpp
- src/editor/palette/location_palette.cpp
- src/editor/palette/location_palette.hpp
- src/editor/palette/palette_manager.cpp
- src/editor/palette/palette_manager.hpp
Use int for measurements of pixels, vs std::size_t for container sizes.
The scroll_bottom() methods were never called, although scroll_top() is used when switching between subgroups. The logic is scroll_bottom() was broken; items_start wasn't changed inside the loop, so the loop would run at most once.
> Editor palettes: fix -Wshorten-64-to-32 and improve docs

- data/core/units/monsters/Caribe_Nibbler.cfg
Closes #7516
Nibbler now has the same resistances as the level 1 (Caribe) and level 2 (Hunter Caribe)
> Units/Nibbler: set resistances to be same as level ups

- src/display.hpp
- src/display_context.hpp
- src/game_display.hpp
Silence the warnings in `viewing_side()` and `playing_side()` with a `static_cast`.
The static casts are for -Wshorten-64-to-32 warnings, it would take a lot of work to fix this in a better way.
> Add comments to display and display_context, silence 64-to-32 warnings

- src/utils/math.hpp
The last uses of this were removed in 0fbc12ea01986bc97ef6426e0edc89f12224a0d5.
The only uses of the other fixed-point functions from math.hpp are in src/sdl/utils.cpp. That should probably move to using color.hpp instead, but this commit is just to solve the -Wshorten-64-to-32 warning.
> Fix -Wshorten-64-to-32: math.hpp
