wesnoth/wesnoth

- data/gui/window/migrate_version_selection.cfg
- source_lists/wesnoth
- src/filesystem.cpp
- src/filesystem.hpp
- src/game_config.cpp
- src/game_config.hpp
- src/gui/dialogs/migrate_version_selection.cpp
- src/gui/dialogs/migrate_version_selection.hpp
- src/gui/dialogs/title_screen.cpp
- src/wesconfig.h
Currently migrated, if existing:
* Add-ons (redownloaded if present on new add-ons server)
* Preferences file
* Credentials file
> Add a prompt to migrate data from previous versions of wesnoth.

- data/core/units/monsters/Frost_Stoat.cfg
- data/lua/core/wml.lua
- data/lua/wml-tags.lua
- src/game_data.cpp
- src/scripting/game_lua_kernel.cpp
- src/scripting/lua_common.hpp
- src/scripting/mapgen_lua_kernel.cpp
Forward-ports of the last batch, another random fix I stumbled across, and some small new features. I'll probably merge once CI passes.
> Stuff for CI

- data/campaigns/World_Conquest/_main.cfg
- data/campaigns/World_Conquest/scenarios/WC_II_scenario.cfg
Same as PR #5958 but for master branch
> [world conquest] [master/1.17] add credits, campaign icon(s) and image.

- src/mp_game_settings.cpp
> Have add-ons with no min version specified require the latest version.

- changelog.md
- data/campaigns/Liberty/scenarios/06_The_Hunters.cfg
Back-port #6025 to 1.16 branch.
> Resolve #6019 - allied side not triggering failure condition when sighted (1.16)

- data/campaigns/World_Conquest/lua/map/scenario_utils/plot.lua
Fixes the campaign part of #5891.
(forward-port of #6039)
> WC: End the campaign at the end of the final scenario

- data/campaigns/Delfadors_Memoirs/scenarios/06_Swamps_of_Illuven.cfg
Introduced in #5382, discussion seems to agree that we should avoid this.
> Avoid contemporary phrasing

- data/campaigns/Delfadors_Memoirs/scenarios/06_Swamps_of_Illuven.cfg
As per suggestion from @CelticMinstrel
> Rephrase #6060

- data/multiplayer/scenarios/2p_Aethermaw.cfg
fixes #1406
I'm not sure if changing directories with "../" is allowed.
EDIT: looks like World Conquest does something similar, so I guess it's OK.
> 2p_Aethermaw - fix sprit decorations above fog

- src/server/wesnothd/game.cpp
- src/server/wesnothd/game.hpp
Also removed some methods/parameters that are not used.
> Add doxygen docs to wesnothd's game.hpp.

- data/campaigns/Legend_of_Wesmere/scenarios/chapter2/04_The_Elvish_Treasury.cfg
See issue #4880 for discussion.
> LoW S4: Avoid use of 'men' with respect to female elves (resolves #4880)

- data/campaigns/Under_the_Burning_Suns/scenarios/02_Across_the_Harsh_Sands.cfg
> UtBS: Correct inconsistency in Ring description

- data/campaigns/The_Rise_Of_Wesnoth/scenarios/12_A_Final_Spring.cfg
> TRoW S12: Always give Lord Typhon a storm trident

- data/campaigns/Secrets_of_the_Ancients/scenarios/10_Merfolk_Revenge.cfg
- data/campaigns/Secrets_of_the_Ancients/scenarios/11_Battleground.cfg
- data/campaigns/Secrets_of_the_Ancients/scenarios/13_Together_Again.cfg
- data/campaigns/Secrets_of_the_Ancients/scenarios/14_Entering_the_Northlands.cfg
- data/campaigns/Secrets_of_the_Ancients/scenarios/15_Mountain_Pass.cfg
- data/campaigns/Secrets_of_the_Ancients/scenarios/18_Abandoned_Outpost.cfg
- data/campaigns/Secrets_of_the_Ancients/scenarios/19_Lava_and_Stone.cfg
Had to close #6129 because I messed with the branch that had changes (by pressing fetch upstream). Here is a new pull request of a clean branch of my changes. #6129 was already approved, so just go ahead and merge this.
> Sota proofread

- data/campaigns/Sceptre_of_Fire/scenarios/2t_In_the_Dwarven_City.cfg
Add a reference to SotA North Knalga in Sceptre of Fire.
> Reference SotA in SoF, closes #6151

- src/format_time_summary.cpp
- src/gui/dialogs/addon/manager.cpp
- src/save_index.cpp
> Add translation hints for time format strings

- src/server/common/dbconn.cpp
- src/server/common/dbconn.hpp
- src/server/common/forum_user_handler.cpp
- src/server/common/forum_user_handler.hpp
- src/server/common/user_handler.hpp
- src/server/wesnothd/server.cpp
---
I had already fixed this issue on the client side a while ago, but perhaps WCII has another way of triggering it.
> Check for potential duplicates before inserting.

- src/gui/widgets/chatbox.cpp
> Check whether to display lobby joins in the game creation screen.

- data/campaigns/The_Rise_Of_Wesnoth/scenarios/08_Clearwater_Port.cfg
> Refactor the boarding events for TRoW S8 Clearwater Port

- data/campaigns/Secrets_of_the_Ancients/scenarios/02_Dark_Business.cfg
- data/campaigns/Secrets_of_the_Ancients/scenarios/07_Meeting_of_the_Minds.cfg
- data/campaigns/Secrets_of_the_Ancients/scenarios/11_Battleground.cfg
- data/campaigns/Secrets_of_the_Ancients/scenarios/13_Together_Again.cfg
> Capitalise references to the Academy of Magic on Isle of Alduin

- src/gui/dialogs/multiplayer/lobby.cpp
> Prompt moderators to observe game with observers disabled.

- data/campaigns/Under_the_Burning_Suns/scenarios/09_Blood_is_Thicker_Than_Water.cfg
Resolves #6229.
I debug-tested this and it seemed to work as intended, but of course, please point out any mistakes or any suggestions you have.
> UtBS S9: Avoid 'punishing' the player for saving the rebels

- changelog.md
That should do it,. If I did something wrong I'll fix it later.
> Update 1.16 Changelog with my backported PRs

- data/campaigns/Descent_Into_Darkness/_main.cfg
- data/campaigns/Descent_Into_Darkness/scenarios/08_Alone_at_Last.cfg
- data/campaigns/Descent_Into_Darkness/utils/characters.cfg
- data/core/macros/optional_unit_advancements.cfg
another fix off https://github.com/wesnoth/wesnoth/issues/6351
> fix Did advancement

- changelog.md
- data/campaigns/Under_the_Burning_Suns/scenarios/09_Blood_is_Thicker_Than_Water.cfg
As per @nemaara's directive. Resolves #6365.
CC: @Descacharrado
> UtBS S9: Turn rebels into loyal units

- data/campaigns/Under_the_Burning_Suns/scenarios/04_Descending_into_Darkness.cfg
Now the event triggers when the player gets sight on Panok (the goblin leader) moving.
Closes #6266
> UtBS S04 - enhance goblin leader trigger "how can he move that fast?"

- .github/workflows/ci-scripts/macos.sh
Not really sure why they're able to run now.
---
Will merge after CI passes.
> Run the WML unit tests on macOS.

- src/menu_events.cpp
- src/mouse_events.cpp
- src/mouse_events.hpp
Forward-port of #6405, so just running the CI and testing locally.
Fixes #6292.
> Only show planned moves to self and allies in multiplayer

- data/campaigns/World_Conquest/lua/game_mechanics/artifacts.lua
> [world conquest] Fix for HP glitch when picking up items/artifacts

- src/help/help_topic_generators.cpp
Backport of #6400 and the follow-up change of "on to" to "onto". Already reviewed, so will merge once the CI passes.
The notes are automatically added based on the terrain's properties,
there isn't a way to add or remove them in WML.
Any questions about negative values for gives_healing() are issue #4232.
(cherry picked from commits 1afb7effc490d2c7c12116d278fc07c465c54f57
and d3e1c73ca10ea51cb2bccbb7657a90a708feb2b1)
> [1.16] Add a "special notes" section to terrain help pages

- src/chat_command_handler.cpp
- src/chat_command_handler.hpp
- src/chat_events.hpp
- src/gui/widgets/chatbox.cpp
- src/gui/widgets/chatbox.hpp
- src/menu_events.hpp
- src/tests/gui/test_gui2.cpp
Solves #3202
Add `/clear` chat command
(cherry-picked commit from https://github.com/wesnoth/wesnoth/pull/6457)
> Add /clear chat command

- data/core/about.cfg
Add max_torch as miscellaneous contributor.
> Add max_torch to about.cfg

- src/game_config_manager.cpp
Postponed until 1.16.3 due to string freeze.
Closes #6204.
Supersedes PR #5922, which is why it was opened as a draft before 1.16.2 released.
The existing code searched for `[units][advancefrom]` instead of
`[unit_type][advancefrom]`, so wasn't triggering. It was planned
for removed in 1.17, so simply mark it as already-removed instead.
The deprecation warning is shown on stdout/stderr, but not in the
in-game UI, so it's generally not visible to players. I think it
would be better if it was visible, but OTOH it's something that's
easy for someone to check all add-ons for with a simple grep.
> [1.16.3] Fix deprecation of [advancefrom], mark as already removed

- data/test/macros/wml_unit_test_macros.cfg
- data/test/scenarios/ability_id_not_active_test.cfg
- data/test/scenarios/as_text.cfg
- data/test/scenarios/conditionals.cfg
- data/test/scenarios/event_handlers_in_events.cfg
---
This PR is the start of three steps I'm going go through as I'm able:
1) Add code documentation to the existing unit tests.
2) Reorganize the existing unit tests into directories based on which APIs they are testing.
3) Add more tests to fill in the areas that don't have any unit test coverage.
> Add code comments stating what each unit test is testing.

- data/campaigns/World_Conquest/lua/map/scenario_utils/side_definitions.lua
```lua
share_view = true,
```
To:
```lua
share_vision = "all",
```
> [world conquest] update deprecated share_view to share_vision

- data/campaigns/Winds_of_Fate/maps/09_Ancestor.map
This patches the following:
https://cdn.discordapp.com/attachments/438001869906903060/934966013311737936/unknown.png
Context: At the second stage, the player has to team up with the dragon and kill all enemies...but this cave bear is unreachable so scenario never ends
> WoF: update map of S9 To stop a Cave Bear spawning at an unreachable location

- data/core/about.cfg
Add larb0b as a miscellaneous contributor. Was pinged about this in #6475.
> Add larb0b to about.cfg

- data/core/about.cfg
Add myself as a miscellaneous contributor; see #6475
Past commits: https://github.com/wesnoth/wesnoth/commits?author=cooljeanius
Inspired by #6545
> Add egallager to about.cfg

- data/core/units/monsters/Boar_Piglet.cfg
Possibly unnecessary, but can't hurt.
> Piglets: add a po hint that these are wild boars' young

- projectfiles/CodeBlocks/liblua.cbp
Fix https://github.com/wesnoth/wesnoth/issues/6562 isue
> update codeblock projetfiles

- scons/sdl.py
---
Just waiting to see that the scons jpg check passes, then I'll merge.
> Use non-attic jpg file.

- data/test/scenarios/simulate_combat_clone_adjacent.cfg
- data/test/scenarios/simulate_combat_occupied.cfg
- wml_test_schedule
Forward-port of #6569, just running the CI.
(cherry picked from commit d96968b2ec0ea3198982fc530ee68054dd19af63)
> Add unit tests for Lua API wesnoth.simulate_combat

- data/campaigns/Descent_Into_Darkness/scenarios/08_Alone_at_Last.cfg
> [DID] [Alone at Last] Ensure Spectral Servant unit-line cannot pick up the book

- src/gui/core/event/dispatcher.hpp
- src/utils/general.hpp
> Attempt to actually make this a compile-time check

- src/addon/client.cpp
- src/addon/validation.cpp
- src/addon/validation.hpp
- src/server/campaignd/server.cpp
- src/server/campaignd/server.hpp
- src/server/common/forum_user_handler.cpp
- src/server/common/forum_user_handler.hpp
- src/server/common/user_handler.hpp
---
Re-PR of #5836 so it's off my fork's master branch since it won't make it for 1.16.0.
@irydacea When you have some time, I'd appreciate an in depth description of what you're looking for in terms of UI changes and how the password would be stored.  I know we talked about it a bit on Discord, but I'm still having a hard time coming up with an implementation.
> Add support for forum_auth when uploading to campaignd.

- data/campaigns/World_Conquest/scenarios/WC_II_scenario.cfg
incorrect image path after merger of #6655 so patching it
> [wc2p] fix broken icon image path for WC2P campaign

- changelog.md
- src/controller_base.cpp
- src/controller_base.hpp
I tested it briefly and it's working as expected.
I also updated the changelog.
> Backport smooth scrolling fix

- utils/woptipng.py
This PR simply just adds an encoding comment, as per: https://peps.python.org/pep-0263/
> Update woptipng.py to add encoding line

- src/picture.cpp
I made it log a warning when it replaces, because while this will work fine, it indicates a bug if it happens in a fresh install or newly started campaign.
Fixes https://github.com/wesnoth/wesnoth/issues/6696
> Automatically replace missing .png graphics with .webp if found.

- src/arrow.cpp
- src/arrow.hpp
Here are some small spacing issues and a return that seems clearer
> Add explicit + some cleanup in arrow.h/cpp

- data/test/scenarios/test_add_or_sub_in_leadership.cfg
- src/actions/attack.cpp
- src/actions/heal.cpp
- src/units/abilities.cpp
- src/units/abilities.hpp
Fix https://github.com/wesnoth/wesnoth/issues/6466 issue.
> 1.17 fix cumulative=yes don't function for [leadership]

- src/video.cpp
> Potential fix for hardware-rendering high-dpi issues on Mac.

- changelog.md
- data/campaigns/Northern_Rebirth/scenarios/01_Breaking_the_Chains.cfg
Closes #6735
The new strings are not set in stone.
> NR S1 Vary the die dialog depending on race

- src/actions/attack.cpp
- src/tod_manager.cpp
- src/tod_manager.hpp
Resolve https://github.com/wesnoth/wesnoth/issues/6740 issue. Based on last proposition of @CelticMinstrel
> Make Liminal be sensitive to overillumination/overdarkening

- packaging/windows/SConscript
- packaging/windows/wesnoth.exe.manifest
- src/font/font_config.cpp
- src/wesnoth.cpp
See #1549 for the background here. For now just creating this PR so the CI will generate a windows installer with these changes applied to see if it also fixes a potentially related issue.
> Use fontconfig

- .github/workflows/ci-scripts/macos.sh
> Unsetting macOS code signing is no longer needed.

- src/picture.cpp
aimed at fixing https://github.com/wesnoth/wesnoth/issues/6782
> Flush texture caches on :refresh

- src/gui/dialogs/network_transmission.cpp
- src/gui/dialogs/network_transmission.hpp
This seems to have been applied to 1.14, but not 1.15/master at the time.
> Manual forward-port of #4244.

- src/tests/main.cpp
Fix https://github.com/wesnoth/wesnoth/issues/6834 issue in wait of best resolving.
> fix compilation issue in src/test/main.cpp

- projectfiles/CodeBlocks/campaignd.cbp
- projectfiles/CodeBlocks/tests.cbp
- projectfiles/CodeBlocks/wesnoth.cbp
- projectfiles/CodeBlocks/wesnothd.cbp
> Revert "update codeblock projectfiles"

- changelog.md
- src/hotkey/hotkey_item.cpp
- src/sdl/input.cpp
- src/sdl/input.hpp
> Fix being unable to interact with units when scroll lock is active

- changelog.md
- src/hotkey/hotkey_item.cpp
The simple parts of https://github.com/wesnoth/wesnoth/pull/6840
> Backport scroll lock fix

- src/draw.cpp
- src/draw.hpp
- src/gui/core/canvas.cpp
- src/minimap.cpp
> Clear minimap render textures

- .github/workflows/ci-scripts/macos.sh
- src/tests/test_config_cache.cpp
Currently this is just to test if it even works. I'm not sure whether or not it's a good idea.
> Run Boost unit tests on MacOS CI

- src/gui/widgets/minimap.cpp
> GUI2/minimap: Mark minimap dirty when updating

- projectfiles/CodeBlocks/tests.cbp
- projectfiles/CodeBlocks/wesnoth.cbp
remove unused tracer.cpp source file
> update codeblock projectfiles

- src/log.cpp
---
Letting this go through CI just in case first.
> Remove one more std::cerr.

- changelog.md
- data/campaigns/The_South_Guard/scenarios/04_Vale_of_Tears.cfg
> TSG S4 Fixed replay OOS on victory event

- data/schema/core/actionwml.cfg
Fixup for 715cf386, planning to merge when the CI finishes.
> Schema: the [fire_event][data] tag is optional

- data/campaigns/Northern_Rebirth/scenarios/02_01_Infested_Caves.cfg
- data/campaigns/Northern_Rebirth/scenarios/02_02_Meeting_With_Dwarves.cfg
- data/campaigns/Northern_Rebirth/scenarios/03_To_the_Mines.cfg
- data/campaigns/Northern_Rebirth/scenarios/05a_02_Dealings.cfg
- data/campaigns/Northern_Rebirth/scenarios/13a_Showdown.cfg
> NR: give hamel leadership

- data/campaigns/Sceptre_of_Fire/scenarios/7_Outriding_the_Outriders.cfg
> [SoF] In S7, edit a sentence to not use awkward reuse of the word "doubt"

- data/core/hotkeys.cfg
This prevents unneeded collisions.
No keys are changing with this PR.
> Changed and added hotkeys

- src/font/text.cpp
- src/font/text.hpp
- src/game_launcher.cpp
- src/picture.cpp
- src/video.cpp
- src/video.hpp
Probably does the F-word you should never say on github to #6950
> Clear all texture caches before game end

- data/test/scenarios/events-test_filterable1.cfg
- data/test/scenarios/events-test_pre_attack.cfg
- data/test/scenarios/test_unit_map.cfg
- src/actions/attack.cpp
- wml_test_schedule
This addresses #4075
---
This is a re-PR of #4083 - I'll be testing and adding some unit tests for it, and if everything works then I'll merge it.
> Add pre attack event

- src/font/text.cpp
> Font/Text: tweak line height

- data/gui/window/mp_faction_select.cfg
- src/gui/dialogs/statistics_dialog.cpp
I added contexts to the word Recruits to be able to translate it by proper Czech words.
> distinguish noun from verb

- add_source_file
Usage: `./add_source_file <filename> [target ...]`
Targets are "wesnoth", "wesnothd", "campaignd", "lua", "tests".
It defaults to the "wesnoth" target.
The 'pbxproj' python package is required to modify the Xcode project. As may be inferred, this is a Python script.
It probably works? I don't know, really. It adds some stuff and looks vaguely correct.
It also sorts the `source_lists` files when adding to them, if that's a problem it can be made to not do that.
> A script to add new source files

- src/gui/dialogs/multiplayer/lobby.cpp
- src/gui/dialogs/multiplayer/lobby.hpp
Rather than always opening your own.
> Open the forum profile of the currently selected user.

- changelog.md
- data/core/about.cfg
- src/commandline_options.cpp
- src/commandline_options.hpp
- src/filesystem.cpp
- src/filesystem.hpp
- src/wesnoth.cpp
> Make cache directory configurable too.

- data/campaigns/Under_the_Burning_Suns/scenarios/04_Descending_into_Darkness.cfg
> [UtBS] S4 extra dialog to acknowledge effect of finding the map in S3

- packaging/flatpak/org.wesnoth.Wesnoth.json
- utils/dockerbuilds/CI/Dockerfile-base-flatpak
> Update flatpak runtime to freedesktop 22.08.

- src/reports.cpp
> Fix #4456: Sidebar abilities display leaks shrouded information

- data/campaigns/World_Conquest/lua/era/era.lua
- data/campaigns/World_Conquest/lua/map/scenario_utils/plot.lua
Re-PR of #6538 without the problematic second commit.
> Re pr 6538

- data/schema/units/specials.cfg
- src/actions/attack.cpp
- src/actions/attack.hpp
- src/actions/heal.cpp
- src/attack_prediction.cpp
- src/gui/dialogs/attack_predictions.cpp
- src/gui/dialogs/unit_attack.cpp
- src/reports.cpp
- src/scripting/game_lua_kernel.cpp
- src/tod_manager.cpp
- src/units/abilities.cpp
- src/units/abilities.hpp
- src/units/attack_type.hpp
- src/units/types.cpp
- src/units/unit.cpp
the old code of deprecated backstab is removedin this PR and wml code used intead pushed in backstab attribute for it's work
> Remove deprecated backstab code and using wml filters instead

- data/advanced_preferences.cfg
- src/preferences/general.cpp
- src/preferences/general.hpp
- src/server/common/server_base.cpp
- src/wesnothd_connection.cpp
- src/wesnothd_connection.hpp
Also adds a windows version of keepalive to the servers.
Resolves #1336
---
I'm not too sure what would be a good test of this, however.
> Enabled client-side keepalive.

- data/campaigns/Eastern_Invasion/scenarios/11_Captured.cfg
> EI S11: update inconsistency on northern orcs/trolls

- data/campaigns/Legend_of_Wesmere/scenarios/chapter4/13_News_from_the_Front.cfg
- data/campaigns/Northern_Rebirth/scenarios/04_Clearing_the_Mines.cfg
- data/campaigns/Northern_Rebirth/scenarios/05a_01_The_Pursuit.cfg
- data/campaigns/Northern_Rebirth/scenarios/06a_Old_Friend.cfg
- data/campaigns/Northern_Rebirth/scenarios/07a_Settling_Disputes.cfg
- data/campaigns/Northern_Rebirth/scenarios/08a_Elvish_Princess.cfg
- data/campaigns/Northern_Rebirth/scenarios/09a_Introductions.cfg
- data/campaigns/Northern_Rebirth/scenarios/10a_Stolen_Gold.cfg
- data/campaigns/Northern_Rebirth/scenarios/11a_The_Eastern_Flank.cfg
- data/campaigns/Northern_Rebirth/scenarios/12a_Get_the_Gold.cfg
- data/campaigns/Northern_Rebirth/scenarios/13a_Showdown.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/9_Caverns_of_Flame.cfg
- data/campaigns/Secrets_of_the_Ancients/scenarios/06_Following_the_Shadow.cfg
- data/campaigns/Secrets_of_the_Ancients/scenarios/22_Epilogue.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/08_Out_of_the_Frying_Pan.cfg
- data/campaigns/Winds_of_Fate/scenarios/01_The_Hunt.cfg
- data/campaigns/Winds_of_Fate/scenarios/05_Threshold.cfg
- data/campaigns/Winds_of_Fate/scenarios/11_Crosswind.cfg
Fix unknown speaker or id errors
See #4494
> Fix unknown speaker errors

- data/core/terrain.cfg
> add missing terrain type alias to elevation markers

- src/gui/dialogs/unit_attack.cpp
Fix https://github.com/wesnoth/wesnoth/issues/7088 issue
> Fix "Chance to hit" not translated in tooltip

- data/campaigns/Dead_Water/scenarios/11_Getting_Help.cfg
- data/campaigns/Delfadors_Memoirs/scenarios/01_Overture.cfg
- data/campaigns/Delfadors_Memoirs/scenarios/05_Council_in_Weldyn.cfg
- data/campaigns/Eastern_Invasion/scenarios/15_The_Council.cfg
- data/campaigns/Heir_To_The_Throne/scenarios/21_Elven_Council.cfg
- data/campaigns/Legend_of_Wesmere/scenarios/chapter4/13_News_from_the_Front.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/2t_In_the_Dwarven_City.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/3t_The_Council_Regathers.cfg
- data/campaigns/Sceptre_of_Fire/scenarios/4t_The_Jeweler.cfg
- data/campaigns/Secrets_of_the_Ancients/scenarios/07_Meeting_of_the_Minds.cfg
- data/campaigns/Secrets_of_the_Ancients/scenarios/13_Together_Again.cfg
- data/campaigns/Secrets_of_the_Ancients/scenarios/17_Mortality.cfg
- data/campaigns/The_Rise_Of_Wesnoth/scenarios/07_Return_to_Oldwood.cfg
- data/campaigns/The_Rise_Of_Wesnoth/scenarios/11_Southbay_in_Winter.cfg
- data/campaigns/The_Rise_Of_Wesnoth/scenarios/16_The_Kalian.cfg
- data/campaigns/The_Rise_Of_Wesnoth/scenarios/18_A_Spy_in_the_Woods.cfg
- data/campaigns/The_Rise_Of_Wesnoth/scenarios/21_The_Plan.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/10_Speaking_with_the_Fishes.cfg
Resolves #6180.
Resolves #7123.
> Disable saving of replays for story-only scenarios

- data/campaigns/Heir_To_The_Throne/scenarios/14_Plunging_Into_the_Darkness.cfg
> HttT S14: give Relgorn his missing traits

- src/wesnoth.cpp
the code that does autodetection looked like it could be put inside a function - add a function that explains what it does
avoid some string copying and move where possible
use scoped ifs (c++17) to limit scope of local variables
> Refactor autodetect_game_data_dir into function

- src/units/abilities.cpp
using code of https://github.com/wesnoth/wesnoth/commit/67f2c32c54e65055abc909e219a87c65ad11ea14 commit in overwrite_specials
> include Refactor ability lists using utils::erase_if and std::remove_if to overwrite_specials

- data/test/scenarios/swarm_disables_upgrades.cfg
- data/test/scenarios/test_add_or_sub_in_leadership.cfg
- data/test/scenarios/test_assert.cfg
- data/test/scenarios/test_berserk_firststrike.cfg
- data/test/scenarios/test_check_victory.cfg
- data/test/scenarios/test_clear.cfg
- data/test/scenarios/test_create_side.cfg
- data/test/scenarios/test_cve_2018_1999023.cfg
- data/test/scenarios/test_dofile.cfg
- data/test/scenarios/test_effect_on_vision.cfg
- data/test/scenarios/test_end_turn.cfg
- data/test/scenarios/test_for_tag.cfg
- data/test/scenarios/test_grunt_tod_damage.cfg
- data/test/scenarios/test_lua_color.cfg
- data/test/scenarios/test_lua_name.cfg
- wml_test_schedule
---
Skipped over `test_force_chance_to_hit_macro` for now since it's changing in #7050.
> More unit test documentation.

- src/gettext.cpp
See https://github.com/boostorg/locale/pull/128/
> gettext: fix build with Boost.Locale 1.81

- data/campaigns/Heir_To_The_Throne/scenarios/05b_Isle_of_the_Damned.cfg
- data/campaigns/Liberty/scenarios/01_The_Raid.cfg
> Sync Delurin between HttT and Liberty

- src/gettext.cpp
This PR is pretty simple; it fixes issue #3868 and addresses a review comment that @CelticMinstrel had left in b780da4.
> Address some minor nits in gettext.cpp

- data/campaigns/Secrets_of_the_Ancients/utils/terrain.cfg
- data/core/editor/help.cfg
The terrain elevation feature is different than the usual terrain graphics.  So this is for a help topic in the "Map and Scenario Editor->Terrain Editor" tree.
> 1.17 elevated terrain Help Topic

- data/core/terrain.cfg
> 1.17 - get elevation markers out of the mini-map

- data/gui/window/addon_auth.cfg
- src/addon/client.cpp
- src/gui/dialogs/addon/addon_auth.cpp
- src/server/campaignd/server.cpp
- src/server/campaignd/server.hpp
- src/server/common/dbconn.cpp
- src/server/common/dbconn.hpp
- src/server/common/forum_user_handler.cpp
- src/server/common/forum_user_handler.hpp
- src/server/common/user_handler.hpp
- utils/mp-server/table_definitions.sql
The secondary_authors attribute is a comma-delimited list of forum accounts that can also upload updates to an add-on. Secondary authors can't change the primary/secondary authors and can't delete the add-on.
The primary author can also make someone else the primary author by:
* Putting their username in the secondary_authors attribute
* Putting someone else's username in the author attribute
* Uploading the add-on while selecting themselves
This works since they are still (until the upload is done) the primary author in the database, so they are allowed to change the authors list, including in this case.
---
Scenarios tested locally:
* upload as primary author, no secondary authors - **succeeds**, only primary author row exists
* upload as primary author, has secondary authors - …
> Add ability to allow secondary authors to upload an add-on.

- data/campaigns/Legend_of_Wesmere/scenarios/chapter3/11_Battle_of_the_Book.cfg
- data/campaigns/Legend_of_Wesmere/scenarios/chapter4/14_Human_Alliance.cfg
- data/campaigns/Legend_of_Wesmere/scenarios/chapter4/17_Breaking_the_Siege.cfg
> LoW: Make gold carry-over consistent with objectives

- data/campaigns/Descent_Into_Darkness/scenarios/03_A_Haunting_in_Winter.cfg
- data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg
it's `[set_achievement]` (in the Lua file)
Fixes #7305
> [Achievements] add correct tag

- data/campaigns/Heir_To_The_Throne/units/Injured_Sergeant.cfg
> [HttT] [Units] make injured sergeant lie flat on ground

- data/achievements.cfg
- data/campaigns/Descent_Into_Darkness/achievements.cfg
- data/schema/achievements.cfg
- src/achievements.hpp
- src/gui/dialogs/achievements_dialog.cpp
- src/scripting/game_lua_kernel.cpp
Also hidden_name and hidden_hint are no longer attributes of [achievement].
> Have hidden achievements actually be hidden.

- data/lua/wml-tags.lua
- src/gui/dialogs/achievements_dialog.cpp
- src/gui/dialogs/achievements_dialog.hpp
- src/preferences/general.cpp
- src/preferences/general.hpp
Also give a better warning when amount isn't a number.
> Save last selected achievement to the preferences

- data/lua/wml-tags.lua
- src/preferences/general.cpp
- src/scripting/game_lua_kernel.cpp
---
@CelticMinstrel There isn't really much going on here, but I just wanted to have my use of `luaW_pcall` double checked before merging.
> Small achievements cleanup

- data/schema/units/single.cfg
> Remove hp_bar_scaling and xp_bar_scaling from [unit] schema

- data/campaigns/World_Conquest/lua/game_mechanics/promote_commander.lua
> WC: fix abnormal commander mechanic

- data/campaigns/Winds_of_Fate/scenarios/01_The_Hunt.cfg
Just a double quote by mistake
> WoF S01 typo

- data/gui/window/addon_manager.cfg
- src/gui/dialogs/addon/manager.cpp
> Display ID of addon in addon manager

- data/campaigns/Northern_Rebirth/scenarios/08a_Elvish_Princess.cfg
- data/campaigns/Northern_Rebirth/scenarios/09a_Introductions.cfg
I never got an answer to my question in #5374, but this change seems to do what was requested.
> NR: Give Eryssa hero trait since her death is a loss condition

- CMakeLists.txt
- INSTALL.md
- SConstruct
- changelog_entries/#7443
- projectfiles/Xcode/The Battle for Wesnoth.xcodeproj/project.pbxproj
- source_lists/wesnoth
- src/CMakeLists.txt
- src/gui/dialogs/multiplayer/match_history.cpp
- src/network_download_file.cpp
- src/network_download_file.hpp
- utils/dockerbuilds/CI/Dockerfile-base-2204-master
- utils/dockerbuilds/CI/Dockerfile-base-mingw
- utils/dockerbuilds/msys2/Dockerfile
- vcpkg.json
This is a complement to #7416 where it would be used to replace opening the replay's download URL in a browser.
> Add curl-based functionality to download files from a URL.

- add_source_file
- projectfiles/CodeBlocks/wesnoth.cbp
- projectfiles/Xcode/The Battle for Wesnoth.xcodeproj/project.pbxproj
- source_lists/wesnoth
- src/carryover_show_gold.cpp
- src/carryover_show_gold.hpp
- src/game_initialization/playcampaign.cpp
Pr to run the checks. Part of my current work to fix victory events in replays, Since adding a new file seems to have a rather big chance for merging conflicts (in particular the xcode projectifles, i used the add_source_file script), i want to merge this quickly.
> move carryover message to new file

- data/campaigns/Northern_Rebirth/scenarios/01_Breaking_the_Chains.cfg
So I was talking in issue #7448 and someone said that I could make some dialog changes but thought I remembered some other editing problems in the story. I looked at the first scenario and a lot of things in the story that didn't make sense on reading through. I'd like to, if you don't mind, go through each scenario and do some editing.
I don't want my editing to hurt anyone's feelings, and I tried to separate each change in a different commit. So you can pick and choose the changes and squash the commits you like. If you don't like any of the changes, you can reject them all.
I edited it as well as I could, and I ran it through LanguageTool. A lot of the problems I found were that the sentences were too long and made my eyes cross. I tried to shorten them.
> NR: Dialog/ Story Rewrite: Scenario One.

- changelog_entries/pr_7456.md
- data/campaigns/World_Conquest/config.cfg
- data/campaigns/World_Conquest/era/era.cfg
- data/campaigns/World_Conquest/lua/game_mechanics/artifacts_updated.lua
- data/campaigns/World_Conquest/lua/shared_utils/wml_converter_updated.lua
- data/campaigns/World_Conquest/resources/resources.cfg
- data/campaigns/World_Conquest/scenarios/WC_II_scenario.cfg
- src/actions/undo_action.cpp
- src/game_state.cpp
- src/hotkey/hotkey_handler.cpp
- src/hotkey/hotkey_handler_sp.cpp
- src/replay.cpp
- src/teambuilder.cpp
- src/teambuilder.hpp
- src/units/animation.cpp
- src/whiteboard/manager.cpp
Partly tested.
- the Bezoar Item works now (tested)
- custom effects work in following scenarios
- "Destruction mechanic line 73 bug"
- Promoted commanders having the wrong id.
> 1.16 Backports

- src/filesystem.hpp
based on discussions here: https://github.com/wesnoth/wesnoth/pull/7483/commits/c4439cf5ebb47f6ca5ceed4ef75690f2d1efc00b
and here:
https://github.com/wesnoth/wesnoth/commit/7bff35f991ee6bb4db4918a9165ad921a69086a7#r106243393
> remove static_assert used only for testing

- data/campaigns/Legend_of_Wesmere/scenarios/chapter2/06_Acquaintance_in_Need.cfg
Updated the proposed changes of Kalenz's speech.
> updated Kalenz's dialogue #7110

- src/gui/dialogs/addon/manager.cpp
> Set uploader attribute when forum_auth=true and passphrase exists in the pbl.

- src/units/unit.cpp
The title here is pretty self-explanatory.
Regarding use cases, this can be useful every time a unit needs to increase its level in an AMLA: for example, I have two units like this in TSoG and until now I had to use variations as a workaround for the lack of this feature. In an RPG-style add-on, this can allow a unit to level up (or down, if you wish so) as much as you want.
Implementation notes:
* there are two keys to change the unit's level, which are `increase=` and `set=`;
* negative levels are correctly supported;
* percentages aren't supported. Usually levels are small numbers so it doesn't make much sense to use percentages, but I can add them if you want;
* using `apply_to=level` and `times=per level` at the same time is disallowed to avoid confusion (would that apply to the …
> Add support for [effect] apply_to=level

- data/core/units/monsters/Fire_Dragon.cfg
- data/core/units/monsters/Skeletal_Dragon.cfg
> Crop dragon unit images to fit the side-bar window

- src/gui/dialogs/multiplayer/match_history.cpp
- src/server/common/resultsets/game_history.cpp
Fixes #7489
---
@Wedge009 I'm not able to reproduce the crash you mentioned in that issue. Could you get a stack trace for it?
> Correctly handle no game history data existing.

- src/game_events/handlers.cpp
resolve problem in https://github.com/wesnoth/wesnoth/pull/7509#discussion_r1165220995discussion
> fix test of presence of attack/second_attack in filter_attack function

- data/campaigns/Descent_Into_Darkness/achievements.cfg
- data/campaigns/Descent_Into_Darkness/scenarios/01_Saving_Parthyn.cfg
- data/campaigns/Descent_Into_Darkness/scenarios/03_A_Haunting_in_Winter.cfg
- data/campaigns/Descent_Into_Darkness/scenarios/06_Return_to_Parthyn.cfg
- data/campaigns/Descent_Into_Darkness/scenarios/08_Alone_at_Last.cfg
- data/campaigns/Descent_Into_Darkness/scenarios/09_Descent_into_Darkness.cfg
- data/campaigns/Descent_Into_Darkness/scenarios/10_Endless_Night.cfg
- data/campaigns/Descent_Into_Darkness/scenarios/11_Squidville.cfg
Like the title says. I playtested some but not others (will do that soon). It will help if others can confirm if they work as well.
> Add achievements to DiD

- data/campaigns/Liberty/achievements.cfg
- data/campaigns/Liberty/scenarios/02_Civil_Disobedience.cfg
- data/campaigns/Liberty/scenarios/04_Unlawful_Orders.cfg
- data/campaigns/Liberty/scenarios/05_Hide_and_Seek.cfg
- data/campaigns/Liberty/scenarios/06_The_Hunters.cfg
- data/campaigns/Liberty/scenarios/07_Glory.cfg
Like the title says. Giving a few days for feedback on this one too.
> Add achievements to Liberty

- data/campaigns/Heir_To_The_Throne/scenarios/20b_Underground_Channels.cfg
4eb7fccaa0 made this comment a ``po-override`` without given justification.
> HttT: Restore context information for Haralandum's name

- src/playsingle_controller.cpp
> Return early if there are no sides

- src/font/font_config.cpp
> Add a hack to workaround setting the fontconfig cachedir only for windows.

- src/scripting/game_lua_kernel.cpp
> Achievements - use lua_error instead of returning -2

- data/tools/wesnoth/wmltools3.py
> Improvements to wmltools3

- src/game_state.cpp
- src/game_state.hpp
- src/play_controller.cpp
- src/play_controller.hpp
- src/playmp_controller.cpp
- src/playsingle_controller.cpp
- src/playturn.cpp
- src/replay_controller.cpp
- src/saved_game.cpp
- src/server/wesnothd/game.cpp
- src/synced_context.cpp
- src/synced_context.hpp
- src/units/unit.cpp
- src/units/unit.hpp
Fixes (some only partial) for #https://github.com/wesnoth/wesnoth/issues/3925 https://github.com/wesnoth/wesnoth/issues/3742 https://github.com/wesnoth/wesnoth/issues/4438
> Misc fixes

- data/tools/unit_tree/helpers.py
- data/tools/unit_tree/html_output.py
- data/tools/unit_tree/wiki_output.py
- data/tools/wmlunits
This PR deals with several issues similar to the one reported in #7528. However, the specific reason behind #7528 should get clarified after someone pulls up the log files.
> wmlunits: Handle code paths for missing attributes

- data/tools/unit_tree/overview.py
> wmlunits: Specify error as class in html reports

- data/tools/wmlunits
> wmlunits: Fixup for fa76e77

- data/tools/wesnoth/campaignserver_client.py
Add a minimum version of protocol for security.
> Fix insecure SSL/TLS connexion used in campaignserver_client.py

- data/tools/TeamColorizer
- data/tools/addon_manager/html.py
- data/tools/unit_tree/helpers.py
- data/tools/unit_tree/team_colorizer.py
- data/tools/wmlunits
Reduces subprocess spamming in ``wmlunits``.
> Refactor TeamColorizer into a Python library

- changelog_entries/extent_remove_ability_efect_to_attribute_changelog.md
- data/schema/filters/abilities.cfg
- data/schema/filters/unit.cfg
- data/schema/game_config.cfg
- data/schema/units/modifications.cfg
- data/test/scenarios/wml_tests/ScenarioWML/EffectWML/test_remove_ability_by_filter.cfg
- data/test/scenarios/wml_tests/ScenarioWML/EventWML/events-test_filter_ability.cfg
- src/units/filter.cpp
- src/units/unit.cpp
- src/units/unit.hpp
- wml_test_schedule
This is the first commit of #7168, which I intend to merge while leaving the other 2 commits for further discussion in that PR.
See the comments starting at https://github.com/wesnoth/wesnoth/pull/7168#issuecomment-1537129642 for an explanation.
> CI run for first commit of 7168 (filter_ability)

- data/tools/unit_tree/html_output.py
- data/tools/wmlunits
Just some low-hanging fruit. This makes the code and output cleaner and faster.
> wmlunits: Refactor HTML postprocess step

- changelog.md
- src/gui/dialogs/title_screen.cpp
- src/gui/dialogs/title_screen.hpp
> gui/title_screen: Refresh Language button after changing languages

- src/gui/dialogs/unit_attack.cpp
- src/units/abilities.cpp
resolve https://github.com/wesnoth/wesnoth/issues/7612 issue
> chage source code in unit_attack.cppand abilities.cpp for pot update

- po/SConscript
- scons/gettext_tool.py
currently this fixes error with newest po4a but still po4a complains about po4a-gettextize/po4a-translate being deprecated. Could also go unified po4a approach but it seems less buildsystem-friendly.
> Refresh po4a workflow

- data/core/macros/multiplayer.cfg
- data/multiplayer/eras.cfg
> move multiplayer macros to proper folder

- doc/man/wesnoth.6
- src/commandline_options.cpp
- src/log_windows.cpp
- src/log_windows.hpp
- src/wesnoth.cpp
Fixes #7619
---
Also adds the `--log-to-file` man page entry since it was missing.
> Add --no-con to disable writing to CONOUT.

- data/tools/wmllint
> Update wmllint calls to parse_macroref

- src/wesnoth.cpp
I am unsure if this is an acceptable way to do this, I'd be glad to hear any suggestions if it's not.
> hopefully fixes #6883

- data/campaigns/Legend_of_Wesmere/_main.cfg
- data/campaigns/World_Conquest/lua/game_mechanics/unittypedata.lua
- data/multiplayer/scenarios/ANL_utils/ANL_leader_options.cfg
> LoW/ANL/WC update instances of `units/elves-wood/fighter` to account extra introduced DIR

- src/units/unit.cpp
error don't affect functionality, but it is for writing quality.
> Fix a writing in matches_ability_filter function

- changelog.md
- data/campaigns/Liberty/scenarios/04_Unlawful_Orders.cfg
Resolves #7748, introduced with #7518.
> Liberty S4: Resolve nameless enemies gaining names

- data/campaigns/Under_the_Burning_Suns/scenarios/03_Stirring_in_the_Night.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/08_Out_of_the_Frying_Pan.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/09_Blood_is_Thicker_Than_Water.cfg
- data/campaigns/Under_the_Burning_Suns/utils/storytxt.cfg
> UtBS prose updates

- data/tools/pywmlx/state/lua_states.py
- data/tools/pywmlx/state/machine.py
- data/tools/pywmlx/state/wml_states.py
This is a pure refactor that simplifies the code and makes it easier to implement new TBD directives and/or modify behavior of ``#po-override``.
Related: #7570
> Refactor collection of #po, #po-override comments

- changelog.md
Primarily fixes for 1.17.19 changelog, but caught a few old typos as well.
> doc: proofreading fixes for changelog.md

- changelog_entries/utbs_s3.md
- data/campaigns/Under_the_Burning_Suns/scenarios/03_Stirring_in_the_Night.cfg
Resolves #7774
I think this can/should be back-ported to 1.16 as well.
> UtBS S3: Resolve Garak's attacks only partially being converted to fire damage

- src/tests/test_lexical_cast.cpp
> Cleaned up last use of boost::mpl

- data/campaigns/Under_the_Burning_Suns/units/quenoth/Sun_Singer.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Sun_Sylph.cfg
- data/campaigns/Under_the_Burning_Suns/utils/abilities.cfg
As in title, still no description improvement tho so with that help would be nice.
> Fix song verse ability for UtBS

- data/gui/window/mp_create_game.cfg
- src/map_settings.cpp
- src/map_settings.hpp
And widen the corresponding 'soft' limits for the multiplayer scenario creation screen.
~~Normally I thoroughly test everything before a pull request, but am not currently set up to build from source, So I cannot test the small, surgical, engine level changes in this one.~~ Edit: now tested and working.
> Cut arbitrary hardcoded restrictions of scenario settings

- data/gui/window/editor_choose_addon.cfg
- src/editor/controller/editor_controller.cpp
- src/editor/controller/editor_controller.hpp
- src/editor/editor_main.cpp
- src/editor/editor_main.hpp
- src/editor/map/context_manager.cpp
- src/editor/map/context_manager.hpp
> Don't show the add-on selection dialog on editor start.

- data/campaigns/Winds_of_Fate/_main.cfg
Somehow I never updated the placeholder campaign description, so doing that now.
Any thoughts? Otherwise, this should be ready to commit.
> WoF: new campaign description

- data/core/units/monsters/Ant_Fire_Queen.cfg
- data/core/units/monsters/Ant_Queen.cfg
- data/core/units/monsters/Kraken.cfg
- data/core/units/monsters/Raven.cfg
- data/core/units/monsters/Raven_Harbinger.cfg
- data/core/units/monsters/Raven_Omen.cfg
- data/core/units/monsters/Roc.cfg
- data/core/units/monsters/Shadow_Jumping_Spider.cfg
- data/core/units/saurians/Oracle.cfg
- data/core/units/saurians/Soothsayer.cfg
- data/core/units/undead/Skele_Bone_Knight.cfg
- data/core/units/undead/Skeleton_Rider.cfg
Im not even writing changelog for this, all (or 80%) was added / changed during this patch anyway, 10% is pretty much bugfix and what remains are maybe ant queens unless they were added during this patch as well. 
If no objections mergin withing like soon(tm).
Fail CI I dare u.
> New units & stragglers balance

- data/core/units.cfg
- data/core/units/monsters/Ant_Egg.cfg
- data/core/units/monsters/Raven.cfg
- data/core/units/monsters/Raven_Harbinger.cfg
- data/core/units/monsters/Raven_Omen.cfg
This should make the fluff tied to the ravens less placeholder-y.  I'll see if there are any other strings I added that need a quick revision before the freeze, but if 1.17.22 can't wait any longer, this can be merged (assuming it doesn't fail CI for some reason).
EDIT: As much as I dislike the current name of the jumping spiders, I'm having trouble thinking of a clear improvement.
EDIT2:  This is probably all I'll get done, will merge in a couple hours
> 1.17 - Last-minute string cleanups

- data/campaigns/Under_the_Burning_Suns/utils/abilities.cfg
The sun units have several abilities, but it is basically one big ability.
The STR_VERSE macros won't be used, but I left them in for now.
> UtBS: ability names and descriptions

- data/campaigns/World_Conquest/lua/map/postgeneration/6A_Rural.lua
A random thing i noticed while searching for something else, pr because  not tested yet.
> WC: fix to in 6A_Rural mapgen

- src/editor/map/map_context.cpp
> Change editor event from start to prestart.

- src/editor/editor_main.cpp
- src/editor/map/context_manager.cpp
- src/filesystem.cpp
- src/filesystem.hpp
> Get the add-on ID from the file path if possible.

- src/server/common/dbconn.cpp
Fixes #7988
I have no idea why this helps anything at all, since my understanding has always been that inner joins vs a big where clause are essentially two different ways of accomplishing the same thing, but changing the two inner joins to a where clause improves query performance from 6.3 to 0.012 seconds (when running the query from the website VM). As best I can tell from the explain plans, the inner joins are somehow confusing the query optimizer to use the game_content_info table as the starting point of the query instead of the game_info table, but why it's doing that or why it has such a large impact remains a mystery.
------
Current query:
```
select 
game.GAME_NAME, 
game.START_TIME, 
GROUP_CONCAT(CONCAT(player.USER_NAME, ':', player.FACTION)) as PLAYERS, 
IFNULL(scenario.NAME, …
```
> Improve performance of the game history query by a lot.

- data/lua/wml/harm_unit.lua
> Avoid accessing data of potentially killed unit

- data/campaigns/Under_the_Burning_Suns/utils/dehydration-utils.cfg
all terrain sand should be deshydrating terrain.
> UtBS S02: Beach Sand is a dehydrating terrain

- data/multiplayer/factions/drakes-aoh.cfg
- data/multiplayer/factions/drakes-default.cfg
Reason: Saurian Seer and Soothsayer have 7mp
> Remove Saurian Seer and Soothsayer from the leaderpool

- data/campaigns/Winds_of_Fate/_main.cfg
Resolves #8008 
Any thoughts on the wording or formatting?
> WoF: list unique mechanics in campaign description

- src/gui/widgets/window.cpp
> Clip rerender requests to the window area.

- data/campaigns/Winds_of_Fate/scenarios/06_Landfall.cfg
A small balance patch based on feedback from @Hejnewar over [here.](https://github.com/wesnoth/wesnoth/pull/8031#issuecomment-1797917693)
> WoF S6: weaken player allies

- data/core/units/undead/Skele_Bone_Knight.cfg
- data/core/units/undead/Skeleton_Rider.cfg
Both Units can now move in deep water and use submerge
Closes #8138
> [Units] Skeleton Rider and Bone Knight can now traverse Deep Water

- data/campaigns/Under_the_Burning_Suns/units/quenoth/Youth.cfg
Fix https://github.com/wesnoth/wesnoth/issues/8149 issue
> fix leveling for Kaleh and Nym in Utbs

- data/campaigns/Eastern_Invasion/scenarios/04b_Ill_Humors.cfg
> EI S4: Safyam is supposed to be female

- src/gui/dialogs/outro.cpp
- src/gui/dialogs/outro.hpp
- src/gui/widgets/window.hpp
> Prevent wesnoth from crashing after campaign credits

- data/modifications/pick_advance/main.lua
> Update all units of type and side after selection with is_game_override

- data/campaigns/Eastern_Invasion/scenarios/12_Evacuation.cfg
> EI S12: Ran-Lar appears to be renamed Rakkha

- data/core/about.cfg
> Add missing names to about.cfg

- data/campaigns/Winds_of_Fate/story/Morogor_Dialect.txt
Address a few weird or problematic entries in the glossary. This also makes it use the term "glossary" instead of "dictionary", as that's what it really is.
> Update Morogor Dialect notes

- data/campaigns/Eastern_Invasion/scenarios/11_Captured.cfg
> EI S11: Correct a couple of [message]message= to [message]female_message=

- data/core/hotkeys.cfg
- src/game_classification.cpp
Add 'k' hotkey in data/core to be available in main menu ('M').
(fixes #8209)
> Add 'k' hotkey to core management window from main screen

- .github/ISSUE_TEMPLATE/bug_report.yml
> [`bug_report.yml`]: change comma to full-stop

- src/game_board.cpp
- src/game_board.hpp
- src/mouse_events.cpp
- src/units/map.cpp
- src/whiteboard/move.cpp
> Re-sets the standing animation before and after the temporary_unit_mover moves the unit

- src/scripting/game_lua_kernel.cpp
> add an optional delay argument to scroll.

- src/display.cpp
- src/image_modifications.cpp
- src/image_modifications.hpp
- src/reports.cpp
- src/sdl/utils.cpp
- src/sdl/utils.hpp
> Re-add cropping of transparent padding on status icons.

- src/game_initialization/create_engine.cpp
- src/game_initialization/create_engine.hpp
- src/game_initialization/depcheck.cpp
- src/game_initialization/depcheck.hpp
- src/gui/dialogs/campaign_selection.cpp
- src/gui/dialogs/campaign_selection.hpp
- src/gui/dialogs/multiplayer/mp_create_game.cpp
- src/gui/dialogs/multiplayer/mp_create_game.hpp
Error string left as untranslatable for now due to string freeze.
Fixes #6780
> Fix duplicate mod ids breaking mod selection

- data/campaigns/Eastern_Invasion/scenarios/06a_Undead_Crossing.cfg
@tamanegi-jp thanks for the bug report. This PR should fix the issue.
> EI S06: fix enemy spawning event not triggering when turns end (#8376)

- src/modules/lua_README.md
- src/wesnoth_lua_config.md
A minor documentation improvement I should have thought to include in #8234.
> Add CI update to Lua update documentation

- data/core/about.cfg
Under "Packagers" and "Miscellaneous Contributors".
> Add myself to about.cfg

- data/campaigns/Eastern_Invasion/scenarios/01_Eastern_Invasion.cfg
- data/campaigns/Eastern_Invasion/scenarios/02_The_Escape_Tunnel.cfg
- data/campaigns/Eastern_Invasion/scenarios/03_An_Unexpected_Appearance.cfg
- data/campaigns/Eastern_Invasion/scenarios/04a_An_Elven_Interlude.cfg
- data/campaigns/Eastern_Invasion/scenarios/04b_Ill_Humors.cfg
- data/campaigns/Eastern_Invasion/scenarios/04c_Mal-Ravanals_Capital.cfg
No changes to translatable strings, just to the hints.
@tamanegi-jp and @hermestrismi, is this the right sort and amount of comments? I'm intending to do another pass over the same scenario files and maybe add a bit more, hence the "draft" status of the PR.
> EI S01-S04x: Add more po hints

- src/about.cpp
- src/image_modifications.cpp
- src/scripting/lua_kernel_base.cpp
- src/serialization/string_utils.cpp
- src/serialization/string_utils.hpp
- src/utils/from_chars.hpp
No functionality changes, just cleanup. Would like some thoughts on the from_chars wrapper.
> IPF string view cleanup

- data/campaigns/Eastern_Invasion/scenarios/05_Northern_Outpost.cfg
- data/campaigns/Eastern_Invasion/scenarios/06a_Undead_Crossing.cfg
- data/campaigns/Eastern_Invasion/scenarios/06b_Soradoc.cfg
- data/campaigns/Eastern_Invasion/scenarios/07b_Ogre_Crossing.cfg
- data/campaigns/Eastern_Invasion/scenarios/08_Xenophobia.cfg
- data/campaigns/Eastern_Invasion/scenarios/09_Castle_in_the_Ice.cfg
- data/campaigns/Eastern_Invasion/scenarios/10_Dark_Sanctuary.cfg
Please can I have a review, @Dalas121?
@nemaara this puts into comments the dates from the timeline that are mentioned in #8387, along with suggesting that that text will change to "Early in the reign of ..." in 1.19.
> EI S05-S10: Add more PO hints

- src/image_modifications.cpp
- src/utils/from_chars.hpp
> IPF: convert uses of lexical_cast_default to from_chars

- data/ai/lua/ai_helper.lua
> Revert renaming of ai_helper.checked_move_core

- data/campaigns/Eastern_Invasion/scenarios/01_Eastern_Invasion.cfg
- data/campaigns/Eastern_Invasion/scenarios/13_Spoils_of_War.cfg
She's meant to be female, but in S01 the gender defaulted to male, while in S13 it was set to random.
Fixes #8389.
> EI S01, S13: Fix Gaennell's gender

- data/campaigns/Under_the_Burning_Suns/scenarios/01_The_Morning_After.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/05_A_Subterranean_Struggle.cfg
Fixes #8201, #8198, #8190, #8188 (very not great fix but works), #8184 and a bit more
> UtBS fixes

- data/campaigns/Under_the_Burning_Suns/units/quenoth/Champion.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Fighter.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Flanker.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Ranger.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Warrior.cfg
- data/campaigns/Under_the_Burning_Suns/units/quenoth/Youth.cfg
> UtBS Units and Heroes: Fighter line adjustments and Taunting Strike xp farm fix

- data/test/scenarios/wml_tests/UnitsWML/increase_experience_by_percentage.cfg
- src/units/unit.cpp
- wml_test_schedule
Resolve https://github.com/wesnoth/wesnoth/issues/8374 issue
> Fix increase by percentage returns 1 if experience or max_experience are equal to zero

- data/ai/lua/ai_helper.lua
- data/campaigns/Secrets_of_the_Ancients/utils/zombie_recruit_dialog.lua
- data/lua/core/map.lua
- data/lua/location_set.lua
- data/lua/wml-tags.lua
I split out the parts of #7359 that seemed backportable. Obviously, this should be merged into master as well.
> Lua Warning Cleanup (1.18)

- data/tools/GUI.pyw
> updated copyright in WML tool GUI app

- data/campaigns/Winds_of_Fate/scenarios/01_The_Hunt.cfg
- data/campaigns/Winds_of_Fate/scenarios/05_Threshold.cfg
- data/campaigns/Winds_of_Fate/scenarios/08_Overlook.cfg
- data/campaigns/Winds_of_Fate/scenarios/09_Ancestor.cfg
Cherry picks two WoF fixes from #8447 on master and back ports them to the 1.18 stable branch.
> [1.18] WoF: two fixes for stable

- data/campaigns/Winds_of_Fate/scenarios/11_Crosswind.cfg
Backports to stable 1.18 branch the last remaining commit from #8447 which was not already backported by #8487
> [1.18] WoF: another fix for stable

- data/core/about_i18n.cfg
Based on https://wiki.wesnoth.org/SlovakTranslation
> Adding myself to credits

- data/core/macros/abilities.cfg
Fix https://github.com/wesnoth/wesnoth/issues/8512 issue in 1.18
> [1.18]Fix Ambush Ability Does not Work in Bluff/Glutch Forest Terrain

- data/core/macros/abilities.cfg
Resolve https://github.com/wesnoth/wesnoth/issues/8512 issue
> Fix Ambush Ability Does not Work in Bluff/Glutch Forest Terrain

- src/utils/optimer.hpp
> Attempt to disambiguate operator<< for optimer

- changelog_entries/sota_crelanu.md
Just a CI run (arguably unnecessary, but I want to keep the habit of PRs for everything)
Changelog for d106238410cf1ffc7f36352ce7b5d24fcfa19b59, the changelog is already included in 1.18's cherry-pick.
> Changelog for SotA S16: Keep Crelanu within his ring

- projectfiles/Xcode/The Battle for Wesnoth.xcodeproj/project.pbxproj
Forward port of #8544 which was already merged into 1.18.
> Add -Wno-shorten-64-to-32 to compiler flags in Xcode

- data/campaigns/Winds_of_Fate/scenarios/01_The_Hunt.cfg
- data/campaigns/Winds_of_Fate/scenarios/03_The_Contention.cfg
- data/campaigns/Winds_of_Fate/scenarios/04_Journey.cfg
- data/campaigns/Winds_of_Fate/scenarios/05_Threshold.cfg
- data/campaigns/Winds_of_Fate/scenarios/06_Landfall.cfg
- data/campaigns/Winds_of_Fate/scenarios/07_Harvest.cfg
- data/campaigns/Winds_of_Fate/scenarios/08_Overlook.cfg
- data/campaigns/Winds_of_Fate/scenarios/11_Crosswind.cfg
- data/campaigns/Winds_of_Fate/scenarios/12_Epilogue.cfg
This is based on feedback in #8507 and a review of WoF's scenario music playlists as a result.
I am going to start a full play through with these adjustments to get a better sense for them, so there might be some further adjustments soon. But posting this now in case @irydacea or anyone else has further feedback to give before the stable release.
> WoF: adjust music

- data/campaigns/Winds_of_Fate/scenarios/06_Landfall.cfg
- data/campaigns/Winds_of_Fate/scenarios/07_Harvest.cfg
- data/campaigns/Winds_of_Fate/scenarios/09_Ancestor.cfg
- data/campaigns/Winds_of_Fate/scenarios/10_Fire_Meets_Steel.cfg
- data/campaigns/Winds_of_Fate/scenarios/11_Crosswind.cfg
Some tweaks for the later scenarios based on a final play test of all scenarios before the stable release.
These should also get backported into 1.18.
> WoF: balance tweaks

- data/campaigns/Winds_of_Fate/scenarios/01_The_Hunt.cfg
- data/campaigns/Winds_of_Fate/scenarios/03_The_Contention.cfg
- data/campaigns/Winds_of_Fate/scenarios/04_Journey.cfg
- data/campaigns/Winds_of_Fate/scenarios/05_Threshold.cfg
- data/campaigns/Winds_of_Fate/scenarios/06_Landfall.cfg
- data/campaigns/Winds_of_Fate/scenarios/07_Harvest.cfg
- data/campaigns/Winds_of_Fate/scenarios/08_Overlook.cfg
- data/campaigns/Winds_of_Fate/scenarios/09_Ancestor.cfg
- data/campaigns/Winds_of_Fate/scenarios/10_Fire_Meets_Steel.cfg
- data/campaigns/Winds_of_Fate/scenarios/11_Crosswind.cfg
- data/campaigns/Winds_of_Fate/scenarios/12_Epilogue.cfg
> [1.18] WoF: some fixes for stable

- changelog_entries/recruit_recall_filtering.md
- src/gui/dialogs/unit_recall.cpp
- src/gui/dialogs/unit_recruit.cpp
> gui/unit_recall: Add alignment and race hints for filtering (1.18)

- po/wesnoth-sof/de.po
> CI run for a po update

- src/preferences/game.cpp
Change default settings for the timer to 240/240/360/0.
Will forward port latter.
> Improve default settings for the timer

- src/game_config.cpp
> Fix "implicit conversion turns floating-point number into integer" warnings (development branch forward-port version)

- po/wesnoth-sof/de.po
> CI run for po update

- doc/man/wesnoth.6
- src/commandline_options.cpp
- src/wesnoth.cpp
> Add an environment variable to disable logging to file

- data/campaigns/Winds_of_Fate/scenarios/11_Crosswind.cfg
> WoF S11: tweak enemy gold

- .github/ISSUE_TEMPLATE/bug_report.yml
IMO build info is rather confusing for most people and those that understand it are likely to provide the info anyway.
Has downloaded from ever been helpful?
> Streamline bug report template

- data/campaigns/Eastern_Invasion/scenarios/10_Dark_Sanctuary.cfg
> EI S10: change "ghasts in cages" to "ghouls in cages"

- src/gui/dialogs/campaign_selection.cpp
Remove leftover print statement and `#include<iostream>` from #8451 which is only used for testing.
> remove leftover print statement

- data/core/terrain.cfg
> All "Sands" to "Sand"

- data/core/about_i18n.cfg
- po/wesnoth-tools/de.po
- po/wesnoth-units/de.po
- po/wesnoth-wof/de.po
s1m0n was in the credits for 1.16, but that was missed when his contributions were copied to master. Fix that, along with adding his latest updates.
The fuzzy flag in -wof probably got readded by mistake when rebasing.
> CI run for a German translation update

- data/core/about_i18n.cfg
- po/wesnoth-tools/de.po
- po/wesnoth-units/de.po
- po/wesnoth-wof/de.po
s1m0n was in the credits for 1.16, but that was missed when his contributions were copied to master. Fix that, along with adding his latest updates.
The fuzzy flag in -wof probably got readded by mistake when rebasing.
> CI run for German translation update

- data/test/macros/wml_unit_test_macros.cfg
@newfrenchy83 please would you review whether this PR is a good change?
> Clearer documentation for the ATTACK_AND_VALIDATE macro

- po/CMakeLists.txt
- po/SConscript
Compare to https://github.com/wesnoth/website/blob/17f8223c38bc40380a89299fb5013a476164d0db/gettext.wesnoth.org/includes/config.php#L45-L54
> Fix mismatch between what gettext.w.o and wesnoth consider core textdomains

- data/campaigns/Eastern_Invasion/scenarios/14_The_Drowned_Plains.cfg
- data/campaigns/Eastern_Invasion/scenarios/16_Eleventh_Hour.cfg
> EI: preserve XP when Dacyn receives scripted advancements

- CMakeLists.txt
- INSTALL.md
- SConstruct
- changelog_entries/SDL.md
- src/display.cpp
- src/display.hpp
- src/draw.cpp
- src/draw.hpp
- src/units/frame.cpp
Original code from mesilliac in #6826. Made a separate PR for this since the relevant code moved to an entirely separate file and trying to "properly" fix the merge conflicts resulting from that isn't worth the time.
> Hardware unit submerge effect using SDL_RenderGeometry.

- data/campaigns/Eastern_Invasion/utils/final_battle/final_battle.cfg
> EI: fix "mak-dak'an" typo

- src/gui/dialogs/game_version_dialog.cpp
- src/log.cpp
> Check log file actually exists before enabling Log File button

- data/campaigns/Eastern_Invasion/scenarios/12_Evacuation.cfg
> EI S12: prevent ogres from saying the final goodbye

- .github/workflows/ci-main.yml
> Restore Windows CI

- src/gui/widgets/listbox.cpp
> Avoid invalid pointer access on recall

- data/core/terrain.cfg
> Add shallow water to oasis like ford terrain

- data/campaigns/Under_the_Burning_Suns/units/quenoth/Youth.cfg
- src/formula/callable_objects.cpp
- src/units/unit.cpp
- src/units/unit.hpp
Can resolve https://github.com/wesnoth/wesnoth/issues/8179 issue
while waiting for the release of the use of the number of advancement or their identity to be decided, I added both in the formulas
> Add modification count and ids in formula

- data/campaigns/Heir_To_The_Throne/scenarios/16_Hasty_Alliance.cfg
> S16: fix li'sar missing her unrenamable=yes

- data/core/units/elves/Avenger.cfg
- data/core/units/elves/Enchantress.cfg
- data/core/units/elves/Sharpshooter.cfg
- data/core/units/elves/Shyde.cfg
- data/core/units/elves/Sylph.cfg
Seeing the very positive reaction from the community to my suggestions in issue #8741 I decided to move forward with this issue and open a PR with my changes implemented.
> Nerf Elvish Shyde/Enchantress/Sylph/Sharpshooter/Avenger in 1.19

- src/editor/map/map_context.cpp
> allow loading .mask files

- data/campaigns/Eastern_Invasion/scenarios/07b_Ogre_Crossing.cfg
- data/campaigns/Eastern_Invasion/utils/items.cfg
Forward-port of #8802.
(cherry picked from commit 8c83da78e28c54a32f0fc526f5ab38198eb4706b)
> EI: Add po hints about the plague staff

- data/campaigns/Eastern_Invasion/units/Ant_Queen.cfg
- data/campaigns/Eastern_Invasion/units/Egg_Sac.cfg
Resolving issue #8769 . @Dalas121
> EI - change undead variants from 'spider' to 'ant'

- data/campaigns/Eastern_Invasion/scenarios/10_Dark_Sanctuary.cfg
> EI: S10 fix owaec being able to enter the sanctuary

- doc/man/wesnoth.6
- doc/man/wesnothd.6
Closes #8616.
Partially addresses #8622.
> Update wesnothd man page

- copyrights.csv
update copyrights.csv for recent Wyvern graphics update
> Copyrights for Wyvern images

- po/wesnoth-ei/de.po
> CI run for updating the German translation on 1.18

- po/wesnoth-ei/de.po
> CI run for updating the German translation on master

- data/core/units/monsters/Horse_White.cfg
As pointed out by Celtic Minstrel and hejnewar
> Units: fix White Horse HP and XP stats

- data/lua/wml-tags.lua
> Reject [terrain] with unknown terrain type

- data/campaigns/Liberty/scenarios/04_Unlawful_Orders.cfg
> Liberty - get The Nameless General achievement to work on dawn

- data/campaigns/Eastern_Invasion/scenarios/16_Eleventh_Hour.cfg
- data/campaigns/Eastern_Invasion/units/Human_Townsfolk.cfg
> EI: remove random traits from S16 townsfolk

- data/campaigns/Winds_of_Fate/utils/macros.cfg
> [backport] WoF: fix Lua type error with cast to number

- data/campaigns/Winds_of_Fate/scenarios/11_Crosswind.cfg
> [backport] WoF S11: fix easy win AI exploit

- changelog_entries/8166_unit_type_editor.md
- changelog_entries/8390_new_widgets.md
- changelog_entries/8451_completion_filter.md
- changelog_entries/8539_aethermaw_prose_change.md
- changelog_entries/8737_enchantress_sylph_changes.md
- changelog_entries/8803_about_dialog.md
Adds changelog entry files in the changelog_entries folder for PRs #8166, #8390, #8451, #8539, #8737 and #8803.
> add changelog entries

- data/campaigns/Winds_of_Fate/scenarios/08_Overlook.cfg
> WoF S8: clarify objective notes

- changelog.md
Just adding entries for commits that should have had a changelog_entries file, not merging the existing changelog_entries files.
> [1.18] Update the changelog

- changelog_entries/8837_mudcrawler_swamp.md
- data/core/units/monsters/Giant_Mudcrawler.cfg
- data/core/units/monsters/Mudcrawler.cfg
> Mudcrawlers better in swamp, worse in buildings

- src/game_initialization/connect_engine.cpp
This was deprecated back in 1.13.1
> remove deprecated controller=<number>

- data/campaigns/Eastern_Invasion/scenarios/06b_Soradoc.cfg
@Dalas121 when a PR is reporting errors, please fix them before merging
> Fix the whitespace error on master

- data/campaigns/Eastern_Invasion/scenarios/06b_Soradoc.cfg
@Dalas121 when a PR is reporting errors, please fix them before merging
> Fix the whitespace error on 1.18

- data/campaigns/Eastern_Invasion/scenarios/10_Dark_Sanctuary.cfg
https://www.reddit.com/r/wesnoth/comments/1d6a3e7/eastern_invasion_is_much_better_but_still_bad/
EI's S10 is overly hard on Normal, and especially on Easy (which is intended to be a very accessible difficulty).  This PR increases the available gold and adds several villages, which aid in both defense and upkeep.  This PR also drastically reduces the number of orcs on lower difficulties.
> EI S10: reduce difficulty on Easy/Normal

- data/campaigns/Eastern_Invasion/scenarios/10_Dark_Sanctuary.cfg
Owaec has a crown but little other indicator that he's a leader, and this scenario requires him to be used to recruit.
> EI S10: add message about Owaec being able to recruit

- data/lua/wml-tags.lua
> Use same default id in [remove_unit_overlay] as [unit_overlay]

- projectfiles/Xcode/The Battle for Wesnoth.xcodeproj/project.pbxproj
Header files added/removd in commits: c4c292fa3bc0, 43f5644e36e1, 32799739608b, c5b1fa9dfdbb, d954d307bce6, 01f28b12aea5, 63d14217c9c1, 6d77fdc48c6f, 0e85fac29c15, 0b646dec8a13 and 6c5a8e923d52
> Update added/removed header files in Xcode project

- src/color.cpp
- src/game_config.cpp
Just to double check, since we don't use hex value with alpha, `uint32_t` should be big enough to support any hex string-to-num conversion, right?
> Minor color_t cleanup

- data/test/scenarios/wml_tests/ScenarioWML/EventWML/events-test_filterable1.cfg
- src/actions/attack.cpp
If there are no strong objections about design I will add some tests too.
> Trigger unit_hits, unit_misses events, re #7782

- data/tools/wesnoth/wmliterator3.py
- data/tools/wesnoth/wmltools3.py
> [1.18] wmltools3 and Python 3.12

- data/gui/widget/button_success.cfg
> use correct font for checkmark character

- src/editor/controller/editor_controller.cpp
- src/editor/map/context_manager.cpp
- src/units/unit.cpp
- src/units/unit.hpp
Contains a couple of backported fixes from #8903, and some new behavioral fixes inside the Editor. Changes detailed in the commit messages. New changes will need to be forward-ported.
New commits in this PR (forward-port needed):
4b1752be06b396abf3201b9fc4e14beccd2127ab
> some editor bugfixes from #8903

- src/color_range.cpp
For this specific codepath on game launch, it reduces its execution time from ~18ms to ~1ms.
> Optimize color_range reference palette generation

- data/campaigns/The_Hammer_of_Thursagan/scenarios/01_At_the_East_Gate.cfg
- data/campaigns/The_Hammer_of_Thursagan/scenarios/05_Fear.cfg
Resolves #9008.
I think this is a small enough change to be back-ported.
> SoF: Align masked dwarf portrait to the right

- README.md
The app has been removed from the Play Store.
> Updated link to android version in README

- data/campaigns/Eastern_Invasion/scenarios/10_Dark_Sanctuary.cfg
Resolves #9066.
@Dalas121 Might as well ask you to review this at the same time as #9081.
> EI S10: Clarify Dacyn's wording

- src/ai/default/recruitment.cpp
- src/ai/formula/function_table.cpp
- src/generators/default_map_generator_job.cpp
- src/gui/widgets/grid.cpp
- src/minimap.cpp
- src/pathfind/pathfind.cpp
- src/terrain/builder.cpp
- src/terrain/translation.hpp
Makes the code do what is commonly expected and avoids needless overflow since otherwise the multiplication is done as int.
> Perform multiplication in result type for types larger than int

- src/filesystem.cpp
Behavior should be generally as in 1.18 except for interpreting relative paths normally instead of under $HOME. The latter was warned about for quite a few versions now.
> Simplify user data dir determination

- data/campaigns/World_Conquest/lua/game_mechanics/invest/invest_show_dialog.lua
we no longer show the deserter option fo no deserter are avilable
> wc: fix #9012 errro when deserter list is empty

- data/campaigns/World_Conquest/TODO.txt
Removes completed TODOs and ones deemed irrelevant.
> WC: update todo.txt file

- src/filesystem.cpp
- src/preferences/preferences.hpp
- src/server/wesnothd/server.cpp
- src/tests/main.cpp
As discussed previously in https://github.com/wesnoth/wesnoth/pull/9016#discussion_r1650036348
> Move assert into filesystem::get_user_data_path()

- src/commandline_options.cpp
- src/commandline_options.hpp
- src/filesystem.hpp
- src/filesystem_common.cpp
- src/wesnoth.cpp
Log files goes in the userdata folder so they therefore need the userdata to be initialized before that.
Fixes #9111
---
This does at least fix #9111, though obviously more is needed before it can be merged.
> Move command line processing before logger initialization

- data/lua/core/map.lua
- src/scripting/lua_formula_bridge.cpp
- src/scripting/lua_formula_bridge.hpp
- src/scripting/lua_terrainfilter.cpp
- src/scripting/lua_terrainfilter.hpp
- utils/emmylua/wesnoth/map.lua
I split this from #7359 so that @gfgtdf can easily review and merge it. It looks like several places are just doing entirely the wrong thing. I haven't verified that I caught _every_ place with this issue, but it's likely that I did, as I think they all would've raised the same warning in my Lua linter.
> [Lua] Clean up inconsistencies in mapgen filter API, and improve documentation

- src/actions/advancement.cpp
> fix WRN_NG level

- src/color_range.cpp
- src/display.cpp
- src/display_context.cpp
- src/display_context.hpp
- src/formula/variant_value.cpp
- src/formula/variant_value.hpp
- src/gui/dialogs/multiplayer/mp_connect.cpp
- src/gui/dialogs/multiplayer/mp_connect.hpp
- src/scripting/lua_unit.cpp
- src/serialization/parser.cpp
- src/serialization/schema/tag.cpp
- src/serialization/schema/tag.hpp
- src/terrain/builder.cpp
- src/terrain/builder.hpp
- src/tests/test_serialization.cpp
- src/units/unit.cpp
Various changes from #9109 that don't need C++20.
> Cleanup backported from cpp20 branch

- misc/fortunes/wesnoth
I update an old link now available in https. I’m not sure what this file is for, but I doubt this should cause any issues.
> Update link to https in fortunes

- data/campaigns/The_Hammer_of_Thursagan/scenarios/01_At_the_East_Gate.cfg
- data/campaigns/The_Hammer_of_Thursagan/scenarios/02_Reclaiming_the_Past.cfg
- data/campaigns/The_Hammer_of_Thursagan/scenarios/03_Strange_Allies.cfg
- data/campaigns/The_Hammer_of_Thursagan/scenarios/04_High_Pass.cfg
- data/campaigns/The_Hammer_of_Thursagan/scenarios/05_Fear.cfg
- data/campaigns/The_Hammer_of_Thursagan/scenarios/06_Forbidden_Forest.cfg
- data/campaigns/The_Hammer_of_Thursagan/scenarios/07_The_Siege_of_Kal_Kartha.cfg
- data/campaigns/The_Hammer_of_Thursagan/scenarios/08_The_Court_of_Karrag.cfg
- data/campaigns/The_Hammer_of_Thursagan/scenarios/09_The_Underlevels.cfg
- data/campaigns/The_Hammer_of_Thursagan/scenarios/10_Epilogue.cfg
- data/campaigns/The_Hammer_of_Thursagan/utils/characters.cfg
- data/campaigns/The_Hammer_of_Thursagan/utils/macros.cfg
Resolves [1.15 THoT Movrur should be created if he doesn't exist #5520 ](https://github.com/wesnoth/wesnoth/issues/5520) as well as adds few small fixes.
> THoT: Create heroes if they don't exist

- src/SConscript
> Call Export appropriately instead of using locals()

- po/CMakeLists.txt
- po/SConscript
Use a standard sed invocation and avoid rewriting the file.
> Simplify pot generation

- src/arrow.cpp
- src/arrow.hpp
- src/display.cpp
- src/display.hpp
- src/drawing_layer.hpp
- src/editor/editor_display.cpp
- src/game_display.cpp
- src/units/animation.cpp
- src/units/drawer.cpp
- src/units/frame.cpp
- src/units/frame.hpp
- src/whiteboard/attack.cpp
- src/whiteboard/manager.cpp
- src/whiteboard/move.cpp
- src/whiteboard/recall.cpp
- src/whiteboard/recruit.cpp
- src/whiteboard/suppose_dead.cpp
> Split drawing_layer into its own file, make scoped enum

- src/server/common/simple_wml.cpp
> Properly implement DO_NOT_MODIFY_CACHE

- data/lua/wml/kill.lua
- data/test/scenarios/wml_tests/ScenarioWML/EventWML/ActionWML/DirectActionsWML/kill_fires_events.cfg
Solves https://forums.wesnoth.org/viewtopic.php?t=58511
>  Set unit hitpoints to 0 during [kill]

- data/schema/units/abilities.cfg
- data/schema/units/specials.cfg
- src/units/unit.hpp
fix bug show in https://github.com/wesnoth/wesnoth/pull/9192
> Add disable ability

- src/preferences/preferences.cpp
> handle preferences case change

- data/schema/units/abilities.cfg
- data/schema/units/specials.cfg
- src/actions/attack.cpp
fix https://github.com/wesnoth/wesnoth/pull/9192 don't work with ability
> fix incomplete add [disable] abilityto abilities used like weapon special

- data/campaigns/Heir_To_The_Throne/scenarios/20b_Underground_Channels.cfg
The change to Alzheimer’s Disease was suggested by CelticMinstrel some time ago in #7545
> HttT S20b: Remove reference to Asperger Syndrome in po comment

- data/themes/default.cfg
closes #7636
re #6021
re #5575
> add tooltip to [unit_vision]

- data/schema/core/actionwml.cfg
- data/schema/core/addons.cfg
- data/schema/core/conditionalwml.cfg
Fix schema tags where "name" is a comma separated list which is not actually supported.
> Update and correct game config schema

- utils/CI/fix_whitespace.sh
Also process some more extensions that current source files use.
> Avoid rewriting the same file multiple times

- data/core/encyclopedia/geography.cfg
> Encyclopedia clean up following #9188

- src/filesystem.cpp
- src/filesystem.hpp
- src/tests/test_filesystem.cpp
> Correct confusing handling of ./ paths

- .github/workflows/image_metadata.yml
Correcting some mistakes in [78a4c5c](https://github.com/wesnoth/wesnoth/commit/78a4c5c494ee2cd50f97347f52776d0a3c741c61)
> Corrections to image metadata check CI

- .github/workflows/image_metadata.yml
- src/scripting/push_check.hpp
@gfgtdf wrote this for me
Adds the ability to set a variable to nil in lua to indicate "unused" instead of just, for example, an int.  Or at least, that's what I'm using it for.
Example (tested):
```
dialog.no_max.on_button_click = function() dialog.gold_sp.max_value=nil end
dialog.yes_max.on_button_click = function() dialog.gold_sp.max_value=80 end
```
```
WIDGET_SETTER("max_value", utils::optional<int>, gui2::spinner)
{
if(value) {
w.set_maximum_value(*value);
} else {
w.reset_maximum_value();  // disable use of maximum_value completely
}
}
```
see #9080
> add optional data type support

- data/campaigns/Son_Of_The_Black_Eye/scenarios/03_Toward_Mountains_of_Haag.cfg
- they wont attack from poor defense anymore
- will only attack from hills where they have better defense
- makes them less suicidal (so players wont lose when Gruu gets whacked due to stupid AI decisions)
Part of the SotBE revision but added here earlier than the rest.
> [SOTBE] S3: make allied AI smarter

- data/campaigns/Son_Of_The_Black_Eye/scenarios/05_To_the_Harbor_of_Tirigaz.cfg
- give side 1 starting villages near the orc base
- move Kapou'e to his keep at start
> SOTBE S5: some UX improvements

- data/core/help.cfg
Resolves: [https://github.com/wesnoth/wesnoth/issues/8719](https://github.com/wesnoth/wesnoth/issues/8719)
Added a short explanation of vision to the in-game help. As the text isn't certain to be translated at the moment no .po/.pot files were generated.
> Added an explanation of vision to the in-game help

- src/gui/dialogs/editor/edit_unit.cpp
> reduce the number of translatable strings in the unit type editor

- src/color_range.cpp
- src/tests/test_sdl.cpp
- src/utils/span.hpp
> Add utils::span wrapper

- data/core/editor/help.cfg
Reflects the change that it is now possible to remove items.
> [1.18] Update the help page entry for the Item tool

- src/ai/configuration.cpp
- src/ai/formula/ai.cpp
- src/ai/formula/candidates.cpp
- src/config.cpp
- src/config.hpp
- src/game_config.cpp
- src/gui/dialogs/multiplayer/mp_options_helper.cpp
- src/language.cpp
- src/menu_events.cpp
- src/movetype.cpp
- src/preferences/preferences.cpp
- src/scripting/lua_common.cpp
- src/serialization/parser.cpp
- src/server/campaignd/addon_utils.cpp
- src/statistics_record.cpp
- src/units/formula_manager.cpp
- src/units/types.cpp
- src/units/unit.cpp
- src/variable.cpp
> Minor config cleanup

- src/serialization/parser.cpp
- src/serialization/parser.hpp
- src/serialization/preprocessor.cpp
- src/serialization/tokenizer.cpp
- src/serialization/tokenizer.hpp
also clean it up a bit/make usage of things consistent
> add code documentation for the tokenizer

- src/actions/undo_move_action.cpp
- src/addon/client.cpp
- src/ai/configuration.cpp
- src/config.cpp
- src/config_cache.cpp
- src/editor/map/map_context.cpp
- src/formula/callable_objects.cpp
- src/game_config_manager.cpp
- src/game_events/handlers.cpp
- src/game_events/manager.cpp
- src/generators/cave_map_generator.cpp
- src/gui/core/canvas.cpp
- src/gui/dialogs/gamestate_inspector.cpp
- src/gui/dialogs/multiplayer/mp_options_helper.cpp
- src/play_controller.cpp
- src/preferences/preferences.cpp
- src/replay.cpp
- src/scripting/game_lua_kernel.cpp
- src/scripting/lua_common.cpp
- src/scripting/lua_wml.cpp
- src/serialization/parser.cpp
- src/serialization/schema_validator.cpp
- src/theme.cpp
- src/units/abilities.cpp
- src/units/attack_type.cpp
- src/units/filter.cpp
- src/units/types.cpp
- src/units/unit.cpp
- src/variable.cpp
- src/wesnoth.cpp
> Config: use structured bindings with all_children_range

- src/filesystem_common.cpp
- src/game_initialization/create_engine.cpp
- src/menu_events.cpp
fixes issue brought up on the forums: https://forums.wesnoth.org/viewtopic.php?t=58725
> use the correct editor dir location

- src/units/abilities.cpp
- src/units/ability_tags.hpp
- src/utils/config_filters.cpp
resolve https://github.com/wesnoth/wesnoth/issues/7992 issue
> filter attribute integrates the tag_name check to verify that the attribute sought can be used there

- src/gui/dialogs/addon/manager.cpp
> fix problematic find_widget usage and slightly rewrite the logic (#9388)

- data/campaigns/The_Hammer_of_Thursagan/scenarios/06_Forbidden_Forest.cfg
> Fix a comment typo in THoT S6

- src/game_events/action_wml.cpp
Better error message for ActionWML [unit] for unit type errors. resolves #9382
> Action wml unit better error

- src/gui/widgets/rich_label.cpp
- src/gui/widgets/rich_label.hpp
Couple cleanup/optimization thinks I saw looking through the code.
> GUI2/Rich Label: minor cleanup

- src/gui/widgets/rich_label.cpp
- src/scripting/lua_widget_methods.cpp
- utils/emmylua/gui.lua
Tested on listbox, multipage and tree_view/tv_node.
Please see comments starting at line 504 of lua_widget_methods.  I fixed a spelling issue, but that whole comment just looks wrong to me.
Looking at emmylua/gui.lua and the wiki for remove_items_at(), I think both might be wrong, but I'm not confident enough in that to correct them.
> GUI2 LuaAPI: add clear_items()

- data/lua/wml-tags.lua
- data/lua/wml-utils.lua
Better error messages for allow_recruit ActionWML. Resolves #9383.
> Better action wml allow_recruit error

- changelog_entries/remove_experiemental.md
- data/campaigns/Eastern_Invasion/scenarios/12_Evacuation.cfg
- data/schema/filters/unit.cfg
- data/schema/units/modifications.cfg
- data/schema/units/specials.cfg
- data/test/scenarios/wml_tests/ScenarioWML/EffectWML/test_remove_ability_by_filter.cfg
- data/test/scenarios/wml_tests/ScenarioWML/EventWML/events-test_filter_ability.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/test_overwrite_specials_filter.cfg
- src/units/abilities.cpp
- src/units/filter.cpp
- src/units/unit.cpp
now what 1.18 separate of master branch it istime of aiming for that.
> remove 'experimental_' of filter_ability/specials tags

- src/gui/widgets/multi_page.cpp
> multi_page::remove_page - consider index when limiting pages

- vcpkg.json
Let's see if this fixes the recent glib build issues...
> Bump vcpkg baseline

- data/core/macros/deprecated-utils.cfg
- data/core/macros/weapon_specials.cfg
- data/core/units/nagas/Guard.cfg
- data/core/units/nagas/Guard_High.cfg
- data/core/units/nagas/Guard_Shield.cfg
- data/core/units/nagas/Sicarius.cfg
This PR based on issue https://github.com/wesnoth/wesnoth/issues/8992 
All stats already discussed with @Dalas121
> Improve Naga Guard line

- src/animated.cpp
- src/animated.hpp
- src/animated.tpp
- src/display.cpp
- src/halo.cpp
- src/terrain/builder.cpp
- src/terrain/builder.hpp
- src/units/animation.cpp
- src/units/animation.hpp
- src/units/animation_component.cpp
- src/units/animation_component.hpp
- src/units/frame.cpp
- src/units/frame.hpp
- src/units/frame_private.hpp
- src/units/udisplay.cpp
- src/units/udisplay.hpp
Follow up to #9519. I wanted to handle it separately since it touches so much.
> Convert animation code to use chrono types

- src/preferences/preferences.cpp
- src/preferences/preferences.hpp
- src/preferences/preferences_list.hpp
> Add missed preference

- src/log.cpp
- src/log.hpp
- src/preferences/preferences.cpp
- src/serialization/chrono.hpp
- src/server/common/dbconn.cpp
- src/server/common/forum_user_handler.cpp
- src/server/common/forum_user_handler.hpp
- src/server/common/resultsets/ban_check.cpp
- src/server/common/resultsets/ban_check.hpp
- src/server/common/user_handler.hpp
- src/server/wesnothd/ban.cpp
- src/server/wesnothd/ban.hpp
- src/server/wesnothd/game.cpp
- src/server/wesnothd/metrics.cpp
- src/server/wesnothd/metrics.hpp
- src/server/wesnothd/player.cpp
- src/server/wesnothd/player.hpp
- src/server/wesnothd/player_connection.hpp
- src/server/wesnothd/server.cpp
- src/server/wesnothd/server.hpp
Still a few things to clean up, but mostly complete. Functionality should be unchanged.
> wesnothd: use std::chrono instead of the C time API

- data/core/units/boats/Boat.cfg
- data/core/units/boats/Galleon.cfg
- data/core/units/boats/Pirate_Galleon.cfg
- data/core/units/boats/Transport_Galleon.cfg
I messed up some image references in #9484, this should fix it.
> fix portrait references

- data/core/units/dwarves/Miner.cfg
Intended to compensate for high gold.
HP 22 -> 24
Attack 4x3 -> 5x3
> Balancing Update to Dwarvish Miner

- src/gui/dialogs/game_load.cpp
- src/gui/dialogs/game_stats.cpp
- src/gui/dialogs/preferences_dialog.cpp
- src/gui/dialogs/unit_create.cpp
- src/gui/dialogs/unit_list.cpp
- src/gui/dialogs/unit_recall.cpp
- src/gui/widgets/addon_list.cpp
- src/gui/widgets/listbox.cpp
- src/gui/widgets/listbox.hpp
@babaissarkar How does this affect your work on #9499?
> GUI2/Listbox: allow setting all sorters at once

- src/gui/widgets/listbox.cpp
- src/gui/widgets/listbox.hpp
Simplifies the Listbox builders. Split from #9499.
> listbox: simplify builder

- src/gui/widgets/listbox.cpp
- src/gui/widgets/listbox.hpp
Reverts wesnoth/wesnoth#9630. Was merged prematurely.
> Revert "listbox: simplify builder"

- data/gui/themes/default/widget/listbox_default.cfg
- src/gui/dialogs/game_load.cpp
- src/gui/dialogs/game_stats.cpp
- src/gui/dialogs/preferences_dialog.cpp
- src/gui/dialogs/unit_create.cpp
- src/gui/dialogs/unit_list.cpp
- src/gui/dialogs/unit_recall.cpp
- src/gui/widgets/addon_list.cpp
- src/gui/widgets/listbox.cpp
- src/gui/widgets/listbox.hpp
- src/gui/widgets/scroll_label.cpp
- src/gui/widgets/scroll_label.hpp
- src/gui/widgets/scroll_text.cpp
- src/gui/widgets/scroll_text.hpp
- src/gui/widgets/scrollbar_container.cpp
- src/gui/widgets/scrollbar_container.hpp
- src/gui/widgets/scrollbar_panel.cpp
- src/gui/widgets/scrollbar_panel.hpp
- src/gui/widgets/tree_view.cpp
- src/gui/widgets/tree_view.hpp
- src/utils/general.hpp
Worked off @babaissarkar 's work in #9630 combined with the general method employed by the matrix widget. Finally, `[instance]`!
> Listbox builder and sorter cleanup

- src/gui/widgets/container_base.cpp
- src/gui/widgets/container_base.hpp
- src/gui/widgets/generator.cpp
- src/gui/widgets/generator_private.hpp
- src/gui/widgets/grid.cpp
- src/gui/widgets/grid.hpp
- src/gui/widgets/grid_private.hpp
- src/gui/widgets/matrix.cpp
- src/gui/widgets/matrix.hpp
- src/gui/widgets/scrollbar_container.cpp
- src/gui/widgets/scrollbar_container.hpp
- src/gui/widgets/scrollbar_container_private.hpp
- src/gui/widgets/stacked_widget.cpp
- src/gui/widgets/stacked_widget.hpp
- src/gui/widgets/styled_widget.cpp
- src/gui/widgets/styled_widget.hpp
- src/gui/widgets/tree_view_node.cpp
- src/gui/widgets/tree_view_node.hpp
- src/gui/widgets/viewport.cpp
- src/gui/widgets/viewport.hpp
- src/gui/widgets/widget.cpp
- src/gui/widgets/widget.hpp
- src/gui/widgets/window.cpp
- src/gui/widgets/window.hpp
> GUI2: take find_widget and find ID args as string_view

- src/server/common/forum_user_handler.cpp
- src/server/common/forum_user_handler.hpp
- src/server/common/user_handler.hpp
- src/server/wesnothd/server.cpp
- src/server/wesnothd/server.hpp
I was not able to reproduce the crash locally, but this is the solution discussed on discord and it doesn't appear to break anything.
> attempt to fix wesnothd crash when player disconnecting before game history response

- add_source_file
I think the title is self explaining.
When i tested this, it removed unexpected things from the xcode projectfile, butim assuming its just that opening tthe pjects with the lib and hen closing them removes unsed stuff? Not fully sure
Also im unsure wheterh the option should be -d or -r
> Add -r option to add_source_file fix #8733

- changelog_entries/primary_authors.md
- data/gui/themes/default/window/editor_edit_pbl.cfg
- data/schema/pbl.cfg
- src/gui/dialogs/addon/addon_auth.cpp
- src/gui/dialogs/editor/edit_pbl.cpp
- src/server/campaignd/server.cpp
- src/server/common/forum_user_handler.cpp
- src/server/common/forum_user_handler.hpp
- src/server/common/user_handler.hpp
and use the new primary_authors attribute instead
Fixes #9547
> return pbl author attribute to its original usage

- src/server/common/simple_wml.cpp
- src/server/common/simple_wml.hpp
- src/server/wesnothd/game.cpp
- src/server/wesnothd/game.hpp
- src/server/wesnothd/server.cpp
- src/server/wesnothd/server.hpp
We refactor a the mp server game turn data a bit to fix #2563 and #3899
> Fix mp empty side1

- src/gui/dialogs/game_load.cpp
- src/gui/dialogs/game_load.hpp
- src/gui/dialogs/log_settings.cpp
- src/gui/dialogs/log_settings.hpp
- src/gui/dialogs/unit_create.cpp
- src/gui/dialogs/unit_create.hpp
- src/gui/dialogs/unit_recall.cpp
- src/gui/dialogs/unit_recruit.cpp
- src/gui/dialogs/unit_recruit.hpp
- src/gui/widgets/listbox.cpp
- src/gui/widgets/listbox.hpp
- src/utils/ci_searcher.hpp
Lottttt of redundant code. Pondering ways to abstract even further...
> GUI2: simplify various dialog's filter handling

- changelog_entries/dune_warmaster.md
- data/core/units/dunefolk/Warmaster.cfg
> Buff Dune Warmaster

- src/actions/undo_action.cpp
- src/ai/composite/aspect.hpp
- src/config.hpp
- src/events.cpp
- src/game_data.cpp
- src/gui/core/event/dispatcher_private.hpp
- src/gui/core/event/handler.cpp
- src/quit_confirmation.cpp
- src/scripting/application_lua_kernel.cpp
- src/utils/ranges.hpp
- src/whiteboard/highlighter.cpp
- src/whiteboard/mapbuilder.cpp
Uses a simpler approach than what I added in 7311b19d4d24ca0f54a309e033f2a767d56faeb4. Also adds additional aliases to the compat layer.
> Clean up and expand ranges compat layer

- data/campaigns/Eastern_Invasion/scenarios/05_Northern_Outpost.cfg
- data/campaigns/Eastern_Invasion/utils/final_battle/final_battle.cfg
> EI S05 prose: Galdren and the sylph 

- src/editor/map/map_context.cpp
- src/game_state.cpp
- src/team.cpp
- src/team.hpp
- src/teambuilder.cpp
- src/teambuilder.hpp
previously there were team::gold_ and team::team_info::gold
doing the same thing, now we just have one gold variable
team::team_info::gold, we also removed some related unused code
> cleanup team::gold

- src/gui/dialogs/outro.cpp
fix https://github.com/wesnoth/wesnoth/issues/9697 issue
> fix bug in compilation for gcc

- src/serialization/markup.cpp
- src/serialization/markup.hpp
- src/tests/test_help_markup.cpp
- src/tstring.hpp
> Markup: doc cleanup, take arguments by string_view when possible

- data/campaigns/Under_the_Burning_Suns/scenarios/01_The_Morning_After.cfg
Adds a couple of exclamation marks to better emphasize Kaleh's shock.
> UtBS S01: make Kaleh's dialog a bit more emotional

- data/campaigns/Eastern_Invasion/scenarios/08_Xenophobia.cfg
> EI S08: mention invasion force instead of just undead

- data/campaigns/The_South_Guard/_main.cfg
> Fix typo in TSG Comment

- data/campaigns/The_South_Guard/scenarios/01_Born_to_the_Banner.cfg
- data/campaigns/The_South_Guard/scenarios/02_Proven_by_the_Sword.cfg
- data/campaigns/The_South_Guard/scenarios/02x_Westin.cfg
- data/campaigns/The_South_Guard/scenarios/03_Vale_of_Tears.cfg
- data/campaigns/The_South_Guard/scenarios/04_Choice_in_the_Fog.cfg
- data/campaigns/The_South_Guard/scenarios/05b_Pebbles_in_the_Flood.cfg
- data/campaigns/The_South_Guard/scenarios/05c_Into_the_Depths.cfg
- data/campaigns/The_South_Guard/scenarios/06a_Vengeance.cfg
- data/campaigns/The_South_Guard/scenarios/06b_The_Tides_of_War.cfg
- data/campaigns/The_South_Guard/scenarios/06x_Epilogue.cfg
- data/campaigns/The_South_Guard/utils/savescumming.cfg
- data/campaigns/The_South_Guard/utils/sg_help.cfg
@Dalas121 Hopefully everything should make sense. Just a few comments:
* I think I must have mixed up the 'at range / in range' line references in my original review. The way I've changed it here sounds right to me.
* I'm guessing that line spacer wasn't meant to be translated.
* Line about healing should either be singular, 'a healer like me _or_ Ethiliel' or plural, '_healers_ like me and Ethiliel'.
* It's trivial, I know, but I really think double question marks and double exclamation marks are non-standard and distracting. Happy for those to be reverted if you feel strongly enough, however.
* In this context, classic and traditional mean the same thing to me so I found it redundant to call AToTB both.
* With respect to another instance of 'ironman' - I'm not sure what you'd prefer to …
> TSG: Various small corrections and revisions

- data/campaigns/The_Hammer_of_Thursagan/scenarios/01_At_the_East_Gate.cfg
Was supposed to have been changed with the map revision, but was not saved properly.
> Update coordinates for Movrur in THoT S1

- data/campaigns/The_South_Guard/scenarios/02_Proven_by_the_Sword.cfg
- data/campaigns/The_South_Guard/scenarios/05b_Pebbles_in_the_Flood.cfg
- data/campaigns/The_South_Guard/scenarios/06a_Vengeance.cfg
- data/campaigns/The_South_Guard/utils/sg_help.cfg
Some po hints and string changes to make TSG more translatable, as requested by @celerini in #9682. Is this an improvement?
> TSG: Improve Translatability

- src/gui/dialogs/wml_message.cpp
- src/gui/dialogs/wml_message.hpp
The fix I proposed in the issue discussion worked just fine.
> Fix [message] with two images.

- data/campaigns/Son_Of_The_Black_Eye/maps/13_The_Dwarvish_Stand.map
SotBE S13 map was last updated 8 years ago, so I did some refinements.
Mostly minor, more snow themed.
Same map size
> SotBE: S13: refine map

- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/attacks/attacks_high_fraction.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/attacks/attacks_multiply_fraction.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/berserk/berserk_high_fraction.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage/damage_high_fraction.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage/damage_multiply_fraction.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/drains/drains_high_fraction.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/drains/drains_multiply_fraction.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/heal_on_hit/heal_on_hit_high_fraction.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/heal_on_hit/heal_on_hit_multiply_fraction.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/heals/heal_high_fraction.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/heals/heal_multiply_fraction.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/illuminates/illuminates_high_fraction.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/illuminates/illuminates_multiply_fraction.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/leadership/leadership_high_fraction.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/leadership/leadership_multiply_fraction.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/regenerate/regenerate_high_fraction.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/regenerate/regenerate_multiply_fraction.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/resistance/resistance_high_fraction.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/resistance/resistance_multiply_fraction.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/special_calculations.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/swarm/swarm_attacks_max_fraction.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/swarm/swarm_attacks_min_fraction.cfg
- src/actions/attack.cpp
- src/reports.cpp
- src/units/abilities.cpp
- src/units/abilities.hpp
- src/units/attack_type.hpp
- src/utils/math.hpp
- wml_test_schedule
Fix https://github.com/wesnoth/wesnoth/issues/9467
> Fix weapon special int value ever truncated instead to be round to nearest integer.

- data/ai/lua/ai_helper.lua
> Convert hex to new format, closes #9799

- src/tests/main.cpp
Attempt to fix CI failure from https://github.com/wesnoth/wesnoth/commit/c9b54a5edacac369310d2c32f2a6b0986cdeca86.
> tests: call set_main_thread

- data/schema/filters/weapon.cfg
- data/test/scenarios/wml_tests/ScenarioWML/EventWML/events-test_filter_attack_type.cfg
- src/ai/formula/function_table.cpp
- src/formula/callable_objects.cpp
- src/gui/dialogs/attack_predictions.cpp
- src/gui/dialogs/unit_attack.cpp
- src/reports.cpp
- src/units/abilities.cpp
- src/units/attack_type.cpp
- src/units/attack_type.hpp
- src/units/unit.cpp
- wml_test_schedule
Fix (https://github.com/wesnoth/wesnoth/issues/8585)
> Doing [filter_attack/weapon]type= pick type who doing more damage only

- utils/dockerbuilds/CI/Dockerfile-base-android
Updates the dockerfile introduced in https://github.com/wesnoth/wesnoth/commit/7be779226514fb95df44b5635260e8e8d88288de.
1. Removes installation of dependency libraries via apt, they are downloaded and built from source during build.
2. Sets some environment variables
> Update android dockerfile

- data/campaigns/The_Hammer_of_Thursagan/maps/03_Strange_Allies.map
Accidentally deleted the branch for the last one (#9815). This passed checks the last time and was approved by knyghtmare and Dalas, so this can be merged I think.
(Not sure why this passed map diff check the last time but not this time)
> THoT S3 Map: Aesthetic Revision

- src/gui/dialogs/units_dialog.cpp
- src/gui/dialogs/units_dialog.hpp
- src/menu_events.cpp
- src/menu_events.hpp
- src/units/helper.cpp
- src/units/helper.hpp
* Properly grey out units in recruit dialog (similar to 1.18) (Resolves https://github.com/wesnoth/wesnoth/issues/9813)
* Fix crash (Resolves https://github.com/wesnoth/wesnoth/issues/9839)
> Units Dialog fixes

- data/campaigns/Son_Of_The_Black_Eye/_main.cfg
@ln-zookeeper has not committed to SotBE since 2018.
> Change zookeeper to former maintainer of SotBE

- data/core/units/wose/Wose_Sapling.cfg
Fixes #7685
This issue I created has been lying around for a very long time, so I thought I'd try my best to fix it.
@Dalas121 I believe this should be reviewed by you.
> Add Wose Sapling Description

- data/campaigns/The_Hammer_of_Thursagan/maps/04_High_Pass.map
Another aesthetic revision of a THoT map, this time Scenario 4, High Pass.
Current Map:
Proposed Map:
@Dalas121 Needs your review
> THoT S4 Map: Aesthetic Revision

- data/campaigns/The_Hammer_of_Thursagan/scenarios/02_Reclaiming_the_Past.cfg
I don't think the typography style guide specifies if this should be capitalized or not, but it does feel right and the capitalization was inconsistent within the same line, so I decided to fix it by capitalizing the word Lord in both titles.
> Consistently capitalize Lord in THoT S2 Text

- data/campaigns/Son_Of_The_Black_Eye/_main.cfg
Going with what the Wedge said in #9858
> SotBE: update credits

- data/campaigns/Son_Of_The_Black_Eye/_main.cfg
- data/campaigns/Son_Of_The_Black_Eye/scenarios/03_Toward_Mountains_of_Haag.cfg
- data/campaigns/Son_Of_The_Black_Eye/scenarios/13_The_Dwarvish_Stand.cfg
- data/campaigns/Son_Of_The_Black_Eye/scenarios/14_Back_Home.cfg
- data/campaigns/Son_Of_The_Black_Eye/scenarios/15_Civil_War.cfg
The only excluded one is S16: The Coward as it takes place during the first days of Spring.
> SotBE: add snow weather sfx to selected scenarios

- data/campaigns/The_Rise_Of_Wesnoth/_main.cfg
@ln-zookeeper has not committed to TRoW since 2018.
> Change zookeeper to former maintainer of TRoW

- data/core/encyclopedia/geography.cfg
Some small tweaks to the Green Isle section of the encyclopedia I recently added.
@Dalas121 Needs your review
> Green Isle Encyclopedia Tweaks

- data/campaigns/The_South_Guard/achievements.cfg
> Fix achievement and scenario name inconsistency in TSG

- src/sdl/rect.cpp
when i try to compile std::round not know
> fix rect.cpp compilation

- data/campaigns/Eastern_Invasion/units/Human_Owaec_Clan_Captain.cfg
- data/campaigns/Eastern_Invasion/units/Human_Owaec_Horse_Lord.cfg
- data/campaigns/Eastern_Invasion/units/Human_Owaec_Princeling.cfg
- data/campaigns/Eastern_Invasion/utils/abilities.cfg
> EI: Rename weapon special shock to stagger

- data/campaigns/The_Deceivers_Gambit/units/Saurian_Juvenile.cfg
> TDG: Fix typo in Saurian Juvenile Unit Description

- data/campaigns/Dead_Water/_main.cfg
> Use Far North instead of Northern Lands in DW Campaign Description

- data/campaigns/The_Hammer_of_Thursagan/_main.cfg
@Dalas121 Should you review this and #9926?
> Use Northlands instead of Northern Lands in THoT Campaign Description

- data/campaigns/Son_Of_The_Black_Eye/scenarios/16_The_Coward.cfg
Make Orga the Orc Warlord move to his keep and then face the player, Kapou'e
Shan Taum orders Orga to take care of the player while he chills at his keep. So, we move to Orga to the castle keep and give the impression he is taking over the Bitok defenses.
> SotBE-S16: tweak start event

- data/campaigns/Descent_Into_Darkness/units/Mal_Keshar.cfg
- data/campaigns/Descent_Into_Darkness/utils/abilities.cfg
- data/campaigns/Under_the_Burning_Suns/_main.cfg
- data/campaigns/Under_the_Burning_Suns/scenarios/01_The_Morning_After.cfg
- data/campaigns/Under_the_Burning_Suns/utils/abilities.cfg
- data/campaigns/Winds_of_Fate/utils/abilities.cfg
This had not yet been done in the mainline.
> Integrate special ability events into these abilities.

- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/filter_student_adjacent_active.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/filter_student_adjacent_inactive.cfg
else possibility of victory result in test.
> add 'invulnerable' status for prevent unit die during tests

- src/scripting/lua_race.cpp
> lua api: expose male/female names for races

- .github/workflows/map-diff.yml
Always generate a comment even if image upload failed and add API response for easier debugging.
> Add map dimension info

- data/campaigns/Eastern_Invasion/scenarios/11_Captured.cfg
Improvement upon 7e461ae2f52c28c37a41016e92776c30a806ce5a.
[ci_skip]
> Eastern Invasion S11

- data/campaigns/The_Hammer_of_Thursagan/scenarios/03_Strange_Allies.cfg
- Side 2 will be less reckless and more defensive
- Side 3 will avoid making stupid moves, like placing units on water for easy kills
Players have mentioned they are disappointed in AI allies in this scenario not performing as well as they expect them too.
> THoT-S3: make AI sides smarter

- data/campaigns/The_South_Guard/utils/sg_help.cfg
> TSG: sg_help.cfg: use correct variable call

- data/core/units/trolls/Great.cfg
> Revert "Use the alternative Troll Hero profile as a profile for the Great Troll"

- add_source_file
All the changes should be strictly styling changes to be more like other python files that are found in the project.  I didn't adjust any lines based off of line length because of the note about no min line length from the coding style guide on the website.
> Styling changes for readability

- scons/install.py
Addresses files in #9988 
Can keep PR open till all files have been addressed.
> Improve scons/ python files code style standards

- data/modifications/pick_advance/main.lua
> PUA: Access only the right unit type ID attribute

- .github/workflows/ci-main.yml
Closes #10044. This reverts the following commits: d3a8b882a75e155f32804205898f6d12008c0edc
6415bb8adc89b6b8d76735163e01ebb8a0cfe2e5
> Restore Windows CI job

- src/map/location.hpp
- src/mouse_events.cpp
- src/mouse_events.hpp
This makes units with weapons with custom min/max_range capable of attack when controlled by player.
(I have the AI code too, but not in this PR)
For proper working requires these PR merged:
Propper max/min_range: https://github.com/wesnoth/wesnoth/pull/9203
Propper UI preview: https://github.com/wesnoth/wesnoth/pull/9255
> UI support for real-ranged attacks

- utils/dockerbuilds/CI/Dockerfile-base-steamrt
- utils/dockerbuilds/steamrt/Dockerfile
- utils/dockerbuilds/steamrt/start.sh
Packages pango 1.50 with the Steam package, to avoid the issue mentioned in [#10088](https://github.com/wesnoth/wesnoth/pull/10088#issuecomment-2785195574).
> Add pango 1.50 to Steam package

- src/editor/map/map_context.cpp
> Editor: Remove old ToD schedule before saving new one

- src/display.cpp
- src/picture.cpp
- src/picture.hpp
Resolves #10101. I'm not entirely sure about the approach I've taken here, so any thoughts are welcome.
> Use a proper struct for lightmap adjustments

- data/core/editor/help.cfg
- data/core/encyclopedia/geography.cfg
- data/core/help.cfg
Covers `<img>`, `<ref>`, `<bold>`, `<italic>`, and `<header>`.
> Help: convert to new markup

- data/campaigns/Winds_of_Fate/units/Stymphalian.cfg
I made this description months ago but forgot to make a PR.
@Dalas121 I’m guessing you have to review this?
> Improve Stymphalian Unit Description

- src/gui/dialogs/units_dialog.cpp
To support the Great Horde mechanic in SotBE
Closes #8265
supersedes #9887
Note: Another non-engine alternative solution is modifying SotBE's Great Horde mechanics code itself. So, can do that if this does not fly either.
> units_dialog.cpp: edit message text

- data/campaigns/Son_Of_The_Black_Eye/scenarios/15_Civil_War.cfg
- essentially units will prefer sticking to enemy leader if player units are nearby
- this makes the scenario less boring in the end when you just to kill a leader on a keep
> SotBE S15: add AI support code

- src/serialization/string_utils.cpp
- src/serialization/string_utils.hpp
- src/tests/test_serialization.cpp
Completely rewrote the function to be 2-5x faster in most cases. Fixed a passing test case that should have failed and added a few more cases.
> Improve the performance of wildcard_string_match

- src/scripting/game_lua_kernel.cpp
Closes #9591
Back-port of 8ee2a2663451f1c68cc2ee76483f6c9f7340ac07
> Fix width weirdness with add_overlay_text (1.18)

- src/ai/contexts.cpp
- src/ai/formula/ai.cpp
- src/chat_command_handler.cpp
- src/chat_events.cpp
- src/chat_events.hpp
- src/display_chat_manager.cpp
- src/display_chat_manager.hpp
- src/floating_textbox.cpp
- src/formula/function.cpp
- src/game_events/pump.cpp
- src/gui/dialogs/lua_interpreter.cpp
- src/gui/widgets/chatbox.cpp
- src/gui/widgets/chatbox.hpp
- src/menu_events.cpp
- src/menu_events.hpp
- src/playmp_controller.cpp
- src/playsingle_controller.cpp
- src/replay.cpp
- src/scripting/game_lua_kernel.cpp
- src/scripting/lua_common.cpp
- src/tests/gui/test_gui2.cpp
- src/whiteboard/manager.cpp
The chrono work continues. Besides misc changes and some things still using SDL_GetTicks, this should be the last of the big chrono batch changes.
> Chat Handler: use std::chrono over C time API

- src/reports.cpp
- src/units/unit.cpp
- src/units/unit.hpp
Fix https://github.com/wesnoth/wesnoth/issues/10241 issue.
> Fix Sidebar tooltip no longer shows effect of unit damage resistances(always 0%)

- .github/workflows/ci-main.yml
- CMakeLists.txt
- SConstruct
- src/xBRZ/xbrz.cpp
build the servers with strict enabled
> update to latest mariadbpp

- data/campaigns/Under_the_Burning_Suns/_main.cfg
- data/campaigns/Under_the_Burning_Suns/utils/abilities.cfg
Complete https://github.com/wesnoth/wesnoth/commit/8a3be4fd3eebdf1eaae28be530a86f3830f33548
reply to https://github.com/wesnoth/wesnoth/issues/10243#issuecomment-2929514717
> add id to event_abilities in Utbs

- src/preferences/preferences.cpp
> Check the correct attribute for sub achievements

- data/core/units/dunefolk/Wyvern_Rider.cfg
Previously, it was doing a melee attack thing for a ranged attack...
> [Units] Wyvern Rider: update ranged attack anim

- changelog_entries/add_radius_to_filter_adjacent.md
- data/schema/filters/unit.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/filter_distant_active.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/filter_distant_direction_active.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/filter_distant_direction_inactive.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/filter_distant_inactive.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/filter_filter_distant_active.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/filter_filter_distant_direction_active.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/filter_filter_distant_direction_inactive.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/filter_filter_distant_inactive.cfg
- src/units/abilities.cpp
- src/units/filter.cpp
- wml_test_schedule
with using this attribute it is possible to filter unit on a radius greater than 1.
> add a 'radius' to abilities [filter_adjacent] and [filter][filter_adjacent].

- data/core/units/boats/Canoe.cfg
- data/core/units/boats/Derelict_Ship.cfg
- data/core/units/boats/Elf_Cutter.cfg
- data/core/units/boats/Elf_Sloop.cfg
- data/core/units/boats/Fireship.cfg
- data/core/units/boats/Ghost_Ship.cfg
- data/core/units/boats/Orc_Barge.cfg
- data/core/units/boats/Orc_Battle-Barge.cfg
- data/core/units/boats/Orc_Rigship.cfg
- data/core/units/boats/Orc_Warship.cfg
- data/core/units/boats/Pirate_Ship.cfg
- data/core/units/boats/Raft.cfg
- data/core/units/boats/Raider_Coastal.cfg
- data/core/units/boats/Raider_Iron.cfg
- data/core/units/boats/Skiff.cfg
- data/core/units/boats/Transport_Ship.cfg
addresses the comment here: https://github.com/wesnoth/wesnoth/issues/10217#issuecomment-2964421227
> 1.19 - add primary key to boat frames

- src/reports.cpp
- src/units/unit.cpp
- src/units/unit.hpp
else [damage_type] not used in tooltips
> Fix weapon tooltip to display modifications by [damage_type]

- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/filter_adjacent_self_inactive.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/filter_filter_adjacent_self_inactive.cfg
- src/units/abilities.cpp
- src/units/filter.cpp
- wml_test_schedule
Resolves https://github.com/wesnoth/wesnoth/issues/10304
> Fix [filter_adjacent] which checks the central unit

- data/campaigns/The_Deceivers_Gambit/utils/spellcasting.cfg
- data/campaigns/Under_the_Burning_Suns/utils/abilities.cfg
- data/core/macros/abilities.cfg
- src/units/abilities.cpp
name_affected attribute is intented for abilities used like specials only
> Fix 'name_afected' implemented in [specials] specials by error

- src/game_events/manager.cpp
its possible that event cleanup fails. I don't see any serious problems in that case so i replaced that assertion with a ERR_NG.
See also issue #9708
> Fix assertion after event cleanup failue

- data/campaigns/Northern_Rebirth/scenarios/04_Clearing_the_Mines.cfg
Source: https://forums.wesnoth.org/viewtopic.php?p=698930#p698930
> NR S04: check if hex is passable before spawn

- data/test/scenarios/lua_tests/gui/show_dialog.cfg
- src/lua_jailbreak_exception.cpp
- src/lua_jailbreak_exception.hpp
- src/scripting/lua_widget_methods.cpp
- wml_test_schedule
> Lua jailbreak catch backport1.18

- changelog_entries/new-wfl-functions.md
- src/formula/function.cpp
- src/formula/function_gamestate.cpp
Adds debug_print, run_file, nearest_loc, unit_tod_modifier, is_shrouded, and is_fogged as non-FAI WFL functions.
> WFL: add new core functions to supplement FAI functionality

- changelog_entries/ghoul_line.md
- data/core/units/undead/Corpse_Ghast.cfg
- data/core/units/undead/Corpse_Ghoul.cfg
- data/core/units/undead/Corpse_Necrophage.cfg
> Ghoul-line: Resistance changes

- src/sound.cpp
- Fix index argument never being used
- Don't try and play an invalid track even once
- Manage new track with shared_ptr (avoids unnecessary copies)
- Clarify list-insert logic
> Improve play_music_config implementation

- projectfiles/CodeBlocks/wesnoth.cbp
- src/units/abilities.cpp
- src/units/ability_tags.hpp
- src/units/udisplay.cpp
- src/units/unit.hpp
So they are all gathered in the same file
> Move checking_tags()set to ability_tags.hpp file

- changelog_entries/add-radius-to_illuminates-abilities.md
- data/schema/units/abilities.cfg
- data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/illuminates/illuminates_value_chaotic_distant.cfg
- src/tod_manager.cpp
- wml_test_schedule
work like [affect_adjacent]radius but for radius of illumination/darkening
> give 'radius' to 'illuminates' abilities

- data/campaigns/The_South_Guard/lua/companion_message.lua
- data/campaigns/The_South_Guard/scenarios/02x_Westin.cfg
- data/campaigns/The_South_Guard/scenarios/03_Vale_of_Tears.cfg
- data/campaigns/The_South_Guard/scenarios/04_Choice_in_the_Fog.cfg
- data/campaigns/The_South_Guard/scenarios/05a_The_Long_March.cfg
- data/campaigns/The_South_Guard/scenarios/06a_Vengeance.cfg
Urza Afalas was significantly more "noble" in the original TSG than in my revision. Revert some of that here.
Also fixes a `[companion_message]` bug, and reduces difficulty on one branch of S04.
> TSG: make Afalas nicer

- src/gui/core/canvas.cpp
- src/gui/core/canvas_private.hpp
The i18n support was added in 887bd5f7d60da0e4373de877127d663ba565b3cc.
A trivial change, collecting knowledge from working on #10449.
> Update comments about image loading for canvases

- data/tips.cfg
Adds a new gameplay tip highlighting that hotkeys are customizable (improves player QoL discovery) and fixes an extra space in an existing tip line. Changes:
data/tips.cfg: +1 new tip, minor spacing correction.
Rationale:
Encourages players to tailor controls, speeding turn execution.
Low-risk text-only change; no gameplay logic impacted.
> Tips: add hotkey customization tip and fix spacing

- data/campaigns/Two_Brothers/maps/04_Return_to_the_Village.map
@Dalas121 Very minor aesthetic changes to this map. I have made sure this map's new embellishments don't overlap with ruined houses seen in the scenario.
Current Map:
Proposed Map:
> AToTB S4 Map: Aesthetic Revision

- data/campaigns/The_Deceivers_Gambit/utils/spellcasting.cfg
Fix https://github.com/wesnoth/wesnoth/issues/10489 issue. (partially)
To fix the other issues, I have to leave the third point unresolved and restore some playability.
> Fix some issues with 'Enthrall' in TDG

- changelog_entries/tdg_adjustments.md
- data/campaigns/The_Deceivers_Gambit/scenarios/11x_Revelry.cfg
- data/campaigns/The_Deceivers_Gambit/scenarios/13_Revelry_Revisited.cfg
- data/campaigns/The_Deceivers_Gambit/scenarios/13x_The_King_is_Dead.cfg
- data/campaigns/The_Deceivers_Gambit/scenarios/14_Long_Live_the_Queen.cfg
Before TDG was added to mainline, I made some adjustments to the campaign to stay compatible with the upcoming "Asheviere's Dogs" campaign. However, the "Asheviere's Dogs" author is now planning to make some major revisions to his campaign, which has delayed its entry to mainline until 1.21.
Therefore, I'm making some further changes to the final few scenarios so as to lead more smoothly into Liberty and Heir to the Throne. This PR also includes some improvements to those scenarios' dialogue based on @doofus-01's feedback.
> TDG: Asheviere's Dogs reversions

- src/savegame.cpp
Since this is seemingly meant to be a private function, move its two implementations to the closest anonymous namespace and drop the prototypes to avoid the issue altogether.
> Fix "no previous prototype for function" warnings on Xcode 26

- data/multiplayer/scenarios/2p_Sullas_Ruins.cfg
Makes it more consistent with https://github.com/wesnoth/wesnoth/pull/8539.
> Sulla's Ruins: mention that Sulla was Aether Mage

- src/config.cpp
- src/config.hpp
- src/game_config_view.cpp
- src/game_config_view.hpp
Just a bunch of small cleanups to config that I had sitting around.
> Config: misc minor cleanups
