wesnoth/wesnoth

.github/workflows/labeler.yml
Setting sync-labels to "true" means that it removes labels which people have added, but which aren't implied by the filelist.
=> Stop removing manually-added labels on Github PRs

src/units/abilities.cpp
best fix what https://github.com/wesnoth/wesnoth/pull/7537 or https://github.com/wesnoth/wesnoth/pull/7535 because don't delete placeholder weapon of filter_attack and applied to weapon like ability only.
=> fix ability used like weapon affect placeholder weapon used in defense when not attack of same range what attacker

data/test/scenarios/wml_tests/ScenarioWML/EventWML/events-test_filter_attack_no_defense.cfg, wml_test_schedule
A new test of what happens when a unit with only a ranged weapon fights a unit with only a melee weapon, along with a code change to ignore the placeholder attack that caused the new test to fail.
(The next paragraph is a suggestion for future work, I'm not intending to add it to this PR.)
This only affects the filtering so far, there should probably be another additional test to check what the combat results are. Not added in this commit, as the test here is specific to the code path being fixed; also testing the actual results would need an ability such as the Deep Elves' Stardust that passively affects the amount of damage taken, and doesn't need the defender to hit with a slows ability.
@newfrenchy83 I'm suggesting this instead of #7535, please would you review it?
=> Test attack_filter with melee-only vs ranged-only units

data/test/scenarios/wml_tests/ScenarioWML/EventWML/ActionWML/DirectActionsWML/modify_unit_recall_cost.cfg, src/units/unit.cpp, src/units/unit.hpp, wml_test_schedule
Fixed issue #7159. Bug had to do with indexing into 0 based team vector with 1 based side_ member variable as speculated in the thread. Added method to return side_ - 1 and then used in apply_to recall_cost code.
=> Fix modify_unit recall_cost indexing issue 

data/core/units/monsters/Caribe.cfg, data/core/units/monsters/Caribe_Hunter.cfg, data/core/units/monsters/Caribe_Nibbler.cfg, data/core/units/monsters/Dragonfly.cfg, data/core/units/monsters/Dragonfly_Grand.cfg, data/core/units/monsters/Elder_Falcon.cfg, data/core/units/monsters/Falcon.cfg, data/core/units/monsters/Seahorse.cfg
To keep the ellipses and status indicators from bobbing/drifting with the base frame, I'd put the body sprite in an alternate frame, but did not think to check for status effect color-shifts like poison or slows.  This is a simple fix for that, only question is if I missed some unit.
fixes #7551
=> [1.17] - make engine-bobbing sprites use the correct primary frame

.github/workflows/ci-main.yml
This adds new CI artifact containing file wesnoth.flatpak. It can be installed and run like this:
`flatpak --user install wesnoth.flatpak`
`flatpak run --branch=ci org.wesnoth.Wesnoth`
After done with with testing it can be removed to save disk space:
`flatpak uninstall org.wesnoth.Wesnoth` and choose install from branch `ci` if there are other installs.
=> Made flatpak ci job upload bundle too

data/test/scenarios/wml_tests/ScenarioWML/EventWML/ActionWML/ConditionalActionsWML/swarms_effects_not_checkable.cfg
The test spawns a new unit, this commit makes it test that new unit instead of the Elvish Archer with a 5x2 melee attack.
@newfrenchy83 please would you review this?
=> Test the correct unit in swarms_effects_not_checkable

src/deprecation.hpp, src/serialization/base64.hpp, src/serialization/preprocessor.hpp
Looks like 1.16.9 no longer compile on new compilers as Clang 16.
Due errors:
```
/builddir/build/BUILD/wesnoth-1.16.9/src/deprecation.hpp:20:24: error: unknown type name 'uint8_t'
DEBUG util.py:445:  enum class DEP_LEVEL : uint8_t { INDEFINITE = 1, PREEMPTIVE, FOR_REMOVAL, REMOVED };
DEBUG util.py:445:                         ^
DEBUG util.py:445:  In file included from /builddir/build/BUILD/wesnoth-1.16.9/src/serialization/preprocessor.cpp:25:
DEBUG util.py:445:  /builddir/build/BUILD/wesnoth-1.16.9/src/config.hpp:51:12: error: enumeration redeclared with different underlying type 'uint8_t' (aka 'unsigned char') (was 'int')
DEBUG util.py:445:  enum class DEP_LEVEL : uint8_t;
DEBUG util.py:445:             ^
DEBUG util.py:445:  /builddir/build/BUILD/wesnoth-1.16.9/src/deprecation.hpp:20:12 …
```
=> add missing stdint.h includes

projectfiles/CodeBlocks/wesnoth.cbp, projectfiles/Xcode/The Battle for Wesnoth.xcodeproj/project.pbxproj, source_lists/wesnoth, src/actions/advancement.cpp, src/actions/attack.cpp, src/actions/create.cpp, src/actions/undo_recall_action.cpp, src/actions/undo_recruit_action.cpp, src/game_initialization/multiplayer.cpp, src/game_launcher.cpp, src/gui/dialogs/multiplayer/mp_join_game.cpp, src/gui/dialogs/statistics_dialog.cpp, src/gui/dialogs/statistics_dialog.hpp, src/menu_events.cpp, src/menu_events.hpp, src/play_controller.cpp, src/play_controller.hpp, src/playsingle_controller.cpp, src/replay.cpp, src/saved_game.cpp, src/saved_game.hpp, src/savegame.cpp, src/statistics.cpp, src/statistics.hpp, src/statistics_record.cpp, src/statistics_record.hpp, src/tests/gui/test_gui2.cpp, src/wesnoth.cpp, src/whiteboard/recall.cpp
Previously statistics were stored in global variables, now it is a part of saved_game. With this saved_game now finally represent the contents of a safefile as it was intended to, without needing to fill the statistics part in some global variable.
In particular now no longer have to manually reset the statistics as random parts of the code, it gets reset along with the saved_game object. Also it is now in theroy possible for multiple saved_game objects to exist.
Statistics was split in two objects, the statistics_record which only contains the data, and statistics_t, which provides methods to modify statistics during a game (to get cleaner dependencies)
=> Refactor Statistics

data/gui/macros/_initial.cfg, data/gui/widget/label_achievement_title.cfg, data/gui/window/achievements_dialog.cfg, src/gui/dialogs/achievements_dialog.cpp
This is done as a guarantee that there will always be one unambiguous way to identify that the achievement is completed.
=> Don't allow markup in achievement titles.

data/tools/wmlunits
This fixes an issue of missing resources, such as seen in https://units.wesnoth.org/1.16/To_Lands_Unknown/en_US/To_Lands_Unknown.html
Closes #4124
=> wmlunits: Include nested dependencies in -L for -B to process

data/campaigns/Descent_Into_Darkness/scenarios/01_Saving_Parthyn.cfg, data/campaigns/Descent_Into_Darkness/scenarios/03_A_Haunting_in_Winter.cfg, data/campaigns/Descent_Into_Darkness/scenarios/07b_A_Small_Favor2.cfg, data/campaigns/Descent_Into_Darkness/scenarios/07c_A_Small_Favor3.cfg, data/campaigns/Descent_Into_Darkness/scenarios/10_Endless_Night.cfg, data/campaigns/Sceptre_of_Fire/scenarios/9_Caverns_of_Flame.cfg, data/campaigns/The_South_Guard/scenarios/06a_Into_the_Depths.cfg, data/campaigns/The_South_Guard/scenarios/08b_The_Tides_of_War.cfg, data/core/editor/help.cfg, data/tools/pywmlx/state/lua_states.py, data/tools/pywmlx/state/machine.py, data/tools/pywmlx/state/wml_states.py
```
[message]
speaker=narrator
message= "This is the story I am narrating, but I forgot to mark is a translatable"
[/message]
[message]
speaker=Delfador
message= _ "Hi. I am a mage, and my sentence will be translated"
[/message]
```
According to @AncientLich , current behavior is:
> in this situation, discarding all previous comments after the first sentence found avoids to place itself in a wrong place. If the # po wouldn't discarded, than it would be applied to the next translatable string, with the result of adding the comment "narrator is explaining the tale" in the sentence "Hi. I am a mage, and my sentence will be translated".
> This behaviour is thinked in order to prevent to misplace comments or overrides. The logic around this choice was "better dropping an information, than …
=> wmlxgettext: Error out on unused #po, #po-override directives

data/_main.cfg, data/test/_main.cfg
Move the line that includes data/test/scenarios/manual_tests/ below the line that includes data/test/macros/. This allows a manual test to use the setup in COMMON_KEEP_A_B_C_D_UNIT_TEST, putting units in the right position to test combat and leadership abilities.
Also improve comments in data/test/_main.cfg.
=> Reorder WML includes so manual tests can use the unit-test macros

data/gui/window/achievements_dialog.cfg, data/lua/wml-conditionals.lua, data/lua/wml-tags.lua, data/schema/achievements.cfg, src/achievements.cpp, src/achievements.hpp, src/gui/dialogs/achievements_dialog.cpp, src/gui/dialogs/achievements_dialog.hpp, src/preferences/general.cpp, src/preferences/general.hpp, src/scripting/game_lua_kernel.cpp, src/scripting/game_lua_kernel.hpp
This adds support for having up to 28 distinct sub-achievements within a single achievement. This limit exists since wesnoth's layout isn't smart enough to tell a horizontal listbox to actually use its scrollbar instead of forcing a horizontal scrollbar on the whole window.
Additionally this adds the [set_sub_achievement] and [has_sub_achievement] WML tags and their respective lua functions. [has_sub_achievement] is unsafe for use in MP, for the same reasons that [has_achievement] is.
---
=> Add support for distinct sub-achievements.

changelog.md, src/gui/core/event/handler.cpp
The documentation is a bit unclear, but `SDL_WINDOWEVENT_RESIZED` seems not to trigger under certain circumstances, specifically when changing resolution via `SDL_SetWindowSize()`; `SDL_WINDOWEVENT_SIZE_CHANGED` meanwhile is implied to trigger any time the window size changes whether it's from an API call, or the operating system, or a user action.
<https://wiki.libsdl.org/SDL2/SDL_WindowEventID>
We need to translate at least one of these events into a GUI2 event in order for dialogs to be properly re-laid out after the window size changes, but we should not handle both because that could result in unnecessary work recalculating all dialog layouts.
Closes #7436.
Tested on macOS Ventura and openSUSE Tumbleweed so far. I want to properly test this on Windows just in case so don't merge yet.
=> gui: Handle SDL_WINDOWEVENT_SIZE_CHANGED instead of SDL_WINDOWEVENT_RESIZED

changelog.md, src/gui/dialogs/title_screen.cpp, src/gui/dialogs/title_screen.hpp
This unifies both the Version and the Language menu labels into a single method for both that is called both during construction and after switching languages. Both have this issue where they aren't `t_string` instances, so changing languages has no effect on them for that reason and they need to be manually re-translated.
=> gui2/title_screen: Fix Version label translation not updating

data/campaigns/Northern_Rebirth/scenarios/01_Breaking_the_Chains.cfg, data/campaigns/Northern_Rebirth/utils/herodeaths.cfg
So this is another part of the northern rebirth editing /rewrite I'm doing. The last one was #7454. This one isn't the next scenario but I should be able to get that soon. This one is fixing a couple editing problems I didn't catch in scenario one and I real quick checked the herodeaths.
The main thing is in scenario one I rewrote a paragraph in order to fix issue #6510. I also changed a sentence that seemed to really pop out to be confusing. The bit about raiding parties becoming companies becoming war-bands. Because while you can have a company of orc soldiers, it's different from a war band.
I also added an oxford comma. Are we using oxford comas in wesnoth? If not I'll change it back. 
The hero death changes are pretty self explanatory.
=> Nr: Dialog/ Story Rewrite : Scenario One (Fix) and herodeaths

src/formula/string_utils.cpp, src/formula/string_utils.hpp
Prevent crash from buffer overflow and improve the approximation of the Levenshtein distance without sacrificing much performance.
Fixes: #7412
=> fix: crash in edit_distance_approx

data/gui/widget/toggle_button_no_label.cfg, src/gui/dialogs/drop_down_menu.cpp
Using checkboxes with an empty label doesn't quite do the trick and it results in some (minimal) wasted horizontal space.
I wrote the labelless checkbox definition a few years ago precisely to solve a similar issue in the MP alerts configuration dialog, so it makes sense to use it here as well since the real label is a different widget on a different column.
**Before:**
**After:**
=> gui: Use true labelless checkboxes in the dropdown menu implementation

data/gui/window/mp_match_history.cfg, src/gui/dialogs/multiplayer/match_history.cpp, src/gui/dialogs/multiplayer/match_history.hpp, src/server/common/dbconn.cpp, src/server/common/dbconn.hpp, src/server/common/forum_user_handler.cpp, src/server/common/forum_user_handler.hpp, src/server/common/user_handler.hpp, src/server/wesnothd/server.cpp
This still defaults to searching by the selected player name, but now also allows searching by:
* player name
* game name
* one of scenario id, era id, or modification id
The game name, scenario id, era id, and modification id support a leading and/or trailing wildcard for partial matches by essentially replacing the leading and/or trailing asterisk with a percent sign.
Scenario, era, and modification parameters are the ID, not the name, since the server gets the translated value for the name. Therefore searching by name would only give partial results in nearly all situations. So while this is probably unintuitive to a player, it still seems like the less bad option.
---
The updated UI:
The close button and left/right arrows have been moved up into the same line as the new Search button …
=> Add some search terms to the match history dialog.

src/addon/info.cpp, src/display.cpp, src/editor/action/mouse/mouse_action_select.cpp, src/editor/editor_display.cpp, src/game_display.cpp, src/game_launcher.cpp, src/picture.cpp, src/picture.hpp, src/units/frame.cpp, src/whiteboard/suppose_dead.cpp, src/widgets/menu.cpp
- Used inline default values to reduce ctor mess
- Used a forwarded ctor for locator::value instead of duplicating them between the main class and the value class
- Removed trailing underscores from public struct members
- Removed const char* ctor to make locator use more explicit instead of relying on implicit conversions
- Moved parse_arguments to a value ctor since it's more appropriate there
- Added locator::clone to replace the ctor with optional modifications
=> Cleaned up implementation of image::locator

cmake/FindTranslationTools.cmake, doc/manual/CMakeLists.txt
This and @loonycyborg's #7648 are both working on #7149. Ended up with this being the CMake one, and the other being the SCons one.
The po4a tool's author considers running po4a-gettextize to be a once-and-done operation, however it seems to be moving towards acting as its own build system, expecting to be run with a config file telling it which files to build.
See https://bugs.debian.org/1020821
=> Support po4a version 0.68-1 (cmake part)

doc/manual/CMakeLists.txt, po/SConscript, scons/gettext_tool.py
Backport the SCons fix from https://github.com/wesnoth/wesnoth/pull/7648 and the CMake fix from https://github.com/wesnoth/wesnoth/pull/7649.
Fixes #7149.
This cherry-picks only the important part of #7649 from master, making the script use `PO4A-UPDATEPO_EXECUTABLE` instead of `PO4A-GETTEXTIZE_EXECUTABLE`. In contrast to the master branch's commit, this makes no changes to  findTranslationTools.cmake, so `PO4A-GETTEXTIZE_EXECUTABLE` will still be defined in that script. It's simply that that script has been extensively rewritten in master, and I don't see a point in porting that part of the change.
=> [1.16] Backport the fixes for running pot-update with recent versions of po4a

src/wesnoth.cpp
This replaces a workaround to overwrite SDL signal handlers with our own by simply telling SDL to not set up its signal handlers.
=> Remove signal handlers

src/gui/dialogs/addon/install_dependencies.cpp
Forward-port of #7674, just doing a CI run. This isn't an issue with the CMake scripts in master, I'm just cherry picking the commit so that there isn't a "missing" commit on master.
C++ source files are considered to be in textdomain "wesnoth" by default.
The 1.16 CMake scripts that sort files into textdomains miss this file, because it treats files with no `GETTEXT_DOMAIN` as being in "wesnoth", but not ones that explicitly declare themselves in "wesnoth".
(cherry picked from commit f0ceaf2ae086bf412e56778656e3f4b95824a261)
=> Remove an explicit GETTEXT_DOMAIN "wesnoth"

data/themes/default.cfg, src/controller_base.cpp, src/controller_base.hpp, src/editor/controller/editor_controller.cpp, src/editor/controller/editor_controller.hpp, src/game_events/menu_item.hpp, src/game_events/wmi_manager.cpp, src/game_events/wmi_manager.hpp, src/hotkey/command_executor.cpp, src/hotkey/command_executor.hpp, src/hotkey/hotkey_command.cpp, src/hotkey/hotkey_handler.cpp, src/hotkey/hotkey_handler.hpp, src/hotkey/hotkey_handler_mp.cpp, src/hotkey/hotkey_handler_mp.hpp, src/hotkey/hotkey_handler_sp.cpp, src/hotkey/hotkey_handler_sp.hpp, src/replay_controller.cpp, src/replay_controller.hpp
This also does a bit of refactoring on the show_menu code, in particular `do_execute_command` now now tries to use the id of the command instead of mapping the index to certain actions. It's not perfect yet and i'm not sure yet what i want the final interface to be though
=> Separate menus for quick replays

data/campaigns/Under_the_Burning_Suns/scenarios/08_Out_of_the_Frying_Pan.cfg
It needs to be translatable because it needs to match the other strings that call him by name. It was translatable until 1.15.4, and several of the .po files that are already in the 1.16 still include it as an obsolete message, so the next pot-update run will turn this back into a translated text in Bulgarian, Greek, Irish, Galician, Latin, Lithuanian, Russian, Serbian and Traditional Chinese.
Opening as a PR, but will be linking to this from the forum thread about translations.
=> [1.16] UtBS: Make the name of the dark assassin translatable again

src/log.cpp
this uses tee sink from boost.iostreams
=> Write log output both to stderr and logfile at the same time

data/campaigns/Under_the_Burning_Suns/scenarios/02_Across_the_Harsh_Sands.cfg, data/campaigns/Under_the_Burning_Suns/scenarios/03_Stirring_in_the_Night.cfg, data/campaigns/Under_the_Burning_Suns/scenarios/06b_In_the_Domain_of_Dwarves.cfg, data/campaigns/Under_the_Burning_Suns/scenarios/08_Out_of_the_Frying_Pan.cfg
Forward-port of #7697, so assuming that just waiting 24 hours for the CI and any comments is OK.
po: The rest of this commit message is for the translators' changelog, because it's notes about what changed recently, as found by looking at fuzzies while updating the German translation.
S01 "Come on, Kaleh, we have to go see if anyone is hurt or needs help. ..." was just a grammar fix, of "answer to the call".
UtBS S08's dialogue had Esanoo refer to Melusand as "my master" repeatedly. That changed to "leader" or "wise leader" in 1.15.4, mainly without other changes in the text.
Other lines should have changed "master" to "leader". I'm planning to do that later, but this commit is just the cherry-pick.
* S08 Zhul's "You don’t know where to find your master?"
* S08 Kaleh's two game-over lines …
=> UtBS: improve po hints

CONTRIBUTING.md
There's also <https://wiki.wesnoth.org/UI_Style_Guide>, which I haven't linked here.
=> Contributing: the Typography and Gettext docs are separate Wiki pages

data/core/units/monsters/Jinn.cfg, data/core/units/monsters/Wild_Wyvern.cfg, data/core/units/undead/Corpse_Soulless.cfg, data/core/units/undead/Corpse_Walking.cfg
Some units still didn't change color when they were supposed to (poisoned or petrified*, anything else?)
- Jinn 
- Wild Wyvern
- WC & Soulless Falcon
I think this is it, but if anyone finds something, I can add it to the list.
partially deals with #7709 
[*] via debug, they do turn gray under most circumstances.
=> 1.17 - add primary key to some unit animations that need it

src/units/abilities.cpp
I forget what abilities is the only who can use 'overwrite_specials' and what'filter_student' must ever checked instead of 'filter_self' in reference list
=> Fix bug in overwrite_specials

data/test/_main.cfg, data/test/lua/wml_tags.lua, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/plague_without_priority.cfg, data/test/units.cfg, data/test/units/test_melee_quintain.cfg, wml_test_schedule
Just a draft for the moment, as several different improvements have ended up intertwined with each other. If anyone wants to use one of these on its own, please shout, because I feel this PR is going to be in draft for about a month (other things in life are currently higher priority).
The new tag takes ids instead of needing coordinates. So instead of storing units or hardcoding values, an attack can be done like this:
```
[test_do_attack_by_id]
attacker=alice
defender=bob
weapon=0
[/test_do_attack_by_id]
```
Add a simpler unit for unit tests than the Elvish Archer / Orcish Grunt combo, cherry-picked from gfgtdf's PR #7589. This is a unit with a 10x1 melee attack, and 0% defense on all terrains.
Edit on 29th June: this now includes a test for plague abilities, to see if a plague weapon …
=> Add [test_do_attack_by_id], a wrapper for [do_command][attack]

data/campaigns/Liberty/scenarios/06_The_Hunters.cfg
Resolves #7751
Question: Would it be appropriate to back-port this to 1.16? While it's not a major bug, there doesn't appear to be high risk in making this correction either.
=> Liberty S6: Correct target hex for Shadow Mage

changelog_entries/liberty_s5.md, data/campaigns/Liberty/scenarios/05_Hide_and_Seek.cfg
Hans only makes an appearance in this scenario and isn't even mentioned afterwards (that I could see). Still, Link explicitly states that Hans will guide Baldras and Harper to the Grey Woods so I suppose it does make sense to make a consequence of Hans' death.
I'm not a writer, happy for the dialogue to be updated directly without my input. But the change itself should address @Konrad22's concern in #7750.
=> Liberty S5: Make the loss of Hans a lose-condition

changelog_entries/did_s3.md, data/campaigns/Descent_Into_Darkness/scenarios/03_A_Haunting_in_Winter.cfg
Resolves #7758
New commit instead of just reverting 4a5f38c5755da9e4ab3511f1daf2e3987e33d9f7 so I could add an explanatory comment to hopefully avoid this kind of breakage again.
=> DiD S3: Resolved Darken Volk speaking from the darkness

data/campaigns/Descent_Into_Darkness/utils/amlas.cfg
Resolves #7767.
Not sure if it could be back-ported. Perhaps not, since it's a bug that works in the player's favour.
Alternative would be to change the description to match the actual effect.
=> DiD: Correct inconsistency between AMLA description and its actual effect

data/test/macros/start_position_common_keep_a_b.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/teacher_damage_formula.cfg, wml_test_schedule
Originally by gfgtdf, this was cherry-picked from gfgtdf's PR #7589, with modifications.
COMMON_KEEP_A_B_UNIT_TEST gains support for optional args SIDE1_LEADER and SIDE2_LEADER.
=> Add a test for formulas in taught abilities

src/units/abilities.cpp, src/units/attack_type.hpp
Because complexity of special_active function, i was afraid to use directly special_affects_self/opponent, but like in this state, only apply to self/opponent/etc. is pertinent, i have finally try that.
=> simplify checking for overwrite_specials when 'one_side' used

utils/wesnoth-map-diff/package-lock.json
I have Dependabot PRs turned on in my fork, so it opened this against mine today, so I'm submitting it back upstream as well.
Bumps [tough-cookie](https://github.com/salesforce/tough-cookie) from 4.0.0 to 4.1.3.
- [Release notes](https://github.com/salesforce/tough-cookie/releases)
- [Changelog](https://github.com/salesforce/tough-cookie/blob/master/CHANGELOG.md)
- [Commits](https://github.com/salesforce/tough-cookie/compare/v4.0.0...v4.1.3)
---
updated-dependencies:
- dependency-name: tough-cookie
dependency-type: indirect
...
Signed-off-by: dependabot[bot] <support@github.com>
=> Bump tough-cookie from 4.0.0 to 4.1.3 in /utils/wesnoth-map-diff

vcpkg.json
Uses the same base-line that @Vultraz updated in master recently, in b50a8012ea000b47955a1c92283be9d88fd929b2. This updates to pango 1.50.14 (from 1.50.12) which resolves #7217 (but also introduces #7543).
I had to make the other changes (back-ported from master) to compile. Tested and verified on VS2019 (Win7) and VS2022 (Win10).
=> 1.16: Use same vcpkg base-line as current master

data/core/units/bats/Bat_Blood.cfg, data/core/units/bats/Bat_Dread.cfg, data/core/units/undead/Corpse_Ghast.cfg, data/core/units/undead/Corpse_Ghoul.cfg, data/core/units/undead/Corpse_Necrophage.cfg, data/core/units/undead/Necro_Ancient_Lich.cfg, data/core/units/undead/Necro_Dark_Sorcerer.cfg, data/core/units/undead/Necro_Lich.cfg, data/core/units/undead/Necromancer.cfg, data/core/units/undead/Skele_Banebow.cfg, data/core/units/undead/Skele_Bone_Shooter.cfg, data/core/units/undead/Skele_Draug.cfg, data/core/units/undead/Skele_Revenant.cfg, data/core/units/undead/Skeleton.cfg, data/core/units/undead/Spirit_Nightgaunt.cfg, data/core/units/undead/Spirit_Shadow.cfg, data/core/units/undead/Spirit_Spectre.cfg, data/core/units/undead/Spirit_Wraith.cfg
Changes:
Level1:
Skeleton - xp changed from 35 to 39. 
Ghoul - xp changed from 35 to 30. 
Blood Bat - cost changed from 22 to 23, xp changed from 70 to 37. 
Level 2:
Revenant - cost changed from 31 to 28, xp changed from 85 to 78.
Dark Sorcerer - cost changed from 33 to 34, xp changed from 90 to 110.
Shadow - cost changed from 38 to 44, xp changed from 100 to 77.
Wraith - xp changed from 100 to 90.
Necrophage - melee damage changed from 7 to 9, cost changed from 27 to 23, xp changed from 120 to 61.
Bone Shooter - cost changed from 26 to 24, xp changed from 80 to 60.
Dread Bat - cost changed from 34 to 32.
Level 3:
Draug - cost changed from 47 to 70.
Lich - cost changed from 50 to 90. 
Necromancer - ranged cold damage changed from 17 to 19, ranged arcane damage changed from 12 to 16, hp …
=> Balance for Undead 1.18

data/core/units/goblins/Direwolf_Rider.cfg, data/core/units/goblins/Pillager.cfg, data/core/units/goblins/Wolf_Rider.cfg, data/core/units/nagas/Fighter.cfg, data/core/units/nagas/Myrmidon.cfg, data/core/units/nagas/Warrior.cfg, data/core/units/orcs/Archer.cfg, data/core/units/orcs/Crossbowman.cfg, data/core/units/orcs/Nightblade.cfg, data/core/units/orcs/Slayer.cfg, data/core/units/orcs/Slurbow.cfg, data/core/units/orcs/Warlord.cfg, data/core/units/orcs/Warrior.cfg, data/core/units/trolls/Rocklobber.cfg, data/core/units/trolls/Troll.cfg, data/core/units/trolls/Warrior.cfg
Changes:
Level 1:
Archer - xp changed from 30 to 32.
Naga - xp changed from 32 to 33.
Wolf Rider - xp change from 30 to 34. 
Level 2:
Warrior - cost changed from 26 to 23, xp changed from 60 to 67.
Pillager - cost changed from 28 to 31. 
Troll - cost changed from 27 to 25, xp changed from 66 to 58. 
Rocklobber - ranged damage changed from 17 to 19, hp changed form 51 to 53. 
Naga Warrior - cost changed from 24 to 22, xp changed from 66 to 56.
Crossbowman - melee damage changed from 4 to 6, ranged pierce damage changed from 8 to 9, hp changed from 43 to 46, cost changed from 21 to 22, xp changed from 80 to 43.
Slayer - cost changed from 26 to 21, xp changed from 64 to 62.
Level 3:
Warlord - cost changed from 48 to 52.
Direwolf Rider - cost changed from 44 to 52. 
Troll Warrior - cost …
=> Balance for Northerners 1.18

data/core/units/dwarves/Dragonguard.cfg, data/core/units/dwarves/Fighter.cfg, data/core/units/dwarves/Guardsman.cfg, data/core/units/dwarves/Lord.cfg, data/core/units/dwarves/Sentinel.cfg, data/core/units/dwarves/Stalwart.cfg, data/core/units/dwarves/Steelclad.cfg, data/core/units/dwarves/Thunderer.cfg, data/core/units/dwarves/Thunderguard.cfg, data/core/units/gryphons/Gryphon_Master.cfg, data/core/units/gryphons/Gryphon_Rider.cfg, data/core/units/humans/Outlaw.cfg, data/core/units/humans/Outlaw_Assassin.cfg, data/core/units/humans/Outlaw_Footpad.cfg, data/core/units/humans/Outlaw_Fugitive.cfg, data/core/units/humans/Outlaw_Rogue.cfg, data/core/units/humans/Outlaw_Thief.cfg, data/core/units/humans/Woodsman_Huntsman.cfg, data/core/units/humans/Woodsman_Poacher.cfg, data/core/units/humans/Woodsman_Ranger.cfg, data/core/units/humans/Woodsman_Trapper.cfg
Changes:
Level 1:
Fighter - xp changed from 41 to 45.
Thunderer - xp changed from 40 to 35.
Guardsman - ranged damage increased from 5 to 6, xp changed from 47 to 40.
Footpad - xp changed from 36 to 35.
Thief - xp changed from 28 to 29.
Poacher - xp changed from 29 to 28.
Gryphon Rider - cost changed from 24 to 23, xp changed from 38 to 46.
Level 2: 
Steelclad - xp changed from 74 to 88.
Thunderguard - cost changed from 27 to 24, xp changed from 95 to 65.
Stalwart - hp changed from54 to 59, ranged damage changed from 8 to 9, xp changed from 85 to 78.
Outlaw - cost changed from 26 to 24, hp changed from 42 to 47, xp changed from 77 to 71.
Rogue - xp changed from 70 to 80, cost changed from 24 to 25.
Trapper - hp changed from 45 to 49, melee damage changed from 4 to 5, xp changed from 65 to …
=> Balance for Knalgan Alliance 1.18

data/core/units/dunefolk/Apothecary.cfg, data/core/units/dunefolk/Blademaster.cfg, data/core/units/dunefolk/Burner.cfg, data/core/units/dunefolk/Captain.cfg, data/core/units/dunefolk/Cataphract.cfg, data/core/units/dunefolk/Explorer.cfg, data/core/units/dunefolk/Falconer.cfg, data/core/units/dunefolk/Harrier.cfg, data/core/units/dunefolk/Herbalist.cfg, data/core/units/dunefolk/Horse_Archer.cfg, data/core/units/dunefolk/Raider.cfg, data/core/units/dunefolk/Rider.cfg, data/core/units/dunefolk/Rover.cfg, data/core/units/dunefolk/Scorcher.cfg, data/core/units/dunefolk/Skirmisher.cfg, data/core/units/dunefolk/Sky_Hunter.cfg, data/core/units/dunefolk/Soldier.cfg, data/core/units/dunefolk/Spearguard.cfg, data/core/units/dunefolk/Spearmaster.cfg, data/core/units/dunefolk/Strider.cfg, data/core/units/dunefolk/Sunderer.cfg, data/core/units/dunefolk/Swordsman.cfg, data/core/units/nagas/Ophidian.cfg, data/core/units/nagas/Ringcaster.cfg
Changes:
Level 1:
Burner - hp changed from 34 to 35, xp changed from 40 to 37.
Herbalist - cost changed from 14 to 13, xp changed for 39 to 36.
Rider - hp changed from 34 to 33, xp changed from 47 to 49.
Rover - hp changed from 32 to 33, xp changed from 43 to 40. 
Soldier - cost changed from 18 to 17, xp changed from 43 to 39. 
Skirmisher - xp changed from 34 to 39. 
Level 2:
Explorer - xp changed from 80 to 73.
Swordsman - cost changed from 30 to 28, xp changed from 75 to 68.
Capitan - cost changed from 30 to 29, xp changed from 75 to 74.
Spearguard - cost changed from 30 to 29, xp changed from 75 to 74.
Scorcher - ranged damage changed from 9 to 10, cost changed from 25 to 23, xp changed from 70 to 60.
Raider - cost changed from 34 to 35, xp changed from 70 to 77.
Swiftrider - xp …
=> Balance for Dunefolk 1.18

data/core/units/drakes/Arbiter.cfg, data/core/units/drakes/Armageddon.cfg, data/core/units/drakes/Blademaster.cfg, data/core/units/drakes/Clasher.cfg, data/core/units/drakes/Enforcer.cfg, data/core/units/drakes/Fighter.cfg, data/core/units/drakes/Fire.cfg, data/core/units/drakes/Flameheart.cfg, data/core/units/drakes/Flare.cfg, data/core/units/drakes/Glider.cfg, data/core/units/drakes/Hurricane.cfg, data/core/units/drakes/Inferno.cfg, data/core/units/drakes/Sky.cfg, data/core/units/drakes/Thrasher.cfg, data/core/units/drakes/Warden.cfg, data/core/units/drakes/Warrior.cfg, data/core/units/saurians/Ambusher.cfg, data/core/units/saurians/Flanker.cfg, data/core/units/saurians/Javelineer.cfg, data/core/units/saurians/Soothsayer.cfg, data/core/units/saurians/Spearthrower.cfg
Changes: 
Level 1:
Fighter - xp changed from 42 to 41.
Clasher - xp changed from 43 to 41.
Glider - xp changed from 35 to 39.
Level 2: 
Warrior - xp changed from 70 to 81, cost changed from 32 to 31. 
Arbiter - hp changed from 62 to 63, xp changed from 105 to 81.
Thrasher - xp changed from 95 to 77.
Flare  - xp changed from 80 to 86.
Fire - xp changed from 80 to 84.
Sky - xp changed from 80 to 76, cost changed from 28 to 32. 
Ambusher - hp changed from 36 to 38, cost changed from 24 to 22. 
Soothsayer - melee attack strikes changed from 2 to 3, mp changed from 6 to 7, cost changed from 25 to 28.
Spearthrower - melee damage changed from 6 to 5.
Level 3:
Blademaster - cost changed from 47 to 62.
Warden - cost changed from 46 to 62.
Enforcer - cost changed from 44 to 58.
Flameheart - cost …
=> Balance for Drakes 1.18

data/core/units/elves/Avenger.cfg, data/core/units/elves/Captain.cfg, data/core/units/elves/Champion.cfg, data/core/units/elves/Druid.cfg, data/core/units/elves/Enchantress.cfg, data/core/units/elves/Fighter.cfg, data/core/units/elves/Hero.cfg, data/core/units/elves/Marksman.cfg, data/core/units/elves/Marshal.cfg, data/core/units/elves/Outrider.cfg, data/core/units/elves/Ranger.cfg, data/core/units/elves/Rider.cfg, data/core/units/elves/Scout.cfg, data/core/units/elves/Sharpshooter.cfg, data/core/units/elves/Shyde.cfg, data/core/units/elves/Sorceress.cfg, data/core/units/elves/Sylph.cfg, data/core/units/merfolk/Entangler.cfg, data/core/units/merfolk/Hunter.cfg, data/core/units/merfolk/Javelineer.cfg, data/core/units/merfolk/Netcaster.cfg, data/core/units/merfolk/Spearman.cfg, data/core/units/wose/Ancient.cfg, data/core/units/wose/Elder.cfg
Level 1: 
Fighter - xp cost changed from 40 to 37.
Merman Hunter - xp changed from 35 to 33.
Scout - xp changed from 32 to 42.
Level 2: 
Hero - xp changed from 90 to 80.
Captain - xp changed from 90 to 85.
Marksman - cost changed from 31 to 34, xp changed from 80 to 80.
Ranger - xp changed from 90 to 85. 
Rider - ranged damage changed from 9 to 11, hp changed form 46 to 49, cost changed from 28 to 35, xp changed from 53 to 75.
Druid - cost changed from 27 to 25, xp changed from 80 to 85.
Sorceress - cost changed from 32 to 34, xp changed from 100 to 90. 
Elder Wose - cost changed from 27 to 28, xp changed from 100 to 80.
Merman Netcaster - cost changed from 27 to 26, xp changed from 85 to 54.
Merman Spearman - cost changed from 27 to 22, xp changed from 85 to 54.
Level 3:
Champion - melee …
=> Balance for Rebels 1.18

data/campaigns/World_Conquest/lua/game_mechanics/unittypedata.lua
These didn't have context in the .po files, so this makes clear which unit is joining.
The Ulf and Ghoul are special, a couple of others get a bit more detail about British slang.
=> [1.16] WC: add po hints to the messages when units join

data/campaigns/World_Conquest/lua/game_mechanics/unittypedata.lua
Add to 1.17 the po hints that #7716 adds to 1.16, and fix the issues of #7718.
Drake Fighters now say "blade" instead of "sword".
Remove the response when a human finds an Ulf, because it didn't sound right as the first thing a human says to a dwarf. The Ulf’s "a good day to die" could be read as a Native American battlecry, and "brave words" as "words of an Indian Brave", leaving the "little big man" to sound like a name.
Without catching the culture reference, it came across as a jibe about the dwarf's height.
Catching the culture reference, the logic seems reversed. Why would another dwarf use the generic form, but a human feel comfortable saying that?
=> WC: change some messages when units join, and add po hints

changelog.md
Left out movement point changes of `Elvish Outrider` and `Saurian Soothsayer` as that PR has not been merged yet.
=> update missing entries for 1.17.19 changelog

data/campaigns/World_Conquest/lua/campaign/objectives.lua
=> WC II - Typo and translatability of Difficulty and Version

.github/workflows/ci-main.yml, src/editor/map/map_context.cpp
Based on some feedback, doing a `git checkout` may help with the frequent cache misses of the vcpkg dependencies.
=> Re-enable Windows CI jobs

src/editor/map/context_manager.cpp, src/editor/map/map_context.cpp, src/gui/dialogs/editor/choose_addon.cpp
F5 causing the editor to crash - the editor saves temporary files out to disk which don't have an extension, so give them the proper extension
The add-on selection dialog showing non-add-on folders in the add-ons folder - only show files with a _main.cfg
=> Fix parts of #7810

src/play_controller.cpp
previously the code that tried to activate the whiteboard failed because it checks `can_modify_game_state` which checks for `!synced_context::is_unsynced`
=> Fix #7820 "Enable planning mode on start" Setting

.github/workflows/ci-main.yml
Using the version from 2 days ago, as that avoids an update to CMake, and I want to look at one issue at a time.
=> Update vcpkg baseline to include glib's build fix

data/schema/core/addons.cfg, data/test/scenarios/wml_tests/ScenarioWML/EventWML/events-test_priority_lua1.cfg, data/test/scenarios/wml_tests/ScenarioWML/EventWML/events-test_priority_lua2.cfg, data/test/scenarios/wml_tests/ScenarioWML/EventWML/events-test_priority_wml1.cfg, data/test/scenarios/wml_tests/ScenarioWML/EventWML/events-test_priority_wml2.cfg, data/test/scenarios/wml_tests/ScenarioWML/EventWML/events-test_priority_wml3.cfg, data/test/scenarios/wml_tests/ScenarioWML/EventWML/events-test_priority_wml4.cfg, src/game_events/handlers.cpp, src/game_events/handlers.hpp, src/game_events/manager.cpp, src/game_events/manager.hpp, src/game_events/manager_impl.cpp, src/game_events/manager_impl.hpp, src/game_events/menu_item.cpp, src/scripting/game_lua_kernel.cpp, utils/emmylua/wesnoth/game_events.lua, wml_test_schedule
For any given event name, events execute in order of decreasing priority.
Priority is a real number, and may be assigned via the `priority` attribute for
the WML ``[event]`` tag, or through the Lua APIs:
- ``wesnoth.game_events.add({priority = number})``
- ``wesnoth.game_events.add_repeating(name, action, [priority])``
Note that delayed variable substitution is not currently supported in the WML attribute.
Fixes #7582
=> Implement event priority

src/units/abilities.cpp
…
when selecting a unit with an active ability only when adjacent to another, it marks active when the cursor is placed next to it
and with https://github.com/wesnoth/wesnoth/pull/7805 it's the problem of displaying the halo with an ability that only affects adjacent units, in this case the owner briefly displays the halo when he moves to side of a unit meeting the conditions
=> fix self-detecting unit issue in abilities [affect_adjacent] and [fiter_adjacent]

changelog_entries/atotb_amulets.md, data/campaigns/Two_Brothers/scenarios/01_Rooting_Out_a_Mage.cfg, data/campaigns/Two_Brothers/scenarios/04_Return_to_the_Village.cfg, data/campaigns/Two_Brothers/utils/bigmap.cfg
Having these in canon felt like a plot hole in other campaigns. If an apprentice mage could make these amulets circa 350 YW then every village and border-fort should have them, but Wesnoth's storylines work better if a messenger on horseback is the usual method of long-distance communication. For example, TSG is about a commander sent to discipline a lazy outpost, only to find that they should have brought reinforcements. When it's the enemy trying to communicate, DM S21 and UtBS S08 both involve stopping the messengers.
This changes the intro to have a beacons for communicating with the trade caravans, I'm leaving it ambiguous whether it's a smoke signal or a fire signal. Fire beacons might make more sense if the village sees the caravan's campfires at night and, in normal usage, light …
=> AToTB: Remove the instant-communication amulets

changelog_entries/ArcaneResistancesRework.md, data/core/macros/movetypes.cfg, data/core/units.cfg, data/core/units/humans/Horse_Paladin.cfg, data/core/units/humans/Mage_White.cfg, data/core/units/humans/Mage_of_Light.cfg, data/core/units/undead/Necro_Lich.cfg
Smallfoot, armoredfoot, elusivefoot, mounted,  fly, smallfly, lightfly, deepsea, mountainfoot, gurefoot, rodentfoot, lizard, dunefoot, duneelusivefoot, dunearmoredfoot, dunehorse, dunearmoredhorse - arcane resistance changed from 20% to 10%. 
Treefolk - arcane resistance changed from -30% to -20%.
Undeadfoot - arcane resistance changed from -50% to -20%.
Undeadfly - arcane resistance changed from -40% to -20%.
Drakefly, drakeglide, drakeglide2, drakefoot - arcane resistance changed from -30% to -10%.
Float ???
Paladin - arcane resistance changed from 60% to 30%.
White mage - arcane resistance changed from 40% to 30%.
Mage of Light - arcane resistance changed from 60% to 50%.
Lich - arcane resistance changed from -40% to -20%.
@nemaara kinda lore changes, paladin no longer is on a level of …
=> Arcane Resistances Rework

data/lua/wml/micro_ai.lua, data/schema/core/actionwml.cfg
~~It can take a list as of this commit: https://github.com/wesnoth/wesnoth/commit/0bd679b11c8a5bf6b2b2c0a38ee2250b9736de77~~
~~From @CelticMinstrel on IRC/Discord:~~
> It's likely another case of "we want to encourage the use of filters going forward" that didn't make it into the schema because it > was complicated to handle it correctly.
> Looking closer, I guess I was wrong. It doesn't actually support a filter for the sides.
> BTW, s_unsigned_range_list is incorrect. It doesn't support ranges, so it would have to be s_unsigned_list.
> Unless of course you want to make it support ranges, which is valid.
> I don't know how useful it is. There aren't so many sides in a normal scenario that I'd find ranges to be useful.
> Maybe it's s_uint_list actually.
~~Have to agree checking for a …
=> Add range support for [micro_ai]side=

data/multiplayer/maps/4p_King_of_the_Hill.map, data/multiplayer/scenarios/4p_King_of_the_Hill.cfg
The premise of this venerable mainline map was always for players to fight over the central hilltop castle. Yet its scenario gave no perks to combat the downsides of taking the hill:
- No recruiting while leader is traveling there.
- Leader vulnerable while traveling.
- Hill surrounded by enemies on multiple sides.
This update adds a powerful perk to hopefully make the hill worth fighting over.
~~When a leader sits on the hill keep, all other castles collapse into ruins so that no other side can recruit. Only if this leader (the king) is assassinated or abdicates his hilltop throne will the other castles be restored. To make the situation more clear, there is no fog or shroud on the hill, so that all players can see some of what goes on there at all times.~~
~~[Forum Development …
=> Add game logic to King of the Hill scenario

changelog_entries/crash_inspect_page.md, src/gui/dialogs/gamestate_inspector.cpp
Switching to a different item cleared the data, but didn't clear the cache of where the page breaks are located. The subsequent call to `get_data_paged(int which_page)` has a bounds check for the page number, so it's sufficient to just clear the page breaks, which is already ok as it resets the object to the same state as a newly-created instance.
Fixes (on 1.16) #7851. Will be forward-ported to master, as the bug will definitely exist on master too, however I'm unable to trigger the page-change buttons to appear on master (possibly a side-effect of #7565).
=> [1.16] Fix a crash in :inspect when switching from page 2 to a different item

changelog_entries/crash_inspect_page.md, src/gui/dialogs/gamestate_inspector.cpp
Switching to a different item cleared the data, but didn't clear the cache of where the page breaks are located. The subsequent call to `get_data_paged(int which_page)` has a bounds check for the page number, so it's sufficient to just clear the page breaks, which is already ok as it resets the object to the same state as a newly-created instance.
Forward-ported to fix #7851, but currently untestable in master, as the page-selection buttons are only shown when there's a large amount of text, which triggers the known regression (the credits-crash bug).
(cherry picked from commit 7cb5f09bcf0de4b5a2cc26a593cffa2d5cfbcd14)
=> Fix a crash in :inspect when switching from page 2 to a different item

changelog_entries/low_gold_carry_over.md, data/campaigns/Legend_of_Wesmere/scenarios/chapter3/09_Bounty_Hunters.cfg, data/campaigns/Legend_of_Wesmere/scenarios/chapter3/11_Battle_of_the_Book.cfg, data/campaigns/Legend_of_Wesmere/scenarios/chapter4/14_Human_Alliance.cfg
So it looks like when I made #7248 I wasn't aware of - or had forgotten about - the distinction between 'old' and 'new' style gold carry-over. Like that PR, this potentially disrupts the gold balancing again, but this time in the player's favour. My assumption was the changes that led to both #7230 and #7862 being reported were intended to change the entire campaign to the 'new' style carry over at the standard 40% rate. If that assumption is incorrect, then some other means of sorting out the gold carry-over inconsistency needs to be decided upon.
Otherwise resolves #7862.
=> LoW: Replace lingering instances of ‘old’ style gold carry over

data/core/help.cfg, data/gui/window/addon_manager.cfg, data/gui/window/editor_edit_pbl.cfg, data/gui/window/editor_edit_pbl_translation.cfg
* Removed duplicated  'to display' text
* Favour generic term 'file manager' over Microsoft terminology.
* Clarify language code use - though I'm not actually sure what language code convention Wesnoth follows. Please correct as necessary.
* Replace inconsistent spelling of 'add-on'. It looks like older instances use the single-word form 'addon' (which I don't think is right) and that 'add-on' is currently the intended spelling in Wesnoth's context. I verified this by checking the `en_US` language option.
* There are a couple of lingering instances I left alone because the line they were in had been disabled-via-comment (and should probably just be deleted).
=> wesnoth-lib review

src/game_launcher.cpp
this commit handles the load_game_exception thrown when the user presses the button to load a specific turn.
=> fix #2648: allow load turn in local multiplayer

src/ai/default/recruitment.cpp
in the previous logic some cases return from the function and others would set a return variable that would be set later.
this commit, changes all the cases into all returns so that other cases added in the future should not avoid caching.
right now there are no ways to avoid the caching which should be the expected behaviour (unless explicitly added the case where cache is unwanted)
=> fix #7821: all cases of the calculation should be cached

data/campaigns/Eastern_Invasion/utils/abilities.cfg
Minor tweak to EI.
Mal-Ravanal and Khrakrahs have the "terror" ability, reducing the damage of nearby enemies.  The custom "survivor" trait (found on a number of scripted units) grants immunity, but these units are numerous and I feel this devalues the "terror" ability.  This PR removes survivors' terror immunity.
=> EI: "survivor" trait no longer grants "terror" immunity

INSTALL.md, vcpkg.json
When I was compiling on Windows, I got an error:
```text
[cmake] CMake Error at D:/program/cmake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
[cmake]   Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
```
PkgConfig installation is quite troublesome in Windows, but vcpkg provides it for us, so we only need to add the following line in `vcpkg.json` to automatically add Pkgconfig during Windows build:
```json
{
"name": "pkgconf",
"platform": "windows"
}
```
=> add `"pkgconf"` to `vcpkg.json`

changelog_entries/extent_remove_ability_efect_to_attribute_changelog.md, data/core/macros/utils.cfg, data/schema/filters/abilities.cfg, data/schema/units/abilities.cfg, data/schema/units/specials.cfg, data/test/scenarios/macro_tests/test_force_chance_to_hit_macro.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/test_overwrite_specials_filter.cfg, src/units/abilities.cpp, src/units/attack_type.hpp, src/units/unit.hpp, src/utils/general.hpp, wml_test_schedule
Since I add another feature to overwrite_specials in addition to filtering with the priority system, which obviates the need to limit its use to abilities used as weapons, I prefer to open this query to group the main commits that are related to it .
=> Add priority and filter to overwrite specials

data/schema/filters/abilities.cfg, data/schema/game_config.cfg, data/test/scenarios/wml_tests/ScenarioWML/EventWML/events-test_filter_ability.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/test_overwrite_specials_filter.cfg, src/units/unit.cpp
This addresses #7944 without addressing #7923. The code and schema changes are a subset of #7924, the test changes are a subset of those in #7924 with an extra assert added on top. I think #7924 should probably be merged, but there's a few changes still under discussion, and so it would be worth merging this and then rebasing to reduce the size of #7924.
There are questions about how `[filter_ability]type_value=` should treat empty values. The use cases that we can think of can be implemented in other ways, for example, if we want to look for big damage boosts, then we could filter for `add=5-infinity` `[or]` `multiply=2-infinity`. The simple answer seems to be to remove `type_value=` from the API before we freeze for 1.18.
Make the ability filter tests stricter. With the default …
=> Remove [filter_ability]type_value=

data/lua/core/game_events.lua, data/lua/diversion.lua, data/lua/on_event.lua, data/lua/wml-tags.lua, src/actions/undo_action.cpp, src/actions/undo_action.hpp, src/game_events/action_wml.cpp, src/scripting/game_lua_kernel.cpp, src/scripting/game_lua_kernel.hpp, src/synced_context.cpp, src/synced_context.hpp, utils/emmylua/wesnoth/game_events.lua
This fixes the issue of the new events API not allowing a way to make events undoable, beyond calling into the corresponding WML actions.
The API additions are:
* `wesnoth.game_events.set_undoable` sets whether or not the current event can be undone.
* `wesnoth.game_events.add_undo_actions` adds actions to be performed when the current event is undone. Can be either a Lua function or a table of ActionWML.
* `wesnoth.game_events.add_repeating` takes an optional third argument which a function to call on undo, which automatically marks the event undoable. (Or it was supposed to, I think I actually missed that.)
There are a couple of things missing – the above parenthetical, and what to do when serializing an undo stack that contains a Lua function. Obviously it's not going to work, but we …
=> Lua API to the undo system

data/schema/filters/abilities.cfg, data/schema/game_config.cfg, data/test/scenarios/wml_tests/ScenarioWML/EventWML/events-test_filter_ability.cfg, src/tests/test_config_filters.cpp, src/units/unit.cpp, src/utils/config_filters.cpp, src/utils/config_filters.hpp, wml_test_schedule
Fix https://github.com/wesnoth/wesnoth/issues/7923 .when we want to detect an ability with value=0-20 and an ability with add=15 is present, this is detected because the system assigns a value of 0 when 'value' is not present, and so the system matches abilities that do not use 'value' or even no numerical value at all. it is therefore necessary to decide that the absence of an attribute is a non-correspondence to the criteria.
=> repair detects non-existent default attribute value in numérical attribute

src/reports.cpp
I merged #7920, missing @soliton- 's comment that - "Actually I get an out of range exception in the editor when hovering over a village. In scenario mode it works fine. I'm guessing the owner_team stuff needs checking."
This is the fix, and most of it is just a whitespace change for the extra level of indentation.
=> Fix crash when mousing over a village in the terrain editor

data/campaigns/World_Conquest/lua/campaign/scenario.lua
a free random training on easier difficulties should only be given in the first scenario. (Otherwise they'll accumulate to 5 free trainings at scenario 5.)
=> WC: fix #7921 Random training per scenario

src/mouse_events.cpp, src/mouse_events.hpp, src/mouse_handler_base.cpp, src/mouse_handler_base.hpp, src/scripting/game_lua_kernel.cpp, src/scripting/game_lua_kernel.hpp
This is a flexible event handler mechanism to allow for more advanced add-on features. It does not allow the add-on to consume the value however, so there's no mechanism for the add-on to requrest the default action not be executed.
We would normally deal separately with mouse down, up and click, with the later being an event where the mouse has gone both down and up on the same UI component. However, Wesnoth's code seems to allow a mouse up on many UI components to serve as a click, so this implementation follows that behavior.
This addresses issue #7949
I'm still in the process of testing, but would like to get this in before the freeze!
=> Add lua mouse button event handler

changelog_entries/fix_add_start.md, src/replay.cpp
With this it puts the player back to the title screen after showing an error dialog, so it's not much better, but at least it's not a crash.
Fixes #7164
We weren't able to work out what caused the file corruption reported, but I believe it's a race condition about saving while the AI is recruiting. The file in the bug report has a `[snapshot]` tag with `init_side_done=yes` but without a `playing_team` attribute, which must be the result of `game_state::write()` when not in the `PLAY` phase. Loading such a file causes `game_state::start_event_fired_ == false`, and triggers `play_controller::start_game` to call `replay::add_start_if_not_there_yet`.
The i18n'd string is reused from `game_launcher.cpp`.
=> Avoid an assert in replay::add_start_if_not_there_yet with corrupt files

src/gui/widgets/widget.cpp
Fixes #7617
widget::set_origin should probably also call queue_redraw(), not fully sure yet though.
=> also invalidate previous location when resizing a widget

changelog_entries/[damage]_special_changelog.md, data/campaigns/Dead_Water/scenarios/08_Talking_to_Tyegea.cfg, data/campaigns/Delfadors_Memoirs/scenarios/14_Shadows.cfg, data/campaigns/Delfadors_Memoirs/scenarios/19_Showdown_in_the_Northern_Swamp.cfg, data/campaigns/Delfadors_Memoirs/scenarios/22_Face_of_the_Enemy.cfg, data/campaigns/Eastern_Invasion/utils/items.cfg, data/campaigns/Heir_To_The_Throne/scenarios/05b_Isle_of_the_Damned.cfg, data/campaigns/Heir_To_The_Throne/scenarios/09_The_Valley_of_Death.cfg, data/campaigns/Northern_Rebirth/scenarios/05a_01_The_Pursuit.cfg, data/campaigns/The_Rise_Of_Wesnoth/scenarios/06_Temple_in_the_Deep.cfg, data/campaigns/The_Rise_Of_Wesnoth/scenarios/17d_Cursed_Isle.cfg, data/campaigns/Under_the_Burning_Suns/scenarios/02_Across_the_Harsh_Sands.cfg, data/campaigns/Under_the_Burning_Suns/scenarios/03_Stirring_in_the_Night.cfg, data/campaigns/World_Conquest/resources/data/artifacts.cfg, data/campaigns/World_Conquest/resources/data/training.cfg, data/core/macros/items.cfg, data/core/macros/weapon_specials.cfg, data/schema/filters/weapon.cfg, data/schema/units/specials.cfg, data/test/scenarios/manual_tests/scenario-test.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/special_damage_type.cfg, src/gui/dialogs/attack_predictions.cpp, src/gui/dialogs/unit_attack.cpp, src/movetype.cpp, src/reports.cpp, src/units/abilities.cpp, src/units/attack_type.cpp, src/units/attack_type.hpp, src/units/unit.cpp, wml_test_schedule
At the suggestion of @stevecotton, I propose a special 'type' and 'added_type' attribute in [damage] capable of modifying the type of attack used when the conditions are met.
=> add a 'replacement_type' and 'alternative_type' attribute in [damage] special or ability who modify the type of attack used

data/campaigns/Eastern_Invasion/_main.cfg
Changes Editor terrain Group Icon from "UMC" to "Mainline".
Well, a mainline campaign should not have the UMC terrain group icon. Just looks odd in the terrain group listings.
=> [Campaigns][Eastern Invasion] fix editor group icon

data/core/units.cfg
- feral wolves do not get names (but wolf riders do, and that's supposed to be true)
- Ants do not get names
- scorpion do not get names
- bears do not get names
- bats do not get names
- Roc does not get name
- falcons and ravens get names which is unusual
- horses do not get names
- Falcons and Ravens should not get names.
This pull request does this.
=> [Units] update falcon and raven races to not get names

src/addon/state.cpp
=> Don't treat an add-on as published if it has no version attribute.

src/saved_game.cpp
including scenarios generated by the editor was the main usecase for this
=> Fix include_file= not being able to handle cfg files generated by the editor

src/events.cpp, src/video.cpp
This just brings the custom resize event that can be fired in line with the change made in ac96df07bebbfc5d494f7325b89aa42ad4e567a9 .
The only thing that uses this event is the pixel scale slider which fires it manually when changed, as the window size doesn't actually change but the UI still needs to be regenerated.
This fixes the display updating incorrectly when changing pixel scale in prefs. (which i haven't reported because i just fixed it in stead)
=> Fix UI update when changing pixel scale in preferences

data/gui/widget/panel_story_viewer.cfg, data/gui/widget/panel_wml_message.cfg, src/draw.cpp, src/draw.hpp, src/gui/core/canvas.cpp, src/gui/core/canvas.hpp, src/gui/widgets/grid.cpp, src/gui/widgets/minimap.cpp, src/gui/widgets/minimap.hpp, src/gui/widgets/multi_page.cpp, src/gui/widgets/multi_page.hpp, src/gui/widgets/panel.cpp, src/gui/widgets/panel.hpp, src/gui/widgets/spacer.cpp, src/gui/widgets/spacer.hpp, src/gui/widgets/styled_widget.cpp, src/gui/widgets/styled_widget.hpp, src/gui/widgets/toggle_panel.cpp, src/gui/widgets/toggle_panel.hpp, src/gui/widgets/widget.cpp, src/gui/widgets/widget.hpp, src/gui/widgets/window.cpp, src/gui/widgets/window.hpp, src/sdl/point.hpp, src/video.cpp, src/video.hpp
I haven't done much (or any, really) testing on this, but it should solve #7615 
I verified that it does reduce CPU usage when opening the Load Game screen while in the tutorial.
I'm not sure if there might be rendering bugs in other areas. But the basic system is straightforward. It just renders windows to offscreen render textures when they change, and doesn't do any more work unless it needs to. When the window needs to be redrawn, it just blits from this texture without actually redrawing anything.
Renders should be minimal, and it's using all the same draw code so actually very little has changed.
=> Offscreen window rendering

src/display.cpp, src/display.hpp
Fixes #6922
Just hides the buttons until the game has started. There was already a function to cause the game map not to draw while the story screen was showing, so i just used that as the cue for unhiding the buttons.
There is some weirdness with the buttons under the minimap appearing at different times. But that seems to be a separate issue, and unrelated.
=> Start game with theme buttons hidden.

src/draw_manager.cpp, src/draw_manager.hpp, src/gui/core/canvas.cpp, src/gui/core/canvas.hpp, src/gui/dialogs/story_viewer.cpp
I didn't like that the blur effect required two frames to render, so i implemented basic multipass rendering. That is, while rendering, anything can request that another rendering pass is performed before flipping to the screen. This means the blur can render the thing behind it, blur that, then render itself, all in the same frame.
Theoretically this would also work for multiple layered blurs, rendering in three or more passes. But try not to do that as it's expensive, and will probably drop frames on weak hardware.
I also noticed while testing that the story screen text panels now have blur, and it wasn't updating, so i forced it to regenerate the blur at each step. Without the multipass rendering, this causes a one-frame flicker which was pretty much unacceptable. It looks pretty good …
=> Multipass rendering

src/display.cpp, src/game_launcher.cpp, src/tests/utils/fake_display.cpp, src/video.cpp, src/video.hpp, src/wesnoth.cpp
It does require a rendering context now.
I added a new fake video mode that just does everything as normal except with the main window hidden.
Also renamed the `video::fake` enum entries for a bit more clarity.
It seems to work for me. I'm not sure how it would work on a headless system, but i think anything that can run the unit tests should be able to do `--screenshot` as well.
=> Fix the --screenshot commandline arg

src/server/common/dbconn.cpp
---
Not sure if this makes sense to keep after the performance issue is resolved or not, but the goal is:
* log the actual SQL statement being run, to make sure it matches what I think it should.
* log between the individual steps so it's clear which is taking up too much time.
=> add some logging to game history query

data/game_config.cfg, src/display.cpp, src/game_config.cpp
Zoom scales, which are described in draw-space pixels, were always required to be multiples of 4. This was violated at some point, resulting in graphical glitches when drawing fog at some zoom levels.
This both checks that zoom scales are divisible by four, and changes the zoom level specification to integers rather than multiplication factors so that they can be specified accurately.
This *also* fixes an auxiliary problem that the 1/3x zoom level specified as "0.33333333333333333" was incorrectly rounding to 23 in stead of 24, resulting in more graphical glitches.
This is related to #6959 but won't fix it entirely as that's a separate problem. The 1/3x zoom level is likely improved however.
These are the types of glitches fixed by this change. They are only obvious in fog, as that …
=> Fix overlapping fog texture at some zoom levels

changelog_entries/help_duplicate_images.md, src/help/help_topic_generators.cpp
If a unit type has male and female versions, then two images of the unit are displayed at the top-left of the help page. However, it did this even if the two images were the same, which made the duplication look like a bug.
The Naga Fighter is one of the affected unit types.
This was reported in the [WoF discussion about female drakes](https://r.wesnoth.org/p684546), and I was in the middle of logging a "good first issue" bug when I realised it was just a one-liner.
Screenshot **without** the fix:
=> Help Browser: only show one image if male and female are the same

src/gui/dialogs/gamestate_inspector.cpp
This doesn't fix the underlying issue with labels trying to show text too long to be rendered, but it does at least make the text show up now.
Fixes #7565, not sure about the other inspector related issues.
=> Quick hack to get the gamestate inspector working again.

changelog_entries/[damage]_special_changelog.md, data/campaigns/Under_the_Burning_Suns/scenarios/03_Stirring_in_the_Night.cfg, data/core/macros/weapon_specials.cfg, data/schema/filters/abilities.cfg, data/schema/filters/weapon.cfg, data/schema/units/abilities.cfg, data/schema/units/specials.cfg, data/test/scenarios/wml_tests/ScenarioWML/EventWML/events-test_filter_attack_type.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/special_damage_type.cfg, src/gui/dialogs/unit_attack.cpp, src/units/abilities.cpp, src/units/attack_type.cpp, src/units/attack_type.hpp, src/units/unit.cpp, src/units/unit.hpp, wml_test_schedule
To respond to an objection from @CelticMinstrel in https://github.com/wesnoth/wesnoth/pull/7865#issuecomment-1784239363, I moved alternative/replacement_type in matches_ability_filter and checking will be done with the 'type' filter in attack_type ::matches_filter() with security, if the function is called from a weapons specials([filter_self/opponent][filter_weapon]) then the type encoded in [damage] will not be checked to avoid a recursive loop.
=> replace alternative/replacement_type with 'type' in [filter_attack/weapon]

data/campaigns/Eastern_Invasion/utils/items.cfg
During the transition from add-on to mainline, EI's Sentinel Shield item's behavior got broken. This fixes it.
=> EI - Sentinel Shield Bugfix

data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/heal.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/heal_with_filter.cfg, wml_test_schedule
The ability's code in UtBS hasn't changed since 1.16, but there's now bug #8037 about healing sometimes not working in UtBS S02. The new test was written to check for an engine bug when a healer has two units next to it, only one of which passes the filter. Although the test is passing, it seems reasonable to keep the test.
Also, use `{ASSERT ...}` for better logging in the old healing test.
=> New unit test for UtBS-style [heals] with a filter

data/schema/filters/unit.cfg, data/schema/units/modifications.cfg, data/test/scenarios/wml_tests/ScenarioWML/EffectWML/test_remove_ability_by_filter.cfg, data/test/scenarios/wml_tests/ScenarioWML/EventWML/events-test_filter_ability.cfg, src/units/filter.cpp, src/units/unit.cpp
because it is experimental the tag of filter is changed except for [overwrite][filter_specials]
a bug is fixed also for case or ability diffrent of drains, berserk etc in checking 'value' attribute
=> rename [filter_ability(_active)] to experiemental_ability

src/units/unit.cpp
For me (and this is not the opinion of @soliton-) when we check the value of the value attribute,
we seek to verify that the value encoded in ability (or possibly the default) corresponds,
the value by default means that the value attribute is encoded with this default value, that's it.
Apparently @soliton- understood that it was the returned value that was checked and
I let myself get into this error which I am now correcting.
currently absence of default value is only detected when other numeric attributes are used, this commit is here to repair this rather unfortunate oversight.
=>  remove checking for the presence of add, sub etc. attributes when check value.

src/sdl/window.cpp
Resolves #8038 by requesting Direct3D v11 over the default Direct3D v9 on Windows platforms.
According to https://discourse.libsdl.org/t/a-couple-of-questions-regarding-batching-in-sdl-2-0-10/26453/2, `SDL_HINT_RENDER_DRIVER` implies `SDL_HINT_RENDER_BATCHING=0`. I tested `SDL_HINT_RENDER_BATCHING=1` on Windows and Linux and was not able to replicate #4237 nor #4245 (I was never able to replicate the related #4309). Given the rendering work I think disabling batched renders is no longer necessary.
I suppose we could force `SDL_HINT_RENDER_BATCHING=1` on Windows as well just for consistency but Wesnoth isn't exactly a demanding application in terms of rendering. If someone with sufficiently low-end hardware can demonstrate a significant difference between batched and non-batched renders, …
=> Update SDL render hints

src/gui/dialogs/campaign_selection.cpp, src/gui/dialogs/campaign_selection.hpp
A Linux packaging issue has, for apparently multiple years now, resulted in Wesnoth getting installed with only the tutorial campaign available. So, check for that and alert the player that there's an issue so they don't think Wesnoth actually only has a tutorial available.
Fixes #7875
=> Show an error when mainline campaigns are missing.

data/schema/units/specials.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/test_overwrite_specials_filter.cfg, src/units/abilities.cpp
Since it calls into the same code as [filter_ability] did.
=> [filter_specials] -> [experimental_filter_specials]

vcpkg.json
Works around #7543 for MSVC developers but does not resolve it as the official Wesnoth Windows builds do not use MSVC or vcpkg.
Only necessary for 1.16 because 1.17+ uses fontconfig.
=> Work around #7543 for 1.16

data/core/units/drakes/Arbiter.cfg, data/core/units/drakes/Armageddon.cfg, data/core/units/drakes/Blademaster.cfg, data/core/units/drakes/Burner.cfg, data/core/units/drakes/Clasher.cfg, data/core/units/drakes/Enforcer.cfg, data/core/units/drakes/Fighter.cfg, data/core/units/drakes/Fire.cfg, data/core/units/drakes/Flameheart.cfg, data/core/units/drakes/Flare.cfg, data/core/units/drakes/Glider.cfg, data/core/units/drakes/Hurricane.cfg, data/core/units/drakes/Inferno.cfg, data/core/units/drakes/Sky.cfg, data/core/units/drakes/Thrasher.cfg, data/core/units/drakes/Warden.cfg, data/core/units/drakes/Warrior.cfg
This (should) solve the issue raised by Antro of the Italiano translation team [on the forums](https://forums.wesnoth.org/viewtopic.php?p=684505#p684505). Basically, some languages have no neuter gender or cannot use it for unit names without sounding very awkward. So if any drake character is female, then its `unit_type` must also have a translatable string available for the female version of its name.
As with the naga race, there is no need for new sprites to be created for female variations of drake units. Since our real life audience is entirely made up of humans, they will not be able to tell the difference between male and female dragons anyway. :p
Additionally, this enables the long unused female drake name list and name generator to be used for recruited and randomly spawned …
=> Add female name strings for drake units

data/campaigns/Under_the_Burning_Suns/_main.cfg
Let players see what to expect when looking through the campaign menu, instead of only giving players this information after they start the campaign and have no clear or quick way to return to the main or campaign selection menus.
The cherry-picks text from both the commits and the review comments of #8027, and fixes part (but not all) of #8009.
The preceding translatable string includes trailing newlines, but is the same as 1.16. So I've left that as-is, while using a separate non-translatable string for the new string's newlines.
=> UtBS: Mention the campaign mechanics in the campaign description

src/draw.cpp, src/draw.hpp, src/gui/widgets/window.cpp, src/minimap.cpp
This might fix #8061 ... in any case `fill(0,0,0,0)` wasn't doing what it was supposed to.
I added a `draw::clear()` function to clear the current render target / fill it with transparency, as semi-transparent fills are being used in a few places and i don't want to change how they work.
=> Add (and use) a drawing function to clear the current render target

data/gui/window/title_screen.cfg, src/gui/core/canvas.cpp, src/gui/core/canvas.hpp, src/gui/dialogs/title_screen.cpp
This adds a check to regenerate blur whenever the screen region of the blur changes. This should catch most cases of moved and resized widgets.
It also explicitly regenerates the title screen blurs when the prefs dialog is closed. Otherwise the regenerated blurs will include the prefs dialog that's sitting on top.
Fixes #8023
=> Update title screen widget blur when resizing the game window

src/mouse_events.cpp
Implemented TODO* in `mouse_handler::drag_threshold()`
Changes the drag threshold from 14 to be based on window resolution. Scaling is performed so that a 1080p window has the original threshold of 14 (since 1080p is currently the most popular monitor size and I assume people are mostly playing Wesnoth in full screen mode). 
*Note that I haven't used the physical screen size because I imagine that it would be impractical to maintain cross-platform, and probably it isn't a good measure of user perceived drag distance anyway (eg. you hold a phone much closer to your face than a laptop). 
The main use case for this is ensuring that on very high resolution displays the drag distance is still reasonable. 
Tangentially related to issue #7955
Closely related to issue #8071
=> Adaptive drag threshold

changelog_entries/preprocess_non_cfg.md, src/serialization/preprocessor.cpp
The changed function is only called when using --preprocess, but calls itself recursively. This moves the filename filter to be around the recursive call, thus skipping the check for the top-level call.
Fixes #7654.
Ping @ProditorMagnus
=> Allow wesnoth --preprocess to work on files without the .cfg extension

src/chat_events.cpp, src/commandline_options.cpp, src/commandline_options.hpp, src/deprecation.cpp, src/game_config.cpp, src/gui/dialogs/log_settings.cpp, src/log.cpp, src/log.hpp, src/server/campaignd/options.cpp, src/server/campaignd/options.hpp, src/server/campaignd/server.cpp, src/server/wesnothd/server.cpp, src/tests/test_commandline_options.cpp, src/tests/test_unit_map.cpp, src/wesnoth.cpp
Refactored all relevant code to use `lg::severity` Enum instead of `int` type. 
A nice-to-have prerequisite for issue #7894 (not technically required but would be nice).
=> lg::severity Enum refactoring

.gitignore
I've written my previous PR using VSCode with the Clangd extension after generating a compile_commands.json file. This environment creates the .cache/clangd [index](https://clangd.llvm.org/design/indexing) directories.
I've decided to request this change as well to help future users and to reduce the need of editing .gitignore locally when contributing more in the future.
=> Add clangd cache directory to gitignore

src/gui/dialogs/preferences_dialog.cpp
Trying to open the preferences dialog when a theme from an addon was selected that is not currently in use asserts in menu_button::set_values.
=> Use index 0 when current theme is not found

data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/resistance_value.cfg, src/units/unit.cpp, wml_test_schedule
Fix https://github.com/wesnoth/wesnoth/issues/8092 issue.
If none [resistance] ability of the list contain max_avlue, on default value of 100 is used instead.
=> Fix [resistance] without max_value bug

data/lua/on_event.lua
previously on_event.lua and game_events.add had seperate priority lists, so that unrelated of the priority parameter (which both game_events.add and on_event.lua now support) on_event.lua events were always excuted first. 
The set_undoable(false) call is there for compatibility with the old on_event implementation.
=> use game_events.add in on_event.lua

copyrights.csv
This assumes Styxnix is the right attribution, currently waiting for confirmation in IRC (in the Finnish language channel). I'm going AFK for the afternoon, so anyone please merge once it's confirmed.
Move the previous addition of the UtBS blowgun into sort-by-filename order.
Correct copyright of orb-two-color.png, as it was based on orb.png.
=> Update the copyright info for the Finnish help images

data/modifications/pick_advance/main.lua
local lua variables  are not persitent over reloading. moveto events that change the gamestate cannot be undoable unless on_undo code is provided.
=> Fix out of sync errors with pick advance mod

data/core/terrain-graphics/enduring-bridge.cfg
adjust layering to keep units from sinking into N/S bridge image, fixes #8111 (and hopefully doesn't create any new issues)
I also see the NW, N, NE bridge to castle transition needs help, but that needs new images so I will postpone.
=> 1.18 - N/S bridge and sprite layering

data/core/terrain-graphics/enduring-bridge.cfg
This adjusts layering of bridges vs castles to put castle walls above.  The image below is a hybrid: 
1. NW-SE (new)
2. NE-SW (current)
My comment in #8121 on this issue may be wrong, I don't think new images are needed after all if "castles on top" are the desired outcome.  If "bridges on top" are desired, then lots of new images likely are needed to avoid weirdness like this:
(the jaggy shadow on the dwarf castle NW and the strange cut-off on the elf castle NW)
=> 1.18 - bridge-end layering relative to castle walls

data/campaigns/Sceptre_of_Fire/scenarios/1_A_Bargain_is_Struck.cfg
This is to fix #8083 
1. Clarify the objectives of where the caravans and rider are supposed to go
2. make the target area a little bigger (could have also made it `enter_hex` instead of `moveto`, but I think this should do - it wasn't the main complaint anyway)
EDIT:  I'm really not a fan of this copyrights.csv CI, it gives me grief even when I don't touch images.
EDIT2: Never mind, I see it has nothing to do with this, it was failing after the recent translations update
=> 1.18 SoF S1 - Victory Conditions

data/schema/units/abilities.cfg
In the validation schema abilities-value in abilities.cfg contains not only the numerical attributes but also active_on and apply_to, while these two deniers are only used by [resistance], and the abilities used as weapons are validated by the schema validation of special weapons, and the abilities [leadership], [heals], [regenerate] and [illuminates] also use all numerical attributes.
=> Modify shema validation for more consistency

src/controller_base.cpp, src/mouse_handler_base.cpp
The old issue #2218 was actually a bug in SDL, fixed on X11 in version 2.0.18 and on Wayland in version 2.0.20.  The hardcoded workaround in pull #2481 (commit 4bc4373) caused a regression in fixed SDL versions.
This fix is similar to the workaround in widelands/widelands#5394 committed as widelands/widelands@67db32a.
Tested with SDL 2.0.14 and 2.28.5.
=> Fix horizontal scrolling regression (fixes #7404)

data/campaigns/Eastern_Invasion/scenarios/04b_Ill_Humors.cfg
04b's "time over" event triggers on turn 22, even after the turn limit gets extended (thanks for the bug report 'Emperor').  This is a quick fix for the issue.
=> EI - 04b_Ill_Humors.cfg "time over" bugfix

src/image_modifications.cpp, src/image_modifications.hpp, src/tests/test_image_modifications.cpp
Previously, the mod parser returned a raw to-heap pointer. Once added to a mod queue, it would then be owned by a shared_ptr (overkill). This makes it so the mod executors are managed by unique_ptrs for their entire lifetime.
=> IPF: improve memory safety when constructing mod queue

copyrights.csv, update_copyrights
When the tool finds new or changed files, it puts them at the top of the output .csv file for easy editing. However, this means that those lines move when update_copyrights is run again. It also means that any two PRs touching images are likely to have merge conflicts, as they'll change line 2 of copyrights.csv.
Make the CI fail unless the file has been sorted again after editing.
=> Check that copyrights.csv is sorted by filename

src/serialization/schema/tag.hpp
For more context:
https://github.com/wesnoth/wesnoth/pull/8136#issuecomment-1872243927
This makes iterators based on `wml_tag::iterator` to meet LegacyInputIterator requirements.
=> make `wml_tag::iterator` copy assignable

changelog_entries/horizontal_scrolling.md, src/controller_base.cpp, src/mouse_handler_base.cpp
The old issue #2218 was actually a bug in SDL, fixed on X11 in version 2.0.18 and on Wayland in version 2.0.20.  The hardcoded workaround in pull #2481 (commit 4bc4373) caused a regression in fixed SDL versions.
This fix is similar to the workaround in widelands/widelands#5394 committed as widelands/widelands@67db32a.
Also make mouse handler use same coordinate signs as map and fix mouse_wheel_*() virtual method calls, which have been wrong in the X axis since commit dfe2f33 (and unused since commit c912f7e).
Tested with SDL 2.0.14 and 2.28.5.
Cherry picked from commit ab4001d (pull #8137) in the master branch (1.17).
=> [1.16] Backport #8137: Fix horizontal scrolling regression (fixes #7404)

changelog_entries/horizontal_scrolling.md, src/controller_base.cpp
Avoids two to four function calls on each SDL_MouseWheelEvent.
Also update code comment and changelog entry based on @vgaming's report of issue #3362 being fixed.
Slightly improves commit ab4001d.  Tested again with SDL 2.0.14 and 2.28.5.
Slight (unnoticeable) performance improvement inspired by @vgaming's review of pull #8158.
See also #8186 for 1.16.
=> Save horizontal scrolling inversion check in static variable

changelog_entries/horizontal_scrolling.md, src/controller_base.cpp
Avoids two to four function calls on each SDL_MouseWheelEvent.
Also update code comment and changelog entry based on @vgaming's report of issue #3362 being fixed.
Slightly improves commit e628e27.  Tested again with SDL 2.0.14 and 2.28.5.
Slight (unnoticeable) performance improvement inspired by @vgaming's review of pull #8158.
See also #8185 for master.
=> [1.16] Save horizontal scrolling inversion check in static variable

data/test/macros/wml_unit_test_macros.cfg, data/test/scenarios/wml_tests/ScenarioWML/EventWML/ActionWML/DirectActionsWML/harm_unit_kill_no_experience_no.cfg, data/test/scenarios/wml_tests/ScenarioWML/EventWML/ActionWML/DirectActionsWML/harm_unit_kill_no_experience_yes.cfg, data/test/scenarios/wml_tests/ScenarioWML/EventWML/ActionWML/DirectActionsWML/harm_unit_kill_split_experience_no.cfg, data/test/scenarios/wml_tests/ScenarioWML/EventWML/ActionWML/DirectActionsWML/harm_unit_kill_split_experience_yes.cfg, data/test/scenarios/wml_tests/ScenarioWML/EventWML/ActionWML/DirectActionsWML/harm_unit_kill_yes_experience_no.cfg, data/test/scenarios/wml_tests/ScenarioWML/EventWML/ActionWML/DirectActionsWML/harm_unit_kill_yes_experience_yes.cfg, data/test/scenarios/wml_tests/ScenarioWML/EventWML/ActionWML/DirectActionsWML/harm_unit_survivable_experience_no.cfg, data/test/scenarios/wml_tests/ScenarioWML/EventWML/ActionWML/DirectActionsWML/harm_unit_survivable_experience_yes.cfg, wml_test_schedule
This is testing experience=yes and experience=no, with the expectation that some new values for that attribute will be added afterwards.
Adds a new generic macro ASSERT_UNIT_HP_XP. Looking thorugh the ability tests, ASSERT_UNIT_HP (without the XP) could be a heavily-used macro, but it wouldn't be used by this particular commit, so I'm not adding it in this commit.
=> Add tests for [harm_unit]

data/campaigns/Under_the_Burning_Suns/scenarios/03_Stirring_in_the_Night.cfg, data/campaigns/Under_the_Burning_Suns/scenarios/09_Blood_is_Thicker_Than_Water.cfg, data/core/macros/special-notes.cfg
Multiline comments need the `po:` prefix on each line, otherwise that line is ignored. This fixes all occurances of this.
Any lines which have nothing after the `po:` are still ignored, so I haven't added it to the paragraph-break lines. The resulting .pot file doesn't have paragraphs.
Planning to just do a CI check overnight and merge in the morning.
=> Fix some multiline po: comments

data/campaigns/Under_the_Burning_Suns/utils/abilities.cfg
Fixes #7966
In UtBS, at the start of the player's turn any units that are next to a Quenoth Shaman get +1 move (or +2 for some of the L2/L3 shamans).
Without this fix, the buffed units have an orange orb instead of the green unmoved orb, and don't rest-heal next turn. This makes things look correct during the player's turn, at the expense of showing the unit's max_moves as the buffed amount, even if the unit won't get the buff next turn.
=> UtBS: Units with tailwind have green orbs and rest-heal

update_copyrights
Improve the error messages about the input file needing sorting, to avoid confusion when successfully creating a sorted output from an unsorted input.
Addresses the discussion in https://github.com/wesnoth/wesnoth/commit/e07acf71dc926b975420de3e34dbfa0303b6f4bb#commitcomment-136180490
=> Check that every file in copyrights.csv has a license and author

src/formula/callable_objects.cpp
The "undead" attribute for `unit_type_callable` was split in https://github.com/wesnoth/wesnoth/commit/d82762b87d8#diff-7842222d67a8d773accb3fa2e9b89c54e5342a648566c987c88004eb8998b1bc but the input remained and the split was not done for `unit_callable`.
For 1.18 I think it might be best to fix the input to have it work for unit and unit type. It can be removed for 1.20.
=> [WFL] deal with formula_callable inputs that currently don't do anything

data/campaigns/The_Rise_Of_Wesnoth/maps/08_Clearwater_Port.map
Fixed starting location (bug)
In 1.17, the author has changed the enemy side numbers in the scenario file. However, it seems that the map file starting locations where not updated accordingly. This file updates the starting location. However, there is a chance the author did alter the map as whole, and in that case, we should wait for his upload for the new file.
Tldr: changed these locations:
3 into 4
4 into 5
5 into 6 (originally there was no 6th starting location)
=> 08_Clearwater_Port.map

data/campaigns/Under_the_Burning_Suns/scenarios/06a_In_the_Tunnels_of_Trolls.cfg
Resolves #8192.
I grant this still doesn't make much sense, because arguably the Dust Devil shouldn't be able to bury the bones, but it's perhaps less jarring than a mute Dust Devil having dialogue.
=> UtBS S6a: Avoid Dust Devil speaking

SConstruct, changelog_entries/systemd_nobody.md, packaging/systemd/SConscript, packaging/systemd/wesnothd.service.in, packaging/systemd/wesnothd.service.scons.in, packaging/systemd/wesnothd.sysusers.conf.in, packaging/systemd/wesnothd.tmpfiles.conf.in
[systemd 246+ logs a warning message](https://github.com/systemd/systemd/blob/v246/NEWS#L106-L113), because running as "nobody" is unsafe.
This should be reviewed and tested by someone who knows and uses systemd, as I do not.  Is this worth escalating in the changelog to `### Security Fixes`?
See also #8169 for 1.16.
=> systemd: Run as _wesnoth:_wesnoth using sysusers.d

SConstruct, changelog_entries/systemd_nobody.md, packaging/systemd/SConscript, packaging/systemd/wesnothd.service.in, packaging/systemd/wesnothd.service.scons.in, packaging/systemd/wesnothd.sysusers.conf.in, packaging/systemd/wesnothd.tmpfiles.conf.in
[systemd 246+ logs a warning message](https://github.com/systemd/systemd/blob/v246/NEWS#L106-L113), because running as "nobody" is unsafe.
This should be reviewed and tested by someone who knows and uses systemd, as I do not.  Is this worth escalating in the changelog to `### Security Fixes`?
See also #8168 for master.
=> [1.16] systemd: Run as _wesnoth:_wesnoth using sysusers.d

src/scripting/game_lua_kernel.cpp
lua_unit::put_map already removes the unit previously on that tile, and doing it here causes an error when the unit was on that tile already.
=> fix unit:to_map(loc) #8229

data/tools/unit_tree/html_output.py
Not tested, and not planning to personally test until #3953
Given attack has accuracy=2 and parry=3, unit would show instead of current 
12 × 5 ranged (arcane) (pierce, skilled)
12 × 5 ranged (arcane) (pierce, skilled, accuracy 2%, parry 3%)
=> Show accuracy/parry as weapon specials in html, fixes #7895

changelog_entries/rtl_help_menu.md, src/help/help_menu.cpp, src/help/help_menu.hpp, src/widgets/menu.cpp, src/widgets/menu.hpp, src/widgets/menu_style.cpp
Fixes #8205
This addresses #5600 and #8205. As #8205 is specifically about the names I'm marking it as fixing that one, and leaving #5600 for the issues that you can see on the right-hand pane in that issue's first screenshot, where the yellow text should be to the left of the corresponding white header text.
The GUI1 menu code is only used to support one UI feature, which is the help browser. The RTL support displayed incorrectly, and the code in menu::draw_row was complex, because it supported multiple columns and multiple things in each column; to do so it did a lot of string parsing. The help browser itself wanted to know whether clicks are on the icon or the text, but that wasn't provided by the existing code (it's all in the same column), so was already reimplemented in …
=> Handling RTL in the left pane of the help browser

data/test/scenarios/wml_tests/ScenarioWML/EventWML/events-test_filters.cfg
This passes both with and without #8245, it tests to prevent an unintentional API change in case someone looks at that copy and prematurely optimises the list copying.
It also adds the missing first_time_only=no, which is why the three [moveto] events didn't trigger the third event three times.
=> Make event_test_filter_condition check when the filters run

changelog.md, data/campaigns/Eastern_Invasion/scenarios/08_Xenophobia.cfg, data/campaigns/Eastern_Invasion/scenarios/09_Castle_in_the_Ice.cfg, data/campaigns/Eastern_Invasion/scenarios/11_Captured.cfg, data/campaigns/Eastern_Invasion/utils/traits.cfg
In S11, make the first deserter always male so the translations don't need to worry about gender variants.
Fixes #8225. Most the new strings are ones that had to be added to replace the strings that contained macros. The deserter mechanism included strings that had to change, so a few of the deserter-related strings in S11 have also been split for male/female speakers; I think that's a bug-fix, and those strings are currently only translated in `en_GB` and `sk` (plus any translation that's not yet reached @ivanovic ).
=> EI: fix macros in translatable strings, improve po hints

data/test/scenarios/wml_tests/ScenarioWML/EventWML/events-test_priority_in_same_name.cfg, src/game_events/manager.cpp, wml_test_schedule
This avoids issues if the events being executed add new handlers, since adding a new handler needs to sort the list according to the event priority.
Fixes #8157
=> Make a copy of the active event handler list before executing them.

src/game_classification.cpp
As the core is potentially changing the behavior of the game, the core should be stored into the save in order to have the full setting of the game in the save.
The behavior of the engine when loading a save with a core (different from default) can be left open, but the saves should include the core id to leave options open.
=> Store core ID into save

data/campaigns/Eastern_Invasion/units/Human_Shadow_Lord.cfg, data/campaigns/Eastern_Invasion/units/Human_Shadow_Mage.cfg
Original Shadow Mage/Lord stats were based on undead's 50% arcane vulnerability.  With the arcane rebalance, the Mage/Lord's arcane weapon is no longer worth using.
This PR adjusts the Lord/Mage's arcane weapon to be stronger, and impact weapon to be weaker.
=> EI Shadow Mage, Shadow Lord Balance

changelog_entries/systemd_nobody.md, packaging/systemd/wesnothd.service.in, packaging/systemd/wesnothd.service.scons.in, packaging/systemd/wesnothd.sysusers.conf.in, packaging/systemd/wesnothd.tmpfiles.conf.in
Prefixing all system and group names with the underscore is recommended by the systemd developers.
This reverts commit 8b6ef6aeeb80273a5826e2a25fffe5a2ca26a529.
(cherry picked from commit 91bd96b319ffa4b33fcfb33dce03c529aa480509)
1.17.25 was released using `_wesnoth:_wesnoth`.  So should be the upcoming 1.16.12.
Some discussion in https://github.com/wesnoth/wesnoth/pull/8168#issuecomment-1898040835.
Ping @stevecotton
=> [1.16] Revert "systemd: drop _ prefix from username"

data/campaigns/Under_the_Burning_Suns/units/quenoth/Youth.cfg
Nym's 2 parry adjustments function as expected. Kaleh's does not as it uses improper WML. It should use increase_parry instead of parry.
=> Fix Kaleh sword parry

add_source_file
Treat an argument of "--help" as a request to print help, instead of a filename to add to the source lists.
Treat the arguments "src/foo.cpp" "src/foo.hpp" as two filenames, instead of adding src/foo.cpp to target src/foo.hpp. The old command line
./add_source_file a b c
becomes
./add_source_file a --target b --target c
When saying that pbxproj is required, suggest optionally using a venv instead of installing systemwide.
Fixes the "obnoxious behavior" noted in #8291, but not the issue about .hpp files that's reported there.
=> Use argparse for add_source_file

data/test/macros/generic_backstab_test.cfg, data/test/macros/start_position_common_keep_a_b_c_d.cfg, data/test/maps/4p_separate_castles.map, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/backstab.cfg, wml_test_schedule
The units on the outsides of a backstab don't have to be allied to each other, they just have to be enemies of the victim. That's hardcoded into the AI via attack.cpp's backstab_check() function, hence a unit test to check that WEAPON_SPECIAL_BACKSTAB activates in that situation.
Add a new map with 4 sides all on separate castles. This is a variation of the generic 2p unit test map, extended in the south with a horizontal reflection of existing map.
Add a MAP_FILE argument to COMMON_KEEP_A_B_C_D_UNIT_TEST, because it's the same setup except for the map file.
=> Backstab unit tests: check that backstab works in a free-for-all

data/tools/unit_tree/html_output.py
=> Remove warning 'Weapon special x has no name for', fixes #8298

CMakeLists.txt, INSTALL.md
This reverts commits 7ce1bf9f7da and c6a2dc93175.
OpenSSL >= 3.0 was required (but only when building with CMake) so that `src/preferences/credentials.cpp` could use `EVP_EncryptInit_ex2()` (commit a880f01a315), but that change was reverted (commit 83ab05532a9), all within three hours.
Tested locally by building with OpenSSL version 1.1.1w, logging into the lobby with "Save password locally (encrypted)" checked, quitting, and logging in again without having to enter a password.
@Pentarctagon
=> Revert "Check for correct openssl version."

data/campaigns/Heir_To_The_Throne/scenarios/12_Northern_Winter.cfg
Currently, snowfall is not at a constant pace as intended.
707 hexes of 10 terrain types (Gs,Gd,Co,Ko,Gll^Fp,Gll^Fmw,Gll^Fdw,Gd^Vo,Gd^Vc,Hhd^Vo) are converted to snowy terrains. Therefore, on challenging difficulty with 28 turn limit (=27 snowfall turns), it should be (26 hexes converted*22 turns) + (27 hexes converted*5 turns)=707 hexes. However, according to my experiments, 21~30 hexes are randomly converted. Removing Re and Rb from filtered locations should solve this problem.
Line 227 (original):
Re, Rb are dirt, and these hexes are not converted to snowy terrain. However, by having them within [filter_location], the snowfall pace fluctuates. Also, Hhd^Vc doesn't exist on this map.
Line 258~269 (original):
Coa and Hhd are not filtered.
Line306~311 (original)
Hhd^Vc doesn't exist on …
=> HttT S12 Snow falls at a constant pace

data/core/terrain-graphics.cfg, data/core/terrain-graphics/new-macros.cfg
Allows for more flag-based filtering, so that the ice transitions can be disabled in the little hole in the upper right, but still works for the same terrain inside the big gulch region.
=> 1.18 - fix terrain graphics rule for elevation/ice/water transition

add_source_file
Only add files that were named on the command line, don't implicitly add a .hpp file when the .cpp file was given. Previously the script both needed the .hpp (for Xcode) and failed when the .hpp was given (for CodeBlocks).
Add the following checks, and if any of them fail exit before making any changes. Also add a --no-checks option to proceed anyway.
* Check the files exist
* If a .cpp is given and the .hpp exists, check it was given too.
* If a .hpp is given and the .cpp exists, check it was given too.
For the files used by CMake and SCons, .hpp files were never added, and they still won't be.
PR #8301 is a draft, but has successfully compiled on the CI with files added with this script. The numbers in Xcode files are randomly generated UUIDs, so they change each time the script is run …
=> Clarify whether add_source_file should add .hpp files

data/campaigns/Heir_To_The_Throne/scenarios/14_Plunging_Into_the_Darkness.cfg
Usually, when (14, 23) is unoccupied by any unit,
(14, 23) = Kalenz
(13, 23) = Gryphon
(12, 22) = irrelevant
, and then the Gryphon is killed by the current code.
However, when (14, 23) is occupied either by an ally or enemy unit (picture below),
(14, 23) = occupied
(13, 23) = Kalenz
(12, 22) = Gryphon
, and then the Gryphon stays there and joins the recall list.
(15, 19) is almost always unoccupied, but the same problem can occur.
Therefore, this fix uses "id=" instead of positions to make sure that Gryphons are removed no matter where they are on the map, just like how Gryphon Tender (Elvish Shaman) is removed by the current code.
Relevant forum posts: [Feedback by Orek (me)](https://forums.wesnoth.org/viewtopic.php?p=681283#p681283), [Feedback by …
=> HttT S14 Use "id=" to remove Gryphon units

src/actions/create.cpp
There are still other places in the code that call unit_placed so there might be some cases left where unit_placed don't prevent undoing, but most of them are nonundoable anyways.
=> fix (most parts of) 7780 make unit_placed events nonundoable by default

copyrights.csv, update_copyrights
Commit 97c8feb8ca3b (pull #7903) included a comma in the "Notes" field of four files, which instead of being enclosed in quotes, overflowed into the "Needs Update" field.  So if those files are updated, update_copyrights would clobber part of the notes.
The same commit specified for 58 of LordBob's portraits a license of "GNU GPL v2+;CC BY-SA 4.0".  I don't know if the semicolon is supposed to mean "and" or "or".
"And" isn't legally possible, because the GPL doesn't allow others to relicense under CC BY-SA.  "Or" appears incorrect, because LordBob [licensed][1] his portraits under "the GNU GPL" and I can't find any evidence of him also licensing them under CC BY-SA 4.0.
@Pentarctagon, is this license fix correct, or did LordBob relicense some (but not all) of his portraits somewhere I …
=> copyrights.csv: Fix and check "License" and "Needs Updated" fields

changelog_entries/8214.md, data/core/units/monsters/Raven.cfg, data/core/units/monsters/Raven_Harbinger.cfg, data/core/units/monsters/Raven_Omen.cfg
Level 1 has HP 26 and XP 44
but level 2 has HP 29 (just +3?) and XP 150 (It's not a level 3)
This pull request adjusts the stats of level 2 _War Harbinger_ to be level 2
=> [Units] Raven unit tree Stats patch

src/game_initialization/lobby_data.cpp, src/saved_game.cpp
It's better to be defensive with those default values, especially now that the mp lobby code can automatically download addons, having require_modification set to true isn't inconvenient for the users either.
(The issue that the added comment is abotu isn't something that was added in this commit)
=> require_modification/campaign now defaults to yes

changelog.md
Doing so since we have three Javelineers:
- Javelineer (Loyalist)
- Merman Javelineer (Rebels)
- Saurian Javelineer (core/pseudo-Drakes)
One can easily mistake the loyalist one for the merman one here.
=> changelog: add missing unit type ID prefix to clarify ambiguity

data/schema/schema.cfg
Fixes schema.cfg validation errors after #8136.
I've followed the same pattern of the other tags in this schema to allow the conditional tags `case`, `else`, `then`, `elseif` and `else` to be defined without a name key.
=> Add optional tag name overrides to conditional tags in schema.cfg

data/lua/wml/endlevel.lua, data/test/scenarios/manual_tests/scenario-test.cfg, src/scripting/game_lua_kernel.hpp
Change the Lua implementation to directly call the non-deprecated function, this is related to 9daa10a9f2.
Clean up the C++ header files by removing the declarations of functions that were removed in 3c8de46771.
Use [endlevel]end_credits=no in the test scenario (trigger it by moving to hex 9,3). If you debug with :next_level without triggering the moveto, "The End" will show; trigger the moveto first, and it won't show the credits.
=> Fix deprecation warning when setting [endlevel]end_credits=

src/units/unit.cpp
previously it could happen that removing an object applies the status healing, in particular of the default amlas (which are meant to only heal the unit once)
[tranform_unit], unit:transform(),  [remove_object]  and unit:remove_modifications() are required not to change a unit current hp see https://wiki.wesnoth.org/DirectActionsWML#.5Btransform_unit.5D , especially not in a unpredictable manner like this.
=>  make sure transform_unit doesn't heal the unit

data/core/terrain-graphics.cfg
fixes #8333 
removes something added in b4471f3 that might have been ghost of an abandoned plan that crept in, because I'm not seeing the reason for it now.
=> 1.18 - remove LAYER argument from main Cud wall rule

src/gui/widgets/listbox.cpp
content_resize_request() doesn't appear to return the correct result in this case, even when the number of rows to display has increased.
Fix #7270
=> Force the UI to update fully when changing addon filters

src/help/help_impl.cpp
Displaying variations in the help has some rough edges. This is a patch from the liked PR which, while it can be further improved, is still good enough to improve the situation. Changes:
* Doesn't clutter unit help tree when a unit variation is displayed (that's the main problem. Doofus posted a before/after image is in the issue.)
* When displaying a unit variation in the help, it displays the links below the unit image at the same line as when displaying the base unit (That's a side effect)
Room for further improvement improvement:
Change the code so that not the same text is used in both places. Sidebar should stay as with this change, but help page couls show the Type Name with the variation in parentheses in the same line, instead of with the line break as before, or not at all with …
=> Avoid linebreak in title text of help pages

data/campaigns/Sceptre_of_Fire/scenarios/2_Closing_the_Gates.cfg
Standing on the runes changes some hexes to impassable, so it's a change to the game state. It isn't a random event, so it would be possible to add an [on_undo], but that seems unnecessary, and would need to handle multiple runes.
Fixes #8343 (assuming that @alberic89 confirms that it's only happened in this scenario).
=> SoF S02: Don't [allow_undo] when activating the runes

CMakeLists.txt, SConstruct
Version 13 of GCC added the -Wdangling-reference option, however due to false positives it had to be moved from -Wall to -Wextra. Discussion about its status in GCC-14 is in
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110075
The docs don't explain exactly what triggers the warning, but here's the explanation from https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106393#c1
> The warning works by checking if a reference is initialized with a function
> that returns a reference, and at least one parameter of the function is a
> reference that is bound to a temporary. It assumes that such a function
> actually returns one of its arguments! ... suppress the warning when we've
> seen the definition of the function and we can say that it can return a
> variable with static storage duration. …
=> Use -Wno-dangling-reference when building with GCC-13

data/campaigns/Sceptre_of_Fire/scenarios/2_Closing_the_Gates.cfg
The intro to this map shows Rugnur running into the stronghold, with the elves not far behind. Those moves were running into shroud, which generated "could not find move_unit_fake route" warnings because the animation prefers routes that moving side can already see.
Also, have the conversation between Alanin and Rugnur take place with Alanin on a road hex, because if he starts on the keep then he takes a long route to avoid cave terrain.
Fixes #8350.
=> SoF S02: Alanin has planned (unshrouded) his escape route

data/tools/addon_manager/COPYING.txt
Commit 81c31c40c53 updated jQuery to 3.7.0 and tablesorter to 2.31.3.
Update homepages, in particular for the tablesorter fork.
jQuery dropped the confusing and unnecessary dual licensing in 2012:
- https://blog.jquery.com/2012/09/10/jquery-licensing-changes/
Also specify the GPL version used by tablesorter and clarify the "MIT" license.  The license actually comes from Expat and is one of many licenses used by MIT (including the X11 license, which is also commonly called "the MIT license"):
- https://en.wikipedia.org/wiki/MIT_License#Ambiguity_and_variants
- https://www.gnu.org/licenses/license-list.html#Expat
=> Update COPYING.txt for jQuery and tablesorter

data/schema/core/actionwml.cfg, src/game_events/action_wml.cpp
Each [teleport] tag should have exactly one each of [source], [target] and [filter]. Missing any of those is caught immediately above the new conditional block, so this makes having two or more of any of them be treated the same.
The log should maybe be made more visible, but it's a case that can already be detected by schema validation, so validate it there instead.
The code in teleport.cpp uses assert() in the cases that the newly-added code in this commit catches. That's bug #8175, and it's probably still reachable for units with teleport abilities, so this doesn't close that bug. The change in #8223 should still be added as well.
=> Log instead of assert for incorrect [teleport] tags in ActionWML

data/campaigns/Eastern_Invasion/scenarios/04b_Ill_Humors.cfg
This doesn't change a translatable string, it removes a comma that was immediately after the translatable string.
Fixes #8372.
=> EI S04b: Fix Hahid's name having a trailing comma

data/campaigns/Heir_To_The_Throne/maps/11_The_Ford_of_Abez.map, data/campaigns/Heir_To_The_Throne/scenarios/11_The_Ford_of_Abez.cfg
For almost 20 years, "Move Konrad to the north side of the river" has been criticized for being misleading and unclear objective because “the north side” does not include sand hexes. There are dozens of posts pointing this out in [the campaign feedback thread](https://forums.wesnoth.org/viewtopic.php?t=8716).
Therefore, “past the sandy shores” is added to the objective sentence. I’m not sure if this is a correct, natural, and clear English expression, so I don’t mind seeing it replaced by better wording.
Also, currently, only y=1~8 hexes trigger the scenario end event, but some grass hexes are y=9 (picture). Therefore, all the non-sand hexes in the north are specified in the fixed version.
=> HttT S11 Make the objective clearer

changelog_entries/gettext_gender.md, data/tools/pywmlx/state/machine.py, data/tools/pywmlx/state/wml_states.py
This will automatically record the gender (if specified) of each `[unit]`, `[unit_type]` and `[side]` (leader).
The hint `gender=male,female` is often applied to `[unit_type]name=`, although that's usually the male name. I believe that's the only downside of this change.
Resolves #8382.
=> wmlxgettext: treat gender as a po hint

src/gui/core/gui_definition.cpp, src/wml_exception.cpp, src/wml_exception.hpp
This builds the standard text for errors such as
"In section '[styled_widget]' the mandatory key 'id' isn't set."
However, if passed "[styled_widget]" as the section argument, the message would say "[[styled_widget]]". If passed "styled_widget", the doubled "[[" and "]]" would still appear, along with an extra log message about the lack of square brackets.
Make calling it without square brackets the documentated way.
There are four calls to this that want to pass multiple tags, which I haven't changed. This means they'll still show doubled brackets, but as it's a message which should rarely be seen I feel that's better than having strings which look wrong in the source.
* gui/core/window_builder.cpp: "[window][resolution][" + tagname + "]"
* gui/widgets/listbox.cpp: …
=> Avoid extra square brackets in "missing key" error dialogs

data/campaigns/tutorial/lua/character_selection.lua
When a unit data passed to `to_map` either lacks a side or has side zero, implementation automatically sets it to 1, thus the existing code worked fine. However:
1. The lack of a `side` caused a warning in EmmyLua.
2. The tutorial should be good example code, and the special-case in the C++ code that made this work is a case of "assume it's a SP situation, and choose the result that benefits side 1".
Cherry-picked from #7359.
=> Tutorial: Specify the side of Li'sar in the char select

data/campaigns/Eastern_Invasion/units/Human_Terraent_Paladin.cfg
When Terraent was created, the mainline paladin had no standing anim. When that was added, it conflicted with Terraent's. This fixes that issue.
This also updates Terraent's other stats to match the mainline paladin's rebalanced stats.
#8371 
(is this an acceptable way to fix the issue?)
=> EI: fix Terraent standing animation, and update stats to match mainline

data/campaigns/Eastern_Invasion/scenarios/12_Evacuation.cfg
Fixes #8414.
S18 conditionally forwards the player to the bonus scenario, S99. One of the required conditions is that dra_nak_dead is not yes. The victory event of S12 unconditionally clears dra_nak_dead, meaning that that test in S18 will always pass.
S12 tests dra_nak_dead to see if he was killed in S11, and if he wasn't then it renames "Varrak-Klar" to "Chief Dra-Nak", as if Dra-Nak was pursuing the heroes. However, S12 doesn't set the dra_nak_dead variable if the renamed Varrak-Klar dies.
=> EI - dra_nak_dead branch bugfix

data/gui/widget/multiline_text_default.cfg, data/schema/schema.cfg, src/gui/widgets/scroll_text.cpp, src/gui/widgets/scroll_text.hpp, src/gui/widgets/scrollbar_container.hpp, src/gui/widgets/spinner.cpp
Fixes the following bugs :
1. Stop `scroll_text` from growing infinitely and instead show the scrollbars when the text dimensions exceed the default size of the underlying `multiline_text` in some dialogs (such as edit_pbl, the pbl publishing editor).
2. Allow `horizontal_grow`/`vertical_grow` to work correctly. Currently, the widget stops vertically growing due to absence of `max_height=0`, again in some specific dialogs.
=> Multiline Text Area bugfix

data/campaigns/Heir_To_The_Throne/scenarios/17_Scepter_of_Fire.cfg
Relevant forum post: [https://forums.wesnoth.org/viewtopic.php?p=683820#p683820](https://forums.wesnoth.org/viewtopic.php?p=683820#p683820)
Most of the time, Konrad can recruit/recall 6 units per turn. However, when he spawns at the very bottom of the map, some hexes are outside the map boundary, and therefore, only 5 or 3 units can be recruited/recalled. To fix this problem, 1 castle hex is added when he is at (odd, 68), and 3 castle hexes are added when he is at (even, 68).
These added codes are made based on the codes immediately above (line 445~473). If more experienced people can come up with better and more concise codes to achieve the same outcome, I am all for it.
=> HttT S17 Map always has 6 castle hexes around Konrad

data/campaigns/World_Conquest/resources/data/artifacts.cfg
The item now applies the effects directly instead of using [trait]s,  The lua code that added traits in the wc lua files didn't work, but the main reason why i preferred  this solution instead of changing the lua files is that it makes it possible to simply remove the artifact via for example [remove_object] (which wouldn't work for artifacts using traits as those are separate modifications)
The code now also adds a dummy ability so that players know that this unit has the benefits of the healthy fearless and  undead  traits.
=> wc: fix #6513  Bezoar artifact

data/campaigns/Eastern_Invasion/scenarios/04a_An_Elven_Interlude.cfg, data/campaigns/Eastern_Invasion/scenarios/04b_Ill_Humors.cfg, data/campaigns/Eastern_Invasion/scenarios/09_Castle_in_the_Ice.cfg, data/campaigns/Eastern_Invasion/scenarios/11_Captured.cfg, data/campaigns/Eastern_Invasion/scenarios/12_Evacuation.cfg, data/campaigns/Eastern_Invasion/scenarios/13_Spoils_of_War.cfg, data/campaigns/Eastern_Invasion/scenarios/14_The_Drowned_Plains.cfg, data/campaigns/Eastern_Invasion/scenarios/15_Return_to_Wesnoth.cfg, data/campaigns/Eastern_Invasion/scenarios/16_Eleventh_Hour.cfg, data/campaigns/Eastern_Invasion/scenarios/17a_The_Duel.cfg, data/campaigns/Eastern_Invasion/scenarios/17b_All-In.cfg, data/campaigns/Eastern_Invasion/scenarios/18_Epilogue.cfg, data/campaigns/Eastern_Invasion/scenarios/99_Empire.cfg
Has a few updates to S04a, S04b, S09 and S99 too. This isn't the complete set for S99, but it feels like a good stopping point if I want to get it reviewed in time for this weekend's release.
Lore: this declares Khrakrahs (dragon seen in SoF) to be male. He's been in many versions of Wesnoth that only had male drakes, thus will surely already be male in any translation where the gender has an effect on the wording.
There's a few questions and "TODO for 1.19" comments added:
* In S12, the left behind units say "we must ride ... to save Wesnoth", but it looks like that should be "you must ride".
* The intro of S13 is confusing, there's little indication of why you only have one unit, or what mission he failed.
* In S16, Gweddry says "night approaches" on turn 1 (morning)
This shouldn't …
=> EI S11-S18: Add more PO hints

data/campaigns/Descent_Into_Darkness/scenarios/10_Endless_Night.cfg
A simple case of `role=unit` instead of `speaker=unit`, the necessary translatable text was already in the scenario.
Reported by JL42 in https://r.wesnoth.org/p686563 , it's a trivial fix so intending to merge once the CI's sanity checks are done.
=> DiD S10: Fix missing line in human heroes' book endings

src/gui/widgets/multiline_text.cpp, src/gui/widgets/multiline_text.hpp, src/gui/widgets/scroll_text.hpp
When code in text_box_base.cpp calls the virtual method, it will only consider the 2-argument version, and thus skip the 3-argument wrapper. Override the 2-argument method to catch the calls and have the intended extra effect.
Note: in testing I don't see a difference in what happens in the UI, but I'm not familiar with the edge cases of this widget.
I just checked the stack traces to confirm that the call from text_box_base::insert_char skipped the wrapper.
This fixes a Clang warning, although the warning itself points out the opposite effect - that the 3-argument version hid the 2-argument one in the subclass.
Also fix a Clang warning that scroll_text could mark a method as an override.
=> Fix multiline_text's overriding of set_cursor

src/gui/widgets/scroll_text.cpp, src/gui/widgets/spinner.cpp, src/wml_exception.cpp, src/wml_exception.hpp
This adds a new missing_mandatory_wml_tag() function, which returns a message using a common string, similar to the existing missing_mandatory_wml_key.
To avoid new strings in 1.18, the current implementation just calls missing_mandatory_wml_key directly.
=> Remove new strings that were used for VALIDATE_WML_CHILD

data/campaigns/Secrets_of_the_Ancients/scenarios/02_Dark_Business.cfg, data/core/units/saurians/Prophet.cfg, data/core/units/saurians/Seer.cfg
Corrects some image paths as flagged by `wmllint`. This complements @pehjota's #8435/#8436 for #8432.
This should probably be back-ported to 1.18 branch.
=> Correct image locations

data/campaigns/Heir_To_The_Throne/scenarios/05b_Isle_of_the_Damned.cfg
NAMED_LOYAL_UNIT has the loyal trait built in, so this results in an extra copy of it being granted to the unit.
=> HttT S5b: Fix duplicate loyal trait for Delurin

src/scripting/lua_unit_type.cpp
=> Lua: Make sure unit type is built before returning it from iteration

src/help/help_topic_generators.cpp
Fixes #8275
------
Current:
With this PR:
=> Multiply help portait scaling by the pixel multiplier.

src/gui/dialogs/campaign_difficulty.cpp
Still feels a bit clunky, but I'm following the pattern already used here:
https://github.com/wesnoth/wesnoth/blob/90a74e1b965b77b6abca46a4b7f94a297a290ab1/src/gui/dialogs/campaign_selection.cpp#L98-L110
This works for me, at least. Thanks to @CelticMinstrel for pointing me in the right direction. If there's a better way than just relying on the count of difficulties, please advise.
Resolves #8442. Should be back-ported to 1.18 branch, I think 1.16 as well unless there's absolutely no way there's going to be another release for it.
=> Keep laurel decorations consistent with difficulty level

vcpkg.json
Gives us (among other things) these updates:
Boost:             1.82                            -> 1.84
OpenSSL/libcrypto: 3.1.0a-dev (runtime 3.1.0a-dev) -> 3.2.0a-dev (runtime 3.2.0a-dev)
libcurl:           8.1.2 (runtime 8.1.2-DEV)       -> 8.6.0 (runtime 8.6.0-DEV)
Cairo:             1.17.8 (runtime 1.17.8)         -> 1.18.0 (runtime 1.18.0)
Pango:             1.50.14 (runtime 1.50.14)       -> 1.50.14 (runtime 1.50.14)
SDL:               2.26.5 (runtime 2.26.5)         -> 2.30.0 (runtime 2.30.0)
SDL_image:         2.6.3 (runtime 2.6.3)           -> 2.8.2 (runtime 2.8.2)
SDL_mixer:         2.6.3 (runtime 2.6.3)           -> 2.8.0 (runtime 2.8.0)
=> Bump vcpkg baseline

src/units/types.cpp
Backport of #8483
static variables are only initialized the first time they are encountered, even if they are only defined in the body of the method. therefore their value here is set to the first language used when this method is called, but won't change later if the language changes because they've already been initialized.
Fixes #8393
(cherry picked from commit ef972bb0a064002359f8ec00545c37181d63344f)
=> The method is static, but these variables can't be.

src/gui/widgets/button.cpp, src/gui/widgets/chatbox.cpp, src/gui/widgets/drawing.cpp, src/gui/widgets/horizontal_scrollbar.cpp, src/gui/widgets/image.cpp, src/gui/widgets/label.cpp, src/gui/widgets/listbox.cpp, src/gui/widgets/matrix.cpp, src/gui/widgets/menu_button.cpp, src/gui/widgets/minimap.cpp, src/gui/widgets/multiline_text.cpp, src/gui/widgets/multimenu_button.cpp, src/gui/widgets/pane.cpp, src/gui/widgets/panel.cpp, src/gui/widgets/progress_bar.cpp, src/gui/widgets/repeating_button.cpp, src/gui/widgets/scroll_label.cpp, src/gui/widgets/scrollbar_panel.cpp, src/gui/widgets/slider.cpp, src/gui/widgets/text_box.cpp, src/gui/widgets/toggle_button.cpp, src/gui/widgets/toggle_panel.cpp, src/gui/widgets/tree_view.cpp, src/gui/widgets/unit_preview_pane.cpp, src/gui/widgets/vertical_scrollbar.cpp, src/gui/widgets/viewport.cpp
The logic is that the strings included the names of WML tags, but weren't clear that they were WML tags, and so the tag names are being translated. The change is similar to #8433, and there's discussion leading up to this PR in #7600.
This reverts almost all of the string changes of PR #7600, which were in commit f5be4cffb7b34fdd2ac875cf0f76fc8db7e23cef, as well as a few similar strings which weren't in 1.16.x.
Yes, it's intentional that the non-translatable strings don't have the outermost `[` and `]`, even if they're `tag_1][tag_2`. Those outside ones are added by the message-creation function.
=> [1.18] Use missing_mandatory_wml_tag instead of extra translatable strings

changelog_entries/addon_server_id_ui.md, src/addon/client.hpp, src/gui/dialogs/addon/manager.cpp
This expands the server display at the bottom left of the Add-ons Manager window to include the server-provided server id and version after the server address. The goal with this is to make proper use of the `[server_id]` command (already sent during every connection since 1.15.x) and be able to differentiate server instances more easily when the port number is not part of the connection address.
**Default view (debug mode disabled):**
**Detailed view (debug mode enabled):**
If the `[server_id]` info is not available (e.g. when connecting to obsolete pre-1.15.x servers), the instance id/version are simply not shown.
As a reminder, the `[server_id]` is part of the add-ons server protocol and the `id=` field in it is a free-form string specified by the server admins, while the `version=` is …
=> ui: Add add-ons server identification to the bottom left display in Add-ons Manager

changelog_entries/ui-outro-text-fading.md, data/gui/window/outro.cfg, src/gui/dialogs/outro.cpp, src/gui/dialogs/outro.hpp
While playing HttT last night I found out that the text fading effect in the outro screen at the end of the campaign was basically unnoticeable on my M1 MacBook Pro because of some poor assumptions in the outro screen's animation code regarding the frequency of screen updates — assumptions that in particular appear to have been broken by the 1.17.x rendering engine changes.
This PR replaces the outro screen's text fading logic with a clock-based version to avoid relying on rendering engine internals that can change all the time because of architectural changes, different hardware configurations, or user preferences.
Relevant text from the commit message follows:
> This version uses `SDL_GetTicks()` as a monotonic source to avoid the previous version's pitfalls, namely the fact that the …
=> gui/outro: New clock-based timing logic for the text fading

data/campaigns/Winds_of_Fate/scenarios/01_The_Hunt.cfg, data/campaigns/Winds_of_Fate/scenarios/05_Threshold.cfg, data/campaigns/Winds_of_Fate/scenarios/08_Overlook.cfg, data/campaigns/Winds_of_Fate/scenarios/09_Ancestor.cfg, data/campaigns/Winds_of_Fate/scenarios/11_Crosswind.cfg
Fixes an issue [discovered](https://github.com/wesnoth/wesnoth/pull/7908#discussion_r1495724310) by @Wedge009 in the wmllint logs, using the magic comment [suggested](https://github.com/wesnoth/wesnoth/pull/7908#discussion_r1496780958) by @CelticMinstrel. Also fixes three other WoF issues reported in the wmllint logs.
At least the "wrongly capitalized variable name" should be considered for backporting to 1.18 since it fixes a player affecting bug of one of their main character units (Resha) losing an upgrade object if it is given to her.
=> WoF: fixes for wmllint warnings

src/editor/map/context_manager.cpp
currently the editor defaults to its maps directory even when you open a map file somewhere without it being in an "add-on", for example opening a map in a mainline campaign's maps folder.
=> use the currently selected map's path when opening a new file

data/tools/wmllint
The idea of using multiples of 5 seems like a way to avoid having to change multiple campaigns' ranks at once, because it leaves space to rearrange a mainline campaign between two other campaigns.
But enforcing "it must be a multiple of 5, even if that means changing other campaigns" loses the advantage of using multiples. For example, WoF currently has rank=152, which triggers the warning, which has caused a PR to be opened that changes WoF, SoF, LoW and SotA - because keeping them in order requires four campaigns to change.
Closes #7224, removes a commit from #8447, will itself be obsoleted by #8321.
=> wmllint: drop the rule about [campaign]rank= being a multiple of 5

data/test/scenarios/wml_tests/UnitsWML/modification_effect_type_variation.cfg, src/units/unit.cpp, wml_test_schedule
Previously the code would apply the variation effects last, so that codes like
```
[effect]
apply_to=variation
..
[/effect]
[effect]
apply_to=hitpoints
heal_full=yes
[/effect]
```
Would not set the unit hitpoints to the new variations hitpoints because the variation effect was applied after the healing effect.
In 1.16 this worked becasue healign was applied a little too often but that lead  also to bugs like #8324
=> Fix #8460 [effect] apply_to=variation

data/campaigns/Eastern_Invasion/units/Undead_Horse_Barrow_Wight.cfg
Barrow Wight's definition includes a couple of attack name strings from the wesnoth-units textdomain bound to wesnoth-ei by default instead, which creates two unnecessary extra strings for translators to translate. This PR fixes this by binding these two strings to wesnoth-units so their existing translations can be used.
(Pyre Wight does not require this change since it already uses the wesnoth-units textdomain for the single attack name it uses.)
=> EI: Bind stock translatable strings in Barrow Wight's definition to the wesnoth-units textdomain

src/actions/advancement.cpp, src/scripting/game_lua_kernel.cpp, src/units/udisplay.cpp
Fixes #8227
---
I haven't looked deeper to see if there's anything else that needs to be done yet, but it does fix the death animation playing at least.
=> Make sure animations are skipped when skipping animations in replays

data/campaigns/Secrets_of_the_Ancients/scenarios/16_The_Mage.cfg
I play-tested this in master and couldn't get Crelanu to leave his ring, even with as tempting a target such as a weak Ardonna.
Resolves #8361.
=> SotA S16: Keep Crelanu within his ring of protective holy waters

projectfiles/Xcode/The Battle for Wesnoth.xcodeproj/project.pbxproj
This is necessary with Xcode 15.3 to avoid about 750 warnings across all of the codebase regarding "Implicit conversion loses integer precision", most of which apply in cases where theoretical limits are involved because of conversions from unsigned 64-bit integers (usually `size_t`) to signed 32-bit (`int`).
Ideally we want to address these warnings, but given how many of them there are all over the place this is not something that can reasonably be done in such short notice before Wesnoth 1.18.0 is released, and in the meantime they make the compiler output with Xcode unnecessarily noisy and completely bury any relevant warnings from actual code changes. In the meantime, this is best for productivity until we can get to a place where we can fix all of them and force using …
=> Add -Wno-shorten-64-to-32 to compiler flags in Xcode

changelog_entries/recruit_recall_filtering.md, src/gui/dialogs/unit_recall.cpp, src/gui/dialogs/unit_recruit.cpp
This adds the human-readable version of each unit's alignment and their (gendered) race name and plural race name as hints for the filter box functionality, so that players can enter keywords such as "liminal", "dwarves", "mermaid" and get what they expect even if those words are not literally part of the unit type names.
Inspired by this Ideas forum thread: https://forums.wesnoth.org/viewtopic.php?t=57749
Still a work in progress since I want to do the same for the Recruit dialog, which seems a little more involved due to it using a different mechanism for handling the Filter box.
I'm curious if @Pentarctagon and @Vultraz believe this is a reasonable candidate for backporting to 1.18 since it's not a massively impactful change and — especially for the Recall dialog when playing longer …
=> gui/unit_recall: Add alignment and race hints for filtering

changelog_entries/aethermaw_images.md, data/multiplayer/scenarios/2p_Aethermaw.cfg
Cherry-picked backport of the first commit from @babaissarkar's #8539 (that PR is still in review, but only because the later commits add new art and prose).
Fixes #8432.
I've added a changelog entry when backporting.
=> [1.18] MP: Aethermaw: Update images with their 1.18 variants

src/game_config.cpp
Found with Xcode 15.3:
`/Users/iris/Projects/wesnoth/src/game_config.cpp:551:18 Implicit conversion turns floating-point number into integer: 'double' to 'const int'`
=> Fix "implicit conversion turns floating-point number into integer" warnings

data/campaigns/Winds_of_Fate/scenarios/11_Crosswind.cfg
Last minute tweak to WoF S11 for the stable branch.
Testing the default difficulty setting by effectively droiding the player's side, the enemy side still lost even with 480 gold and otherwise default difficulty settings - [droid_side1_vs_480g_side2.gz](https://github.com/wesnoth/wesnoth/files/14628065/droid_side1_vs_480g_side2.gz). So upping enemy side gold to 480 for all difficulty levels. (Note I had to manually retreat the non-leader-but-must-survive characters since default AI does not recognize the importance of their survivals).
Will forward port this to master.
=> [1.18] WoF S11: tweak enemy gold

changelog_entries/wc-double-scrollbar-bugfix.md, data/campaigns/World_Conquest/gui/help_dialog.cfg, data/gui/window/achievements_dialog.cfg
Caused by the fact that the vertical scollbar mode in the left hand treeview was set to `never`. Setting it to `auto` allows the scrollbar to grow, and prevent the window from showing it's own scrollbar. (Issue #8576)
=> fix double scrollbar bug in WC Help dialog

src/filesystem.cpp
It *appears* that the migration prompt doesn't show up for steam players because steam automatically creates the <userdata>/saves/steam_autocloud.vdf file on start, since the saves folder is what's synced. Since the migration logic is looking for whether the userdata folder exists, this means it always exists when launched from steam.
So, fix that by checking a different subfolder under userdata (checking the logs folder is arbitrary, it could be any of them aside from the saves folder).
=> Attempt to fix data migration for steam

changelog_entries/jpg_to_webp.md, src/picture.cpp
Give .jpg files the same logic that .png files were given in 8f06da197462e376bf25704253299a886622ba58, because many files were renamed in 51b58ad218fc285717c7d5889fdfeda59f017ca6. UMC using the old name for images will trigger a warning, but the player will still see the image file.
This is just a cosmetic change that doesn't change compatibility, because have_asset("images", "blah.jpg") won't be automatically redirected to "blah.webp". Thanks to @ProditorMagnus for pointing that out. I feel it should merge for 1.18.1, and it can then be cleanly cherry-picked for master - if it's not going into 1.18, no reason to add it to master as UMC will be updated anyway for 1.18.
=> [1.18] Automatically replace missing .jpg images with .webp if found

data/tools/pywmlx/state/machine.py
Backport of #8577
(cherry picked from commit 4be9aa85849010e93a9a3b0f0701d0630e7b9368)
=> fix invalid escape sequence

changelog_entries/jpg_to_webp.md, src/picture.cpp
Forward-port of #8618
Give .jpg files the same logic that .png files were given in 8f06da197462e376bf25704253299a886622ba58, because many files were renamed in 51b58ad218fc285717c7d5889fdfeda59f017ca6. UMC using the old name for images will trigger a warning, but the player will still see the image file.
This is just a cosmetic change that doesn't change compatibility, because have_asset("images", "blah.jpg") won't be automatically redirected to "blah.webp".
(cherry picked from commit 84ed5488e0676a1cff6989ae3caa75a68f739bf7)
=> Automatically replace missing .jpg images with .webp if found

changelog_entries/aethermaw_images.md, data/multiplayer/scenarios/2p_Aethermaw.cfg
Forward-port of #8563, which was itself a cherry-pick from with #8539 with added changelog. I think it makes sense to merge this part so that #8539 becomes smaller.
(cherry picked from commit 2b9ed4708003d1b213f2efc3649f8dfffca5e95b)
=> MP: Aethermaw: Update images with their 1.18 variants

data/multiplayer/scenarios/2p_Aethermaw.cfg
Sulla's power in Aethermaw seem to be far more than what can be expected of a Wesnothian Great Mage, so updated the lore and gave her a new type which seems more apt.
Also planning to add some new images for the new type, if it is something I can do with my skill level.
Yet another reason would be to let players know that the paths human magi can take are as varied as there are human. Currently the main paths are Red vs White mage (and Silver maybe). But other races show that these are not the only types of magic that exist. (I think at this moment it gives a false impression that Red Magi are the best, and only they can become Great Mages). This can slightly alleviate that. (Compare for example War of Legends' magi, where even dual and multielement magi are possible)
Current choice : …
=> Aethermaw Cosmetic Updates

.github/workflows/ci-main.yml, utils/CI/check_wml_images.sh
Playing the multiplayer scenario Aethermaw as Loyalists vs. Undead revealed some image errors (#8432):
20240219 06:50:21 error image: could not open image 'units/undead/shadow-s-attack-1.png'
20240219 06:50:21 error image: could not open image 'units/undead/shadow-s-attack-4.png'
20240219 06:50:21 error image: could not open image 'units/undead/shadow-n-3.png'
20240219 06:50:22 error image: could not open image 'units/undead/shadow-n-attack-2.png'
20240219 06:50:26 error image: could not open image 'units/human-loyalists/spearman-attack-se-9.png'
20240219 06:50:26 error image: could not open image 'units/human-loyalists/spearman-attack-se-10.png'
20240219 06:50:26 error image: could not open image 'units/human-loyalists/spearman-attack-s-6.png'
20240219 06:50:26 error image: could not …
=> Re-add the renamed/removed unit images in MP Aethermaw (#8432)

data/campaigns/tutorial/scenarios/01_Tutorial_part_1.cfg
No string changes, just adjusting when the hints at the top-left of the screen appear and disappear.
The hint about crowns now appears after recruiting both elves, so that there are units to compare the leader to, who have the same orb color but no crown.
The hint about traits appears when told to attack the quintain with the elves. The player will probably find a strong or dexterous trait, and Delfador already comments about those traits after attacking. Even if neither elf has those, speedy or robust could also influence whether to use melee or ranged attacks.
There's now no hint on screen when first choosing which village to use for healing; previously it was the hint about crowns which didn't seem relevant. No strings are added in this commit, but a hint about checking the quintain's …
=> Tutorial S01: Better timing for the hints

data/campaigns/Under_the_Burning_Suns/scenarios/01_The_Morning_After.cfg
Adjusts chance of finding a unit in village (by difficulty and unit value), making it less likely to have long streaks of luck or unluck.
https://docs.google.com/spreadsheets/d/1Wqrb6ytW3FeYcWXlfKBlNgi6bcklNyk7bXDfdl1QsJ4/edit#gid=0 is a quick and dirty analysis of different max_fate values on how much an empty village, fighter, scout, or tauroch adjusts your chances in all future villages.
=> UtBS luck smoothing: scenario 1

src/utils/config_filters.hpp
Due to my confusion between NULL and std::nullopt, a compilation error was introduced. @iFoundSilentHouse would this suit you better?
=> alternative fix build with musl libc

boost_test_schedule
It was added in 532d17f958969186baa0646c5528c2477bcb65b3, but that commit missed adding it to boost_test_schedule.
=> [1.18] Boost tests: run test_without_attribute_filter

src/filesystem.cpp
`boost::filesystem::symbolic_link_exists()` has been deprecated since at least Boost 1.34 (2007).
=> Fix macOS-specific deprecation warning from Boost.Filesystem API call

src/filesystem.cpp
=> Fix macOS-specific deprecation warning from Boost.Filesystem API call (development branch forward-port version)

changelog_entries/macos-bundle-changelog.md, src/macosx/SDLMain.mm
This changes the URL used for the changelog menu item from using a direct GitHub file link to the master branch's changelog.md file to using a https://changelog.wesnoth.org/X.Y.Z link, where X.Y.Z are specifically the version number used in the macOS bundle's Info.plist file.
Note that this may result in incorrect links for +dev versions, where the Changelog link will simply send the user to the page for the latest release and not the future release. This shouldn't be a problem though, since people using those builds, especially on macOS, should really already know where to find the most relevant changelog for the version they're running -- in their own source tree.
---
To add a little more background to this, I remember adding a https://changelog.wesnoth.org/X.Y.Z redirect at some point …
=> Make the Changelog macOS app menu item more relevant

changelog_entries/macos-bundle-changelog.md, src/macosx/SDLMain.mm
Just running a forward-port of #8572 through CI build.
=> Make the Changelog macOS app menu item more relevant (development branch forward-port version)

boost_test_schedule
It was added in 532d17f958969186baa0646c5528c2477bcb65b3, but that commit missed adding it to boost_test_schedule.
(cherry picked from commit c80fdc2283ac42635674a441999544b6164bd6b2)
=> Boost tests: run test_without_attribute_filter

data/campaigns/Eastern_Invasion/scenarios/05_Northern_Outpost.cfg
In EI's S05, Owaec briefly recounts the bloody fate of his local priestess, killed by undead.
The scenario's music consists of wanderer.ogg and traveling_minstrels.ogg, which are inappropriate for encountering a mangled corpse.
Instead, fade the music out during this section.
This is the second version of this pull request; I did something weird on the first one causing the entire file to change.
=> EI S05: fade to silence when recounting the priestess's death (v2)

src/gui/dialogs/multiplayer/match_history.cpp, src/server/common/dbconn.cpp
Currently even though the results ultimately don't display duplicate information for the modifications used, the resultset coming back does have a row per modification and player, so it appears as though the player list is duplicated.
Fixes #8619
---
Draft since I haven't tested it locally yet - my local database instance seems to have vanished, so I need to see what's going on with that.
=> Don't duplicate player names per mod used

data/gui/window/campaign_dialog.cfg
The different RNG options available when choosing a new campaign could use more in-depth explanations with examples, to make them easier for new players to understand.
As part of this, I've also renamed "Biased RNG (experimental)" to "Reduced RNG", which I believe is a more intuitive name.
=> campaign_dialog.cfg - Explain the RNG options better

data/campaigns/Eastern_Invasion/scenarios/12_Evacuation.cfg
The "illuminates" ability was recently changed to create its own halo, instead of relying on the unit's halo. This caused issues in a section of EI where Dacyn (a mage of light) is supposed to have a flickering halo. This PR fixes that EI bug.
Fixes issue #8675
=> EI 12_Evacuation.cfg: fix Dacyn's halo not flickering

data/tools/pywmlx/state/lua_states.py, data/tools/pywmlx/state/machine.py
Testing: running a pot-update with this should produce no string changes compared to 1.18.0. SotA's strings are a particular place to check, because this fixes #8646. Some strings move around in wesnoth-tutorial.pot because of #8660, but they shouldn't change.
The original code was probably meant to strip trailing whitespace, which turned out to be a bug when adce3fe79b4f52e2caf21962b2bc440fa36b0476 fixed the buggy regexp so that it started working. That has now been removed.
Fixed handling of multiline plural strings, which was broken too.
One feature has been left unimplemented, and will cause wmlxgettext to error out. For "long bracketed" strings, Lua allows the contents to start with a newline, which is automatically stripped from the resulting string. Trying to understand the …
=> [1.18] wmlxgettext: Fix "fix invalid escape sequence"

changelog_entries/language-ui.md, data/gui/window/language_selection.cfg, src/gui/dialogs/language_selection.cpp, src/gui/dialogs/language_selection.hpp, src/language.cpp, src/language.hpp
(Please ignore the first commit including a separate bugfix.)
This overhaul introduces a GUI option to show all languages regardless of their completion threshold, as well as a side panel including a general explanation of community translations and how players can potentially contribute to them, plus a link to the main translations page on the wiki.
A few points to make here:
* The URL points to the main page on purpose, since it's meant to be a catch-all for all languages regardless of which one the player has got selected or configured (those are two different things at the moment).
* There's an issue where when showing all translations, some of the non-Latin translation names cause the baseline of the language name labels to end up entirely misaligned with the completion labels. I am …
=> Language selection UI overhaul

data/tools/pywmlx/state/lua_states.py, data/tools/pywmlx/state/machine.py
Forward-port of #8672, will merge when the CI run finishes.
The original code was probably meant to strip trailing whitespace, which turned out to be a bug when 4be9aa85849010e93a9a3b0f0701d0630e7b9368 fixed the buggy regexp so that it started working. That has now been removed.
Fixed handling of multiline plural strings, which was broken too.
One feature has been left unimplemented, and will cause wmlxgettext to error out. For "long bracketed" strings, Lua allows the contents to start with a newline, which is automatically stripped from the resulting string. Trying to understand the original purpose lead me to this feature of Lua strings which we don't use in Wesnoth; and I finally concluded that, if someone wants to use that feature, it can be their problem to implement it.
This fixes …
=> wmlxgettext: Fix "fix invalid escape sequence"

data/campaigns/Eastern_Invasion/utils/abilities.cfg, data/campaigns/Eastern_Invasion/utils/items.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/resistance/resistance_to_damage_type_special.cfg, wml_test_schedule
Fix https://github.com/wesnoth/wesnoth/issues/8631 issue
When damage_type is used but the opponent uses the resistance ability against the added type it can only detect the original type and the new type is not affected.
=> [1.18]EI: Barrow Wight Resistance to Arcane On Defence Ability Doesn't Work Against Mixed Damage Type Weapons

data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/resistance/resistance_to_damage_type_special.cfg, src/units/unit.cpp, src/units/unit.hpp, wml_test_schedule
Fix https://github.com/wesnoth/wesnoth/issues/8631 issue
When damage_type is used but the opponent uses the resistance ability against the added type it can only detect the original type and the new type is not affected.
=> fix attack::damage_type bug for abilitie resistance

.github/workflows/ci-main.yml
Setting up vcpkg tries to build xz from source, which fails because the entire xz repo has now been made private or taken down. The vcpkg team have been advised not to switch to an alternative repo [1], so for now our Windows builds will always fail.
Turn those builds off, so that we don't get familiar with seeing red status markers on all PR's CI results.
[1] `https://github.com/microsoft/vcpkg/pull/37957` - second comment is the vcpkg team's "We have been explicitly asked by security folks to not change the upstream [to a different repo] for liblzma at this time."
Link is in backticks because I didn't intend this to create noise in the vcpkg PR it linked to (the commit itself does, sadly).
=> [1.18] Disable the Windows CI builds

src/reports.cpp, src/units/unit.cpp, src/units/unit.hpp
If the first trait of a unit has no name, then clicking on the units (other) trait in the sidebar opened the wrong page in the help.
Fixes #8635.
=> Fix clicking on the sidebar going to the wrong trait

.github/workflows/ci-main.yml
Setting up vcpkg tries to build xz from source, which fails because the entire xz repo has now been made private or taken down. The vcpkg team have been advised not to switch to an alternative repo [1], so for now our Windows builds will always fail.
Turn those builds off, so that we don't get familiar with seeing red status markers on all PR's CI results.
[1] `https://github.com/microsoft/vcpkg/pull/37957` - second comment is the vcpkg team's "We have been explicitly asked by security folks to not change the upstream [to a different repo] for liblzma at this time."
=> Disable the Windows CI builds

data/core/units/fake/Fog_Clearer.cfg
Not mentioned here, but turning on debug mode also affects which units, and therefore which units' traits, are shown in help.
Having looked back into the history while wondering why it was done this way in e9603e6e01, back then we needed a fix that could be backported to 1.14, so couldn't add a new attribute to [unit_type]. The feature request to do it properly is #5139.
=> Document why the Fog Clearer's traits show in help

changelog_entries/moveto_message.md, src/gui/widgets/window.cpp
If a mouse click causes a delay and then a message to appear, for example when moving a unit triggers an `[event]name=moveto`, then the message would sometimes flash on screen and then disappear with barely enough time to see which character's portrait was used, let alone to read it.
Although there's already logic to not be triggered by the same mouseclick that caused the unit to move, it had a race condition if the MOUSE_UP happened around the time the the dialog's pre_show() function was running.
Fixes #8644
=> [1.18] Fix race condition causing moveto messages to immediately close

changelog_entries/moveto_message.md, src/gui/widgets/window.cpp
Forward-port of #8717, fixes #8644.
If a mouse click causes a delay and then a message to appear, for example when moving a unit triggers an `[event]name=moveto`, then the message would sometimes flash on screen and then disappear with barely enough time to see which character's portrait was used, let alone to read it.
Although there's already logic to not be triggered by the same mouseclick that caused the unit to move, it had a race condition if the MOUSE_UP happened around the time the the dialog's pre_show() function was running.
(cherry picked from commit 26ead85914c9e7af9e378d583657fef7f68f6821)
=> Fix race condition causing moveto messages to immediately close

data/campaigns/Eastern_Invasion/utils/amlas.cfg
Under some circumstances, units in EI can have their custom AMLAs listed multiple times in the advancement dialog.  This PR should fix that issue.
Also can we backport this?
=> EI: remove duplicate AMLAs

doc/man/wesnoth.6, src/commandline_options.cpp, src/commandline_options.hpp, src/tests/test_commandline_options.cpp, src/wesnoth.cpp
The pull request removes the `--gzip`, ` --gunzip`, `--bzip2`, and `--bunzip2` command line options and related documentation.
These options allow compression and decompression of gzip and bzip2 archives from the command line. Given the widespread availability of third-party compression tools, these options most likely have no real use case. Also, it looks like Windows 11, starting from build 23493, can natively handle gzip and bzip2 files (I didn't test how well it works). 
Resolves #8065
=> Remove gzip/bzip2 (de)compression commandline options

src/ai/formula/function_table.cpp, src/movetype.cpp, src/movetype.hpp
The movetype data includes vulnerability to damage types, for example `resistance_against("arcane")`. There was also a convenience wrapper that took an attack_type, and returned the vulnerability to that attack_type's damage type.
The logic of the wrapper is very basic, and does not use unit.cpp's logic to check whether abilities that change the type are active. Although it gained knowledge of alternative damage types in 3910817cf7, it won't always return the same value as the unit.cpp function does.
The wrapper is now only used in FormulaAI, so let's move the code there, which in effect marks it deprecated.
=> Move knowledge of attack_type out of movetype

data/gui/window/editor_edit_unit.cfg
I'm assuming these translation marks weren't intended.
=> Remove translation mark from image paths

data/schema/units/abilities.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/resistance/resistance_min_value.cfg, src/actions/attack.cpp, src/units/abilities.cpp, src/units/abilities.hpp, src/units/unit.cpp, wml_test_schedule
If max_value is used to limit the increase in resistance with the "resistance" capability there is no equivalent for its reduction.
To be able to add min_value without redoing the "resistance" checking for the umpteenth time, I prefer to modify effect:: so that the checking of these two attributes is done at the same time as the other numerical attributes and keep the door open to a possible generalization of the proceed
=> add min_value to [resistance]

data/lua/core/map.lua
This is for consistency with other things that return locations in the engine.
=> [Lua] Make wesnoth.read_location return its result in standard named tuple format

data/core/units/elves/Enchantress.cfg, data/core/units/elves/Sylph.cfg
Elvish Sylph's gossamer and Enchantress' entangle attacks' user visible name is changed to _ethereal web_ to make them more consistent with the new lore introduced in Wesnoth 1.16. (Issue #8583)
Enchantress' attack icon is also changed to make it consistent with the description.
All changes are purely cosmetic and should not break any existing mainline or UMC content.
=> sylph and enchantress attack description changes (cosmetic)

src/units/abilities.cpp
this code should be more readable without affecting the operation of damage_type
=> return optional<std::string> instead of vector<std::string> for static damage_type_list

data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/resistance/resistance_to_damage_type_special.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/special_damage_type.cfg, src/reports.cpp, src/units/abilities.cpp, src/units/attack_type.hpp, src/units/unit.cpp, src/units/unit.hpp, wml_test_schedule
If two [damage_type]altenative_type= are used with two different types, the chosen type displayed in the pre-combat window will be the one to which the opponent will be most vulnerable, and if he is more vulnerable to that one rather than to the type d originally, this is the one that will be used.
On the other hand, in this case, report will not display alternative_type because there is no opponent to check
=>  Change the list check from [damage_type] to a system that takes into account the opponent's sensitivity(2nd try)

src/conftests/sdl2.cpp
The argv variable was unused. The build still succeeded, but GCC emited a warning about it.
=> Fix a warning in the sdl2 conftest

src/gui/widgets/listbox.cpp
Backport of #8788, fixes #8778.
(cherry picked from commit 5ec648a1b2b8675a2a6bb7dcb8b50404b7d2c800)
=> [1.18] Avoid invalid pointer access on recall

src/conftests/sdl2.cpp
The argv variable was unused. The build still succeeded, but GCC emited a warning about it.
(cherry picked from commit c7acbd243a7e3f6e5d2ed69953759461adf75fb7)
=> [1.18] Fix a warning in the sdl2 conftest

src/gui/dialogs/lua_interpreter.cpp
It's rarely useful and just gets in the way. Fixes #3328.
=> Remove history expansion

data/gui/window/language_selection.cfg, src/gui/dialogs/language_selection.cpp
This pull request brings a few minor additions to the improved Language selection UI from #7638:
1. Adds text requested by @Pentarctagon to clarify that the percentages shown only correspond to core textdomains, which also includes a pointer to <https://gettext.wesnoth.org/>.
(Because I know someone will inevitably complain that the explanation isn't exhaustive... There is hardly any point in mentioning every single textdomain counted as "core" in this dialog. If someone really, *really* wants to know, they can either use gettext.wesnoth.org or ask the team about it on Discord/IRC. Listing every single textdomain counted as core here would require writing many words for no tangible gain.)
2. Moves the Show All checkbox from the main panel to the bottom left corner of the dialog to save …
=> Add more information to the Language selection UI

data/campaigns/Sceptre_of_Fire/scenarios/7_Outriding_the_Outriders.cfg
This is to counteract the swifter and deadlier Elvish Outrider after the 1.18 core unit balance changes. It reduces the number of Elvish Outriders at the beginning of the scenario from 5 to 4 and ensures none of them has the  `quick` trait.
This should get back ported to 1.18.
Closes #8589
=> SoF S7: fewer and slower enemy outriders

data/core/terrain.cfg
Follow up to #8783 this makes a unit on an oasis tile visibly sink slightly into its waters, just like with ford terrain.
=> Add submerge to oasis terrain

data/core/terrain.cfg, src/editor/palette/terrain_palettes.cpp, src/help/help_impl.cpp, src/help/help_topic_generators.cpp, src/terrain/terrain.cpp, src/terrain/terrain.hpp, src/terrain/type_data.cpp
Help shows terrain types in the section for their default_base
Instead of the aliasing hack that the oasis terrain used to use, have the help topic generator reuse the editor_default_base as a hint that it should be included in that section.
The terrain_type class gets a new boolean method, and more documentation. There's a couple of refactors to use the new method in old code too.
=> Show the oasis in help without needing a hacky aliasof

src/gui/dialogs/addon/manager.cpp
Current implementation of translation::strftime() uses boost. Boost docs do not appear to have a 'current' or 'latest' link, instead only making documentation available by explicit version number.
Resolves #8822.
=> Add-ons UI: Add date/time reference to translation hint

src/gui/dialogs/addon/manager.cpp
Backport of #8826, fixes #8822
Current implementation of translation::strftime() uses boost. Boost docs do not appear to have a 'current' or 'latest' link, instead only making documentation available by explicit version number.
(cherry picked from commit 5e9260570b3f1401603b294ecd63119d8ca732d1)
=> Add date/time reference to translation hint

data/core/editor/help.cfg
As a spelling mistake, I think this should be back-ported, but it is a rather long block of text so if others disagree, so be it.
Resolves #8615.
=> Editor Help: grammar correction

src/build_info.cpp
Next time someone attempts to remove Boost.Predef because it looks "unused", they will at least cause strict CI builds to fail.
(Discovered while reviewing #8803.)
=> bi: Fix for "unknown" arch issue and enforce the fix

projectfiles/Xcode/The Battle for Wesnoth.xcodeproj/project.pbxproj, src/filesystem.cpp
Instead set the Apple preferences folder from within the code rather than using -DPREFERENCES_DIR. Remove -DHAS_RELATIVE_LOCALEDIR since that doesn't appear to actually do anything since its only usage is in filesystem_common.cpp, not filesystem.cpp.
=> Remove version-specific info from xcode projectfile

src/filesystem.cpp
Partially in preparation for #8059 and also removes one use of _X11 for #8806
---
Would also like to get rid of the `PREFERENCES_DIR` define and the associated `relative_ok` boolean.
=> Make userdata path setting code easier to read

src/filesystem.cpp, src/gui/dialogs/migrate_version_selection.cpp, src/gui/dialogs/migrate_version_selection.hpp
Instead store the preferences, credentials, and lua command history files in the userdata folder, same as is done on windows and macos.
Also removes another instance of _X11 for #8806
=> Remove special handling of config directory on linux

data/campaigns/Eastern_Invasion/scenarios/04b_Ill_Humors.cfg
In "Ill Humors", 2 spawn regions for aswaldan herbs overlap, which can result in both spawning on the same hex without any special visual indicator.
Credit to PointMeAtTheDawn.
=> Prevent aswaldan herbs from stacking

src/scripting/game_lua_kernel.cpp
Fixes #8858
---
Though this also essentially means that all of the functionality for UMC to query achievement status is not replay-safe either. Not sure if it's best to just document that on the wiki vs removing the functionality entirely though.
=> Don't trigger achievement completion during replays.

data/gui/window/editor_edit_unit.cfg, src/gui/dialogs/editor/edit_unit.cpp, src/gui/dialogs/editor/edit_unit.hpp
1. accept space in unit type id
2. don't write translated string to generated wml (https://github.com/wesnoth/wesnoth/pull/8731#issuecomment-2059282680)
3. add textdomain at the top of the generated file
4. fix bad key in generated attack block
Please let me know if I missed any translatable strings.
=> bugfixes for unit type editor

src/filesystem.cpp
Introduced in d2b0df99673b9bd871d24d00cacae97e17ae8b10, at least one of the functions is affected on Xcode on macOS.
=> Fix compiler warnings due to missing function prototypes

data/campaigns/tutorial/scenarios/02_Tutorial_part_2.cfg
Addresses the final point mentioned in #5544.
The advice about the Elvish Shamans is lost in the scenario where the orc dies during the first attack of Turn 3, but I suppose a player would have been _very_ lucky to be in this situation, plus I think there are still plenty of notes about Shamans as healers elsewhere.
=> Tutorial S2: Only trigger comment about the orc if it is still alive

src/gui/dialogs/game_version_dialog.cpp
Fix typo that stops the initial tab from opening correctly. (It's opening tab id 0 instead of tab id = `start_page_`)
=> about dialog : correctly open the initial tab

changelog_entries/add_filter_wml_in_filter_ability.md, data/schema/filters/abilities.cfg, data/test/scenarios/wml_tests/ScenarioWML/EventWML/events-test_filter_ability.cfg, src/units/unit.cpp, wml_test_schedule
adding a sub-filter should make it possible to take into account the sub_tags of the abilities in the checking
use https://github.com/wesnoth/wesnoth/pull/8561/commits/596a64c00c76ddffffbaa7fbb224acc6f486d121 commit like base
=> add [filter_wml] to filter_abilities code

data/tools/pywmlx/state/wml_states.py
Resolves #8867.
As best as I can tell, this class isn't mentioned or used anywhere else. Not sure if these tools are intended to be used from the stable branch - this probably should be back-ported if that's the case.
=> Remove WmlDefineState class disabled-as-comment/string

data/campaigns/Eastern_Invasion/achievements.cfg, data/campaigns/Eastern_Invasion/scenarios/16_Eleventh_Hour.cfg
The current S16 achievement requires that the player don't recall any units or have any items.
Some items are undroppable, which can make this achievement impossible if you give one to a loyal auto-recalled unit early in the campaign.
This PR alters the achievement to only care about droppable items.
=> EI: simplify S16 achievement

src/game_initialization/playcampaign.cpp
This is not an optiomal fix as it can still crash if can_start_game() returns false, but its clearly am improvment to the situation in #7478 .
This also removes the "always show mp staging between scenarios in debug mode" feature, which imo never was that useful anyways.
=> Fix #7478 game crash after reloading a mp game in debug mode

data/gui/window/community_dialog.cfg
Most of the GUI, including the title screen's "Community" button, is already in wesnoth-lib. So making this consistent also means we're only adding one copy of "Community" to the .pot files.
Make the whitespace in this file consistent (using tabs).
=> [1.18] Put the community dialog's strings in the wesnoth-lib domain

data/gui/window/language_selection.cfg
Backport of the still-in-review #8905 - I hope the current wording will be accepted, and if so, I want the CI to have already run.
The link with details about individual compaigns is useful to players, even if they aren't looking to become translators. So move it upwards.
The text about first-time players seemed confusing to me, as the choice is already limited to languages that the player can read. Reworded it, but after discussion in the PR, neither version was better than just removing it.
=> [1.18] gui/language_selection: Rephrase text about becoming a translator

data/gui/window/language_selection.cfg
The link with details about individual compaigns is useful to players, even if they aren't looking to become translators. So move it upwards.
The text about first-time players seemed confusing to me, as the choice is already limited to languages that the player can read. Rearrange it to say that people should be familiar with most of the campaigns before considering joining the translation teams.
The current text was added in #8792, and backported to 1.18 after 1.18.0, so this changes text which hasn't yet entered the .pot files. The first paragraph is unchanged - I'm wondering if it should start with "The".
=> gui/language_selection: Rephrase text about becoming a translator

data/gui/window/game_version.cfg
In some platforms, the bullet characters ✦ (U+2726) and ➤ (U+27A4) used in the About dialog will not be visible unless they are using a font that actually has those characters.
=> make sure bullets in about dialog use a font that has those characters

src/gui/dialogs/gamestate_inspector.cpp
Setting visibility::hidden would be consistent with the only other example I could find, the arrows in the help menu.  I think it looks weird to have buttons just disappear completely (except when none would be available), but I'd change it if that's the standard.
=> set buttons inactive when irrelevant

changelog_entries/filter_value_check_default.md, data/schema/filters/abilities.cfg, data/schema/game_config.cfg, src/utils/config_filters.cpp
for answer to an suggestion of @soliton- who think in filter abilitie, value must could check 'default' value of an abilitie/specials directly without have specify this value in filter
=> 'value' attribute in [experimental_filter_ability(_active)] can have 'default' value

data/tips.cfg
As requested by @Konrad22.
There's no particular reason why Delfador should say this during HttT, but perhaps it will make the connection to the campaign clearer.
Closes #8365.
=> Change Delfador's quote date to the start of HttT

data/campaigns/Sceptre_of_Fire/scenarios/6_Towards_the_Caves.cfg
...since he is already present among the dwarves, as highlighted by @doofus-01.
Given this is a bug in the meaning of the text, I think it warrants back-porting to 1.18. However, if others disagree, so be it.
Resolves #8311.
=> SoF S6: Remove reference to finding Alanin

vcpkg.json
I was not able to build current 1.18 branch on MSVC without this. Also means master and 1.18 use same vcpkg base-line again.
=> Back-port vcpkg base-line

data/campaigns/Eastern_Invasion/scenarios/04a_An_Elven_Interlude.cfg, data/campaigns/Eastern_Invasion/scenarios/04c_Mal-Ravanals_Capital.cfg, data/campaigns/Eastern_Invasion/scenarios/08_Xenophobia.cfg, data/campaigns/Eastern_Invasion/scenarios/09_Castle_in_the_Ice.cfg, data/campaigns/Eastern_Invasion/scenarios/14_The_Drowned_Plains.cfg
"optional" may imply that the scenario will be completed once this objective is finished, which is not accurate.
=> EI: use "bonus objective" instead of "optional objective"

src/units/abilities.cpp
When a [damage_type] without alternative_type is used,un "" value is added to set and "", " + string_table["type_" + alt_t]" will be added in report.cpp
It will have then a unknow type showed in report
=> fix show error in report

data/campaigns/Eastern_Invasion/scenarios/10_Dark_Sanctuary.cfg
https://www.reddit.com/r/wesnoth/comments/1d6a3e7/eastern_invasion_is_much_better_but_still_bad/?rdt=58522
Owaec has a leader icon, but it's not made explicit that he can recruit units. In most scenarios that doesn't matter, but in S10 he becomes isolated from Gweddry and must recruit to survive.
Note that there's already a `[show_objectives][/show_objectives]` when `orcs_attacking` is set.
=> EI S10: specify that Owaec can recruit

data/campaigns/Eastern_Invasion/scenarios/08_Xenophobia.cfg, data/campaigns/Eastern_Invasion/scenarios/13_Spoils_of_War.cfg
In add-on form, EI used images to display "Part II" and "Part III".  For translation reasons this got replaced with ugly title_text when the add-on went mainline.
This PR once again makes the "Part II" "Part III" storytext more fancy, while maintaining translatability.
=> EI: use fancy script for "Part II" "Part III" storytext

src/reports.cpp
When any of the images is missing, a text description is shown as a fallback.
The bug being fixed is that the search for the secondary PNGs used the basename
with neither the directory nor the ".png".
The existence of the files controls a single conditional block, but was using
three bools with two dedicated to single files and one shared between all the
alternate files. This changes it to a single bool shared between all files for
clarity.
=> Fix sidebar always showing text for [damage_type]alternative_type= 

changelog_entries/modify_apply_to_in_filter_ability.md, data/test/scenarios/wml_tests/ScenarioWML/EventWML/events-test_filter_ability.cfg, src/units/unit.cpp, src/utils/config_filters.cpp, src/utils/config_filters.hpp, wml_test_schedule
Until now apply_to= could only be used to check if the ability used as a weapon applied to 'self|opponent|attacker|defender' but abilities [resistance] which use apply_to= to determine the types of damage concerned remained excluded.
if all the elements of the list to be checked are present in the ability, then it will match, for example if we look for apply_to=arcane, fire in an ability [resistance]apply_to=arcane, fire, cold, it will match even if its list is longer than the one used for the backward check if [resistance]apply_to=arcane, impact, cold, this will not match because 'fire' will be missing.
=> Allow [experimental_ability(_active)]apply_to= to check damage types in abilities [resistance]

src/network_download_file.cpp
According to [Curl Docs](https://curl.se/libcurl/c/CURLOPT_PROTOCOLS.html), CURLOPT_PROTOCOLS is deprecated with `curl_easy_setopt()`.
=> replace deprecated CURLOPT_PROTOCOLS with CURLOPT_PROTOCOLS_STR

data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage_recalculation_mid_attack.cfg, wml_test_schedule
A weapon with poison, which does extra damage to poisoned opponents. This tests that the weapon-special's filter is checked on each strike, instead of being tested once and then cached during the battle.
I'd welcome suggestions of a better name for this.
=> Add a unit test for a weapon-special activating mid-attack

data/campaigns/Eastern_Invasion/scenarios/10_Dark_Sanctuary.cfg, data/campaigns/Eastern_Invasion/scenarios/11_Captured.cfg, data/campaigns/Eastern_Invasion/scenarios/12_Evacuation.cfg
Resolves #8969
In EI S10, Dacyn picks up a cursed amulet and his HP drops to 1. In EI S11, Dacyn remains on very low HP, and is surrounded by orcs. There's a convenient ford hex he can hide on and be protected, but several players did not notice this hex and complained about difficulty.
In S10, this commit also drops his XP to 0. 1) showing that the amulet interferes with his MoL-ing, and 2) preventing the player from deliberately AMLA-ing Dacyn in the next scenario (partially a difficulty issue, but mostly it's bad to punish blind playthroughs / reward foreknowledge).
In S11, this commit adds a gold pile on Easy/Normal hinting towards the hex, while on Easy Dacyn's HP is fully restored. Hard is unaffected.
In S12, this commit restores Dacyn's HP on Easy (since it would be odd if he had …
=> EI S10, S11, S12: Dacyn difficulty tweaks

data/campaigns/Eastern_Invasion/scenarios/13_Spoils_of_War.cfg
Formerly, EI S13 uses various Deathblades' max-moves status instead of [filter_second] for some reason. This breaks when deathblades get rebuild, which in the bug report was caused by the sentinel shield.  Use [filter_second] instead.
=> EI S13: fix gaoler rebuild breaking "free prisoner" events

src/synced_context.cpp
Previously undo_blocked() would return false positive results. Leading to OOS erros because the game would then send actions to other clients even though they were still undoable. This would then result in OOS erros when the player attempts to undo the move.
This line is probably not needed at all since using the rng should always set is_simultaneous_ to true, but lets keep the changes minimal for the 1.18 stable branch.
=> Fix game sending actions too soon leading to OOS erros

packaging/org.wesnoth.Wesnoth.appdata.xml
Flathub linter complains about mismatched id in flatpak manifest and
appstream. Based on appstream docs it seems that reverse-DNS name is
expected without .desktop extension so appstream should be changed.
Extra `<provides>` and `<replaces>` tags added as per
https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#renaming-id-tag
=> Change id tag in appstream manifest to what is expected

data/tools/wesnoth/wmltools3.py
This disallows matching "0-11-2" and "1," for example. It also avoids an exponential backtracking issue which could make this regex very slow.
=> Fix "span" regex

src/network_download_file.cpp
Backports of #8958 and #8999, fixing the compiler warning. Not sure whether to squash or not, I like having a separation between "this is the change" and "this is just formatting".
=> [1.18]Backport replacing deprecated CURLOPT_PROTOCOLS with CURLOPT_PROTOCOLS_STR

src/gui/auxiliary/typed_formula.hpp, src/gui/dialogs/unit_advance.cpp, src/help/help_impl.cpp
Fix warnings about a template id in a constructor, which is redundant, and GCC-14 warns that this isn't allowed in C++20.
An iterator can often be a struct containing a single pointer, so creating a reference to such a small struct doesn't make sense.
The structure returned by child_range is likely to be exactly two pointers, so it's not a burden to keep it even though back() has already finished accessing the child_iterator.
This fixes half of #8979, as I'm splitting the PRs by estimated amount of discussion. Once it's merged I'll open a PR that pastes 6 copies of the following block into header files, but request that comments on that wait until that PR opens.
```c++
#ifdef __has_cpp_attribute
#if __has_cpp_attribute(gnu::no_dangling)
[[gnu::no_dangling]]
#endif
#endif
```
=> [1.18] Fix some GCC-14 warnings

src/scripting/lua_widget_attributes.cpp
the signal is "on_left_click", so logically the correct method is `connect_signal_mouse_left_click`.
(AFAIK notify_modified is not available for most widgets and doesn't do the same thing as left_click either.)
=> lua: use correct method to attach on_left_click signal

src/units/abilities.cpp, src/units/attack_type.hpp
If [damage_type]apply_to= is applied to a unit that does not have the range attack equivalent to that of the user this type will still be shown, which should not be.
=> Fix damage_type types show in unit attack window[1.18]

src/units/abilities.cpp, src/units/attack_type.hpp
If [damage_type]apply_to= is applied to a unit that does not have the range attack equivalent to that of the user this type will still be shown, which should not be.
=> Fix damage_type types show in unit attack window

data/schema/units/abilities.cfg, data/schema/units/specials.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/attacks/attacks_max_value.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/heals/heals_max_value.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/leadership/leadership_max_value.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/regenerate/regenerate_max_value.cfg, src/tod_manager.cpp, src/units/abilities.cpp, src/units/abilities.hpp, src/units/unit.cpp
In the case of [leadership], the fact that the values of each ability can be added when cumulative=yes can justify the addition of limit values not to be exceeded, but this can also apply to heals and [regenerates] with the use of 'add' or 'multiply'.
As for [resistance], it already uses max_value, but if cumulative=yes, then all max_values can add up which could be problematic.
=> Generalize the use of max_value and add the min_value attribute

src/filesystem.hpp, src/global.hpp, src/gui/auxiliary/find_widget.hpp, src/hotkey/hotkey_command.hpp, src/theme.hpp, src/units/race.hpp
For GCC-13, cfb28fbfb52ed5c75d93e283738d2e45061f9c84 (in master) added -Wno-dangling-reference, and that commit explains why the false positive is triggered by calling find_widget. For GCC-14 there's an attribute so we can flag this specific function as ok.
Clang complains about unknown attributes in the gnu:: namespace, so has to have the #if, and the #if means we need the #ifdef.  I'm intending to leave this PR open a couple of weeks (until the end of June) for discussion about whether there's a less unpleasant alternative.
There are still warnings in src/actions/attack.cpp, but that area is being worked on for an infinite recursion bug, and those warnings log in a single batch instead of being spread across multiple .cpp files.
Fixes part of #8979, will forward-port along with #8998.
=> Ignore GCC-14 and Clang false positives about dangling pointers

data/campaigns/Heir_To_The_Throne/scenarios/17_Scepter_of_Fire.cfg, data/campaigns/Heir_To_The_Throne/utils/httt_utils.cfg
The lava is supposed to stay away from the Sceptre itself. However, 60d114b changed from using sceptre_x,sceptre_y to using a location_id, and missed updating these macros.
Fixes #9038.
=> [1.18] HttT S17 Don't create lava near the Sceptre

changelog_entries/game_load_filter.md, src/gui/dialogs/game_load.cpp, src/gui/dialogs/game_load.hpp
When the user types something into the filter box and then changes to a different version, apply the filter immediately instead of showing the full list of files.
The drop-down to switch between directories is hidden unless savegames from other versions are detected. The button will appear at the bottom-left in master, and at the top of the dialog in 1.18.
It's a trivial bug, but still worth backporting IMO.
=> GUI2/Game Load: Apply filter when changing directory

changelog_entries/game_load_filter.md, src/gui/dialogs/game_load.cpp, src/gui/dialogs/game_load.hpp
Backport of #8955.
When the user types something into the filter box and then changes to a different version, apply the filter immediately instead of showing the full list of files.
The drop-down to switch between directories is hidden unless savegames from other versions are detected. The button will appear at the bottom-left in master, and at the top of the dialog in 1.18.
(cherry picked from commit 17c202d3fb4fdb2f89f65f3b49eeda56836fd43e)
=> [1.18] GUI2/Game Load: Apply filter when changing directory

data/tools/wesnoth/wmliterator3.py, data/tools/wesnoth/wmltools3.py
Has no merge conflicts with #9041.
When backporting, I'll cherry-pick 28a895985499afac8809c4c03ed080f4fe133da5 too.
=> wmltools3: fix regexp compatibility with Python 3.12

data/tools/wesnoth/wmltools3.py, data/tools/wmllint, src/addon/manager.cpp, src/editor/controller/editor_controller.cpp, src/editor/map/context_manager.cpp, src/editor/map/map_context.cpp, src/filesystem.cpp, src/filesystem.hpp, src/game_config_manager.cpp, src/gui/dialogs/editor/edit_unit.cpp, src/gui/dialogs/wml_error.cpp, src/menu_events.cpp, src/persist_context.cpp, src/serialization/preprocessor.cpp
Reduces the the number of hardcoded filenames extensions, especially those that are used in many files (.map, .cfg, .mask). Instead hardcode them only once. For C++, it's in `filesystem.cpp`, for Python tools, it is in `wmltools3.py`.
Also adds new methods for checking if a file is one of these extensions in `filesystem`. (Please use those in new code.)
=> Reduce hardcoded extensions

src/filesystem.hpp, src/global.hpp, src/gui/auxiliary/find_widget.hpp, src/gui/auxiliary/typed_formula.hpp, src/gui/dialogs/unit_advance.cpp, src/help/help_impl.cpp, src/hotkey/hotkey_command.hpp, src/theme.hpp, src/units/race.hpp
Forward-port of
* #8998 
* #9006 
Fixes most of #8979. There are still warnings in src/actions/attack.cpp, but that area is being worked on for an infinite recursion bug, and those warnings log in a single batch instead of being spread across multiple .cpp files.
=> Fix some GCC-14 warnings

src/formula/function.cpp
WFL rotate_loc_around used to set both loc to first parameter.
Repaired.
=> WFL: Use correct argument for the second location in rotate_loc_around

data/campaigns/Eastern_Invasion/utils/items.cfg
Resolves #9070.
@Dalas121 While I was reviewing this, I noticed empty bold blocks and double-spaces at the start of italics blocks. Any reason for this?
https://github.com/wesnoth/wesnoth/blob/888fbf13e55e41cef445770c0479d2706ac5eb37/data/campaigns/Eastern_Invasion/utils/items.cfg#L116-L120
=> Minor changes to Eastern Invasion item wording

doc/man/wesnoth.6, src/commandline_options.cpp, src/log.cpp, src/log.hpp, src/wesnoth.cpp
Resolves #8505.
Adds the `--no-log-sanitize` option. When this option is used, the actual username of the user will be shown in the log instead of `USER`.
=> add a command line option for disabling log sanitization

data/campaigns/Eastern_Invasion/terrain.cfg, data/core/team-colors.cfg
Cleans up the help browser and fixes #8497 (and makes the icon no longer pink).
I'm not sure I like this terrain idea, villages that aren't villages but use the village graphics.  As long as it stays in EI though, I guess it can be OK.
=> EI - urbanjungle clean-ups

update_copyrights
Avoid discarding the entire copyrights.csv when running the update on Windows, and force slashes in file path strings if adding new files.
Also rename hash object to avoid collision with built-in hash function. Clarified file object is representing a file path string as opposed to an actual open file object.
See https://github.com/wesnoth/wesnoth/pull/9063#issuecomment-2224076873 for why I settled on this particular resolution.
=> Update copyrights: Always use slashes for the file path

update_copyrights
This surprises me, but quoting https://docs.python.org/3/library/functions.html#open:
> In text mode, if encoding is not specified the encoding used is platform-dependent...
At any rate, 'explicit is better than implicit'.
=> Update copyrights: Write CSV as UTF-8

data/languages/bn_BD.cfg
Adds a `sort_name` key as well as makes the naming consistent with other languages.
Without this Bengali will be sorted at the end of the language selection list
=> update bengali locale info

src/addon/manager.cpp, src/ai/configuration.cpp, src/ai/formula/function_table.cpp, src/editor/map/context_manager.cpp, src/editor/map/map_context.cpp, src/editor/palette/editor_palettes.cpp, src/filesystem.cpp, src/filesystem.hpp, src/filesystem_common.cpp, src/font/font_config.cpp, src/game_config_manager.cpp, src/game_launcher.cpp, src/gui/dialogs/editor/edit_pbl.cpp, src/gui/dialogs/game_load.cpp, src/gui/gui.cpp, src/language.cpp, src/picture.cpp, src/save_index.cpp, src/scripting/lua_fileops.cpp, src/scripting/lua_wml.cpp, src/serialization/preprocessor.cpp, src/serialization/schema_validator.cpp, src/sound.cpp, src/sound_music_track.cpp, src/tests/test_filesystem.cpp, src/units/race.cpp, src/wesnoth.cpp
Most `filesystem::` functions that returned an empty string for an invalid path now return `optional<string>` . There are a couple areas (mostly with the schema files) where I'm not sure if I should use `value_or("")`, since it's possible with `value` we get the wrong exception thrown for an invalid path.
=> FS: use optional<string> to represent non-existent paths

data/campaigns/Eastern_Invasion/scenarios/99_Empire.cfg
In EI's S99, you gain gold from defeating and capturing hostile drakes.  The drakes are physically moved to prison cells in the middle of the map.
Previously, the player could continue capturing drakes even if enemies overran the prison area. Additionally, the prison cells stayed locked with prisoners inside. This makes no sense in-universe, and also made it a strong strategy to abandon the center and turtle up in a corner of the map. 
This PR fixes this issue. This also adds 2 new strings; I'm planning to backport to 1.18.2, as this is arguably a bugfix.
=> EI S99: prevent prisoner income if prisons are captured

data/campaigns/Eastern_Invasion/scenarios/04c_Mal-Ravanals_Capital.cfg
EI's S04c has an achievement for rescuing all 6 prisoners. This achievement currently triggers whenever all prisoners are freed, even if they die before escaping the scenario.  This PR changes the achievement to only trigger if all 6 prisoners actually escape.
=> EI S04c: only award achievement if all prisoners escape

data/campaigns/Eastern_Invasion/scenarios/17b_All-In.cfg
EI's S17b has a gold refund mechanic, allowing enemies to build up large gold reserves in certain situations.
When gold gets high, enemies are supposed to start recruiting higher-level units so they can spend it faster. The former implementation had some inconsistent issues; this should restore the intended behavior.
=> EI S17b: fix buggy dynamic recruit list macro

data/campaigns/Eastern_Invasion/scenarios/12_Evacuation.cfg
In EI S11, the player encounters an orcish warlord named Dra-Nak. If not killed in S11, he continues pursuing the player in S12, but the current S12 gives him different traits and a different portrait. This PR fixes the issue.
=> EI S12: fix Dra-Nak having inconsistent traits and portrait

changelog_entries/ei_assorted_changes.md, data/campaigns/Eastern_Invasion/scenarios/16_Eleventh_Hour.cfg, data/campaigns/Eastern_Invasion/units/Human_Gweddry_Veteran_Commander.cfg, data/campaigns/Eastern_Invasion/units/Human_Gweddry_Veteran_Lieutenant.cfg, data/campaigns/Eastern_Invasion/units/Human_Konrad_King_of_Wesnoth.cfg, data/campaigns/Eastern_Invasion/units/Undead_Ravanal_Dark_Shape.cfg, data/campaigns/Eastern_Invasion/utils/character-definitions.cfg, data/campaigns/Eastern_Invasion/utils/items.cfg
Fixing several reported issues.
Units: Gweddry has the wrong HP values
Units: Konrad is neutral, should he be lawful
Units: "Dark Shape" is neutral instead of chaotic
Items: prevent Konrad from picking up the plague staff
S16: prevent Konrad and generals from recalling undead
=> EI: minor assorted unit stat and item tweaks

data/lua/feeding.lua
Use filters to decide whether the event should trigger, rather than triggering it always and aborting if the filter doesn't match.
This _might_ be backportable.
Note: Must merge #8462 before this, as the first commit listed below belongs in that PR.
=> Lua feeding cleanup

data/test/scenarios/README.md
Rewrite the non-reservation of "break" and "error" for clarity.
Even tests that don't have "_bug" in the name shouldn't prevent intentional changes to behavior, I've added a paragraph about that.
The idea comes from #9074, I'm splitting it from that because I wrote that PR to test a behavior that I knew about, and found other problems that have meant I need to change what I'm testing.
=> Reserve the name "_bug" for tests of behavior that should change

src/synced_context.cpp
Previously `synced_context::undo_blocked()` sometimes returned the worng result, leading to OOS because `synced_context::undo_blocked()` was used to determine whether we can send action to the other clients.
With this patch `synced_context::undo_blocked()` not doesn't always return true  when its called during "local choices".
I am curently not even sure whether that line is needed at all since using the rng should always set is_simultaneous_ to true.
=> Fix common OOS error #8960

data/campaigns/Delfadors_Memoirs/scenarios/18_The_Portal_of_Doom.cfg, data/campaigns/Delfadors_Memoirs/utils/sides.cfg
In S18 Portal of Doom, all player units must escape through the tunnel, after which Delfador will follow them.
However, if unit entered the tunnel, it magically appeared in the recall list and could be recalled again. I fixed it, and now the escaped units are not available until the next scenario.
=> DM: S18 recall fix

.editorconfig
we currently use the same indentation style for  lua as for cpp files
=> add .lua files to .editorconfig

src/gui/dialogs/title_screen.cpp
1. Uses `utf8::insert` to modify the string so that it works for non-ASCII characters.
2. Use the locale's script font instead of using Oldania always.
=> titlescreen: make drop cap algorithm utf8 aware

src/editor/map/context_manager.cpp
Forward port of the new commit in #9062. (88fc3cda4fb66d09cf670c7e456f042fcb3d0fdb)
Opens load map/save map as dialogs in the addon's map directory.
With no addon selected they open in the `editor/maps` directory.
=> [Fwdport] Opens load map/save map as dialogs in correct folders

data/gui/themes/default/window/preferences.cfg, data/gui/themes/default/window/preferences/03_display.cfg, src/gui/dialogs/preferences_dialog.cpp, src/gui/dialogs/preferences_dialog.hpp, src/gui/dialogs/title_screen.cpp, src/gui/dialogs/title_screen.hpp, src/gui/gui.cpp, src/gui/gui.hpp, src/tests/main.cpp, src/tests/utils/game_config_manager_tests.cpp, src/wesnoth.cpp
With this, after changing the gui2 theme using **Preferences -> Display -> UI Theme**, no restart of wesnoth is required. The theme gets reloaded after the user presses the "Apply" button.
=> allow quick reload of gui2 themes, no restart of wesnoth needed

src/floating_label.cpp, src/floating_label.hpp, src/tooltips.cpp
In some cases (LotI), some tooltips for items on the right hand panel of the main scenario screen do not fit.  The current algo to place tips just checks to see if the tip will fit above the origin, and if not places it below (which is often a worse choice).  I made a suggestion for improving this at https://forums.wesnoth.org/viewtopic.php?t=57103 where it was recommended that I submit a PR, even though I'm not a programmer, I don't know C++ (or SDL, or...), etc.  So here it is, warts and all.
The first step, changes to init_label(), is a complete mess.  It's clear I have no idea what I'm doing, except I know I'm doing it wrong.  But it does at least allow me to demonstrate the idea.  Basically, the text_width of the tooltip texture is set to 400.  If a tooltip is too "tall" to fit (and …
=> improve tooltip placement on sidebar

src/config_attribute_value.cpp, src/config_attribute_value.hpp, src/tests/test_config.cpp
The old implementation was recursive when building with C++20 due to primary operator reordering. More importantly, however, it would fail this test:
```
c["x"] = "yes";
BOOST_CHECK_EQUAL(c["x"], true);
```
=> Clean up `config_attribute_value::operator==`

data/schema/core/addons.cfg
In addition to the mp_village_gold used in mainline, there exist as well:
- mp_fog
- mp_shroud
- mp_village_support
Not covered by this PR: How to specify what is allowed when using a generator? In 
```
[multiplayer]
scenario_generation=default
[generator]
[scenario]
mp_* = are  allowed here, but not if map_generation=default is used
```
=> Schema: add other mp_ keys too

data/core/units/monsters/Skeletal_Dragon.cfg
This comment existed when the unit was still in EI campaign. It's been moved to core ages ago and yet, the comment, now no longer relevant outside of EI still persisted...
Also, why is this _undead_ unit still in `units/monsters/` when `units/undead/` exists?
=> [Units][Skeletal Dragon] Update Stats

data/lua/wml/objectives.lua
Current message:
```
Unknown Condition, ignoring
```
This really does not tell me anything of where I might have messed up and can be even more confusing if I have custom lua from the campaign or an add-on being used in the same scenario.
The edited one tells me where I actually have to look for the error message and fix it.
=> [objectives.lua] improve clarity of error message

data/campaigns/The_Hammer_of_Thursagan/scenarios/06_Forbidden_Forest.cfg
Somewhat adresses #8507 (SotA is unaffected)
This replaces the song Travelling Minstrels with Vengeful Pursuit in S6 of THoT (Forbidden Forest). In my opinion, this is much more fitting to the scenario.
=> THoT S6 Music Tweak

.github/workflows/ci-main.yml
Not that useful to run them with debug as well as release binaries and it takes a lot of time.
Adresses #9167.
=> Disable WML tests for debug builds

data/campaigns/Secrets_of_the_Ancients/scenarios/02_Dark_Business.cfg
Work-around for #9150. If a unit already occupies the hex, it doesn't do anything about the break in animation, but at least the unit present won't be destroyed - and it won't fail the scenario if Ardonna is the one occupying the hex.
=> SotA S2: Avoid destroying unit potentially already occupying target hex

src/picture.cpp, src/picture.hpp
Makes all the cache management functions local to the cache class. There's no reason to publicly expose it through locator given that the actual cache objects which that API needs to function are local to this translation unit anyway.
This also cleans up the cache implementation in order to take advantage of the switch from a vector to map awhile back. `copy_from_cache` was removed in favor of bounds- checked access.
=> Decouple image cache management from locator, and simplify

src/menu_events.cpp
Closes https://github.com/wesnoth/wesnoth/issues/8879
This PR adds handling for empty/null teams when using the `:droid` command.
It now shows an error message:
=> Handling empty team in :droid

data/test/_main.cfg, data/test/macros/wml_unit_test_macros.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage_type/damage_type_alternative_arcane.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage_type/damage_type_alternative_blade.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage_type/damage_type_alternative_cold.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage_type/damage_type_alternative_fire.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage_type/damage_type_alternative_impact.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage_type/damage_type_alternative_pierce.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage_type/damage_type_alternative_three.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage_type/damage_type_alternative_two.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage_type/damage_type_both_same_alternative_best.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage_type/damage_type_both_same_replacement_best.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage_type/damage_type_both_separate_alternative_best.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage_type/damage_type_both_separate_replacement_best.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage_type/damage_type_many.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage_type/damage_type_replacement_arcane.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage_type/damage_type_replacement_blade.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage_type/damage_type_replacement_cold.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage_type/damage_type_replacement_fire.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage_type/damage_type_replacement_impact.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage_type/damage_type_replacement_pierce.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage_type/damage_type_replacement_three.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage_type/damage_type_replacement_two.cfg, wml_test_schedule
@newfrenchy83 currently the alternate_type tests fail since only the defender uses the damage type that deals more damage. The attacker uses the original damage type even though the alternate type would deal more damage.
=> damage_type tests

src/server/wesnothd/server.cpp, src/server/wesnothd/server.hpp
Ensure that there is no coroutine yield between confirmation of login
and update of player_connections_. Otherwise another login under same
name could succeed if it happened before handle_player() which resulted
in an assert later.
=> wesnothd: avoid a race condition when logging on

data/campaigns/Heir_To_The_Throne/scenarios/17_Scepter_of_Fire.cfg, data/campaigns/Heir_To_The_Throne/utils/httt_utils.cfg, data/test/scenarios/wml_tests/ScenarioWML/EventWML/ActionWML/DirectActionsWML/terrain_with_location_filter.cfg, wml_test_schedule
The random map generator can generate starting locations so close that ERASE_CASTLE removed not just the intended castle, but also the keep of the nearby leader. To avoid that, remove the intended keep, then castle that isn't adjacent to a keep.
The ERASE_CASTLE macro is obsolete, using location_id makes the code simple enough that a macro isn't useful. However, as this change is being applied to 1.18, I'm only adding a comment about it.
Fixes #9042. For obvious reasons, tested alongside #9045.
=> [1.18] HttT S17 Don't erase castles from other leaders

data/gui/themes/default/window/gamestate_inspector.cfg, src/font/text.cpp, src/font/text.hpp, src/gui/widgets/multiline_text.cpp, src/gui/widgets/multiline_text.hpp, src/gui/widgets/text_box.cpp, src/gui/widgets/text_box_base.hpp
Resolves #8032.
Uses `scroll_text` instead of `scroll_label` so that text can be copied.
(Should not be squashed.)
_Known issue:_
Could face slight slowdown for large texts, but it won't crash while selecting text or lag during loading.
=> Gamestate Inspector: replace scroll_label with scroll_text

src/gui/core/canvas.cpp, src/image_modifications.cpp, src/image_modifications.hpp, src/picture.cpp, src/sdl/utils.cpp, src/sdl/utils.hpp
Before, every single surface operation would clone the surface before operating and return the new surface. This made for a convenient API, but there's really no reason to do that for the majority of surface mods. Obviously, some of them, like scaling, will need a new surface, so those have been left alone.
=> Conduct surface manipulation in-place when possible

data/tools/wmlscope
It's not just `prune`, but rather `wmlscope: prune`. I discovered this when working on cooljeanius/Flight_Freedom#23 earlier.
=> wmlscope: fix format of magic comment in documentation

data/test/scenarios/wml_tests/ScenarioWML/EventWML/ActionWML/InternalActionsWML/store_locations_and_or_not_unit_filter.cfg, data/test/scenarios/wml_tests/ScenarioWML/EventWML/ActionWML/InternalActionsWML/store_locations_with_unit_filter.cfg, wml_test_schedule
Not sure this is really needed, but it's currently part of a discussion about whether `[filter_weapon][not]special_id_active=foo` should match a unit that has no weapon. So this is checking for reference that `[filter][not]race=elf` excludes every hex that has no unit on it.
=> Add test store_locations_with_unit_filter

src/game_events/manager_impl.cpp
previously is_map_[id] would point to the wrong event, so that when an event was later deleted by id the wrong event would be deleted.
=> fix #9225 events with negative priority getting erroneously deleted

src/wesnoth.cpp
Also print the error before the dialog so you don't first have to dismiss it to see the message on stderr as well.
=> Make command line option errors consistently return 2 as documented

changelog_entries/macos-option-key-label.md, src/hotkey/hotkey_item.cpp
Addresses #9172.
A couple of additional remarks about this:
* It is common for macOS apps to use the standards icons for key modifiers rather than their textual labels, i.e. ⌥ for Option, ⌃ for Control, ⌘ for Command. However, I don't believe there are any official guidelines specifically encouraging this, and since Wesnoth is a game it kind of violates most user interface design guidelines as it is anyway.
* It may make sense to add a combo-based Advanced preferences entry that lets the player choose between "Native", "PC" and "Mac" key labels, but at the same time it's a lot of effort for a niche use case (people with mismatched keyboards that struggle to translate between Mac and PC keyboard layouts).
=> hotkey: Identify Alt as "opt" on macOS

data/campaigns/Liberty/scenarios/01_The_Raid.cfg
Extends damage and not the number of hits, so use "heavier rocks" instead of "more rocks".
=> Fix #9241, Liberty S1 dialogue item tweak

.github/workflows/image_metadata.yml
I don't know how to test this directly in the PR, but I did test in a different repository.
- It only tests for Artist and Copyright tags, I guess the other tags can be optional.
- It doesn't sift through all images in the repository, it just looks at images in a PR.
=> Image metadata CI check

src/filesystem.hpp
Without the change build fails on upcoming `gcc-15` as:
In file included from src/desktop/paths.cpp:20:
src/filesystem.hpp:232:13: error: 'uint8_t' was not declared in this scope
232 | std::vector<uint8_t> read_file_binary(const std::string& fname);
|             ^~~~~~~
=> filesystem.hpp: include missing <cstdint>

data/core/macros/optional_unit_advancements.cfg, data/core/units/undead/Skele_Death_Squire.cfg
The existing {ENABLE_DEATH_KNIGHT} macro allows Revenants to advance to Death Knights. The newly core-ed Death Squire also advances to Death Knight, but has no {ENABLE_DEATH_SQUIRE} macro.
I suggest adding a new {ENABLE_DEATH_SQUIRE} macro, while keeping the old {ENABLE_DEATH_KNIGHT} for backwards compatibility.
I also propose reducing the Death Squire's attack from 8x4 to 9x3, to make the Revenant a more competitive advancement.
Who's the current maintainer of SotA? Should {ENABLE_DEATH_SQUIRE} be used there, or should we continue using {ENABLE_DEATH_KNIGHT}?
Hejnewar, if you approve, what cost should the Death Squire be after this change?
=> Death Squire optional advancement macro and damage nerf

src/scripting/game_lua_kernel.cpp
it previously didn't work as expected because that the variable wasn't given a name, so it locks the map and then immediately unlocks it again.
=> fix map_locker in lua kernel

changelog_entries/gui2-theme-support-in-addons.md, data/schema/gui/widget_definitions.cfg, src/config.cpp, src/config.hpp, src/game_initialization/playcampaign.cpp, src/game_initialization/playcampaign.hpp, src/gui/core/widget_definition.cpp, src/gui/core/window_builder.cpp, src/gui/dialogs/title_screen.cpp, src/gui/dialogs/title_screen.hpp, src/gui/gui.cpp, src/hotkey/command_executor.cpp, src/scripting/lua_gui2.cpp, src/scripting/lua_gui2.hpp, src/serialization/schema_validator.cpp, src/wesnoth.cpp, src/wml_exception.cpp, utils/emmylua/gui.lua
The relevant gui definition should be in `<add-on-dir>/gui-theme.cfg`
**TODO**
=> Support loading gui2 themes from addons

data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage_type/damage_type_apply_to_attacker_filter_attacker_defender.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage_type/damage_type_apply_to_both_filter_self_opponent.cfg, wml_test_schedule
if filtering type of damage in [damage_type] for both self and opponent when apply_to=both, it will create a recursion issue.
Idem for apply_to=attacker/defender when applied to opponent of owner of special.
=> add test for apply_to=both and apply_to=attacker/defender when both type of self and opponent weapon are filtered.

data/core/units/dwarves/Miner.cfg
This was proposed in the forums a while back, and I personally think its a good idea. This changes the Dwarvish Miner to a level 0 unit which can advance to a Dwarvish Ulfserker, Fighter or Guardsman. It also reduces its XP from 50 to 19. The Dwarvish Fighter's stats look like a level 0 unit, and I think it would make sense as one. These are all proposals made by various people on this thread, not myself: https://forums.wesnoth.org/viewtopic.php?t=57995
=> Turn Dwarvish Miners into a Level 0 unit

data/campaigns/Son_Of_The_Black_Eye/scenarios/06_Black_Flag.cfg
- Making Gruu do a suicidal solo charge? Yeah, no.
- To win this scenario, it's imperative that Kapou'e can reach the unoccupied keep at Tirigaz Harbor. His only starting units are Gruu, and maybe Jetto (if he's alive). So, he delays by even a turn, it's a full restart...Thus, we give some hint to the player to focus on the first goal: getting Kapou'e to the keep. 
- Sending Gruu to face side 2 loyalists alone is suicide. He is easily overwhelmed even at level 3 Great Troll.
=> SotBE S6: replace bad advice at turn 2

data/campaigns/Son_Of_The_Black_Eye/maps/07_The_Desert_of_Death.map, data/campaigns/Son_Of_The_Black_Eye/scenarios/07_The_Desert_of_Death.cfg
- add auxiliary camp keep and camp
There is fog of war enabled and no distinct way to tell what the enemy sides are (unless you are playing as a veteran with foreknowledge). We add second keep and camp of 2 hexes to allow player to react to facing the bandits (as in, to recall/recruit a Grunt/Whelp to combat as these types would not be usually recalled since Sand Scuttlers are heavily resistant vs Impact)
- make scorpions avoid villages
Some players have expressed that "it's not fair" that the scorpions would spawn behind them and then damage their per turn income (by stealing villages), leading to low bonus gold at scenario end.
=> SotBE S7: UX improvements

data/core/units/undead/Corpse_Soulless.cfg, data/core/units/undead/Corpse_Walking.cfg
Resolves #9224
Hejnewar says he doesn't have strong feelings about this right now, but that originally it was an oversight to leave Corpse/Soulless arcane resist at -40%. Making this PR to keep things consistent, and also because I think it's a generally positive change.
=> Reduce Corpse/Soulless arcane vulnerablility from -40% to -20%

data/core/macros/names.cfg
So, removing this word for...self-explanatory reasons.
=> Unit Names: remove inappropriate saurian name

data/campaigns/Two_Brothers/scenarios/01_Rooting_Out_a_Mage.cfg, data/campaigns/Two_Brothers/scenarios/02_The_Chase.cfg, data/campaigns/Two_Brothers/scenarios/03_Guarded_Castle.cfg, data/campaigns/Two_Brothers/scenarios/04_Return_to_the_Village.cfg, data/campaigns/Two_Brothers/scenarios/05_Epilogue.cfg
A small tweak to the story text in AToTB that replaces roman numerals for months with Wesnoth’s fictional month names. The months are shown in the in-game encyclopedia. As far as I’m aware, these are 
only used in Liberty and  Eastern Invasion. Presuming they map to the Gregorian months, Scryer’s Bloom is around May and Stillseed is around September.
=> AToTB: Use month names instead of Roman Numerals

src/scripting/lua_widget_methods.cpp, utils/emmylua/gui.lua
previously this function used c++ 0-based indexing, and could  lead to assertions when wrong indicies were used, now it used lua 1-based indicies and throws lua errors on wrong indicies.
=> Fix indices in widget.add_item_of_type()

changelog_entries/fix_infinite_recursion.md, data/test/scenarios/wml_tests/ScenarioWML/EventWML/events-test_filters.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/four_cycle_recursion_branching.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/four_cycle_recursion_by_id.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/four_cycle_recursion_by_tagname.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/special_damage_type.cfg, src/units/attack_type.cpp, src/units/attack_type.hpp, wml_test_schedule
this is a backport of https://github.com/wesnoth/wesnoth/commits?author=stevecotton https://github.com/wesnoth/wesnoth/commit/4afdc92f13eff33f89684e4e9489ff66f87bf17e comit because one change of behavior is to prevent crashes of game
This adds a recursion counter which runs on a per-weapon basis; if the recursion limit is reached then the last level of recursion is assumed to have returned false. A warning is printed (with error severity).
At the user-visible layer, that gives the following logic:
* Abilities that depend on another ability being active will be inactive.
* Pairs of abilities, where X depends on Y being inactive and Y depends on X being inactive, will end up with them both inactive.
The limit is defined by ATTACK_RECURSION_LIMIT in attack_type.cpp. The minimum for passing …
=> Fix weapon special filters can lead to infinite recursion(1.18 backport)

data/campaigns/Northern_Rebirth/scenarios/05a_01_The_Pursuit.cfg
I changed some of the lines in NR The Pursuit to fit better with the different heroes. Tallin, Abhai, Krash. I did not do it for every dialogue.
Addresses issues #8319 and #8772
=> NR05a: Vary dialogue to better suit the speaker

data/gui/themes/default/window/editor_edit_unit.cfg, src/desktop/paths.cpp, src/editor/action/mouse/mouse_action_item.cpp, src/editor/action/mouse/mouse_action_item.hpp, src/editor/controller/editor_controller.cpp, src/editor/controller/editor_controller.hpp, src/editor/editor_display.cpp, src/editor/editor_display.hpp, src/editor/map/context_manager.cpp, src/editor/palette/editor_palettes.cpp, src/editor/palette/item_palette.cpp, src/floating_label.cpp, src/gui/dialogs/editor/edit_unit.cpp, src/gui/dialogs/editor/edit_unit.hpp, src/gui/dialogs/file_dialog.cpp, src/gui/widgets/combobox.hpp, src/hotkey/hotkey_command.cpp, src/preferences/preferences.hpp
1. Item tool: Right click now removes items from the map (https://forums.wesnoth.org/viewtopic.php?t=54905)
2. If an addon is selected using Select active Add-on option, the Unit menu now becomes active and the Unit Type Editor can be accessed.
3. New validation check for filenames with whitespaces.
4. Using comboboxes for Attack range and types that show icons. (Partial custom type/range support)
5. Icons are also shown for race and alignments.
6. Fixes a bug that disabled the Save button when a filename was selected from list instead of typed manually.
7. Unit type editor: Add a quit confirmation to cancel button so the user doesn't lose data.
8. File Dialog: Fix a bug that stopped the user bookmarks from getting saved. (Resolves #9298)
=> Editor enhancements

src/editor/action/mouse/mouse_action_item.cpp, src/editor/action/mouse/mouse_action_item.hpp, src/editor/palette/editor_palettes.cpp, src/editor/palette/item_palette.cpp, src/hotkey/hotkey_command.cpp
Backport of the item tool improvement from #9273 (https://github.com/wesnoth/wesnoth/commit/7065ed9fde535e14b45a3e8bad1dfc74ea663b9f). This allows to remove items by right clicking with the unit tool.
=> [1.18] item tool: add right-click to remove functionality

src/display.cpp
fix https://github.com/wesnoth/wesnoth/issues/9305 issue.
ter_sub was not include in if loop condition and submerge calculation made a multiply by zero.
=> fix submerge item issue

data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/special_calculations.cfg, wml_test_schedule
Fix a typo in the add_sub_separated test, because it was testing exactly the same code as add_sub_cumulative.
Add two new tests and clarify documentation, because in these tests the order of the abilities determines whether the add or sub value is used, it isn't that sub always overrides add.
Will merge-conflict with #7271, but I'd prefer to have this merge first, documenting what the behavior was, and then have #7271 change the tests as documentation of what it changes.
=> Test calculations of abilities with add and sub

.github/workflows/codeql.yml, CMakeLists.txt, INSTALL.md, SConstruct, changelog_entries/boost-to-82.md, packaging/flatpak/org.wesnoth.Wesnoth.json
1.82 adds boost::mysql, which Pent means to make use of, and 1.78 adds boost::span, which I want to make use of.
=> [For CI] Bump min Boost to 1.82

data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/attacks/attacks_add_sub.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/chance_to_hit/chance_to_hit_add_sub.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/damage/damage_add_sub.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/drains/drains_add_sub.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/heal_on_hit/heal_on_hit_add_sub.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/heals/heal_add_sub.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/illuminates/illuminates_add_sub.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/leadership/leadership_add_sub.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/regenerate/regenerate_add_sub.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/resistance/resistance_add_sub.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/special_calculations.cfg, src/units/abilities.cpp
when two special weapons use multiply and divide with the same id, both operations are used, isn't that so why should it be different with 'add' and 'sub' where it's the larger value that is used (if asub=value_sub and add=value_add are used and value_sub>value_add then value_sub is used). This logic is counter-intuitive. that multiplication/division is applied to (base_value +- add/sub) is understandable but not this discrimination. For me add and sub should still be usable; even if it means changing the rules, but I think we will gain clarity in the end.
=> change calculation rules so that add and sub are always used independently

data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/special_calculations.cfg, wml_test_schedule
Fix a typo in the add_sub_separated test, because it was testing exactly the same code as add_sub_cumulative.
Add two new tests and clarify documentation, because in these tests the order of the abilities determines whether the add or sub value is used, it isn't that sub always overrides add.
(cherry picked from commit 547de5fd93c5dca321c4382c265a90d93ed3f30b)
=> [1.18] Test calculations of abilities with add and sub

data/core/editor/help.cfg
Updates the help page entry for the item tool to reflect the changes in 7065ed9fde535e14b45a3e8bad1dfc74ea663b9f, in particular, that removal of items is now possible. Should be backported.
=> Update the help page entry for the Item tool

src/hotkey/hotkey_command.cpp
Unit description is not yet implemented. Once it is, I expect menu item is changed back to unit description, while the opened dialog has link to navigate to unit type description.
=> Clarify unit type description label

src/units/abilities.cpp
Like unit recursion depth is to 3 and attack recursion 4, what count begin if and only if ability_(id/type) active called is more appropriate.
=> Remove unit recursion of special_unit_matches() 

src/scripting/lua_widget.cpp
Enables length operator for listbox, multi_page, tree_view and tree_view_node, e.g. 
`dialog.lb_slider.max_value = #dialog.lb`
number_of_items() was recently added to lua_widget_methods.cpp.  I kind of feel like that should be moved somewhere where it can be shared, for example I could use it here instead of replicating the work.  Wouldn't save anything here, but it'd be consistent.  I'm just not sure if it's worth doing, or where it would go.  Or perhaps all containers should have the same get_item_count()?
=> GUI2/LuaAPI: add len operator to container widgets

changelog_entries/non-ascii-case-insensitve-filtering.md, src/game_initialization/lobby_data.cpp, src/gui/dialogs/addon/manager.cpp, src/gui/dialogs/game_load.cpp, src/menu_events.cpp
Attempt to resolve #9328.
Caveats:
1. This is based purely on the discussion from the linked issue. I don't know if I've covered all the details discussed therein.
2. This seems to work for me, but at present I don't have non-ASCII characters in my saved game names, so I can't properly test this.
3. The game load dialogue isn't the only place where case-insensitive searching is limited to ASCII characters. If this change is accepted, then potentially it could be applied to other searches:
https://github.com/wesnoth/wesnoth/blob/47642719bf4e5519945f99d579c926d43725a04d/src/gui/dialogs/addon/manager.cpp#L68-L77
https://github.com/wesnoth/wesnoth/blob/47642719bf4e5519945f99d579c926d43725a04d/src/menu_events.cpp#L1393-L1397
https://github.com/wesnoth/wesnoth/blob/47642719bf4e5519945f99d579c926 …
=> Extend case-insensitive filtering beyond ASCII characters

data/gui/themes/default/window/preferences.cfg, data/gui/themes/default/window/preferences/03_display.cfg, src/gui/dialogs/preferences_dialog.cpp
Moves the Apply button beside the UI Theme list and disables it unless the theme is changed.
This also makes it obvious that the Apply button is used only for UI theme selection, and is not a global Apply button.
=> Preferences: move the Apply button and disable it unless needed

data/test/scenarios/macro_tests/test_force_chance_to_hit_macro_nested.cfg, data/test/scenarios/macro_tests/test_force_chance_to_hit_macro_toplevel.cfg, wml_test_schedule
It should work even when the macro appears in the same event as the attack; this tests that.
The new one uses the COMMON_KEEP macro, but I've left the existing one unchanged, except for the renaming.
=> Add a second unit test for TEST_FORCE_CHANCE_TO_HIT

src/display_context.cpp
This code sets orb color to can-still-make-an-action if unit has no moves left, and has a visible enemy within max and min range of a weapon.
This also affects if the unit is selectable with 'N' (units that can move or attack).
Currently, it doesn't affect the mainline much, as no unit has a weapon max/min_range different from 1, most notice-able, it marks units with no attack as incapable of action, after having no moves left.
The purpose of this is part of getting real-ranged attacks into the mainline.
=> Make status orb work with custom max/min_range

data/campaigns/The_Rise_Of_Wesnoth/_main.cfg, data/campaigns/Winds_of_Fate/scenarios/09_Ancestor.cfg
This follows the typography style guide.
=> Use proper apostrophe to spell Shek’kahan

data/schema/units/abilities.cfg, data/schema/units/specials.cfg, data/test/scenarios/wml_tests/ScenarioWML/EventWML/events_in_ability_and_special_tags.cfg, data/test/units/events_in_ability_and_special_tags.cfg, src/units/unit.cpp
This aims to better support abilities and weapon specials which rely on events written in WML, like those on this [page](https://wiki.wesnoth.org/Wml_abilities
). Currently such event code has to be loaded explicitly in each `[campaign]`, `[scenario]`, `[era]`, or `[resource]` where the custom ability or special will be used, or otherwise written directly in the `[unit_type]`. By supporting embedded events in the `[abilities]` and `[specials]` tags this code can load automatically whenever a unit with a custom ability or special is spawned.
=> Support events in [abilities] and [specials] tags

src/game_events/manager_impl.cpp
previously is_map_[id] would point to the wrong event, so that when an event was later deleted by id the wrong event would be deleted.
=> [1.18] fix #9225 events with negative priority getting erroneously deleted

src/display.cpp, src/display.hpp
* Makes it more type-safe by using chrono types more directly.
* Fixes a few design issues, such as the current time point being taken multiple times when updating the data.
* Fixes min and map FPS times being swapped
=> Display: clean up the FPS counter implementation

data/gui/themes/default/widget/chatbox.cfg, data/gui/themes/default/widget/multiline_text_default.cfg, data/gui/themes/default/widget/scroll_text_default.cfg, src/desktop/clipboard.cpp, src/desktop/clipboard.hpp, src/editor/controller/editor_controller.cpp, src/events.cpp, src/font/text.cpp, src/font/text.hpp, src/gui/dialogs/chat_log.cpp, src/gui/dialogs/editor/custom_tod.cpp, src/gui/dialogs/game_cache_options.cpp, src/gui/dialogs/game_version_dialog.cpp, src/gui/dialogs/gamestate_inspector.cpp, src/gui/dialogs/lua_interpreter.cpp, src/gui/dialogs/screenshot_notification.cpp, src/gui/dialogs/wml_error.cpp, src/gui/widgets/chatbox.cpp, src/gui/widgets/label.cpp, src/gui/widgets/multiline_text.cpp, src/gui/widgets/multiline_text.hpp, src/gui/widgets/password_box.cpp, src/gui/widgets/password_box.hpp, src/gui/widgets/scroll_text.cpp, src/gui/widgets/scroll_text.hpp, src/gui/widgets/styled_widget.cpp, src/gui/widgets/text_box_base.cpp, src/gui/widgets/text_box_base.hpp, src/widgets/textbox.cpp
Resolves #1206.
This allows text to be selected from the MP lobby chat log area.
Introduces the following two keys in `multiline_text` and `scroll_text`: `use_markup` and `link_aware`. Markup support only works for non-editable text areas only ATM, which is relevant to the usecase of #1206. Editable text areas with formatted text are outside the scope of this PR, but may be done in future (that essentially makes `multiline_text` a pango rich text editor).
=> Multiline markup and link support and MP lobby text copy support

data/core/editor/help.cfg
This note was previously borderline unreadable on my screen. This makes it slightly large. Still not as large as the other text, but it should be a bit easier to read.
=> Increased text size for UMC Author note in terrain elevation help page

data/campaigns/Dead_Water/scenarios/09_The_Mage.cfg
This PR adds a dialog, when you enter Caladon's house with a bat to prevent the scenario being too easy.
=> [Campaign][Dead Water] S9: improve event handling of bat units in player side (fixes #8766)

src/display.cpp, src/display.hpp, src/editor/action/mouse/mouse_action_item.cpp, src/overlay.hpp, src/scripting/game_lua_kernel.cpp
Instead of passing all the arguments for an overlay to display::add_overlay, just take an rvalue-reference to an existing overlay object.
The overlay ctor was adjusted. It no longer takes a halo::handle argument, and the display class sets that manually.
=> Display: simplify add_overlay interface

src/gui/widgets/widget.hpp
=> The NOT_DANGLING specifier should be before the const attribute

data/campaigns/Under_the_Burning_Suns/_main.cfg
This makes a lot more sense given how forgotten everything before the fall is by the time of UtBS. 300 AF is small enough for a few elves to remember the times before. 1000 AF is more sensible in my opinion. This a change I proposed in #9398 but decide to split into another PR.
=> Change UtBS date from 300 to 1000 AF

data/campaigns/Eastern_Invasion/units/Human_Dacyn_Fallen_Mage.cfg, data/campaigns/Eastern_Invasion/units/Human_Dacyn_Twilight_Mage.cfg
In EI, Dacyn transforms into a Twilight Mage and then Fallen Mage, meant to foreshadow his transition towards undeath.
The original arcane resistances for these forms were set before the 1.18 arcane rework. In particular, it's odd that Fallen Mage Dacyn (who's still visibly human) has worse arcane resist than a lich or a skeleton.
Even if the arcane changes proposed in #9392 go through, these proposed Dacyn stats should still be reasonable.
=> EI: update Dacyn arcane resistance to be consistent with the arcane rework

changelog_entries/ei-drowned-plains-redesign.md, data/campaigns/Eastern_Invasion/scenarios/14_The_Drowned_Plains.cfg, data/campaigns/Eastern_Invasion/scenarios/16_Eleventh_Hour.cfg
Drowned Plains is one of the most-criticized EI scenarios. It has a 75 turn limit, and involves trudging across swamp while enduring ambushes to kill 3 enemy leaders.
This revision drastically shortens the scenario to only 25 turns, and changes the objective to _'Gather as much gold as you can before turns run out'_. Enemy leaders have piles of gold nearby, to reward killing them (or luring/stealing from them).
I played through this once to verify the balance was at least plausible and that nothing was completely broken, but it's possible I missed something. Please let me know if anything looks incorrect.
=> EI S14 "Drowned Plains" - rework scenario objective

src/config.hpp, src/config_attribute_value.cpp, src/config_attribute_value.hpp
Fixes:
* `cfg["foo"] = std::move(value)` is now allowed
* `config { key, value }` will no longer fail if `value` is a const config reference (it worked with a non-const reference)
`config::all_children_view` is meant to replace `all_children_range` for the vast majority of cases in which you just need the iterate over tags without saving the iterator. It's easier to read, code-wise, it fixes the issue of `any_child` always holding a mutable reference even when the owning config was const, and intellisense now properly shows key/value types as references when destructuring (rather than value as with `all_children_range`).
=> More config stuff

data/core/units/monsters/Horse_Dark.cfg, data/core/units/monsters/Horse_White.cfg, data/core/units/monsters/Sand_Scamperer.cfg, data/core/units/monsters/Sand_Scuttler.cfg
Out of all 311 core units, only 5 relatively newly added units use `[base_unit]` tag as a part of their definition (Dark Horse, White Horse, Sand Scamperer, Sand Scuttler, and Fire Ant Egg).
To keep the consistency, and to prevent the potential nested structure of `[base_unit]` of `[base_unit]` in modified units, it is probably better to define core units without the tag.
1. Dark Horse, White Horse, Sand Scamperer, and Sand Scuttler are now defined without `[base_unit]` by copy-pasting data from respective base units.
2. The deprecated variation of Giant Scorpion (moved to Sand Scuttler) is untouched just in case, but it should be removed in the future.
3. Ant_Egg.cfg is the only file that defines 2 units (Giant Ant Egg and Fire Ant Egg) within a single file. They should be separate in my …
=> Define core units without [base_unit] tag (Horse, Scorpion, Ant Egg)

src/units/abilities.cpp
- Resolves #9366
- By setting the bouncing back logic of strike times to only happen when attributes are used incorrectly(meaning sub is non-negative at the same time)
- #9366
- This is a bug fix.
Adjust possibly missed related method.
This PR is a Work In Progress.
see changes in the src.
=> Fix weapon special unexpected behaviour

src/game_initialization/connect_engine.cpp, src/game_initialization/connect_engine.hpp
Resolves #9407 where status dialog team names are not changed, when changed at game start.
=> Status table team name fix

data/core/units/monsters/Cat_Jump.cfg
Alongside PR #9420, I also noticed that the new Jumpcat's current stats have some glaring problems:
1. first and most important, despite being a lvl1 unit it, he has, all at the same time: 9mp, a 12-2 attack that also has 10 accuracy bonus, nightstalk, parry on melee, and all this while only costing 15 gold
2. on the subject of parry, I believe using parry on an elusivefoot unit is too much, as the jumpcat will have 80% dodge chance on many types of terrain, while normally dodge chance is pretty much never above 70% in wesnoth.
I think heavily nerfing the unit to the point of being on par with other lvl1 would take away the unit's uniqueness, and it's cool to have a powerful non-undead nightstalk unit, so instead I propose rebalancing the unit into a lvl2:
level from 1 to 2 (massive …
=> [Units][Jumpcat] Rebalance Stats

data/core/units/ogres/Young_Ogre.cfg
According to the typography style guide (https://wiki.wesnoth.org/Typography_Style_Guide#Race_Names) race names should not be capitalized in Wesnoth. While ogres are a unit, in the context of the young ogre description this probably to reffers to the race and not the unit.
=> Properly capitalize Young Ogre description

data/schema/pbl.cfg, src/addon/validation.cpp, src/addon/validation.hpp, src/gui/dialogs/addon/manager.cpp, src/gui/dialogs/editor/edit_pbl.cpp
With custom gui2 theme support in #9057, it is now possible to create addons that supply UI Themes or Skins. This adds support so such addons are properly recognized and validated.
A new addon type, `theme` is now recognized in the PBL file as well as the Addons Manager and PBL Editor.
=> Add support for UI Theme addon type

src/gui/widgets/window.cpp
Resolves #9443 and partially deals with #1239.
The first SDL_KEY_DOWN handler is being called twice, while the second one is being called once. The tab order handling is done by the first handler, which caused the focus to move *twice*, resulting in the erratic behavior when tab was pressed. Moving the tab handling to the second one stops this and now focus moves only once when Tab is pressed.
Original code:
https://github.com/wesnoth/wesnoth/blob/1ca69e1ecaf8fe387f3ea6220671c842c250cc3b/src/gui/widgets/window.cpp#L322-L327
=> GUI2: Fix broken tab order

data/schema/filters/unit.cfg, data/test/scenarios/wml_tests/ScenarioWML/EventWML/events-test_filter_ability.cfg, src/units/filter.cpp
Resolves https://github.com/wesnoth/wesnoth/issues/7926
Under pressure from @soliton-, I agree to merge [filter_ability] and [filter_ability_active] into a single filter equipped with the 'active' attribute which when the value is 'true' checks the units affected by the sought ability and when the value is 'false' will check the units carrying the ability even if they are not affected by it.
Because of the attribute strategy, I'm afraid that the developer will be mistaken about its function and that's why I'm not at all keen on it. (is it so bad to keep two tags like for ability_type and ability_type_active? there it would be clearer for those who manipulate these attributes because of the resemblance)
=> Create in [filter_ability] an attribute 'active' to replace _active suffix in [filter_ability_active]

src/units/abilities.cpp, src/units/attack_type.cpp, src/units/attack_type.hpp, src/units/unit.hpp
When I use an ability id=A and include [filter][filter_adjacent]ability_id_active=A, the more units with the adjacent ability I add to it, the slower the game becomes, and at the third unit the game freezes, whereas with the direct comparison of the configs the game only slows down significantly after the 5th unit added.
=> Replace the recursion decoptge method with the less CPU-intensive config comparison method

src/display.cpp, src/floating_label.cpp, src/gui/core/canvas.cpp, src/sdl/rect.cpp, src/sdl/rect.hpp
Unsure if I should add a `shrink_by` function or keep the current `grow_by(-amount)` approach. Also, `grow_by` is a little inconsistent with the other const helper functions (`shifted_by`, for instance). Considering `adjusted_by`?
=> Rect: add grow_by, point_at, and subrect

src/server/campaignd/server.cpp
... to fix compile issues with boost 1.86.
Commit 9c665ae3c4684f8826f4b7d8e0a75b9a986e8617 does the same for wesnothd, but campaignd still fails to compile with overload resolution failure.
References  #9284
=> campaignd: Use completion token overload

src/actions/attack.cpp, src/gui/dialogs/attack_predictions.cpp, src/reports.cpp, src/scripting/lua_unit_attacks.cpp, src/units/attack_type.cpp, src/units/attack_type.hpp
while retesting the alignment in lua I realized that the fallback was not working as I thought, so I'm coming back to a solution so that the value of string in the case of a non-existent attack alignment is empty if the value of the unit alignment is not available.
=> Change the alignment code in attack to return an optional value and avoid falling back to neutral alignment when unit alignment is not available.

src/editor/controller/editor_controller.cpp
Resolves #9226. Game no longer crashes when clicking menu bar after setting unit facing.
=> Scenario editor, unit facing, game crash fix

copyrights.csv
This music would be useful in core. I don't have to change any WML as I'm not actually changing any playlists. It's still specific to EI. The difference here is UMC creators can more easily use them without copying unnecessary files.
Edit: Failed copyright checks. Is music still using copyrights.csv?
Eidt 2: Looks like it is. I thought it was replaced with a metadata system.
=> Move Cry from Elensefar to Core

data/gui/themes/default/window/campaign_dialog.cfg, src/game_initialization/singleplayer.cpp, src/game_launcher.cpp, src/gui/dialogs/campaign_selection.cpp, src/gui/dialogs/campaign_selection.hpp
Resolves #8478 by adding an entry to open the Add-ons manager in the campaign list.
=> campaign selection: opening add-ons manager entry

src/savegame.cpp
I'll grant this is really old text, introduced in 2007 (1.3.13) in 22ad729bccab7d52f06e71a02fbcd6816a36da9e, but the text as it stands really doesn't read right to me.
This also aligns better with the line immediately below it:
https://github.com/wesnoth/wesnoth/blob/c284a080e3d7c93652598bb71b1bad95620263f6/src/savegame.cpp#L436
=> Save game: text correction

data/core/editor/help.cfg, data/core/help.cfg
#3653 and subsequent related commits prompted a change in translated strings and I found a few more issues. Primarily I want to avoid including mark-up in the translated strings (last commit here), hopefully to reduce the burden on translators if the strings in question haven't already been changed fundamentally. A lot of the strings include mark-up already (part of the problem) but at least we shouldn't be including new mark-up where none existed previously.
=> Help text review

src/soundsource.cpp
Resolves #9453. Sound source full_range and fade_range are now allowed to be 0. When fade_range=0 division by zero prevented.
=> sound source zero fade rangefix

src/countdown_clock.cpp, src/events.cpp, src/events.hpp, src/sound.cpp, src/utils/rate_counter.hpp
Probably going to add more to this. Main functional change is using native SDL handling for double clicks, which means the click radius has bumped to 32px. Double click time remains unchanged (500ms), though I think SDL queries it from the OS on Windows (https://github.com/libsdl-org/SDL/blob/SDL2/src/events/SDL_mouse.c#L49-L75). Shouldn't be an issue though.
=> Events stuff

data/core/units.cfg
https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/Winds_of_Fate/story/Past_and_Future_Drake_History_(Spoilers).txt
This contradicts the unused drake history file in WoF, which shows the elves appeared after many other races, like drakes, trolls and many others.
CC: @Dalas121
=> Make sure Elvish Race Description doesn't contradict WoF

.github/workflows/image_metadata.yml
GIMP can read/write Creator and Rights XMP tags in PNGs, unlike the tags in the PNG or EXIF chunks.   Fixes #9312 
Maybe XMP should be used for everything, but at least for Dolphin, I can see the Artist & Copyright under PNG or EXIF, and nothing for XMP.  Is that just Dolphin weirdness, or is it a similar case for Windows and Mac?  If XMP isn't as visible, it would make sense to just use that for PNG files, while leaving the larger WebP and JPEG files with EXIF, since those are more likely to be "browsed" and shouldn't need "small fixes".
This is to change the CI.  A follow-up to migrate the data in existing PNGs will be a separate PR.
=> Use XMP metadata for PNG files

data/campaigns/Liberty/scenarios/05_Hide_and_Seek.cfg
The event never fired because it has to use side 3 (side 2 is idle). After fixing that, the event fires, but the IF_VAR statement is always false unless you remove the dollar sign.
=> Fix the attack_end event in Liberty S5

src/gui/dialogs/editor/custom_tod.cpp
Closes #9492. Bonus spelling correction.
The four translated strings are listed in https://github.com/wesnoth/wesnoth/issues/9492#issuecomment-2432013072.
=> Re-use translation strings from wesnoth-lib instead of duplicating them in wesnoth-editor

changelog_entries/thot_achievements.md, data/campaigns/The_Hammer_of_Thursagan/achievements.cfg, data/campaigns/The_Hammer_of_Thursagan/scenarios/04_High_Pass.cfg, data/campaigns/The_Hammer_of_Thursagan/scenarios/06_Forbidden_Forest.cfg, data/campaigns/The_Hammer_of_Thursagan/scenarios/09_The_Underlevels.cfg
The following achievements have been added:
- Gryphon Hunter: Kill the Gryphon leader in High Pass
- Conqueror of the Forest: Defeat an enemy leader in Forbidden Forest
- New Thursagan: Complete The Underlevels on challenging difficulty
=> Add achievements to THoT

data/test/scenarios/wml_tests/ScenarioWML/EventWML/events-test_filter_ability.cfg, src/units/abilities.cpp
In special_id/type without the _'active' suffix only the encoding of the special in the attack is checked, and therefore the specials encoded in the [abilities] tags are de facto excluded, except that I forgot this logic in [filter_special] and I have to fix my error before updating the wikia.
=> Fixed an error in [filter_special] encoding

src/scripting/lua_widget.cpp
Simply adds the ability to do something like `#dialog.my_stacked_widget`.
I started out wanting to make the sw more like other container widgets, where you could add and remove layers, etc.  Removing is simple, adding not so much.  I really can't think of any good use cases for adding layers, other than perhaps removing and adding layers as a way of changing the order of layers.
Along the way I found that the stacked_widget seems to be a little odd, particularly from the Lua API.  FWIW....
WML/LUA:
Initially, all layers are visible, selected_index returns 0, and events go to last (highest index) child.  Widgets may be made in/visible using sw[3].id3.visible (this is acting on the child widget, NOT the stacked_widget).
If you set selected_index (say =2), that widget becomes the only …
=> GUI2 stacked_widget - add length operator

changelog_entries/tweak_elvish_marshal.md, data/core/units/elves/Marshal.cfg
Since the 1.18 elf enhancements were deemed excessive and received a rollback of one sort or another, there is no reason to leave Marshal in an over-enhanced form. 
However, a full rollback to 1.16 was found to be controversial. I propose a different solution: 
```
HP: 68 -> 62 
MP: 5 -> 6 
```
This way, Marshal will lose some combat power, but will become stronger as a leader. This will emphasize his differences from the Champion and equalize both options in terms of strength.
=> Tweak Elvish Marshal Stats

data/campaigns/Sceptre_of_Fire/scenarios/7_Outriding_the_Outriders.cfg
This reverts commit b3802f44ea1d50364c83e00d207e8dcef04645b4.
Since commit 70df290 restores the Elvish Outrider to essentially its original stats, the 1.18 balance fix for this one campaign scenario is no longer useful.
=> Revert "SoF S7: fewer and slower enemy outriders"

data/core/macros/weapon_specials.cfg, data/core/units/monsters/Cat_Forest.cfg
Looking at the brand-new 1.19 cat stats. The concept is neat but I believe the unit is a bit overtuned (and Jump Cat is very overtuned, but I will get to that one in another PR) with 9mp, 15-2 attack and 21 cost a once. Though on the other hand, using attack/defense weights seems a bit too not-user-friendly since that mechanic is not visible in-game, so I propose the following changes with my PR
arcane resistance from 20% to 10%
claws from 5-4 to 6-4 now usable on offense
bite from 15-2 to 9-2 charge, now usable in defense
price from 21 to ~~27~~ 30
MP from 9 to 7
HP from 42 to 48
EDIT: reduced price to 24
EDIT2: reverted damage numbers but nerfed MP to 7 as suggested by Dalas
EDIT3: another rebalance around making it a charge unit
EDIT4: increased price to 30
=> [Units] Adjust Forest Lion Stats

data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/ability_cycle_filter_weapon_recursion.cfg, src/units/abilities.cpp, wml_test_schedule
In moving recursion_guard from matches_filter() to special_unit_matches() i has forgotten what [leadership] abilities called directly matches_filter().
=> add recursion_guard in [filter_(second_)weapon] for [leadership] and [resistance] abilities.

src/gui/dialogs/unit_list.cpp, src/gui/dialogs/unit_recall.cpp
error cause to show text of color code instead of use for color level number(same fix what for https://github.com/wesnoth/wesnoth/commit/37b7a83ce08f34f3fcc5036b9e16f824d234355f#diff-010538c81e10d3e4eeadfb49808ab52a6fe1becc787cb247c6a854b8f4c1900aL104)
=> fix malformed markup in unit_list and unit_recall

src/actions/undo.cpp
previously in `undoable_action->undo(side_) ` the undo stack was not in sync with the relpay stack becasue the code called `undos_.pop_back();` before that and `resources::recorder->undo_cut` after that, this could confuse the code which sends replay commands to the other clients.
=> fix #9561 OOS when undoingin multiplayer

data/campaigns/Eastern_Invasion/scenarios/02_The_Escape_Tunnel.cfg
In the existing code, on HARD difficulty, creating a unit with id="Hur" is done twice, first as a Troll Whelp, then as a Troll Rocklobber. As a result, the former unit is replaced with the latter one. As they are created at the same coordinates, I believe this is the intended behavior.
But according to https://wiki.wesnoth.org/SingleUnitWML , reusing the id "may produce unpredictable results in many cases". For example, (I tested it) if you create the new unit at the different coordinates, it instead appears at the former unit's coordinates.
I've added another preprocessor directive, so the unit with this id is created only once on both NORMAL and HARD.
=> EI S02: Avoid creating unit with same id twice

data/campaigns/Eastern_Invasion/scenarios/01_Eastern_Invasion.cfg
The outposts are east of River Weldyn in the campaign map. Also, in scenario 1, the castle is east of the river. The heartland of Wesnoth country is west of that river, so the  eastern bank is the "far" one.
These words date back to the original campaign design by Eric S. Raymond. Back then, the campaign map had the outposts on the western bank of Weldyn.
But in aeb9ec7 the map was replaced with a newer one, with outpost on the eastern bank, which persists to this day with some minor changes (like the southern outpost was moved futher south).
=> EI S01 story: Fix outposts locations accorting to campaign map

src/serialization/markup.cpp, src/serialization/markup.hpp
Internal escaping causing markup failure when tags are nested. See #9569 and #9572 for example. Functions in markup will no longer escape their contents, and those should be escaped by caller if needed.
=> markup: don't escape internally and update docs

changelog_entries/change_huntsman_ranger, changelog_entries/change_huntsman_ranger.md, data/core/macros/abilities.cfg, data/core/units/humans/Woodsman_Huntsman.cfg, data/core/units/humans/Woodsman_Ranger.cfg, data/core/units/monsters/Crocodile.cfg
These Ranger changes are an attempt to raise his power closer to the Master Bowman or Elvish Avenger, while also cementing his role as a wilderness rover - powerful in the wild but vulnerable in castle/village.
These Huntsman changes are an attempt to help him better-fill the role of a frail mage-equivalent for the bandits (who otherwise lack Marksman/Magical), while adding some hunting flavor and a useful niche with "swamp lurk".
=> Change Human Ranger and Huntsman

src/editor/palette/tristate_button.cpp
Fixed palette button not being clickable after scrolling in palette widget without moving the cursor. Resolves #1335. The cause of the bug was that scrolling doesnt change the highlighted state of the palette buttons and not highlighted buttons didnt process being clicked. Solved the bug by making not highlighted buttons process being clicked.
=> Editor terrain button click fix

src/editor/palette/tristate_button.cpp
Backport of #9560, opening a PR to run the CI.
Fixed palette button not being clickable after scrolling in palette widget without moving the cursor. Resolves #1335. The cause of the bug was that scrolling doesnt change the highlighted state of the palette buttons and not highlighted buttons didnt process being clicked. Solved the bug by making not highlighted buttons process being clicked.
(cherry picked from commit 484116ea09ab3bf0ac6cddd5340458dd91ea8730)
=> [1.18] Map Editor terrain button click fix (#1335)

src/gui/widgets/combobox.hpp, src/gui/widgets/scroll_label.hpp, src/gui/widgets/scroll_text.hpp, src/gui/widgets/slider.hpp, src/gui/widgets/text_box.hpp, src/gui/widgets/text_box_base.hpp, src/gui/widgets/tree_view.hpp, src/gui/widgets/widget.hpp, src/scripting/lua_widget_attributes.cpp, src/scripting/lua_widget_attributes.hpp, utils/emmylua/README.md, utils/emmylua/gui.lua
Obviously, the Lua API is missing a lot of stuff, for example you can set a styled_widget enabled (active), but you can't check whether it is enabled.  Some of these are pretty obvious, others I'm not sure what, if anything, to do with.
The attached spreadsheet contains a bunch of "attributes" I've found, whether because they can be set in WML, or just have a public member function, or whatever.  It's a complete mess atm, but it seems like it would be useful to have the data in one place.
No real reason to push at this point, except that I know I'm going to have a lot of questions.  For example...
**visible**
- current can be set (not get) for styled_widget, though the function is a member of widget
- Currently, from lua you can set via string (visible,invisible,hidden) or bool …
=> GUI2 LuaAPI: expand widget attr support

data/campaigns/Eastern_Invasion/scenarios/03_An_Unexpected_Appearance.cfg
This scenario aims to have a custom dialogue if Gweddry or Dacyn are killed by Mal-Tar's side (event on line 294). The comment on line 339 suggests that their normal "last breath" events (HERODEATH macros) are added only after Mal-Tar is dead. However, these macros are also added at the bottom of the file (line 438). This leads to a couple of minor bugs:
* If Gweddry or Dacyn are killed by Mal-Tar, a chat message "\<Lua\> Repeated [endlevel] execution, ignoring" appears in the top left corner of the screen. That's because it is executed in both this scenario's "die" event, and the "last breath" included by the macro.
* If Mal-Tar is killed, the "last breath" events for both Gweddry and Dacyn are duplicated. So, if one of them is killed afterwards, you need to press the space button twice …
=> Fix issues with hero deaths in EI S03

changelog_entries/macos-font-render-backend.md, src/wesnoth.cpp
Fixes #8488 based on my first suggestion there since there doesn't seem to be any particular interest around here in pursuing the second path — the issue has been dormant for months with multiple stable and development releases tagged in the meantime and a wholesale refresh of the main menu making it even more visible to users.
Ideally we would instead figure out how to fix Oldania ADF Std to work on newer macOS, but since we know the Fontconfig backend works for us on Windows and Linux, we may as well stick to it and hope there will never be a situation where CoreText would prove superior somehow.
This patch is equivalent to invoking Wesnoth with `PANGOCAIRO_BACKEND=fontconfig wesnoth`, with the difference being that we don't overwrite the environment variable if it already exists (e.g. …
=> Switch default Pango/Cairo render backend to Fontconfig on macOS

doc/man/wesnoth.6, src/commandline_options.cpp, src/commandline_options.hpp, src/editor/map/map_context.cpp, src/serialization/preprocessor.cpp, src/serialization/preprocessor.hpp, src/wesnoth.cpp
Resolves #9580.
Adds a `preprocess_string` method that allows to run the preprocessor on a string. Example:
https://github.com/wesnoth/wesnoth/blob/0088534cd91b4331fe0ed5e9fcf992e93a1b8ea8/src/editor/map/map_context.cpp#L762
Also, the Loyal trait will now be written inside `[modifications]`.
TODO:
=> add preprocess_string method and use preprocessed loyal trait

data/campaigns/Eastern_Invasion/scenarios/04b_Ill_Humors.cfg
These two variables are used everywhere else in this scenario, hardcoding the amounts here must've been a mistake.
=> Use variables for deducting gold in EI S04b

src/formula/format_timespan.hpp, src/formula/string_utils.cpp, src/formula/string_utils.hpp, src/game_initialization/multiplayer.cpp, src/log.cpp, src/serialization/chrono.hpp, src/server/wesnothd/metrics.cpp, src/tests/test_formula_timespan.cpp
Required a rather in-depth refactor since we're now dealing with distinct types for the different durations. This also adjusts the periods for years and months. Previously, we were using values of 30 days for a month and 12 months for year. Now, we use the chrono values of a month as 1/12 of a year and a year as 365.2425 days.
Requesting a review from Iris since she implemented the function originally.
=> Refactor utils::format_timespan to use chrono types

.clang-tidy, .github/workflows/ci-main.yml, .gitignore, CMakeLists.txt, SConstruct, src/CMakeLists.txt, src/config_cache.cpp, src/conftests/sdl2_audio.cpp, src/conftests/sdl2_jpg.cpp, src/conftests/sdl2_png.cpp, src/conftests/sdl2_webp.cpp, src/crypt_blowfish/.clang-tidy, src/gui/core/event/distributor.cpp, src/gui/widgets/chatbox.cpp, src/hash.cpp, src/log.cpp, src/modules/CMakeLists.txt, src/picture.cpp, src/playsingle_controller.cpp, src/preferences/preferences.cpp, src/scripting/application_lua_kernel.cpp, src/scripting/lua_terrainfilter.cpp, src/server/campaignd/auth.cpp, src/tests/utils/fake_display.cpp, src/utils/general.cpp
clang-tidy is a linter tool that automatically checks for common code quality issues. This PR adds a cmake option `DCLANG_TIDY` that when set with `DCLANG_TIDY=ON` will automatically lint Wesnoth's code for the issues specified in `src/.clang-tidy`
As a representative example, the `NULL` macro is an implementation-defined keyword that is typically the integer 0. This causes issues because it is not actually a pointer type, and so will trigger integer overloads of methods preferentially to pointer overloads. In C++11, the keyword `nullptr` was introduced which is actually a pointer type and doesn't have this problem. This PR removes the last remaining usages of `NULL` or `0` from the codebase and enables `clang-tidy` to check for usage of `NULL` automatically.
Git submodules not owned by …
=> Enable clang-tidy and refactor NULL to nullptr

src/actions/create.cpp, src/actions/move.cpp, src/actions/shroud_clearing_action.cpp, src/actions/shroud_clearing_action.hpp, src/actions/undo.cpp, src/actions/undo.hpp, src/actions/undo_action.cpp, src/actions/undo_action.hpp, src/actions/undo_dismiss_action.cpp, src/actions/undo_dismiss_action.hpp, src/actions/undo_move_action.cpp, src/actions/undo_move_action.hpp, src/actions/undo_recall_action.cpp, src/actions/undo_recall_action.hpp, src/actions/undo_recruit_action.cpp, src/actions/undo_recruit_action.hpp, src/actions/undo_update_shroud_action.cpp, src/actions/undo_update_shroud_action.hpp, src/config_attribute_value.hpp, src/game_state.cpp, src/scripting/game_lua_kernel.cpp, src/synced_commands.cpp, src/synced_context.cpp, src/synced_context.hpp, src/team.cpp, src/utils/general.hpp
This commit splits undo actions into multiple smaller steps. The main advantages:
- Its allows us always undo the parts of an action in the reverse order of which
they originally happen, preventing bugs that could be caused if the parts
interact with each other in a way where the order matters (like for example
an [on_undo] resetting a units moves, when the event happend in a move action
which would then also reset the units moves on undoing).
- It's easier to add (c++) undo steps for specific steps even if they are used
from wml, like spending gold.
- [do_command] no longer confuses the undo stack (in fact it's by default now undoable).
- All actions are put onto the undo stack in the same way, previously it was
often unclear whether the undo stack is empty during a specific step  during …
=> split undo actions into smaller steps

.github/workflows/ci-main.yml
I didn't realize I could do this until now. This PR actually makes CI fail when there's a linter issue.
=> Enable warnings as errors for scons

changelog_entries/elvish-champion-honed.md, data/core/macros/weapon_specials.cfg, data/core/units/elves/Champion.cfg
Following the failed balance team vote for #9557, we held a follow-up vote for a partial reversion: lowering the Champion's hp to 1.16 and explaining his accuracy bonus via a weapon special. The follow-up vote passed 3-0, so I'm implementing it here.
I don't mean to block off any possible future reversion to 1.16's 9-5, if the balance team decides to vote differently in the future - but this is still hopefully an improvement over 1.18.
Resolves #8706
Since discussion about this topic has already taken place on #9557 and since a vote for this partial reversion has already been held, I'll merge this PR once the checks finish.
=> Elvish Champion: revert hp to 1.16, explain accuracy bonus via a weapon special

.github/workflows/ci-main.yml, src/actions/attack.cpp, src/ai/configuration.cpp, src/ai/configuration.hpp, src/game_events/manager_impl.cpp, src/help/help_topic_generators.cpp, src/network_asio.cpp, src/recall_list_manager.cpp, src/recall_list_manager.hpp, src/server/common/dbconn.cpp, src/server/common/dbconn.hpp, src/units/types.cpp, src/units/types.hpp
Fixes leftover clang-tidy warnings that causes the CI to fail. (Most probably from #9618)
=> fix clang-tidy warnings

src/gui/widgets/chatbox.cpp, src/gui/widgets/chatbox.hpp
- Add a red line to help distinguish the old msgs (Based on the discussion of adding redlines as referenced in #9211）
- By making sure every time the chat log is loaded, there's a red line at the bottom of chat window. 
- It's a feature from discussion in #9211.
- While keeping the old msgs when entering lobby, some UI clarification on what are old messages would be expected according to the related discussion in #9211.
Adjust possibly missed related method and changes I mistakenly made. 
If there's a better idea about the details of red line content, it's perhaps also okay to replace existed red line content with that.
This PR is Ready for Review.
Compile and run, see the test video I might upload later if needed, or see changes in the src.
=> Add a red line to the bottom of chat window when entering lobby

src/gui/dialogs/game_stats.cpp, src/gui/dialogs/preferences_dialog.cpp, src/gui/dialogs/unit_create.cpp, src/gui/dialogs/unit_list.cpp, src/gui/dialogs/unit_recall.cpp, src/gui/widgets/addon_list.cpp, src/gui/widgets/listbox.cpp, src/gui/widgets/listbox.hpp
Instead of two functions for translatable and non-translatable options, comparison will be determined by the return value of the sorter. Existing translatable sorting options have been adjusted to return t_string rather than string.
=> GUI2/Listbox: unify registration of sorting options

changelog_entries/dawarf-level.md, data/campaigns/Under_the_Burning_Suns/units/monsters/Darawf.cfg
This unit far too weak for a level 1, with only 22HP, relatively terrain defenses and resistances and a only 6x2 meele attack. I know it's only a joke unit, but I'd still like it if the stats made sense.
I propose the following changes:
-Decrease level from 1 to 0.
-Decrease XP from 50 to 25 so it makes more sense with the new level.
-Reduce gold from 17 to 12 like in Venomous Sands. They aren't recruited in-game, but I think it's still good to have a cost that is sensible for its level.
=> Demote Dawarf to level 0

src/ai/manager.cpp, src/ai/manager.hpp
Fixed map editor crashing when creating or opening scenario after played local scenario before opening map editor. Resolves #9563. The cause of the bug was that the ai manager singleton pointer was not set to nullptr after it was destructed. Fixed this by making ai manager destructor set singleton to nullptr. Before this the ai_map_ map member has to be cleared in destructor because it might try to access the singleton when destructed.
=> Map editor segmentation fault fix

SConstruct, boost_test_schedule, projectfiles/CodeBlocks/wesnoth.cbp, projectfiles/Xcode/The Battle for Wesnoth.xcodeproj/project.pbxproj, scons/boost.py, source_lists/wesnoth, src/config_attribute_value.cpp, src/lexical_cast.hpp, src/serialization/parser.cpp, src/tests/test_config.cpp, src/tests/test_lexical_cast.cpp, src/utils/charconv.cpp, src/utils/charconv.hpp
This makes attribute_value and lexical_cast use the "new" to/from_chars api.
Its main advantages are:
- It's guaranteed to be locale independent, hopefully fixing all cases of #3945 and similar
- It fixes some cases config serialization, in particular the test
```
cfg["x"] = "9.87654321";
BOOST_CHECK_EQUAL(cfg["x"], 9.87654321);
```
- Previously the lexical_cast implementation used exception
handling for invalid formats (catching std::invalid_argument)
which made noise during debugging (and is also slower if it
is not optimized out).
- It's faster
So far afaik the only compiler which has a complete and proper to/from_chars implementation is msvc, gccs implementation of from_chars sometimes uses strtod under the hood and clang simply hasn't implemented from_chars for floating point numbers …
=> use to/from_chars in attribute_value and lexical_cast

data/campaigns/Eastern_Invasion/scenarios/04c_Mal-Ravanals_Capital.cfg
Fixes #9623
@Dalas121 I've changed the WML you proposed in the issue a bit.
I think it's more straightforward to have it in one "turn refresh" event, right before the side's AI launches.
I've tested it, it works as intended.
=> EI S04c: fix gold management for Ravanal

CMakeLists.txt, SConstruct, changelog.md, projectfiles/CodeBlocks/campaignd.cbp, projectfiles/CodeBlocks/tests.cbp, projectfiles/CodeBlocks/wesnoth.cbp, projectfiles/CodeBlocks/wesnothd.cbp, src/desktop/windows_tray_notification.hpp
As mentioned on Discord, it looks as if the ~current~ upcoming VS 17.13 release cycle will be the last, and support for targeting Windows 7 is going to be [dropped when VS 18.x comes out](https://github.com/microsoft/STL/issues/4560#issuecomment-2348622212). Additionally, boost::filesystem just dropped support for Windows versions prior to 10 with 1.87, so it seems a good a time as any to do this, especially since we're targeting 2026 for 1.20.
=> Target Windows 10

src/server/campaignd/server.cpp, src/server/common/forum_user_handler.cpp, src/server/common/forum_user_handler.hpp, src/server/common/server_base.cpp, src/server/common/server_base.hpp, src/server/common/user_handler.hpp, src/server/wesnothd/game.cpp, src/server/wesnothd/server.cpp
Boost 1.87.0 removes some functions that have been deprecated for a few releases, but are still used in wesnoth.
=> Fix build with boost >= 1.87.0

src/scripting/lua_unit.cpp
This logic seems inverted, this probably happened while the lua attributes were converted to use the LATTR_SETTER macros.
=> Fix #9651 Error in u:extract()

src/game_initialization/flg_manager.cpp, src/game_initialization/flg_manager.hpp, src/team.cpp
previously the leader= attribute in [side] could be used to make the engine choose a faction by its leader, similar to how [side]faction_from_recruit worked.
However this was not documented in the wiki, and the name clash with the [side][leader] subtag could also cause problems and is also a litte confusing.
So it was decided to remove it. an alternative approach to fix the name clash would be to rename it, but i can't think of real usecases of this feature currently.
=> remove [side] leader=

changelog_entries/fire_guardian_resistances.md, data/core/units.cfg, data/core/units/monsters/Fire_Guardian.cfg, data/core/units/monsters/Fire_Wisp.cfg, data/core/units/monsters/Fire_Wraith.cfg
Fire Wisps and Guardian fire resistances increased from 50% to 70%, whereas the more powerful level 2 Fire Wraiths have increased to 80%. The previous 50% made little sense for a unit made of flames and smoke, so this is a bit more reasonable while still not requiring changes to existing scenarios or much rebalancing of UMC.
=> Increase Fire Resistances of Fire Guardian Line

src/gui/dialogs/game_version_dialog.cpp
Most of the changes here is just me restructuring things so I can read/understand the flow better. Hopefully it makes sense to others as well. The core of the change is not attempting to access non-existing elements in an empty vector.
The change avoids the immediate problem of the crash that causes #9661, but there are things that could be done better:
* I use `en` as a fall-back for System Language. I don't think it's unreasonable to open a US English manual as a default regardless of the user's system language, but perhaps we can re-use the same logic from the language menu label to have some sort of attempt at discerning the user's system language.
https://github.com/wesnoth/wesnoth/blob/a6954bd56e214ab7e7f656a419a814e00f6de1b7/src/gui/dialogs/title_screen.cpp#L392-L418
* This change …
=> View Manual: Avoid crash from indexing an empty vector

changelog_entries/ei-dialogue-fixes.md, data/campaigns/Eastern_Invasion/scenarios/18_Epilogue.cfg, data/campaigns/Eastern_Invasion/utils/items.cfg
Fixes #9627 . I've also added a changelog entry for my previous PR #9637 where I forgot to add one.
The INVALID_DESC parameter in PLACE_ITEM macro is now supposed to contain WML code rather than a single string. It should be at least a single [message] tag. Correspondingly, I replaced empty strings for this parameter with empty parentheses. This way I don't need to change a lot of code in the macro (which may break other items). However, that means that if the code is changed in the future, you need to make sure there's no contradictions between the code in REQUIREMENTS and in INVALID_DESC.
The unreachable dialogue in S18 (for the cases when Dolburras or Hahid wear the staff) is removed.
I have verified that different units produce different rejection messages, but I didn't fill the …
=> EI: forbid dunefolk from taking the Plague Staff and add custom rejection messages

data/lua/wml/message.lua
This is minor, typo correction,
The old way, if you put a voice into the message, it keeps playing again and again once the message is dismissed.
Repaired, tested.
=> Message voice fix

changelog_entries/orcish_xbowman_nerf.md, data/core/units/orcs/Crossbowman.cfg
The changes of Orcish Crossbowman made in 1.18 increased the power of this unit disproportionately. When advancing lvl 1 Orcish Archer, his melee damage rises extremely fast (3 times, from 3-2 of Orcish Archer to 6-3 of Orcish Crossbowman, which is unprecedented).
Also, the new xp requirement for advancing to level 3 is 43 (compared to 80 in 1.16), which is very close to lvl1-to-lvl-2 values. It becomes near-advancement after just several kills, which makes fighting him extremely troublesome.
My proposal is to set leveling XP to 57 (-10 xp compared to Orcish Warrior's 67 xp, like Orcish Archer-Orcish Grunt xp reqs) and to return 4-3 melee attack as it was in 1.16. I keep 1.18's increased hp (46 compared to 1.16's 43) and increased ranged pierce attack (9-3 vs 1.16's 8-3) because I believe …
=> Nerf of Orcish Crossbowman

changelog_entries/explorer_resistance_nerf.md, data/core/units/dwarves/Explorer.cfg, data/core/units/dwarves/Pathfinder.cfg
The Dwarvish Scout and Pathfinder have 10% resistance to Blade/Pierce/Impact, but the Explorer has 20%. The Explorer's 20% resistance removes one of the unit line's unique attributes, and also makes him even more similar to the Dragonguard than he already was.
This PR lowers the Explorer's resistances to match the rest of the unit line, and moderately improves their damage in compensation.
I don't mean to make the unit as a whole significantly stronger or weaker, nor do I mean to change their role or affect the balance of existing content. I do mean to reduce one area of similarity between the Explorer and Dragonguard, and to emphasize the Scout/Pathfinder's unique identity as a 10%-resistance dwarf.
The Dwarvish Scout's usage is currently set to 'mixed fighter'. This PR also changes the …
=> Dwarvish Explorer: reduce resistances from 20% to 10%

data/campaigns/Eastern_Invasion/scenarios/04c_Mal-Ravanals_Capital.cfg
The problem is, if `ravanal_gets_serious` event is triggered before turn 8, then Dacyn's words in `turn 8` event:
> all will be lost if Mal-Ravanal finds me amongst you
are nonsense - as Ravanal has already found him.
To fix this, I put Dacyn saying those words into a separate single-use event `dacyn_warning`, and trigger it either in `turn 8` or in the beginning of `ravanal_gets_serious`, whichever happens earlier.
=> EI S04c: avoid contradictory dialogue if Ravanal is triggered early

data/campaigns/Eastern_Invasion/scenarios/05_Northern_Outpost.cfg
The code for Owaec's side joining the player was duplicated, so I moved it into a custom event. This involves only the code merging the sides, without any dialogues.
There is no changes in behavior.
An alternative would be to join the `die` events like
```
[event]
name=die
[filter]
id=Shodrano,Rilaka
[/filter]
```
but then it would require 2-3 `[if]` blocks inside for differing dialogues and actions, so it would be less readable.
=> EI S5: reduce code duplication

src/game_initialization/connect_engine.cpp, src/game_initialization/flg_manager.cpp, src/game_initialization/flg_manager.hpp, src/gui/dialogs/multiplayer/mp_join_game.cpp, src/saved_game.cpp, src/team.cpp, src/team.hpp, src/teambuilder.cpp, src/tests/test_mp_connect.cpp, src/units/types.cpp
Added code to convert all  ` [side]type=` to `[side][leader]` when the `[scenario]` is read, and the rest of the engine code to only work with [leader], this should fix all possible problems with  [leader] and also simplify the code a bit
Fixes #7985
Fixes #3742
=> Use [leader] in the c++ code

data/campaigns/Eastern_Invasion/scenarios/04c_Mal-Ravanals_Capital.cfg
These variables are not used later, so they may be cleared. Otherwise they appear uselessly in later scenarios.
- `dead_ravanal` variable is used in this scenario only
- `possessee` may be kept to use in `RAVANAL_DEPOSSESS`, but this macro is not used in this scenario
=> EI S04c: clear dangling variables

packaging/flatpak/org.wesnoth.Wesnoth.json
because artifactory is down too much and they plan to move away from it
anyway.
=> Change boost download link in flatpak to archive.boost.io

src/gui/dialogs/units_dialog.cpp
Resolves #9701.
As already mentioned on #9701, the `image_icon` property is documented but not used. This updated the units dialog (recruit configuration) to use it if available and fallback to `image` if necessary. The image will be scaled to 72x72px if bigger.
Quoting from [UnitTypeWML](https://wiki.wesnoth.org/UnitTypeWML#Unit_Type) wiki page:
> **image_icon**: sets the image used to represent the unit in areas such as the attack dialog and the unit image box in the sidebar. [~CROP](https://wiki.wesnoth.org/ImagePathFunctions#Crop_Function) function can be useful here. You can see Loyalists Paladin as an example.
=> units dialog (recruit): use image_icon instead of image

data/gui/themes/default/window/mp_method_selection.cfg, src/gui/dialogs/multiplayer/mp_method_selection.cpp, src/gui/dialogs/multiplayer/mp_method_selection.hpp, src/preferences/preferences.hpp, src/preferences/preferences_list.hpp
Allows method selection using arrow keys once again (Resolves #9501).
Adds Tab ordering to the MP method selection dialog. Initially the method list has focus so method can be selected using Left/Right keys. To change username, the player just needs to press Tab once to move focus to the Login textbox.
Additionally, the layout and message is adjusted a bit and @ProditorMagnus's suggestion of remembering the last connection method has been implemented. (https://github.com/wesnoth/wesnoth/issues/9501#issuecomment-2560330243)
Also, a close button has been added so that the window can be close using mouse once again.
(Changed from initial idea of removing the login textbox based on feedback received on Discord/IRC.)
=> Improve keyboard navigation in MP Method Selection dialog

data/campaigns/Eastern_Invasion/scenarios/07a_Capturing_the_Ogres.cfg
This is a small code improvement, without changes in behavior.
If we initialize these cyclic counter variables in the `prestart` event, then we don't need to check for their existence every time.
Also, to preserve the message order, increment the counters after use rather than before.
=> EI S07a: init counter variables in prestart

data/campaigns/Eastern_Invasion/scenarios/06b_Soradoc.cfg, data/campaigns/Eastern_Invasion/utils/deaths.cfg
I'll explain them by commit.
Write the event for moving one unit next to another in a simpler way. No behavior changes.
The `meet_yannic` custom event can be fired from two other events, and one of them (Owaec moves next to Yannic) already guarantees that Yannic is alive. For another event (3 enemy leaders killed) we should check, so I moved the condition into that event. I think it makes the code more readable. No behavior changes.
Fix a minor bug: Owaec's "eulogy" message for Yannic didn't appear even after they met. That's because the event used wrong variable: `saved_yannic` (which doesn't appear anywhere else) instead of `met_yannic`.
Fix another bug: the message from the unit who reached the exit marker didn't appear because the engine doesn't understand reverse integer ranges.
To …
=> EI S06b: fix a couple of small bugs, code improvements

data/campaigns/Eastern_Invasion/scenarios/07b_Ogre_Crossing.cfg
Explanation by commit.
Fix a minor bug: the `SCROLL_TO` macro didn't work.
That's because it resolves to a `[scroll_to]` tag, which uses the [StandardLocationFilter](https://wiki.wesnoth.org/StandardLocationFilter) - so it can't match a location with coordinates outside of the map borders.
So I replace it with `[scroll_to_unit]` to Grug.
By using the nested events, we can achieve the same effect (limiting undead moves on their first turn after appearing) without using variables. No changes in behavior.
These commits improve the code for enemy leaders' deaths. No changes in behavior.
Izziasch had two `last breath`, and the results (whether we get achievements or not) depended on the order they execute. While the events are [guaranteed](https://wiki.wesnoth.org/EventWML#priority) to fire in …
=> EI S07b: fix bugs, code improvements

data/campaigns/Eastern_Invasion/scenarios/08_Xenophobia.cfg, data/campaigns/Eastern_Invasion/utils/deaths.cfg
Explanation by commit:
`po` comments mentioned saurians. Side 5 is actually nagas.
`po` comments mentioned that Whitefang orcs attacked Tath in the beginning of DiD. It was actually Parthyn.
Prevent the Dolburras - Pelanthsil task from starting if Pelanthsil is dead. He can't actually be reached by enemies at that point (turn 2), but this makes the event more error-proof in case of future scenario changes.
Fix a bug: the Dolburras - Pelanthsil task stays in the objective list even if one of them is killed.
According to https://wiki.wesnoth.org/DirectActionsWML , keys like `bonus` in `[endlevel]` are not used if the result is `defeat`, so I remove it. No behavior changes.
Minor improvement: if we choose to replay the level from the options, the defeat message seems odd, so I remove it in …
=> EI S08: fix bug, code improvements

data/campaigns/Eastern_Invasion/scenarios/08_Xenophobia.cfg
Fixes #9730
I think we don't need to mention prince Konrad (HttT) because:
1. Players may confuse him with the current king Konrad II.
2. Delfador made a greater impression on dwarves with his magic, they remember him better than the prince.
=> EI S08: replace mention of Ulrek with Relgorn

data/campaigns/Descent_Into_Darkness/scenarios/10_Endless_Night.cfg, data/campaigns/Eastern_Invasion/scenarios/08_Xenophobia.cfg, data/campaigns/Northern_Rebirth/scenarios/05a_02_Dealings.cfg, data/campaigns/Northern_Rebirth/scenarios/08a_Elvish_Princess.cfg
Use "ken" only for "know" or "see" meanings, not for "can" meaning.
Fixes #9731
=> DiD, EI, NR: replace "ken" with "can" in dwarf speech

data/campaigns/The_Hammer_of_Thursagan/utils/characters.cfg
The macro `CHARACTER_STATS_ANGARTHING` was defined. twice.
=> THoT: remove duplicate macro

changelog_entries/submenu-positioning.md, src/gui/dialogs/drop_down_menu.cpp, src/gui/dialogs/drop_down_menu.hpp, src/hotkey/command_executor.cpp
This is an attempt to improve the way menus work in Wesnoth. The current implementation handles each menu as a modal dialog of its own, in particular allowing there to be at most only one menu on screen. It goes without saying that when dealing with menus that have submenus (such as the in-game turn and replay menus, as well as the editor's MRU list) this is very suboptimal. I'd like to look into changing this later, but for now I've at least figured out a way to improve the **positioning** of submenus.
Currently, when a menu item that spawns a submenu is selected, the latter is displayed with its top left coordinate at the exact position of the mouse cursor. This means that the top left corner of a **submenu** is not so much dependent on where the **parent menu item** that is associated …
=> gui: Better positioning of submenus in the main UI

changelog_entries/macos-font-render-backend.md, src/wesnoth.cpp
This is a backport to 1.18 of PR #9593, which fixes issue #8488.
=> (1.18 backport) Switch default Pango/Cairo render backend to Fontconfig on macOS

data/campaigns/Eastern_Invasion/utils/schedule.cfg
Fixes #9748
- Remove `NORTHERN_MIDDAY` time of day which was used by removed `NORTHERN_WINTER_SCHEDULE` (see commit a5a84c4)
- Remove unused `BRAZIER_ILLUMINATION` schedule
=> EI: remove the rest of unused schedules

data/campaigns/Eastern_Invasion/utils/items.cfg
If we select the option to leave the item on the ground, we should be able to undo and move another unit to take it.
I've tested it in S06a with the crystal quiver and the elixir of water breathing, seems to work without any bugs.
=> EI: allow undo if we choose to not pick the item (or elixir)

data/campaigns/tutorial/_main.cfg
I am aware the title was changed to include Old Tutorial. This is intended to further clarify to players that this tutorial is no longer reccomended fow new players. This is intended to remove contradictions between the title and description to prevent confusion for new players.
=> Warn against old tutorial in description

data/campaigns/Eastern_Invasion/scenarios/01_Eastern_Invasion.cfg, data/core/encyclopedia/geography.cfg
On the title screen map, Soradoc seems to be the same latitude as Tath and Aldril, while Carcyn and Elensefar are even further north. Soradoc being the "northernmost outpost" seems to be a holdover from the early geography outline.
Also, as of EI years (which is the only current mainline campaign featuring Soradoc), there are settlements east of Weldyn river, so calling Soradoc an "outpost" seems wrong. Also, its description in EI S06b is:
> Established by the Crown and administered by the Horse Clans, Soradoc controlled the strategic confluence of the Great River and the River Weldyn. Since its founding in the early days of Wesnoth, it had grown into a prosperous and well-fortified border **town**.
As for location of the EI outposts, according to EI campaign map, the Northern Outpost is …
=> EI prose, encyclopedia: fix Soradoc and outposts locations

data/campaigns/Eastern_Invasion/scenarios/06a_Undead_Crossing.cfg
I noticed there's some differences between Hahid's dialogue in S06a and S07b:
- In S06a, there's small print saying the elixir is less effective on cavalry. But on testing it doesn't seem to be the case (in both scenarios).
- In S06a, the strike-through text is just "call". In S07b, it's "call now". The latter seems more readable to me.
So, I copied these two lines from S07b to S06a.
=> EI S06a: improve Hahid's eleixir-related messages

data/campaigns/tutorial/achievements.cfg
Changed from Tutorial to Old Tutorial given the TSG Rework.
=> Change display name of Old Tutorial Achievement Group

data/campaigns/Eastern_Invasion/scenarios/09_Castle_in_the_Ice.cfg
The main purpose of this PR is to fix a minor bug: it was always Gweddry who said "Brrrr, I can’t feel my fingers..." between turns 1 and 2, even if he drank Hahid's elixir on turn 1 and became resistant to cold.
In the current code the speaker depends on the order the units are stored into the array (which, AFAIK, is not guaranteed to stay the same in future versions of the game). So I think it's better to fix the speaker to either Gweddry, or Owaec if Gweddry takes the elixir. The other speakers seem less suitable:
- Dolburras and Grug speak other dialects, they shouldn't suddenly start speaking proper Wesnothish.
- Dacyn is unlikely to complain about cold because he visited this area before, and it was him who dragged everyone here in the first place.
- Terraent seems pretty stoic in …
=> EI S09: improve frostbite event

src/draw.cpp, src/draw.hpp, src/units/drawer.cpp
This fixes an issue where the bar borders would always be one pixel wide, regardless of the zoom level or game render scaling which made the bars stand out badly amongst the pixel art. This brings us closer to the old look from the surface-drawn days.
This is also an experiment with using normalized, fractional coordinates for rendering instead of absolute screen coordinates. I'd like to take this approach in more places, so this is a good proof of concept.
=> Refactor unit bar drawing

data/campaigns/The_Deceivers_Gambit/scenarios/00_Graduation.cfg, data/campaigns/The_Deceivers_Gambit/scenarios/01_Stirrings_of_War.cfg, data/campaigns/The_Deceivers_Gambit/scenarios/02_Fort_Garard.cfg, data/campaigns/The_Deceivers_Gambit/scenarios/03_The_Ambassador.cfg, data/campaigns/The_Deceivers_Gambit/scenarios/04_The_Sylvan_Seer.cfg, data/campaigns/The_Deceivers_Gambit/scenarios/06_Ring_of_Swords.cfg, data/campaigns/The_Deceivers_Gambit/scenarios/07x_Weldyn_Court.cfg, data/campaigns/The_Deceivers_Gambit/scenarios/08_Ruins_of_Saurgrath.cfg, data/campaigns/The_Deceivers_Gambit/scenarios/09_Omaranth.cfg, data/campaigns/The_Deceivers_Gambit/scenarios/10_Houses_of_the_Dead.cfg, data/campaigns/The_Deceivers_Gambit/scenarios/11_Clan_Blackcrest.cfg, data/campaigns/The_Deceivers_Gambit/scenarios/11x_Revelry.cfg, data/campaigns/The_Deceivers_Gambit/scenarios/12_The_Traitor.cfg, data/campaigns/The_Deceivers_Gambit/scenarios/13x_The_King_is_Dead.cfg, data/campaigns/The_Deceivers_Gambit/scenarios/14_Long_Live_the_Queen.cfg, data/campaigns/The_Deceivers_Gambit/utils/macros.cfg, data/campaigns/The_Deceivers_Gambit/utils/side_ai.cfg, data/campaigns/The_Deceivers_Gambit/utils/spellcasting.cfg, data/campaigns/The_Deceivers_Gambit/utils/unified_characters.cfg, data/schema/core/actionwml.cfg, data/schema/core/addons.cfg, utils/CI/schema_validation.patch, utils/CI/schema_validation.sh
While adding TDG to mainline, I missed adding it to the schema. As a result, a lot of issues went unnoticed.
This PR adds TDG to the schema, and fixes the various discovered errors. This PR also updates the schema to reflect the engine supporting multiple [filter] tags in events, and to reflect the engine supporting [change_theme] without keys.
=> TDG: add to schema, and fix schema issues

src/scripting/lua_widget_attributes.cpp, utils/emmylua/gui.lua
Exposes Rich Label's `register_link_callback` function as the lua `on_link_click` setter. The function set to this will be called with the target of the clicked link.
Resolves #9124.
**Example:**
If you have a rich_label with id `test` in your dialog, say inside a grid like this:
```ini
[row]
[column]
horizontal_alignment = "left"
[rich_label]
id = "test"
label = _ "<b>Link: </b><ref dst='..units'>Units</ref>"
[/rich_label]
[/column]
[column]
[spacer]
[/spacer]
[/column]
[/row]
```
then you can use it like this inside your `preshow` function:
```lua
local test = dialog:find("test")
test.on_link_click = function(dest)
gui.alert(dest)
gui.show_help(dest)
end
```
=> lua: expose rich_label link handling mechanism

data/campaigns/The_Deceivers_Gambit/units/Monster_Silverback.cfg
https://wiki.wesnoth.org/Typography_Style_Guide
According to the Typography Style Guide, races shouldn’t be capitalized but unit types should be. Silverbacks aren’t a species, and in this case I think this refer to the Unit Type.
=> TDG: Capitalize Silverback in Unit Description

data/campaigns/Eastern_Invasion/scenarios/09_Castle_in_the_Ice.cfg
Fixes #9784
- The first commit simplifies the events for sighting the ogres and introduces `ogres_sighted` variable. No changes in behavior.
- The second commit adds `side 5` ogres to the list of frostbitten units, if `ogres_sighted` is set.
=> EI S09: make frostbite affect wild ogres after they are sighted

changelog.md, changelog_entries/south_guard_is_tutorial.md, po/CMakeLists.txt, po/SConscript, utils/po_stat.py
For working out which languages have 80% of core translated, TSG is now relevant and the old tutorial isn't. This means that the 80% threshold has increased by around 500 strings.
Add missing changelog entries for 1.19.8 directly to the changelog. (Although I'm using the changelog_entries mechanism for the 1.19.9 change, there shouldn't be any danger of merge conflicts for the 1.19.8 part.)
=> For translation stats, TSG is now the tutorial

changelog.md, src/units/unit.cpp, src/units/unit.hpp
See #7292, closes #2913. Apparently, this has never worked, and based on discussion in #7292, it's not even particularly useful. Plus, since it was removed from the schema two years ago, has been functionally deprecated since then.
The keys in unit_type remain untouched.
=> Unit: remove bar scaling overrides

src/formula/formula.cpp, src/units/filter.cpp
- Resolves #9249.
- By adding try-catch to finish a todo in filter.cpp, it catches formula error when evaluating formula.
- #9249
- This is a bug fix. Also, there's a case in formula evaluating that the formula will undoubtly be an empty expression and don't need to call itself again to find out the error, the pr also makes changes on it.
Adjust possibly missed related method, delete some redundant description.
This PR is Ready for Review.
Compile and run, see the test video I might be uploading soon, or see changes in the src. (personally have tested it and it works)
=> Fix invalid WFL crashes Wesnoth

src/preferences/preferences.cpp
Resolves #9581.
The advanced preference list variable was not being cleared before loading from advanced preferences file.
=> advanced prefs: clear list everytime advanced prefs are reloaded.

data/campaigns/Son_Of_The_Black_Eye/scenarios/10_Saving_Inarix.cfg
- updated objectives to the player once Inarix and party arrive on turn 4
- move note part of objective win to notes section. Self-Explanatory
- add bonus objective caption to the saving inarix and her 4 saurians objective
=> [SotBE] S10: refine objectives flow

data/schema/gui/generic.cfg, src/gui/core/canvas.cpp, src/gui/widgets/rich_label.cpp
Resolves #9822.
This key toggles parsing of `text` key as formula or not. Default: true.
=> canvas: add a `parse_text_as_formula` key to `[text]`

data/campaigns/Eastern_Invasion/scenarios/08_Xenophobia.cfg, data/campaigns/Eastern_Invasion/scenarios/09_Castle_in_the_Ice.cfg, data/campaigns/Eastern_Invasion/utils/macros.cfg
Fixes #9816
It displays message depending on the race of the unit. Dwarves, ogres, and undead use their own custom messages, the rest use the default one.
Optional arguments allow changing the speaker and the image. By default, narrator speaks for the undead, other units speak themselves.
Another optional argument is for the sound (same for all races).
This new macro is used for messages in scenarios 8 and 9, with placeholder messages to be filled in later commit.
=> EI: add macro for multiracial messages

data/core/about.cfg
I think I may be eligible to be added miscellaneous contributor to the credits. I am an active contributor with  37 total commits (many of which are very minor) including a fairly significant revision of the in-game encyclopedia.
This PR should not be backported, since I only have two extremely minor contributions before 1.19.
=> Add myself to credits

data/core/units/elves/Captain.cfg
Elvish Captain is a unit name, so according to the typogrpahy style guide both parts need to be capitalized.
=> Capitalize Elvish Captain in unit description

data/core/units/goblins/Pillager.cfg
Race names should not be capitalized according to the typography style guide.
=> Uncapitalize goblin in pillager unit description

data/campaigns/The_Rise_Of_Wesnoth/scenarios/13_Peoples_in_Decline.cfg
Fixes #8263
Now uses Morogor dialect. Casters is an ancient word for human mentioned here: https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/Winds_of_Fate/story/Morogor_Dialect.txt
=> TRoW S13: Fix Drake Dialogue Inconsistency

data/campaigns/Legend_of_Wesmere/_main.cfg
No commits to LoW since 2016 from @fendrin or Fabian Müller (not sure who this reffers to, but neither of these accounts have contributed in a very long time).
=> Change Fabi/Fendrin to former maintainer of LoW

data/campaigns/Heir_To_The_Throne/_main.cfg
@ln-zookeeper Hasn’t commited to HttT since 2018. I haven’t removed them from HttT’s credits, but I have replaced “current maintainer” with “former maintainer”, which is more accurate.
=> Change zookeeper to former maintainer of HttT

data/campaigns/Son_Of_The_Black_Eye/scenarios/12_Giving_Some_Back.cfg, data/campaigns/Son_Of_The_Black_Eye/utils/utils.cfg
- Partially makes them focus on attacking only when no enemy is near their leader, but switch to full defensive if enemy leaders are nearing the vicinity
=> SotBE: S12: make loyalists AI smarter

data/campaigns/The_Hammer_of_Thursagan/units/Dwarvish_Masked_Berserker.cfg, data/campaigns/The_Hammer_of_Thursagan/units/Dwarvish_Masked_Dragonguard.cfg, data/campaigns/The_Hammer_of_Thursagan/units/Dwarvish_Masked_Fighter.cfg, data/campaigns/The_Hammer_of_Thursagan/units/Dwarvish_Masked_Guardsman.cfg, data/campaigns/The_Hammer_of_Thursagan/units/Dwarvish_Masked_Lord.cfg, data/campaigns/The_Hammer_of_Thursagan/units/Dwarvish_Masked_Sentinel.cfg, data/campaigns/The_Hammer_of_Thursagan/units/Dwarvish_Masked_Stalwart.cfg, data/campaigns/The_Hammer_of_Thursagan/units/Dwarvish_Masked_Steelclad.cfg, data/campaigns/The_Hammer_of_Thursagan/units/Dwarvish_Masked_Thunderer.cfg, data/campaigns/The_Hammer_of_Thursagan/units/Dwarvish_Masked_Thunderguard.cfg, data/core/units/dwarves/Steelclad.cfg
Updated the stats of Masked Dwarves in THoT to be up to date with default dwarves, as they are supposed to be he same in terms of stats. These hasn’t been updated in years despite several balancing changes for the default dwarves. I also updated the unit description the Dwarvish Masked Steelcad since the default one was reworked a few years ago.
=> THoT: Update Masked Dwarf Stats

data/campaigns/Eastern_Invasion/scenarios/09_Castle_in_the_Ice.cfg, data/campaigns/Eastern_Invasion/utils/items.cfg
Explanation commit-by commit:
It looks like this map had more villages before, and the scenario code wasn't changed to reflect that. 
There are no villages close enough to the player's starting position, so `STARTING_VILLAGES` macro does nothing, so I remove it. No changes in behavior.
Two of the revealed coordinates are empty spots near the ogre camp. I've changed them to the coordinates of the village there. So, now on turn 1 we have 2 villages revealed instead of 1. There are 4 villages in total, and the other 2 are close to the main path.
There is no village at this coordinates, so `CAPTURE_VILLAGES` macro does nothing.
There is a village a bit further east, but Mortic needs 2 turns to reach it from the keep. I tested it, and he doesn't try to capture that eastern village, but fights …
=> EI S09: fix minor bugs, code improvements

data/core/units/boats/Pirate_Galleon.cfg
According to the typography style guide, both parts of unit names should be capitalized.
=> Capitalize both parts of Pirate Galleon in Unit Description

data/campaigns/Eastern_Invasion/scenarios/12_Evacuation.cfg
Eyrie is much more commonly used in Wesnoth nowadays, and is the form used in WoF.
=> EI S12: Use Eyrie instead of Aerie

data/campaigns/The_Deceivers_Gambit/utils/spellcasting.cfg
Cave movement was previously left out as an oversight.
=> TDG: allow the levitate spell to improve cave movement

data/campaigns/Eastern_Invasion/units/Human_Owaec_Clan_Captain.cfg, data/campaigns/Eastern_Invasion/units/Human_Owaec_Horse_Lord.cfg, data/campaigns/Eastern_Invasion/units/Human_Owaec_Princeling.cfg, data/campaigns/Eastern_Invasion/utils/abilities.cfg
I've noticed that PR #9864 removes an unused `NOTE_SHOCK` macro.
The text in that note is actually useful. Currently it doesn't appear in Owaec's unit description page, and that's a mistake.
Instead of including it into `[unit_type]` files, I put it directly into the tag for that weapon special. It's the newer and simpler way of achieving the same effect, see wiki: [UnitTypeWML#Special_Notes](https://wiki.wesnoth.org/UnitTypeWML#Special_Notes)
I've also changed the way the "vanguard" ability note is included to the newer one. No behavior change for this note: it's displayed the same way as before.
Note: I don't delete the unused macro `NOTE_SHOCK` because it's deleted in PR #9864, to avoid a merge conflict. The code will stay in a working state regardless which PR is merged first.
=> EI: display the note for Owaec's weapon special in unit description

changelog.md, src/preferences/preferences.hpp
Hopefully, we'll be able to implement better support for layouts that don't relay on pixel canvas sizes, but for now, this solves two important issues:
Using 1280x720 as the default window size means 3x auto pixel scaling for 4k fullscreen, which looks utterly horrendous and unusable. 2x is the practical limit of usability without going so far in the opposite direction as to actually reduce the available space.
Bumping the min window size also resolves #9898 and saves us from having to deal with layouts on unusably small windows.
As a side note, we should not be thinking in terms of pixel size anymore. I'm hoping SDL3 can give us better control over our HDPI support (which is much improved from before), but the fact remains that our current pixel scaling implementation is, essentially, a …
=> Bump min and default game window size

data/campaigns/The_South_Guard/scenarios/01_Born_to_the_Banner.cfg
@Dalas121 Was this the arm intended to have been lost? The sprite would suggest the right arm was lost:
https://github.com/wesnoth/wesnoth/blob/529f4caca9ebfb1e94e2edad722d9f64e0821152/data/campaigns/The_South_Guard/images/units/mari2/mari.png
So I changed this po note to say right instead of left.
=> TSG: Correctly show which arm Mari is missing in po note

data/campaigns/The_South_Guard/scenarios/03_Vale_of_Tears.cfg
A Skeleton is supposed to be summoned to (12,3), but it isn't properly cleared like the other hexes around (12,4).
Resolves #9920
=> TSG S3: Correct ending scene

CMakeLists.txt
Fixes the "Policy CMP0167 is not set: The FindBoost module is removed" warning when running `vcpkg install`. I'm not sure if this change requires bumping to Boost 1.70 or not.
=> Cmake: use BoostConfig explicitly to silence CMP0167 warning

data/campaigns/The_Rise_Of_Wesnoth/_main.cfg
Other instances of “Kingdom of Wesntoh” have Kingdom capitalized (e.g. DW S2) and capitalizing this would be the general convention in this case so it makes sense to do it in the TRoW Campaign Description as well.
=> Capitalize Kingdom in TRoW Campaign Description

source_lists/wesnoth
Duplicate inclusion, exists in both `source_lists/wesnoth` and `source_lists/libwesnoth`. Opened PR for test CI run to see if one can be dropped.
=> drop preferences.cpp from source lists (no longer needed)

data/schema/units/abilities.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/filter_adjacent_active.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/filter_adjacent_direction_active.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/filter_adjacent_direction_inactive.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/filter_adjacent_inactive.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/filter_adjacent_location_count_three_active.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/filter_adjacent_location_count_zero_active.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/filter_adjacent_location_count_zero_inactive.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/filter_student_adjacent_active.cfg, data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/filter_student_adjacent_inactive.cfg, src/units/abilities.cpp, src/units/attack_type.hpp, wml_test_schedule
check is the same what for units/filter.cpp, if an unit or an adjacent locaton don't matche, the loop continue without increase value of 'coount' variable instead of return false and stop checking, that who doing fail the function.
=> Fix “filter_adjacent_location” not working in ability

data/campaigns/The_Deceivers_Gambit/units/Saurian_Devotee.cfg, data/campaigns/The_Deceivers_Gambit/units/Saurian_Juvenile.cfg, data/campaigns/The_Deceivers_Gambit/units/Saurian_Young.cfg
@Dalas121 I tried to improve these descriptions. The Devotee and Spike are currently using description from their level 1 counterparts, so I gave them something more unique. The saurian race description already said saurians become adults at the age of three, so I used that in the Saurian Juvenile description, which I hopefully improved from the original.
(Check failure in the first commit is unrelated to my changes)
=> TDG: Improve Custom Saurian Unit Descriptions

data/campaigns/Heir_To_The_Throne/units/Sea_Orc.cfg
"a great leap for all orcs" makes more sense since they are supposed to be orcs.
=> Use orcs instead of goblins in Sea Orc unit description

data/core/units/boats/Galleon.cfg
I remade the Galleon unit description. The detail on their origin in the Green Isle in new, but their appearance in TRoW would suggest this.
=> Improve Galleon Unit Description

data/campaigns/The_Deceivers_Gambit/scenarios/00_Graduation.cfg, data/campaigns/The_Deceivers_Gambit/utils/spellcasting.cfg
Based on: https://forums.wesnoth.org/viewtopic.php?p=696551#p696551
Makes the "_Delfador does not use XP to level-up_" message less likely to appear in the first scenario, and elaborates on how delfador _does_ level-up.
=> TDG: some S00 onboarding improvements

data/campaigns/World_Conquest/Modding.md, data/campaigns/World_Conquest/lua/game_mechanics/invest/invest.lua, data/campaigns/World_Conquest/lua/game_mechanics/training.lua, data/campaigns/World_Conquest/resources/data/training.cfg
Intended as a bug fix for: https://github.com/wesnoth/wesnoth/issues/9372
Removed hard-coded indices. Bonus points route through get_trainer so they should work as normal. This primarily updates training.list_available. References to the "Among" list_available parameter were also removed. The dark training was updated to not be visible on the invest screen as is default. The modding readme was updated to include this new functionality.
Edit: I am working on testing this more extensively with friends, locally, in the meantime.
=> World Conquest: Remove hard coded trainer indices

data/campaigns/The_Deceivers_Gambit/utils/spellcasting.cfg
TDG gives Delfador access to a loyal raven/dire raven/war harbinger. Currently, the speed for this unit is capped at 6, to prevent it from being overly-powerful when compared with other options.
revolting_peasant pointed out that this speed cap makes the raven's stats inconsistent with the numbers in "view unit type". To resolve that, this PR replaces the speed cap with {TRAIT_SLOW}.
=> TDG: remove silent raven speed reduction, and use TRAIT_SLOW instead

src/gui/dialogs/help_browser.cpp, src/help/help_topic_generators.cpp, src/terrain/terrain.hpp
Resolves #9456 by linking the help pages for Base and Overlay terrain for composite terrains.
=> help: link base and overlay terrains in terrain help pages (#9456)

src/gui/dialogs/attack_predictions.cpp, src/gui/dialogs/attack_predictions.hpp, src/gui/dialogs/unit_attack.cpp, src/gui/dialogs/unit_attack.hpp, src/mouse_events.cpp, src/mouse_events.hpp
- Resolves #8728.
- By keeping the unit place not changed, and deal with the logic that a unit must stand beside the other in order to launch an attack.
- #8728
- This is a bug fix.
Adjust possibly missed related method. If the ranged attack units(which can attack from 2 or more hexes away) come into being, more changes need to take place for backward compat.
This PR is Ready for Review.
Compile and run, see the test video I uploaded, or see changes in the src.
=> Fixes unit moving during attack selection screen

data/core/units/monsters/Ant_Firebomb.cfg, data/core/units/monsters/Dragonfly_Grand.cfg
These are L2 units with no L3 advancement, but have 80xp for some reason. This PR changes them to the more standard 100xp.
=> Update Firebomb Ant and Grand Dragonfly XP

README.md
I am aware Wesnoth is being ported to android, but this is not yet finished and not the version linked here.
=> Note that iOS/Android versions are currently unmaintained in readme

changelog.md, data/schema/units/single.cfg, data/test/scenarios/manual_tests/scenario-test.cfg, src/gui/dialogs/units_dialog.cpp, src/units/unit.cpp, src/units/unit.hpp
Resolves #8964.
Adds `dismissable` and `block_dismiss_message` keys to `[unit]`
Used in conjunction with `Dismiss` button on Unit Recall Dialog. If `dismissable` is false, the unit cannot be dismissed using the `Dismiss` button in the Unit Recall dialog, and doing so will show the `block_dismiss_message` if provided, else will show a default hardcoded message.
=> Add `[unit]dismissable` and `[unit]block_dismiss_message`

changelog.md, data/gui/themes/default/dialogs/help_browser.cfg, src/gui/dialogs/help_browser.cpp, src/gui/dialogs/help_browser.hpp
=> help browser: add search functionality

.github/workflows/ci-main.yml, data/campaigns/The_South_Guard/scenarios/03_Vale_of_Tears.cfg, data/campaigns/The_South_Guard/scenarios/04_Choice_in_the_Fog.cfg, data/campaigns/The_South_Guard/scenarios/06a_Vengeance.cfg, data/campaigns/The_South_Guard/scenarios/06b_The_Tides_of_War.cfg, utils/CI/fix_whitespace.sh
Indentation was fixed by adding a newline to constructs with excessive density and running wmlindent again. While the constructs were not particularly readable it wouldn't hurt if wmlindent would cope a bit better.
=> Fix some indentation and make CI abort if wmlindent errors

data/campaigns/The_Deceivers_Gambit/scenarios/06_Ring_of_Swords.cfg
TDG S06 requires the player to both rescue Asheviere and also survive until turns run out.
With this commit, re-show objectives after rescuing Asheviere, and strikethrough the completed ones.
=> TDG S06: clarify scenario objectives

changelog.md, src/log.cpp
A recent change in an upstream library must've resulted in an indirect inclusion of `<chrono>` disappearing:
```
D:\wesnoth-1.18\src\log.cpp(429): error C2039: 'high_resolution_clock': is not a member of 'std::chrono'
```
Whatever the case may be, adding one of our own fixes this and poses no issue on other platforms.
(Not needed in the dev branch since the same include was already added by commit 2d765118ed48a976b102c5b296a8062d0846922a.)
=> [1.18] Fix failure to build on current versions of MSVC

changelog.md, src/help/help_topic_generators.cpp, src/scripting/game_lua_kernel.cpp, utils/emmylua/wesnoth.lua
Resolves #9969.
These expose `terrain_type::mvt_type()` and `terrain_type::def_type()` as `mvt_alias` and `def_alias` subtables (array) to `wesnoth.terrain_types` table, which have the same meaning as mentioned in [TerrainWML](https://wiki.wesnoth.org/TerrainWML).
(Note: no way to figure out whether it is a `best of` or `worst of` for the latter two yet, because it's a bit too involved, but may be done in future.)
=> Add various terrain type subtables

packaging/android/AndroidManifest.xml, packaging/android/app/src/main/AndroidManifest.xml
Added 1 line for landscape orientation, at line 77, the following: _android:screenOrientation="landscape"_
This instructs Android to always have landscape orientation (to right side of screen)
=> Android: hardcode landscape (right) orientation

data/campaigns/The_Deceivers_Gambit/lua/spellcasting.lua
This is my first in a series of PRs that will gradually replace the current TDG's magic system with a better and more developer-friendly version, which is currently used in CtL, as it was agreed with @Dalas121 
This PR removes a spacer that was significantly increasing the width of the spellcasting dialog in the new interface 1.19 due to the increased font size of title_text
**Before**
**After**
=> Delete spacer in TDG's spellcasting dialog

data/gui/themes/default/widgets/rich_label_default.cfg, data/schema/gui/widget_definitions.cfg, src/gui/widgets/rich_label.cpp, src/gui/widgets/rich_label.hpp, src/help/help_topic_generators.cpp
Adds a `[colors]` tag under `[rich_label_definition]`. This allows associating color values with names which can later be accessed from Help Markup (for now just from `<table><row bgcolor=...>`).
Uses this functionality to improve Help Browser table's  appearance.
=> rich label: support setting table bgcolors from definition

data/campaigns/The_South_Guard/utils/sg_help.cfg
As pointed out by @Wedge009 / @stevecotton in #9682, this string may need to be translated differently depending on the type of unit being attacked.
Also removes the message when attacking a Thief - Rogues (which IIRC are the only thief-line unit you fight in this campaign) have a ranged attack.
=> TSG help.cfg: improve translatability of "ranged attack" help message

doc/man/wesnoth.6, src/log.cpp
Previously, `--log-debug='*'` would not match all domains. Similarly, `conf*` would not be a correct pattern, etc.
With this change, special handling of top-level domains is removed. For example, the `config` domain will be matched by `conf*`.
All domains can be matched by the magic string `all` as before, or by using `*`.
Basic manual testing was performed for this PR:
* broken domain patterns that do not match anything result in an error, as expected.
* patterns `all` and `*` were tested.
* specifying `conf*` correctly enables the config domain.
* specifying `gui/*` does not enable the config domain.
* patterns containing a comma (delimiter) are handled "correctly", that is, individual components are understood and processed separately. For example, `--log-debug='gui/*,conf*'` would …
=> Generalise log domain matching rules

src/chat_events.cpp, src/chat_events.hpp, src/map_command_handler.hpp, src/menu_events.cpp, src/menu_events.hpp, src/play_controller.cpp
Also save chat messages or commands in history. Previously this was not done in #5538 because "Chat messages are not stored like this to avoid spam." but the server rejects messages if they are sent too fast anyway. So that is not a good reason IMO.
=> Leave chat open on failed command execution

data/campaigns/Northern_Rebirth/scenarios/02_01_Infested_Caves.cfg, data/campaigns/Northern_Rebirth/scenarios/03_To_the_Mines.cfg, data/campaigns/Northern_Rebirth/scenarios/06a_Old_Friend.cfg, data/campaigns/Northern_Rebirth/scenarios/08a_Elvish_Princess.cfg
Currently, carryover gold % for meeting the main objective and the alternative objective are respectively;
S2: 40%, 80%
S3: 80%, 40%
S8: 40%, 80%
because `{NEW_GOLD_CARRYOVER 40}` was added only once per scenario by b0a302b. Also, S6 lacks `[endlevel]` for meeting the alternative objective and the scenario doesn't end (although it is probably impossible anyway), but the scenario automatically ends with 80% carryover gold when all enemy leaders are killed. For the record, S10 has multiple objectives as well, but they are all 40%, so no fix seems necessary.
This PR turns all 80% into 40% and adds `[endlevel]` with 100% for the alternative objective in S6.
=> NR S2, 3, 6, 8: fix carryover gold %

data/gui/themes/default/dialogs/fps_report.cfg, data/gui/themes/default/widgets/window_debug_overlay.cfg, projectfiles/CodeBlocks/wesnoth.cbp, projectfiles/Xcode/The Battle for Wesnoth.xcodeproj/project.pbxproj, source_lists/wesnoth, src/display.cpp, src/display.hpp, src/gui/core/tracked_drawable.cpp, src/gui/core/tracked_drawable.hpp, src/gui/dialogs/fps_report.cpp, src/gui/dialogs/fps_report.hpp, src/tests/gui/test_gui2.cpp
Splits the FPS viewer out of the display class and into its own modeless dialog. This serves as a proof-of-concept for further modeless GUI in-game dialogs. Admittedly, it only works because I explicitly disconnect it from the UI event context, since it doesn't need to receive events.
This also introduces a new `tracked_drawable` interface that encapsulates the fps logic. This serves as a simple middleware for any `top_level_drawable`, and any class that inherits from it can have its render stats displayed using the new `fps_report` dialog.
=> Port FPS viewer to GUI2

data/campaigns/Heir_To_The_Throne/maps/05a_Muff_Malal_Peninsula.map, data/campaigns/Heir_To_The_Throne/scenarios/05a_Muff_Malal_Peninsula.cfg
The main objective says "Escape down the road to Elensefar". It actually means that the scenario ends when Konrad moves to (5,1), but the signpost that says "To Elensefar" is at (8,2). In S1, the signpost was the place that Konrad was supposed to go to, so it’s natural for new players to assume the same for S5a (relevant feedback posts: [2019](https://forums.wesnoth.org/viewtopic.php?p=638143#p638143), [2024](https://forums.wesnoth.org/viewtopic.php?p=689695#p689695)).
Therefore, the signpost is moved to (5,1), and it is highlighted at the start of the scenario just like S1. Also, some minor terrain changes are made so that (5,1) is the only road-like terrain at the edge of the map at y=1.
=> HttT S5a: clearer objective

data/campaigns/The_Deceivers_Gambit/lua/spellcasting.lua
Just a small PR that allows developers to put a price on spells not only in experience but also in gold. 
This new feature doesn't affect TDG in any way and isn't used by it
=> Add gold_cost for TDG's Magic System

data/campaigns/Son_Of_The_Black_Eye/scenarios/17_The_Human_Attack.cfg
Players have complained why the NA was so unaware of such a brutal war erupting in the Far North. Provided a possible reason in one message. This is a better alternative than scripting 1-2 cutscenes in between scenarios.
=> SotBE-S17: add message to event

src/config_attribute_value.cpp, src/config_attribute_value.hpp, src/filesystem.cpp, src/filesystem.hpp, src/filesystem_common.cpp, src/format_time_summary.cpp, src/format_time_summary.hpp, src/formula/string_utils.hpp, src/game_initialization/lobby_data.hpp, src/gettext.cpp, src/gettext.hpp, src/gui/dialogs/addon/manager.cpp, src/gui/widgets/debug.cpp, src/log.cpp, src/log.hpp, src/log_windows.cpp, src/reports.cpp, src/save_index.cpp, src/save_index.hpp, src/savegame.cpp, src/server/campaignd/server.cpp, src/server/wesnothd/ban.cpp, src/tests/test_formula_core.cpp, src/units/id.hpp, src/wesnoth.cpp
- Remove config_attribute_value::to_time_t (finally!)
- Add C++20 codepath for format_time_summary
- Deploy chrono::format_local_timestamp more widely, including replacing uses of translation::strftime (need to confirm this still plays nicely with translations - don't want #1709 to crop back up...)
- Clean up unnecessary includes
- Clean up uses of time_t in filesystem and save_index
- Clean up last use of ctime
- Simplify wesnothd ban duration calculations
=> Continue work on chrono cleanup

src/gui/core/event/dispatcher.cpp, src/gui/core/event/dispatcher.hpp, src/gui/dialogs/achievements_dialog.hpp, src/gui/dialogs/gui_test_dialog.hpp, src/gui/dialogs/multiplayer/lobby.cpp, src/gui/dialogs/multiplayer/lobby.hpp, src/gui/dialogs/multiplayer/mp_staging.cpp, src/gui/dialogs/title_screen.cpp, src/gui/dialogs/title_screen.hpp, src/gui/widgets/window.cpp
- Restore the is-handled callback return value (functionally reverts 8bf95ce69a9bd59d98d14653cc727368d23f75c0)
- Take hotkey callbacks by rvalue reference
- Avoid registering achievement hotkey twice
- Clean up excessive callback wrappers in the lobby and main menu
- Properly define the display function for the test and achievement dialogs
=> GUI2: hotkey registration and related callback cleanup

src/color_range.cpp, src/filesystem.cpp, src/gettext.cpp, src/gettext.hpp, src/hash.cpp, src/serialization/base64.cpp, src/serialization/base64.hpp, src/tests/test_sdl.cpp, src/tests/test_serialization.cpp, src/utils/span.hpp
Boosts the boost requirements to 1.78 so we can use boost::span as a fallback when targeting C++17 (currently the default).
Covers existing conditional uses of std::span as well as utils::byte_string_view (here renamed to byte_view). This use of std::string_view is not standard-compliant, causes build issues, and should properly be a span anyway.
Resolves #10101, resolves #9546.
=> Deployed std::span via compat wrapper

changelog.md, src/formula/function.cpp, src/tests/test_formula_function.cpp
According to [the docs](https://wiki.wesnoth.org/Wesnoth_formula_language#substring), the optional size arguments are supposed to be the number of characters to take, relative to `offset`. ~Small fix to handle multi-byte characters. Confirmed while testing a fix for #9917.~
EDIT: After discussion on discord, I decided to add a `byte_index` function instead that takes a character index and a string. It seems better to opt into multibyte handling, especially since the logic for indices is very annoying complicated...
=> WFL: add byte_index function

src/cursor.cpp, src/gui/core/event/distributor.cpp, src/gui/core/event/handler.cpp, src/gui/dialogs/end_credits.cpp, src/gui/widgets/window.cpp, src/image_modifications.hpp, src/scripting/lua_kernel_base.cpp, src/sdl/surface.cpp, src/sdl/surface.hpp, src/sdl/utils.cpp, src/sdl/utils.hpp, src/sdl/window.cpp, src/video.cpp, src/widgets/textbox.cpp
- Use a mutable span for iterating over surface pixels (convers simple cases for now)
- Use the appropriate SDL_PixelFormatEnum directly rather than getting the value from a dummy surface. Likewise, simplified the is-neutral check by checking the format type (this wasn't available in SDL 1.2 when the check was originally written)
- Remove is_neutral and make_neutral as class members. All surfaces are already converted to the neutral format internally, so we don't need these as part of the public API. Likewise, removed the only remaining external use of make_neutral in the cursor code.
- Move most function implementations out of the header and cleaned up implementation helpers. These didn't need to be class members and just made the code harder to read.
- Simplify ctor/assignment ops and …
=> SDL: surface-related cleanups

src/terrain/builder.cpp, src/terrain/translation.cpp, src/terrain/translation.hpp
The only place WILDCARD was the default was [terrain_graphics][tile]type= and this had still exceptions for * and !. Should be simpler to have this work constistently in every context.
=> Always default to NO_LAYER for the overlay

src/map/map.cpp, src/map/map.hpp
We haven't used maps with headers in years.
=> Remove old gamemap header parsing

changelog_entries/ei-fixes-and-tweaks.md, data/campaigns/Eastern_Invasion/achievements.cfg, data/campaigns/Eastern_Invasion/scenarios/01_Eastern_Invasion.cfg, data/campaigns/Eastern_Invasion/scenarios/05_Northern_Outpost.cfg, data/campaigns/Eastern_Invasion/scenarios/09_Castle_in_the_Ice.cfg, data/campaigns/Eastern_Invasion/scenarios/10_Dark_Sanctuary.cfg, data/campaigns/Eastern_Invasion/scenarios/15_Return_to_Wesnoth.cfg
Things that've been on my list for a while, to do before 1.20:
- S01: initial objective text now includes the 10,15 trapdoor
- S05: added objective note explaining how to check for bandits
- S05: fix Gweddry or Owaec not getting XP if they personally kill the final enemy leader
- S09: cold damage now starts lower, but grows faster
- S09: drakes no longer avoid the objective area after the guarding icemonax are cleared
- S10: replaced wild Wyvern with a more climate-appropriate Yeti
- S15: Gweddry and co. now enter Weldyn through a tunnel, instead of effortlessly penetrating the undead siege
- achievements: use white teamcolor instead of magenta for S10's achievement
=> EI: some assorted fixes and tweaks

changelog.md, src/sdl/utils.cpp
Resolves #8785. Diff best viewed with whitespace changes hidden. Functions affected:
- `adjust_surface_color`
- `greyscale_image`
- `monochrome_image`
- `sepia_image`
- `negative_image`
- `shadow_image`
- `swap_channels_image`
- `recolor_image`
- `brighten_image`
- `adjust_surface_alpha_add`
- `light_surface`
=> Don't skip fully transparent pixels when recoloring surfaces

src/gui/widgets/unit_preview_pane.cpp, src/gui/widgets/unit_preview_pane.hpp, src/help/help_topic_generators.cpp, src/reports.cpp
Resolves #10108.
Unit List (should be similar in Recall)
Unit Create Dialog (should be same in recruit)
Help page for Unit Type (cannot show remaining attack because it's the Unit Type's help, and not the Unit's)
=> show max_attacks/attack usage in Help and Units dialog

changelog_entries/necromancer-more-plague.md, data/core/units/undead/Necromancer.cfg
The 1.18 Necromancer is in an odd spot. His/her damage is very similar to the Lich, but inferior to both the Enchantress and Arch Mage (and MoL, if we factor in Illuminates). But unlike every other mage, the Necromancer boasts a whopping 76 hp and 10% impact resistance.
These stats (more hp than a Royal Guard!?) point the Necromancer towards a front-line tank/shock trooper role. I get that this is reasonable for balance - undead don't have good impact-resistant tanks - but I also feel that using Necromancers as meatshields runs contrary to the unit fantasy.
This PR lowers the Necro's durability closer to that of the other mages, while instead emphasizing his/her thematic plague ability:
- hitpoints 76 -> 62, impact resist 10% -> 0%
- plague staff (melee impact) 6-3 -> 8-3
- chill wave …
=> Necromancer: emphasize plague, reduce durability

src/network_download_file.cpp
Needs to be back-ported to 1.18 as well.
=> Network: Correct curl protocol configuration (resolves #10139)

src/font/text.cpp, src/font/text.hpp, src/gui/widgets/label.cpp, src/gui/widgets/rich_label.hpp, src/gui/widgets/styled_widget.cpp, src/gui/widgets/styled_widget.hpp
Also fixes non-left aligned inline links having wrong link click bounds. (resolves #8915)
Note: I came upon the solution accidentally while doing some cleanup. Fix is:
https://github.com/wesnoth/wesnoth/blob/4976f0a3f8cb6d5d10f608fbcb220fa36cabffce/src/gui/widgets/styled_widget.cpp#L560-L567
=> label inline link mechanism code simplification

src/display.cpp
This was an attempt at an optimization in line with the image vector class member, but it wasn't backed up by profiling. Better to optimize later if it's found to be needed.
=> Don't keep a static light adjust list

src/font/attributes.cpp, src/font/text.cpp
Without this, the inline images in help browser appear unscaled for pixel scale > 1. (smaller images with respect to text)
Tested with virtual scaling 2x. (My monitor is low res)
=> help: correct inline image size for scaling > 1

src/editor/controller/editor_controller.cpp, src/help/help.cpp, src/help/help.hpp, src/reports.cpp
Follow-up to https://github.com/wesnoth/wesnoth/commit/53b08325e7729397859b476dcd8c306aa514cb27 and https://github.com/wesnoth/wesnoth/commit/81a7ba55dfb0771e1e03110eb69c040849ef7de5, separates out the help topic id generation logic from `help::show_unit_description()` so it can also be used in `reports.cpp`.
Also includes some cleanup and collapses one-use small methods
=> help: separate unit help page id generation logic

src/picture.cpp
Supersedes and closes #10154. Confirmed this fixes at least one issue with ToD borders I noticed when testing with EI S2.
After giving the problem more thought, I decided to just let boost handle the actual has implementation instead of trying to come up with a suitable one myself. This is consistent with the `image::locator` hash which also uses `boost::hash_combine`.
I considered the feedback that suggests using the vector directly as a map key and relying on lexicographical comparison for cache lookup. That would require using a plain map instead of an unordered_map. As long as the cache uses an unordered map, a hash needs to come from *somewhere*, and using the span view (or even the vector itself) as a key would require specializing a range hash object. `boost::hash_range` provides a …
=> Use boost to hash lightmap range

CMakeLists.txt, src/CMakeLists.txt
A fresh build on Manjaro Linux fails due to not including Boost::CharConv in the CMake build scripts. Adding the following patch fixes the issue.
=> Fixed CMake build failure due to dependency on Boost CharConv

src/editor/controller/editor_controller.cpp, src/help/help.cpp, src/help/help.hpp, src/reports.cpp
Backport of 53b08325e7729397859b476dcd8c306aa514cb27, 81a7ba55dfb0771e1e03110eb69c040849ef7de5 and 8a2515d428393012ec5562a7ec29fb24a5a6b1c9, with 1.18 specific adjustments. (The second commit was small so it was squished into the preceding one)
=> [1.18] Help topic logic improvement

.gitignore
- Creates itself on latest master for some reason.
=> Update .gitignore to ignore the LOCAL_APPDATA_FONTCONFIG_CACHE directory

src/display.cpp, src/picture.cpp, src/picture.hpp
Apparently, using a hash could lead to potential collisions and the wrong surface being pulled.
=> Store lightmap data keys explicitly

SConstruct
Only 1.19 has all the required changes for c++20, #10146
Options are cached, removing the option makes sure that it is not accidentally enabled after switching from the master branch.
=> scons: remove option to use c++20 on 1.18 branch

src/filesystem.cpp, src/filesystem.hpp, src/gui/dialogs/editor/custom_tod.cpp, src/gui/dialogs/editor/edit_unit.cpp, src/tests/test_filesystem.cpp
Uses `boost::filesystem::path` and the `filesystem::is_prefix` method to improve the `filesystem::to_asset_path` method, hopefully improving cross-platform compatibility.
Resolves #9579
=> filesystem: simplify to_asset_path

CMakeLists.txt, SConstruct, packaging/flatpak/org.wesnoth.Wesnoth.json, src/filesystem.cpp, src/game_launcher.cpp, utils/dockerbuilds/CI/Dockerfile-base-steamrt
Resolves #10174. There doesn't seem to be a straight replacement for `process::process_error`, so I'm just going for a catch all `std::exception`.
=> Use boost::process::v2 on 1.86 and later

src/server/common/simple_wml.cpp, src/server/common/simple_wml.hpp
Added in 2f95e5b43d47bebed3fdf636e867ea7458a56f94 and unchanged since. Was unused then, unused now, doesn't actually seem to insert anything, and is an infinite loop.
=> Simple WML: remove unused function with infinite loop

src/server/wesnothd/player.hpp, src/server/wesnothd/player_connection.hpp, src/server/wesnothd/server.cpp
- Use emplace when adding entry to player_connections_
- Remove const members from `player` to allow implicit move ctor to work
- Take `player` by rvalue reference in `player_record`
=> Wesnothd: avoid unnecessary copy of new player object

src/gui/dialogs/network_transmission.cpp, src/gui/dialogs/network_transmission.hpp
- Remove unnecessary invalidate_layout call
- Fix progress bar sometimes not filling up when completed
- Allow final progress stage to display
- Use a pointer instead of optional_reference
=> GUI2/Network Transmission: refinements

src/ai/lua/core.cpp, src/server/common/server_base.cpp, src/server/common/server_base.hpp, src/server/wesnothd/server.cpp, src/units/filter.cpp, src/units/filter.hpp
Specifically, this redeclares some parameters as const references when those parameters are only used in a const way. It also removes std::move from being used on those parameters as you cannot move a const ref. Finally, it also adds std::move when necessary.
I'm not sure why these got missed but they appear as errors on my own machine.
=> Fix some linter issues relating to move/const refs

changelog.md, data/gui/themes/default/dialogs/units_dialog.cfg, src/gui/dialogs/units_dialog.cpp, src/gui/dialogs/units_dialog.hpp, src/units/unit.cpp, src/units/unit.hpp
Resolves #7733
Adds a new button to the Units List and Recall dialog using which units can be marked as favorite. Favorite unis are shown (for now) with a white filled star in the leading column, while rest are shown with unfilled white star.
=> Units Dialog: support marking units as favorite

data/test/scenarios/wml_tests/UnitsWML/AbilitiesWML/poison_id_no_work.cfg, src/units/attack_type.cpp, src/units/attack_type.hpp, wml_test_schedule
Fix https://github.com/wesnoth/wesnoth/issues/10225 issue. if for example, someone has fun giving a special [chance_to_hit] an id=poison, then the target will be poisoned once hit, this PR solves this problem
=> fix id=poison can poison opponent same if in another type of special

src/utils/charconv.hpp
boost::charconv::from_chars with integers is broken on boost 1.85 (fixed in boost 1.86)
however for the floating point variants we still need boost on some compilers since those are sometimes missing/incomplete on std
=> use std::from_chars for the integer variants (issue #10009)

data/test/scenarios/manual_tests/scenario-test.cfg, src/xBRZ/xbrz.cpp
Instead of type-punning to smaller struct, just pas the const-ref to the larger one. The functions are intended to be inlined anyway.
=> Fix strict aliasing by not type-punning

src/units/types.cpp, src/units/types.hpp
#10053 inadvertently added a variable which copied a unit_type. This would have been caught had the copy ctor been deleted 
(as copy assignment already is). Since these aren't objects we'll be passing around, better to delete both to catch such cases in future. Ironically, the only place that actually used the unit_type copy ctor was the unit_type copy ctor itself (and the code for copying the gender variations looks broken anyway - it was checking whether the wrong variable was non-null!)
Also added a default definition of the move assignment operator (we already had a move ctor), and deleted the default ctor (unimplemented) ~~and dtor (empty~~).
=> Unit Type: delete copy, default ctors

src/scripting/game_lua_kernel.cpp
Backport of 1d039c395dc44b93e9c22424cf976f0740284897 (#10258).
Resolves #10098 for 1.18.
=> [1.18] Floating label replace fix backport

changelog.md, data/schema/core/addons.cfg, src/game_initialization/connect_engine.cpp
See #3177, resolves #7753. Adds an `auto_sort` key to [era] which, if false (default true), will use the [multiplayer_side] order as given in the config.
@ProditorMagnus is this acceptable?
=> MP/Connect Engine: add ability to disable faction sorting

src/hotkey/hotkey_handler.cpp, src/hotkey/hotkey_handler.hpp
Instead of constructing an intermediate list whose special members (wml items, autosaves, etc) are then expanded, simply append the expanded items on the initial pass.
Also optimizes the case where a large number of configs would be constructed for long games, only to be pruned.
=> Hotkey/Handler: optimize menu list generation

data/campaigns/Secrets_of_the_Ancients/utils/sota-utils.cfg
Closes #10299
I can see how this was missed in #5189 but I don't (yet) see the error message logged in #10299. 1.18 is also affected so it could be back-ported.
=> SotA: Update terrain

data/gui/themes/default/dialogs/editor_edit_side.cfg, src/ai/default/ca.cpp, src/ai/lua/engine_lua.cpp, src/editor/map/map_context.cpp, src/gui/dialogs/gamestate_inspector.cpp, src/team.cpp, src/team.hpp, src/terrain/filter.cpp
Resolves #10123
Reasoning given in https://github.com/wesnoth/wesnoth/issues/10123#issuecomment-2991271494, quoted here:
> 
> This is where the `+2` comes from:
> https://github.com/wesnoth/wesnoth/blob/a1d3e10e75b6695dc8466360168525a1bb47d743/src/team.hpp#L183
> 
> (game's base income is `2`, which gets added to the value loaded from the file)
> 
> `base_income()`'s retval is used for the `editor_team_info` constructor here:
> https://github.com/wesnoth/wesnoth/blob/a1d3e10e75b6695dc8466360168525a1bb47d743/src/editor/map/map_context.cpp#L46
> 
> Which in turn gets used in the Edit Side dialog, so when you save it it's income from saved scenario file + base income of game.
=> Editor/Edit Side: don't add/write game default base_income

src/game_events/wmi_manager.cpp, src/hotkey/command_executor.cpp
This includes a fix for #10270 which is required to implement #7948. I'm happy to commit the fix separately, but I'm putting them together for convenience, since I'd like feedback on both.
=> Allow var substitution for wml menu items at invocation time

.github/workflows/ci-main.yml
GitHub says Windows 2019 is no longer used and suggests to use Windows 2022 or 2025. master already does this via Windows 'latest'.
=> CI: Update Windows image

data/campaigns/Heir_To_The_Throne/scenarios/19c_Cliffs_of_Thoria.cfg
The initial objective says "Make it to the end of the river," and because gohere.png image is placed at (55,3), it's natural to assume that it is the place to go to. However, any hex within (53-55,1-5) meets the objective. Although meeting the initial objective doesn't end the scenario and only changes it to "Move Konrad to the cave," visual markers should match the actual objective. Therefore, the hex to meet the initial objective is limited to (55,3).
=> HttT S19c: clearer objective

data/gui/themes/default/dialogs/mp_faction_select.cfg, data/schema/core/addons.cfg, data/schema/game_config.cfg, src/game_initialization/connect_engine.cpp, src/game_initialization/connect_engine.hpp, src/game_initialization/flg_manager.cpp, src/game_initialization/flg_manager.hpp, src/gui/dialogs/multiplayer/faction_select.cpp, src/gui/dialogs/multiplayer/mp_join_game.cpp, src/tests/gui/test_gui2.cpp
Resolves #10338. Sorting is no longer done internally on the host, but is now a purely cosmetic operation for anyone selecting a faction. [era] auto_sort has been upgraded from a bool to now accept "none", "ascending", or "descending".
=> MP/Faction Select: add listbox sorter for faction names

changelog.md, data/core/hotkeys.cfg, data/schema/core/config.cfg, src/controller_base.cpp, src/hotkey/hotkey_command.cpp, src/hotkey/hotkey_item.cpp, src/hotkey/hotkey_item.hpp, src/mouse_events.cpp
Touch behavior changes:
* Double tap no longer shows context menu. It can still be accessed via long press.
* Single tap selects the unit. Another single tap on a hex shows hover info, which was previously not available.
* Single tap select followed by double tap on a hex moves the unit.
* Dragging now properly indicates the path and defense.
Also:
* mouse [hotkey]-s now support specifying the number of clicks.
* user visible mouse [hotkey] names (in Hotkey Preferences) are improved and will show number of clicks when >1. (i.e., left mouse instead of mouse 1)
* fixes long press delay accidentally being zero.
=> GUI/Events: Touch: double tap movement/single tap select

src/server/common/dbconn.cpp, src/server/common/dbconn.hpp, src/server/wesnothd/server.cpp
time_t ends up being a long while we only have if-blocks for int and unsigned long long. so the parameter doesn't get set at all, and somehow mariadbpp runs the query without all the required parameters being set.
=> Fix non-permanent bans not actually working

src/gui/widgets/text_box_base.cpp
~~This reverts commit e503658256fa4ab07d9a7fbbc5bb2cb353638585.~~
Fixes https://github.com/wesnoth/wesnoth/issues/10361 issue by adding `ifdef` guard around `SDL_Start/StopTextInput()` introduced in e503658256fa4ab07d9a7fbbc5bb2cb353638585.
=> Fix command line and some keyboard shortcuts no longer work

src/units/abilities.cpp, src/units/filter.cpp
Fix https://github.com/wesnoth/wesnoth/issues/10364 issue
When a unit with the halo_image attribute [affect_adjacent] but with affect_self=no moves, it is likely to be illuminated by this halo, as it finds itself next to a temporary unit that is almost identical except for its location. This requires slightly complicating the verification with id if a simple comparison of unit is not sufficient.
same for [filter_adjacent] and [filter], if a unit with hides ability is invisible only when another unit of same race is adjacent, when unitmoves, it is 'hidden' because' adjacent to itself.
=> Fix halo and hides display bug in abilities

src/about.cpp, src/carryover.cpp, src/config.cpp, src/display.cpp, src/formula/function_gamestate.cpp, src/game_initialization/flg_manager.cpp, src/game_initialization/singleplayer.cpp, src/gui/dialogs/addon/manager.cpp, src/gui/dialogs/multiplayer/mp_create_game.cpp, src/gui/dialogs/title_screen.cpp, src/gui/gui.cpp, src/gui/widgets/addon_list.cpp, src/gui/widgets/chatbox.cpp, src/gui/widgets/chatbox.hpp, src/gui/widgets/tree_view.cpp, src/gui/widgets/tree_view.hpp, src/menu_events.cpp, src/recall_list_manager.cpp, src/scripting/game_lua_kernel.cpp, src/serialization/schema_validator.cpp, src/sound.cpp, src/tests/utils/game_config_manager_tests.cpp, src/utils/general.hpp, src/variable.cpp
This adds a new `utils::ranges::find` helper function modeled after C++20's `ranges::find`. Unlike the latter, it only accepts lvalue references (you can't have a "borrowed range"), but for most cases the syntax is equivalent to `ranges::find`. The most useful part is the projection argument, which significantly simplifies existing uses of `std::find_if`. The C++20 version proper should be a drop-in replacement once we bump our minimums.
=> Add util for container lookup with projections

data/core/units/merfolk/Diviner.cfg
* Avoids slightly awkward phrasing. (`that` followed by `the`.)
* Improve sentence flow.
* Add `almost slain` instead of slain and delete `in full number`. If they were dead, they can't fight back next day in full number without necromancy. This makes it sound more realistic without changing the story too much.
=> Merfolk Diviner: slightly adjust description.

src/video.cpp
This also prevents a divide-by-zero crash in `sdl::get_mouse_state()` if the `active_view`'s origin is at (0, 0).
=> Change mistaken call to active_view::origin back to active_view::size

data/core/units/monsters/Skeletal_Dragon.cfg
> Not centered but it should use image_icon or similar. (#10391)
We could use a different cropping for the image_icon. Cropped in a way that one doesn't see the wings, with 72x72. Merging?
It's cropped to 72x72, but the attack dialogue will use 144x144.
=> Skeletal Dragon image_icon

packaging/android/app/build.gradle, packaging/android/app/src/main/java/org/wesnoth/Wesnoth/IOUtils.java, packaging/android/app/src/main/java/org/wesnoth/Wesnoth/InitActivity.java, packaging/android/app/src/main/res/menu/main_menu.xml
Adds a new menu item to the setting menu in the Android splash screen/launcher activity that allows import/export of Wesnoth userdata folders.
TODO
~~- [ ] Custom userdata folder~~ (Will attempt in a future PR if possible)
=> Android/InitActivity: add userdata import/export functionality (#10326)

changelog.md, src/scripting/lua_widget_attributes.cpp, utils/emmylua/gui.lua
Adds a new `on_double_click` function to toggle panels that get called when the user left double clicks on it. For other widgets, they can be wrapped inside a `[toggle_panel]` to add double click handlers, because the C++ dbl click handler supports only `[toggle_panel]`-s.
=> lua api: add double click event handler

boost_test_schedule, src/addon/manager_ui.cpp, src/config_cache.cpp, src/config_cache.hpp, src/editor/map/map_context.cpp, src/game_config_manager.cpp, src/gui/gui.cpp, src/scripting/lua_wml.cpp, src/serialization/preprocessor.cpp, src/serialization/preprocessor.hpp, src/serialization/tokenizer.hpp, src/tests/gui/test_gui2.cpp, src/tests/test_config_cache.cpp, src/tests/test_filesystem.cpp, src/tests/utils/game_config_manager_tests.cpp, src/tests/wml/schema/test_schema_validator.cpp, src/wesnoth.cpp
- Prefer return values over input parameters in the config cache. The test_non_clean_config_loading test has likewise been removed since `config_cache::get_config` no longer takes an input parameter.
- Remove unnecessary default ctors or use defaulted ones
- Use in-place construction for preproc_defines. Especially no need to create default objects only to assign them to default objects.) Subscript lookup for define maps has been replaced either with try_emplace or insert_or_assign`.
- Slightly optimize `preproc_define` size (saves 8 bytes)
- Replace `preproc_define::read_pair` with a new in-place construction helper (`preproc_define::insert`).
- ~Optimize `config_cache::transaction::add_defines_map_diff`. Remove an unnecessary copy by erasing duplicates from the input map before copying …
=> Reduce copying of preproc_define and tidy up config cache

src/units/abilities.cpp, src/units/attack_type.hpp
Now that support for Boolean specials is separated from filtering, it would be better if the checks for self_ and other_ were handled by a single function instead of copying the code for each of them to simplify the writing. Hence, the use of two functions: one for handling Boolean specials, which will be called twice, and one for the filter functions, which will be called four times in total.
the two first commit are the same what https://github.com/wesnoth/wesnoth/pull/10426
=> Regroup the checks for abilities used as weapons into two separate functions.

boost_test_schedule, src/scripting/lua_ptr.hpp, src/tests/test_lua_ptr.cpp
The move assignment didn't return a value, however it was also unused, GCC started giving warnings when the test was changed to use it.
Thanks to Nanamuru for finding this, it's one of the bugs found by static analysis and reported in #10386.
@gfgtdf I'm opening this as a draft, because I've added comments about what I think this code does, but I'd like your confirmation that I've understood it correctly.
=> Fix move behavior of enable_lua_ptr<T>

src/config_cache.cpp, src/editor/map/map_context.cpp, src/gui/dialogs/editor/edit_unit.cpp, src/gui/gui.cpp, src/scripting/lua_wml.cpp, src/serialization/preprocessor.cpp, src/serialization/preprocessor.hpp, src/serialization/schema_validator.cpp, src/tests/utils/wml_equivalence.cpp, src/tests/utils/wml_equivalence.hpp, src/tests/wml/schema/test_schema_validator.cpp, src/wesnoth.cpp
- Add preprocess_file and preprocess_string overloads taking a preproc_map reference instead of a defaulted pointer argument. No longer need to take the address of every defines map we pass in.
- Make preprocess_string return the stream to match preprocess_file
- Remove unused `default_defines_` member from from preprocessor_streambuf. Was added all the way back in 1e32e22ca9ba4f4be8726b908a76bdda4ba5f688 to serve as a local fallback for the defines pointer, but that functionality has long since been relegated to preprocessor_scope_helper (now called preprocessor_istream)
- Store defines as a reference in preprocessor_streambuf, since we know it's always valid.
- Use rdbuf over `std::ios::init` and remove a comment I added years ago which now proved to be incorrect.
- Expand …
=> Preprocessor: clean up preproc_map input handling

src/gui/core/canvas.cpp, src/gui/core/canvas_private.hpp
This was triggering for a broken Data URI in the list of add-ons, which declares itself as image/png but the data is image/webp. The whole Data URI was getting logged on every draw() call.
For formulas, this means that only the first failing filename or data URI will be reported, even if the formula changes to a different image. It seems unnecessary to add more logic; if the person who sees the log is the person who can fix the problem, then they're likely to either see a common pattern in a set of broken filenames, or to keep testing until everything is fixed.
Note: when testing this on the 1.19 add-ons server, you'll currently see two logs, which look like the same error. It's because Town of Arnsreach has a separate Resources add-on, and there's one log for each.
=> Log at most one "image won't be drawn" error per canvas

src/game_launcher.cpp, src/game_launcher.hpp, src/gui/dialogs/game_load.cpp, src/gui/dialogs/game_load.hpp, src/gui/dialogs/multiplayer/mp_create_game.cpp, src/gui/dialogs/title_screen.cpp, src/gui/dialogs/title_screen.hpp, src/hotkey/hotkey_handler.cpp, src/hotkey/hotkey_handler_sp.cpp, src/play_controller.cpp, src/saved_game.cpp, src/saved_game.hpp, src/savegame.cpp, src/savegame.hpp, src/tests/gui/test_gui2.cpp, src/wesnoth.cpp
While working on #10451, I noticed that errors for saves weren't being displayed in-game. That was because b007b5a8d09980e10c5e7192f5620319e0d88edf made it so we checked the save index for save validity in order to avoid loading the actual save file twice - once to validate it before load_game_exception was thrown and once in the titlescreen loop to actually load the damn thing.
All in-game loading (autosaves and interactive) now reads the save file to check its validity and surface any errors *before* throwing load_game_exception. The load_game_metadata  payload is likewise now expected to contain the parsed save config. The autosave loader path has been adjusted to pass the loaded payload along with its exception. (Thankfully, gfgtdf's work already made this trivial.) Conversely, the …
=> Simplify and consolidate save loading paths

src/addon/client.cpp, src/addon/info.cpp, src/gui/dialogs/addon/manager.cpp, src/gui/widgets/addon_list.cpp, src/gui/widgets/addon_list.hpp
Resolves #10466
The issue is caused by duplicate escaping in `addon_info::display_title`, which gets escaped again in the addon client (`client.cpp`).
=> Addon Info: remove extra escaping

changelog_entries/other_version_savefiles.md, src/filesystem.cpp
If there are save directories for other versions of Wesnoth, there's a drop-down list in the Load Game dialog to see those other directories.
This adapts 1.18 for commit 80fe9ba84ddb507f0212c445e4af9bb163e94bb3, so that 1.18 will see the save directory of 1.19.2 onwards.
Previously, 1.18 would show the directory that 1.19.0 and 1.19.1 used.
I'm planning to forward-port this as-is to 1.19, I think the technical debt of hardcoding the directory name "sync" in this place is balanced by this being a place where some cross-version debt is to be expected.
=> [1.18] Make the Load Game dialog see other-version save files from 1.19

src/gui/dialogs/units_dialog.cpp
Resolves #10480
In Units Dialog (Recall), changes primary sort order to experience required to reach next level, secondary sort is by max experience.
=> Units Dialog (Recall): sort by experience to next level

src/replay_helper.cpp, src/replay_helper.hpp, src/synced_commands.cpp
the old code tried to prevent the creation of a dummy undo stack entry for toggling shroud updated if there are no elements in te undo stack before. However the old way of doing this resulted in the action being removed from the replay recorder aswell , leading to OOS.
Now we just always block undo in this case.
The optional paramter in get_auto_shroud does in theory allow us to make it undoable again later in a save way.
=>  fix #10496 OOS when using DSU

src/gui/dialogs/help_browser.cpp
Resolves #8853
For hidden topics, there may not be a corresponding `tree_view_node`, so makes corresponding checks optional.
=> Help hidden topic improvement

src/floating_label.cpp
Also revert the original change in 81f916d and only remove trailing newlines from tooltips as intended.
=> Revert behavior change from 3cc3c75

data/core/units/undead/Skele_Bone_Knight.cfg
Ideally both descriptions should be different, but two slightly different words between these are unnecessary and it feels like one may have been updated without updating the other at some point.
=> Remove unnecessary differences between Bone Knight and Skeleton Rider unit descriptions

src/gui/dialogs/help_browser.cpp, src/serialization/markup.cpp, src/serialization/markup.hpp, src/serialization/unicode.cpp, src/serialization/unicode.hpp
Resolves #4590 (Help browser can already deal with `&amp;`, and shows error messages in the page if invalid.)
Adds Line/Character position info in Help Markup Parser errors.
Source:
```ini
[topic]
id=..introduction
title= _ "Introduction"
text="<img src='misc/logo-bg.png~BLIT(misc/logo.png)' float='yes' align='center'/><clear/>" + _ "
<i>Battle for Wesnoth</i> is a turn-based fantasy strategy game somewhat unusual among modern strategy games. While other games strive for complexity, <i>Battle for Wesnoth</i> strives for simplicity of both rules and gameplay. This does not make the game simple, however — from these simple rules arises a wealth of strategy, making the game easy to learn but a challenge to master.
The following pages outline &all you need to know to play Wesnoth. As you …
```
=> Help: Add positioning info to parse errors

changelog_entries/wilderlands_lag.md, data/multiplayer/scenarios/5p_The_Wilderlands.cfg
The filter on the unit_placed event didn't check if the unit was already loyal, and after 4 turns, the first unit belonging to side 5 had over 600 of these [object]s.
The objects aren't needed at all, side 5's units are loyal anyway.
Fixes #10419
=> MP: Fix lag during AI turns on 5P The Wilderlands

src/config_attribute_value.hpp, src/preferences/preferences.cpp, src/scripting/application_lua_kernel.cpp, src/tests/test_config.cpp
Also fixes comparison with std::string_view on the legacy codepath
=> Config Attribute Value: compare string-like types directly, remove heterogenous comparison for integers

src/config_attribute_value.hpp, src/tests/test_config.cpp
Expecting these to initially fail on C++17.
=> Add tests for reversed-order config heterogenous comparison

data/test/scenarios/manual_tests/scenario-test.cfg
Weapon specials can have location filters, even if they're applied directly to the weapon rather than being used like abilities. This gives the Shyde a special which should be shown as inactive except when moving to or attacking from a forest hex.
Currently (commit ee7f4c047a4) the sidebar always shows it as active, because the sidebar uses a weapon context that doesn't know which hex it should be used in.
=> Test scenario: Give the Shyde a new slows that only works in forest

src/scripting/lua_terrainfilter.cpp, src/server/wesnothd/server.cpp, src/theme.cpp, src/units/animation.cpp
Toward #10427. I decided to go with utils::from_chars as a replacement and keep the same fallback to 0 in case of errors (`atoi` returns 0 on error). I left the instances in attack_prediction.cpp (commented out ancient benchmarking code, should really just be removed) and `simple_wml::string_span::to_int()` (already full of C-isms, makes sense to keep for now).
=> Remove most uses of atoi

src/ai/composite/value_translator.hpp
=> ai: don't use lexical_cast to write configs

data/core/units/boats/Canoe.cfg, data/core/units/boats/Carrack_Merchant.cfg, data/core/units/boats/Carrack_Pirate.cfg, data/core/units/boats/Derelict_Ship.cfg, data/core/units/boats/Elf_Cutter.cfg, data/core/units/boats/Elf_Sloop.cfg, data/core/units/boats/Fireship.cfg, data/core/units/boats/Ghost_Ship.cfg, data/core/units/boats/Orc_Barge.cfg, data/core/units/boats/Orc_Battle-Barge.cfg, data/core/units/boats/Orc_Rigship.cfg, data/core/units/boats/Orc_Warship.cfg, data/core/units/boats/Raft.cfg, data/core/units/boats/Raider_Coastal.cfg, data/core/units/boats/Raider_Iron.cfg, data/core/units/boats/Skiff.cfg
Once/if #10576 is merged, ships will have 0% defense on land.
When ships are on land (usually only possible via a coastal village), this PR replaces their usual bobbing [standing_anim] with a more stationary one.
=> Ships: don't bob while beached
